In [1]:
import os

import pandas as pd

In [2]:
df = pd.read_parquet(os.path.join("data", "cnb_vyber.parquet"))

In [3]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 500)

In [4]:
df[df["245_a"].astype(str).str.contains("Nápady čtenáře detektivek", na=False)]

KeyboardInterrupt

In [ ]:
df[df["830_a"].astype(str).str.contains("Otázky a názory", na=False)]

In [ ]:
df[df["245_a"].astype(str).str.contains("Jak s tím pohnu", na=False)]

In [ ]:
df[
    df["830_a"].astype(str).str.contains("Krystal", na=False)
    & df["830_a"].astype(str).str.contains("dětské knihy", na=False)
]

In [ ]:
df[df["490_a"].astype(str).str.contains("Krystal", na=False)]

In [ ]:
df[df["100_a"].astype(str).str.contains("Houška, Vítězslav", na=False)]

In [ ]:
df[df["245_a"].astype(str).str.contains("Naši savci", na=False)]

In [ ]:
df[
    df["830_a"].astype(str).str.contains("Oko", na=False)
    & df["830_a"].astype(str).str.contains("Albatros", na=False)
]

In [ ]:
df[df["245_a"].astype(str).str.contains("Každému chléb", na=False)]

In [ ]:
df[df["830_a"].astype(str).str.contains("Dobrý vítr", na=False)]

In [11]:
df[df["100_a"].astype(str).str.contains("Richta, Radov", na=False)]

,008,020_a,020_c,020_q,041_a,041_h,041_ind1,044_a,072_a,072_x,080_a,100_4,100_7,100_a,100_d,240_l,245_a,245_c,245_n,245_p,246_a,250_a,250_b,260_a,260_b,260_c,260_e,260_f,260_ind1,264_a,264_b,264_c,264_ind2,300_a,300_b,300_c,490_a,490_v,500_a,520_a,520_b,521_a,546_a,648_a,650_a,650_x,650_y,650_z,651_a,653_a,655_a,700_4,700_7,700_a,700_d,710_4,710_7,710_a,710_b,830_a,928_a,964_a,leader
001,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
bk196401074,970920s1963 xr e 00| 0 cze,None,None,[(Brož.)],None,None,None,None,[316.3],[Globální společnosti. Sociální struktura. Soc...,"[316.323.72, 316.3, (041)]",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Komunismus a proměny lidského života :],[Radovan Richta],None,None,None,None,None,[Praha :],[Čs. společnost pro šíření politických a vědec...,[1963],None,None,None,None,None,None,None,[54 s. ;],None,[21 cm],None,None,"[5000 výt., Pozn., Pro potřeby lektorů Čs. spo...",None,None,None,None,None,"[komunismus, společnost]",None,None,None,None,None,[brožury],None,None,None,None,None,None,None,None,None,None,[Komunismus - proměny společenské - materiály],nam a22 1 4500
bk196401170,970923s1963 xr g 000 0 cze,None,None,[(Brož.)],None,None,None,None,[62],[Technika všeobecně],"[62:316.3, 001.102, (041)]",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Člověk a technika v revoluci našich dnů /],[Radovan Richta],None,None,None,None,None,[Praha :],[Čs. společnost pro šíření politických a vědec...,[1963],None,None,None,None,None,None,None,[85 s. ;],None,[21 cm],None,None,"[5000 výt., Pro potř. lektorů Čs. společ. PVZ]",None,None,None,None,None,"[vědeckotechnické informace, technika a společ...",None,None,None,None,None,[brožury],None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - povaha a význam s...,nam a22 1 4500
bk196505047a,971213s1966 xr a e 000 0 cze,None,None,[(Brož.)],None,None,None,None,[316.4],[Sociální procesy],"[316.7+008, 62:001.892, 001.83, 316.42, 001:31...",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Civilizace na rozcestí :],[Radovan Richta a kolektiv ; [předml. F. Šorm]],None,None,None,[1. vyd.],None,[Praha :],"[Svoboda,]",[1966],None,[(Rudé právo)],None,None,None,None,None,"[236, [20] s. :]",[tb. ;],[8°],None,None,[Obálku navrhl a graficky upravil Václav Kučer...,[Úvahy objasňují komplexně a synteticky vědeck...,None,None,None,[20. století],"[civilizace, vědecko-technický rozvoj, sociáln...","[None, interdisciplinární aspekty, None, None]","[20. století, None, 20. století, 20. století]",None,None,None,[kolektivní monografie],[aui],None,"[Šorm, F.]",None,None,None,None,None,None,None,[Revoluce vědeckotechnická - rozbory marxistické],nam a22 1 4500
bk196700715,970714s1967 xr a e 000 0 cze,None,None,None,None,None,None,None,[316.4],[Sociální procesy],"[316.7+008, 62:001.892, 001.83, 316.42, 001:31...",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Civilizace na rozcestí :],[Radovan Richta a kolektiv ; [předml. F. Šorm]],None,None,None,[2. vyd.],None,[Praha :],"[Svoboda,]",[1967],None,[(Rudé právo)],None,None,None,None,None,"[236, [20] s. :]",[tb. ;],[8°],None,None,"[Souběž. rus., angl., něm. a franc. obsah, Poz...",None,None,None,None,[20. století],"[civilizace, vědecko-technický rozvoj, sociáln...","[None, interdisciplinární aspekty, None, None]","[20. století, None, 20. století, 20. století]",None,None,None,[kolektivní monografie],[aui],None,"[Šorm, F.]",None,None,None,None,None,None,None,[Revoluce vědeckotechnická - rozbory marxistické],nam a22 1 4500
bk196902469,971111s1969 xr e 000 0 cze,None,"[Kčs 33,00]",[(Váz.) :],None,None,None,None,[316.4],[Sociální procesy],"[316.7+008, 62:001.892, 001.83, 316.42, 001:31...",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Civilizace na rozcestí :],[Radovan Richta a kolektiv ; [předml. F. Šorm]],None,None,None,"[3., rozš. vyd.]",None,[Praha :],"[Svoboda,]",[1969],None,[(Rudé právo)],None,None,None,None,None,"[412, [5] s. :]",[tb. ;],[8°],None,None,"[Obálka a vazbu navrhl Václav Kučera, 20000 vý...",[Nové vydání kolektivního díla objasňujícího k...,None,None,None,[20. století],"[civilizace, vědecko-technický rozvoj, sociáln...","[None, interdisciplinární aspekty, None, None]","[20. století, None, 20. století, 20. století]",None,None,None,[kolektivní monografie],None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - rozbory marxistické],nam a22 1 4500

In [13]:
df[df["964_a"].astype(str).str.contains("Revoluce vědeckotechnická", na=False)]

,008,020_a,020_c,020_q,041_a,041_h,041_ind1,044_a,072_a,072_x,080_a,100_4,100_7,100_a,100_d,240_l,245_a,245_c,245_n,245_p,246_a,250_a,250_b,260_a,260_b,260_c,260_e,260_f,260_ind1,264_a,264_b,264_c,264_ind2,300_a,300_b,300_c,490_a,490_v,500_a,520_a,520_b,521_a,546_a,648_a,650_a,650_x,650_y,650_z,651_a,653_a,655_a,700_4,700_7,700_a,700_d,710_4,710_7,710_a,710_b,830_a,928_a,964_a,leader
001,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
bk196401170,970923s1963 xr g 000 0 cze,None,None,[(Brož.)],None,None,None,None,[62],[Technika všeobecně],"[62:316.3, 001.102, (041)]",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Člověk a technika v revoluci našich dnů /],[Radovan Richta],None,None,None,None,None,[Praha :],[Čs. společnost pro šíření politických a vědec...,[1963],None,None,None,None,None,None,None,[85 s. ;],None,[21 cm],None,None,"[5000 výt., Pro potř. lektorů Čs. společ. PVZ]",None,None,None,None,None,"[vědeckotechnické informace, technika a společ...",None,None,None,None,None,[brožury],None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - povaha a význam s...,nam a22 1 4500
bk196503139,971016s1965 xr 000 | cze,None,None,[(Brož.)],None,None,None,None,None,None,[62.004:338.984.2(100-11)(082)],None,None,None,None,None,[Společnost a technická revoluce],None,None,None,None,[1. vyd.],None,[Praha :],"[Orbis,]",[1965],[(Přerov :],[Tisk 4)],None,None,None,None,None,"[218, [iv] s. ;]",None,[20 cm],[Studijní materiály pro lektory ;],[sv. 11/1965],None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[ko2004253513, ko2004231823]","[Osvětový ústav (Praha, Česko), Československá...",None,[Studijní materiály pro lektory],None,[Revoluce vědeckotechnická - společnost social...,nam a22 1 4500
bk196505047a,971213s1966 xr a e 000 0 cze,None,None,[(Brož.)],None,None,None,None,[316.4],[Sociální procesy],"[316.7+008, 62:001.892, 001.83, 316.42, 001:31...",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Civilizace na rozcestí :],[Radovan Richta a kolektiv ; [předml. F. Šorm]],None,None,None,[1. vyd.],None,[Praha :],"[Svoboda,]",[1966],None,[(Rudé právo)],None,None,None,None,None,"[236, [20] s. :]",[tb. ;],[8°],None,None,[Obálku navrhl a graficky upravil Václav Kučer...,[Úvahy objasňují komplexně a synteticky vědeck...,None,None,None,[20. století],"[civilizace, vědecko-technický rozvoj, sociáln...","[None, interdisciplinární aspekty, None, None]","[20. století, None, 20. století, 20. století]",None,None,None,[kolektivní monografie],[aui],None,"[Šorm, F.]",None,None,None,None,None,None,None,[Revoluce vědeckotechnická - rozbory marxistické],nam a22 1 4500
bk196601008,970922s1966 xr cze,None,None,None,None,None,None,None,None,None,[62.001:330.148(075)],[aut],[jk01021806],"[Čihák, Miloš]",None,None,[Vědeckotechnická revoluce a její důsledky v s...,[Miloš Čihák],None,None,None,[1. vyd.],None,[Praha :],"[NPL,]",[1966],None,[(Rudé právo)],None,None,None,None,None,"[89, [3] s. ;]",None,[8°],None,None,[Vyd. pro potř. Večerní univ. marxismu-leninis...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - povaha a význam -...,nam a22 1 4500
bk196700715,970714s1967 xr a e 000 0 cze,None,None,None,None,None,None,None,[316.4],[Sociální procesy],"[316.7+008, 62:001.892, 001.83, 316.42, 001:31...",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Civilizace na rozcestí :],[Radovan Richta a kolektiv ; [předml. F. Šorm]],None,None,None,[2. vyd.],None,[Praha :],"[Svoboda,]",[1967],None,[(Rudé právo)],None,None,None,None,None,"[236, [20] s. :]",[tb. ;],[8°],None,None,"[Souběž. rus., angl., něm. a franc. obsah, Poz...",None,None,None,None,[20. století],"[civilizace, vědecko-technický rozvoj, sociáln...","[None, interdisciplinární aspekty, None, None]","[20. století, None, 20. století, 20. století]",None,None,None,[kolektivní monografie],[aui],None,"[Šorm, F.]",None,None,None,None,None,None,None,[Revoluce vědeckotechnická - rozbory marxistické],nam a22 1 4500
bk196701467,970724s1967 xr 000 | cze,None,None,[(Brožováno)],None,None,None,None,None,None,[018.1+016:62.004],[com],[jk01071782],"[Legátová, Božena,]",[1920-],None,[Vědeckotechnická revoluce :],[sestavila Božena Legátová],None,None,None,None,None,None,None,None,None,None,None,[Ostrava :],"[Státní vědecká knihovna,]",[1967],[1],[63 listů ;],None,[30 cm],[Publikace Státní vědecké knihovny v Ostravě. ...,[čís. 416],None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Publikace Státní vědecké knihovny v Ostravě],None,[Revoluce vědeckotechnická - bibliografie],nam a22 1i 4500
bk196704651,971120s1967 xr cze,None,None,None,None,None,None,None,None,None,[001.89:302.12(079.3)],None,None,None,None,None,[Dialog o vědeckotechnické revoluci :],None,None,None,None,None,None,[Praha :],"[Ekonomický ústav ČSAV,]",[1967],None,None,None,None,None,None,None,"[44, [1] s. ;]",None,[8°],[Informační publ. Ekon. ústavu ČSAV v Praze ;],[čís. 58],"[250 výt., Pozn., Pro vnitř. potřebu]",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Informační publ. Ekon. ústavu ČSAV v Praze],None,[Revoluce vědeckotechnická - vědci čs. - předn...,nam a22 1 4500
bk196802063,970620s1968 xr cze,None,None,None,None,None,None,None,None,None,[62.004+001.892:355(075)],[aut],[jn20010309356],"[Ždímal, Milan]",None,None,[Vědeckotechnická revoluce ve vojenství /],[Milan Ždímal],None,None,None,None,None,[Praha :],"[[Socialist. akademie],]",[1968],None,[(SČT 202)],None,None,None,None,None,[31 s. :],[2 s. příl. ;],[4°],[Studijní materiály Socialist. akademie v Praze],None,"[Přehl. lit., Pozn., Odkazy na lit., Z vědecko...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Studijní materiály Socialist. akademie v Praze],None,[Vojenství - revoluce vědeckotechnická - mater...,nam a22 1 4500
bk196803043,970716s1968 xr cze,None,None,None,None,None,None,None,None,None,[001.89:62.004]:331.01:159.9+111.11(082)],None,None,None,None,None,[K vybraným otázkám antropologie a psychologie...,None,None,None,None,None,None,[Praha :],"[Socialistická akademie,]",[1968],None,[(KNT 4)],None,None,None,None,None,"[62, [2] s. ;]",None,[8°],[Knižnice vědeckotechn. revoluce],None,"[Obálka: Zdeněk Svačina, Pro lektory Socialist...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knižnice vědeckotechn. revoluce],None,[Revoluce vědeckotechnická - antropologie a ps...,nam a22 1 4500
bk196803055,970716s1968 xr cze,None,None,None,None,None,None,None,None,None,[62.004:001.89]:330-012.8(075.8)],[aut],[jk01021806],"[Čihák, Miloš]",None,None,[Vědeckotechnická revoluce a soudobý kapitalis...,[Miloš Čihák],None,None,None,None,None,[Praha :],"[Vys. škola polit. ÚV KSČ,]",[1968],None,None,None,None,None,None,None,"[81, [6] s. ;]",None,[8°],None,None,"[Z Katedry polit. ekonomie, Pozn. a odkazy na ...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Kapitalismus státně monopolistický - revoluce...,nam a22 1 4500
bk196803716,970825s1968 xr cze,None,None,None,None,None,None,None,None,None,[62.001.7:001.892:371.031(082)],None,None,None,None,None,[K perspektivám rozvoje vzdělání a vzdělávacíc...,None,None,None,None,None,None,[Praha :],"[Socialistická akademie,]",[1968],None,[(ST 4)],None,None,None,None,None,"[69, [2] s. ;]",None,[8°],[Knižnice vědeckotechnické revoluce],None,"[Obálka: Zdeněk Svačina, 2000 výt., Spoluvyd. ...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knižnice vědeckotechnické revoluce],None,[Revoluce vědeckotechnická - vzdělání - rozvoj...,nam a22 1 4500
bk196803717,970825s1968 xr cze,None,None,None,None,None,None,None,None,None,[62.001.7:001.892:339.4(082)],None,None,None,None,None,[Ke vztahu vědeckotechnické revoluce a konzumn...,None,None,None,None,None,None,[Praha :],"[Socialistická akademie,]",[1968],None,[(ST 4)],None,None,None,None,None,"[69, [2] s. ;]",None,[8°],[Knižnice vědeckotechnické revoluce],None,"[1500 výt., Spoluvyd. ČSAV, Pozn. a odkazy na ...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knižnice vědeckotechnické revoluce],None,[Revoluce vědeckotechnická - společnost konzum...,nam a22 1 4500
bk196803718,970825s1968 xr cze,None,None,None,None,None,None,None,None,None,[62.001.7:001.892]:613.63(041)],[aut],None,"[Leiský, Otakar]",None,None,[Zdravé přírodní prostředí - základní předpokl...,[Otakar Leiský],None,None,None,None,None,[Praha :],"[Socialistická akademie,]",[1968],[(Jihlava :],[G)],None,None,None,None,None,"[61, [1] s. ;]",None,[8°],[Studijní materiály pro lektory Socialist. aka...,None,"[Obálka: Jaromír Chuchel, 1300 výt.]",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Studijní materiály pro lektory Socialist. aka...,None,[Revoluce vědeckotechnická - uskutečňování - p...,nam a22 1 4500
bk196803719,970825s1968 xr cze,None,None,None,None,None,None,None,None,None,[001.892:62.001.7+30(075.8)],[aut],[jk01121615],"[Stuna, Rudolf,]",[1930-2008],None,[Vědeckotechnická revoluce a vývoj společnosti :],[Autor: Rudolf Stuna a kol.],None,None,None,[1. vyd.],None,[Olomouc :],"[Univerzita Palackého,]",[1968],None,None,None,None,None,None,None,"[53, [2] s. ;]",None,[4°],[Učební texty vys. škol],None,"[Bibliogr. pozn., 200 výt.]",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Učební texty vys. škol],None,[Revoluce vědeckotechnická - učebnice vysokošk...,nam a22 1 4500
bk196901369,970810s1968 xr ||| | cze,None,None,None,None,None,None,None,None,None,[62.001+5(061.3)],None,None,None,None,None,[Jak mění objevy přírodních věd podmínky lidsk...,[[poř. Socialist. akademie a ČSAV ve dnech 27....,None,None,None,None,None,[Praha :],"[[s.n.],]",[1968],None,[(KNT 4)],None,None,None,None,None,[80 s. ;],None,[8°],[Knižnice vědeckotechnické revoluce],None,"[Vyd. pro potř. lektorů Socialist. akademie, O...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knižnice vědeckotechnické revoluce],None,[Přírodověda - revoluce vědeckotechnická - sou...,nam a22 1 4500
bk196902024,970920s1968 xr cze,None,None,None,None,None,None,None,None,None,[016:[62.001.7:001.892],[com],[jx20041115013],"[Kasková, Irena]",None,None,[Vědeckotechnická revoluce :],[Sest. I. Kasková],None,None,None,None,None,[Karlovy Vary :],"[Okresní knihovna,]",[[1968]],None,None,None,None,None,None,None,[5 s. ;],None,[8°],None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - bibliografie výbě...,nam a22 1 4500
bk196902469,971111s1969 xr e 000 0 cze,None,"[Kčs 33,00]",[(Váz.) :],None,None,None,None,[316.4],[Sociální procesy],"[316.7+008, 62:001.892, 001.83, 316.42, 001:31...",[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,[Civilizace na rozcestí :],[Radovan Richta a kolektiv ; [předml. F. Šorm]],None,None,None,"[3., rozš. vyd.]",None,[Praha :],"[Svoboda,]",[1969],None,[(Rudé právo)],None,None,None,None,None,"[412, [5] s. :]",[tb. ;],[8°],None,None,"[Obálka a vazbu navrhl Václav Kučera, 20000 vý...",[Nové vydání kolektivního díla objasňujícího k...,None,None,None,[20. století],"[civilizace, vědecko-technický rozvoj, sociáln...","[None, interdisciplinární aspekty, None, None]","[20. století, None, 20. století, 20. století]",None,None,None,[kolektivní monografie],None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - rozbory marxistické],nam a22 1 4500
bk196903667,971022s1969 xr cze,None,None,[(Brož.)],None,None,None,None,None,None,[17.03+62.001.7:001.892],[aut],[jk01060354],"[Klein, Ota,]",[1921-1968],None,[Životní styl a moderní civilizace /],[Ota Klein ; Z pozůstalosti k vyd. připr. Rado...,None,None,None,[1. vyd.],None,[Praha :],"[Symposium,]",[1969],None,[(Rudé právo)],None,None,None,None,None,"[165, [2] s. ;]",None,[8°],[Knihovna Doby ;],[Sv. 2],"[Obálka: Nina Roháčová, Pozn., Odkazy na lit.]","[Výbor z prací předčasně zesnulého O. Kleina, ...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knihovna doby],None,[Revoluce vědeckotechnická - styl životní - st...,nam a22 1 4500
bk197003329,970609s1969 xr cze,None,None,[(Brož.)],None,None,None,None,None,None,[019.922 :[62.004 +008],[com],[xx0036038],"[Boková, Vlasta,]",[1924-],None,[Člověk a vědeckotechnická revoluce :],[Sest. Vlasta Boková],None,None,None,None,None,[Ústí nad Labem :],"[Kraj. knihovna Maxima Gorkého,]",[1969],None,None,None,None,None,None,None,"[16, [1] s. ;]",None,[8°],[Bibliografie Kraj. knihovny Maxima Gorkého v ...,[Roč. 1969. Čís. 15],"[Obálka: Alena Koblencová, 200 výt., Jmenný re...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Bibliografie Kraj. knihovny Maxima Gorkého v ...,None,[Člověk - revoluce vědeckotechnická - bibliogr...,nam a22 1 4500
bk197101411,970326s1971 xr cze,None,None,None,None,None,None,None,None,None,"[001:62:355.01, 62.001+001.126]:355.48, 001.12...",[aut],[jk01013001],"[Brátka, František]",None,None,[Válka a vědeckotechnická revoluce /],"[[autoři:] František Brátka, Josef Kepka]",None,None,None,[1. vyd.],None,[Praha :],"[Naše vojsko,]",[1971],None,None,None,None,None,None,None,"[247, [4] s. ;]",None,[8°],[Knižnice vojen. teorie a praxe ;],[Sv. 13],"[Přehl. použité lit., S grafy v textu, Obálka ...","[Nevšedním způsobem, který prozrazuje důkladno...",None,None,None,None,None,None,None,None,None,None,None,[aut],[jo20000080524],"[Kepka, Josef,]",[1950-],None,None,None,None,[Knižnice vojen. teorie a praxe],None,[Revoluce vědeckotechnická - vojenství - rozbo...,nam a22 1 4500
bk197202197,970217s1972 xr cze,None,None,None,None,None,None,None,None,None,[32:159.922.27(041)],[aut],[jk01051005],"[Janků, Vladimír]",None,None,[Člověk a společnost :],[Vladimír Janků],None,None,None,[1. vyd.],None,[Praha :],"[Vyšehrad,]",[1972],None,[(Mír 5)],None,None,None,None,None,"[37, [2] s. ;]",None,[8°],[Knihovna Čs. strany lid.],None,"[Obálka: Karel Vodák, Pro účely polit. výchovy...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knihovna Čs. strany lid.],None,[Člověk - společnost - vývoj politický - brožu...,nam a22 1 4500
bk197203327,970314s1972 xr cze,None,None,[(Brož.)],None,None,None,None,None,None,"[62.001.7+001.892]:335.55, 001.126+62.001:321....",[aut],[jk01031172],"[Filipec, Jindřich,]",[1926-],None,[Vědeckotechnická revoluce a socialismus /],"[Jindřich Filipec, Radovan Richta]",None,None,None,[1. vyd.],None,[Praha :],"[Svoboda,]",[1972],None,[(Rudé právo)],None,None,None,None,None,"[113, [3] s. ;]",None,[8°],[Dialogy ;],[sv. 15],"[Obálka: Jiří Rathouský, 6000 výt., Pozn., Odk...",[Pojednání o rozvoji vědy a techniky v moderní...,None,None,None,None,None,None,None,None,None,None,None,[aut],[jk01102454],"[Richta, Radovan,]",[1924-1983],None,None,None,None,[Dialogy (Svoboda)],None,[Revoluce vědeckotechnická - socialismus - roz...,nam a22 1 4500
bk197300116,970630s1972 xr cze,None,None,None,[cze],[rus],[1],None,None,None,[62.001.7:001.892]:335(082)],None,None,None,None,None,[Vědeckotechnická revoluce a socialismus :],[Z růz.] rus. originálů přel. kol.],None,None,None,[1. vyd.],None,[Praha :],"[Práce,]",[1972],None,[(Mír 1)],None,None,None,None,None,"[163, [3] s. ;]",None,[8°],None,None,"[S tb. v textu, Obálka: Ivan Kincl, Vyd. k 50....",[Významní sovětští politikové a vědci se ve sv...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Revoluce vědeckotechnická - socialismus - sbo...,nam a22 1 4500
bk197301032,970211s1973 xr 000 | cze,None,"[Kčs 14,00]",[(Brož.) :],[cze],[rus],[1],None,None,None,"[62.001.7 :001.892""312""]",[aut],[xx0040957],"[Šuchardin, Semen Viktorovič,]",[1917-],None,[Současná vědeckotechnická revoluce /],[S.V. Šuchardin a kol. ; [z ruského originálu ...,None,None,None,[1. vyd.],None,[Praha :],"[Orbis,]",[1973],None,[(ST 2)],None,None,None,None,None,"[304, [2] s. ;]",None,[8°],[Pyramida],None,"[Pozn. a odkazy na lit. vyprac. J. Němeček, Ob...",[Kolektiv pracovníků Ústavu přírodních věd a t...,None,None,None,None,None,None,None,None,None,None,None,"[trl, trl]","[jk01061159, jk01012809]","[Kohoutová, Miroslava, Boudyšová, Vlasta]",None,None,None,None,None,[Pyramida (Orbis)],None,[Revoluce vědeckotechnická - podstata a projev...,nam a22 1a 4500
bk197301160,970220s1972 xr cze,None,None,None,[cze],[rus],[1],None,None,None,[62.001.7:001.892]:355.23(041)],[aut],None,"[Vydrin, I. F.]",None,None,[Vědeckotechnická revoluce ve vojenství-někter...,[I.F. Vydrin ; Z rus. orig. Naučno-techničeska...,None,None,None,[1. vyd.],None,[Praha :],"[Naše vojsko,]",[1972],None,None,None,None,None,None,None,"[23, [1] s. ;]",None,[8°],[Na pomoc přednáškové propagandě],None,[Vyd. hl. polit. správa Čs. lid. armády],None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[ko2003204637],[Československo.],"[Armáda., Hlavní politická správa]",[Na pomoc přednáškové propagandě],None,[Revoluce vědeckotechnická - vojenství - brožu...,nam a22 1 4500
bk197301224,970221s1972 xr cze,None,None,None,None,None,None,None,None,None,[62.001.7:001.892]:330.148(075.8)],[aut],[jn20001227410],"[Jurečka, Václav,]",[1943-],None,[Vědeckotechnická revoluce a její ekonomické a...,[Václav Jurečka],None,None,None,None,None,[Praha :],"[Vys. škola polit. ÚV KSČ,]",[1972],None,None,None,None,None,None,None,"[160, [1] s. ;]",None,[8°],None,None,"[Pro vnitř. potřebu školy, 500 výt., Pozn. a o...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Země kapitalistické - revoluce vědeckotechnic...,nam a22 1 4500
bk197302441,970424s1973 xr ||| | cze,None,None,None,None,None,None,None,None,None,[62.001.7:001.892(041)],[aut],[jx20100226013],"[Hulešová, Věra]",None,None,[Vědeckotechnická revoluce a její vliv na vývo...,[Věra Hulešová],None,None,None,[1. vyd.],None,[Praha :],"[Vyšehrad,]",[1973],None,[(Mír 5)],None,None,None,None,None,[50 s. ;],None,[8°],[Knihovna Čs. strany lidové],None,"[Obálka: Karel Vodák, Neprodejné, 3000 výt.]",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Knihovna Čs. strany lidové],None,[Revoluce vědeckotechnická - společnost - vývo...,nam a22 1 4500
bk197305047,970806s1973 xr cze,None,None,None,None,None,None,None,None,None,[301:[62.001.7:001.892(075.8)],None,None,None,None,None,[Základní společenské problémy vědeckotechnick...,[Autor: kol. pod ved. Rudolfa Fraňka],None,None,None,[1. vyd.],None,[Praha :],"[ČVUT,]",[1973],None,None,None,None,None,None,None,[203 s. ;],None,[4°],None,None,"[200 výt., Z Ústavu marxismu-leninismu, Pozn.,...",None,None,None,None,None,None,None,None,None,None,None,None,[aut],[jk01031722],"[Franěk, Rudolf,]",[1929-],None,None,None,None,None,None,[Revoluce vědeckotechnická - problémy společen...,nam a22 1 4500
bk197402868,970306s1974 xr cze,None,None,None,None,None,None,None,None,None,[62.001.7:001.892(041)],[aut],[jk01122387],"[Šafránek, Ladislav]",None,None,[Vybrané problémy vědeckotechnické revoluce /],[Ladislav Šafránek],None,None,None,[1. vyd.],None,[Praha :],"[Práce,]",[1974],None,[(Mír 1)],None,None,None,None,None,"[90, [2] s. ;]",None,[8°],[Na pomoc funkcionářskému aktivu ROH],None,"[13500 výt., Vyd. ve spolupráci s odd. propaga...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[Na pomoc funkcionářskému aktivu ROH],None,[Revoluce vědeckotechnická - podstata a charak...,nam a22 1 4500