In [214]:
import os
import polars as pl
from src.bez_bordelu import bez_bordelu
from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
pl.Config(tbl_rows=500)

In [149]:
df = pl.read_parquet(
    os.path.join("data/cnb_sloupce","100.parquet")
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","020.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","022.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","041.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","260.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","300.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","490.parquet")), left_on="001", right_on="001", how="left"
).explode(
    "300_a"
).with_columns(
    pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran')
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
).explode(
    "260_b"
).with_columns(
    pl.col(("260_b")).map_elements(bez_bordelu, return_dtype=str)
).explode(
    "490_a"
).with_columns(
    pl.col(("490_a")).map_elements(bez_bordelu, return_dtype=str)
)

In [127]:
def zjisti(nazev):
    frejm = df.filter(pl.col("245_a").str.contains(nazev)).select(pl.col(["100_a","245_a","260_b","rok","stran","490_a"])).sort(by="rok")
    print(frejm.select(pl.col("490_a")).to_series().to_list()[0])
    return frejm

In [97]:
zjisti("Jak s tím pohnu")

Krystal

shape: (1, 6)
┌────────────────────┬─────────────────┬───────┬──────┬───────┬─────────┐
│ 100_a              ┆ 245_a           ┆ 260_b ┆ rok  ┆ stran ┆ 490_a   │
│ ---                ┆ ---             ┆ ---   ┆ ---  ┆ ---   ┆ ---     │
│ str                ┆ str             ┆ str   ┆ i64  ┆ i64   ┆ str     │
╞════════════════════╪═════════════════╪═══════╪══════╪═══════╪═════════╡
│ Houška, Vítězslav, ┆ Jak s tím pohnu ┆ SNDK  ┆ 1965 ┆ 188   ┆ Krystal │
└────────────────────┴─────────────────┴───────┴──────┴───────┴─────────┘

In [75]:
zjisti("Nejkrásnější bývá šílená")

Poesie

shape: (3, 5)
┌────────────────────┬──────────────────────────┬──────┬───────┬──────────────┐
│ 100_a              ┆ 245_a                    ┆ rok  ┆ stran ┆ 490_a        │
│ ---                ┆ ---                      ┆ ---  ┆ ---   ┆ ---          │
│ str                ┆ str                      ┆ i64  ┆ i64   ┆ str          │
╞════════════════════╪══════════════════════════╪══════╪═══════╪══════════════╡
│ Cincibuch, Petr,   ┆ Nejkrásnější bývá šílená ┆ 1983 ┆ 74    ┆ Poesie       │
│ Seifert, Jaroslav, ┆ Nejkrásnější bývá šílená ┆ 1996 ┆ 136   ┆ Květy poezie │
│ Seifert, Jaroslav, ┆ Nejkrásnější bývá šílená ┆ 1968 ┆ 124   ┆ Květy poezie │
└────────────────────┴──────────────────────────┴──────┴───────┴──────────────┘

In [152]:
zjisti("Pět olympijských")

None

shape: (1, 6)
┌──────────────────┬────────────────────────┬───────┬──────┬───────┬───────┐
│ 100_a            ┆ 245_a                  ┆ 260_b ┆ rok  ┆ stran ┆ 490_a │
│ ---              ┆ ---                    ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str              ┆ str                    ┆ str   ┆ i64  ┆ i64   ┆ str   │
╞══════════════════╪════════════════════════╪═══════╪══════╪═══════╪═══════╡
│ Zapletal, Miloš, ┆ Pět olympijských kruhů ┆ STN   ┆ 1964 ┆ 426   ┆ null  │
└──────────────────┴────────────────────────┴───────┴──────┴───────┴───────┘

In [156]:
def edice(retezec, nakladatelstvi=None):
    if nakladatelstvi == None:
        return df.filter(pl.col("490_a").str.contains(retezec)).select(pl.col(["100_a","245_a","stran","rok"])).sort(by='rok')
    else:
        return df.filter(pl.col("490_a").str.contains(retezec)).filter(pl.col("260_b") == nakladatelstvi).select(pl.col(["100_a","245_a","300_a","rok","stran"])).sort(by='rok')

In [158]:
edice("Škola mladých matematiků")

shape: (70, 4)
┌─────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                       ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                         ┆ ---                             ┆ ---   ┆ ---  │
│ str                         ┆ str                             ┆ i64   ┆ i64  │
╞═════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Hradecký, František,        ┆ Několik úloh z geometrie jedno… ┆ 89    ┆ 1961 │
│ Sedláček, Jiří,             ┆ Co víme o přirozených číslech   ┆ 42    ┆ 1961 │
│ Šisler, Miroslav            ┆ O funkcích                      ┆ 56    ┆ 1962 │
│ Šedivý, Jaroslav,           ┆ Shodná zobrazení v konstruktiv… ┆ 74    ┆ 1962 │
│ Šisler, Miroslav            ┆ O funkcích                      ┆ 55    ┆ 1963 │
│ Hradecký, František,        ┆ Několik úloh z geometrie jedno… ┆ 92    ┆ 1963 │
│ Veselý, František,          ┆ O nerovnostech                  ┆ 67    ┆ 1963 │
│ Výborný, Rudolf,            ┆ Matematická indukce             ┆ 61    ┆ 1963 │
│ Šedivý, Jaroslav,           ┆ O podobnosti v geometrii        ┆ 77    ┆ 1963 │
│ Vyšín, Jan,                 ┆ Konvexní útvary                 ┆ 93    ┆ 1964 │
│ Sedláček, Jiří,             ┆ Faktoriály a kombinační čísla   ┆ 85    ┆ 1964 │
│ Sedláček, Jiří,             ┆ Co víme o přirozených číslech   ┆ 53    ┆ 1965 │
│ Holubář, Josef,             ┆ Geometrická místa bodů v prost… ┆ 55    ┆ 1965 │
│ Havlíček, Karel,            ┆ Prostory o čtyřech a více rozm… ┆ 84    ┆ 1965 │
│ Horák, Stanislav,           ┆ Kružnice                        ┆ 123   ┆ 1966 │
│ Koman, Milan,               ┆ Jak vyšetřujeme geometrická mí… ┆ 97    ┆ 1966 │
│ Šisler, Miroslav            ┆ O řešení algebraických rovnic   ┆ 126   ┆ 1966 │
│ Výborný, Rudolf,            ┆ Matematická indukce             ┆ 61    ┆ 1966 │
│ Veselý, František,          ┆ O dělitelnosti čísel celých     ┆ 118   ┆ 1966 │
│ Havlíček, Karel,            ┆ Analytická geometrie a nerovno… ┆ 86    ┆ 1967 │
│ Hroník, Jaromír             ┆ Úlohy o maximech a minimech fu… ┆ 100   ┆ 1967 │
│ Šedivý, Jaroslav,           ┆ O podobnosti v geometrii        ┆ 81    ┆ 1967 │
│ Jarník, Jiří,               ┆ Komplexní čísla a funkce        ┆ 75    ┆ 1967 │
│ Apfelbeck, Alois,           ┆ Kongruence                      ┆ 133   ┆ 1968 │
│ Šmakal, Stanislav,          ┆ Goniometrické funkce            ┆ 144   ┆ 1968 │
│ Morávek, Jaroslav,          ┆ Oddělitelnost množin            ┆ 69    ┆ 1969 │
│ Šalát, Tibor,               ┆ Dokonalé a spriatelené čísla    ┆ 49    ┆ 1969 │
│ Gatial, Ján,                ┆ Stavba Lobačevského planimetri… ┆ 115   ┆ 1969 │
│ Hruša, Karel,               ┆ Polynomy v moderní algebře      ┆ 100   ┆ 1970 │
│ Bukovský, Lev,              ┆ Dirichletov princíp             ┆ 58    ┆ 1970 │
│ Váňa, Jiří,                 ┆ O rovnicích s parametry         ┆ 61    ┆ 1970 │
│ Horák, Stanislav,           ┆ Mnohostěny                      ┆ 83    ┆ 1970 │
│ Budinský, Bruno,            ┆ Vektory v geometrii             ┆ 155   ┆ 1971 │
│ Koman, Milan,               ┆ Malý výlet do moderní matemati… ┆ 187   ┆ 1972 │
│ Zítek, František,           ┆ Vytvořující funkce              ┆ 145   ┆ 1972 │
│ Odvárko, Oldřich,           ┆ Booleova algebra                ┆ 115   ┆ 1973 │
│ Morávek, Jaroslav,          ┆ O dynamickém programování       ┆ 77    ┆ 1973 │
│ Vyšín, Jan,                 ┆ Druhý výlet do moderní matemat… ┆ 95    ┆ 1973 │
│ Kufner, Alois,              ┆ Co asi nevíte o vzdálenosti     ┆ 116   ┆ 1974 │
│ Rieger, Ladislav,           ┆ O grupách                       ┆ 139   ┆ 1974 │
│ Koman, Milan,               ┆ Malý výlet do moderní matemati… ┆ 187   ┆ 1974 │
│ Kufner, Alois,              ┆ Nerovnosti a odhady             ┆ 117   ┆ 1975 │
│ Riečan, Beloslav,           ┆ O pravdepodobnosti              ┆ 101   ┆ 1976 │
│ Bosák, Juraj,               ┆ Latinské štvorce                ┆ 82    ┆ 1976 │
│ Černý, Ján                  ┆ O aplikáciach matematiky        ┆ 115   ┆ 1976 │
│ Hradecký, František,        ┆ Několik úloh z geometrie jedno… ┆ 116   ┆ 1977 │
│ Sedláček, Jiří,             ┆ Co víme o přirozených číslech   ┆ 62    ┆ 1977 │
│ Vrba, Antonín               ┆ Princip matematické indukce     ┆ 138   ┆ 1977 │
│ Zelinka, Bohdan,            ┆ Rovinné grafy                   ┆ 131   ┆ 1977 │
│ Beran, Ladislav,            ┆ Uspořádané množiny              ┆ 73    ┆ 1978 │
│ Jarník, Jiří,               ┆ Posloupnosti a řady             ┆ 138   ┆ 1979 │
│ Zelinka, Bohdan,            ┆ Matematika hrou i vážně         ┆ 188   ┆ 1979 │
│ Šedivý, Jaroslav,           ┆ Shodnost a podobnost v konstru… ┆ 157   ┆ 1980 │
│ Vrba, Antonín               ┆ Kombinatorika                   ┆ 130   ┆ 1980 │
│ Niederle, Arnošt            ┆ Zajímavé dvojice trojúhelníků   ┆ 268   ┆ 1980 │
│ Vít, Pavel,                 ┆ Řetězové zlomky                 ┆ 158   ┆ 1982 │
│ Gatial, Ján,                ┆ Hry takmer matematické          ┆ 140   ┆ 1982 │
│ Kufner, Alois,              ┆ Symetrické funkce               ┆ 116   ┆ 1982 │
│ Gutenmacher, Viktor L'vovič ┆ Přímky a křivky                 ┆ 154   ┆ 1982 │
│ Płocki, Adam,               ┆ O náhodě a pravděpodobnosti     ┆ 172   ┆ 1982 │
│ Veselý, František,          ┆ O nerovnostech a nerovnicích    ┆ 86    ┆ 1982 │
│ Holubář, Josef,             ┆ Množiny bodů v prostoru         ┆ 55    ┆ 1983 │
│ Davidov, Ljubomir,          ┆ Funkcionální rovnice            ┆ 92    ┆ 1984 │
│ Sedláček, Jiří,             ┆ Faktoriály a kombinační čísla   ┆ 125   ┆ 1985 │
│ Horák, Stanislav,           ┆ Nerovnosti v trojúhelníku       ┆ 125   ┆ 1986 │
│ Kästner, Herbert            ┆ Algebra                         ┆ 172   ┆ 1986 │
│ Morávek, Jaroslav,          ┆ Oddělitelnost množin            ┆ 83    ┆ 1987 │
│ Korec, Ivan,                ┆ Úlohy o veľkých číslach         ┆ 134   ┆ 1988 │
│ Tůma, Jiří,                 ┆ Matematické halvolamy a základ… ┆ 246   ┆ 1988 │
│ Kufner, Alois,              ┆ Nerovnosti a odhady             ┆ 117   ┆ 1989 │
└─────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [55]:
edice("Super lekce")

shape: (2, 4)
┌───────────────────────┬─────────────────────────────────┬──────┬───────┐
│ 100_a                 ┆ 245_a                           ┆ rok  ┆ stran │
│ ---                   ┆ ---                             ┆ ---  ┆ ---   │
│ str                   ┆ str                             ┆ i64  ┆ i64   │
╞═══════════════════════╪═════════════════════════════════╪══════╪═══════╡
│ McManus, Sean,        ┆ Jak se naučit programovat v 10… ┆ 2017 ┆ 64    │
│ Bishop-Stephens, Will ┆ Jak se naučit animovat v 10 sn… ┆ 2017 ┆ 64    │
└───────────────────────┴─────────────────────────────────┴──────┴───────┘

In [69]:
edice("AAA : edice anglo-amerických autorů")

shape: (134, 4)
┌────────────────────────┬─────────────────────────────────┬──────┬───────┐
│ 100_a                  ┆ 245_a                           ┆ rok  ┆ stran │
│ ---                    ┆ ---                             ┆ ---  ┆ ---   │
│ str                    ┆ str                             ┆ i64  ┆ i64   │
╞════════════════════════╪═════════════════════════════════╪══════╪═══════╡
│ Erdrich, Louise,       ┆ Čarování s láskou               ┆ 1994 ┆ 241   │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 1994 ┆ 283   │
│ Toole, John Kennedy,   ┆ Neónová bible                   ┆ 1994 ┆ 120   │
│ Kosiński, Jerzy N.,    ┆ Byl jsem při tom                ┆ 1995 ┆ 81    │
│ Toole, John Kennedy,   ┆ Spolčení hlupců                 ┆ 1995 ┆ 359   │
│ Brautigan, Richard,    ┆ Willard a jeho kuželkářské tro… ┆ 1995 ┆ 149   │
│ Kosiński, Jerzy N.,    ┆ Nabarvené ptáče                 ┆ 1995 ┆ 215   │
│ Cave, Nick,            ┆ A uzřela oslice anděla          ┆ 1995 ┆ 297   │
│ McCarthy, Cormac,      ┆ Všichni krásní koně             ┆ 1995 ┆ 251   │
│ Allen, Woody,          ┆ Bez peří                        ┆ 1995 ┆ 95    │
│ Carver, Raymond,       ┆ Buď, prosím tě, zticha          ┆ 1996 ┆ 233   │
│ Robbins, Tom,          ┆ Parfém bláznivého tance         ┆ 1996 ┆ 379   │
│ Plath, Sylvia,         ┆ Pod skleněným zvonem            ┆ 1996 ┆ 209   │
│ Kosiński, Jerzy N.,    ┆ Kroky                           ┆ 1996 ┆ 103   │
│ Potok, Chaim,          ┆ Jmenuji se Ašer Lev             ┆ 1996 ┆ 287   │
│ Cohen, Leonard,        ┆ Nádherní poražení               ┆ 1997 ┆ 222   │
│ Ondaatje, Michael,     ┆ Anglický pacient                ┆ 1997 ┆ 263   │
│ Allen, Woody,          ┆ Vyřídit si účty                 ┆ 1997 ┆ 92    │
│ Robbins, Tom,          ┆ Další dálniční atrakce          ┆ 1997 ┆ 353   │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 1997 ┆ 286   │
│ Pynchon, Thomas,       ┆ Městečko Vineland               ┆ 1997 ┆ 374   │
│ Carter, Angela,        ┆ Krvavá komnata                  ┆ 1997 ┆ 143   │
│ McCarthy, Cormac,      ┆ Hranice                         ┆ 1997 ┆ 353   │
│ McInerney, Jay,        ┆ To už je život                  ┆ 1998 ┆ 141   │
│ Atwood, Margaret,      ┆ Z hlubin                        ┆ 1998 ┆ 189   │
│ Vonnegut, Kurt,        ┆ Časotřesení                     ┆ 1998 ┆ 184   │
│ Saroyan, William,      ┆ Kluci a holky, když jsou spolu  ┆ 1998 ┆ 131   │
│ Cohen, Leonard,        ┆ Oblíbená hra                    ┆ 1998 ┆ 203   │
│ Winterson, Jeanette,   ┆ Na světě nejsou jen pomeranče   ┆ 1998 ┆ 184   │
│ Robbins, Tom,          ┆ Hubené nohy a všechno ostatní   ┆ 1998 ┆ 454   │
│ Ondaatje, Michael,     ┆ Máme to v rodině                ┆ 1998 ┆ 160   │
│ Irving, John,          ┆ Modlitba za Owena Meanyho       ┆ 1999 ┆ 615   │
│ Mills, Magnus,         ┆ Ohrady pro zvířata              ┆ 1999 ┆ 172   │
│ Kesey, Ken,            ┆ Tak mě někdy napadá             ┆ 1999 ┆ 655   │
│ Potok, Chaim,          ┆ Dar Ašera Leva                  ┆ 1999 ┆ 360   │
│ Vonnegut, Mark,        ┆ Expres do ráje                  ┆ 1999 ┆ 250   │
│ Gray, Alasdair,        ┆ Něco z kůže                     ┆ 1999 ┆ 233   │
│ Doctorow, E. L.,       ┆ Světová výstava                 ┆ 1999 ┆ 256   │
│ Barthelme, Donald,     ┆ Padesát povídek                 ┆ 1999 ┆ 303   │
│ Ishiguro, Kazuo,       ┆ Malíř pomíjivého světa          ┆ 1999 ┆ 166   │
│ Robbins, Tom,          ┆ Zátiší s Datlem                 ┆ 2000 ┆ 232   │
│ Wharton, William,      ┆ Birdy                           ┆ 2000 ┆ 269   │
│ Winterson, Jeanette,   ┆ Vášeň                           ┆ 2000 ┆ 148   │
│ Jackson, Mick,         ┆ Muž z podzemí                   ┆ 2001 ┆ 211   │
│ Walker, Alice,         ┆ Barva nachu                     ┆ 2001 ┆ 252   │
│ Vonnegut, Kurt,        ┆ Tabatěrka z Bagomba             ┆ 2001 ┆ 285   │
│ Woronov, Mary          ┆ V podzemních vodách             ┆ 2001 ┆ 164   │
│ Momaday, N. Scott      ┆ Dům z úsvitu                    ┆ 2001 ┆ 167   │
│ Potok, Chaim,          ┆ Na počátku                      ┆ 2001 ┆ 424   │
│ Eggers, Dave,          ┆ Srdceryvné dílo ohromujícího g… ┆ 2001 ┆ 382   │
│ …                      ┆ …                               ┆ …    ┆ …     │
│ McCarthy, Cormac,      ┆ Cesta                           ┆ 2008 ┆ 185   │
│ McCarthy, Cormac,      ┆ Všichni krásní koně             ┆ 2008 ┆ 260   │
│ McCarthy, Cormac,      ┆ Hranice                         ┆ 2008 ┆ 346   │
│ Boyle, T. Coraghessan, ┆ Řeči řeči                       ┆ 2008 ┆ 356   │
│ Robinson, Marilynne,   ┆ Ztrácení                        ┆ 2008 ┆ 200   │
│ Pessl, Marisha,        ┆ Vybrané okruhy z mechaniky poh… ┆ 2008 ┆ 435   │
│ Welsh, Louise,         ┆ Falešná trefa                   ┆ 2009 ┆ 301   │
│ McCarthy, Cormac,      ┆ Krvavý poledník, aneb, Večerní… ┆ 2009 ┆ 389   │
│ Donleavy, J. P.        ┆ Bezuzdná blahoslavenství Balta… ┆ 2009 ┆ 416   │
│ Díaz, Junot,           ┆ Krátký, leč divuplný život Osk… ┆ 2009 ┆ 314   │
│ Richler, Mordecai,     ┆ Jezdec z Ulice sv. Urbana       ┆ 2009 ┆ 514   │
│ Krauss, Nicole,        ┆ Muž vejde do pokoje             ┆ 2009 ┆ 264   │
│ Cave, Nick,            ┆ Smrt Zajdy Munroa               ┆ 2009 ┆ 238   │
│ Lahiri, Jhumpa,        ┆ Tlumočník nemocí                ┆ 2009 ┆ 179   │
│ McCarthy, Cormac,      ┆ Dítě Boží                       ┆ 2009 ┆ 180   │
│ Lahiri, Jhumpa,        ┆ Nezvyklá země                   ┆ 2010 ┆ 322   │
│ Atkinson, Kate,        ┆ Neuzavřené případy              ┆ 2010 ┆ 304   │
│ Rapp, Adam,            ┆ Rok nekonečného strádání        ┆ 2010 ┆ 458   │
│ McCarthy, Cormac,      ┆ Města na planině                ┆ 2010 ┆ 294   │
│ Chaon, Dan,            ┆ Čekat Vaše odpověď              ┆ 2010 ┆ 326   │
│ Barthelme, Donald,     ┆ Mrtvý otec                      ┆ 2010 ┆ 174   │
│ Martel, Yann,          ┆ Beatrice a Vergilius            ┆ 2011 ┆ 158   │
│ Kosiński, Jerzy N.,    ┆ Nabarvené ptáče                 ┆ 2011 ┆ 215   │
│ Krauss, Nicole,        ┆ Dějiny lásky                    ┆ 2011 ┆ 246   │
│ Vann, David,           ┆ Ostrov Sukkwan                  ┆ 2011 ┆ 160   │
│ McCarthy, Cormac,      ┆ Vnější tma                      ┆ 2011 ┆ 218   │
│ Krauss, Nicole,        ┆ Velký dům                       ┆ 2012 ┆ 307   │
│ McCarthy, Cormac,      ┆ Strážce sadu                    ┆ 2012 ┆ 227   │
│ McCarthy, Cormac,      ┆ Suttree                         ┆ 2012 ┆ 511   │
│ Shteyngart, Gary,      ┆ Megasmutná pravdivá lovestory   ┆ 2013 ┆ 413   │
│ Franzen, Jonathan,     ┆ Svoboda                         ┆ 2013 ┆ 415   │
│ Torres, Justin,        ┆ My, zvířata                     ┆ 2013 ┆ 127   │
│ Self, Will,            ┆ Deštník                         ┆ 2014 ┆ 346   │
│ Oyeyemi, Helen,        ┆ Dívka jménem Boy                ┆ 2016 ┆ 263   │
│ Holmes, John Clellon,  ┆ Jeď!                            ┆ 2016 ┆ 419   │
│ Pynchon, Thomas,       ┆ Výkřik techniky                 ┆ 2017 ┆ 518   │
│ Ishiguro, Kazuo,       ┆ Pohřbený obr                    ┆ 2017 ┆ 318   │
│ Ishiguro, Kazuo,       ┆ Neopouštěj mě                   ┆ 2018 ┆ 301   │
│ Ishiguro, Kazuo,       ┆ Malíř pomíjivého světa          ┆ 2018 ┆ 196   │
│ Cave, Nick,            ┆ Smrt Zajdy Munroa               ┆ 2019 ┆ 239   │
│ Vann, David,           ┆ Akvárium                        ┆ 2019 ┆ 230   │
│ Cohen, Leonard,        ┆ Nádherní poražení               ┆ 2019 ┆ 260   │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 2019 ┆ 392   │
│ McCarthy, Cormac,      ┆ Krvavý poledník, aneb, Večerní… ┆ 2019 ┆ 391   │
│ St. Aubyn, Edward,     ┆ Patrick Melrose                 ┆ 2019 ┆ 1     │
│ Ishiguro, Kazuo,       ┆ Neutěšenci                      ┆ 2020 ┆ 637   │
│ McCarthy, Cormac,      ┆ Tahle země není pro starý       ┆ 2020 ┆ 237   │
│ Cohen, Leonard,        ┆ Oblíbená hra                    ┆ 2020 ┆ 285   │
│ Burns, Anna,           ┆ Mlíkař                          ┆ 2020 ┆ 412   │
│ Irving, John,          ┆ Modlitba za Owena Meanyho       ┆ 2021 ┆ 720   │
└────────────────────────┴─────────────────────────────────┴──────┴───────┘

In [77]:
edice("Květy poezie")

shape: (228, 4)
┌────────────────────────────────┬─────────────────────────────────┬──────┬───────┐
│ 100_a                          ┆ 245_a                           ┆ rok  ┆ stran │
│ ---                            ┆ ---                             ┆ ---  ┆ ---   │
│ str                            ┆ str                             ┆ i64  ┆ i64   │
╞════════════════════════════════╪═════════════════════════════════╪══════╪═══════╡
│ Goethe, Johann Wolfgang von,   ┆ Balady                          ┆ 1958 ┆ 85    │
│ Tasso, Torquato,               ┆ Lyrika                          ┆ 1958 ┆ 125   │
│ Nezval, Vítězslav,             ┆ Edison                          ┆ 1958 ┆ 109   │
│ Rimbaud, Arthur,               ┆ Výbor                           ┆ 1959 ┆ 175   │
│ Poe, Edgar Allan,              ┆ Havran                          ┆ 1959 ┆ 89    │
│ Corbière, Tristan,             ┆ Žluté lásky                     ┆ 1959 ┆ 92    │
│ Catullus, Gaius Valerius,      ┆ Básně                           ┆ 1959 ┆ 198   │
│ Dyk, Viktor,                   ┆ Milá sedmi loupežníků           ┆ 1959 ┆ 125   │
│ Rictus, Jehan,                 ┆ Poezie                          ┆ 1959 ┆ 87    │
│ Hrubín, František,             ┆ Jobova noc                      ┆ 1959 ┆ 53    │
│ Byron, George Gordon Byron,    ┆ Lyrika                          ┆ 1959 ┆ 123   │
│ Verhaeren, Émile,              ┆ Žárné chorály                   ┆ 1960 ┆ 128   │
│ Hořejší, Jindřich,             ┆ Hudba na náměstí                ┆ 1960 ┆ 92    │
│ Jeffers, Robinson,             ┆ Hřebec grošák                   ┆ 1960 ┆ 87    │
│ Sandburg, Carl,                ┆ Ocel a dým                      ┆ 1960 ┆ 179   │
│ Nekrasov, Nikolaj Aleksejevič, ┆ Ruské ženy                      ┆ 1960 ┆ 128   │
│ Závada, Vilém,                 ┆ Vzduch a světlo                 ┆ 1960 ┆ 177   │
│ Ovidius,                       ┆ Listy heroin                    ┆ 1960 ┆ 81    │
│ Espronceda, José de,           ┆ Výbor                           ┆ 1961 ┆ 153   │
│ Verlaine, Paul,                ┆ Mé tuláctví                     ┆ 1961 ┆ 87    │
│ Browning, Elizabeth Barrett,   ┆ Portugalské sonety              ┆ 1961 ┆ 79    │
│ Ševčenko, Taras Hryhorovyč,    ┆ V tom ráji na zemi              ┆ 1961 ┆ 93    │
│ Hora, Josef,                   ┆ Zahrada Popelčina               ┆ 1961 ┆ 96    │
│ García Lorca, Federico,        ┆ Písně na andaluskou notu        ┆ 1961 ┆ 251   │
│ Tóth, Árpád,                   ┆ Od srdce k srdci                ┆ 1961 ┆ 119   │
│ Neruda, Pablo,                 ┆ Semena bouře                    ┆ 1961 ┆ 115   │
│ Holan, Vladimír,               ┆ Terezka Planetová               ┆ 1962 ┆ 85    │
│ Propertius, Sextus,            ┆ Elegie                          ┆ 1962 ┆ 103   │
│ Shelley, Percy Bysshe,         ┆ Odpoutaný Prométheus            ┆ 1962 ┆ 174   │
│ Bagrickij, Èduard Georgijevič, ┆ Thyl Ulenspiegel                ┆ 1962 ┆ 89    │
│ Heine, Heinrich,               ┆ Meč a plamen                    ┆ 1962 ┆ 128   │
│ Camões, Luís de,               ┆ Msti se mým slzám               ┆ 1962 ┆ 111   │
│ Hughes, Langston,              ┆ Harlemský zpěvník               ┆ 1963 ┆ 120   │
│ Chénier, André,                ┆ Sen o Heladě                    ┆ 1963 ┆ 99    │
│ Halas, František,              ┆ Sbohem, múzy                    ┆ 1963 ┆ 241   │
│ Bednář, Kamil,                 ┆ Krásných paní milování a jiné … ┆ 1963 ┆ 107   │
│ Brecht, Bertolt,               ┆ Domácí postila Bertolta Brecht… ┆ 1963 ┆ 178   │
│ Anakreón,                      ┆ Oslavujme Bakcha                ┆ 1963 ┆ 94    │
│ Quevedo, Francisco de,         ┆ Kruté sny                       ┆ 1963 ┆ 152   │
│ Sel'vinskij, Il'ja L'vovič,    ┆ Pohár oceánu                    ┆ 1963 ┆ 149   │
│ Kästner, Erich,                ┆ Z malých dějin                  ┆ 1963 ┆ 145   │
│ Blake, William,                ┆ Svět v zrnku písku              ┆ 1964 ┆ 153   │
│ Ovidius,                       ┆ Listy heroin                    ┆ 1964 ┆ 110   │
│ Hesse, Hermann,                ┆ Stupně                          ┆ 1964 ┆ 98    │
│ Morgenstern, Christian,        ┆ Palmström a Palma Kunkel        ┆ 1964 ┆ 172   │
│ Radnóti, Miklós,               ┆ A přece se vrátím               ┆ 1964 ┆ 197   │
│ Shakespeare, William,          ┆ Sonety                          ┆ 1964 ┆ 168   │
│ Cendrars, Blaise,              ┆ V srdci světa                   ┆ 1964 ┆ 132   │
│ Baudelaire, Charles,           ┆ Květy zla                       ┆ 1964 ┆ 232   │
│ Mikulášek, Oldřich,            ┆ Divoké kačeny                   ┆ 1964 ┆ 107   │
│ …                              ┆ …                               ┆ …    ┆ …     │
│ Erben, Karel Jaromír,          ┆ Kytice                          ┆ 1996 ┆ 162   │
│ Kryl, Karel,                   ┆ Znamení doby                    ┆ 1996 ┆ 163   │
│ Gellner, František,            ┆ Teplo zhaslého plamene          ┆ 1997 ┆ 138   │
│ Szymborska, Wisława,           ┆ Konec a počátek                 ┆ 1997 ┆ 153   │
│ Prévert, Jacques,              ┆ Pro tebe, má lásko              ┆ 1997 ┆ 131   │
│ Seifert, Jaroslav,             ┆ Maminka                         ┆ 1997 ┆ 84    │
│ Kavafīs, Kōnstantinos P.,      ┆ Nebezpečné touhy                ┆ 1997 ┆ 129   │
│ Baudelaire, Charles,           ┆ Květy zla                       ┆ 1997 ┆ 145   │
│ Hiršal, Josef,                 ┆ Párkař                          ┆ 1997 ┆ 54    │
│ Camões, Luís de,               ┆ Trýzeň i útěcha                 ┆ 1997 ┆ 106   │
│ Brodskij, Iosif Aleksandrovič, ┆ Konec krásné epochy             ┆ 1997 ┆ 141   │
│ Alighieri, Dante,              ┆ To sladké jméno Beatrice        ┆ 1998 ┆ 126   │
│ Ronsard, Pierre de,            ┆ Tři lásky                       ┆ 1998 ┆ 92    │
│ Hlaváček, Karel,               ┆ Budu snít marně                 ┆ 1998 ┆ 105   │
│ Hrubín, František,             ┆ Romance pro křídlovku           ┆ 1998 ┆ 70    │
│ Mickiewicz, Adam,              ┆ Balady a romance                ┆ 1998 ┆ 157   │
│ Bécquer, Gustavo Adolfo,       ┆ Sloky                           ┆ 1998 ┆ 146   │
│ Thákur, Rabíndranáth,          ┆ Zahradník                       ┆ 1999 ┆ 124   │
│ Li, Po,                        ┆ Nebe mi pokrývkou a země polšt… ┆ 1999 ┆ 143   │
│ Ringelnatz, Joachim,           ┆ Stará láska nerezaví            ┆ 1999 ┆ 118   │
│ Mácha, Karel Hynek,            ┆ Máj                             ┆ 1999 ┆ 79    │
│ Heaney, Seamus,                ┆ Přezimování pod širým nebem     ┆ 1999 ┆ 153   │
│ Pilinszky, János,              ┆ Ortel                           ┆ 1999 ┆ 157   │
│ Nezval, Vítězslav,             ┆ Básně noci                      ┆ 1999 ┆ 141   │
│ Creeley, Robert,               ┆ Zahrady paměti                  ┆ 1999 ┆ 135   │
│ Morgenstern, Christian,        ┆ Písně šibeničních bratří        ┆ 2000 ┆ 143   │
│ Hrabal, Bohumil,               ┆ Bambino di Praga                ┆ 2000 ┆ 111   │
│ Ginsberg, Allen,               ┆ Slovy a dechem                  ┆ 2000 ┆ 147   │
│ Nezval, Vítězslav,             ┆ Manon Lescaut                   ┆ 2001 ┆ 253   │
│ Desbordes-Valmore, Marceline,  ┆ Knížka něžností                 ┆ 2001 ┆ 67    │
│ Nguyen Binh,                   ┆ Tisíc oken                      ┆ 2001 ┆ 88    │
│ Wernisch, Ivan,                ┆ Půjdeme do Mů                   ┆ 2002 ┆ 96    │
│ Parra, Nicanor,                ┆ Básně proti plešatění           ┆ 2002 ┆ 132   │
│ Karásek ze Lvovic, Jiří,       ┆ Sodoma                          ┆ 2002 ┆ 92    │
│ Li, Qingzhao,                  ┆ Květy skořicovníku              ┆ 2002 ┆ 108   │
│ Elytis, Odysseus,              ┆ Bláznivý granátovník            ┆ 2003 ┆ 133   │
│ Lamartine, Alphonse de,        ┆ Básnické meditace               ┆ 2003 ┆ 124   │
│ Hutka, Jaroslav,               ┆ Pravděpodobnej svět             ┆ 2003 ┆ 132   │
│ Koneski, Blaže,                ┆ Poslání                         ┆ 2003 ┆ 144   │
│ Kryl, Karel,                   ┆ Znamení doby                    ┆ 2004 ┆ 163   │
│ Cohen, Leonard,                ┆ Květiny pro Hitlera             ┆ 2004 ┆ 201   │
│ Ko, Ŭn,                        ┆ Květy okamžiku                  ┆ 2005 ┆ 94    │
│ Shakespeare, William,          ┆ Sonety                          ┆ 2005 ┆ 172   │
│ Holan, Vladimír,               ┆ Mozartiana                      ┆ 2006 ┆ 56    │
│ Graves, Robert,                ┆ Kráska v nesnázích              ┆ 2006 ┆ 135   │
│ Kotrlý, Zdeněk,                ┆ Souznička                       ┆ 2006 ┆ 189   │
│ Fischer, Otokar,               ┆ Poutník a píseň                 ┆ 2008 ┆ 145   │
│ Erben, Karel Jaromír,          ┆ Kytice                          ┆ 2009 ┆ 162   │
│ Erben, Karel Jaromír,          ┆ Kytice                          ┆ 2021 ┆ 162   │
│ Erben, Karel Jaromír,          ┆ Kytice                          ┆ 2024 ┆ 162   │
└────────────────────────────────┴─────────────────────────────────┴──────┴───────┘

In [103]:
edice("Krystal", nakladatelstvi="SNDK")

shape: (10, 5)
┌───────────────────────────────┬───────────────────────┬────────────────────┬──────┬───────┐
│ 100_a                         ┆ 245_a                 ┆ 300_a              ┆ rok  ┆ stran │
│ ---                           ┆ ---                   ┆ ---                ┆ ---  ┆ ---   │
│ str                           ┆ str                   ┆ list[str]          ┆ i64  ┆ i64   │
╞═══════════════════════════════╪═══════════════════════╪════════════════════╪══════╪═══════╡
│ Adla, Zdeněk,                 ┆ Krásná a slavná       ┆ ["257, [7] s. :"]  ┆ 1961 ┆ 257   │
│ Bojarová, Olga,               ┆ Od hlavy k patě       ┆ ["186, [6] s. ;"]  ┆ 1961 ┆ 186   │
│ Petr, Tomislav,               ┆ Divy oceánů           ┆ ["174 s. :"]       ┆ 1962 ┆ 174   │
│ Koval, Václav,                ┆ Na dně vzdušného moře ┆ ["221, [4] s. ;"]  ┆ 1962 ┆ 221   │
│ Štuka, Ivo,                   ┆ Šest dnů na luně 1    ┆ ["200, [3] s. ;"]  ┆ 1963 ┆ 200   │
│ Houška, Vítězslav,            ┆ Jak s tím pohnu       ┆ ["188 s. ;"]       ┆ 1965 ┆ 188   │
│ Tichý, Jaroslav,              ┆ Letem ČSSR            ┆ ["214, [6] s. ;"]  ┆ 1965 ┆ 214   │
│ Elstner, František Alexander, ┆ Motorové opojení      ┆ ["207, [5] s. ;"]  ┆ 1966 ┆ 207   │
│ Deyl, Václav,                 ┆ Tajemství plamenů     ┆ ["185, [7] s. :"]  ┆ 1967 ┆ 185   │
│ Hons, Josef,                  ┆ A štafeta běží dál    ┆ ["214, [34] s. :"] ┆ 1967 ┆ 214   │
└───────────────────────────────┴───────────────────────┴────────────────────┴──────┴───────┘

In [119]:
zjisti("Nová divočina")

ReX

shape: (2, 6)
┌────────────────┬───────────────┬───────┬──────┬───────┬──────────────────┐
│ 100_a          ┆ 245_a         ┆ 260_b ┆ rok  ┆ stran ┆ 490_a            │
│ ---            ┆ ---           ┆ ---   ┆ ---  ┆ ---   ┆ ---              │
│ str            ┆ str           ┆ str   ┆ i64  ┆ i64   ┆ str              │
╞════════════════╪═══════════════╪═══════╪══════╪═══════╪══════════════════╡
│ Zbořil, Jonáš, ┆ Nová divočina ┆ null  ┆ 2020 ┆ 77    ┆ ReX              │
│ Cook, Diane,   ┆ Nová divočina ┆ null  ┆ 2022 ┆ 460   ┆ Světová knihovna │
└────────────────┴───────────────┴───────┴──────┴───────┴──────────────────┘

In [121]:
edice("ReX")

shape: (35, 5)
┌──────────────────────────┬────────────────────────────────┬────────────────────────────────┬──────┬───────┐
│ 100_a                    ┆ 245_a                          ┆ 300_a                          ┆ rok  ┆ stran │
│ ---                      ┆ ---                            ┆ ---                            ┆ ---  ┆ ---   │
│ str                      ┆ str                            ┆ list[str]                      ┆ i64  ┆ i64   │
╞══════════════════════════╪════════════════════════════════╪════════════════════════════════╪══════╪═══════╡
│ Hruška, Petr,            ┆ Auta vjíždějí do lodí          ┆ ["65 s. :"]                    ┆ 2007 ┆ 65    │
│ Slíva, Vít,              ┆ Souvrať                        ┆ ["74 s. :"]                    ┆ 2007 ┆ 74    │
│ Malý, Radek,             ┆ Malá tma                       ┆ ["71 s. :"]                    ┆ 2008 ┆ 71    │
│ Urbánková, Dagmar,       ┆ Ta hlava větru vypadá jako pes ┆ ["107 s. :"]                   ┆ 2008 ┆ 107   │
│ Kudláček, Slavomír,      ┆ Schůzka v lomu                 ┆ ["75 s. :"]                    ┆ 2009 ┆ 75    │
│ Machulková, Inka,        ┆ Zamkni les a pojď              ┆ ["85 s. :"]                    ┆ 2009 ┆ 85    │
│ Žila, Jaroslav,          ┆ V hrudi pták                   ┆ ["66 s. :"]                    ┆ 2010 ┆ 66    │
│ Žila, Jaroslav,          ┆ V hrudi pták                   ┆ ["66 s. :"]                    ┆ 2010 ┆ 66    │
│ Reiner, Martin,          ┆ Hubená stehna Twiggy           ┆ ["103 s. :"]                   ┆ 2010 ┆ 103   │
│ Šťastná, Marie,          ┆ Interiéry                      ┆ ["71 s., [1] l. obr. příl. :"] ┆ 2010 ┆ 71    │
│ Slíva, Vít,              ┆ Račí mor                       ┆ ["89 s. :"]                    ┆ 2011 ┆ 89    │
│ Fridrich, Radek,         ┆ Krooa krooa                    ┆ ["63 s. :"]                    ┆ 2011 ┆ 63    │
│ Hruška, Petr,            ┆ Darmata                        ┆ ["52 s. :"]                    ┆ 2012 ┆ 52    │
│ Děžinský, Milan,         ┆ Tajný život                    ┆ ["70 s. ;"]                    ┆ 2012 ┆ 70    │
│ Malý, Radek,             ┆ Světloplaší                    ┆ ["97 s. ;"]                    ┆ 2012 ┆ 97    │
│ Stöhr, Martin Josef,     ┆ Smích ze snu                   ┆ ["63 s. :"]                    ┆ 2012 ┆ 63    │
│ Hruška, Petr,            ┆ Darmata                        ┆ ["52 s. :"]                    ┆ 2013 ┆ 52    │
│ Macura, Ondřej,          ┆ Sklo                           ┆ ["92 s. :"]                    ┆ 2013 ┆ 92    │
│ Hanus, Ondřej,           ┆ Výjevy                         ┆ ["56 s. :"]                    ┆ 2013 ┆ 56    │
│ Slíva, Vít,              ┆ Návrší                         ┆ ["99 s. ;"]                    ┆ 2014 ┆ 99    │
│ Malý, Radek,             ┆ Všehomír                       ┆ ["60 stran ;"]                 ┆ 2015 ┆ 60    │
│ Gabriel, Tomáš,          ┆ Obvyklé hrdinství              ┆ ["96 stran ;"]                 ┆ 2016 ┆ 96    │
│ Děžinský, Milan,         ┆ Obcházení ostrova              ┆ ["51 stran ;"]                 ┆ 2017 ┆ 51    │
│ Marks, Luděk,            ┆ Po hadí kůži                   ┆ ["113 stran ;"]                ┆ 2017 ┆ 113   │
│ Hanus, Ondřej,           ┆ Volné verše                    ┆ ["56 stran ;"]                 ┆ 2017 ┆ 56    │
│ Slíva, Vít,              ┆ Ultima Thúlé, nejzazší zem     ┆ ["83 stran ;"]                 ┆ 2018 ┆ 83    │
│ Goldstein, Klára,        ┆ Kenotaf                        ┆ ["63 stran :"]                 ┆ 2018 ┆ 63    │
│ Iljašenko, Marie,        ┆ Sv. Outdoor                    ┆ ["56 stran ;"]                 ┆ 2019 ┆ 56    │
│ Šťastná, Marie,          ┆ Štěstí jistě přijde            ┆ ["71 stran ;"]                 ┆ 2019 ┆ 71    │
│ Kaprál, Zeno,            ┆ Elegie naruby                  ┆ ["63 stran ;"]                 ┆ 2019 ┆ 63    │
│ Veselá-Jirousová, Marta, ┆ Zahrada                        ┆ ["81 stran ;"]                 ┆ 2019 ┆ 81    │
│ Zbořil, Jonáš,           ┆ Nová divočina                  ┆ ["77 stran :"]                 ┆ 2020 ┆ 77    │
│ Stöhr, Martin Josef,     ┆ Užitá lyrika                   ┆ ["61 stran :"]                 ┆ 2020 ┆ 61    │
│ Šustková, Tereza,        ┆ Tíha vlny                      ┆ ["73 stran ;"]                 ┆ 2020 ┆ 73    │
│ Goldstein, Klára,        ┆ Falkenfrau                     ┆ ["69 stran ;"]                 ┆ 2021 ┆ 69    │
└──────────────────────────┴────────────────────────────────┴────────────────────────────────┴──────┴───────┘

In [133]:
zjisti("Nebe, peklo")

Umělecké snahy

shape: (20, 6)
┌───────────────────────────┬─────────────────────────────────┬───────────────────────┬──────┬───────┬─────────────────────────────────┐
│ 100_a                     ┆ 245_a                           ┆ 260_b                 ┆ rok  ┆ stran ┆ 490_a                           │
│ ---                       ┆ ---                             ┆ ---                   ┆ ---  ┆ ---   ┆ ---                             │
│ str                       ┆ str                             ┆ str                   ┆ i64  ┆ i64   ┆ str                             │
╞═══════════════════════════╪═════════════════════════════════╪═══════════════════════╪══════╪═══════╪═════════════════════════════════╡
│ Mahen, Jiří,              ┆ Nebe, peklo, ráj ... (1917)     ┆ B. Kočí               ┆ 1919 ┆ 103   ┆ Umělecké snahy                  │
│ Mahen, Jiří,              ┆ Nebe, peklo, ráj ... 1917       ┆ B. Kočí               ┆ 1922 ┆ 103   ┆ Umělecké snahy                  │
│ Biebl, Konstantin,        ┆ Nebe, peklo, ráj                ┆ Erna Janská           ┆ 1930 ┆ 43    ┆ Editio princeps                 │
│ Biebl, Konstantin,        ┆ Nebe, peklo, ráj                ┆ Sfinx, Bohumil Janda  ┆ 1931 ┆ 54    ┆ Růžová zahrada                  │
│ Biebl, Konstantin,        ┆ Nebe, peklo, ráj                ┆ null                  ┆ 1931 ┆ 54    ┆ Růžová zahrada                  │
│ Mahen, Jiří,              ┆ Nebe, peklo, ráj... (1917)      ┆ null                  ┆ 1950 ┆ 139   ┆ Československé divadelní a lit… │
│ Kornelová, Marie,         ┆ Nebe, peklo, ráj                ┆ SNDK                  ┆ 1967 ┆ 204   ┆ null                            │
│ Cortázar, Julio,          ┆ Nebe, peklo, ráj                ┆ Odeon                 ┆ 1972 ┆ 580   ┆ Soudobá světová próza           │
│ Salivarová, Zdena,        ┆ Nebe, peklo, ráj                ┆ Atlantis              ┆ 1991 ┆ 271   ┆ null                            │
│ Gurevič, Aron Jakovlevič, ┆ Nebe, peklo, svět               ┆ H & H                 ┆ 1996 ┆ 524   ┆ null                            │
│ Skořepová, Luba,          ┆ Nebe, peklo, ráj                ┆ Knižní klub           ┆ 1999 ┆ 174   ┆ null                            │
│ Cortázar, Julio,          ┆ Nebe, peklo, ráj                ┆ Mladá fronta          ┆ 2001 ┆ 600   ┆ Román                           │
│ Salivarová, Zdena,        ┆ Nebe, peklo, ráj                ┆ Academia              ┆ 2001 ┆ 267   ┆ Scarabeus                       │
│ Lipecká, Olga,            ┆ Dívky hrají Nebe, peklo, ráj    ┆ Akcent                ┆ 2009 ┆ 182   ┆ null                            │
│ Janek, Dalibor,           ┆ Nebe, peklo, ráj závodníka a m… ┆ Computer Press        ┆ 2010 ┆ 152   ┆ null                            │
│ Francková, Zuzana,        ┆ Nebe, peklo, ráj                ┆ Erika                 ┆ 2010 ┆ 125   ┆ null                            │
│ Kovářová, Daniela,        ┆ Nebe, peklo, ráj                ┆ Agentura Lucie        ┆ 2011 ┆ 133   ┆ null                            │
│ Jindra, Miroslav,         ┆ Nebe, peklo, zem                ┆ Barrister & Principal ┆ 2013 ┆ 261   ┆ Paměť                           │
│ Cortázar, Julio,          ┆ Nebe, peklo, ráj                ┆ null                  ┆ 2019 ┆ 641   ┆ null                            │
│ Plyšák                    ┆ Nebe, peklo, ráj                ┆ null                  ┆ 2022 ┆ 51    ┆ null                            │
└───────────────────────────┴─────────────────────────────────┴───────────────────────┴──────┴───────┴─────────────────────────────────┘

In [135]:
edice('Román', nakladatelstvi="Mladá fronta")

shape: (41, 5)
┌────────────────────────┬─────────────────────────────────┬──────────────┬──────┬───────┐
│ 100_a                  ┆ 245_a                           ┆ 300_a        ┆ rok  ┆ stran │
│ ---                    ┆ ---                             ┆ ---          ┆ ---  ┆ ---   │
│ str                    ┆ str                             ┆ list[str]    ┆ i64  ┆ i64   │
╞════════════════════════╪═════════════════════════════════╪══════════════╪══════╪═══════╡
│ Kohout, Pavel,         ┆ Hvězdná hodina vrahů            ┆ ["422 s. ;"] ┆ 1995 ┆ 422   │
│ Kohout, Pavel,         ┆ Konec velkých prázdnin          ┆ ["711 s. ;"] ┆ 1996 ┆ 711   │
│ Kohout, Pavel,         ┆ Šest & Sex                      ┆ ["229 s. ;"] ┆ 1998 ┆ 229   │
│ Hoffmann, E. T. A.,    ┆ Ďáblův elixír                   ┆ ["291 s. ;"] ┆ 2001 ┆ 291   │
│ Cortázar, Julio,       ┆ Nebe, peklo, ráj                ┆ ["600 s. ;"] ┆ 2001 ┆ 600   │
│ Guillou, Jan,          ┆ Cesta do Svaté země             ┆ ["356 s. :"] ┆ 2001 ┆ 356   │
│ Chaviano, Daína,       ┆ Havana blues                    ┆ ["241 s. ;"] ┆ 2001 ┆ 241   │
│ Aust, Kurt,            ┆ Den hněvu                       ┆ ["356 s. ;"] ┆ 2001 ┆ 356   │
│ Beckett, Samuel,       ┆ První láska                     ┆ ["71 s. ;"]  ┆ 2001 ┆ 71    │
│ Roy, Arundhati,        ┆ Bůh maličkostí                  ┆ ["331 s. ;"] ┆ 2001 ┆ 331   │
│ Dalmau, Antoni,        ┆ Země zapomnění                  ┆ ["251 s. ;"] ┆ 2001 ┆ 251   │
│ Henriksen, Vera,       ┆ Stříbrné kladivo                ┆ ["260 s. :"] ┆ 2001 ┆ 260   │
│ Cazotte, Jacques,      ┆ Zamilovaný ďábel                ┆ ["237 s. ;"] ┆ 2001 ┆ 237   │
│ Roy, Arundhati,        ┆ Bůh maličkostí                  ┆ ["331 s. ;"] ┆ 2001 ┆ 331   │
│ Ancion, Nicolas,       ┆ Čtvrté patro                    ┆ ["125 s. ;"] ┆ 2002 ┆ 125   │
│ Rahimi, Atiq,          ┆ Země a popel                    ┆ ["76 s. ;"]  ┆ 2002 ┆ 76    │
│ Tsiolkas, Christos,    ┆ Ari                             ┆ ["212 s. ;"] ┆ 2002 ┆ 212   │
│ Antunes, António Lobo, ┆ Jidášova díra                   ┆ ["215 s. ;"] ┆ 2002 ┆ 215   │
│ Montero, Mayra,        ┆ Jako tvůj posel                 ┆ ["244 s. ;"] ┆ 2002 ┆ 244   │
│ Grenville, Kate,       ┆ Lilianin příběh                 ┆ ["330 s. ;"] ┆ 2002 ┆ 330   │
│ Niemi, Mikael,         ┆ Popmusic z Vittuly              ┆ ["258 s. ;"] ┆ 2003 ┆ 258   │
│ Asimov, Isaac,         ┆ Nadace a Říše                   ┆ ["307 s. ;"] ┆ 2003 ┆ 307   │
│ Page, Martin,          ┆ Jak jsem se stal hlupákem       ┆ ["131 s. ;"] ┆ 2003 ┆ 131   │
│ Vargas Llosa, Mario,   ┆ Vypravěč                        ┆ ["183 s. ;"] ┆ 2003 ┆ 183   │
│ Tremain, Rose,         ┆ Valentina a já                  ┆ ["377 s. ;"] ┆ 2003 ┆ 377   │
│ Cercas, Javier,        ┆ Vojáci od Salaminy              ┆ ["226 s. ;"] ┆ 2004 ┆ 226   │
│ Vargas Llosa, Mario,   ┆ Tetička Julie a zneuznaný géni… ┆ ["320 s. ;"] ┆ 2004 ┆ 320   │
│ Houellebecq, Michel,   ┆ Rozšíření bitevního pole        ┆ ["154 s. ;"] ┆ 2004 ┆ 154   │
│ Gavalda, Anna,         ┆ A taková to byla láska--        ┆ ["149 s. ;"] ┆ 2004 ┆ 149   │
│ Shields, Carol,        ┆ Ledaže                          ┆ ["259 s. ;"] ┆ 2004 ┆ 259   │
│ Vargas Llosa, Mario,   ┆ Město a psi                     ┆ ["332 s. ;"] ┆ 2004 ┆ 332   │
│ Nielsen, Hans-Jorgen,  ┆ Fotbalový anděl                 ┆ ["203 s. ;"] ┆ 2004 ┆ 203   │
│ Kirchhoff, Bodo,       ┆ Krvák                           ┆ ["270 s. ;"] ┆ 2004 ┆ 270   │
│ Faulkner, William,     ┆ Prapory v prachu                ┆ ["383 s. ;"] ┆ 2004 ┆ 383   │
│ Bernig, Jörg,          ┆ Čas nikoho                      ┆ ["225 s. ;"] ┆ 2004 ┆ 225   │
│ Atwood, Margaret,      ┆ Přežívá nejsmutnější            ┆ ["316 s. ;"] ┆ 2005 ┆ 316   │
│ Vargas Llosa, Mario,   ┆ Zelený dům                      ┆ ["372 s. ;"] ┆ 2005 ┆ 372   │
│ Asimov, Isaac,         ┆ Druhá Nadace                    ┆ ["305 s. ;"] ┆ 2005 ┆ 305   │
│ Dai, Sijie,            ┆ Balzac a čínská Švadlenka       ┆ ["131 s. ;"] ┆ 2005 ┆ 131   │
│ Mendes, Bob,           ┆ Chuť svobody                    ┆ ["383 s. ;"] ┆ 2006 ┆ 383   │
│ Vargas Llosa, Mario,   ┆ Ráj je až za rohem              ┆ ["362 s. ;"] ┆ 2007 ┆ 362   │
└────────────────────────┴─────────────────────────────────┴──────────────┴──────┴───────┘

In [137]:
zjisti("Svobodná")

None

shape: (30, 6)
┌─────────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┬──────┬───────┬─────────────────────────────────┐
│ 100_a                           ┆ 245_a                           ┆ 260_b                           ┆ rok  ┆ stran ┆ 490_a                           │
│ ---                             ┆ ---                             ┆ ---                             ┆ ---  ┆ ---   ┆ ---                             │
│ str                             ┆ str                             ┆ str                             ┆ i64  ┆ i64   ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╪═════════════════════════════════╪══════╪═══════╪═════════════════════════════════╡
│ Sallač, Karel,                  ┆ Svobodná dělitelnost pozemků j… ┆ K. Sallač                       ┆ 1887 ┆ 33    ┆ null                            │
│ Radić, Stjepan,                 ┆ Svobodná škola politických věd… ┆ Samostatnost                    ┆ 1899 ┆ 64    ┆ null                            │
│ Doubrava, Josef,                ┆ Pastýřský list nejdp. biskupa … ┆ nákl. vl.                       ┆ 1906 ┆ 24    ┆ Časové úvahy                    │
│ Černý, Josef,                   ┆ Svobodná, volná škola a její v… ┆ null                            ┆ 1907 ┆ 187   ┆ null                            │
│ Obuchov, Aleksandr Michajlovič… ┆ Svobodná výchova a disciplina   ┆ s.n.                            ┆ 1910 ┆ 17    ┆ Sedmá výr. zpr. dívč. lycea sp… │
│ Mach, Jarka,                    ┆ Svobodná                        ┆ K.J. Barvitius                  ┆ 1934 ┆ 2     ┆ Barvitiova edice                │
│ Mach, Jarka,                    ┆ Svobodná                        ┆ K.J. Barvitius                  ┆ 1934 ┆ 2     ┆ Popěvky                         │
│ Lamp, Rudolf,                   ┆ Svobodná                        ┆ Státní hudební vydavatelství    ┆ 1963 ┆ 17    ┆ Zábavní orchestr                │
│ Lamp, Rudolf,                   ┆ Svobodná                        ┆ Státní hudební vydavatelství    ┆ 1963 ┆ 17    ┆ Salon-orchester                 │
│ García Lorca, Federico,         ┆ Svobodná paní Rosita, aneb, Kv… ┆ Dilia                           ┆ 1979 ┆ 56    ┆ null                            │
│ Sedláček, Karel,                ┆ Volá Svobodná Evropa            ┆ Archa 90                        ┆ 1993 ┆ 164   ┆ null                            │
│ Janovský-Drážďanský, Karel,     ┆ Svobodná Evropa                 ┆ Papyrus                         ┆ 1995 ┆ 222   ┆ null                            │
│ Marie-Françoise                 ┆ Svobodná matka                  ┆ Ivo Železný                     ┆ 1995 ┆ 60    ┆ Knihovnička Večerů pod lampou.… │
│ Joch, Roman,                    ┆ Svobodná společnost, individuá… ┆ Občanský institut               ┆ 1997 ┆ 23    ┆ Bulletin OI                     │
│ McCaffrey, Anne,                ┆ Svobodná volba                  ┆ Netopejr                        ┆ 1999 ┆ 319   ┆ null                            │
│ Lejsková, Věra,                 ┆ Moje Brno v pořadech Radia Svo… ┆ Šimon Ryšavý                    ┆ 2003 ┆ 108   ┆ null                            │
│ Klausnerová, Eva,               ┆ Svobodná Plzeň hovoří           ┆ Nava                            ┆ 2005 ┆ 111   ┆ null                            │
│ Prášil, Petr,                   ┆ Svobodná Ves                    ┆ Petr Prášil                     ┆ 2005 ┆ 1     ┆ null                            │
│ Velikovská, Kamila              ┆ Svobodná, i když za mrížemi i.… ┆ Jota                            ┆ 2006 ┆ 279   ┆ null                            │
│ Bystrov, Vladimír,              ┆ Svobodná nesvoboda              ┆ Vyšší odborná škola publicisti… ┆ 2006 ┆ 131   ┆ Studie                          │
│ Brázda, Petr                    ┆ Svobodná spolková republika Kr… ┆ Petr Brázda                     ┆ 2007 ┆ 1     ┆ null                            │
│ McCulley, Carolyn,              ┆ Svobodná a v pohodě             ┆ Samuel, Biblická práce pro dět… ┆ 2009 ┆ 205   ┆ null                            │
│ Gazzaniga, Michael S.,          ┆ Kdo to tady řídí?, aneb, Svobo… ┆ Dybbuk                          ┆ 2013 ┆ 236   ┆ null                            │
│ Harris, Sam,                    ┆ Svobodná vůle                   ┆ null                            ┆ 2015 ┆ 83    ┆ null                            │
│ Sternlicht, Hana,               ┆ Svobodná, volná                 ┆ null                            ┆ 2018 ┆ 145   ┆ null                            │
│ Rakušanová, Lída,               ┆ Svobodná v Evropě               ┆ null                            ┆ 2020 ┆ 287   ┆ null                            │
│ Danišová, Justina               ┆ Svobodná hra                    ┆ null                            ┆ 2020 ┆ 307   ┆ null                            │
│ Rakušanová, Lída,               ┆ Svobodná v Evropě               ┆ null                            ┆ 2021 ┆ 8     ┆ null                            │
│ Ypi, Lea,                       ┆ Svobodná                        ┆ null                            ┆ 2023 ┆ 309   ┆ null                            │
│ Grace, Annie,                   ┆ Svobodná mysl                   ┆ null                            ┆ 2024 ┆ 285   ┆ null                            │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────┴──────┴───────┴─────────────────────────────────┘

In [139]:
zjisti("Pánův hlas")

Omnia

shape: (1, 6)
┌─────────────────┬────────────┬─────────┬──────┬───────┬───────┐
│ 100_a           ┆ 245_a      ┆ 260_b   ┆ rok  ┆ stran ┆ 490_a │
│ ---             ┆ ---        ┆ ---     ┆ ---  ┆ ---   ┆ ---   │
│ str             ┆ str        ┆ str     ┆ i64  ┆ i64   ┆ str   │
╞═════════════════╪════════════╪═════════╪══════╪═══════╪═══════╡
│ Lem, Stanisław, ┆ Pánův hlas ┆ Svoboda ┆ 1981 ┆ 729   ┆ Omnia │
└─────────────────┴────────────┴─────────┴──────┴───────┴───────┘

In [143]:
edice("Omnia", nakladatelstvi="Svoboda")

shape: (275, 5)
┌─────────────────────────────────┬─────────────────────────────────┬───────────────────────────┬──────┬───────┐
│ 100_a                           ┆ 245_a                           ┆ 300_a                     ┆ rok  ┆ stran │
│ ---                             ┆ ---                             ┆ ---                       ┆ ---  ┆ ---   │
│ str                             ┆ str                             ┆ list[str]                 ┆ i64  ┆ i64   │
╞═════════════════════════════════╪═════════════════════════════════╪═══════════════════════════╪══════╪═══════╡
│ Larni, Martti,                  ┆ Ve znamení Panny                ┆ ["206, [4] s. ;"]         ┆ 1968 ┆ 206   │
│ Cronin, A. J.                   ┆ Citadela                        ┆ ["446 s. ;"]              ┆ 1969 ┆ 446   │
│ Březovský, Bohuslav,            ┆ Vzdušné zámky                   ┆ ["418, [5] s. ;"]         ┆ 1969 ┆ 418   │
│ Comfort, Will Levington,        ┆ Zvířata a lidé v džungli        ┆ ["200, [3] s. ;"]         ┆ 1969 ┆ 200   │
│ Dumas, Alexandre,               ┆ Josef Balsamo                   ┆ ["2 sv. (682; 699 s.) :"] ┆ 1969 ┆ 699   │
│ Wurmser, André,                 ┆ Vrah zemřel první...            ┆ ["135, [1] s. ;"]         ┆ 1969 ┆ 135   │
│ Šmahelová, Helena,              ┆ Devět tisíc dnů                 ┆ ["220, [2] s. ;"]         ┆ 1969 ┆ 220   │
│ Steinbeck, John,                ┆ Nebeské pastviny                ┆ ["191 s. ;"]              ┆ 1969 ┆ 191   │
│ Mináč, Vladimír,                ┆ Nikdy nejsi sama                ┆ ["256 s. ;"]              ┆ 1969 ┆ 256   │
│ Ossowski, Leonie,               ┆ Nebe - peklo - ráj, kam tě, du… ┆ ["251 s. ;"]              ┆ 1969 ┆ 251   │
│ Jánský, Filip,                  ┆ Nebeští jezdci                  ┆ ["217, [2] s. ;"]         ┆ 1969 ┆ 217   │
│ London, Jack,                   ┆ Odyssea severu                  ┆ ["357, [3] s. ;"]         ┆ 1969 ┆ 357   │
│ Dostojevskij, Fedor Michajlovi… ┆ Strýčkův sen                    ┆ ["366, [4] s. ;"]         ┆ 1969 ┆ 366   │
│ Jirásek, Alois,                 ┆ Filosofská historie             ┆ ["256 s. ;"]              ┆ 1969 ┆ 256   │
│ Chabrol, Jean-Pierre,           ┆ Budu tě milovat bez ostychu     ┆ ["196 s. ;"]              ┆ 1970 ┆ 196   │
│ Dumas, Alexandre,               ┆ Královnin náhrdelník            ┆ ["2 sv. (431; 410 s.) ;"] ┆ 1970 ┆ 431   │
│ Burke, John Frederick           ┆ Předměstí libosti               ┆ ["342 s. ;"]              ┆ 1970 ┆ 342   │
│ Michna, Vladimír,               ┆ Dáma a čarostřelec              ┆ ["191 s. ;"]              ┆ 1970 ┆ 191   │
│ Hončík, Eduard,                 ┆ Jízdenka do Kanady              ┆ ["268 s. ;"]              ┆ 1970 ┆ 268   │
│ Kožík, František,               ┆ Třikrát se ohlédni              ┆ ["181, [3] s. ;"]         ┆ 1970 ┆ 181   │
│ Skočdopole, Bedřich,            ┆ Zatykač na Královnu             ┆ ["167 s. ;"]              ┆ 1970 ┆ 167   │
│ Kříž, Ivan,                     ┆ Velká samota                    ┆ ["358 s. ;"]              ┆ 1970 ┆ 358   │
│ Neff, Vladimír,                 ┆ Lidé v tógách                   ┆ ["179 s. ;"]              ┆ 1970 ┆ 179   │
│ Nauman, Pavel,                  ┆ Faon                            ┆ ["253 s. ;"]              ┆ 1970 ┆ 253   │
│ Ječný, Dobromil,                ┆ Brevíř moderního člověka        ┆ ["172 s. ;"]              ┆ 1970 ┆ 172   │
│ Bradbury, Ray,                  ┆ 451 stupňů Fahrenheita          ┆ ["155 s. ;"]              ┆ 1970 ┆ 155   │
│ Loukotková, Jarmila,            ┆ Bůh či ďábel                    ┆ ["342, [2] s. ;"]         ┆ 1970 ┆ 342   │
│ Féval, Paul,                    ┆ Hrbáč                           ┆ ["542 s. ;"]              ┆ 1970 ┆ 542   │
│ Dimitrova, Blaga,               ┆ Objížďka                        ┆ ["237, [2] s. ;"]         ┆ 1971 ┆ 237   │
│ Cusack, Dymphna,                ┆ Černý blesk                     ┆ ["223, [1] s. ;"]         ┆ 1971 ┆ 223   │
│ Hejcman, Pavel,                 ┆ Doňa Teresa                     ┆ ["195 s. ;"]              ┆ 1971 ┆ 195   │
│ Dumas, Alexandre,               ┆ Pád Bastily                     ┆ ["2 sv. (315, 310 s.) :"] ┆ 1971 ┆ 315   │
│ Sanson, Charles Henri,          ┆ Tajnosti popraviště             ┆ ["416 s. ;"]              ┆ 1971 ┆ 416   │
│ Kratochvíl, Miloš Václav,       ┆ Matyášův meč                    ┆ ["299, [2] s. ;"]         ┆ 1971 ┆ 299   │
│ Wallace, Edgar,                 ┆ Když gangsteři ovládli Londýn   ┆ ["219, [2] s. ;"]         ┆ 1971 ┆ 219   │
│ Olbracht, Ivan,                 ┆ Dobyvatel                       ┆ ["573 s. ;"]              ┆ 1971 ┆ 573   │
│ Kožík, František,               ┆ Hejtman Šarovec                 ┆ ["255, [3] s. ;"]         ┆ 1971 ┆ 255   │
│ Clarke, Arthur C.               ┆ 2001: Vesmírná odysea           ┆ ["204, [3] s. ;"]         ┆ 1971 ┆ 204   │
│ Figuli, Margita,                ┆ Babylón                         ┆ ["408 s. ;"]              ┆ 1971 ┆ 408   │
│ Figuli, Margita,                ┆ Babylón                         ┆ ["406 s. ;"]              ┆ 1971 ┆ 406   │
│ Cooper, James Fenimore,         ┆ Rudý pirát                      ┆ ["224, [2] s. :"]         ┆ 1972 ┆ 224   │
│ Forš, Ol'ga Dmitrijevna,        ┆ Carevna a rebel                 ┆ ["438 s. ;"]              ┆ 1972 ┆ 438   │
│ Korol'kov, Jurij Michajlovič,   ┆ Tajemný dr. Sorge               ┆ ["220, [2] s. ;"]         ┆ 1972 ┆ 220   │
│ Steinberg, Werner,              ┆ Komisařův klobouk               ┆ ["244 s. ;"]              ┆ 1972 ┆ 244   │
│ Tendrjakov, Vladimir Fedorovič… ┆ Cesta na jedno století          ┆ ["237 s. ;"]              ┆ 1972 ┆ 237   │
│ Twain, Mark,                    ┆ Panna ve zbroji                 ┆ ["233, [2] s. ;"]         ┆ 1972 ┆ 233   │
│ London, Jack,                   ┆ Démon alkohol                   ┆ ["189, [2] s. ;"]         ┆ 1972 ┆ 189   │
│ Kin, Viktor Pavlovič,           ┆ Byli jsme dva                   ┆ ["181, [1] s. ;"]         ┆ 1972 ┆ 181   │
│ Lesage, Alain-René,             ┆ Kulhavý ďábel                   ┆ ["236, [3] s. ;"]         ┆ 1972 ┆ 236   │
│ Diderot, Denis,                 ┆ Jakub fatalista a jeho pán      ┆ ["252 s. ;"]              ┆ 1972 ┆ 252   │
│ …                               ┆ …                               ┆ …                         ┆ …    ┆ …     │
│ Scortia, Thomas N.,             ┆ Ponorka                         ┆ ["473 s. ;"]              ┆ 1988 ┆ 473   │
│ McBain, Ed,                     ┆ Sníh                            ┆ ["313 s. ;"]              ┆ 1988 ┆ 313   │
│ Dobzynski, Charles,             ┆ Taromancie                      ┆ ["380 s. ;"]              ┆ 1988 ┆ 380   │
│ Steklač, Vojtěch,               ┆ Zlatá brána                     ┆ ["377 s. ;"]              ┆ 1988 ┆ 377   │
│ Leonard, Frank,                 ┆ Schránka 100                    ┆ ["132 s. ;"]              ┆ 1988 ┆ 132   │
│ Martin, Eduard,                 ┆ Milenci našich žen              ┆ ["423 s. ;"]              ┆ 1989 ┆ 423   │
│ Dumas, Alexandre,               ┆ Robin Hood                      ┆ ["236 s. ;"]              ┆ 1989 ┆ 236   │
│ Borovička, V. P.                ┆ Procesy, které vzrušily svět    ┆ ["557 s. ;"]              ┆ 1989 ┆ 557   │
│ Strugackij, Arkadij Natanovič,  ┆ Vlny ztišují vítr               ┆ ["282 s. ;"]              ┆ 1989 ┆ 282   │
│ Jeschke, Wolfgang,              ┆ Poslední den stvoření           ┆ ["218 s. ;"]              ┆ 1989 ┆ 218   │
│ Semenov, Julian Semenovič,      ┆ Tiskové středisko               ┆ ["371 s. ;"]              ┆ 1989 ┆ 371   │
│ Féval, Paul,                    ┆ Hrbáč                           ┆ ["533 s. ;"]              ┆ 1989 ┆ 533   │
│ Dilov, Ljuben,                  ┆ Let Ikaru                       ┆ ["347 s. ;"]              ┆ 1989 ┆ 347   │
│ Féval, Paul,                    ┆ Tajnosti Londýna                ┆ ["2 sv. (327; 332 s.) ;"] ┆ 1989 ┆ 332   │
│ Duchenne, Albert,               ┆ Soukromý detektiv               ┆ ["152 s. ;"]              ┆ 1990 ┆ 152   │
│ Štemler, Il‘ja Petrovič,        ┆ Vlak                            ┆ ["269 s. ;"]              ┆ 1990 ┆ 269   │
│ Martin, Eduard,                 ┆ Manželka z Venuše               ┆ ["535 s. ;"]              ┆ 1990 ┆ 535   │
│ Mortimer, John Clifford,        ┆ Příběhy obhájce Rumpolea        ┆ ["381 s. ;"]              ┆ 1990 ┆ 381   │
│ Hailey, Arthur,                 ┆ Konečná diagnóza                ┆ ["316 s. ;"]              ┆ 1991 ┆ 316   │
│ West, Morris L.                 ┆ Cassidy                         ┆ ["259 s. ;"]              ┆ 1991 ┆ 259   │
│ Madsen, Svend Åge,              ┆ Miluj mne i zítra               ┆ ["163 s. ;"]              ┆ 1991 ┆ 163   │
│ Goldfluss, Howard E.            ┆ Rozsudek                        ┆ ["209 s. ;"]              ┆ 1991 ┆ 209   │
│ Hyde, Christopher,              ┆ Jericho                         ┆ ["301 s. ;"]              ┆ 1991 ┆ 301   │
│ Wul, Stefan,                    ┆ Ňork                            ┆ ["108 s. ;"]              ┆ 1991 ┆ 108   │
│ Steklač, Vojtěch,               ┆ Lví dvůr                        ┆ ["268 s. ;"]              ┆ 1991 ┆ 268   │
│ King, Stephen,                  ┆ Nadaný žák                      ┆ ["307 s. ;"]              ┆ 1991 ┆ 307   │
│ Fowlkes, Frank                  ┆ Miliónová finta                 ┆ ["228 s. ;"]              ┆ 1991 ┆ 228   │
│ Pecinovský, Josef,              ┆ Abbey Road                      ┆ ["265 s. ;"]              ┆ 1991 ┆ 265   │
│ Merle, Robert,                  ┆ Muži pod ochranou               ┆ ["325 s. ;"]              ┆ 1991 ┆ 325   │
│ Mareš, Zdeněk,                  ┆ Pavilón beznaděje               ┆ ["216 s. ;"]              ┆ 1991 ┆ 216   │
│ Castle, John                    ┆ Let do nebezpečí                ┆ ["122 s. ;"]              ┆ 1992 ┆ 122   │
│ Hauserová, Eva,                 ┆ Hostina mutagenů                ┆ ["166 s. ;"]              ┆ 1992 ┆ 166   │
│ Simenon, Georges,               ┆ Maigret na tenkém ledě          ┆ ["313 s. ;"]              ┆ 1992 ┆ 313   │
│ Corsari, Willy,                 ┆ Neviditelný nepřítel            ┆ ["250 s. ;"]              ┆ 1992 ┆ 250   │
│ Féval, Paul,                    ┆ Železný muž                     ┆ ["178 s. ;"]              ┆ 1992 ┆ 178   │
│ Vadim, Roger,                   ┆ Zamilovaný blázen               ┆ ["232 s. ;"]              ┆ 1992 ┆ 232   │
│ Westlake, Donald E.,            ┆ Jak nevodit policii za nos      ┆ ["136 s. ;"]              ┆ 1992 ┆ 136   │
│ Neff, Vladimír,                 ┆ Lidé v tógách                   ┆ ["142 s. ;"]              ┆ 1992 ┆ 142   │
│ Bradbury, Malcolm,              ┆ Jíst lidi je neslušné           ┆ ["217 s. ;"]              ┆ 1992 ┆ 217   │
│ Watson, Ian,                    ┆ Cesta proti času                ┆ ["117 s. ;"]              ┆ 1992 ┆ 117   │
│ Herbert, James,                 ┆ Lovec duchů                     ┆ ["166 s. ;"]              ┆ 1994 ┆ 166   │
│ Le Carré, John,                 ┆ Smileyho lidé                   ┆ ["318 s. ;"]              ┆ 1994 ┆ 318   │
│ Lee, Tanith,                    ┆ Volkhavaar - služebník Černého… ┆ ["171 s. ;"]              ┆ 1994 ┆ 171   │
│ Sayers, Dorothy L.              ┆ Devět krejčíků                  ┆ ["245 s. ;"]              ┆ 1994 ┆ 245   │
│ Simenon, Georges,               ┆ 2x komisař Maigret              ┆ ["236 s. ;"]              ┆ 1994 ┆ 236   │
│ Cherryh, C. J.,                 ┆ Kukaččí vejce                   ┆ ["286 s. ;"]              ┆ 1995 ┆ 286   │
│ Herbert, Frank,                 ┆ Děti Duny                       ┆ ["441 s. ;"]              ┆ 1995 ┆ 441   │
│ Boulle, Pierre,                 ┆ Kdo s koho, Satane!             ┆ ["109 s. ;"]              ┆ 1996 ┆ 109   │
│ Herbert, Frank,                 ┆ Božský imperátor Duny           ┆ ["413 s. ;"]              ┆ 1996 ┆ 413   │
│ Herbert, Frank,                 ┆ Kacíři Duny                     ┆ ["542 s. ;"]              ┆ 1997 ┆ 542   │
└─────────────────────────────────┴─────────────────────────────────┴───────────────────────────┴──────┴───────┘

In [145]:
zjisti("Ragtime")

None

shape: (10, 6)
┌──────────────────┬────────────────────────┬─────────────────┬──────┬───────┬─────────────────────────────────┐
│ 100_a            ┆ 245_a                  ┆ 260_b           ┆ rok  ┆ stran ┆ 490_a                           │
│ ---              ┆ ---                    ┆ ---             ┆ ---  ┆ ---   ┆ ---                             │
│ str              ┆ str                    ┆ str             ┆ i64  ┆ i64   ┆ str                             │
╞══════════════════╪════════════════════════╪═════════════════╪══════╪═══════╪═════════════════════════════════╡
│ Ghali, Adib      ┆ Ragtime guitar         ┆ Levné knihy KMa ┆ null ┆ 45    ┆ null                            │
│ Watson, Fr. Th.  ┆ The Ragtime Girl       ┆ null            ┆ 1914 ┆ 4     ┆ null                            │
│ Mládek, Ivan,    ┆ Ragtime-coctail        ┆ Panton          ┆ 1981 ┆ 13    ┆ null                            │
│ Doctorow, E. L., ┆ Ragtime                ┆ Odeon           ┆ 1982 ┆ 251   ┆ Soudobá světová próza           │
│ Doctorow, E. L., ┆ Ragtime                ┆ Odeon           ┆ 1985 ┆ 251   ┆ null                            │
│ Mládek, Ivan,    ┆ Ragtime-coctail        ┆ Panton          ┆ 1985 ┆ 13    ┆ null                            │
│ Joplin, Scott,   ┆ Original rags. Ragtime ┆ Panton          ┆ 1988 ┆ 5     ┆ Chvilka s kytarou               │
│ Doctorow, E. L., ┆ Ragtime                ┆ Odeon           ┆ 1989 ┆ 241   ┆ null                            │
│ Doctorow, E. L., ┆ Ragtime                ┆ Levné knihy KMa ┆ 2000 ┆ 259   ┆ Edice světových autorů          │
│ Doctorow, E. L., ┆ Ragtime                ┆ Euromedia Group ┆ 2005 ┆ 222   ┆ Světová literatura Lidových no… │
└──────────────────┴────────────────────────┴─────────────────┴──────┴───────┴─────────────────────────────────┘

In [147]:
edice("Světová literatura Lidových n")

shape: (61, 5)
┌─────────────────────────────────┬─────────────────────────────────┬──────────────┬──────┬───────┐
│ 100_a                           ┆ 245_a                           ┆ 300_a        ┆ rok  ┆ stran │
│ ---                             ┆ ---                             ┆ ---          ┆ ---  ┆ ---   │
│ str                             ┆ str                             ┆ list[str]    ┆ i64  ┆ i64   │
╞═════════════════════════════════╪═════════════════════════════════╪══════════════╪══════╪═══════╡
│ Hrabal, Bohumil,                ┆ Perlička na dně                 ┆ ["188 s. ;"] ┆ 2005 ┆ 188   │
│ García Márquez, Gabriel,        ┆ Sto roků samoty                 ┆ ["318 s. ;"] ┆ 2005 ┆ 318   │
│ Remarque, Erich Maria,          ┆ Na západní frontě klid          ┆ ["175 s. ;"] ┆ 2005 ┆ 175   │
│ Irving, John,                   ┆ Svět podle Garpa                ┆ ["515 s. ;"] ┆ 2005 ┆ 515   │
│ Škvorecký, Josef,               ┆ Zbabělci                        ┆ ["379 s. ;"] ┆ 2005 ┆ 379   │
│ McEwan, Ian,                    ┆ Betonová zahrada                ┆ ["127 s. ;"] ┆ 2005 ┆ 127   │
│ Capote, Truman,                 ┆ Snídaně u Tiffanyho             ┆ ["92 s. ;"]  ┆ 2005 ┆ 92    │
│ Bulgakov, Michail Afanas‘jevič… ┆ Mistr a Markétka                ┆ ["396 s. ;"] ┆ 2005 ┆ 396   │
│ Kafka, Franz,                   ┆ Proces                          ┆ ["203 s. ;"] ┆ 2005 ┆ 203   │
│ Doctorow, E. L.,                ┆ Ragtime                         ┆ ["222 s. ;"] ┆ 2005 ┆ 222   │
│ Merle, Robert,                  ┆ Smrt je mým řemeslem            ┆ ["299 s. ;"] ┆ 2005 ┆ 299   │
│ Fitzgerald, Francis Scott,      ┆ Něžná je noc                    ┆ ["347 s. ;"] ┆ 2005 ┆ 347   │
│ Puzo, Mario,                    ┆ Kmotr                           ┆ ["390 s. ;"] ┆ 2005 ┆ 390   │
│ Pasternak, Boris Leonidovič,    ┆ Doktor Živago                   ┆ ["540 s. ;"] ┆ 2005 ┆ 540   │
│ Mann, Thomas,                   ┆ Smrt v Benátkách                ┆ ["93 s. ;"]  ┆ 2005 ┆ 93    │
│ Abe, Kōbō,                      ┆ Písečná žena                    ┆ ["174 s. ;"] ┆ 2005 ┆ 174   │
│ Clavell, James,                 ┆ Král Krysa                      ┆ ["397 s. ;"] ┆ 2005 ┆ 397   │
│ McCoy, Horace,                  ┆ Koně se přece střílejí          ┆ ["95 s. ;"]  ┆ 2005 ┆ 95    │
│ Forsyth, Frederick,             ┆ Den pro Šakala                  ┆ ["284 s. ;"] ┆ 2005 ┆ 284   │
│ Fuks, Ladislav,                 ┆ Spalovač mrtvol                 ┆ ["127 s. ;"] ┆ 2005 ┆ 127   │
│ Heller, Joseph,                 ┆ Hlava XXII                      ┆ ["508 s. ;"] ┆ 2005 ┆ 508   │
│ Eastlake, William,              ┆ Hájili jsme hrad                ┆ ["366 s. ;"] ┆ 2005 ┆ 366   │
│ Vonnegut, Kurt,                 ┆ Kolíbka                         ┆ ["206 s. ;"] ┆ 2005 ┆ 206   │
│ Lustig, Arnošt,                 ┆ Modlitba pro Kateřinu Horovitz… ┆ ["125 s. ;"] ┆ 2005 ┆ 125   │
│ Orwell, George,                 ┆ Nadechnout se                   ┆ ["215 s. ;"] ┆ 2005 ┆ 215   │
│ Woolf, Virginia,                ┆ Paní Dallowayová                ┆ ["158 s. ;"] ┆ 2005 ┆ 158   │
│ Faulkner, William,              ┆ Divoké palmy                    ┆ ["253 s. ;"] ┆ 2005 ┆ 253   │
│ Burgess, Anthony,               ┆ Mechanický pomeranč             ┆ ["174 s. ;"] ┆ 2005 ┆ 174   │
│ Dostojevskij, Fedor Michajlovi… ┆ Idiot                           ┆ ["547 s. ;"] ┆ 2005 ┆ 547   │
│ Greene, Graham,                 ┆ Jádro věci                      ┆ ["269 s. ;"] ┆ 2005 ┆ 269   │
│ Morrison, Toni,                 ┆ Milovaná                        ┆ ["276 s. ;"] ┆ 2005 ┆ 276   │
│ Vian, Boris,                    ┆ Pěna dní                        ┆ ["172 s. ;"] ┆ 2005 ┆ 172   │
│ Čapek, Karel,                   ┆ Krakatit                        ┆ ["253 s. ;"] ┆ 2005 ┆ 253   │
│ Dürrenmatt, Friedrich,          ┆ Soudce a jeho kat               ┆ ["173 s. ;"] ┆ 2006 ┆ 173   │
│ Bellow, Saul,                   ┆ Herzog                          ┆ ["381 s. ;"] ┆ 2006 ┆ 381   │
│ Moravia, Alberto,               ┆ Nuda                            ┆ ["269 s. ;"] ┆ 2006 ┆ 269   │
│ Duras, Marguerite,              ┆ Milenec                         ┆ ["93 s. ;"]  ┆ 2006 ┆ 93    │
│ Poláček, Karel,                 ┆ Hostinec U kamenného stolu      ┆ ["335 s. ;"] ┆ 2006 ┆ 335   │
│ Ruark, Robert Chester,          ┆ Medojedky                       ┆ ["613 s. ;"] ┆ 2006 ┆ 613   │
│ Rushdie, Salman,                ┆ Východ, Západ                   ┆ ["125 s. ;"] ┆ 2006 ┆ 125   │
│ Zweig, Stefan,                  ┆ Netrpělivost srdce              ┆ ["333 s. ;"] ┆ 2006 ┆ 333   │
│ Kesey, Ken,                     ┆ Vyhoďme ho z kola ven           ┆ ["301 s. ;"] ┆ 2006 ┆ 301   │
│ Chevallier, Gabriel,            ┆ Zvonokosy                       ┆ ["316 s. ;"] ┆ 2006 ┆ 316   │
│ James, Henry,                   ┆ Utažení šroubu                  ┆ ["141 s. ;"] ┆ 2006 ┆ 141   │
│ Malaparte, Curzio,              ┆ Kůže                            ┆ ["315 s. ;"] ┆ 2006 ┆ 315   │
│ Márai, Sándor,                  ┆ Svíce dohořívají                ┆ ["125 s. ;"] ┆ 2006 ┆ 125   │
│ London, Jack,                   ┆ Martin Eden                     ┆ ["342 s. ;"] ┆ 2006 ┆ 342   │
│ Nabokov, Vladimir Vladimirovič… ┆ Třináct do tuctu                ┆ ["157 s. ;"] ┆ 2006 ┆ 157   │
│ Borges, Jorge Luis,             ┆ Obecné dějiny hanebnosti        ┆ ["92 s. ;"]  ┆ 2006 ┆ 92    │
│ Roth, Philip,                   ┆ Portnoyův komplex               ┆ ["219 s. ;"] ┆ 2006 ┆ 219   │
│ Forster, E. M.                  ┆ Cesta do Indie                  ┆ ["333 s. ;"] ┆ 2006 ┆ 333   │
│ Coetzee, J. M.                  ┆ Život a doba Michaela K.        ┆ ["156 s. ;"] ┆ 2006 ┆ 156   │
│ Tomasi di Lampedusa, Giuseppe,  ┆ Gepard                          ┆ ["203 s. ;"] ┆ 2006 ┆ 203   │
│ Boulle, Pierre,                 ┆ Most přes řeku Kwai             ┆ ["156 s. ;"] ┆ 2006 ┆ 156   │
│ Zamjatin, Jevgenij Ivanovič,    ┆ My                              ┆ ["157 s. ;"] ┆ 2006 ┆ 157   │
│ Tanizaki, Jun'ichirō,           ┆ Deník bláznivého starce         ┆ ["125 s. ;"] ┆ 2006 ┆ 125   │
│ Lodge, David,                   ┆ Den zkázy v Britském muzeu      ┆ ["173 s. ;"] ┆ 2006 ┆ 173   │
│ Schlink, Bernhard,              ┆ Předčítač                       ┆ ["141 s. ;"] ┆ 2006 ┆ 141   │
│ Atwood, Margaret,               ┆ Z hlubin                        ┆ ["205 s. ;"] ┆ 2006 ┆ 205   │
│ Vančura, Vladislav,             ┆ Konec starých časů              ┆ ["236 s. ;"] ┆ 2006 ┆ 236   │
│ Stout, Rex,                     ┆ Zlatí pavouci                   ┆ ["207 s. ;"] ┆ 2007 ┆ 207   │
└─────────────────────────────────┴─────────────────────────────────┴──────────────┴──────┴───────┘

In [160]:
zjisti("Jak řešit rovnice a jejich soustavy")

Polytechnická knižnice. Ř. 2, Příručky

shape: (3, 6)
┌───────────────┬─────────────────────────────────┬───────┬──────┬───────┬─────────────────────────────────┐
│ 100_a         ┆ 245_a                           ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                           │
│ ---           ┆ ---                             ┆ ---   ┆ ---  ┆ ---   ┆ ---                             │
│ str           ┆ str                             ┆ str   ┆ i64  ┆ i64   ┆ str                             │
╞═══════════════╪═════════════════════════════════╪═══════╪══════╪═══════╪═════════════════════════════════╡
│ Jarník, Jiří, ┆ Jak řešit rovnice a jejich sou… ┆ SNTL  ┆ 1961 ┆ 266   ┆ Polytechnická knižnice. Ř. 2, … │
│ Jarník, Jiří, ┆ Jak řešit rovnice a jejich sou… ┆ SNTL  ┆ 1969 ┆ 243   ┆ Polytechnická knižnice. Řada 2… │
│ Jarník, Jiří, ┆ Jak řešit rovnice a jejich sou… ┆ SNTL  ┆ 1969 ┆ 243   ┆ Řada polytechn. literatury      │
└───────────────┴─────────────────────────────────┴───────┴──────┴───────┴─────────────────────────────────┘

In [216]:
edice("Polytechnická knižnice")

shape: (465, 4)
┌─────────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                           ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                             ┆ ---                             ┆ ---   ┆ ---  │
│ str                             ┆ str                             ┆ i64   ┆ i64  │
╞═════════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Sackmann, Horst,                ┆ Fysikální chemie                ┆ 283   ┆ 1957 │
│ Kohlmann, Čeněk,                ┆ Aritmetika a algebra            ┆ 228   ┆ 1958 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 213   ┆ 1958 │
│ Košťál, Karel,                  ┆ Sbírka fysikálních vzorců a po… ┆ 213   ┆ 1959 │
│ Andrlík, Karel,                 ┆ Škola fotografie                ┆ 186   ┆ 1959 │
│ Krutina, Jaroslav               ┆ Sbírka vzorců z pružnosti a pe… ┆ 254   ┆ 1959 │
│ Vavruch, Ivan,                  ┆ Koloidní chemie                 ┆ 221   ┆ 1959 │
│ Vinter, Jan                     ┆ Práce se dřevem ve školních dí… ┆ 175   ┆ 1959 │
│ Trnka, Jiří,                    ┆ Natíráme sami                   ┆ 152   ┆ 1959 │
│ Bartoš, Rudolf                  ┆ Vrtulníky                       ┆ 202   ┆ 1959 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 254   ┆ 1959 │
│ Kohlmann, Čeněk,                ┆ Geometrie                       ┆ 253   ┆ 1959 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 234   ┆ 1959 │
│ Haškovec, Ladislav              ┆ Znáte dopravní předpisy?        ┆ 258   ┆ 1959 │
│ Vacek, Adolf                    ┆ Početní tabulky pro techniky    ┆ 208   ┆ 1959 │
│ Michajlov, V. A.                ┆ Fyzikální základy uvolňování j… ┆ 183   ┆ 1959 │
│ Ministr, Zdeněk,                ┆ Prášková metalurgie             ┆ 208   ┆ 1959 │
│ Trávníček, Zdeněk               ┆ Vlákna budoucnosti              ┆ 221   ┆ 1959 │
│ Elstner, František Alexander,   ┆ Vázání uzlů                     ┆ 142   ┆ 1959 │
│ Dragoun, Zdeněk                 ┆ Polovodiče                      ┆ 230   ┆ 1959 │
│ Tajovský, Václav                ┆ Stavitelství                    ┆ 170   ┆ 1959 │
│ Hudec, Josef                    ┆ Elektrické stroje               ┆ 198   ┆ 1959 │
│ Jírů, Pavel,                    ┆ Dřevo, jeho vlastnosti a použi… ┆ 219   ┆ 1960 │
│ Jeřábek, Václav,                ┆ Nové stavební hmoty             ┆ 159   ┆ 1960 │
│ Kubeš, Josef                    ┆ Domovní instalace (voda, kanal… ┆ 174   ┆ 1960 │
│ Reichstädter, Bohumil,          ┆ Co máte vědět o textilu, do ně… ┆ 150   ┆ 1960 │
│ Karen, Ota                      ┆ Radiotechnika pro každého       ┆ 283   ┆ 1960 │
│ Vebr, Jiří                      ┆ Šicí stroje a šití na nich      ┆ 161   ┆ 1960 │
│ Ernest, Ivan,                   ┆ Organická chemie                ┆ 422   ┆ 1960 │
│ Brož, Jaroslav                  ┆ Miniaturní spalovací motorky p… ┆ 165   ┆ 1960 │
│ Nedoma, Woodrow                 ┆ Plyn v domácnosti               ┆ 148   ┆ 1960 │
│ Novák, Milan                    ┆ Exkurze do parní elektrárny     ┆ 142   ┆ 1960 │
│ Beneš, Jan                      ┆ Stavba garáže                   ┆ 225   ┆ 1960 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 209   ┆ 1960 │
│ Košťál, Karel,                  ┆ Sbírka fysikálních vzorců a po… ┆ 264   ┆ 1960 │
│ Petrů, František,               ┆ Atomy, ionty, molekuly          ┆ 210   ┆ 1960 │
│ Hansa, Miloš                    ┆ Jak na to?                      ┆ 176   ┆ 1960 │
│ Smolík, František,              ┆ Využijte lépe svého přijímače   ┆ 192   ┆ 1960 │
│ Chvojka, František              ┆ Bytové doplňky vlastní výroby   ┆ 163   ┆ 1960 │
│ Pechlát, Jaroslav               ┆ Vlastní dílna                   ┆ 178   ┆ 1960 │
│ Velík, Vladimír                 ┆ Základy elektrotechniky         ┆ 226   ┆ 1960 │
│ Ženíšek, Ota                    ┆ Moderní prostředky osobní dopr… ┆ 227   ┆ 1960 │
│ Sedláček, Jiří,                 ┆ Nebojte se matematiky           ┆ 169   ┆ 1960 │
│ Hájek, Miroslav,                ┆ O tkaninách                     ┆ 223   ┆ 1960 │
│ Diomidov, Michail Nikolajevič   ┆ V batyskafu na mořské dno       ┆ 223   ┆ 1961 │
│ Mendygral, Zenon                ┆ Radar dnes a zítra              ┆ 144   ┆ 1961 │
│ Miškovský, Ilja,                ┆ Radioaktivní izotopy v praxi    ┆ 257   ┆ 1961 │
│ Doležal, Jaroslav,              ┆ Vazby knih                      ┆ 229   ┆ 1961 │
│ Čihák, Vlastimil,               ┆ Logaritmické pravítko           ┆ 229   ┆ 1961 │
│ Pazourek, Jaroslav,             ┆ Pracujeme s mikroskopem         ┆ 210   ┆ 1961 │
│ Andrlík, Karel,                 ┆ Škola fotografie                ┆ 188   ┆ 1961 │
│ Poletajev, Igor‘ Andrejevič,    ┆ Kybernetika                     ┆ 429   ┆ 1961 │
│ Stupecký, Josef                 ┆ Abeceda filmového amatéra       ┆ 260   ┆ 1961 │
│ Kubát, Karel                    ┆ Pracujeme s magnetofonem        ┆ 212   ┆ 1961 │
│ Samek, Miloslav                 ┆ Samočinné počítače              ┆ 282   ┆ 1961 │
│ Trnka, Jiří,                    ┆ Natíráme sami                   ┆ 190   ┆ 1961 │
│ Frey, Jakub,                    ┆ Loď, moře, námořníci            ┆ 266   ┆ 1961 │
│ Procházka, Vladimír,            ┆ Technická příručka pro modelář… ┆ 266   ┆ 1961 │
│ Ledvina, Milan                  ┆ Raketové motory                 ┆ 187   ┆ 1961 │
│ Jarník, Jiří,                   ┆ Jak řešit rovnice a jejich sou… ┆ 266   ┆ 1961 │
│ Vasil'jev, Michail Vasil'jevič  ┆ Stroje dneška a budoucnosti     ┆ 172   ┆ 1961 │
│ Koval, Václav,                  ┆ Technika zítřka                 ┆ 225   ┆ 1961 │
│ Hruša, Karel,                   ┆ Řešené úlohy z matematiky       ┆ 190   ┆ 1962 │
│ Bauman, Milan,                  ┆ Vývoj sdělovací techniky        ┆ 251   ┆ 1962 │
│ Hájek, Bohumil,                 ┆ Anorganická chemie              ┆ 245   ┆ 1962 │
│ Kuznecov, Boris Grigor‘jevič,   ┆ O teorii relativity             ┆ 237   ┆ 1962 │
│ Havlíček, Karel,                ┆ Diferenciální počet pro začáte… ┆ 250   ┆ 1962 │
│ Beneš, Jan                      ┆ Stavba garáže                   ┆ 228   ┆ 1962 │
│ Greniewski, Henryk,             ┆ Základy kybernetiky             ┆ 190   ┆ 1962 │
│ Košťál, Karel,                  ┆ Sbírka fyzikálních vzorců a po… ┆ 503   ┆ 1962 │
│ Vanýsek, Vladimír,              ┆ Lety v kosmickém prostoru       ┆ 194   ┆ 1962 │
│ Tyl, Josef                      ┆ Jak jezdit bez nehod            ┆ 239   ┆ 1962 │
│ Pacáková, Libuše                ┆ Velmi krátké vlny a jejich pou… ┆ 219   ┆ 1962 │
│ Erhart, Vilém,                  ┆ Amatérské astronomické dalekoh… ┆ 218   ┆ 1962 │
│ Vinter, Jan                     ┆ Práce se dřevem                 ┆ 182   ┆ 1962 │
│ Pechlát, Jaroslav               ┆ Vlastní dílna                   ┆ 178   ┆ 1962 │
│ Hansa, Miloš                    ┆ Jak na to?                      ┆ 175   ┆ 1962 │
│ Menšík, Miroslav,               ┆ Deskriptivní geometrie          ┆ 207   ┆ 1962 │
│ Setzer, Ota,                    ┆ Deskriptivní geometrie          ┆ 207   ┆ 1962 │
│ Dragoun, Zdeněk                 ┆ Polovodiče                      ┆ 251   ┆ 1962 │
│ Krutina, Jaroslav               ┆ Sbírka vzorců z pružnosti a pe… ┆ 238   ┆ 1962 │
│ Procházka, Vladimír,            ┆ Miniaturní elektromotorky pro … ┆ 142   ┆ 1962 │
│ Trtílek, Josef,                 ┆ Jak porozumíme chemickým vzorc… ┆ 191   ┆ 1962 │
│ Vodnárek, Ladislav              ┆ Diktafony v praxi               ┆ 288   ┆ 1962 │
│ Dvořák, Jiří,                   ┆ Technické křivky                ┆ 229   ┆ 1962 │
│ Havlíček, Karel,                ┆ Integrální počet pro začáteční… ┆ 241   ┆ 1963 │
│ Rychnovský, Richard,            ┆ Obyčejné diferenciální rovnice… ┆ 253   ┆ 1963 │
│ Kuba, Josef,                    ┆ Cesta do nitra hmoty            ┆ 398   ┆ 1963 │
│ Březina, Jan                    ┆ Vodní turbíny                   ┆ 162   ┆ 1963 │
│ Horna, Otakar A.                ┆ Zajímavá zapojení s tranzistor… ┆ 176   ┆ 1963 │
│ Vaculík, Jaroslav,              ┆ Rekreační ubytování             ┆ 191   ┆ 1963 │
│ Augusta, Ivo                    ┆ O stavebních konstrukcích       ┆ 229   ┆ 1963 │
│ Bieber, Boleslav                ┆ Chemická laboratoř              ┆ 226   ┆ 1963 │
│ Myslivec, Jaroslav              ┆ Tranzistorové magnetofony       ┆ 219   ┆ 1963 │
│ Barta, Rudolf,                  ┆ Sklářství                       ┆ 196   ┆ 1963 │
│ Rychnovský, Richard,            ┆ Parciální diferenciální rovnic… ┆ 167   ┆ 1963 │
│ Täubl, Karel,                   ┆ Zlatnictví                      ┆ 169   ┆ 1963 │
│ Mareš, Karel,                   ┆ Výrobní práce žáků a výroba     ┆ 150   ┆ 1963 │
│ Koškin, N. J.                   ┆ Základy fyziky                  ┆ 198   ┆ 1963 │
│ Jungmann, Bohumil               ┆ Technologie strojírenské výrob… ┆ 281   ┆ 1963 │
│ Ondříček, Miroslav              ┆ Zdroje a využití energie        ┆ 177   ┆ 1963 │
│ Florov, Vasilij Arkad'jevič     ┆ Kovy budoucnosti                ┆ 210   ┆ 1963 │
│ Bauman, Milan,                  ┆ Za televizní obrazovkou         ┆ 190   ┆ 1963 │
│ Růžička, Primus,                ┆ Diamanty a jejich použití v pr… ┆ 114   ┆ 1963 │
│ Gruncl, Ladislav                ┆ Elektrické přístroje mladého t… ┆ 180   ┆ 1963 │
│ Wittmers, Hugo                  ┆ Úvod do regulační techniky      ┆ 197   ┆ 1963 │
│ Erhart, Vilém,                  ┆ Amatérské astronomické fotogra… ┆ 199   ┆ 1963 │
│ Bláha, Richard,                 ┆ Exkurze do tiskárny             ┆ 162   ┆ 1963 │
│ Ernest, Ivan,                   ┆ Organická chemie                ┆ 334   ┆ 1964 │
│ Mašek, Ladislav                 ┆ Úprava bytového interiéru       ┆ 209   ┆ 1964 │
│ Gruncl, Ladislav                ┆ Přístroje a stroje vlastní výr… ┆ 176   ┆ 1964 │
│ Říman, Evžen,                   ┆ Fyzika                          ┆ 199   ┆ 1964 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 181   ┆ 1964 │
│ Andrlík, Karel,                 ┆ Analytická chemie               ┆ 190   ┆ 1964 │
│ Boublík, Vlastimil,             ┆ Lepidla a jejich příprava       ┆ 189   ┆ 1964 │
│ Valsa, Juraj,                   ┆ Televizní technika              ┆ 149   ┆ 1964 │
│ Dočkal, Jiří,                   ┆ Údržba a opravy mopedů          ┆ 170   ┆ 1964 │
│ Kubeš, Josef                    ┆ Domovní instalace (voda a plyn… ┆ 137   ┆ 1964 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 182   ┆ 1964 │
│ Procházka, Arnold               ┆ Hydraulika v příkladech a poku… ┆ 164   ┆ 1964 │
│ Říman, Evžen,                   ┆ Příklady z fyziky               ┆ 148   ┆ 1964 │
│ Polák, Vilém                    ┆ Využití umělého chladu          ┆ 203   ┆ 1964 │
│ Pazderák, Jiří,                 ┆ Barevná televize                ┆ 183   ┆ 1964 │
│ Košťál, Karel,                  ┆ Sbírka fyzikálních vzorců a po… ┆ 387   ┆ 1964 │
│ Richter, A.                     ┆ Proudová výroba                 ┆ 130   ┆ 1964 │
│ Bartoň, Jan                     ┆ ABC zajímavostí v elektrotechn… ┆ 86    ┆ 1965 │
│ Fišner, Boleslav,               ┆ Chemie                          ┆ 221   ┆ 1965 │
│ Reisenauer, Roman               ┆ Metody matematické statistiky … ┆ 208   ┆ 1965 │
│ Walla, Viktor                   ┆ Kaličství v kostce              ┆ 154   ┆ 1965 │
│ Klepl, Václav,                  ┆ Jak číst schémata v radiotechn… ┆ 175   ┆ 1965 │
│ Mašek, Ladislav                 ┆ Úprava bytového interiéru       ┆ 209   ┆ 1965 │
│ Schätz, Miroslav,               ┆ Kaučuk                          ┆ 178   ┆ 1965 │
│ Keck, Christian                 ┆ Urychlovače částic              ┆ 139   ┆ 1965 │
│ Březina, Jan                    ┆ Parní a plynové turbíny         ┆ 161   ┆ 1965 │
│ Boublík, Vlastimil,             ┆ Práce s plastickými hmotami     ┆ 216   ┆ 1965 │
│ Pospíšil, Antonín,              ┆ Zopakujme si deskriptivu        ┆ 130   ┆ 1965 │
│ Wideman, František              ┆ Základy, stropy a krovy         ┆ 192   ┆ 1965 │
│ Dobrovolný, Bohumil,            ┆ 250 amerických zlepšovacích ná… ┆ 94    ┆ 1965 │
│ Bruthans, Vladimír,             ┆ Matematika                      ┆ 164   ┆ 1965 │
│ Taraba, Oldřich,                ┆ Zázraky světla - lasery         ┆ 65    ┆ 1965 │
│ Novák, Karel                    ┆ Amatérské součástky a stavba t… ┆ 214   ┆ 1965 │
│ Havlíček, Karel,                ┆ Diferenciální počet pro začáte… ┆ 195   ┆ 1965 │
│ Říman, Evžen,                   ┆ Fyzika s příklady a úlohami     ┆ 349   ┆ 1966 │
│ Nor, A. C.,                     ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Nor, A. C.,                     ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Staněk, Milan                   ┆ 100 tranzistorových přístrojů   ┆ 133   ┆ 1966 │
│ Dobrovolný, Bohumil,            ┆ 250 novinek ze světové technol… ┆ 74    ┆ 1966 │
│ Boublík, Vlastimil,             ┆ Lití plastických hmot pro mode… ┆ 199   ┆ 1966 │
│ Elstner, František Alexander,   ┆ Vázání uzlů                     ┆ 137   ┆ 1966 │
│ Válek, Jiří                     ┆ Úvod do elektroniky             ┆ 195   ┆ 1966 │
│ Boublík, Vlastimil,             ┆ Lepidla a jejich příprava       ┆ 190   ┆ 1966 │
│ Štěpánský, Václav,              ┆ Nomogramy                       ┆ 186   ┆ 1966 │
│ Procházka, Arnold               ┆ Základy mechaniky vody v praxi  ┆ 125   ┆ 1966 │
│ Slavíček, Ivan                  ┆ Tranzistory řídí techniku       ┆ 152   ┆ 1966 │
│ Štěpán, Miroslav,               ┆ Chemie v denním životě          ┆ 171   ┆ 1966 │
│ Procházka, Jan,                 ┆ Zázraky divadla                 ┆ 108   ┆ 1966 │
│ Tříska, Jiří,                   ┆ Základní elektrotechnické tabu… ┆ 260   ┆ 1966 │
│ Jeřábek, Václav,                ┆ Obnova a údržba malých staveb   ┆ 149   ┆ 1966 │
│ Novák, Karel                    ┆ Amatérská oprava tranzistorové… ┆ 171   ┆ 1966 │
│ Václavovič, Antonín,            ┆ Umění konstruovat               ┆ 189   ┆ 1966 │
│ Menšík, Miroslav,               ┆ Deskriptivní geometrie          ┆ 224   ┆ 1966 │
│ Seidler, Alois                  ┆ Tabulky normalizovaných závitů… ┆ 316   ┆ 1966 │
│ Beneš, Oldřich                  ┆ 1111 nápadů pro motoristy a dí… ┆ 255   ┆ 1966 │
│ Mašek, Ladislav                 ┆ Úprava bytového interiéru       ┆ 209   ┆ 1967 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 165   ┆ 1967 │
│ Frey, Jakub,                    ┆ Loď, moře, námořníci            ┆ 209   ┆ 1967 │
│ Tauš, Gustav,                   ┆ Pokusy z radiotechniky          ┆ 277   ┆ 1967 │
│ Beneš, Oldřich                  ┆ 1111 nápadů pro motoristy a dí… ┆ 254   ┆ 1967 │
│ Hájek, Bohumil,                 ┆ Anorganická chemie              ┆ 194   ┆ 1967 │
│ Dobrovolný, Bohumil,            ┆ Nové matematické rekreace       ┆ 157   ┆ 1967 │
│ Husička, Karel                  ┆ Využijte lépe svůj magnetofon   ┆ 177   ┆ 1967 │
│ Budlovský, Jaroslav,            ┆ Motory                          ┆ 169   ┆ 1967 │
│ Nečásek, Sláva                  ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Nečásek, Sláva                  ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Urban, Eduard                   ┆ Mosty - jeden z divů světa      ┆ 146   ┆ 1967 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 208   ┆ 1967 │
│ Čermák, Miloš,                  ┆ Sbírka úloh z matematiky        ┆ 250   ┆ 1967 │
│ Vykoukal, Rudolf,               ┆ Automobilové a motocyklové mot… ┆ 196   ┆ 1967 │
│ Seidler, Alois                  ┆ Tabulky normalizovaných závitů… ┆ 318   ┆ 1967 │
│ Břízová, Joza,                  ┆ Technika mění domácnost         ┆ 153   ┆ 1967 │
│ Tůma, Jan,                      ┆ Vyučovací stroje                ┆ 205   ┆ 1967 │
│ Šindelář, Václav,               ┆ Zopakujme si fyziku             ┆ 210   ┆ 1967 │
│ Hanuš, Bohuslav                 ┆ Amatérská stavba elektrických … ┆ 184   ┆ 1967 │
│ Fišner, Boleslav,               ┆ Chemie                          ┆ 229   ┆ 1967 │
│ Petrů, František,               ┆ Atomy, ionty, molekuly          ┆ 170   ┆ 1968 │
│ Batka, Vilém,                   ┆ 100 příkladů z lineárních elek… ┆ 152   ┆ 1968 │
│ Kubeš, Josef                    ┆ Domovní instalace               ┆ 174   ┆ 1968 │
│ Měšťan, Radomír                 ┆ Opravujeme byt a rodinný domek  ┆ 243   ┆ 1968 │
│ Měšťan, Radomír                 ┆ Opravujeme byt a rodinný domek  ┆ 243   ┆ 1968 │
│ Vokoun, Jaroslav,               ┆ Moderní osvětlení do bytu       ┆ 127   ┆ 1968 │
│ Čuma, Miroslav                  ┆ Pokrokové způsoby ostření řezn… ┆ 133   ┆ 1968 │
│ Krňák, Rudolf                   ┆ 500 novinek ze svařování - mal… ┆ 155   ┆ 1968 │
│ Jozífek, Vítězslav,             ┆ Počítáme na logaritmickém prav… ┆ 132   ┆ 1968 │
│ Hyan, Jaroslav,                 ┆ Amatérská stereofonie           ┆ 191   ┆ 1968 │
│ Gregora, Otakar,                ┆ Normy strojnického kreslení     ┆ 226   ┆ 1968 │
│ Slavíček, Ivan                  ┆ Elektromotorky a jejich řízení  ┆ 237   ┆ 1968 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 133   ┆ 1969 │
│ Sedláček, Jiří,                 ┆ Nebojte se matematiky           ┆ 135   ┆ 1969 │
│ Zahradník, Josef                ┆ Lineární programování při říze… ┆ 231   ┆ 1969 │
│ Chalupský, Ladislav,            ┆ 100x o umělém osvětlení         ┆ 278   ┆ 1969 │
│ Johánek, Tomáš                  ┆ 500 příkladů úsporného konstru… ┆ 122   ┆ 1969 │
│ Dobrovolný, Bohumil,            ┆ Automaty si děláme sami         ┆ 132   ┆ 1969 │
│ Škoda, Zdeněk                   ┆ Elektronika v motorovém vozidl… ┆ 163   ┆ 1969 │
│ Jarník, Jiří,                   ┆ Jak řešit rovnice a jejich sou… ┆ 243   ┆ 1969 │
│ Klepl, Václav,                  ┆ Jak číst schémata v radiotechn… ┆ 239   ┆ 1969 │
│ Karaus, Evžen,                  ┆ Teplo našim domovům             ┆ 145   ┆ 1969 │
│ Šindelář, Karel,                ┆ Analytická geometrie pro začát… ┆ 237   ┆ 1969 │
│ Paulín, Zdeněk                  ┆ 100 zajímavostí z radiotechnik… ┆ 157   ┆ 1969 │
│ Havlíček, Karel,                ┆ Integrální počet pro začáteční… ┆ 207   ┆ 1969 │
│ Dobrovolný, Bohumil,            ┆ Matematické rekreace            ┆ 131   ┆ 1969 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 133   ┆ 1970 │
│ Kulhánek, Jaroslav,             ┆ Fotografické tabulky            ┆ 216   ┆ 1970 │
│ Štěpánský, Václav,              ┆ Nomogramy                       ┆ 248   ┆ 1970 │
│ Chytil, Metoděj                 ┆ Zajímavá použití samočinných p… ┆ 131   ┆ 1970 │
│ Reisenauer, Roman               ┆ Metody matematické statistiky … ┆ 239   ┆ 1970 │
│ Košťál, Karel,                  ┆ Sbírka fyzikálních vzorců a po… ┆ 407   ┆ 1970 │
│ Bruthans, Vladimír,             ┆ Matematika                      ┆ 164   ┆ 1970 │
│ Rychnovský, Richard,            ┆ Parciální diferenciální rovnic… ┆ 167   ┆ 1970 │
│ Měšťan, Radomír                 ┆ Opravujeme byt a rodinný domek  ┆ 243   ┆ 1970 │
│ Nečásek, Sláva                  ┆ Výběr zajímavých zapojení       ┆ 256   ┆ 1970 │
│ Kolek, Lubomír                  ┆ Přehled vzorců středoškolské m… ┆ 323   ┆ 1970 │
│ Krištoufek, Karel,              ┆ Matematické stroje              ┆ 197   ┆ 1970 │
│ Slavíček, Ivan                  ┆ 500 tranzistorových obvodů      ┆ 222   ┆ 1970 │
│ Jelínek, Vladimír,              ┆ Stavby rodinných domků, rekrea… ┆ 222   ┆ 1970 │
│ Batka, Vilém,                   ┆ Elektromagnetismus              ┆ 157   ┆ 1970 │
│ Michal, Stanislav               ┆ Perpetuum mobile včera a dnes   ┆ 185   ┆ 1971 │
│ Prágerová, Alena                ┆ Diferenční rovnice              ┆ 115   ┆ 1971 │
│ Švercl, Josef                   ┆ Zobrazovací metody              ┆ 227   ┆ 1971 │
│ Staňková, Jaroslava,            ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │
│ Staňková, Jaroslava,            ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │

In [218]:
zjisti("Normy strojnického kreslení")

Polytechnická knižnice. Řada 1, Technický výběr do kapsy

shape: (1, 6)
┌──────────────────┬─────────────────────────────┬───────┬──────┬───────┬─────────────────────────────────┐
│ 100_a            ┆ 245_a                       ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                           │
│ ---              ┆ ---                         ┆ ---   ┆ ---  ┆ ---   ┆ ---                             │
│ str              ┆ str                         ┆ str   ┆ i64  ┆ i64   ┆ str                             │
╞══════════════════╪═════════════════════════════╪═══════╪══════╪═══════╪═════════════════════════════════╡
│ Gregora, Otakar, ┆ Normy strojnického kreslení ┆ Práce ┆ 1968 ┆ 226   ┆ Polytechnická knižnice. Řada 1… │
└──────────────────┴─────────────────────────────┴───────┴──────┴───────┴─────────────────────────────────┘

In [222]:
edice("Technický výběr do kapsy")

shape: (135, 4)
┌───────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                 ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                   ┆ ---                             ┆ ---   ┆ ---  │
│ str                   ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Sadoul, Georges,      ┆ Zázraky filmu                   ┆ 230   ┆ 1958 │
│ Dobrovolný, Bohumil,  ┆ Zopakujme si elektrotechniku    ┆ 191   ┆ 1958 │
│ Vacek, Adolf          ┆ Logaritmické tabulky a výpočty  ┆ 129   ┆ 1958 │
│ Žalud, Karel          ┆ Rychlosti, vzdálenosti          ┆ 175   ┆ 1958 │
│ Dobrovolný, Bohumil,  ┆ Technika v kostce               ┆ 199   ┆ 1958 │
│ Andrlík, Karel,       ┆ Zopakujme si chemii             ┆ 177   ┆ 1958 │
│ Tříska, Jiří,         ┆ Elektroautomatiky v průmyslu    ┆ 138   ┆ 1958 │
│ Roček, Vladimír       ┆ Pokrokové konstrukce obráběcíc… ┆ 171   ┆ 1958 │
│ Taraba, Oldřich,      ┆ Co dovede ultrazvuk             ┆ 154   ┆ 1958 │
│ Vacek, Adolf          ┆ Zopakujme si matematiku         ┆ 135   ┆ 1959 │
│ Chalupa, Zdeněk       ┆ Atom dobývá svět                ┆ 191   ┆ 1959 │
│ Krutina, Jaroslav     ┆ Zopakujme si mechaniku          ┆ 158   ┆ 1959 │
│ Tříska, Jiří,         ┆ Základní elektrotechnické tabu… ┆ 190   ┆ 1959 │
│ Blabolil, František   ┆ Plastické hmoty ve strojírenst… ┆ 216   ┆ 1959 │
│ Bartoň, Jan           ┆ Novinky v radiotechnice         ┆ 109   ┆ 1959 │
│ Tomsa, Milan,         ┆ Zázraky televize                ┆ 137   ┆ 1959 │
│ Ženíšek, Ota          ┆ Moderní letectví                ┆ 105   ┆ 1959 │
│ Dobrovolný, Bohumil,  ┆ Pokrokové konstrukce lisovacíc… ┆ 163   ┆ 1959 │
│ Dobrovolný, Bohumil,  ┆ Technologie v kostce            ┆ 141   ┆ 1959 │
│ Dobrovolný, Bohumil,  ┆ 500 vtipných nápadů pro dílny   ┆ 138   ┆ 1960 │
│ Růžička, Bohuslav     ┆ Zopakujme si technické kreslen… ┆ 143   ┆ 1960 │
│ Netušil, Jaroslav,    ┆ Světlo v teorii a v praxi       ┆ 173   ┆ 1960 │
│ Kolář, Jan            ┆ Pod zemí pracují stroje         ┆ 183   ┆ 1960 │
│ Blabolil, František   ┆ Novinky v oboru plastických hm… ┆ 53    ┆ 1960 │
│ Wimmer, Miloslav,     ┆ Základní stavební tabulky       ┆ 169   ┆ 1960 │
│ Dvořák, Josef,        ┆ Do kosmického prostoru          ┆ 129   ┆ 1960 │
│ Lukeš, Jaroslav,      ┆ Novinky v radiotechnice         ┆ 50    ┆ 1960 │
│ Körbler, Vladimír     ┆ Budujeme moderní chemický prům… ┆ 171   ┆ 1960 │
│ Václavovič, Antonín,  ┆ Pokrokové způsoby měření ve vý… ┆ 159   ┆ 1960 │
│ Chalupa, Zdeněk       ┆ Novinky v atomistice            ┆ 41    ┆ 1960 │
│ Šindelář, Václav,     ┆ Zopakujme si fysiku             ┆ 158   ┆ 1960 │
│ Hošek, Josef,         ┆ Novinky v letectví              ┆ 48    ┆ 1960 │
│ Dobrovolný, Bohumil,  ┆ Matematické rekreace            ┆ 139   ┆ 1961 │
│ Melzer, Zdeněk        ┆ Maloobsahová vozidla            ┆ 147   ┆ 1961 │
│ Pacák, Miroslav,      ┆ Vyšší škola radiotechniky       ┆ 161   ┆ 1961 │
│ Šebek, Otto,          ┆ Co nevíte o meteorologii        ┆ 136   ┆ 1961 │
│ Andrlík, Karel,       ┆ Základní chemické tabulky       ┆ 159   ┆ 1961 │
│ Klir, George J.,      ┆ Matematické stroje              ┆ 163   ┆ 1961 │
│ Dobrovolný, Bohumil,  ┆ Slovníček nové techniky         ┆ 134   ┆ 1961 │
│ Vrdlovec, Jan         ┆ 200 technických zlepšení z čes… ┆ 117   ┆ 1961 │
│ Staněk, Milan         ┆ 100 tranzistorových přístrojů   ┆ 120   ┆ 1961 │
│ Dobrovolný, Bohumil,  ┆ Nástrojařství v kostce          ┆ 170   ┆ 1962 │
│ Taraba, Oldřich,      ┆ Elektronická měření v průmyslu  ┆ 203   ┆ 1962 │
│ Wimmer, Miloslav,     ┆ Základní stavební tabulky       ┆ 148   ┆ 1962 │
│ Vacek, Adolf          ┆ Logaritmické a početní tabulky  ┆ 130   ┆ 1962 │
│ Krňák, Rudolf         ┆ Zopakujme si svařování          ┆ 159   ┆ 1962 │
│ Pacák, Miroslav,      ┆ Vyšší škola radiotechniky       ┆ 181   ┆ 1962 │
│ Hošek, Josef,         ┆ Dnešní letectví                 ┆ 170   ┆ 1962 │
│ Schneider, Jaroslav,  ┆ Práce v chemické laboratoři     ┆ 137   ┆ 1962 │
│ Klepl, Václav,        ┆ Elektrotechnika v příkladech    ┆ 205   ┆ 1962 │
│ Krutina, Jaroslav     ┆ Zopakujme si statiku            ┆ 157   ┆ 1962 │
│ Vacek, Adolf          ┆ Pokrokové konstrukce a výpočty… ┆ 169   ┆ 1962 │
│ Paulín, Zdeněk        ┆ Zázraky zvuku                   ┆ 173   ┆ 1962 │
│ Sadoul, Georges,      ┆ Zázraky filmu                   ┆ 205   ┆ 1962 │
│ Teplý, Stanislav      ┆ Stavitelství a architektura v … ┆ 168   ┆ 1963 │
│ Roček, Vladimír       ┆ Tabulky z konstrukce nástrojů   ┆ 142   ┆ 1963 │
│ Taraba, Oldřich,      ┆ Co dovede ultrazvuk             ┆ 158   ┆ 1963 │
│ Pokorný, Václav       ┆ Lícovací a dílenské tabulky IS… ┆ 129   ┆ 1963 │
│ Krutina, Jaroslav     ┆ Zopakujme si pružnost a pevnos… ┆ 123   ┆ 1963 │
│ Nussberger, Jaroslav, ┆ Zopakujme si optiku             ┆ 139   ┆ 1963 │
│ Dobrovolný, Bohumil,  ┆ 500 technologických nápadů ze … ┆ 147   ┆ 1963 │
│ Kouba, Jaroslav       ┆ Malý přehled vzorců             ┆ 137   ┆ 1963 │
│ Baran, Ludvík,        ┆ Zázraky fotografie              ┆ 147   ┆ 1964 │
│ Staněk, Milan         ┆ 100 tranzistorových přístrojů   ┆ 130   ┆ 1964 │
│ Pokorný, Václav       ┆ Soustružnictví v kostce         ┆ 142   ┆ 1964 │
│ Ruml, Vladimír        ┆ Zopakujme si technické materiá… ┆ 191   ┆ 1964 │
│ Šulc, Jan             ┆ Zázraky úzkého filmu            ┆ 175   ┆ 1964 │
│ Verunáč, Václav,      ┆ Technika kosmického věku        ┆ 94    ┆ 1964 │
│ Pavlík, Miloslav,     ┆ Rady a recepty pro dílny        ┆ 181   ┆ 1964 │
│ Dobrovolný, Bohumil,  ┆ 500 novinek z mechanizace a au… ┆ 133   ┆ 1964 │
│ Řeháček, Emil         ┆ Ozubená kola                    ┆ 158   ┆ 1964 │
│ Nečásek, Sláva        ┆ 100 zajímavých okruhů z elektr… ┆ 114   ┆ 1964 │
│ Ehleman, Jan,         ┆ Stroje pracují v administrativ… ┆ 191   ┆ 1964 │
│ Bartoň, Jan           ┆ ABC zajímavostí v elektrotechn… ┆ 86    ┆ 1965 │
│ Walla, Viktor         ┆ Kaličství v kostce              ┆ 154   ┆ 1965 │
│ Klepl, Václav,        ┆ Jak číst schémata v radiotechn… ┆ 175   ┆ 1965 │
│ Schätz, Miroslav,     ┆ Kaučuk                          ┆ 178   ┆ 1965 │
│ Keck, Christian       ┆ Urychlovače částic              ┆ 139   ┆ 1965 │
│ Pospíšil, Antonín,    ┆ Zopakujme si deskriptivu        ┆ 130   ┆ 1965 │
│ Dobrovolný, Bohumil,  ┆ 250 amerických zlepšovacích ná… ┆ 94    ┆ 1965 │
│ Taraba, Oldřich,      ┆ Zázraky světla - lasery         ┆ 65    ┆ 1965 │
│ Nečásek, Sláva        ┆ 100 zajímavých okruhů z elektr… ┆ 114   ┆ 1965 │
│ Nor, A. C.,           ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Nor, A. C.,           ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Staněk, Milan         ┆ 100 tranzistorových přístrojů   ┆ 133   ┆ 1966 │
│ Dobrovolný, Bohumil,  ┆ 250 novinek ze světové technol… ┆ 74    ┆ 1966 │
│ Procházka, Arnold     ┆ Základy mechaniky vody v praxi  ┆ 125   ┆ 1966 │
│ Slavíček, Ivan        ┆ Tranzistory řídí techniku       ┆ 152   ┆ 1966 │
│ Štěpán, Miroslav,     ┆ Chemie v denním životě          ┆ 171   ┆ 1966 │
│ Procházka, Jan,       ┆ Zázraky divadla                 ┆ 108   ┆ 1966 │
│ Tříska, Jiří,         ┆ Základní elektrotechnické tabu… ┆ 260   ┆ 1966 │
│ Václavovič, Antonín,  ┆ Umění konstruovat               ┆ 189   ┆ 1966 │
│ Seidler, Alois        ┆ Tabulky normalizovaných závitů… ┆ 316   ┆ 1966 │
│ Beneš, Oldřich        ┆ 1111 nápadů pro motoristy a dí… ┆ 255   ┆ 1966 │
│ Frey, Jakub,          ┆ Loď, moře, námořníci            ┆ 209   ┆ 1967 │
│ Beneš, Oldřich        ┆ 1111 nápadů pro motoristy a dí… ┆ 254   ┆ 1967 │
│ Dobrovolný, Bohumil,  ┆ Nové matematické rekreace       ┆ 157   ┆ 1967 │
│ Budlovský, Jaroslav,  ┆ Motory                          ┆ 169   ┆ 1967 │
│ Nečásek, Sláva        ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Nečásek, Sláva        ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Urban, Eduard         ┆ Mosty - jeden z divů světa      ┆ 146   ┆ 1967 │
│ Vykoukal, Rudolf,     ┆ Automobilové a motocyklové mot… ┆ 196   ┆ 1967 │
│ Seidler, Alois        ┆ Tabulky normalizovaných závitů… ┆ 318   ┆ 1967 │
│ Břízová, Joza,        ┆ Technika mění domácnost         ┆ 153   ┆ 1967 │
│ Šindelář, Václav,     ┆ Zopakujme si fyziku             ┆ 210   ┆ 1967 │
│ Batka, Vilém,         ┆ 100 příkladů z lineárních elek… ┆ 152   ┆ 1968 │
│ Čuma, Miroslav        ┆ Pokrokové způsoby ostření řezn… ┆ 133   ┆ 1968 │
│ Krňák, Rudolf         ┆ 500 novinek ze svařování - mal… ┆ 155   ┆ 1968 │
│ Jozífek, Vítězslav,   ┆ Počítáme na logaritmickém prav… ┆ 132   ┆ 1968 │
│ Gregora, Otakar,      ┆ Normy strojnického kreslení     ┆ 226   ┆ 1968 │
│ Slavíček, Ivan        ┆ Elektromotorky a jejich řízení  ┆ 237   ┆ 1968 │
│ Šimek, Jaroslav,      ┆ Fotografické techniky           ┆ 110   ┆ 1969 │
│ Zahradník, Josef      ┆ Lineární programování při říze… ┆ 231   ┆ 1969 │
│ Chalupský, Ladislav,  ┆ 100x o umělém osvětlení         ┆ 278   ┆ 1969 │
│ Johánek, Tomáš        ┆ 500 příkladů úsporného konstru… ┆ 122   ┆ 1969 │
│ Dobrovolný, Bohumil,  ┆ Automaty si děláme sami         ┆ 132   ┆ 1969 │
│ Tunys, Ladislav,      ┆ Film mění tvář                  ┆ 186   ┆ 1969 │
│ Klepl, Václav,        ┆ Jak číst schémata v radiotechn… ┆ 239   ┆ 1969 │
│ Kameník, Karel,       ┆ 8 mm film standard a super v p… ┆ 167   ┆ 1969 │
│ Karaus, Evžen,        ┆ Teplo našim domovům             ┆ 145   ┆ 1969 │
│ Paulín, Zdeněk        ┆ 100 zajímavostí z radiotechnik… ┆ 157   ┆ 1969 │
│ Dobrovolný, Bohumil,  ┆ Matematické rekreace            ┆ 131   ┆ 1969 │
│ Kulhánek, Jaroslav,   ┆ Fotografické tabulky            ┆ 216   ┆ 1970 │
│ Chytil, Metoděj       ┆ Zajímavá použití samočinných p… ┆ 131   ┆ 1970 │
│ Nečásek, Sláva        ┆ Výběr zajímavých zapojení       ┆ 256   ┆ 1970 │
│ Krištoufek, Karel,    ┆ Matematické stroje              ┆ 197   ┆ 1970 │
│ Slavíček, Ivan        ┆ 500 tranzistorových obvodů      ┆ 222   ┆ 1970 │
│ Batka, Vilém,         ┆ Elektromagnetismus              ┆ 157   ┆ 1970 │
│ Pavlík, Miloslav,     ┆ Recepty a rady pro dílny        ┆ 189   ┆ 1971 │
│ Opava, Zdeněk,        ┆ Jak sestrojovat spojnicové nom… ┆ 167   ┆ 1972 │
│ Ziegelheim, Otakar,   ┆ Obvody s křemíkovými diodami a… ┆ 174   ┆ 1973 │
│ Krutina, Jaroslav     ┆ Sbírka vzorců z pružnosti a pe… ┆ 234   ┆ 1973 │
│ Dobrovolný, Bohumil,  ┆ Dílenská matematika             ┆ 223   ┆ 1974 │
│ Peřina, František     ┆ Atomy slouží člověku            ┆ 108   ┆ 1976 │
│ Janda, Vladimír,      ┆ Integrovaná elektronika pro ka… ┆ 241   ┆ 1977 │
└───────────────────────┴─────────────────────────────────┴───────┴──────┘

In [162]:
edice("Řada polytechn. literatury")

shape: (41, 4)
┌──────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                        ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                          ┆ ---                             ┆ ---   ┆ ---  │
│ str                          ┆ str                             ┆ i64   ┆ i64  │
╞══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Boublík, Vlastimil,          ┆ Lití plastických hmot pro mode… ┆ 199   ┆ 1966 │
│ Válek, Jiří                  ┆ Úvod do elektroniky             ┆ 195   ┆ 1966 │
│ Boublík, Vlastimil,          ┆ Lepidla a jejich příprava       ┆ 190   ┆ 1966 │
│ Štěpánský, Václav,           ┆ Nomogramy                       ┆ 186   ┆ 1966 │
│ Procházka, Arnold            ┆ Základy mechaniky vody v praxi  ┆ 125   ┆ 1966 │
│ Fišner, Boleslav,            ┆ Chemie                          ┆ 229   ┆ 1967 │
│ Sedláček, Jiří,              ┆ Nebojte se matematiky           ┆ 135   ┆ 1969 │
│ Jarník, Jiří,                ┆ Jak řešit rovnice a jejich sou… ┆ 243   ┆ 1969 │
│ Beránek, Robert,             ┆ Úprava okolí chaty nebo rodinn… ┆ 133   ┆ 1970 │
│ Košťál, Karel,               ┆ Sbírka fyzikálních vzorců a po… ┆ 407   ┆ 1970 │
│ Kolek, Lubomír               ┆ Přehled vzorců středoškolské m… ┆ 323   ┆ 1970 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │
│ Toř, Zdeněk                  ┆ Fyzika v příkladech             ┆ 250   ┆ 1971 │
│ Rejman, Martin,              ┆ Co a jak s polyesterovými skel… ┆ 94    ┆ 1972 │
│ Slánský, Bohuslav,           ┆ Technika v malířské tvorbě      ┆ 186   ┆ 1973 │
│ Štulík, Václav               ┆ Jak fotografovat                ┆ 149   ┆ 1973 │
│ Štěpán, Jan                  ┆ Motorové čluny                  ┆ 275   ┆ 1973 │
│ Tůma, Jan,                   ┆ Nebojte se promítání!           ┆ 211   ┆ 1973 │
│ Šulc, Jan                    ┆ Jednoduchá měření pro amatéry   ┆ 106   ┆ 1973 │
│ Tausk, Petr,                 ┆ Materiály pro černobílou fotog… ┆ 125   ┆ 1973 │
│ Tausk, Petr,                 ┆ Materiály pro černobílou fotog… ┆ 125   ┆ 1973 │
│ Vinter, Jan                  ┆ Práce se dřevem                 ┆ 139   ┆ 1973 │
│ Kusl, František              ┆ Příručka pro domácí dílnu       ┆ 179   ┆ 1973 │
│ Beneš, Jan                   ┆ Stavba garáže                   ┆ 213   ┆ 1974 │
│ Jukl, Alois,                 ┆ Vytápěcí zařízení pro byty a d… ┆ 193   ┆ 1974 │
│ Beránek, Robert,             ┆ Úprava okolí chaty nebo rodinn… ┆ 177   ┆ 1974 │
│ Kusl, František              ┆ Příručka pro domácí dílnu       ┆ 179   ┆ 1974 │
│ Šustr, Karel                 ┆ Elektrické rozvody a zařízení … ┆ 183   ┆ 1974 │
│ Šustr, Karel                 ┆ Elektrické rozvody a zařízení … ┆ 183   ┆ 1975 │
│ Täubl, Karel,                ┆ Zlatnictví                      ┆ 199   ┆ 1975 │
│ Šmok, Ján,                   ┆ Diapozitivy v praxi             ┆ 289   ┆ 1975 │
│ Svoboda, Antonín             ┆ Mikrofilm v praxi               ┆ 340   ┆ 1976 │
│ Täubl, Karel,                ┆ Zlatnictví                      ┆ 199   ┆ 1976 │
│ Slánský, Bohuslav,           ┆ Technika v malířské tvorbě      ┆ 186   ┆ 1976 │
│ Jeřábek, Václav,             ┆ Obnova a údržba malých staveb   ┆ 165   ┆ 1976 │
│ David, Stanislav             ┆ Vlastní výroba bytových doplňk… ┆ 142   ┆ 1976 │
│ Krůta, Václav                ┆ Staviva a výrobky pro svépomoc… ┆ 148   ┆ 1978 │
│ Šrejder, Julij Anatol‘jevič, ┆ Binární relace                  ┆ 320   ┆ 1978 │
│ Tausk, Petr,                 ┆ Materiály pro barevnou fotogra… ┆ 147   ┆ 1979 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 427   ┆ 1979 │
└──────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [168]:
zjisti("Volají neviditelné vlny")

Knížky pro chytré děti

shape: (1, 6)
┌───────────────────┬─────────────────────────┬───────┬──────┬───────┬────────────────────────┐
│ 100_a             ┆ 245_a                   ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                  │
│ ---               ┆ ---                     ┆ ---   ┆ ---  ┆ ---   ┆ ---                    │
│ str               ┆ str                     ┆ str   ┆ i64  ┆ i64   ┆ str                    │
╞═══════════════════╪═════════════════════════╪═══════╪══════╪═══════╪════════════════════════╡
│ Škoda, František, ┆ Volají neviditelné vlny ┆ SNDK  ┆ 1960 ┆ 47    ┆ Knížky pro chytré děti │
└───────────────────┴─────────────────────────┴───────┴──────┴───────┴────────────────────────┘

In [170]:
edice("Knížky pro chytré děti")

shape: (9, 4)
┌────────────────────┬─────────────────────────┬───────┬──────┐
│ 100_a              ┆ 245_a                   ┆ stran ┆ rok  │
│ ---                ┆ ---                     ┆ ---   ┆ ---  │
│ str                ┆ str                     ┆ i64   ┆ i64  │
╞════════════════════╪═════════════════════════╪═══════╪══════╡
│ Čtvrtek, Václav,   ┆ Směr vesmír - start!    ┆ 44    ┆ 1959 │
│ Koval, Václav,     ┆ Svět za sklem           ┆ 47    ┆ 1959 │
│ Růžička, Jiří,     ┆ Nej - nej - nej         ┆ 36    ┆ 1959 │
│ Korejs, Milan,     ┆ Rukulíbám - dobrý den   ┆ 47    ┆ 1959 │
│ Svoboda, Vladimír, ┆ Ať přestane svítit      ┆ 46    ┆ 1960 │
│ Škoda, František,  ┆ Volají neviditelné vlny ┆ 47    ┆ 1960 │
│ Koval, Václav,     ┆ 25 divů v našem domě    ┆ 63    ┆ 1961 │
│ Souček, Ludvík,    ┆ Hrátky kolem křižovatky ┆ 54    ┆ 1962 │
│ Nepil, František,  ┆ Kola, strojky, nápady   ┆ 69    ┆ 1963 │
└────────────────────┴─────────────────────────┴───────┴──────┘

In [174]:
zjisti("Hry s kalkulátory")

Knižnice všeobecného vzdělání mládeže. Maják

shape: (3, 6)
┌──────────────┬───────────────────┬───────┬──────┬───────┬─────────────────────────────────┐
│ 100_a        ┆ 245_a             ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                           │
│ ---          ┆ ---               ┆ ---   ┆ ---  ┆ ---   ┆ ---                             │
│ str          ┆ str               ┆ str   ┆ i64  ┆ i64   ┆ str                             │
╞══════════════╪═══════════════════╪═══════╪══════╪═══════╪═════════════════════════════════╡
│ Mrázek, Jiří ┆ Hry s kalkulátory ┆ SPN   ┆ 1984 ┆ 111   ┆ Knižnice všeobecného vzdělání … │
│ Mrázek, Jiří ┆ Hry s kalkulátory ┆ SPN   ┆ 1986 ┆ 111   ┆ Knižnice všeobecného vzděláván… │
│ Mrázek, Jiří ┆ Hry s kalkulátory ┆ SPN   ┆ 1988 ┆ 111   ┆ Knižnice všeobecného vzdělání … │
└──────────────┴───────────────────┴───────┴──────┴───────┴─────────────────────────────────┘

In [178]:
edice("Knižnice všeobecného vzdělání mládeže")

shape: (33, 4)
┌────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                      ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                        ┆ ---                             ┆ ---   ┆ ---  │
│ str                        ┆ str                             ┆ i64   ┆ i64  │
╞════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Duchoň, František,         ┆ Hydroponie                      ┆ 199   ┆ 1965 │
│ Hejda, Stanislav,          ┆ Správná výživa teoreticky a pr… ┆ 304   ┆ 1968 │
│ Řehák, Bohuslav,           ┆ Vycházky do přírody             ┆ 243   ┆ 1968 │
│ Hejda, Stanislav,          ┆ Správná výživa teoreticky a pr… ┆ 304   ┆ 1969 │
│ Kuba, Adolf,               ┆ Kluci, plný plyn                ┆ 131   ┆ 1969 │
│ Bojev, Sergej Nikolajevič, ┆ Jak savci pečují o svá mláďata  ┆ 61    ┆ 1969 │
│ Šimáček, Radovan,          ┆ Obchodujeme s celým světem      ┆ 264   ┆ 1970 │
│ Augusta, Josef,            ┆ U pravěkých lovců               ┆ 163   ┆ 1971 │
│ Augusta, Josef,            ┆ Z hlubin pravěku                ┆ 141   ┆ 1971 │
│ Augusta, Josef,            ┆ Zavátý život                    ┆ 174   ┆ 1971 │
│ Novoveský, Štefan,         ┆ 777 matematických zábav a her   ┆ 381   ┆ 1971 │
│ Mečíř, Miloslav,           ┆ Péče o malé dítě                ┆ 186   ┆ 1971 │
│ Řehák, Bohuslav,           ┆ Vycházky do přírody             ┆ 243   ┆ 1971 │
│ Augusta, Josef,            ┆ Ztracený svět                   ┆ 170   ┆ 1972 │
│ Dobrowolski, Kazimierz A., ┆ Jak živočichové létají          ┆ 145   ┆ 1972 │
│ Augusta, Josef,            ┆ U pravěkých lovců               ┆ 156   ┆ 1973 │
│ Řehák, Bohuslav,           ┆ Vycházky do přírody             ┆ 243   ┆ 1973 │
│ Chvátal, Václav            ┆ Světová socialistická soustava  ┆ 181   ┆ 1974 │
│ Míka, Alois,               ┆ Stoletý zápas o charakter česk… ┆ 189   ┆ 1974 │
│ Picmaus, Karel,            ┆ Evropská bezpečnost             ┆ 190   ┆ 1974 │
│ Augusta, Josef,            ┆ U pravěkých lovců               ┆ 156   ┆ 1975 │
│ Novoveský, Štefan,         ┆ Zábavná matematika              ┆ 325   ┆ 1975 │
│ Duchoň, František,         ┆ Uživí nás Země?                 ┆ 155   ┆ 1976 │
│ Augusta, Josef,            ┆ Lovci jeskynních medvědů        ┆ 229   ┆ 1976 │
│ Augusta, Josef,            ┆ Zavátý život                    ┆ 176   ┆ 1976 │
│ Houška, Jiří,              ┆ Společnost, stát a jednotlivec  ┆ 195   ┆ 1977 │
│ Grosse, Erich,             ┆ Chemie z vlastních pozorování   ┆ 365   ┆ 1977 │
│ Sedliak, Július            ┆ Polsko v epoše socialismu       ┆ 189   ┆ 1977 │
│ Jelínek, Jaroslav,         ┆ Čtení o českém jazyku           ┆ 301   ┆ 1980 │
│ Jelínek, Jaroslav,         ┆ Čtení o českém jazyku           ┆ 301   ┆ 1982 │
│ Polák, Josef,              ┆ Přehled středoškolské matemati… ┆ 627   ┆ 1983 │
│ Mrázek, Jiří               ┆ Hry s kalkulátory               ┆ 111   ┆ 1984 │
│ Mrázek, Jiří               ┆ Hry s kalkulátory               ┆ 111   ┆ 1988 │
└────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [194]:
df.filter(pl.col("245_a").str.contains("Pájení"))

shape: (10, 64)
┌──────────┬───────────────────┬───────────────┬───────────┬───┬───────────┬───────────┬───────┬──────┐
│ 100_ind1 ┆ 100_a             ┆ 100_7         ┆ 100_4     ┆ … ┆ 490_x     ┆ 490_3     ┆ stran ┆ rok  │
│ ---      ┆ ---               ┆ ---           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---  │
│ str      ┆ str               ┆ str           ┆ list[str] ┆   ┆ list[str] ┆ list[str] ┆ i64   ┆ i64  │
╞══════════╪═══════════════════╪═══════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════╪══════╡
│ 1        ┆ Ruža, Viliam      ┆ jx20051114023 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 452   ┆ 1988 │
│ 1        ┆ Ruža, Viliam      ┆ jx20051114023 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 452   ┆ 1988 │
│ 1        ┆ Martínek, Antonín ┆ null          ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 245   ┆ 1990 │
│ 1        ┆ Ruža, Viliam      ┆ jx20051114023 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 395   ┆ 1978 │
│ 1        ┆ Puchnar, Bedřich  ┆ jx20050531019 ┆ ["edt"]   ┆ … ┆ null      ┆ null      ┆ 89    ┆ 1952 │
│ 1        ┆ Němec, Karel      ┆ jk01083089    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 59    ┆ 1970 │
│ 1        ┆ Karlík, Pavel     ┆ xx0039036     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 147   ┆ 1967 │
│ 1        ┆ Karlík, Pavel     ┆ xx0039036     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 147   ┆ 1967 │
│ 1        ┆ Němec, Karel      ┆ jk01083089    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 50    ┆ 1963 │
│ 1        ┆ Slánský, Antonín  ┆ null          ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 78    ┆ 1947 │
└──────────┴───────────────────┴───────────────┴───────────┴───┴───────────┴───────────┴───────┴──────┘

In [182]:
zjisti("Současný šperk")

Soudobé české umění

shape: (1, 6)
┌─────────────────┬────────────────┬───────┬──────┬───────┬─────────────────────┐
│ 100_a           ┆ 245_a          ┆ 260_b ┆ rok  ┆ stran ┆ 490_a               │
│ ---             ┆ ---            ┆ ---   ┆ ---  ┆ ---   ┆ ---                 │
│ str             ┆ str            ┆ str   ┆ i64  ┆ i64   ┆ str                 │
╞═════════════════╪════════════════╪═══════╪══════╪═══════╪═════════════════════╡
│ Vokáčová, Věra, ┆ Současný šperk ┆ Odeon ┆ 1979 ┆ 71    ┆ Soudobé české umění │
└─────────────────┴────────────────┴───────┴──────┴───────┴─────────────────────┘

In [184]:
edice("Soudobé české umění")

shape: (33, 4)
┌───────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                         ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                           ┆ ---                             ┆ ---   ┆ ---  │
│ str                           ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Hlaváček, Luboš,              ┆ Současná kresba                 ┆ 71    ┆ 1976 │
│ Vlček, Tomáš,                 ┆ Současný plakát                 ┆ 71    ┆ 1976 │
│ Konečný, Dušan,               ┆ Výstavy současného umění        ┆ 71    ┆ 1977 │
│ Mrázová-Schusterová, Marcela, ┆ Současná krajinomalba           ┆ 71    ┆ 1977 │
│ Hlaváček, Luboš,              ┆ Současná grafika                ┆ 72    ┆ 1977 │
│ Dvorská, Pavla                ┆ Současná monumentální tvorba    ┆ 71    ┆ 1978 │
│ Michl, Jan                    ┆ Realizace a projekty v současn… ┆ 71    ┆ 1978 │
│ Konečný, Dušan,               ┆ Mladí čeští malíři              ┆ 71    ┆ 1978 │
│ Nýdl, Miroslav,               ┆ Současná známková tvorba        ┆ 71    ┆ 1978 │
│ Holub, Karel,                 ┆ Mladí čeští sochaři             ┆ 71    ┆ 1978 │
│ Laudová, Věra,                ┆ Obraz města v současném malířs… ┆ 71    ┆ 1978 │
│ Dvořák, František,            ┆ Současné exlibris               ┆ 71    ┆ 1979 │
│ Adlerová, Alena,              ┆ Současné sklo                   ┆ 71    ┆ 1979 │
│ Fixl, Viktor,                 ┆ Současná hračka                 ┆ 71    ┆ 1979 │
│ Růžička, Milouš,              ┆ Současná keramika               ┆ 71    ┆ 1979 │
│ Vokáčová, Věra,               ┆ Současný šperk                  ┆ 71    ┆ 1979 │
│ Vlček, Tomáš,                 ┆ Současný plakát                 ┆ 71    ┆ 1979 │
│ Růžička, Milouš,              ┆ Sovremennaja keramika           ┆ 71    ┆ 1979 │
│ Stehlíková, Blanka,           ┆ Zeitgenössische Illustration v… ┆ 71    ┆ 1979 │
│ Mráz, Bohumír,                ┆ Současná tapisérie              ┆ 71    ┆ 1980 │
│ Petrová, Sylva,               ┆ Mladá grafika                   ┆ 71    ┆ 1980 │
│ Jeřábek, Richard,             ┆ Plastika lidových tvůrců        ┆ 71    ┆ 1981 │
│ Fabel, Karel,                 ┆ Současná typografie             ┆ 71    ┆ 1981 │
│ Halířová, Marie               ┆ Portrétní tvorba                ┆ 71    ┆ 1981 │
│ Šimoníková, Jaromíra,         ┆ Interiérová tvorba              ┆ 71    ┆ 1982 │
│ Laudová, Věra,                ┆ Zátiší                          ┆ 71    ┆ 1983 │
│ Stehlíková, Blanka,           ┆ Ilustrace                       ┆ 71    ┆ 1984 │
│ Hošková, Simeona,             ┆ Mladá kresba                    ┆ 71    ┆ 1984 │
│ Procházka, Václav,            ┆ Medaile a plaketa               ┆ 71    ┆ 1984 │
│ Lamarová, Milena,             ┆ Průmyslový design               ┆ 71    ┆ 1985 │
│ Štochlová, Helena             ┆ Animovaný film                  ┆ 71    ┆ 1985 │
│ Matyášová, Eva                ┆ Naivní malířství                ┆ 71    ┆ 1986 │
│ Kybalová, Ludmila,            ┆ Oděvní tvorba                   ┆ 71    ┆ 1986 │
└───────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [198]:
zjisti("Můžu ochutnat")

None

shape: (1, 6)
┌──────────────────────────┬────────────────┬───────┬──────┬───────┬───────┐
│ 100_a                    ┆ 245_a          ┆ 260_b ┆ rok  ┆ stran ┆ 490_a │
│ ---                      ┆ ---            ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str                      ┆ str            ┆ str   ┆ i64  ┆ i64   ┆ str   │
╞══════════════════════════╪════════════════╪═══════╪══════╪═══════╪═══════╡
│ Mizielińska, Aleksandra, ┆ Můžu ochutnat? ┆ null  ┆ 2021 ┆ 112   ┆ null  │
└──────────────────────────┴────────────────┴───────┴──────┴───────┴───────┘

In [204]:
zjisti(", která se nesmála")

None

shape: (1, 6)
┌─────────────────┬──────────────────────────┬────────┬──────┬───────┬───────┐
│ 100_a           ┆ 245_a                    ┆ 260_b  ┆ rok  ┆ stran ┆ 490_a │
│ ---             ┆ ---                      ┆ ---    ┆ ---  ┆ ---   ┆ ---   │
│ str             ┆ str                      ┆ str    ┆ i64  ┆ i64   ┆ str   │
╞═════════════════╪══════════════════════════╪════════╪══════╪═══════╪═══════╡
│ Tashlin, Frank, ┆ Vačice, která se nesmála ┆ Baobab ┆ 2013 ┆ 55    ┆ null  │
└─────────────────┴──────────────────────────┴────────┴──────┴───────┴───────┘

In [206]:
zjisti("Nad propastí")

Spisů pro mládež č. 27

shape: (33, 6)
┌─────────────────────────────┬───────────────────────┬─────────────────────────────────┬──────┬───────┬─────────────────────────────────┐
│ 100_a                       ┆ 245_a                 ┆ 260_b                           ┆ rok  ┆ stran ┆ 490_a                           │
│ ---                         ┆ ---                   ┆ ---                             ┆ ---  ┆ ---   ┆ ---                             │
│ str                         ┆ str                   ┆ str                             ┆ i64  ┆ i64   ┆ str                             │
╞═════════════════════════════╪═══════════════════════╪═════════════════════════════════╪══════╪═══════╪═════════════════════════════════╡
│ Vlasák, Josef Věnceslav,    ┆ Nad propastí          ┆ Nákladem knihkupectví B. Stýbl… ┆ 1882 ┆ 94    ┆ Spisů pro mládež č. 27          │
│ Michajlov, A.,              ┆ Nad propastí          ┆ A. Hynek                        ┆ 1883 ┆ 70    ┆ Česká bibliotéka rodinná        │
│ Michajlov, A.,              ┆ Nad propastí          ┆ Nákladem Al. Hynka, knihkupce   ┆ 1884 ┆ 254   ┆ Česká bibliotéka rodinná        │
│ Michajlov, A.,              ┆ Nad propastí          ┆ Nákladem Al. Hynka, knihkupce   ┆ 1884 ┆ 238   ┆ Česká bibliotéka rodinná        │
│ Vrchlický, Jaroslav,        ┆ Nad propastí          ┆ null                            ┆ 1887 ┆ 46    ┆ Dramatická díla Jaroslava Vrch… │
│ Zahradník-Brodský, Bohumil, ┆ Nad propastí          ┆ E. Šolc                         ┆ 1901 ┆ 371   ┆ null                            │
│ Skarlandt, Julius,          ┆ Nad propastí          ┆ Edvard Jan Baštýř a spol.       ┆ 1908 ┆ 210   ┆ Romány Praž. Illustr. kurýra    │
│ Kraszewski, Józef Ignacy,   ┆ Nad propastí          ┆ Jos. R. Vilímek                 ┆ 1913 ┆ 382   ┆ Vilímkovy illustrované romány   │
│ Vrchlický, Jaroslav,        ┆ Nad propastí          ┆ Nákladem F. Šimáčka             ┆ 1913 ┆ 47    ┆ Dramatická díla Jaroslava Vrch… │
│ Zahradník-Brodský, Bohumil, ┆ Nad propastí          ┆ Alois Wiesner                   ┆ 1913 ┆ 291   ┆ Sebr. spisy                     │
│ Novák, Robert Lev,          ┆ Nad propastí          ┆ nákl.vl.                        ┆ 1916 ┆ 55    ┆ null                            │
│ Novák, Robert Lev,          ┆ Nad propastí          ┆ Přerod                          ┆ 1917 ┆ 59    ┆ Přerod                          │
│ Pasovský, Jaroslav,         ┆ Nad propastí          ┆ B. Kočí                         ┆ 1919 ┆ 16    ┆ Umělecké snahy                  │
│ Dědina, František,          ┆ Nad propastí          ┆ null                            ┆ 1919 ┆ 26    ┆ null                            │
│ Hearts, James               ┆ Nad propastí          ┆ Reiter                          ┆ 1920 ┆ 32    ┆ Povídky z biografu              │
│ Dědina, František,          ┆ Nad propastí          ┆ nákl. vl.                       ┆ 1920 ┆ 32    ┆ null                            │
│ Dědina, František,          ┆ Nad propastí          ┆ Obch. družstvo čes. knihk. dis… ┆ 1920 ┆ 32    ┆ null                            │
│ Zahradník-Brodský, Bohumil, ┆ Nad propastí          ┆ A. Neubert                      ┆ 1922 ┆ 291   ┆ Sebr. spisy                     │
│ Zahradník-Brodský, Bohumil, ┆ Nad propastí          ┆ V. Kotrba                       ┆ 1922 ┆ 291   ┆ Sebrané spisy                   │
│ Šupka, František,           ┆ Nad propastí          ┆ Fr. Šupka                       ┆ 1925 ┆ 220   ┆ Lidové povídky                  │
│ Madeus, Š. A.               ┆ Nad propastí hanby    ┆ Svět                            ┆ 1932 ┆ 243   ┆ Romány Svět                     │
│ Malzahn, Erik               ┆ Nad propastí          ┆ Novela, Karel Ninger            ┆ 1932 ┆ 64    ┆ Knihovna moderní ženy           │
│ Vrba, Rudolf,               ┆ Nad propastí          ┆ null                            ┆ 1932 ┆ 116   ┆ null                            │
│ Vrchlický, Jaroslav,        ┆ Nad propastí          ┆ Rodina                          ┆ 1933 ┆ 84    ┆ Vrchlický, Jaroslav: Dramatick… │
│ Slavík, Jindřich Maria,     ┆ Nad propastí          ┆ C. Beran                        ┆ 1937 ┆ 30    ┆ null                            │
│ Kurka, Bernard,             ┆ Nad propastí          ┆ null                            ┆ 1942 ┆ 33    ┆ Moderní romány                  │
│ Davis, Gill                 ┆ Nad propastí          ┆ Návrat                          ┆ 1996 ┆ 40    ┆ Little & big western            │
│ Kellerman, Jonathan,        ┆ Nad propastí          ┆ Domino                          ┆ 2001 ┆ 389   ┆ null                            │
│ Smith, Wilbur A.,           ┆ Nad propastí          ┆ null                            ┆ 2018 ┆ 480   ┆ Klokan                          │
│ Auður Ava Ólafsdóttir,      ┆ Nad propastí byla tma ┆ null                            ┆ 2018 ┆ 209   ┆ null                            │
│ Havranová, Mária            ┆ Nad propastí          ┆ null                            ┆ 2020 ┆ 234   ┆ null                            │
│ Ord, Toby,                  ┆ Nad propastí          ┆ null                            ┆ 2022 ┆ 480   ┆ Crossover                       │
│ Štefková, Eliška,           ┆ Nad propastí          ┆ null                            ┆ 2024 ┆ 219   ┆ Bookla                          │
└─────────────────────────────┴───────────────────────┴─────────────────────────────────┴──────┴───────┴─────────────────────────────────┘

In [208]:
edice("Crossover")

shape: (16, 4)
┌─────────────────────┬────────────────────────────────┬───────┬──────┐
│ 100_a               ┆ 245_a                          ┆ stran ┆ rok  │
│ ---                 ┆ ---                            ┆ ---   ┆ ---  │
│ str                 ┆ str                            ┆ i64   ┆ i64  │
╞═════════════════════╪════════════════════════════════╪═══════╪══════╡
│ Klein, Naomi,       ┆ Ne nestačí                     ┆ 294   ┆ 2019 │
│ Luce, Edward,       ┆ Soumrak západního liberalismu  ┆ 191   ┆ 2019 │
│ Keen, Andrew        ┆ Jak opravit budoucnost         ┆ 278   ┆ 2019 │
│ Ross, Alec,         ┆ Obory budoucnosti              ┆ 330   ┆ 2019 │
│ Lee, Kai-fu,        ┆ Supervelmoci umělé inteligence ┆ 291   ┆ 2019 │
│ Lowrey, Annie,      ┆ Dejte lidem peníze             ┆ 251   ┆ 2020 │
│ Scheidel, Walter,   ┆ Velký nivelizátor              ┆ 589   ┆ 2020 │
│ Collier, Paul,      ┆ Budoucnost kapitalismu         ┆ 299   ┆ 2020 │
│ Brown, Archie,      ┆ Mýtus silného vůdce            ┆ 503   ┆ 2021 │
│ MacAskill, William, ┆ Dobré úmysly nestačí           ┆ 262   ┆ 2021 │
│ Bregman, Rutger,    ┆ Lidstvo                        ┆ 425   ┆ 2022 │
│ Ord, Toby,          ┆ Nad propastí                   ┆ 480   ┆ 2022 │
│ Milanović, Branko,  ┆ Nic než kapitalismus           ┆ 309   ┆ 2022 │
│ Zuboff, Shoshana,   ┆ Věk kapitalismu dohledu        ┆ 725   ┆ 2022 │
│ Kolbert, Elizabeth, ┆ Pod bílou oblohou              ┆ 214   ┆ 2023 │
│ Turchin, Peter,     ┆ Poslední dny                   ┆ 299   ┆ 2024 │
└─────────────────────┴────────────────────────────────┴───────┴──────┘

In [210]:
zjisti("Neobyvatelná")

Klimax

shape: (1, 6)
┌──────────────────────┬───────────────────┬───────┬──────┬───────┬────────┐
│ 100_a                ┆ 245_a             ┆ 260_b ┆ rok  ┆ stran ┆ 490_a  │
│ ---                  ┆ ---               ┆ ---   ┆ ---  ┆ ---   ┆ ---    │
│ str                  ┆ str               ┆ str   ┆ i64  ┆ i64   ┆ str    │
╞══════════════════════╪═══════════════════╪═══════╪══════╪═══════╪════════╡
│ Wallace-Wells, David ┆ Neobyvatelná Země ┆ null  ┆ 2020 ┆ 390   ┆ Klimax │
└──────────────────────┴───────────────────┴───────┴──────┴───────┴────────┘

In [212]:
edice("Klimax")

shape: (11, 4)
┌──────────────────────┬───────────────────────┬───────┬──────┐
│ 100_a                ┆ 245_a                 ┆ stran ┆ rok  │
│ ---                  ┆ ---                   ┆ ---   ┆ ---  │
│ str                  ┆ str                   ┆ i64   ┆ i64  │
╞══════════════════════╪═══════════════════════╪═══════╪══════╡
│ Wallace-Wells, David ┆ Neobyvatelná Země     ┆ 390   ┆ 2020 │
│ Rich, Nathaniel,     ┆ Jak ztratit Zemi      ┆ 199   ┆ 2020 │
│ Hanišová, Viktorie,  ┆ Beton a hlína         ┆ 258   ┆ 2021 │
│ Carson, Rachel,      ┆ Tiché jaro            ┆ 374   ┆ 2021 │
│ Marshall, George,    ┆ Ani na to nemyslete   ┆ 348   ┆ 2022 │
│ Lovelock, James,     ┆ Novacén               ┆ 148   ┆ 2022 │
│ Mann, Michael E.,    ┆ Nová klimatická válka ┆ 444   ┆ 2022 │
│ Klein, Naomi,        ┆ Tím se všechno mění   ┆ 702   ┆ 2023 │
│ Abram, David,        ┆ Stávat se zvířetem    ┆ 371   ┆ 2024 │
│ Sanderson, Henry     ┆ Zelená horečka        ┆ 316   ┆ 2024 │
│ Goodell, Jeff,       ┆ Vedro                 ┆ 419   ┆ 2024 │
└──────────────────────┴───────────────────────┴───────┴──────┘

In [224]:
zjisti("Každému chléb")

Dobrý vítr

shape: (1, 6)
┌────────────────────┬─────────────────────────────┬──────────────┬──────┬───────┬────────────┐
│ 100_a              ┆ 245_a                       ┆ 260_b        ┆ rok  ┆ stran ┆ 490_a      │
│ ---                ┆ ---                         ┆ ---          ┆ ---  ┆ ---   ┆ ---        │
│ str                ┆ str                         ┆ str          ┆ i64  ┆ i64   ┆ str        │
╞════════════════════╪═════════════════════════════╪══════════════╪══════╪═══════╪════════════╡
│ Selucký, Radoslav, ┆ Každému chléb, každému růže ┆ Mladá fronta ┆ 1962 ┆ 208   ┆ Dobrý vítr │
└────────────────────┴─────────────────────────────┴──────────────┴──────┴───────┴────────────┘

In [226]:
edice("Dobrý vítr")

shape: (46, 4)
┌───────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                         ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                           ┆ ---                             ┆ ---   ┆ ---  │
│ str                           ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Chrastil, Josef,              ┆ Smím prosit?                    ┆ 126   ┆ 1958 │
│ Chrastil, Josef,              ┆ Smím prosit?                    ┆ 126   ┆ 1958 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 123   ┆ 1958 │
│ Faukner, Rudolf,              ┆ Kdyby přišli Marťané, aneb, Pr… ┆ 120   ┆ 1958 │
│ Dvořák, František             ┆ Zařizujete si byt?              ┆ 83    ┆ 1958 │
│ Kusák, Alexej,                ┆ Knížka o vkusu                  ┆ 167   ┆ 1959 │
│ Boček, Jaroslav,              ┆ Znáte je z plátna               ┆ 183   ┆ 1959 │
│ Klímová-Fügnerová, Miroslava, ┆ Na prahu života                 ┆ 91    ┆ 1959 │
│ Zahradník, Miroslav,          ┆ Chcete se líbit?                ┆ 96    ┆ 1959 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 124   ┆ 1960 │
│ Hoffmann, Hans-Joachim,       ┆ Upřímné slovo                   ┆ 137   ┆ 1960 │
│ Jandera, Alexander,           ┆ Medicína do kapsy               ┆ 120   ┆ 1960 │
│ Dvořák, Vladimír,             ┆ Začínáme od Adama               ┆ 133   ┆ 1960 │
│ Kusák, Alexej,                ┆ Země kolem nás                  ┆ 98    ┆ 1961 │
│ Vávra, Ivan                   ┆ Malá abeceda na témata z mezin… ┆ 141   ┆ 1961 │
│ Urbanec, Jindřich             ┆ Lidé kolem stolu                ┆ 118   ┆ 1961 │
│ Hayn, H. G.                   ┆ Adam, Eva a teologové           ┆ 85    ┆ 1961 │
│ Selucký, Radoslav,            ┆ Každému chléb, každému růže     ┆ 208   ┆ 1962 │
│ Příbramská, Markéta           ┆ Móda od A do Z                  ┆ 131   ┆ 1962 │
│ Pavlík, Jan,                  ┆ Taneční do kapsy                ┆ 180   ┆ 1962 │
│ Barták, Vladimír,             ┆ Čtení před manželstvím          ┆ 186   ┆ 1963 │
│ Štěpnička, Jiří,              ┆ Cvičte s námi každý den         ┆ 117   ┆ 1963 │
│ Hartl, Břetislav,             ┆ Fotografie pro Aristotela       ┆ 279   ┆ 1964 │
│ Pondělíček, Ivo,              ┆ Rozumíte sami sobě?             ┆ 188   ┆ 1964 │
│ Tomášková, Jana,              ┆ Breviář půvabu                  ┆ 155   ┆ 1964 │
│ Stoklasa, Jaroslav,           ┆ Byt či nebyt                    ┆ 237   ┆ 1965 │
│ Břízová, Joza,                ┆ A přidáme něco fantazie         ┆ 169   ┆ 1965 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 146   ┆ 1966 │
│ Sís, Vladimír,                ┆ Počítání nudliček v jarní polé… ┆ 116   ┆ 1966 │
│ Plzák, Miroslav,              ┆ První pomoc při nehodách manže… ┆ 131   ┆ 1967 │
│ Sís, Vladimír,                ┆ Počítání nudliček v jarní polé… ┆ 116   ┆ 1967 │
│ Rakušan, Zdenko               ┆ Byt či nebyt                    ┆ 235   ┆ 1967 │
│ Tomášková, Jana,              ┆ Breviář půvabu                  ┆ 160   ┆ 1968 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 146   ┆ 1969 │
│ Plzák, Miroslav,              ┆ První pomoc při nehodách manže… ┆ 130   ┆ 1969 │
│ Stoklasa, Jaroslav,           ┆ Ideální manžel, aneb, Co má vě… ┆ 274   ┆ 1969 │
│ Kozakiewicz, Mikołaj,         ┆ Důvěrnosti                      ┆ 189   ┆ 1970 │
│ Ravik, Slavomír,              ┆ Svět starožitností              ┆ 221   ┆ 1972 │
│ Nyklová, Milena,              ┆ Sbohem dětství                  ┆ 180   ┆ 1972 │
│ Nyklová, Milena,              ┆ O štěstí trochu jinak           ┆ 187   ┆ 1975 │
│ Matulová, Nina                ┆ Žena v dnešní rodině            ┆ 250   ┆ 1976 │
│ Garczyński, Stefan,           ┆ Soužití snadné a složité        ┆ 207   ┆ 1977 │
│ Staněk, Josef                 ┆ Zn. "Jen upřímně a vážně"       ┆ 217   ┆ 1977 │
│ Ravik, Slavomír,              ┆ Svět starožitností              ┆ 377   ┆ 1977 │
│ Kozakiewicz, Mikołaj,         ┆ Každý volí sebe                 ┆ 344   ┆ 1978 │
│ Pávek, František,             ┆ Manželská čítanka               ┆ 282   ┆ 1979 │
└───────────────────────────────┴─────────────────────────────────┴───────┴──────┘