In [3]:
import os
import polars as pl
from src.bez_bordelu import bez_bordelu
from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
pl.Config(tbl_rows=500)

In [4]:
df = pl.read_parquet(
    os.path.join("data/cnb_sloupce","100.parquet")
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","020.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","022.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","041.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","260.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","300.parquet")), left_on="001", right_on="001", how="left"
).join(
    pl.read_parquet(os.path.join("data/cnb_sloupce","490.parquet")), left_on="001", right_on="001", how="left"
).explode(
    "300_a"
).with_columns(
    pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran')
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
).explode(
    "260_b"
).with_columns(
    pl.col(("260_b")).map_elements(bez_bordelu, return_dtype=str)
).explode(
    "490_a"
).with_columns(
    pl.col(("490_a")).map_elements(bez_bordelu, return_dtype=str)
)

In [5]:
def zjisti(nazev):
    frejm = df.filter(pl.col("245_a").str.contains(nazev)).select(pl.col(["100_a","245_a","260_b","rok","stran","490_a"])).sort(by="rok")
    print(frejm.select(pl.col("490_a")).to_series().to_list()[0])
    return frejm

In [6]:
zjisti("Jak s tím pohnu")

Krystal

shape: (1, 6)
┌────────────────────┬─────────────────┬───────┬──────┬───────┬─────────┐
│ 100_a              ┆ 245_a           ┆ 260_b ┆ rok  ┆ stran ┆ 490_a   │
│ ---                ┆ ---             ┆ ---   ┆ ---  ┆ ---   ┆ ---     │
│ str                ┆ str             ┆ str   ┆ i64  ┆ i64   ┆ str     │
╞════════════════════╪═════════════════╪═══════╪══════╪═══════╪═════════╡
│ Houška, Vítězslav, ┆ Jak s tím pohnu ┆ SNDK  ┆ 1965 ┆ 188   ┆ Krystal │
└────────────────────┴─────────────────┴───────┴──────┴───────┴─────────┘

In [7]:
zjisti("Nejkrásnější bývá šílená")

Květy poezie

shape: (3, 6)
┌────────────────────┬──────────────────────────┬──────────────┬──────┬───────┬──────────────┐
│ 100_a              ┆ 245_a                    ┆ 260_b        ┆ rok  ┆ stran ┆ 490_a        │
│ ---                ┆ ---                      ┆ ---          ┆ ---  ┆ ---   ┆ ---          │
│ str                ┆ str                      ┆ str          ┆ i64  ┆ i64   ┆ str          │
╞════════════════════╪══════════════════════════╪══════════════╪══════╪═══════╪══════════════╡
│ Seifert, Jaroslav, ┆ Nejkrásnější bývá šílená ┆ Mladá fronta ┆ 1968 ┆ 124   ┆ Květy poezie │
│ Cincibuch, Petr,   ┆ Nejkrásnější bývá šílená ┆ Melantrich   ┆ 1983 ┆ 74    ┆ Poesie       │
│ Seifert, Jaroslav, ┆ Nejkrásnější bývá šílená ┆ Mladá fronta ┆ 1996 ┆ 136   ┆ Květy poezie │
└────────────────────┴──────────────────────────┴──────────────┴──────┴───────┴──────────────┘

In [8]:
zjisti("Pět olympijských")

None

shape: (1, 6)
┌──────────────────┬────────────────────────┬───────┬──────┬───────┬───────┐
│ 100_a            ┆ 245_a                  ┆ 260_b ┆ rok  ┆ stran ┆ 490_a │
│ ---              ┆ ---                    ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str              ┆ str                    ┆ str   ┆ i64  ┆ i64   ┆ str   │
╞══════════════════╪════════════════════════╪═══════╪══════╪═══════╪═══════╡
│ Zapletal, Miloš, ┆ Pět olympijských kruhů ┆ STN   ┆ 1964 ┆ 426   ┆ null  │
└──────────────────┴────────────────────────┴───────┴──────┴───────┴───────┘

In [9]:
def edice(retezec, nakladatelstvi=None):
    if nakladatelstvi == None:
        return df.filter(pl.col("490_a").str.contains(retezec)).select(pl.col(["100_a","245_a","stran","rok"])).sort(by='rok')
    else:
        return df.filter(pl.col("490_a").str.contains(retezec)).filter(pl.col("260_b") == nakladatelstvi).select(pl.col(["100_a","245_a","300_a","rok","stran"])).sort(by='rok')

In [10]:
edice("Škola mladých matematiků")

shape: (70, 4)
┌─────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                       ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                         ┆ ---                             ┆ ---   ┆ ---  │
│ str                         ┆ str                             ┆ i64   ┆ i64  │
╞═════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Hradecký, František,        ┆ Několik úloh z geometrie jedno… ┆ 89    ┆ 1961 │
│ Sedláček, Jiří,             ┆ Co víme o přirozených číslech   ┆ 42    ┆ 1961 │
│ Šisler, Miroslav            ┆ O funkcích                      ┆ 56    ┆ 1962 │
│ Šedivý, Jaroslav,           ┆ Shodná zobrazení v konstruktiv… ┆ 74    ┆ 1962 │
│ Šisler, Miroslav            ┆ O funkcích                      ┆ 55    ┆ 1963 │
│ Hradecký, František,        ┆ Několik úloh z geometrie jedno… ┆ 92    ┆ 1963 │
│ Veselý, František,          ┆ O nerovnostech                  ┆ 67    ┆ 1963 │
│ Výborný, Rudolf,            ┆ Matematická indukce             ┆ 61    ┆ 1963 │
│ Šedivý, Jaroslav,           ┆ O podobnosti v geometrii        ┆ 77    ┆ 1963 │
│ Vyšín, Jan,                 ┆ Konvexní útvary                 ┆ 93    ┆ 1964 │
│ Sedláček, Jiří,             ┆ Faktoriály a kombinační čísla   ┆ 85    ┆ 1964 │
│ Sedláček, Jiří,             ┆ Co víme o přirozených číslech   ┆ 53    ┆ 1965 │
│ Holubář, Josef,             ┆ Geometrická místa bodů v prost… ┆ 55    ┆ 1965 │
│ Havlíček, Karel,            ┆ Prostory o čtyřech a více rozm… ┆ 84    ┆ 1965 │
│ Horák, Stanislav,           ┆ Kružnice                        ┆ 123   ┆ 1966 │
│ Koman, Milan,               ┆ Jak vyšetřujeme geometrická mí… ┆ 97    ┆ 1966 │
│ Šisler, Miroslav            ┆ O řešení algebraických rovnic   ┆ 126   ┆ 1966 │
│ Výborný, Rudolf,            ┆ Matematická indukce             ┆ 61    ┆ 1966 │
│ Veselý, František,          ┆ O dělitelnosti čísel celých     ┆ 118   ┆ 1966 │
│ Havlíček, Karel,            ┆ Analytická geometrie a nerovno… ┆ 86    ┆ 1967 │
│ Hroník, Jaromír             ┆ Úlohy o maximech a minimech fu… ┆ 100   ┆ 1967 │
│ Šedivý, Jaroslav,           ┆ O podobnosti v geometrii        ┆ 81    ┆ 1967 │
│ Jarník, Jiří,               ┆ Komplexní čísla a funkce        ┆ 75    ┆ 1967 │
│ Apfelbeck, Alois,           ┆ Kongruence                      ┆ 133   ┆ 1968 │
│ Šmakal, Stanislav,          ┆ Goniometrické funkce            ┆ 144   ┆ 1968 │
│ Morávek, Jaroslav,          ┆ Oddělitelnost množin            ┆ 69    ┆ 1969 │
│ Šalát, Tibor,               ┆ Dokonalé a spriatelené čísla    ┆ 49    ┆ 1969 │
│ Gatial, Ján,                ┆ Stavba Lobačevského planimetri… ┆ 115   ┆ 1969 │
│ Hruša, Karel,               ┆ Polynomy v moderní algebře      ┆ 100   ┆ 1970 │
│ Bukovský, Lev,              ┆ Dirichletov princíp             ┆ 58    ┆ 1970 │
│ Váňa, Jiří,                 ┆ O rovnicích s parametry         ┆ 61    ┆ 1970 │
│ Horák, Stanislav,           ┆ Mnohostěny                      ┆ 83    ┆ 1970 │
│ Budinský, Bruno,            ┆ Vektory v geometrii             ┆ 155   ┆ 1971 │
│ Koman, Milan,               ┆ Malý výlet do moderní matemati… ┆ 187   ┆ 1972 │
│ Zítek, František,           ┆ Vytvořující funkce              ┆ 145   ┆ 1972 │
│ Odvárko, Oldřich,           ┆ Booleova algebra                ┆ 115   ┆ 1973 │
│ Morávek, Jaroslav,          ┆ O dynamickém programování       ┆ 77    ┆ 1973 │
│ Vyšín, Jan,                 ┆ Druhý výlet do moderní matemat… ┆ 95    ┆ 1973 │
│ Kufner, Alois,              ┆ Co asi nevíte o vzdálenosti     ┆ 116   ┆ 1974 │
│ Rieger, Ladislav,           ┆ O grupách                       ┆ 139   ┆ 1974 │
│ Koman, Milan,               ┆ Malý výlet do moderní matemati… ┆ 187   ┆ 1974 │
│ Kufner, Alois,              ┆ Nerovnosti a odhady             ┆ 117   ┆ 1975 │
│ Riečan, Beloslav,           ┆ O pravdepodobnosti              ┆ 101   ┆ 1976 │
│ Bosák, Juraj,               ┆ Latinské štvorce                ┆ 82    ┆ 1976 │
│ Černý, Ján                  ┆ O aplikáciach matematiky        ┆ 115   ┆ 1976 │
│ Hradecký, František,        ┆ Několik úloh z geometrie jedno… ┆ 116   ┆ 1977 │
│ Sedláček, Jiří,             ┆ Co víme o přirozených číslech   ┆ 62    ┆ 1977 │
│ Vrba, Antonín               ┆ Princip matematické indukce     ┆ 138   ┆ 1977 │
│ Zelinka, Bohdan,            ┆ Rovinné grafy                   ┆ 131   ┆ 1977 │
│ Beran, Ladislav,            ┆ Uspořádané množiny              ┆ 73    ┆ 1978 │
│ Jarník, Jiří,               ┆ Posloupnosti a řady             ┆ 138   ┆ 1979 │
│ Zelinka, Bohdan,            ┆ Matematika hrou i vážně         ┆ 188   ┆ 1979 │
│ Šedivý, Jaroslav,           ┆ Shodnost a podobnost v konstru… ┆ 157   ┆ 1980 │
│ Vrba, Antonín               ┆ Kombinatorika                   ┆ 130   ┆ 1980 │
│ Niederle, Arnošt            ┆ Zajímavé dvojice trojúhelníků   ┆ 268   ┆ 1980 │
│ Vít, Pavel,                 ┆ Řetězové zlomky                 ┆ 158   ┆ 1982 │
│ Gatial, Ján,                ┆ Hry takmer matematické          ┆ 140   ┆ 1982 │
│ Kufner, Alois,              ┆ Symetrické funkce               ┆ 116   ┆ 1982 │
│ Gutenmacher, Viktor L'vovič ┆ Přímky a křivky                 ┆ 154   ┆ 1982 │
│ Płocki, Adam,               ┆ O náhodě a pravděpodobnosti     ┆ 172   ┆ 1982 │
│ Veselý, František,          ┆ O nerovnostech a nerovnicích    ┆ 86    ┆ 1982 │
│ Holubář, Josef,             ┆ Množiny bodů v prostoru         ┆ 55    ┆ 1983 │
│ Davidov, Ljubomir,          ┆ Funkcionální rovnice            ┆ 92    ┆ 1984 │
│ Sedláček, Jiří,             ┆ Faktoriály a kombinační čísla   ┆ 125   ┆ 1985 │
│ Horák, Stanislav,           ┆ Nerovnosti v trojúhelníku       ┆ 125   ┆ 1986 │
│ Kästner, Herbert            ┆ Algebra                         ┆ 172   ┆ 1986 │
│ Morávek, Jaroslav,          ┆ Oddělitelnost množin            ┆ 83    ┆ 1987 │
│ Korec, Ivan,                ┆ Úlohy o veľkých číslach         ┆ 134   ┆ 1988 │
│ Tůma, Jiří,                 ┆ Matematické halvolamy a základ… ┆ 246   ┆ 1988 │
│ Kufner, Alois,              ┆ Nerovnosti a odhady             ┆ 117   ┆ 1989 │
└─────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [11]:
edice("Super lekce")

shape: (2, 4)
┌───────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                 ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                   ┆ ---                             ┆ ---   ┆ ---  │
│ str                   ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ McManus, Sean,        ┆ Jak se naučit programovat v 10… ┆ 64    ┆ 2017 │
│ Bishop-Stephens, Will ┆ Jak se naučit animovat v 10 sn… ┆ 64    ┆ 2017 │
└───────────────────────┴─────────────────────────────────┴───────┴──────┘

In [12]:
edice("AAA : edice anglo-amerických autorů")

shape: (136, 4)
┌────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                  ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                    ┆ ---                             ┆ ---   ┆ ---  │
│ str                    ┆ str                             ┆ i64   ┆ i64  │
╞════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Erdrich, Louise,       ┆ Čarování s láskou               ┆ 241   ┆ 1994 │
│ Erdrich, Louise,       ┆ Čarování s láskou               ┆ 241   ┆ 1994 │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 283   ┆ 1994 │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 283   ┆ 1994 │
│ Toole, John Kennedy,   ┆ Neónová bible                   ┆ 120   ┆ 1994 │
│ Kosiński, Jerzy N.,    ┆ Byl jsem při tom                ┆ 81    ┆ 1995 │
│ Toole, John Kennedy,   ┆ Spolčení hlupců                 ┆ 359   ┆ 1995 │
│ Brautigan, Richard,    ┆ Willard a jeho kuželkářské tro… ┆ 149   ┆ 1995 │
│ Kosiński, Jerzy N.,    ┆ Nabarvené ptáče                 ┆ 215   ┆ 1995 │
│ Cave, Nick,            ┆ A uzřela oslice anděla          ┆ 297   ┆ 1995 │
│ McCarthy, Cormac,      ┆ Všichni krásní koně             ┆ 251   ┆ 1995 │
│ Allen, Woody,          ┆ Bez peří                        ┆ 95    ┆ 1995 │
│ Carver, Raymond,       ┆ Buď, prosím tě, zticha          ┆ 233   ┆ 1996 │
│ Robbins, Tom,          ┆ Parfém bláznivého tance         ┆ 379   ┆ 1996 │
│ Plath, Sylvia,         ┆ Pod skleněným zvonem            ┆ 209   ┆ 1996 │
│ Kosiński, Jerzy N.,    ┆ Kroky                           ┆ 103   ┆ 1996 │
│ Potok, Chaim,          ┆ Jmenuji se Ašer Lev             ┆ 287   ┆ 1996 │
│ Cohen, Leonard,        ┆ Nádherní poražení               ┆ 222   ┆ 1997 │
│ Ondaatje, Michael,     ┆ Anglický pacient                ┆ 263   ┆ 1997 │
│ Allen, Woody,          ┆ Vyřídit si účty                 ┆ 92    ┆ 1997 │
│ Robbins, Tom,          ┆ Další dálniční atrakce          ┆ 353   ┆ 1997 │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 286   ┆ 1997 │
│ Pynchon, Thomas,       ┆ Městečko Vineland               ┆ 374   ┆ 1997 │
│ Carter, Angela,        ┆ Krvavá komnata                  ┆ 143   ┆ 1997 │
│ McCarthy, Cormac,      ┆ Hranice                         ┆ 353   ┆ 1997 │
│ McInerney, Jay,        ┆ To už je život                  ┆ 141   ┆ 1998 │
│ Atwood, Margaret,      ┆ Z hlubin                        ┆ 189   ┆ 1998 │
│ Vonnegut, Kurt,        ┆ Časotřesení                     ┆ 184   ┆ 1998 │
│ Saroyan, William,      ┆ Kluci a holky, když jsou spolu  ┆ 131   ┆ 1998 │
│ Cohen, Leonard,        ┆ Oblíbená hra                    ┆ 203   ┆ 1998 │
│ Winterson, Jeanette,   ┆ Na světě nejsou jen pomeranče   ┆ 184   ┆ 1998 │
│ Robbins, Tom,          ┆ Hubené nohy a všechno ostatní   ┆ 454   ┆ 1998 │
│ Ondaatje, Michael,     ┆ Máme to v rodině                ┆ 160   ┆ 1998 │
│ Irving, John,          ┆ Modlitba za Owena Meanyho       ┆ 615   ┆ 1999 │
│ Mills, Magnus,         ┆ Ohrady pro zvířata              ┆ 172   ┆ 1999 │
│ Kesey, Ken,            ┆ Tak mě někdy napadá             ┆ 655   ┆ 1999 │
│ Potok, Chaim,          ┆ Dar Ašera Leva                  ┆ 360   ┆ 1999 │
│ Vonnegut, Mark,        ┆ Expres do ráje                  ┆ 250   ┆ 1999 │
│ Gray, Alasdair,        ┆ Něco z kůže                     ┆ 233   ┆ 1999 │
│ Doctorow, E. L.,       ┆ Světová výstava                 ┆ 256   ┆ 1999 │
│ Barthelme, Donald,     ┆ Padesát povídek                 ┆ 303   ┆ 1999 │
│ Ishiguro, Kazuo,       ┆ Malíř pomíjivého světa          ┆ 166   ┆ 1999 │
│ Robbins, Tom,          ┆ Zátiší s Datlem                 ┆ 232   ┆ 2000 │
│ Wharton, William,      ┆ Birdy                           ┆ 269   ┆ 2000 │
│ Winterson, Jeanette,   ┆ Vášeň                           ┆ 148   ┆ 2000 │
│ Jackson, Mick,         ┆ Muž z podzemí                   ┆ 211   ┆ 2001 │
│ Walker, Alice,         ┆ Barva nachu                     ┆ 252   ┆ 2001 │
│ Vonnegut, Kurt,        ┆ Tabatěrka z Bagomba             ┆ 285   ┆ 2001 │
│ Woronov, Mary          ┆ V podzemních vodách             ┆ 164   ┆ 2001 │
│ Momaday, N. Scott      ┆ Dům z úsvitu                    ┆ 167   ┆ 2001 │
│ Potok, Chaim,          ┆ Na počátku                      ┆ 424   ┆ 2001 │
│ Eggers, Dave,          ┆ Srdceryvné dílo ohromujícího g… ┆ 382   ┆ 2001 │
│ Kosiński, Jerzy N.,    ┆ Nabarvené ptáče                 ┆ 215   ┆ 2001 │
│ Gray, Alasdair,        ┆ Lanark                          ┆ 605   ┆ 2002 │
│ Johnson, B. S.         ┆ Nešťastníci                     ┆ 110   ┆ 2002 │
│ Robbins, Tom,          ┆ V žabím pyžamu                  ┆ 370   ┆ 2002 │
│ Mills, Magnus,         ┆ Tři za králem šli               ┆ 132   ┆ 2002 │
│ Jackson, Mick,         ┆ Pětka                           ┆ 201   ┆ 2003 │
│ Kesey, Ken,            ┆ Námořníkova píseň               ┆ 478   ┆ 2003 │
│ Potok, Chaim,          ┆ Staří muži o půlnoci            ┆ 194   ┆ 2003 │
│ Banks, Iain,           ┆ Most                            ┆ 297   ┆ 2003 │
│ Potok, Chaim,          ┆ Slib                            ┆ 315   ┆ 2003 │
│ Carey, Peter,          ┆ Pravdivý příběh Neda Kellyho a… ┆ 371   ┆ 2003 │
│ Robbins, Tom,          ┆ Parfém bláznivého tance         ┆ 379   ┆ 2003 │
│ Richler, Mordecai,     ┆ Učňovská léta Duddyho Kravitze  ┆ 313   ┆ 2003 │
│ Winterson, Jeanette,   ┆ Jak naštěpit třešeň             ┆ 137   ┆ 2004 │
│ Martel, Yann,          ┆ Pí a jeho život                 ┆ 350   ┆ 2004 │
│ Toole, John Kennedy,   ┆ Neónová bible                   ┆ 121   ┆ 2004 │
│ Richler, Mordecai,     ┆ Byl tu Šalomoun Gursky          ┆ 506   ┆ 2004 │
│ Potok, Chaim,          ┆ Davitina harfa                  ┆ 320   ┆ 2004 │
│ Smith, Ali,            ┆ Jiné povídky a jiné povídky     ┆ 146   ┆ 2005 │
│ Kosiński, Jerzy N.,    ┆ Schůzka na slepo                ┆ 233   ┆ 2005 │
│ Thirlwell, Adam,       ┆ Politika                        ┆ 213   ┆ 2005 │
│ Martel, Yann,          ┆ Fakta v pozadí případu Roccama… ┆ 146   ┆ 2005 │
│ Kesey, Ken,            ┆ Poslední kolo                   ┆ 235   ┆ 2005 │
│ Welsh, Louise,         ┆ Tamerlán musí zemřít            ┆ 82    ┆ 2005 │
│ Trevor, William,       ┆ Den, kdy jsme se opili dortem … ┆ 166   ┆ 2005 │
│ Krauss, Nicole,        ┆ Dějiny lásky                    ┆ 245   ┆ 2006 │
│ Chabon, Michael,       ┆ Modelový svět                   ┆ 143   ┆ 2006 │
│ Burroughs, Augusten    ┆ Hlava nehlava                   ┆ 237   ┆ 2006 │
│ Welsh, Louise,         ┆ Řezárna                         ┆ 232   ┆ 2006 │
│ Atkinson, Kate,        ┆ V zákulisí muzea                ┆ 305   ┆ 2006 │
│ Donleavy, J. P.        ┆ Zrzoun                          ┆ 310   ┆ 2006 │
│ McCarthy, Cormac,      ┆ Tahle země není pro starý       ┆ 199   ┆ 2007 │
│ Ondaatje, Michael,     ┆ Anglický pacient                ┆ 265   ┆ 2007 │
│ Williams, John,        ┆ Pět hospod, dva bary a jeden n… ┆ 163   ┆ 2007 │
│ McCarthy, Cormac,      ┆ Cesta                           ┆ 185   ┆ 2008 │
│ McCarthy, Cormac,      ┆ Všichni krásní koně             ┆ 260   ┆ 2008 │
│ McCarthy, Cormac,      ┆ Hranice                         ┆ 346   ┆ 2008 │
│ Boyle, T. Coraghessan, ┆ Řeči řeči                       ┆ 356   ┆ 2008 │
│ Robinson, Marilynne,   ┆ Ztrácení                        ┆ 200   ┆ 2008 │
│ Pessl, Marisha,        ┆ Vybrané okruhy z mechaniky poh… ┆ 435   ┆ 2008 │
│ Welsh, Louise,         ┆ Falešná trefa                   ┆ 301   ┆ 2009 │
│ McCarthy, Cormac,      ┆ Krvavý poledník, aneb, Večerní… ┆ 389   ┆ 2009 │
│ Donleavy, J. P.        ┆ Bezuzdná blahoslavenství Balta… ┆ 416   ┆ 2009 │
│ Díaz, Junot,           ┆ Krátký, leč divuplný život Osk… ┆ 314   ┆ 2009 │
│ Richler, Mordecai,     ┆ Jezdec z Ulice sv. Urbana       ┆ 514   ┆ 2009 │
│ Krauss, Nicole,        ┆ Muž vejde do pokoje             ┆ 264   ┆ 2009 │
│ Cave, Nick,            ┆ Smrt Zajdy Munroa               ┆ 238   ┆ 2009 │
│ Lahiri, Jhumpa,        ┆ Tlumočník nemocí                ┆ 179   ┆ 2009 │
│ McCarthy, Cormac,      ┆ Dítě Boží                       ┆ 180   ┆ 2009 │
│ Lahiri, Jhumpa,        ┆ Nezvyklá země                   ┆ 322   ┆ 2010 │
│ Atkinson, Kate,        ┆ Neuzavřené případy              ┆ 304   ┆ 2010 │
│ Rapp, Adam,            ┆ Rok nekonečného strádání        ┆ 458   ┆ 2010 │
│ McCarthy, Cormac,      ┆ Města na planině                ┆ 294   ┆ 2010 │
│ Chaon, Dan,            ┆ Čekat Vaše odpověď              ┆ 326   ┆ 2010 │
│ Barthelme, Donald,     ┆ Mrtvý otec                      ┆ 174   ┆ 2010 │
│ Martel, Yann,          ┆ Beatrice a Vergilius            ┆ 158   ┆ 2011 │
│ Kosiński, Jerzy N.,    ┆ Nabarvené ptáče                 ┆ 215   ┆ 2011 │
│ Krauss, Nicole,        ┆ Dějiny lásky                    ┆ 246   ┆ 2011 │
│ Vann, David,           ┆ Ostrov Sukkwan                  ┆ 160   ┆ 2011 │
│ McCarthy, Cormac,      ┆ Vnější tma                      ┆ 218   ┆ 2011 │
│ Krauss, Nicole,        ┆ Velký dům                       ┆ 307   ┆ 2012 │
│ McCarthy, Cormac,      ┆ Strážce sadu                    ┆ 227   ┆ 2012 │
│ McCarthy, Cormac,      ┆ Suttree                         ┆ 511   ┆ 2012 │
│ Shteyngart, Gary,      ┆ Megasmutná pravdivá lovestory   ┆ 413   ┆ 2013 │
│ Franzen, Jonathan,     ┆ Svoboda                         ┆ 415   ┆ 2013 │
│ Torres, Justin,        ┆ My, zvířata                     ┆ 127   ┆ 2013 │
│ Self, Will,            ┆ Deštník                         ┆ 346   ┆ 2014 │
│ Oyeyemi, Helen,        ┆ Dívka jménem Boy                ┆ 263   ┆ 2016 │
│ Holmes, John Clellon,  ┆ Jeď!                            ┆ 419   ┆ 2016 │
│ Pynchon, Thomas,       ┆ Výkřik techniky                 ┆ 518   ┆ 2017 │
│ Ishiguro, Kazuo,       ┆ Pohřbený obr                    ┆ 318   ┆ 2017 │
│ Ishiguro, Kazuo,       ┆ Neopouštěj mě                   ┆ 301   ┆ 2018 │
│ Ishiguro, Kazuo,       ┆ Malíř pomíjivého světa          ┆ 196   ┆ 2018 │
│ Cave, Nick,            ┆ Smrt Zajdy Munroa               ┆ 239   ┆ 2019 │
│ Vann, David,           ┆ Akvárium                        ┆ 230   ┆ 2019 │
│ Cohen, Leonard,        ┆ Nádherní poražení               ┆ 260   ┆ 2019 │
│ Kerouac, Jack,         ┆ Na cestě                        ┆ 392   ┆ 2019 │
│ McCarthy, Cormac,      ┆ Krvavý poledník, aneb, Večerní… ┆ 391   ┆ 2019 │
│ St. Aubyn, Edward,     ┆ Patrick Melrose                 ┆ null  ┆ 2019 │
│ Ishiguro, Kazuo,       ┆ Neutěšenci                      ┆ 637   ┆ 2020 │
│ McCarthy, Cormac,      ┆ Tahle země není pro starý       ┆ 237   ┆ 2020 │
│ Cohen, Leonard,        ┆ Oblíbená hra                    ┆ 285   ┆ 2020 │
│ Burns, Anna,           ┆ Mlíkař                          ┆ 412   ┆ 2020 │
│ Irving, John,          ┆ Modlitba za Owena Meanyho       ┆ 720   ┆ 2021 │
└────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [13]:
edice("Květy poezie")

shape: (228, 4)
┌─────────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                           ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                             ┆ ---                             ┆ ---   ┆ ---  │
│ str                             ┆ str                             ┆ i64   ┆ i64  │
╞═════════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Goethe, Johann Wolfgang von,    ┆ Balady                          ┆ 85    ┆ 1958 │
│ Tasso, Torquato,                ┆ Lyrika                          ┆ 125   ┆ 1958 │
│ Nezval, Vítězslav,              ┆ Edison                          ┆ 109   ┆ 1958 │
│ Rimbaud, Arthur,                ┆ Výbor                           ┆ 175   ┆ 1959 │
│ Poe, Edgar Allan,               ┆ Havran                          ┆ 89    ┆ 1959 │
│ Corbière, Tristan,              ┆ Žluté lásky                     ┆ 92    ┆ 1959 │
│ Catullus, Gaius Valerius,       ┆ Básně                           ┆ 198   ┆ 1959 │
│ Dyk, Viktor,                    ┆ Milá sedmi loupežníků           ┆ 125   ┆ 1959 │
│ Rictus, Jehan,                  ┆ Poezie                          ┆ 87    ┆ 1959 │
│ Hrubín, František,              ┆ Jobova noc                      ┆ 53    ┆ 1959 │
│ Byron, George Gordon Byron,     ┆ Lyrika                          ┆ 123   ┆ 1959 │
│ Verhaeren, Émile,               ┆ Žárné chorály                   ┆ 128   ┆ 1960 │
│ Hořejší, Jindřich,              ┆ Hudba na náměstí                ┆ 92    ┆ 1960 │
│ Jeffers, Robinson,              ┆ Hřebec grošák                   ┆ 87    ┆ 1960 │
│ Sandburg, Carl,                 ┆ Ocel a dým                      ┆ 179   ┆ 1960 │
│ Nekrasov, Nikolaj Aleksejevič,  ┆ Ruské ženy                      ┆ 128   ┆ 1960 │
│ Závada, Vilém,                  ┆ Vzduch a světlo                 ┆ 177   ┆ 1960 │
│ Ovidius,                        ┆ Listy heroin                    ┆ 81    ┆ 1960 │
│ Espronceda, José de,            ┆ Výbor                           ┆ 153   ┆ 1961 │
│ Verlaine, Paul,                 ┆ Mé tuláctví                     ┆ 87    ┆ 1961 │
│ Browning, Elizabeth Barrett,    ┆ Portugalské sonety              ┆ 79    ┆ 1961 │
│ Ševčenko, Taras Hryhorovyč,     ┆ V tom ráji na zemi              ┆ 93    ┆ 1961 │
│ Hora, Josef,                    ┆ Zahrada Popelčina               ┆ 96    ┆ 1961 │
│ García Lorca, Federico,         ┆ Písně na andaluskou notu        ┆ 251   ┆ 1961 │
│ Tóth, Árpád,                    ┆ Od srdce k srdci                ┆ 119   ┆ 1961 │
│ Neruda, Pablo,                  ┆ Semena bouře                    ┆ 115   ┆ 1961 │
│ Holan, Vladimír,                ┆ Terezka Planetová               ┆ 85    ┆ 1962 │
│ Propertius, Sextus,             ┆ Elegie                          ┆ 103   ┆ 1962 │
│ Shelley, Percy Bysshe,          ┆ Odpoutaný Prométheus            ┆ 174   ┆ 1962 │
│ Bagrickij, Èduard Georgijevič,  ┆ Thyl Ulenspiegel                ┆ 89    ┆ 1962 │
│ Heine, Heinrich,                ┆ Meč a plamen                    ┆ 128   ┆ 1962 │
│ Camões, Luís de,                ┆ Msti se mým slzám               ┆ 111   ┆ 1962 │
│ Hughes, Langston,               ┆ Harlemský zpěvník               ┆ 120   ┆ 1963 │
│ Chénier, André,                 ┆ Sen o Heladě                    ┆ 99    ┆ 1963 │
│ Halas, František,               ┆ Sbohem, múzy                    ┆ 241   ┆ 1963 │
│ Bednář, Kamil,                  ┆ Krásných paní milování a jiné … ┆ 107   ┆ 1963 │
│ Brecht, Bertolt,                ┆ Domácí postila Bertolta Brecht… ┆ 178   ┆ 1963 │
│ Anakreón,                       ┆ Oslavujme Bakcha                ┆ 94    ┆ 1963 │
│ Quevedo, Francisco de,          ┆ Kruté sny                       ┆ 152   ┆ 1963 │
│ Sel'vinskij, Il'ja L'vovič,     ┆ Pohár oceánu                    ┆ 149   ┆ 1963 │
│ Kästner, Erich,                 ┆ Z malých dějin                  ┆ 145   ┆ 1963 │
│ Blake, William,                 ┆ Svět v zrnku písku              ┆ 153   ┆ 1964 │
│ Ovidius,                        ┆ Listy heroin                    ┆ 110   ┆ 1964 │
│ Hesse, Hermann,                 ┆ Stupně                          ┆ 98    ┆ 1964 │
│ Morgenstern, Christian,         ┆ Palmström a Palma Kunkel        ┆ 172   ┆ 1964 │
│ Radnóti, Miklós,                ┆ A přece se vrátím               ┆ 197   ┆ 1964 │
│ Shakespeare, William,           ┆ Sonety                          ┆ 168   ┆ 1964 │
│ Cendrars, Blaise,               ┆ V srdci světa                   ┆ 132   ┆ 1964 │
│ Baudelaire, Charles,            ┆ Květy zla                       ┆ 232   ┆ 1964 │
│ Mikulášek, Oldřich,             ┆ Divoké kačeny                   ┆ 107   ┆ 1964 │
│ Hrubín, František,              ┆ Hirošima                        ┆ 139   ┆ 1964 │
│ Bai, Juyi,                      ┆ Drak z černé tůně               ┆ 109   ┆ 1964 │
│ Frič, Josef,                    ┆ Umělé květiny                   ┆ 175   ┆ 1965 │
│ Jesenin, Sergej Aleksandrovič,  ┆ Modravá Rus                     ┆ 163   ┆ 1965 │
│ Werfel, Franz,                  ┆ Přítel světa                    ┆ 141   ┆ 1965 │
│ Toulet, Paul-Jean,              ┆ Kam odcházíš, kráso?            ┆ 106   ┆ 1965 │
│ Thomas, Dylan,                  ┆ Kapradinový vrch                ┆ 122   ┆ 1965 │
│ Coleridge, Samuel Taylor,       ┆ Dračí křídlo stesku             ┆ 152   ┆ 1965 │
│ Weiner, Richard,                ┆ Mezopotamie                     ┆ 187   ┆ 1965 │
│ Holan, Vladimír,                ┆ Ptala se tě--                   ┆ 233   ┆ 1965 │
│ Desbordes-Valmore, Marceline,   ┆ Knížka něžností                 ┆ 67    ┆ 1966 │
│ Rilke, Rainer Maria,            ┆ Kniha obrazů                    ┆ 213   ┆ 1966 │
│ Ujević, Tin,                    ┆ Žíznivý kámen na prameni        ┆ 67    ┆ 1966 │
│ Eichendorff, Joseph von,        ┆ Věčný poutník stesk             ┆ 170   ┆ 1966 │
│ Belyj, Andrej,                  ┆ První setkání                   ┆ 89    ┆ 1966 │
│ Březina, Otokar,                ┆ Modlitba za nepřátele           ┆ 229   ┆ 1966 │
│ Valéry, Paul,                   ┆ Básně                           ┆ 182   ┆ 1966 │
│ Bingxin,                        ┆ Hvězdy a Jarní vody             ┆ 66    ┆ 1967 │
│ Lundkvist, Artur,               ┆ Okamžiky a vlny                 ┆ 134   ┆ 1967 │
│ Słowacki, Juliusz,              ┆ Beniowski                       ┆ 176   ┆ 1967 │
│ Novalis,                        ┆ Květinový prach                 ┆ 122   ┆ 1967 │
│ Puškin, Aleksandr Sergejevič,   ┆ Spálený dopis                   ┆ 90    ┆ 1967 │
│ Donne, John,                    ┆ Extáze                          ┆ 132   ┆ 1967 │
│ Kainar, Josef,                  ┆ Třináct kytar                   ┆ 144   ┆ 1967 │
│ Claudianus, Claudius,           ┆ O únosu Persefony               ┆ 118   ┆ 1967 │
│ Campana, Dino,                  ┆ Šílený Orfeus                   ┆ 146   ┆ 1968 │
│ Desbordes-Valmore, Marceline,   ┆ Knížka něžností                 ┆ 67    ┆ 1968 │
│ Bunin, Ivan Aleksejevič,        ┆ Hořký dým paměti                ┆ 124   ┆ 1968 │
│ Seifert, Jaroslav,              ┆ Nejkrásnější bývá šílená        ┆ 124   ┆ 1968 │
│ Jeffers, Robinson,              ┆ Sbohem moře                     ┆ 111   ┆ 1968 │
│ Norwid, Cyprian Kamil,          ┆ Mramory a blesky                ┆ 191   ┆ 1968 │
│ Orten, Jiří,                    ┆ Hrob nezavřel se                ┆ 164   ┆ 1969 │
│ Petrarca, Francesco,            ┆ Kanzóny pro Lauru               ┆ 148   ┆ 1969 │
│ Lenau, Nikolaus,                ┆ Blesky nad roklí                ┆ 117   ┆ 1969 │
│ Claudel, Paul,                  ┆ Múza Milost                     ┆ 138   ┆ 1969 │
│ Martí, José,                    ┆ Raněný orel                     ┆ 112   ┆ 1970 │
│ Lasker-Schüler, Else,           ┆ Klaviatura srdce                ┆ 133   ┆ 1970 │
│ Musset, Alfred de,              ┆ Noci                            ┆ 127   ┆ 1970 │
│ Cvetajeva, Marina Ivanovna,     ┆ Pokus o žárlivost               ┆ 90    ┆ 1970 │
│ Michelangelo Buonarroti,        ┆ Žiji svou smrtí                 ┆ 165   ┆ 1970 │
│ Blok, Aleksandr Aleksandrovič,  ┆ Poslední jamby                  ┆ 96    ┆ 1971 │
│ Eliot, T. S.                    ┆ Vražda v katedrále              ┆ 118   ┆ 1971 │
│ Fabry, Rudolf,                  ┆ Já je někdo jiný                ┆ 94    ┆ 1971 │
│ Ovidius,                        ┆ Listy heroin                    ┆ 137   ┆ 1971 │
│ Goethe, Johann Wolfgang von,    ┆ Život slavím                    ┆ 132   ┆ 1972 │
│ Jesenský, Janko,                ┆ Je láska jako větru šum         ┆ 93    ┆ 1972 │
│ Neumann, Stanislav Kostka,      ┆ Skřivan a lokomotiva            ┆ 126   ┆ 1972 │
│ Leśmian, Bolesław,              ┆ Zelená hodina                   ┆ 128   ┆ 1972 │
│ Majakovskij, Vladimir Vladimir… ┆ Správná věc!                    ┆ 131   ┆ 1972 │
│ Wolker, Jiří,                   ┆ Jitřní píseň                    ┆ 112   ┆ 1973 │
│ Browning, Elizabeth Barrett,    ┆ Portugalské sonety              ┆ 74    ┆ 1973 │
│ Becher, Johannes R.,            ┆ Bílý zázrak                     ┆ 157   ┆ 1973 │
│ Bokov, Viktor Fedorovič,        ┆ Vítr v dlaních                  ┆ 133   ┆ 1974 │
│ Válek, Miroslav,                ┆ Dotyky                          ┆ 130   ┆ 1974 │
│ Hálek, Vítězslav,               ┆ Srdce písněmi dotýkané          ┆ 154   ┆ 1974 │
│ Slavík, Ivan,                   ┆ Motýl z obsidiánu               ┆ 170   ┆ 1974 │
│ Jesenin, Sergej Aleksandrovič,  ┆ Oheň jeřabin                    ┆ 124   ┆ 1975 │
│ Tvardovskij, Aleksandr Trifono… ┆ Z lyriky těchto let             ┆ 82    ┆ 1975 │
│ Toman, Karel,                   ┆ Vlastní podobizna               ┆ 163   ┆ 1975 │
│ Vega, Lope de,                  ┆ Proč unikáš mi                  ┆ 140   ┆ 1975 │
│ Miłosz, Oskar Wladisław de Lub… ┆ Divoký sad vzpomínek            ┆ 85    ┆ 1975 │
│ Bal‘mont, Konstantin Dmitrijev… ┆ Sonety slunce, medu a luny      ┆ 141   ┆ 1976 │
│ Skála, Ivan,                    ┆ Čí je jaro                      ┆ 143   ┆ 1976 │
│ Baudelaire, Charles,            ┆ Květy zla                       ┆ 152   ┆ 1976 │
│ Keats, John,                    ┆ Obrys krásy                     ┆ 118   ┆ 1977 │
│ Baratynskij, Jevgenij Abramovi… ┆ Vyznání za soumraku             ┆ 124   ┆ 1977 │
│ Dickinson, Emily,               ┆ Můj dopis světu                 ┆ 109   ┆ 1977 │
│ Hrubín, František,              ┆ Nefritová flétna                ┆ 134   ┆ 1978 │
│ Hora, Josef,                    ┆ Na neshledanou, vteřiny         ┆ 149   ┆ 1978 │
│ Nekrasov, Nikolaj Aleksejevič,  ┆ Mráz, pán krutých krás          ┆ 61    ┆ 1978 │
│ Éluard, Paul,                   ┆ Nepřerušená poezie              ┆ 142   ┆ 1978 │
│ Darío, Rubén,                   ┆ Toulavý zpěv                    ┆ 119   ┆ 1979 │
│ Hofmannsthal, Hugo von,         ┆ Píseň na cestu                  ┆ 106   ┆ 1979 │
│ Skujiņa, Austra,                ┆ Jako křik ptáka                 ┆ 142   ┆ 1979 │
│ Žáry, Štefan,                   ┆ Opojení                         ┆ 122   ┆ 1979 │
│ Mörike, Eduard,                 ┆ Proč bolíš, radosti?            ┆ 131   ┆ 1979 │
│ Alver, Betti,                   ┆ Hrom je můj bratr               ┆ 122   ┆ 1980 │
│ Florian, Miroslav,              ┆ Jednou provždy                  ┆ 170   ┆ 1980 │
│ Arghezi, Tudor,                 ┆ Nápisy                          ┆ 117   ┆ 1980 │
│ Laforgue, Jules,                ┆ Sólo Luny                       ┆ 126   ┆ 1981 │
│ Horov, Pavol,                   ┆ Ponorná řeka                    ┆ 154   ┆ 1981 │
│ Stehlík, Ladislav,              ┆ Krajina plná znamení            ┆ 108   ┆ 1981 │
│ Rainis, Jānis,                  ┆ Daleké ozvěny                   ┆ 141   ┆ 1982 │
│ Dyk, Viktor,                    ┆ Dobré slovo příštím             ┆ 119   ┆ 1982 │
│ Pilař, Jan,                     ┆ Jabloně                         ┆ 145   ┆ 1982 │
│ Frost, Robert,                  ┆ Hvězda v kamenném člunu         ┆ 121   ┆ 1983 │
│ Baczyński, Krzysztof Kamil,     ┆ Spálené růže                    ┆ 146   ┆ 1983 │
│ Feldek, Ľubomír,                ┆ Hudba před milováním            ┆ 122   ┆ 1983 │
│ Plath, Sylvia,                  ┆ Ariel                           ┆ 121   ┆ 1984 │
│ Neruda, Jan,                    ┆ Zelená hvězdo v zenitu          ┆ 151   ┆ 1984 │
│ Jesenin, Sergej Aleksandrovič,  ┆ Ryšavý podzim                   ┆ 199   ┆ 1984 │
│ Wolker, Jiří,                   ┆ Jitřní píseň                    ┆ 92    ┆ 1985 │
│ Křička, Petr,                   ┆ Květ šípkový                    ┆ 162   ┆ 1986 │
│ Rúfus, Milan,                   ┆ Oféliin pohřeb                  ┆ 200   ┆ 1986 │
│ Hrubín, František,              ┆ Hirošima                        ┆ 127   ┆ 1987 │
│ Ovidius,                        ┆ Listy heroin                    ┆ 140   ┆ 1987 │
│ Bednář, Kamil,                  ┆ Sladkost hořkosti               ┆ 152   ┆ 1987 │
│ Tumanjan, Ovanes,               ┆ Zní šalmaj z hor                ┆ 109   ┆ 1987 │
│ Harasymowicz, Jerzy,            ┆ Černý bez                       ┆ 160   ┆ 1988 │
│ Kraus, Karl,                    ┆ Moc a bezmoc slova              ┆ 127   ┆ 1988 │
│ Kainar, Josef,                  ┆ Netrpěliví motýli               ┆ 124   ┆ 1988 │
│ Rexroth, Kenneth,               ┆ Spirály času                    ┆ 93    ┆ 1989 │
│ Gellner, František,             ┆ Teplo zhaslého plamene          ┆ 139   ┆ 1989 │
│ Sova, Antonín,                  ┆ Vrchol lásky                    ┆ 121   ┆ 1989 │
│ Lawrence, D. H.                 ┆ Sopečná růže                    ┆ 204   ┆ 1990 │
│ Wen, Yiduo,                     ┆ Mrtvá voda                      ┆ 91    ┆ 1990 │
│ Werfel, Franz,                  ┆ V domě dětství                  ┆ 139   ┆ 1990 │
│ Rutebeuf,                       ┆ Život bez rukávů                ┆ 107   ┆ 1991 │
│ García Lorca, Federico,         ┆ Krev noci                       ┆ 156   ┆ 1991 │
│ Li, Qingzhao,                   ┆ Květy skořicovníku              ┆ 110   ┆ 1992 │
│ Miłosz, Czesław,                ┆ Hymnus o perle                  ┆ 149   ┆ 1992 │
│ Fikar, Ladislav,                ┆ Samotín                         ┆ 196   ┆ 1992 │
│ Durych, Jaroslav,               ┆ Osamělé květy                   ┆ 148   ┆ 1993 │
│ Pištora, Jiří,                  ┆ Mezery v paměti                 ┆ 94    ┆ 1993 │
│ Skácel, Jan,                    ┆ Stracholam                      ┆ 195   ┆ 1993 │
│ Krleža, Miroslav,               ┆ Balady Petrici Kerempuha        ┆ 175   ┆ 1994 │
│ Kostohryz, Josef,               ┆ Strmá nenaděj                   ┆ 148   ┆ 1994 │
│ Keats, John,                    ┆ Déšť z plané růže               ┆ 184   ┆ 1994 │
│ Orten, Jiří,                    ┆ Hrob nezavřel se                ┆ 170   ┆ 1994 │
│ Góngora y Argote, Luis de,      ┆ Plody Tantalovy                 ┆ 94    ┆ 1994 │
│ Günther, Johann Christian,      ┆ Krvavý rubín                    ┆ 114   ┆ 1995 │
│ Kolman Cassius, Jaroslav,       ┆ Stesk stráže                    ┆ 189   ┆ 1995 │
│ Villon, François,               ┆ Básně                           ┆ 109   ┆ 1995 │
│ Gumilev, Nikolaj Stepanovič,    ┆ Cizí nebe                       ┆ 158   ┆ 1995 │
│ Larkin, Philip,                 ┆ Vysoká okna                     ┆ 112   ┆ 1995 │
│ Seifert, Jaroslav,              ┆ Nejkrásnější bývá šílená        ┆ 136   ┆ 1996 │
│ Holan, Vladimír,                ┆ Testamenty                      ┆ 150   ┆ 1996 │
│ Matsuo, Bashō,                  ┆ Měsíce, květy                   ┆ 169   ┆ 1996 │
│ Erben, Karel Jaromír,           ┆ Kytice                          ┆ 162   ┆ 1996 │
│ Kryl, Karel,                    ┆ Znamení doby                    ┆ 163   ┆ 1996 │
│ Gellner, František,             ┆ Teplo zhaslého plamene          ┆ 138   ┆ 1997 │
│ Szymborska, Wisława,            ┆ Konec a počátek                 ┆ 153   ┆ 1997 │
│ Prévert, Jacques,               ┆ Pro tebe, má lásko              ┆ 131   ┆ 1997 │
│ Seifert, Jaroslav,              ┆ Maminka                         ┆ 84    ┆ 1997 │
│ Kavafīs, Kōnstantinos P.,       ┆ Nebezpečné touhy                ┆ 129   ┆ 1997 │
│ Baudelaire, Charles,            ┆ Květy zla                       ┆ 145   ┆ 1997 │
│ Hiršal, Josef,                  ┆ Párkař                          ┆ 54    ┆ 1997 │
│ Camões, Luís de,                ┆ Trýzeň i útěcha                 ┆ 106   ┆ 1997 │
│ Brodskij, Iosif Aleksandrovič,  ┆ Konec krásné epochy             ┆ 141   ┆ 1997 │
│ Alighieri, Dante,               ┆ To sladké jméno Beatrice        ┆ 126   ┆ 1998 │
│ Ronsard, Pierre de,             ┆ Tři lásky                       ┆ 92    ┆ 1998 │
│ Hlaváček, Karel,                ┆ Budu snít marně                 ┆ 105   ┆ 1998 │
│ Hrubín, František,              ┆ Romance pro křídlovku           ┆ 70    ┆ 1998 │
│ Mickiewicz, Adam,               ┆ Balady a romance                ┆ 157   ┆ 1998 │
│ Bécquer, Gustavo Adolfo,        ┆ Sloky                           ┆ 146   ┆ 1998 │
│ Thákur, Rabíndranáth,           ┆ Zahradník                       ┆ 124   ┆ 1999 │
│ Li, Po,                         ┆ Nebe mi pokrývkou a země polšt… ┆ 143   ┆ 1999 │
│ Ringelnatz, Joachim,            ┆ Stará láska nerezaví            ┆ 118   ┆ 1999 │
│ Mácha, Karel Hynek,             ┆ Máj                             ┆ 79    ┆ 1999 │
│ Heaney, Seamus,                 ┆ Přezimování pod širým nebem     ┆ 153   ┆ 1999 │
│ Pilinszky, János,               ┆ Ortel                           ┆ 157   ┆ 1999 │
│ Nezval, Vítězslav,              ┆ Básně noci                      ┆ 141   ┆ 1999 │
│ Creeley, Robert,                ┆ Zahrady paměti                  ┆ 135   ┆ 1999 │
│ Morgenstern, Christian,         ┆ Písně šibeničních bratří        ┆ 143   ┆ 2000 │
│ Hrabal, Bohumil,                ┆ Bambino di Praga                ┆ 111   ┆ 2000 │
│ Ginsberg, Allen,                ┆ Slovy a dechem                  ┆ 147   ┆ 2000 │
│ Nezval, Vítězslav,              ┆ Manon Lescaut                   ┆ 253   ┆ 2001 │
│ Desbordes-Valmore, Marceline,   ┆ Knížka něžností                 ┆ 67    ┆ 2001 │
│ Nguyen Binh,                    ┆ Tisíc oken                      ┆ 88    ┆ 2001 │
│ Wernisch, Ivan,                 ┆ Půjdeme do Mů                   ┆ 96    ┆ 2002 │
│ Parra, Nicanor,                 ┆ Básně proti plešatění           ┆ 132   ┆ 2002 │
│ Karásek ze Lvovic, Jiří,        ┆ Sodoma                          ┆ 92    ┆ 2002 │
│ Li, Qingzhao,                   ┆ Květy skořicovníku              ┆ 108   ┆ 2002 │
│ Elytis, Odysseus,               ┆ Bláznivý granátovník            ┆ 133   ┆ 2003 │
│ Lamartine, Alphonse de,         ┆ Básnické meditace               ┆ 124   ┆ 2003 │
│ Hutka, Jaroslav,                ┆ Pravděpodobnej svět             ┆ 132   ┆ 2003 │
│ Koneski, Blaže,                 ┆ Poslání                         ┆ 144   ┆ 2003 │
│ Kryl, Karel,                    ┆ Znamení doby                    ┆ 163   ┆ 2004 │
│ Cohen, Leonard,                 ┆ Květiny pro Hitlera             ┆ 201   ┆ 2004 │
│ Ko, Ŭn,                         ┆ Květy okamžiku                  ┆ 94    ┆ 2005 │
│ Shakespeare, William,           ┆ Sonety                          ┆ 172   ┆ 2005 │
│ Holan, Vladimír,                ┆ Mozartiana                      ┆ 56    ┆ 2006 │
│ Graves, Robert,                 ┆ Kráska v nesnázích              ┆ 135   ┆ 2006 │
│ Kotrlý, Zdeněk,                 ┆ Souznička                       ┆ 189   ┆ 2006 │
│ Fischer, Otokar,                ┆ Poutník a píseň                 ┆ 145   ┆ 2008 │
│ Erben, Karel Jaromír,           ┆ Kytice                          ┆ 162   ┆ 2009 │
│ Erben, Karel Jaromír,           ┆ Kytice                          ┆ 162   ┆ 2021 │
│ Erben, Karel Jaromír,           ┆ Kytice                          ┆ 162   ┆ 2024 │
└─────────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [14]:
edice("Krystal", nakladatelstvi="SNDK")

shape: (10, 5)
┌───────────────────────────────┬───────────────────────┬────────────────┬──────┬───────┐
│ 100_a                         ┆ 245_a                 ┆ 300_a          ┆ rok  ┆ stran │
│ ---                           ┆ ---                   ┆ ---            ┆ ---  ┆ ---   │
│ str                           ┆ str                   ┆ str            ┆ i64  ┆ i64   │
╞═══════════════════════════════╪═══════════════════════╪════════════════╪══════╪═══════╡
│ Adla, Zdeněk,                 ┆ Krásná a slavná       ┆ 257, [7] s. :  ┆ 1961 ┆ 257   │
│ Bojarová, Olga,               ┆ Od hlavy k patě       ┆ 186, [6] s. ;  ┆ 1961 ┆ 186   │
│ Petr, Tomislav,               ┆ Divy oceánů           ┆ 174 s. :       ┆ 1962 ┆ 174   │
│ Koval, Václav,                ┆ Na dně vzdušného moře ┆ 221, [4] s. ;  ┆ 1962 ┆ 221   │
│ Štuka, Ivo,                   ┆ Šest dnů na luně 1    ┆ 200, [3] s. ;  ┆ 1963 ┆ 200   │
│ Houška, Vítězslav,            ┆ Jak s tím pohnu       ┆ 188 s. ;       ┆ 1965 ┆ 188   │
│ Tichý, Jaroslav,              ┆ Letem ČSSR            ┆ 214, [6] s. ;  ┆ 1965 ┆ 214   │
│ Elstner, František Alexander, ┆ Motorové opojení      ┆ 207, [5] s. ;  ┆ 1966 ┆ 207   │
│ Deyl, Václav,                 ┆ Tajemství plamenů     ┆ 185, [7] s. :  ┆ 1967 ┆ 185   │
│ Hons, Josef,                  ┆ A štafeta běží dál    ┆ 214, [34] s. : ┆ 1967 ┆ 214   │
└───────────────────────────────┴───────────────────────┴────────────────┴──────┴───────┘

In [15]:
zjisti("Nová divočina")

ReX

shape: (2, 6)
┌────────────────┬───────────────┬───────┬──────┬───────┬──────────────────┐
│ 100_a          ┆ 245_a         ┆ 260_b ┆ rok  ┆ stran ┆ 490_a            │
│ ---            ┆ ---           ┆ ---   ┆ ---  ┆ ---   ┆ ---              │
│ str            ┆ str           ┆ str   ┆ i64  ┆ i64   ┆ str              │
╞════════════════╪═══════════════╪═══════╪══════╪═══════╪══════════════════╡
│ Zbořil, Jonáš, ┆ Nová divočina ┆ null  ┆ 2020 ┆ 77    ┆ ReX              │
│ Cook, Diane,   ┆ Nová divočina ┆ null  ┆ 2022 ┆ 460   ┆ Světová knihovna │
└────────────────┴───────────────┴───────┴──────┴───────┴──────────────────┘

In [16]:
edice("ReX")

shape: (35, 4)
┌──────────────────────────┬────────────────────────────────┬───────┬──────┐
│ 100_a                    ┆ 245_a                          ┆ stran ┆ rok  │
│ ---                      ┆ ---                            ┆ ---   ┆ ---  │
│ str                      ┆ str                            ┆ i64   ┆ i64  │
╞══════════════════════════╪════════════════════════════════╪═══════╪══════╡
│ Hruška, Petr,            ┆ Auta vjíždějí do lodí          ┆ 65    ┆ 2007 │
│ Slíva, Vít,              ┆ Souvrať                        ┆ 74    ┆ 2007 │
│ Malý, Radek,             ┆ Malá tma                       ┆ 71    ┆ 2008 │
│ Urbánková, Dagmar,       ┆ Ta hlava větru vypadá jako pes ┆ 107   ┆ 2008 │
│ Kudláček, Slavomír,      ┆ Schůzka v lomu                 ┆ 75    ┆ 2009 │
│ Machulková, Inka,        ┆ Zamkni les a pojď              ┆ 85    ┆ 2009 │
│ Žila, Jaroslav,          ┆ V hrudi pták                   ┆ 66    ┆ 2010 │
│ Žila, Jaroslav,          ┆ V hrudi pták                   ┆ 66    ┆ 2010 │
│ Reiner, Martin,          ┆ Hubená stehna Twiggy           ┆ 103   ┆ 2010 │
│ Šťastná, Marie,          ┆ Interiéry                      ┆ 71    ┆ 2010 │
│ Slíva, Vít,              ┆ Račí mor                       ┆ 89    ┆ 2011 │
│ Fridrich, Radek,         ┆ Krooa krooa                    ┆ 63    ┆ 2011 │
│ Hruška, Petr,            ┆ Darmata                        ┆ 52    ┆ 2012 │
│ Děžinský, Milan,         ┆ Tajný život                    ┆ 70    ┆ 2012 │
│ Malý, Radek,             ┆ Světloplaší                    ┆ 97    ┆ 2012 │
│ Stöhr, Martin Josef,     ┆ Smích ze snu                   ┆ 63    ┆ 2012 │
│ Hruška, Petr,            ┆ Darmata                        ┆ 52    ┆ 2013 │
│ Macura, Ondřej,          ┆ Sklo                           ┆ 92    ┆ 2013 │
│ Hanus, Ondřej,           ┆ Výjevy                         ┆ 56    ┆ 2013 │
│ Slíva, Vít,              ┆ Návrší                         ┆ 99    ┆ 2014 │
│ Malý, Radek,             ┆ Všehomír                       ┆ 60    ┆ 2015 │
│ Gabriel, Tomáš,          ┆ Obvyklé hrdinství              ┆ 96    ┆ 2016 │
│ Děžinský, Milan,         ┆ Obcházení ostrova              ┆ 51    ┆ 2017 │
│ Marks, Luděk,            ┆ Po hadí kůži                   ┆ 113   ┆ 2017 │
│ Hanus, Ondřej,           ┆ Volné verše                    ┆ 56    ┆ 2017 │
│ Slíva, Vít,              ┆ Ultima Thúlé, nejzazší zem     ┆ 83    ┆ 2018 │
│ Goldstein, Klára,        ┆ Kenotaf                        ┆ 63    ┆ 2018 │
│ Iljašenko, Marie,        ┆ Sv. Outdoor                    ┆ 56    ┆ 2019 │
│ Šťastná, Marie,          ┆ Štěstí jistě přijde            ┆ 71    ┆ 2019 │
│ Kaprál, Zeno,            ┆ Elegie naruby                  ┆ 63    ┆ 2019 │
│ Veselá-Jirousová, Marta, ┆ Zahrada                        ┆ 81    ┆ 2019 │
│ Zbořil, Jonáš,           ┆ Nová divočina                  ┆ 77    ┆ 2020 │
│ Stöhr, Martin Josef,     ┆ Užitá lyrika                   ┆ 61    ┆ 2020 │
│ Šustková, Tereza,        ┆ Tíha vlny                      ┆ 73    ┆ 2020 │
│ Goldstein, Klára,        ┆ Falkenfrau                     ┆ 69    ┆ 2021 │
└──────────────────────────┴────────────────────────────────┴───────┴──────┘

In [17]:
zjisti("Nebe, peklo")

Umělecké snahy

shape: (20, 6)
┌────────────────────┬─────────────────────────────┬───────────────────────┬──────┬───────┬────────────────────────────┐
│ 100_a              ┆ 245_a                       ┆ 260_b                 ┆ rok  ┆ stran ┆ 490_a                      │
│ ---                ┆ ---                         ┆ ---                   ┆ ---  ┆ ---   ┆ ---                        │
│ str                ┆ str                         ┆ str                   ┆ i64  ┆ i64   ┆ str                        │
╞════════════════════╪═════════════════════════════╪═══════════════════════╪══════╪═══════╪════════════════════════════╡
│ Mahen, Jiří,       ┆ Nebe, peklo, ráj ... (1917) ┆ B. Kočí               ┆ 1919 ┆ 103   ┆ Umělecké snahy             │
│ Mahen, Jiří,       ┆ Nebe, peklo, ráj ... 1917   ┆ B. Kočí               ┆ 1922 ┆ 103   ┆ Umělecké snahy             │
│ Biebl, Konstantin, ┆ Nebe, peklo, ráj            ┆ Erna Janská           ┆ 1930 ┆ 43    ┆ Editio princeps            │
│ Biebl, Konstantin, ┆ Nebe, peklo, ráj            ┆ Sfinx, Bohumil Janda  ┆ 1931 ┆ 54    ┆ Růžová zahrada             │
│ Biebl, Konstantin, ┆ Nebe, peklo, ráj            ┆ null                  ┆ 1931 ┆ 54    ┆ Růžová zahrada             │
│ Mahen, Jiří,       ┆ Nebe, peklo, ráj... (1917)  ┆ null                  ┆ 1950 ┆ 139   ┆ Československé divadelní a │
│                    ┆                             ┆                       ┆      ┆       ┆ lit…                       │
│ Kornelová, Marie,  ┆ Nebe, peklo, ráj            ┆ SNDK                  ┆ 1967 ┆ 204   ┆ null                       │
│ Cortázar, Julio,   ┆ Nebe, peklo, ráj            ┆ Odeon                 ┆ 1972 ┆ 580   ┆ Soudobá světová próza      │
│ Salivarová, Zdena, ┆ Nebe, peklo, ráj            ┆ Atlantis              ┆ 1991 ┆ 271   ┆ null                       │
│ Gurevič, Aron      ┆ Nebe, peklo, svět           ┆ H & H                 ┆ 1996 ┆ 524   ┆ null                       │
│ Jakovlevič,        ┆                             ┆                       ┆      ┆       ┆                            │
│ Skořepová, Luba,   ┆ Nebe, peklo, ráj            ┆ Knižní klub           ┆ 1999 ┆ 174   ┆ null                       │
│ Cortázar, Julio,   ┆ Nebe, peklo, ráj            ┆ Mladá fronta          ┆ 2001 ┆ 600   ┆ Román                      │
│ Salivarová, Zdena, ┆ Nebe, peklo, ráj            ┆ Academia              ┆ 2001 ┆ 267   ┆ Scarabeus                  │
│ Lipecká, Olga,     ┆ Dívky hrají Nebe, peklo,    ┆ Akcent                ┆ 2009 ┆ 182   ┆ null                       │
│                    ┆ ráj                         ┆                       ┆      ┆       ┆                            │
│ Janek, Dalibor,    ┆ Nebe, peklo, ráj závodníka  ┆ Computer Press        ┆ 2010 ┆ 152   ┆ null                       │
│                    ┆ a m…                        ┆                       ┆      ┆       ┆                            │
│ Francková, Zuzana, ┆ Nebe, peklo, ráj            ┆ Erika                 ┆ 2010 ┆ 125   ┆ null                       │
│ Kovářová, Daniela, ┆ Nebe, peklo, ráj            ┆ Agentura Lucie        ┆ 2011 ┆ 133   ┆ null                       │
│ Jindra, Miroslav,  ┆ Nebe, peklo, zem            ┆ Barrister & Principal ┆ 2013 ┆ 261   ┆ Paměť                      │
│ Cortázar, Julio,   ┆ Nebe, peklo, ráj            ┆ null                  ┆ 2019 ┆ 641   ┆ null                       │
│ Plyšák             ┆ Nebe, peklo, ráj            ┆ null                  ┆ 2022 ┆ 51    ┆ null                       │
└────────────────────┴─────────────────────────────┴───────────────────────┴──────┴───────┴────────────────────────────┘

In [18]:
edice('Román', nakladatelstvi="Mladá fronta")

shape: (41, 5)
┌────────────────────────┬─────────────────────────────────┬──────────┬──────┬───────┐
│ 100_a                  ┆ 245_a                           ┆ 300_a    ┆ rok  ┆ stran │
│ ---                    ┆ ---                             ┆ ---      ┆ ---  ┆ ---   │
│ str                    ┆ str                             ┆ str      ┆ i64  ┆ i64   │
╞════════════════════════╪═════════════════════════════════╪══════════╪══════╪═══════╡
│ Kohout, Pavel,         ┆ Hvězdná hodina vrahů            ┆ 422 s. ; ┆ 1995 ┆ 422   │
│ Kohout, Pavel,         ┆ Konec velkých prázdnin          ┆ 711 s. ; ┆ 1996 ┆ 711   │
│ Kohout, Pavel,         ┆ Šest & Sex                      ┆ 229 s. ; ┆ 1998 ┆ 229   │
│ Hoffmann, E. T. A.,    ┆ Ďáblův elixír                   ┆ 291 s. ; ┆ 2001 ┆ 291   │
│ Cortázar, Julio,       ┆ Nebe, peklo, ráj                ┆ 600 s. ; ┆ 2001 ┆ 600   │
│ Guillou, Jan,          ┆ Cesta do Svaté země             ┆ 356 s. : ┆ 2001 ┆ 356   │
│ Chaviano, Daína,       ┆ Havana blues                    ┆ 241 s. ; ┆ 2001 ┆ 241   │
│ Aust, Kurt,            ┆ Den hněvu                       ┆ 356 s. ; ┆ 2001 ┆ 356   │
│ Beckett, Samuel,       ┆ První láska                     ┆ 71 s. ;  ┆ 2001 ┆ 71    │
│ Roy, Arundhati,        ┆ Bůh maličkostí                  ┆ 331 s. ; ┆ 2001 ┆ 331   │
│ Dalmau, Antoni,        ┆ Země zapomnění                  ┆ 251 s. ; ┆ 2001 ┆ 251   │
│ Henriksen, Vera,       ┆ Stříbrné kladivo                ┆ 260 s. : ┆ 2001 ┆ 260   │
│ Cazotte, Jacques,      ┆ Zamilovaný ďábel                ┆ 237 s. ; ┆ 2001 ┆ 237   │
│ Roy, Arundhati,        ┆ Bůh maličkostí                  ┆ 331 s. ; ┆ 2001 ┆ 331   │
│ Ancion, Nicolas,       ┆ Čtvrté patro                    ┆ 125 s. ; ┆ 2002 ┆ 125   │
│ Rahimi, Atiq,          ┆ Země a popel                    ┆ 76 s. ;  ┆ 2002 ┆ 76    │
│ Tsiolkas, Christos,    ┆ Ari                             ┆ 212 s. ; ┆ 2002 ┆ 212   │
│ Antunes, António Lobo, ┆ Jidášova díra                   ┆ 215 s. ; ┆ 2002 ┆ 215   │
│ Montero, Mayra,        ┆ Jako tvůj posel                 ┆ 244 s. ; ┆ 2002 ┆ 244   │
│ Grenville, Kate,       ┆ Lilianin příběh                 ┆ 330 s. ; ┆ 2002 ┆ 330   │
│ Niemi, Mikael,         ┆ Popmusic z Vittuly              ┆ 258 s. ; ┆ 2003 ┆ 258   │
│ Asimov, Isaac,         ┆ Nadace a Říše                   ┆ 307 s. ; ┆ 2003 ┆ 307   │
│ Page, Martin,          ┆ Jak jsem se stal hlupákem       ┆ 131 s. ; ┆ 2003 ┆ 131   │
│ Vargas Llosa, Mario,   ┆ Vypravěč                        ┆ 183 s. ; ┆ 2003 ┆ 183   │
│ Tremain, Rose,         ┆ Valentina a já                  ┆ 377 s. ; ┆ 2003 ┆ 377   │
│ Cercas, Javier,        ┆ Vojáci od Salaminy              ┆ 226 s. ; ┆ 2004 ┆ 226   │
│ Vargas Llosa, Mario,   ┆ Tetička Julie a zneuznaný géni… ┆ 320 s. ; ┆ 2004 ┆ 320   │
│ Houellebecq, Michel,   ┆ Rozšíření bitevního pole        ┆ 154 s. ; ┆ 2004 ┆ 154   │
│ Gavalda, Anna,         ┆ A taková to byla láska--        ┆ 149 s. ; ┆ 2004 ┆ 149   │
│ Shields, Carol,        ┆ Ledaže                          ┆ 259 s. ; ┆ 2004 ┆ 259   │
│ Vargas Llosa, Mario,   ┆ Město a psi                     ┆ 332 s. ; ┆ 2004 ┆ 332   │
│ Nielsen, Hans-Jorgen,  ┆ Fotbalový anděl                 ┆ 203 s. ; ┆ 2004 ┆ 203   │
│ Kirchhoff, Bodo,       ┆ Krvák                           ┆ 270 s. ; ┆ 2004 ┆ 270   │
│ Faulkner, William,     ┆ Prapory v prachu                ┆ 383 s. ; ┆ 2004 ┆ 383   │
│ Bernig, Jörg,          ┆ Čas nikoho                      ┆ 225 s. ; ┆ 2004 ┆ 225   │
│ Atwood, Margaret,      ┆ Přežívá nejsmutnější            ┆ 316 s. ; ┆ 2005 ┆ 316   │
│ Vargas Llosa, Mario,   ┆ Zelený dům                      ┆ 372 s. ; ┆ 2005 ┆ 372   │
│ Asimov, Isaac,         ┆ Druhá Nadace                    ┆ 305 s. ; ┆ 2005 ┆ 305   │
│ Dai, Sijie,            ┆ Balzac a čínská Švadlenka       ┆ 131 s. ; ┆ 2005 ┆ 131   │
│ Mendes, Bob,           ┆ Chuť svobody                    ┆ 383 s. ; ┆ 2006 ┆ 383   │
│ Vargas Llosa, Mario,   ┆ Ráj je až za rohem              ┆ 362 s. ; ┆ 2007 ┆ 362   │
└────────────────────────┴─────────────────────────────────┴──────────┴──────┴───────┘

In [19]:
zjisti("Svobodná")

None

shape: (30, 6)
┌─────────────────────────┬─────────────────────────┬─────────────────────────┬──────┬───────┬─────────────────────────┐
│ 100_a                   ┆ 245_a                   ┆ 260_b                   ┆ rok  ┆ stran ┆ 490_a                   │
│ ---                     ┆ ---                     ┆ ---                     ┆ ---  ┆ ---   ┆ ---                     │
│ str                     ┆ str                     ┆ str                     ┆ i64  ┆ i64   ┆ str                     │
╞═════════════════════════╪═════════════════════════╪═════════════════════════╪══════╪═══════╪═════════════════════════╡
│ Sallač, Karel,          ┆ Svobodná dělitelnost    ┆ K. Sallač               ┆ 1887 ┆ 33    ┆ null                    │
│                         ┆ pozemků j…              ┆                         ┆      ┆       ┆                         │
│ Radić, Stjepan,         ┆ Svobodná škola          ┆ Samostatnost            ┆ 1899 ┆ 64    ┆ null                    │
│                         ┆ politických věd…        ┆                         ┆      ┆       ┆                         │
│ Doubrava, Josef,        ┆ Pastýřský list nejdp.   ┆ nákl. vl.               ┆ 1906 ┆ 24    ┆ Časové úvahy            │
│                         ┆ biskupa …               ┆                         ┆      ┆       ┆                         │
│ Černý, Josef,           ┆ Svobodná, volná škola a ┆ null                    ┆ 1907 ┆ 187   ┆ null                    │
│                         ┆ její v…                 ┆                         ┆      ┆       ┆                         │
│ Obuchov, Aleksandr      ┆ Svobodná výchova a      ┆ s.n.                    ┆ 1910 ┆ 17    ┆ Sedmá výr. zpr. dívč.   │
│ Michajlovič…            ┆ disciplina              ┆                         ┆      ┆       ┆ lycea sp…               │
│ Mach, Jarka,            ┆ Svobodná                ┆ K.J. Barvitius          ┆ 1934 ┆ 2     ┆ Barvitiova edice        │
│ Mach, Jarka,            ┆ Svobodná                ┆ K.J. Barvitius          ┆ 1934 ┆ 2     ┆ Popěvky                 │
│ Lamp, Rudolf,           ┆ Svobodná                ┆ Státní hudební          ┆ 1963 ┆ 17    ┆ Zábavní orchestr        │
│                         ┆                         ┆ vydavatelství           ┆      ┆       ┆                         │
│ Lamp, Rudolf,           ┆ Svobodná                ┆ Státní hudební          ┆ 1963 ┆ 17    ┆ Salon-orchester         │
│                         ┆                         ┆ vydavatelství           ┆      ┆       ┆                         │
│ García Lorca, Federico, ┆ Svobodná paní Rosita,   ┆ Dilia                   ┆ 1979 ┆ 56    ┆ null                    │
│                         ┆ aneb, Kv…               ┆                         ┆      ┆       ┆                         │
│ Sedláček, Karel,        ┆ Volá Svobodná Evropa    ┆ Archa 90                ┆ 1993 ┆ 164   ┆ null                    │
│ Janovský-Drážďanský,    ┆ Svobodná Evropa         ┆ Papyrus                 ┆ 1995 ┆ 222   ┆ null                    │
│ Karel,                  ┆                         ┆                         ┆      ┆       ┆                         │
│ Marie-Françoise         ┆ Svobodná matka          ┆ Ivo Železný             ┆ 1995 ┆ 60    ┆ Knihovnička Večerů pod  │
│                         ┆                         ┆                         ┆      ┆       ┆ lampou.…                │
│ Joch, Roman,            ┆ Svobodná společnost,    ┆ Občanský institut       ┆ 1997 ┆ 23    ┆ Bulletin OI             │
│                         ┆ individuá…              ┆                         ┆      ┆       ┆                         │
│ McCaffrey, Anne,        ┆ Svobodná volba          ┆ Netopejr                ┆ 1999 ┆ 319   ┆ null                    │
│ Lejsková, Věra,         ┆ Moje Brno v pořadech    ┆ Šimon Ryšavý            ┆ 2003 ┆ 108   ┆ null                    │
│                         ┆ Radia Svo…              ┆                         ┆      ┆       ┆                         │
│ Klausnerová, Eva,       ┆ Svobodná Plzeň hovoří   ┆ Nava                    ┆ 2005 ┆ 111   ┆ null                    │
│ Prášil, Petr,           ┆ Svobodná Ves            ┆ Petr Prášil             ┆ 2005 ┆ 1     ┆ null                    │
│ Velikovská, Kamila      ┆ Svobodná, i když za     ┆ Jota                    ┆ 2006 ┆ 279   ┆ null                    │
│                         ┆ mrížemi i.…             ┆                         ┆      ┆       ┆                         │
│ Bystrov, Vladimír,      ┆ Svobodná nesvoboda      ┆ Vyšší odborná škola     ┆ 2006 ┆ 131   ┆ Studie                  │
│                         ┆                         ┆ publicisti…             ┆      ┆       ┆                         │
│ Brázda, Petr            ┆ Svobodná spolková       ┆ Petr Brázda             ┆ 2007 ┆ 1     ┆ null                    │
│                         ┆ republika Kr…           ┆                         ┆      ┆       ┆                         │
│ McCulley, Carolyn,      ┆ Svobodná a v pohodě     ┆ Samuel, Biblická práce  ┆ 2009 ┆ 205   ┆ null                    │
│                         ┆                         ┆ pro dět…                ┆      ┆       ┆                         │
│ Gazzaniga, Michael S.,  ┆ Kdo to tady řídí?,      ┆ Dybbuk                  ┆ 2013 ┆ 236   ┆ null                    │
│                         ┆ aneb, Svobo…            ┆                         ┆      ┆       ┆                         │
│ Harris, Sam,            ┆ Svobodná vůle           ┆ null                    ┆ 2015 ┆ 83    ┆ null                    │
│ Sternlicht, Hana,       ┆ Svobodná, volná         ┆ null                    ┆ 2018 ┆ 145   ┆ null                    │
│ Rakušanová, Lída,       ┆ Svobodná v Evropě       ┆ null                    ┆ 2020 ┆ 287   ┆ null                    │
│ Danišová, Justina       ┆ Svobodná hra            ┆ null                    ┆ 2020 ┆ 307   ┆ null                    │
│ Rakušanová, Lída,       ┆ Svobodná v Evropě       ┆ null                    ┆ 2021 ┆ 8     ┆ null                    │
│ Ypi, Lea,               ┆ Svobodná                ┆ null                    ┆ 2023 ┆ 309   ┆ null                    │
│ Grace, Annie,           ┆ Svobodná mysl           ┆ null                    ┆ 2024 ┆ 285   ┆ null                    │
└─────────────────────────┴─────────────────────────┴─────────────────────────┴──────┴───────┴─────────────────────────┘

In [20]:
zjisti("Pánův hlas")

Omnia

shape: (1, 6)
┌─────────────────┬────────────┬─────────┬──────┬───────┬───────┐
│ 100_a           ┆ 245_a      ┆ 260_b   ┆ rok  ┆ stran ┆ 490_a │
│ ---             ┆ ---        ┆ ---     ┆ ---  ┆ ---   ┆ ---   │
│ str             ┆ str        ┆ str     ┆ i64  ┆ i64   ┆ str   │
╞═════════════════╪════════════╪═════════╪══════╪═══════╪═══════╡
│ Lem, Stanisław, ┆ Pánův hlas ┆ Svoboda ┆ 1981 ┆ 729   ┆ Omnia │
└─────────────────┴────────────┴─────────┴──────┴───────┴───────┘

In [21]:
edice("Omnia", nakladatelstvi="Svoboda")

shape: (275, 5)
┌─────────────────────────────────┬─────────────────────────────────┬───────────────────────┬──────┬───────┐
│ 100_a                           ┆ 245_a                           ┆ 300_a                 ┆ rok  ┆ stran │
│ ---                             ┆ ---                             ┆ ---                   ┆ ---  ┆ ---   │
│ str                             ┆ str                             ┆ str                   ┆ i64  ┆ i64   │
╞═════════════════════════════════╪═════════════════════════════════╪═══════════════════════╪══════╪═══════╡
│ Larni, Martti,                  ┆ Ve znamení Panny                ┆ 206, [4] s. ;         ┆ 1968 ┆ 206   │
│ Cronin, A. J.                   ┆ Citadela                        ┆ 446 s. ;              ┆ 1969 ┆ 446   │
│ Březovský, Bohuslav,            ┆ Vzdušné zámky                   ┆ 418, [5] s. ;         ┆ 1969 ┆ 418   │
│ Comfort, Will Levington,        ┆ Zvířata a lidé v džungli        ┆ 200, [3] s. ;         ┆ 1969 ┆ 200   │
│ Dumas, Alexandre,               ┆ Josef Balsamo                   ┆ 2 sv. (682; 699 s.) : ┆ 1969 ┆ 699   │
│ Wurmser, André,                 ┆ Vrah zemřel první...            ┆ 135, [1] s. ;         ┆ 1969 ┆ 135   │
│ Šmahelová, Helena,              ┆ Devět tisíc dnů                 ┆ 220, [2] s. ;         ┆ 1969 ┆ 220   │
│ Steinbeck, John,                ┆ Nebeské pastviny                ┆ 191 s. ;              ┆ 1969 ┆ 191   │
│ Mináč, Vladimír,                ┆ Nikdy nejsi sama                ┆ 256 s. ;              ┆ 1969 ┆ 256   │
│ Ossowski, Leonie,               ┆ Nebe - peklo - ráj, kam tě, du… ┆ 251 s. ;              ┆ 1969 ┆ 251   │
│ Jánský, Filip,                  ┆ Nebeští jezdci                  ┆ 217, [2] s. ;         ┆ 1969 ┆ 217   │
│ London, Jack,                   ┆ Odyssea severu                  ┆ 357, [3] s. ;         ┆ 1969 ┆ 357   │
│ Dostojevskij, Fedor Michajlovi… ┆ Strýčkův sen                    ┆ 366, [4] s. ;         ┆ 1969 ┆ 366   │
│ Jirásek, Alois,                 ┆ Filosofská historie             ┆ 256 s. ;              ┆ 1969 ┆ 256   │
│ Chabrol, Jean-Pierre,           ┆ Budu tě milovat bez ostychu     ┆ 196 s. ;              ┆ 1970 ┆ 196   │
│ Dumas, Alexandre,               ┆ Královnin náhrdelník            ┆ 2 sv. (431; 410 s.) ; ┆ 1970 ┆ 431   │
│ Burke, John Frederick           ┆ Předměstí libosti               ┆ 342 s. ;              ┆ 1970 ┆ 342   │
│ Michna, Vladimír,               ┆ Dáma a čarostřelec              ┆ 191 s. ;              ┆ 1970 ┆ 191   │
│ Hončík, Eduard,                 ┆ Jízdenka do Kanady              ┆ 268 s. ;              ┆ 1970 ┆ 268   │
│ Kožík, František,               ┆ Třikrát se ohlédni              ┆ 181, [3] s. ;         ┆ 1970 ┆ 181   │
│ Skočdopole, Bedřich,            ┆ Zatykač na Královnu             ┆ 167 s. ;              ┆ 1970 ┆ 167   │
│ Kříž, Ivan,                     ┆ Velká samota                    ┆ 358 s. ;              ┆ 1970 ┆ 358   │
│ Neff, Vladimír,                 ┆ Lidé v tógách                   ┆ 179 s. ;              ┆ 1970 ┆ 179   │
│ Nauman, Pavel,                  ┆ Faon                            ┆ 253 s. ;              ┆ 1970 ┆ 253   │
│ Ječný, Dobromil,                ┆ Brevíř moderního člověka        ┆ 172 s. ;              ┆ 1970 ┆ 172   │
│ Bradbury, Ray,                  ┆ 451 stupňů Fahrenheita          ┆ 155 s. ;              ┆ 1970 ┆ 155   │
│ Loukotková, Jarmila,            ┆ Bůh či ďábel                    ┆ 342, [2] s. ;         ┆ 1970 ┆ 342   │
│ Féval, Paul,                    ┆ Hrbáč                           ┆ 542 s. ;              ┆ 1970 ┆ 542   │
│ Dimitrova, Blaga,               ┆ Objížďka                        ┆ 237, [2] s. ;         ┆ 1971 ┆ 237   │
│ Cusack, Dymphna,                ┆ Černý blesk                     ┆ 223, [1] s. ;         ┆ 1971 ┆ 223   │
│ Hejcman, Pavel,                 ┆ Doňa Teresa                     ┆ 195 s. ;              ┆ 1971 ┆ 195   │
│ Dumas, Alexandre,               ┆ Pád Bastily                     ┆ 2 sv. (315, 310 s.) : ┆ 1971 ┆ 315   │
│ Sanson, Charles Henri,          ┆ Tajnosti popraviště             ┆ 416 s. ;              ┆ 1971 ┆ 416   │
│ Kratochvíl, Miloš Václav,       ┆ Matyášův meč                    ┆ 299, [2] s. ;         ┆ 1971 ┆ 299   │
│ Wallace, Edgar,                 ┆ Když gangsteři ovládli Londýn   ┆ 219, [2] s. ;         ┆ 1971 ┆ 219   │
│ Olbracht, Ivan,                 ┆ Dobyvatel                       ┆ 573 s. ;              ┆ 1971 ┆ 573   │
│ Kožík, František,               ┆ Hejtman Šarovec                 ┆ 255, [3] s. ;         ┆ 1971 ┆ 255   │
│ Clarke, Arthur C.               ┆ 2001: Vesmírná odysea           ┆ 204, [3] s. ;         ┆ 1971 ┆ 204   │
│ Figuli, Margita,                ┆ Babylón                         ┆ 408 s. ;              ┆ 1971 ┆ 408   │
│ Figuli, Margita,                ┆ Babylón                         ┆ 406 s. ;              ┆ 1971 ┆ 406   │
│ Cooper, James Fenimore,         ┆ Rudý pirát                      ┆ 224, [2] s. :         ┆ 1972 ┆ 224   │
│ Forš, Ol'ga Dmitrijevna,        ┆ Carevna a rebel                 ┆ 438 s. ;              ┆ 1972 ┆ 438   │
│ Korol'kov, Jurij Michajlovič,   ┆ Tajemný dr. Sorge               ┆ 220, [2] s. ;         ┆ 1972 ┆ 220   │
│ Steinberg, Werner,              ┆ Komisařův klobouk               ┆ 244 s. ;              ┆ 1972 ┆ 244   │
│ Tendrjakov, Vladimir Fedorovič… ┆ Cesta na jedno století          ┆ 237 s. ;              ┆ 1972 ┆ 237   │
│ Twain, Mark,                    ┆ Panna ve zbroji                 ┆ 233, [2] s. ;         ┆ 1972 ┆ 233   │
│ London, Jack,                   ┆ Démon alkohol                   ┆ 189, [2] s. ;         ┆ 1972 ┆ 189   │
│ Kin, Viktor Pavlovič,           ┆ Byli jsme dva                   ┆ 181, [1] s. ;         ┆ 1972 ┆ 181   │
│ Lesage, Alain-René,             ┆ Kulhavý ďábel                   ┆ 236, [3] s. ;         ┆ 1972 ┆ 236   │
│ Diderot, Denis,                 ┆ Jakub fatalista a jeho pán      ┆ 252 s. ;              ┆ 1972 ┆ 252   │
│ Toman, Josef,                   ┆ Kde lišky dávají dobrou noc     ┆ 296, [2] s. ;         ┆ 1972 ┆ 296   │
│ Harte, Bret,                    ┆ Clarence Brant                  ┆ 335 s. ;              ┆ 1972 ┆ 335   │
│ Dumas, Alexandre,               ┆ Hraběnka de Charny              ┆ 2 sv. (473, 508 s.) ; ┆ 1972 ┆ 508   │
│ Féval, Paul,                    ┆ Tajnosti Londýna                ┆ 2 sv. (323; 331 s.) ; ┆ 1972 ┆ 331   │
│ Dumas, Alexandre,               ┆ Rytíř de Maison-Rouge           ┆ 2 sv. (492, 388 s.) ; ┆ 1973 ┆ 492   │
│ Dumas, Alexandre,               ┆ Robin Hood                      ┆ 236 s. ;              ┆ 1973 ┆ 236   │
│ Lučaninov, Daniil               ┆ Osud generála                   ┆ 380, [4] s. ;         ┆ 1973 ┆ 380   │
│ Liv, Egon                       ┆ Kašparova dvojčata              ┆ 135, [1] s. ;         ┆ 1973 ┆ 135   │
│ Scholefield, Alan,              ┆ Uťatá ruka                      ┆ 254 s. ;              ┆ 1973 ┆ 254   │
│ Jókai, Mór,                     ┆ Dvojí život                     ┆ 493, [5] s. ;         ┆ 1973 ┆ 493   │
│ Radó, Sándor,                   ┆ Volá Dora ...                   ┆ 490, [4] s. ;         ┆ 1973 ┆ 490   │
│ Strugackij, Arkadij Natanovič,  ┆ Je těžké být bohem              ┆ 188, [2] s. ;         ┆ 1973 ┆ 188   │
│ Simenon, Georges,               ┆ Muž, který pozoroval noční vla… ┆ 190 s. ;              ┆ 1973 ┆ 190   │
│ Šmahelová, Helena,              ┆ Bratr a sestra                  ┆ 176, [2] s. ;         ┆ 1973 ┆ 176   │
│ Wallace, Edgar,                 ┆ Postrach Chicaga                ┆ 190, [1] s. ;         ┆ 1973 ┆ 190   │
│ Zapolska, Gabriela,             ┆ Sezónní láska                   ┆ 413, [2] s. ;         ┆ 1973 ┆ 413   │
│ Vaupšasau, Stanislau A.         ┆ Smrt mi šla v patách            ┆ 329, [2] s. ;         ┆ 1973 ┆ 329   │
│ Slocum, Joshua,                 ┆ Sám na lodi kolem světa         ┆ 339, [8] s. ;         ┆ 1973 ┆ 339   │
│ Stevenson, Robert Louis,        ┆ Dobrodružství Davida Balfoura   ┆ 388 s. ;              ┆ 1973 ┆ 388   │
│ Loukotková, Jarmila,            ┆ Medúza                          ┆ 393, [7] s. ;         ┆ 1973 ┆ 393   │
│ Stanev, Emilijan,               ┆ Stopy v lese                    ┆ 196, [3] s. ;         ┆ 1973 ┆ 196   │
│ Karpjuk, Aljaksej Nìčyparavìč,  ┆ Danuta                          ┆ 381, [2] s. ;         ┆ 1974 ┆ 381   │
│ Bergius, C. C.,                 ┆ Havárie                         ┆ 163, [2] s. ;         ┆ 1974 ┆ 163   │
│ Corsari, Willy,                 ┆ Neviditelný nepřítel            ┆ 314, [2] s. ;         ┆ 1974 ┆ 314   │
│ Davydov, Zinovij Samojlovič,    ┆ Nezvaný host                    ┆ 436, [5] s. ;         ┆ 1974 ┆ 436   │
│ Freed, Donald,                  ┆ Atentát na presidenta           ┆ 238, [1] s. ;         ┆ 1974 ┆ 238   │
│ Kraszewski, Józef Ignacy,       ┆ Hraběnka Coselová               ┆ 357, [ii s. ;         ┆ 1974 ┆ 357   │
│ Kratochvíl, Miloš Václav,       ┆ Osamělý rváč                    ┆ 333, [3] s. ;         ┆ 1974 ┆ 333   │
│ Korol'kov, Jurij Michajlovič,   ┆ Případ Alta                     ┆ 238, [2] s. ;         ┆ 1974 ┆ 238   │
│ Remarque, Erich Maria,          ┆ Nebe nezná vyvolených           ┆ 254, [2] s. ;         ┆ 1974 ┆ 254   │
│ Laurent, Jacques,               ┆ Oheň a láska                    ┆ 454 s. ;              ┆ 1974 ┆ 454   │
│ Šmahelová, Helena,              ┆ Dědicové snů                    ┆ 413, [2] s. ;         ┆ 1974 ┆ 413   │
│ Stendhal,                       ┆ Červený a černý                 ┆ 516 s. ;              ┆ 1974 ┆ 516   │
│ Zola, Émile,                    ┆ Štěstí Rougonů                  ┆ 333 s. ;              ┆ 1974 ┆ 333   │
│ Wahlöö, Per,                    ┆ Vražda v jedenatřicátém poscho… ┆ 299 s. ;              ┆ 1974 ┆ 299   │
│ Jirásek, Alois,                 ┆ Skaláci                         ┆ 233, [5] s. ;         ┆ 1974 ┆ 233   │
│ Gerstäcker, Friedrich,          ┆ Zlaté pruty                     ┆ 207 s. ;              ┆ 1974 ┆ 207   │
│ Zapolska, Gabriela,             ┆ Bílý hyacint                    ┆ 330, [2] s. ;         ┆ 1974 ┆ 330   │
│ Osterloff, W. Konrad,           ┆ Rod Pizarrů                     ┆ 227 s. ;              ┆ 1974 ┆ 227   │
│ Bonhoff, Otto,                  ┆ Na příkaz admirála Canarise     ┆ 347, [ii] s. ;        ┆ 1975 ┆ 347   │
│ Karaslavov, Georgi,             ┆ Snacha                          ┆ 200, [2] s. ;         ┆ 1975 ┆ 200   │
│ Borovička, V. P.                ┆ Atentáty, které měly změnit sv… ┆ 393 s. ;              ┆ 1975 ┆ 393   │
│ Cooper, James Fenimore,         ┆ Vyzvědač                        ┆ 303, [1] s. ;         ┆ 1975 ┆ 303   │
│ Nemes, László,                  ┆ Zmrazená láska                  ┆ 198 s. ;              ┆ 1975 ┆ 198   │
│ Franc, Gustav,                  ┆ Bariéra ticha                   ┆ 222, [2] s. ;         ┆ 1975 ┆ 222   │
│ Hériat, Philippe,               ┆ Boussardelovi                   ┆ 558 s. ;              ┆ 1975 ┆ 558   │
│ Prichard, Katharine Susannah,   ┆ Sharn, má naděje a láska        ┆ 371, [2] s. ;         ┆ 1975 ┆ 371   │
│ Christie, Agatha,               ┆ Pozvánka pro Hercula Poirota    ┆ 206 s. ;              ┆ 1975 ┆ 206   │
│ Wernic, Wiesław,                ┆ Slunce Arizony                  ┆ 262, [7] s. ;         ┆ 1975 ┆ 262   │
│ Remarque, Erich Maria,          ┆ Na západní frontě klid          ┆ 189 s. ;              ┆ 1975 ┆ 189   │
│ Simenon, Georges,               ┆ Evertonský hodinář              ┆ 270 s. ;              ┆ 1975 ┆ 270   │
│ Šmahelová, Helena,              ┆ Muž a žena                      ┆ 403, [2] s. ;         ┆ 1975 ┆ 403   │
│ Steinberg, Werner,              ┆ Ikebana                         ┆ 222, [2] s. ;         ┆ 1975 ┆ 222   │
│ Scholefield, Alan,              ┆ Veliký slon                     ┆ 250 s. ;              ┆ 1975 ┆ 250   │
│ Chase, James Hadley,            ┆ Pracka v láhvi                  ┆ 220 s. ;              ┆ 1975 ┆ 220   │
│ Fraineau, Gerard,               ┆ Sbohem moře, sbohem oceány!     ┆ 262 s. ;              ┆ 1975 ┆ 262   │
│ Kirst, Hans Hellmut,            ┆ Vaše věc, pane komisaři         ┆ 306, [2] s. ;         ┆ 1976 ┆ 306   │
│ Balzac, Honoré de,              ┆ Lilie v údolí                   ┆ 291, [2] s. ;         ┆ 1976 ┆ 291   │
│ Cronin, A. J.                   ┆ Velká neznámá                   ┆ 275, [2] s. ;         ┆ 1976 ┆ 275   │
│ Dumas, Alexandre,               ┆ Královna Margot                 ┆ 549 s. ;              ┆ 1976 ┆ 549   │
│ Maugham, W. Somerset            ┆ Odsouzen k útěku                ┆ 217 s. ;              ┆ 1976 ┆ 217   │
│ Bels, Alberts,                  ┆ Klec                            ┆ 139, [2] s. ;         ┆ 1976 ┆ 139   │
│ Held, Wolfgang,                 ┆ Světlo Černé svíčky             ┆ 199 s. ;              ┆ 1976 ┆ 199   │
│ Hériat, Philippe,               ┆ Nezvedené děti                  ┆ 310 s. ;              ┆ 1976 ┆ 310   │
│ Ferber, Edna,                   ┆ Život pro tebe                  ┆ 260 s. ;              ┆ 1976 ┆ 260   │
│ Pratolini, Vasco,               ┆ Děvčata ze Sanfrediana          ┆ 119 s. ;              ┆ 1976 ┆ 119   │
│ Tarchetti, Igino Ugo,           ┆ Fosca                           ┆ 165 s. ;              ┆ 1976 ┆ 165   │
│ Simenon, Georges,               ┆ Donadieuova závěť               ┆ 330 s. ;              ┆ 1976 ┆ 330   │
│ Korolenko, Vladimir Galaktiono… ┆ Nezkrotná řeka                  ┆ 288 s. ;              ┆ 1976 ┆ 288   │
│ Bykaŭ, Vasìl‘,                  ┆ Žít do svítání                  ┆ 235, [3] s. ;         ┆ 1976 ┆ 235   │
│ Bodelsen, Anders,               ┆ Obyčejná nehoda                 ┆ 238, [1] s. ;         ┆ 1977 ┆ 238   │
│ Durrell, Gerald Malcolm,        ┆ Šeptající země                  ┆ 189 s. ;              ┆ 1977 ┆ 189   │
│ Baroja, Pío,                    ┆ Sedm záhad                      ┆ 285, [5] s. ;         ┆ 1977 ┆ 285   │
│ Le Roy, Eugène,                 ┆ Konec zámku Herm                ┆ 237, [2] s. ;         ┆ 1977 ┆ 237   │
│ Becher, Ulrich,                 ┆ Williamovo Ex-Casino            ┆ 225 s. ;              ┆ 1977 ┆ 225   │
│ Brixy, Nenad,                   ┆ Soutěž za milión                ┆ 191, [1] s. ;         ┆ 1977 ┆ 191   │
│ Schreiter, Helfried,            ┆ Žena u okna                     ┆ 163 s. ;              ┆ 1977 ┆ 163   │
│ Lenz, Jürgen                    ┆ Bez pasu do Ria                 ┆ 225, [2] s. ;         ┆ 1977 ┆ 225   │
│ Gor, Gennadij Samojlovič,       ┆ Geometrický les                 ┆ 168 s. ;              ┆ 1977 ┆ 168   │
│ Forš, Ol'ga Dmitrijevna,        ┆ Michajlovský palác              ┆ 216 s. ;              ┆ 1977 ┆ 216   │
│ Bonhoff, Otto,                  ┆ Neviditelné hledí               ┆ 250, [2] s. ;         ┆ 1978 ┆ 250   │
│ Blok, Georgij Petrovič,         ┆ Legenda o slavném městě         ┆ 325, [3] s. ;         ┆ 1978 ┆ 325   │
│ Bagley, Desmond,                ┆ Sněžný tygr                     ┆ 296, [3] s. ;         ┆ 1978 ┆ 296   │
│ Erpenbeck, Fritz,               ┆ Mrtvý na trůně                  ┆ 195, [2] s. ;         ┆ 1978 ┆ 195   │
│ Hériat, Philippe,               ┆ Zlaté mříže                     ┆ 295 s. ;              ┆ 1978 ┆ 295   │
│ Brixy, Nenad,                   ┆ Slyší to celý dům               ┆ 242, [2] s. ;         ┆ 1978 ┆ 242   │
│ Radó, Sándor,                   ┆ Volá Dora                       ┆ 489, [4] s. ;         ┆ 1978 ┆ 489   │
│ Traven, B.,                     ┆ Kareta                          ┆ 237, [1] s. ;         ┆ 1978 ┆ 237   │
│ Perrault, E. G.                 ┆ Exploze                         ┆ 267 s. ;              ┆ 1978 ┆ 267   │
│ Tammsaare, A. H.,               ┆ Dva rody z Vargamäe             ┆ 507, [2] s. ;         ┆ 1978 ┆ 507   │
│ Simenon, Georges,               ┆ Augustinova smrt                ┆ 245 s. ;              ┆ 1978 ┆ 245   │
│ Sjöwall, Maj,                   ┆ Säffleská bestie                ┆ 182 s. ;              ┆ 1978 ┆ 182   │
│ Walldorf, Hans,                 ┆ Červená slonovina               ┆ 183, [1] s. ;         ┆ 1978 ┆ 183   │
│ Passuth, László,                ┆ Lombardský zámek                ┆ 316 s. ;              ┆ 1978 ┆ 316   │
│ Kožík, František,               ┆ Město šťastných lásek           ┆ 292, [2] s. ;         ┆ 1978 ┆ 292   │
│ Bonhoff, Otto,                  ┆ Tajemství masek                 ┆ 213, [2] s. ;         ┆ 1979 ┆ 213   │
│ Dragt, Tonke,                   ┆ Planoucí lesy Venuše            ┆ 277 s. ;              ┆ 1979 ┆ 277   │
│ Bergius, C. C.,                 ┆ Čingischán                      ┆ 478 s. ;              ┆ 1979 ┆ 478   │
│ Hunter, Evan,                   ┆ Džungle před tabulí             ┆ 358 s. ;              ┆ 1979 ┆ 358   │
│ Basargin, Ivan Ul'janovič,      ┆ Mezi tygry                      ┆ 411, [3] s. ;         ┆ 1979 ┆ 411   │
│ Hériat, Philippe,               ┆ Čas na lásku                    ┆ 252 s. ;              ┆ 1979 ┆ 252   │
│ Roy, Gabrielle,                 ┆ Štěstí z výprodeje              ┆ 325 s. ;              ┆ 1979 ┆ 325   │
│ Wahlöö, Per,                    ┆ Pověření k sebevraždě           ┆ 213 s. ;              ┆ 1979 ┆ 213   │
│ Zejthuncjan, Perč,              ┆ Legenda dvacátého století       ┆ 183, [2] s. ;         ┆ 1979 ┆ 183   │
│ Simenon, Georges,               ┆ Vlak                            ┆ 238 s. ;              ┆ 1979 ┆ 238   │
│ Russo, Enzo,                    ┆ Případ Monte Cristo             ┆ 318 s. ;              ┆ 1980 ┆ 318   │
│ Balašov, Dmitrij Michajlovič,   ┆ Jeho Veličenstvo Novgorod       ┆ 186, [2] s. ;         ┆ 1980 ┆ 186   │
│ Clifford, Francis,              ┆ Čas je zrádná past              ┆ 190, [2] s. ;         ┆ 1980 ┆ 190   │
│ Grandmaison, Henri de,          ┆ Polykač papíru                  ┆ 206 s. ;              ┆ 1980 ┆ 206   │
│ Frelau, Axel                    ┆ Zorro se vrací                  ┆ 267 s. ;              ┆ 1980 ┆ 267   │
│ Funk, Richard,                  ┆ Soudní řízení na Epsí           ┆ 242 s. ;              ┆ 1980 ┆ 242   │
│ Kolozsvári Grandpierre, Emil,   ┆ Ženy v drobném                  ┆ 167, [1] s. ;         ┆ 1980 ┆ 167   │
│ Wogatzki, Benito,               ┆ Romance s Amélií                ┆ 222, [2] s. ;         ┆ 1980 ┆ 222   │
│ Scortia, Thomas N.,             ┆ Skleněné peklo                  ┆ 389, [2] s. ;         ┆ 1980 ┆ 389   │
│ Stahuljak, Višnja,              ┆ Veronika a delfín               ┆ 229, [2] s. ;         ┆ 1980 ┆ 229   │
│ Gulia, Georgij Dmitrijevič,     ┆ V krčmě světa                   ┆ 253 s. ;              ┆ 1980 ┆ 253   │
│ Walser, Martin,                 ┆ Prchající kůň                   ┆ 173 s. ;              ┆ 1981 ┆ 173   │
│ Choromański, Michał,            ┆ Žárlivost a medicína            ┆ 217 s. ;              ┆ 1981 ┆ 217   │
│ Hammett, Dashiell,              ┆ Skleněný klíč                   ┆ 206 s. ;              ┆ 1981 ┆ 206   │
│ Panduro, Leif,                  ┆ Packalové                       ┆ 222 s.                ┆ 1981 ┆ 222   │
│ Görlich, Günter,                ┆ Oznámení v novinách             ┆ 190 s. ;              ┆ 1981 ┆ 190   │
│ Patterson, James,               ┆ Vrcholné číslo Thomase Berryma… ┆ 214 s. ;              ┆ 1981 ┆ 214   │
│ Lem, Stanisław,                 ┆ Pánův hlas                      ┆ 729 s. ;              ┆ 1981 ┆ 729   │
│ Lengyel, Péter,                 ┆ Druhá planeta Oggu              ┆ 209, [2] s. ;         ┆ 1981 ┆ 209   │
│ Wicker, Tom                     ┆ V aréně se lvy                  ┆ 619, [3] s. ;         ┆ 1981 ┆ 619   │
│ Artom, Guido,                   ┆ Zmizelí Soudcové                ┆ 203, [2] s. ;         ┆ 1981 ┆ 203   │
│ Bels, Alberts,                  ┆ Hlas volajícího                 ┆ 202 s. ;              ┆ 1981 ┆ 202   │
│ Odebrant, Per,                  ┆ Mamlasové a mizerové            ┆ 213 s. ;              ┆ 1982 ┆ 213   │

In [22]:
zjisti("Ragtime")

None

shape: (10, 6)
┌──────────────────┬────────────────────────┬─────────────────┬──────┬───────┬─────────────────────────────────┐
│ 100_a            ┆ 245_a                  ┆ 260_b           ┆ rok  ┆ stran ┆ 490_a                           │
│ ---              ┆ ---                    ┆ ---             ┆ ---  ┆ ---   ┆ ---                             │
│ str              ┆ str                    ┆ str             ┆ i64  ┆ i64   ┆ str                             │
╞══════════════════╪════════════════════════╪═════════════════╪══════╪═══════╪═════════════════════════════════╡
│ Ghali, Adib      ┆ Ragtime guitar         ┆ Levné knihy KMa ┆ null ┆ 45    ┆ null                            │
│ Watson, Fr. Th.  ┆ The Ragtime Girl       ┆ null            ┆ 1914 ┆ 4     ┆ null                            │
│ Mládek, Ivan,    ┆ Ragtime-coctail        ┆ Panton          ┆ 1981 ┆ 13    ┆ null                            │
│ Doctorow, E. L., ┆ Ragtime                ┆ Odeon           ┆ 1982 ┆ 251   ┆ Soudobá světová próza           │
│ Doctorow, E. L., ┆ Ragtime                ┆ Odeon           ┆ 1985 ┆ 251   ┆ null                            │
│ Mládek, Ivan,    ┆ Ragtime-coctail        ┆ Panton          ┆ 1985 ┆ 13    ┆ null                            │
│ Joplin, Scott,   ┆ Original rags. Ragtime ┆ Panton          ┆ 1988 ┆ 5     ┆ Chvilka s kytarou               │
│ Doctorow, E. L., ┆ Ragtime                ┆ Odeon           ┆ 1989 ┆ 241   ┆ null                            │
│ Doctorow, E. L., ┆ Ragtime                ┆ Levné knihy KMa ┆ 2000 ┆ 259   ┆ Edice světových autorů          │
│ Doctorow, E. L., ┆ Ragtime                ┆ Euromedia Group ┆ 2005 ┆ 222   ┆ Světová literatura Lidových no… │
└──────────────────┴────────────────────────┴─────────────────┴──────┴───────┴─────────────────────────────────┘

In [23]:
edice("Světová literatura Lidových n")

shape: (61, 4)
┌─────────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                           ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                             ┆ ---                             ┆ ---   ┆ ---  │
│ str                             ┆ str                             ┆ i64   ┆ i64  │
╞═════════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Hrabal, Bohumil,                ┆ Perlička na dně                 ┆ 188   ┆ 2005 │
│ García Márquez, Gabriel,        ┆ Sto roků samoty                 ┆ 318   ┆ 2005 │
│ Remarque, Erich Maria,          ┆ Na západní frontě klid          ┆ 175   ┆ 2005 │
│ Irving, John,                   ┆ Svět podle Garpa                ┆ 515   ┆ 2005 │
│ Škvorecký, Josef,               ┆ Zbabělci                        ┆ 379   ┆ 2005 │
│ McEwan, Ian,                    ┆ Betonová zahrada                ┆ 127   ┆ 2005 │
│ Capote, Truman,                 ┆ Snídaně u Tiffanyho             ┆ 92    ┆ 2005 │
│ Bulgakov, Michail Afanas‘jevič… ┆ Mistr a Markétka                ┆ 396   ┆ 2005 │
│ Kafka, Franz,                   ┆ Proces                          ┆ 203   ┆ 2005 │
│ Doctorow, E. L.,                ┆ Ragtime                         ┆ 222   ┆ 2005 │
│ Merle, Robert,                  ┆ Smrt je mým řemeslem            ┆ 299   ┆ 2005 │
│ Fitzgerald, Francis Scott,      ┆ Něžná je noc                    ┆ 347   ┆ 2005 │
│ Puzo, Mario,                    ┆ Kmotr                           ┆ 390   ┆ 2005 │
│ Pasternak, Boris Leonidovič,    ┆ Doktor Živago                   ┆ 540   ┆ 2005 │
│ Mann, Thomas,                   ┆ Smrt v Benátkách                ┆ 93    ┆ 2005 │
│ Abe, Kōbō,                      ┆ Písečná žena                    ┆ 174   ┆ 2005 │
│ Clavell, James,                 ┆ Král Krysa                      ┆ 397   ┆ 2005 │
│ McCoy, Horace,                  ┆ Koně se přece střílejí          ┆ 95    ┆ 2005 │
│ Forsyth, Frederick,             ┆ Den pro Šakala                  ┆ 284   ┆ 2005 │
│ Fuks, Ladislav,                 ┆ Spalovač mrtvol                 ┆ 127   ┆ 2005 │
│ Heller, Joseph,                 ┆ Hlava XXII                      ┆ 508   ┆ 2005 │
│ Eastlake, William,              ┆ Hájili jsme hrad                ┆ 366   ┆ 2005 │
│ Vonnegut, Kurt,                 ┆ Kolíbka                         ┆ 206   ┆ 2005 │
│ Lustig, Arnošt,                 ┆ Modlitba pro Kateřinu Horovitz… ┆ 125   ┆ 2005 │
│ Orwell, George,                 ┆ Nadechnout se                   ┆ 215   ┆ 2005 │
│ Woolf, Virginia,                ┆ Paní Dallowayová                ┆ 158   ┆ 2005 │
│ Faulkner, William,              ┆ Divoké palmy                    ┆ 253   ┆ 2005 │
│ Burgess, Anthony,               ┆ Mechanický pomeranč             ┆ 174   ┆ 2005 │
│ Dostojevskij, Fedor Michajlovi… ┆ Idiot                           ┆ 547   ┆ 2005 │
│ Greene, Graham,                 ┆ Jádro věci                      ┆ 269   ┆ 2005 │
│ Morrison, Toni,                 ┆ Milovaná                        ┆ 276   ┆ 2005 │
│ Vian, Boris,                    ┆ Pěna dní                        ┆ 172   ┆ 2005 │
│ Čapek, Karel,                   ┆ Krakatit                        ┆ 253   ┆ 2005 │
│ Dürrenmatt, Friedrich,          ┆ Soudce a jeho kat               ┆ 173   ┆ 2006 │
│ Bellow, Saul,                   ┆ Herzog                          ┆ 381   ┆ 2006 │
│ Moravia, Alberto,               ┆ Nuda                            ┆ 269   ┆ 2006 │
│ Duras, Marguerite,              ┆ Milenec                         ┆ 93    ┆ 2006 │
│ Poláček, Karel,                 ┆ Hostinec U kamenného stolu      ┆ 335   ┆ 2006 │
│ Ruark, Robert Chester,          ┆ Medojedky                       ┆ 613   ┆ 2006 │
│ Rushdie, Salman,                ┆ Východ, Západ                   ┆ 125   ┆ 2006 │
│ Zweig, Stefan,                  ┆ Netrpělivost srdce              ┆ 333   ┆ 2006 │
│ Kesey, Ken,                     ┆ Vyhoďme ho z kola ven           ┆ 301   ┆ 2006 │
│ Chevallier, Gabriel,            ┆ Zvonokosy                       ┆ 316   ┆ 2006 │
│ James, Henry,                   ┆ Utažení šroubu                  ┆ 141   ┆ 2006 │
│ Malaparte, Curzio,              ┆ Kůže                            ┆ 315   ┆ 2006 │
│ Márai, Sándor,                  ┆ Svíce dohořívají                ┆ 125   ┆ 2006 │
│ London, Jack,                   ┆ Martin Eden                     ┆ 342   ┆ 2006 │
│ Nabokov, Vladimir Vladimirovič… ┆ Třináct do tuctu                ┆ 157   ┆ 2006 │
│ Borges, Jorge Luis,             ┆ Obecné dějiny hanebnosti        ┆ 92    ┆ 2006 │
│ Roth, Philip,                   ┆ Portnoyův komplex               ┆ 219   ┆ 2006 │
│ Forster, E. M.                  ┆ Cesta do Indie                  ┆ 333   ┆ 2006 │
│ Coetzee, J. M.                  ┆ Život a doba Michaela K.        ┆ 156   ┆ 2006 │
│ Tomasi di Lampedusa, Giuseppe,  ┆ Gepard                          ┆ 203   ┆ 2006 │
│ Boulle, Pierre,                 ┆ Most přes řeku Kwai             ┆ 156   ┆ 2006 │
│ Zamjatin, Jevgenij Ivanovič,    ┆ My                              ┆ 157   ┆ 2006 │
│ Tanizaki, Jun'ichirō,           ┆ Deník bláznivého starce         ┆ 125   ┆ 2006 │
│ Lodge, David,                   ┆ Den zkázy v Britském muzeu      ┆ 173   ┆ 2006 │
│ Schlink, Bernhard,              ┆ Předčítač                       ┆ 141   ┆ 2006 │
│ Atwood, Margaret,               ┆ Z hlubin                        ┆ 205   ┆ 2006 │
│ Vančura, Vladislav,             ┆ Konec starých časů              ┆ 236   ┆ 2006 │
│ Stout, Rex,                     ┆ Zlatí pavouci                   ┆ 207   ┆ 2007 │
└─────────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [24]:
zjisti("Jak řešit rovnice a jejich soustavy")

Polytechnická knižnice. Ř. 2, Příručky

shape: (3, 6)
┌───────────────┬─────────────────────────────────┬───────┬──────┬───────┬─────────────────────────────────┐
│ 100_a         ┆ 245_a                           ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                           │
│ ---           ┆ ---                             ┆ ---   ┆ ---  ┆ ---   ┆ ---                             │
│ str           ┆ str                             ┆ str   ┆ i64  ┆ i64   ┆ str                             │
╞═══════════════╪═════════════════════════════════╪═══════╪══════╪═══════╪═════════════════════════════════╡
│ Jarník, Jiří, ┆ Jak řešit rovnice a jejich sou… ┆ SNTL  ┆ 1961 ┆ 266   ┆ Polytechnická knižnice. Ř. 2, … │
│ Jarník, Jiří, ┆ Jak řešit rovnice a jejich sou… ┆ SNTL  ┆ 1969 ┆ 243   ┆ Polytechnická knižnice. Řada 2… │
│ Jarník, Jiří, ┆ Jak řešit rovnice a jejich sou… ┆ SNTL  ┆ 1969 ┆ 243   ┆ Řada polytechn. literatury      │
└───────────────┴─────────────────────────────────┴───────┴──────┴───────┴─────────────────────────────────┘

In [25]:
edice("Polytechnická knižnice").sort(by="stran").head(20)

shape: (20, 4)
┌──────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                  ┆ ---                             ┆ ---   ┆ ---  │
│ str                  ┆ str                             ┆ i64   ┆ i64  │
╞══════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Truhlář, Vladimír    ┆ Domácí oranžerie                ┆ 44    ┆ 1979 │
│ Štolovský, Aleš,     ┆ Technika barev                  ┆ 52    ┆ 1981 │
│ Štolovský, Aleš,     ┆ Technika barev                  ┆ 59    ┆ 1990 │
│ Taraba, Oldřich,     ┆ Zázraky světla - lasery         ┆ 65    ┆ 1965 │
│ Schůrek, Oldřich     ┆ Stavíme si krb                  ┆ 65    ┆ 1971 │
│ Diener, Harry        ┆ Jak správně čistit skvrny       ┆ 65    ┆ 1979 │
│ Dobrovolný, Bohumil, ┆ 250 novinek ze světové technol… ┆ 74    ┆ 1966 │
│ Šimr, Václav         ┆ Pojďte s námi stavět sluneční … ┆ 74    ┆ 1989 │
│ Baier, Jiří          ┆ Ochrana dřeva v bytech, chatác… ┆ 75    ┆ 1983 │
│ Vorel, Miroslav      ┆ Stavba sauny                    ┆ 77    ┆ 1980 │
│ Vorel, Miroslav      ┆ Stavba sauny                    ┆ 77    ┆ 1981 │
│ Kareis, Bedřich,     ┆ Šicí stroje v domácnosti        ┆ 79    ┆ 1983 │
│ Kareis, Bedřich,     ┆ Šicí stroje v domácnosti        ┆ 79    ┆ 1986 │
│ Baier, Jiří          ┆ Ochrana dřeva v bytech, chatác… ┆ 79    ┆ 1989 │
│ Kareis, Bedřich,     ┆ Šicí stroje v domácnosti        ┆ 79    ┆ 1991 │
│ Waterstradt, Georg   ┆ Co a jak s tapetami             ┆ 80    ┆ 1981 │
│ Bartoň, Jan          ┆ ABC zajímavostí v elektrotechn… ┆ 86    ┆ 1965 │
│ Dobrovolný, Bohumil, ┆ 250 amerických zlepšovacích ná… ┆ 94    ┆ 1965 │
│ Rejman, Martin,      ┆ Co a jak s polyesterovými skel… ┆ 94    ┆ 1972 │
│ Rejman, Martin,      ┆ Co a jak s polyesterovými skel… ┆ 94    ┆ 1974 │
└──────────────────────┴─────────────────────────────────┴───────┴──────┘

In [87]:
edice("Polytechnická knižnice").sort(by="stran",descending=True).head(20)

shape: (20, 4)
┌──────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                        ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                          ┆ ---                             ┆ ---   ┆ ---  │
│ str                          ┆ str                             ┆ i64   ┆ i64  │
╞══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Košťál, Karel,               ┆ Sbírka fyzikálních vzorců a po… ┆ 503   ┆ 1962 │
│ Měšťan, Radomír              ┆ Stavba svépomocí                ┆ 465   ┆ 1985 │
│ Měšťan, Radomír              ┆ Stavba svépomocí                ┆ 465   ┆ 1989 │
│ Čeleda, Jiří,                ┆ Cesta do nitra hmoty            ┆ 448   ┆ 1981 │
│ Poletajev, Igor‘ Andrejevič, ┆ Kybernetika                     ┆ 429   ┆ 1961 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 427   ┆ 1979 │
│ Hlad, Oldřich,               ┆ Přehled astronomie              ┆ 427   ┆ 1990 │
│ Ernest, Ivan,                ┆ Organická chemie                ┆ 422   ┆ 1960 │
│ Hajach, Tomáš,               ┆ Základní elektrotechnické výpo… ┆ 411   ┆ 1976 │
│ Košťál, Karel,               ┆ Sbírka fyzikálních vzorců a po… ┆ 407   ┆ 1970 │
│ Měšťan, Radomír              ┆ Dekorativní úpravy v bytě       ┆ 407   ┆ 1986 │
│ Měšťan, Radomír              ┆ Dekorativní úpravy v bytě       ┆ 407   ┆ 1988 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 407   ┆ 1989 │
│ Kowal, Stanisław,            ┆ Matematika pro volné chvíle     ┆ 401   ┆ 1975 │
│ Kuba, Josef,                 ┆ Cesta do nitra hmoty            ┆ 398   ┆ 1963 │
│ Hlad, Oldřich,               ┆ Přehled astronomie              ┆ 393   ┆ 1984 │
│ Měšťan, Radomír              ┆ Modernizace bytů, rodinných do… ┆ 389   ┆ 1990 │
│ Košťál, Karel,               ┆ Sbírka fyzikálních vzorců a po… ┆ 387   ┆ 1964 │
│ Pacák, Josef,                ┆ Poznáváme organickou chemii     ┆ 382   ┆ 1989 │
│ Beránek, Robert,             ┆ Kalendář svépomocných prací     ┆ 366   ┆ 1985 │
└──────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [26]:
edice("Polytechnická knižnice")

shape: (465, 4)
┌─────────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                           ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                             ┆ ---                             ┆ ---   ┆ ---  │
│ str                             ┆ str                             ┆ i64   ┆ i64  │
╞═════════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Sackmann, Horst,                ┆ Fysikální chemie                ┆ 283   ┆ 1957 │
│ Kohlmann, Čeněk,                ┆ Aritmetika a algebra            ┆ 228   ┆ 1958 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 213   ┆ 1958 │
│ Košťál, Karel,                  ┆ Sbírka fysikálních vzorců a po… ┆ 213   ┆ 1959 │
│ Andrlík, Karel,                 ┆ Škola fotografie                ┆ 186   ┆ 1959 │
│ Krutina, Jaroslav               ┆ Sbírka vzorců z pružnosti a pe… ┆ 254   ┆ 1959 │
│ Vavruch, Ivan,                  ┆ Koloidní chemie                 ┆ 221   ┆ 1959 │
│ Vinter, Jan                     ┆ Práce se dřevem ve školních dí… ┆ 175   ┆ 1959 │
│ Trnka, Jiří,                    ┆ Natíráme sami                   ┆ 152   ┆ 1959 │
│ Bartoš, Rudolf                  ┆ Vrtulníky                       ┆ 202   ┆ 1959 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 254   ┆ 1959 │
│ Kohlmann, Čeněk,                ┆ Geometrie                       ┆ 253   ┆ 1959 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 234   ┆ 1959 │
│ Haškovec, Ladislav              ┆ Znáte dopravní předpisy?        ┆ 258   ┆ 1959 │
│ Vacek, Adolf                    ┆ Početní tabulky pro techniky    ┆ 208   ┆ 1959 │
│ Michajlov, V. A.                ┆ Fyzikální základy uvolňování j… ┆ 183   ┆ 1959 │
│ Ministr, Zdeněk,                ┆ Prášková metalurgie             ┆ 208   ┆ 1959 │
│ Trávníček, Zdeněk               ┆ Vlákna budoucnosti              ┆ 221   ┆ 1959 │
│ Elstner, František Alexander,   ┆ Vázání uzlů                     ┆ 142   ┆ 1959 │
│ Dragoun, Zdeněk                 ┆ Polovodiče                      ┆ 230   ┆ 1959 │
│ Tajovský, Václav                ┆ Stavitelství                    ┆ 170   ┆ 1959 │
│ Hudec, Josef                    ┆ Elektrické stroje               ┆ 198   ┆ 1959 │
│ Jírů, Pavel,                    ┆ Dřevo, jeho vlastnosti a použi… ┆ 219   ┆ 1960 │
│ Jeřábek, Václav,                ┆ Nové stavební hmoty             ┆ 159   ┆ 1960 │
│ Kubeš, Josef                    ┆ Domovní instalace (voda, kanal… ┆ 174   ┆ 1960 │
│ Reichstädter, Bohumil,          ┆ Co máte vědět o textilu, do ně… ┆ 150   ┆ 1960 │
│ Karen, Ota                      ┆ Radiotechnika pro každého       ┆ 283   ┆ 1960 │
│ Vebr, Jiří                      ┆ Šicí stroje a šití na nich      ┆ 161   ┆ 1960 │
│ Ernest, Ivan,                   ┆ Organická chemie                ┆ 422   ┆ 1960 │
│ Brož, Jaroslav                  ┆ Miniaturní spalovací motorky p… ┆ 165   ┆ 1960 │
│ Nedoma, Woodrow                 ┆ Plyn v domácnosti               ┆ 148   ┆ 1960 │
│ Novák, Milan                    ┆ Exkurze do parní elektrárny     ┆ 142   ┆ 1960 │
│ Beneš, Jan                      ┆ Stavba garáže                   ┆ 225   ┆ 1960 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 209   ┆ 1960 │
│ Košťál, Karel,                  ┆ Sbírka fysikálních vzorců a po… ┆ 264   ┆ 1960 │
│ Petrů, František,               ┆ Atomy, ionty, molekuly          ┆ 210   ┆ 1960 │
│ Hansa, Miloš                    ┆ Jak na to?                      ┆ 176   ┆ 1960 │
│ Smolík, František,              ┆ Využijte lépe svého přijímače   ┆ 192   ┆ 1960 │
│ Chvojka, František              ┆ Bytové doplňky vlastní výroby   ┆ 163   ┆ 1960 │
│ Pechlát, Jaroslav               ┆ Vlastní dílna                   ┆ 178   ┆ 1960 │
│ Velík, Vladimír                 ┆ Základy elektrotechniky         ┆ 226   ┆ 1960 │
│ Ženíšek, Ota                    ┆ Moderní prostředky osobní dopr… ┆ 227   ┆ 1960 │
│ Sedláček, Jiří,                 ┆ Nebojte se matematiky           ┆ 169   ┆ 1960 │
│ Hájek, Miroslav,                ┆ O tkaninách                     ┆ 223   ┆ 1960 │
│ Diomidov, Michail Nikolajevič   ┆ V batyskafu na mořské dno       ┆ 223   ┆ 1961 │
│ Mendygral, Zenon                ┆ Radar dnes a zítra              ┆ 144   ┆ 1961 │
│ Miškovský, Ilja,                ┆ Radioaktivní izotopy v praxi    ┆ 257   ┆ 1961 │
│ Doležal, Jaroslav,              ┆ Vazby knih                      ┆ 229   ┆ 1961 │
│ Čihák, Vlastimil,               ┆ Logaritmické pravítko           ┆ 229   ┆ 1961 │
│ Pazourek, Jaroslav,             ┆ Pracujeme s mikroskopem         ┆ 210   ┆ 1961 │
│ Andrlík, Karel,                 ┆ Škola fotografie                ┆ 188   ┆ 1961 │
│ Poletajev, Igor‘ Andrejevič,    ┆ Kybernetika                     ┆ 429   ┆ 1961 │
│ Stupecký, Josef                 ┆ Abeceda filmového amatéra       ┆ 260   ┆ 1961 │
│ Kubát, Karel                    ┆ Pracujeme s magnetofonem        ┆ 212   ┆ 1961 │
│ Samek, Miloslav                 ┆ Samočinné počítače              ┆ 282   ┆ 1961 │
│ Trnka, Jiří,                    ┆ Natíráme sami                   ┆ 190   ┆ 1961 │
│ Frey, Jakub,                    ┆ Loď, moře, námořníci            ┆ 266   ┆ 1961 │
│ Procházka, Vladimír,            ┆ Technická příručka pro modelář… ┆ 266   ┆ 1961 │
│ Ledvina, Milan                  ┆ Raketové motory                 ┆ 187   ┆ 1961 │
│ Jarník, Jiří,                   ┆ Jak řešit rovnice a jejich sou… ┆ 266   ┆ 1961 │
│ Vasil'jev, Michail Vasil'jevič  ┆ Stroje dneška a budoucnosti     ┆ 172   ┆ 1961 │
│ Koval, Václav,                  ┆ Technika zítřka                 ┆ 225   ┆ 1961 │
│ Hruša, Karel,                   ┆ Řešené úlohy z matematiky       ┆ 190   ┆ 1962 │
│ Bauman, Milan,                  ┆ Vývoj sdělovací techniky        ┆ 251   ┆ 1962 │
│ Hájek, Bohumil,                 ┆ Anorganická chemie              ┆ 245   ┆ 1962 │
│ Kuznecov, Boris Grigor‘jevič,   ┆ O teorii relativity             ┆ 237   ┆ 1962 │
│ Havlíček, Karel,                ┆ Diferenciální počet pro začáte… ┆ 250   ┆ 1962 │
│ Beneš, Jan                      ┆ Stavba garáže                   ┆ 228   ┆ 1962 │
│ Greniewski, Henryk,             ┆ Základy kybernetiky             ┆ 190   ┆ 1962 │
│ Košťál, Karel,                  ┆ Sbírka fyzikálních vzorců a po… ┆ 503   ┆ 1962 │
│ Vanýsek, Vladimír,              ┆ Lety v kosmickém prostoru       ┆ 194   ┆ 1962 │
│ Tyl, Josef                      ┆ Jak jezdit bez nehod            ┆ 239   ┆ 1962 │
│ Pacáková, Libuše                ┆ Velmi krátké vlny a jejich pou… ┆ 219   ┆ 1962 │
│ Erhart, Vilém,                  ┆ Amatérské astronomické dalekoh… ┆ 218   ┆ 1962 │
│ Vinter, Jan                     ┆ Práce se dřevem                 ┆ 182   ┆ 1962 │
│ Pechlát, Jaroslav               ┆ Vlastní dílna                   ┆ 178   ┆ 1962 │
│ Hansa, Miloš                    ┆ Jak na to?                      ┆ 175   ┆ 1962 │
│ Menšík, Miroslav,               ┆ Deskriptivní geometrie          ┆ 207   ┆ 1962 │
│ Setzer, Ota,                    ┆ Deskriptivní geometrie          ┆ 207   ┆ 1962 │
│ Dragoun, Zdeněk                 ┆ Polovodiče                      ┆ 251   ┆ 1962 │
│ Krutina, Jaroslav               ┆ Sbírka vzorců z pružnosti a pe… ┆ 238   ┆ 1962 │
│ Procházka, Vladimír,            ┆ Miniaturní elektromotorky pro … ┆ 142   ┆ 1962 │
│ Trtílek, Josef,                 ┆ Jak porozumíme chemickým vzorc… ┆ 191   ┆ 1962 │
│ Vodnárek, Ladislav              ┆ Diktafony v praxi               ┆ 288   ┆ 1962 │
│ Dvořák, Jiří,                   ┆ Technické křivky                ┆ 229   ┆ 1962 │
│ Havlíček, Karel,                ┆ Integrální počet pro začáteční… ┆ 241   ┆ 1963 │
│ Rychnovský, Richard,            ┆ Obyčejné diferenciální rovnice… ┆ 253   ┆ 1963 │
│ Kuba, Josef,                    ┆ Cesta do nitra hmoty            ┆ 398   ┆ 1963 │
│ Březina, Jan                    ┆ Vodní turbíny                   ┆ 162   ┆ 1963 │
│ Horna, Otakar A.                ┆ Zajímavá zapojení s tranzistor… ┆ 176   ┆ 1963 │
│ Vaculík, Jaroslav,              ┆ Rekreační ubytování             ┆ 191   ┆ 1963 │
│ Augusta, Ivo                    ┆ O stavebních konstrukcích       ┆ 229   ┆ 1963 │
│ Bieber, Boleslav                ┆ Chemická laboratoř              ┆ 226   ┆ 1963 │
│ Myslivec, Jaroslav              ┆ Tranzistorové magnetofony       ┆ 219   ┆ 1963 │
│ Barta, Rudolf,                  ┆ Sklářství                       ┆ 196   ┆ 1963 │
│ Rychnovský, Richard,            ┆ Parciální diferenciální rovnic… ┆ 167   ┆ 1963 │
│ Täubl, Karel,                   ┆ Zlatnictví                      ┆ 169   ┆ 1963 │
│ Mareš, Karel,                   ┆ Výrobní práce žáků a výroba     ┆ 150   ┆ 1963 │
│ Koškin, N. J.                   ┆ Základy fyziky                  ┆ 198   ┆ 1963 │
│ Jungmann, Bohumil               ┆ Technologie strojírenské výrob… ┆ 281   ┆ 1963 │
│ Ondříček, Miroslav              ┆ Zdroje a využití energie        ┆ 177   ┆ 1963 │
│ Florov, Vasilij Arkad'jevič     ┆ Kovy budoucnosti                ┆ 210   ┆ 1963 │
│ Bauman, Milan,                  ┆ Za televizní obrazovkou         ┆ 190   ┆ 1963 │
│ Růžička, Primus,                ┆ Diamanty a jejich použití v pr… ┆ 114   ┆ 1963 │
│ Gruncl, Ladislav                ┆ Elektrické přístroje mladého t… ┆ 180   ┆ 1963 │
│ Wittmers, Hugo                  ┆ Úvod do regulační techniky      ┆ 197   ┆ 1963 │
│ Erhart, Vilém,                  ┆ Amatérské astronomické fotogra… ┆ 199   ┆ 1963 │
│ Bláha, Richard,                 ┆ Exkurze do tiskárny             ┆ 162   ┆ 1963 │
│ Ernest, Ivan,                   ┆ Organická chemie                ┆ 334   ┆ 1964 │
│ Mašek, Ladislav                 ┆ Úprava bytového interiéru       ┆ 209   ┆ 1964 │
│ Gruncl, Ladislav                ┆ Přístroje a stroje vlastní výr… ┆ 176   ┆ 1964 │
│ Říman, Evžen,                   ┆ Fyzika                          ┆ 199   ┆ 1964 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 181   ┆ 1964 │
│ Andrlík, Karel,                 ┆ Analytická chemie               ┆ 190   ┆ 1964 │
│ Boublík, Vlastimil,             ┆ Lepidla a jejich příprava       ┆ 189   ┆ 1964 │
│ Valsa, Juraj,                   ┆ Televizní technika              ┆ 149   ┆ 1964 │
│ Dočkal, Jiří,                   ┆ Údržba a opravy mopedů          ┆ 170   ┆ 1964 │
│ Kubeš, Josef                    ┆ Domovní instalace (voda a plyn… ┆ 137   ┆ 1964 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 182   ┆ 1964 │
│ Procházka, Arnold               ┆ Hydraulika v příkladech a poku… ┆ 164   ┆ 1964 │
│ Říman, Evžen,                   ┆ Příklady z fyziky               ┆ 148   ┆ 1964 │
│ Polák, Vilém                    ┆ Využití umělého chladu          ┆ 203   ┆ 1964 │
│ Pazderák, Jiří,                 ┆ Barevná televize                ┆ 183   ┆ 1964 │
│ Košťál, Karel,                  ┆ Sbírka fyzikálních vzorců a po… ┆ 387   ┆ 1964 │
│ Richter, A.                     ┆ Proudová výroba                 ┆ 130   ┆ 1964 │
│ Bartoň, Jan                     ┆ ABC zajímavostí v elektrotechn… ┆ 86    ┆ 1965 │
│ Fišner, Boleslav,               ┆ Chemie                          ┆ 221   ┆ 1965 │
│ Reisenauer, Roman               ┆ Metody matematické statistiky … ┆ 208   ┆ 1965 │
│ Walla, Viktor                   ┆ Kaličství v kostce              ┆ 154   ┆ 1965 │
│ Klepl, Václav,                  ┆ Jak číst schémata v radiotechn… ┆ 175   ┆ 1965 │
│ Mašek, Ladislav                 ┆ Úprava bytového interiéru       ┆ 209   ┆ 1965 │
│ Schätz, Miroslav,               ┆ Kaučuk                          ┆ 178   ┆ 1965 │
│ Keck, Christian                 ┆ Urychlovače částic              ┆ 139   ┆ 1965 │
│ Březina, Jan                    ┆ Parní a plynové turbíny         ┆ 161   ┆ 1965 │
│ Boublík, Vlastimil,             ┆ Práce s plastickými hmotami     ┆ 216   ┆ 1965 │
│ Pospíšil, Antonín,              ┆ Zopakujme si deskriptivu        ┆ 130   ┆ 1965 │
│ Wideman, František              ┆ Základy, stropy a krovy         ┆ 192   ┆ 1965 │
│ Dobrovolný, Bohumil,            ┆ 250 amerických zlepšovacích ná… ┆ 94    ┆ 1965 │
│ Bruthans, Vladimír,             ┆ Matematika                      ┆ 164   ┆ 1965 │
│ Taraba, Oldřich,                ┆ Zázraky světla - lasery         ┆ 65    ┆ 1965 │
│ Novák, Karel                    ┆ Amatérské součástky a stavba t… ┆ 214   ┆ 1965 │
│ Havlíček, Karel,                ┆ Diferenciální počet pro začáte… ┆ 195   ┆ 1965 │
│ Říman, Evžen,                   ┆ Fyzika s příklady a úlohami     ┆ 349   ┆ 1966 │
│ Nor, A. C.,                     ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Nor, A. C.,                     ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Staněk, Milan                   ┆ 100 tranzistorových přístrojů   ┆ 133   ┆ 1966 │
│ Dobrovolný, Bohumil,            ┆ 250 novinek ze světové technol… ┆ 74    ┆ 1966 │
│ Boublík, Vlastimil,             ┆ Lití plastických hmot pro mode… ┆ 199   ┆ 1966 │
│ Elstner, František Alexander,   ┆ Vázání uzlů                     ┆ 137   ┆ 1966 │
│ Válek, Jiří                     ┆ Úvod do elektroniky             ┆ 195   ┆ 1966 │
│ Boublík, Vlastimil,             ┆ Lepidla a jejich příprava       ┆ 190   ┆ 1966 │
│ Štěpánský, Václav,              ┆ Nomogramy                       ┆ 186   ┆ 1966 │
│ Procházka, Arnold               ┆ Základy mechaniky vody v praxi  ┆ 125   ┆ 1966 │
│ Slavíček, Ivan                  ┆ Tranzistory řídí techniku       ┆ 152   ┆ 1966 │
│ Štěpán, Miroslav,               ┆ Chemie v denním životě          ┆ 171   ┆ 1966 │
│ Procházka, Jan,                 ┆ Zázraky divadla                 ┆ 108   ┆ 1966 │
│ Tříska, Jiří,                   ┆ Základní elektrotechnické tabu… ┆ 260   ┆ 1966 │
│ Jeřábek, Václav,                ┆ Obnova a údržba malých staveb   ┆ 149   ┆ 1966 │
│ Novák, Karel                    ┆ Amatérská oprava tranzistorové… ┆ 171   ┆ 1966 │
│ Václavovič, Antonín,            ┆ Umění konstruovat               ┆ 189   ┆ 1966 │
│ Menšík, Miroslav,               ┆ Deskriptivní geometrie          ┆ 224   ┆ 1966 │
│ Seidler, Alois                  ┆ Tabulky normalizovaných závitů… ┆ 316   ┆ 1966 │
│ Beneš, Oldřich                  ┆ 1111 nápadů pro motoristy a dí… ┆ 255   ┆ 1966 │
│ Mašek, Ladislav                 ┆ Úprava bytového interiéru       ┆ 209   ┆ 1967 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 165   ┆ 1967 │
│ Frey, Jakub,                    ┆ Loď, moře, námořníci            ┆ 209   ┆ 1967 │
│ Tauš, Gustav,                   ┆ Pokusy z radiotechniky          ┆ 277   ┆ 1967 │
│ Beneš, Oldřich                  ┆ 1111 nápadů pro motoristy a dí… ┆ 254   ┆ 1967 │
│ Hájek, Bohumil,                 ┆ Anorganická chemie              ┆ 194   ┆ 1967 │
│ Dobrovolný, Bohumil,            ┆ Nové matematické rekreace       ┆ 157   ┆ 1967 │
│ Husička, Karel                  ┆ Využijte lépe svůj magnetofon   ┆ 177   ┆ 1967 │
│ Budlovský, Jaroslav,            ┆ Motory                          ┆ 169   ┆ 1967 │
│ Nečásek, Sláva                  ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Nečásek, Sláva                  ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Urban, Eduard                   ┆ Mosty - jeden z divů světa      ┆ 146   ┆ 1967 │
│ Maška, Otokar,                  ┆ Řešené úlohy z matematiky       ┆ 208   ┆ 1967 │
│ Čermák, Miloš,                  ┆ Sbírka úloh z matematiky        ┆ 250   ┆ 1967 │
│ Vykoukal, Rudolf,               ┆ Automobilové a motocyklové mot… ┆ 196   ┆ 1967 │
│ Seidler, Alois                  ┆ Tabulky normalizovaných závitů… ┆ 318   ┆ 1967 │
│ Břízová, Joza,                  ┆ Technika mění domácnost         ┆ 153   ┆ 1967 │
│ Tůma, Jan,                      ┆ Vyučovací stroje                ┆ 205   ┆ 1967 │
│ Šindelář, Václav,               ┆ Zopakujme si fyziku             ┆ 210   ┆ 1967 │
│ Hanuš, Bohuslav                 ┆ Amatérská stavba elektrických … ┆ 184   ┆ 1967 │
│ Fišner, Boleslav,               ┆ Chemie                          ┆ 229   ┆ 1967 │
│ Petrů, František,               ┆ Atomy, ionty, molekuly          ┆ 170   ┆ 1968 │
│ Batka, Vilém,                   ┆ 100 příkladů z lineárních elek… ┆ 152   ┆ 1968 │
│ Kubeš, Josef                    ┆ Domovní instalace               ┆ 174   ┆ 1968 │
│ Měšťan, Radomír                 ┆ Opravujeme byt a rodinný domek  ┆ 243   ┆ 1968 │
│ Měšťan, Radomír                 ┆ Opravujeme byt a rodinný domek  ┆ 243   ┆ 1968 │
│ Vokoun, Jaroslav,               ┆ Moderní osvětlení do bytu       ┆ 127   ┆ 1968 │
│ Čuma, Miroslav                  ┆ Pokrokové způsoby ostření řezn… ┆ 133   ┆ 1968 │
│ Krňák, Rudolf                   ┆ 500 novinek ze svařování - mal… ┆ 155   ┆ 1968 │
│ Jozífek, Vítězslav,             ┆ Počítáme na logaritmickém prav… ┆ 132   ┆ 1968 │
│ Hyan, Jaroslav,                 ┆ Amatérská stereofonie           ┆ 191   ┆ 1968 │
│ Gregora, Otakar,                ┆ Normy strojnického kreslení     ┆ 226   ┆ 1968 │
│ Slavíček, Ivan                  ┆ Elektromotorky a jejich řízení  ┆ 237   ┆ 1968 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 133   ┆ 1969 │
│ Sedláček, Jiří,                 ┆ Nebojte se matematiky           ┆ 135   ┆ 1969 │
│ Zahradník, Josef                ┆ Lineární programování při říze… ┆ 231   ┆ 1969 │
│ Chalupský, Ladislav,            ┆ 100x o umělém osvětlení         ┆ 278   ┆ 1969 │
│ Johánek, Tomáš                  ┆ 500 příkladů úsporného konstru… ┆ 122   ┆ 1969 │
│ Dobrovolný, Bohumil,            ┆ Automaty si děláme sami         ┆ 132   ┆ 1969 │
│ Škoda, Zdeněk                   ┆ Elektronika v motorovém vozidl… ┆ 163   ┆ 1969 │
│ Jarník, Jiří,                   ┆ Jak řešit rovnice a jejich sou… ┆ 243   ┆ 1969 │
│ Klepl, Václav,                  ┆ Jak číst schémata v radiotechn… ┆ 239   ┆ 1969 │
│ Karaus, Evžen,                  ┆ Teplo našim domovům             ┆ 145   ┆ 1969 │
│ Šindelář, Karel,                ┆ Analytická geometrie pro začát… ┆ 237   ┆ 1969 │
│ Paulín, Zdeněk                  ┆ 100 zajímavostí z radiotechnik… ┆ 157   ┆ 1969 │
│ Havlíček, Karel,                ┆ Integrální počet pro začáteční… ┆ 207   ┆ 1969 │
│ Dobrovolný, Bohumil,            ┆ Matematické rekreace            ┆ 131   ┆ 1969 │
│ Beránek, Robert,                ┆ Úprava okolí chaty nebo rodinn… ┆ 133   ┆ 1970 │
│ Kulhánek, Jaroslav,             ┆ Fotografické tabulky            ┆ 216   ┆ 1970 │
│ Štěpánský, Václav,              ┆ Nomogramy                       ┆ 248   ┆ 1970 │
│ Chytil, Metoděj                 ┆ Zajímavá použití samočinných p… ┆ 131   ┆ 1970 │
│ Reisenauer, Roman               ┆ Metody matematické statistiky … ┆ 239   ┆ 1970 │
│ Košťál, Karel,                  ┆ Sbírka fyzikálních vzorců a po… ┆ 407   ┆ 1970 │
│ Bruthans, Vladimír,             ┆ Matematika                      ┆ 164   ┆ 1970 │
│ Rychnovský, Richard,            ┆ Parciální diferenciální rovnic… ┆ 167   ┆ 1970 │
│ Měšťan, Radomír                 ┆ Opravujeme byt a rodinný domek  ┆ 243   ┆ 1970 │
│ Nečásek, Sláva                  ┆ Výběr zajímavých zapojení       ┆ 256   ┆ 1970 │
│ Kolek, Lubomír                  ┆ Přehled vzorců středoškolské m… ┆ 323   ┆ 1970 │
│ Krištoufek, Karel,              ┆ Matematické stroje              ┆ 197   ┆ 1970 │
│ Slavíček, Ivan                  ┆ 500 tranzistorových obvodů      ┆ 222   ┆ 1970 │
│ Jelínek, Vladimír,              ┆ Stavby rodinných domků, rekrea… ┆ 222   ┆ 1970 │
│ Batka, Vilém,                   ┆ Elektromagnetismus              ┆ 157   ┆ 1970 │
│ Michal, Stanislav               ┆ Perpetuum mobile včera a dnes   ┆ 185   ┆ 1971 │
│ Prágerová, Alena                ┆ Diferenční rovnice              ┆ 115   ┆ 1971 │
│ Švercl, Josef                   ┆ Zobrazovací metody              ┆ 227   ┆ 1971 │
│ Staňková, Jaroslava,            ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │
│ Staňková, Jaroslava,            ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │

In [27]:
zjisti("Normy strojnického kreslení")

Polytechnická knižnice. Řada 1, Technický výběr do kapsy

shape: (1, 6)
┌──────────────────┬─────────────────────────────┬───────┬──────┬───────┬─────────────────────────────────┐
│ 100_a            ┆ 245_a                       ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                           │
│ ---              ┆ ---                         ┆ ---   ┆ ---  ┆ ---   ┆ ---                             │
│ str              ┆ str                         ┆ str   ┆ i64  ┆ i64   ┆ str                             │
╞══════════════════╪═════════════════════════════╪═══════╪══════╪═══════╪═════════════════════════════════╡
│ Gregora, Otakar, ┆ Normy strojnického kreslení ┆ Práce ┆ 1968 ┆ 226   ┆ Polytechnická knižnice. Řada 1… │
└──────────────────┴─────────────────────────────┴───────┴──────┴───────┴─────────────────────────────────┘

In [28]:
edice("Technický výběr do kapsy")

shape: (135, 4)
┌───────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                 ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                   ┆ ---                             ┆ ---   ┆ ---  │
│ str                   ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Sadoul, Georges,      ┆ Zázraky filmu                   ┆ 230   ┆ 1958 │
│ Dobrovolný, Bohumil,  ┆ Zopakujme si elektrotechniku    ┆ 191   ┆ 1958 │
│ Vacek, Adolf          ┆ Logaritmické tabulky a výpočty  ┆ 129   ┆ 1958 │
│ Žalud, Karel          ┆ Rychlosti, vzdálenosti          ┆ 175   ┆ 1958 │
│ Dobrovolný, Bohumil,  ┆ Technika v kostce               ┆ 199   ┆ 1958 │
│ Andrlík, Karel,       ┆ Zopakujme si chemii             ┆ 177   ┆ 1958 │
│ Tříska, Jiří,         ┆ Elektroautomatiky v průmyslu    ┆ 138   ┆ 1958 │
│ Roček, Vladimír       ┆ Pokrokové konstrukce obráběcíc… ┆ 171   ┆ 1958 │
│ Taraba, Oldřich,      ┆ Co dovede ultrazvuk             ┆ 154   ┆ 1958 │
│ Vacek, Adolf          ┆ Zopakujme si matematiku         ┆ 135   ┆ 1959 │
│ Chalupa, Zdeněk       ┆ Atom dobývá svět                ┆ 191   ┆ 1959 │
│ Krutina, Jaroslav     ┆ Zopakujme si mechaniku          ┆ 158   ┆ 1959 │
│ Tříska, Jiří,         ┆ Základní elektrotechnické tabu… ┆ 190   ┆ 1959 │
│ Blabolil, František   ┆ Plastické hmoty ve strojírenst… ┆ 216   ┆ 1959 │
│ Bartoň, Jan           ┆ Novinky v radiotechnice         ┆ 109   ┆ 1959 │
│ Tomsa, Milan,         ┆ Zázraky televize                ┆ 137   ┆ 1959 │
│ Ženíšek, Ota          ┆ Moderní letectví                ┆ 105   ┆ 1959 │
│ Dobrovolný, Bohumil,  ┆ Pokrokové konstrukce lisovacíc… ┆ 163   ┆ 1959 │
│ Dobrovolný, Bohumil,  ┆ Technologie v kostce            ┆ 141   ┆ 1959 │
│ Dobrovolný, Bohumil,  ┆ 500 vtipných nápadů pro dílny   ┆ 138   ┆ 1960 │
│ Růžička, Bohuslav     ┆ Zopakujme si technické kreslen… ┆ 143   ┆ 1960 │
│ Netušil, Jaroslav,    ┆ Světlo v teorii a v praxi       ┆ 173   ┆ 1960 │
│ Kolář, Jan            ┆ Pod zemí pracují stroje         ┆ 183   ┆ 1960 │
│ Blabolil, František   ┆ Novinky v oboru plastických hm… ┆ 53    ┆ 1960 │
│ Wimmer, Miloslav,     ┆ Základní stavební tabulky       ┆ 169   ┆ 1960 │
│ Dvořák, Josef,        ┆ Do kosmického prostoru          ┆ 129   ┆ 1960 │
│ Lukeš, Jaroslav,      ┆ Novinky v radiotechnice         ┆ 50    ┆ 1960 │
│ Körbler, Vladimír     ┆ Budujeme moderní chemický prům… ┆ 171   ┆ 1960 │
│ Václavovič, Antonín,  ┆ Pokrokové způsoby měření ve vý… ┆ 159   ┆ 1960 │
│ Chalupa, Zdeněk       ┆ Novinky v atomistice            ┆ 41    ┆ 1960 │
│ Šindelář, Václav,     ┆ Zopakujme si fysiku             ┆ 158   ┆ 1960 │
│ Hošek, Josef,         ┆ Novinky v letectví              ┆ 48    ┆ 1960 │
│ Dobrovolný, Bohumil,  ┆ Matematické rekreace            ┆ 139   ┆ 1961 │
│ Melzer, Zdeněk        ┆ Maloobsahová vozidla            ┆ 147   ┆ 1961 │
│ Pacák, Miroslav,      ┆ Vyšší škola radiotechniky       ┆ 161   ┆ 1961 │
│ Šebek, Otto,          ┆ Co nevíte o meteorologii        ┆ 136   ┆ 1961 │
│ Andrlík, Karel,       ┆ Základní chemické tabulky       ┆ 159   ┆ 1961 │
│ Klir, George J.,      ┆ Matematické stroje              ┆ 163   ┆ 1961 │
│ Dobrovolný, Bohumil,  ┆ Slovníček nové techniky         ┆ 134   ┆ 1961 │
│ Vrdlovec, Jan         ┆ 200 technických zlepšení z čes… ┆ 117   ┆ 1961 │
│ Staněk, Milan         ┆ 100 tranzistorových přístrojů   ┆ 120   ┆ 1961 │
│ Dobrovolný, Bohumil,  ┆ Nástrojařství v kostce          ┆ 170   ┆ 1962 │
│ Taraba, Oldřich,      ┆ Elektronická měření v průmyslu  ┆ 203   ┆ 1962 │
│ Wimmer, Miloslav,     ┆ Základní stavební tabulky       ┆ 148   ┆ 1962 │
│ Vacek, Adolf          ┆ Logaritmické a početní tabulky  ┆ 130   ┆ 1962 │
│ Krňák, Rudolf         ┆ Zopakujme si svařování          ┆ 159   ┆ 1962 │
│ Pacák, Miroslav,      ┆ Vyšší škola radiotechniky       ┆ 181   ┆ 1962 │
│ Hošek, Josef,         ┆ Dnešní letectví                 ┆ 170   ┆ 1962 │
│ Schneider, Jaroslav,  ┆ Práce v chemické laboratoři     ┆ 137   ┆ 1962 │
│ Klepl, Václav,        ┆ Elektrotechnika v příkladech    ┆ 205   ┆ 1962 │
│ Krutina, Jaroslav     ┆ Zopakujme si statiku            ┆ 157   ┆ 1962 │
│ Vacek, Adolf          ┆ Pokrokové konstrukce a výpočty… ┆ 169   ┆ 1962 │
│ Paulín, Zdeněk        ┆ Zázraky zvuku                   ┆ 173   ┆ 1962 │
│ Sadoul, Georges,      ┆ Zázraky filmu                   ┆ 205   ┆ 1962 │
│ Teplý, Stanislav      ┆ Stavitelství a architektura v … ┆ 168   ┆ 1963 │
│ Roček, Vladimír       ┆ Tabulky z konstrukce nástrojů   ┆ 142   ┆ 1963 │
│ Taraba, Oldřich,      ┆ Co dovede ultrazvuk             ┆ 158   ┆ 1963 │
│ Pokorný, Václav       ┆ Lícovací a dílenské tabulky IS… ┆ 129   ┆ 1963 │
│ Krutina, Jaroslav     ┆ Zopakujme si pružnost a pevnos… ┆ 123   ┆ 1963 │
│ Nussberger, Jaroslav, ┆ Zopakujme si optiku             ┆ 139   ┆ 1963 │
│ Dobrovolný, Bohumil,  ┆ 500 technologických nápadů ze … ┆ 147   ┆ 1963 │
│ Kouba, Jaroslav       ┆ Malý přehled vzorců             ┆ 137   ┆ 1963 │
│ Baran, Ludvík,        ┆ Zázraky fotografie              ┆ 147   ┆ 1964 │
│ Staněk, Milan         ┆ 100 tranzistorových přístrojů   ┆ 130   ┆ 1964 │
│ Pokorný, Václav       ┆ Soustružnictví v kostce         ┆ 142   ┆ 1964 │
│ Ruml, Vladimír        ┆ Zopakujme si technické materiá… ┆ 191   ┆ 1964 │
│ Šulc, Jan             ┆ Zázraky úzkého filmu            ┆ 175   ┆ 1964 │
│ Verunáč, Václav,      ┆ Technika kosmického věku        ┆ 94    ┆ 1964 │
│ Pavlík, Miloslav,     ┆ Rady a recepty pro dílny        ┆ 181   ┆ 1964 │
│ Dobrovolný, Bohumil,  ┆ 500 novinek z mechanizace a au… ┆ 133   ┆ 1964 │
│ Řeháček, Emil         ┆ Ozubená kola                    ┆ 158   ┆ 1964 │
│ Nečásek, Sláva        ┆ 100 zajímavých okruhů z elektr… ┆ 114   ┆ 1964 │
│ Ehleman, Jan,         ┆ Stroje pracují v administrativ… ┆ 191   ┆ 1964 │
│ Bartoň, Jan           ┆ ABC zajímavostí v elektrotechn… ┆ 86    ┆ 1965 │
│ Walla, Viktor         ┆ Kaličství v kostce              ┆ 154   ┆ 1965 │
│ Klepl, Václav,        ┆ Jak číst schémata v radiotechn… ┆ 175   ┆ 1965 │
│ Schätz, Miroslav,     ┆ Kaučuk                          ┆ 178   ┆ 1965 │
│ Keck, Christian       ┆ Urychlovače částic              ┆ 139   ┆ 1965 │
│ Pospíšil, Antonín,    ┆ Zopakujme si deskriptivu        ┆ 130   ┆ 1965 │
│ Dobrovolný, Bohumil,  ┆ 250 amerických zlepšovacích ná… ┆ 94    ┆ 1965 │
│ Taraba, Oldřich,      ┆ Zázraky světla - lasery         ┆ 65    ┆ 1965 │
│ Nečásek, Sláva        ┆ 100 zajímavých okruhů z elektr… ┆ 114   ┆ 1965 │
│ Nor, A. C.,           ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Nor, A. C.,           ┆ Technik píše česky              ┆ 287   ┆ 1966 │
│ Staněk, Milan         ┆ 100 tranzistorových přístrojů   ┆ 133   ┆ 1966 │
│ Dobrovolný, Bohumil,  ┆ 250 novinek ze světové technol… ┆ 74    ┆ 1966 │
│ Procházka, Arnold     ┆ Základy mechaniky vody v praxi  ┆ 125   ┆ 1966 │
│ Slavíček, Ivan        ┆ Tranzistory řídí techniku       ┆ 152   ┆ 1966 │
│ Štěpán, Miroslav,     ┆ Chemie v denním životě          ┆ 171   ┆ 1966 │
│ Procházka, Jan,       ┆ Zázraky divadla                 ┆ 108   ┆ 1966 │
│ Tříska, Jiří,         ┆ Základní elektrotechnické tabu… ┆ 260   ┆ 1966 │
│ Václavovič, Antonín,  ┆ Umění konstruovat               ┆ 189   ┆ 1966 │
│ Seidler, Alois        ┆ Tabulky normalizovaných závitů… ┆ 316   ┆ 1966 │
│ Beneš, Oldřich        ┆ 1111 nápadů pro motoristy a dí… ┆ 255   ┆ 1966 │
│ Frey, Jakub,          ┆ Loď, moře, námořníci            ┆ 209   ┆ 1967 │
│ Beneš, Oldřich        ┆ 1111 nápadů pro motoristy a dí… ┆ 254   ┆ 1967 │
│ Dobrovolný, Bohumil,  ┆ Nové matematické rekreace       ┆ 157   ┆ 1967 │
│ Budlovský, Jaroslav,  ┆ Motory                          ┆ 169   ┆ 1967 │
│ Nečásek, Sláva        ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Nečásek, Sláva        ┆ 100 praktických námětů z elekt… ┆ 172   ┆ 1967 │
│ Urban, Eduard         ┆ Mosty - jeden z divů světa      ┆ 146   ┆ 1967 │
│ Vykoukal, Rudolf,     ┆ Automobilové a motocyklové mot… ┆ 196   ┆ 1967 │
│ Seidler, Alois        ┆ Tabulky normalizovaných závitů… ┆ 318   ┆ 1967 │
│ Břízová, Joza,        ┆ Technika mění domácnost         ┆ 153   ┆ 1967 │
│ Šindelář, Václav,     ┆ Zopakujme si fyziku             ┆ 210   ┆ 1967 │
│ Batka, Vilém,         ┆ 100 příkladů z lineárních elek… ┆ 152   ┆ 1968 │
│ Čuma, Miroslav        ┆ Pokrokové způsoby ostření řezn… ┆ 133   ┆ 1968 │
│ Krňák, Rudolf         ┆ 500 novinek ze svařování - mal… ┆ 155   ┆ 1968 │
│ Jozífek, Vítězslav,   ┆ Počítáme na logaritmickém prav… ┆ 132   ┆ 1968 │
│ Gregora, Otakar,      ┆ Normy strojnického kreslení     ┆ 226   ┆ 1968 │
│ Slavíček, Ivan        ┆ Elektromotorky a jejich řízení  ┆ 237   ┆ 1968 │
│ Šimek, Jaroslav,      ┆ Fotografické techniky           ┆ 110   ┆ 1969 │
│ Zahradník, Josef      ┆ Lineární programování při říze… ┆ 231   ┆ 1969 │
│ Chalupský, Ladislav,  ┆ 100x o umělém osvětlení         ┆ 278   ┆ 1969 │
│ Johánek, Tomáš        ┆ 500 příkladů úsporného konstru… ┆ 122   ┆ 1969 │
│ Dobrovolný, Bohumil,  ┆ Automaty si děláme sami         ┆ 132   ┆ 1969 │
│ Tunys, Ladislav,      ┆ Film mění tvář                  ┆ 186   ┆ 1969 │
│ Klepl, Václav,        ┆ Jak číst schémata v radiotechn… ┆ 239   ┆ 1969 │
│ Kameník, Karel,       ┆ 8 mm film standard a super v p… ┆ 167   ┆ 1969 │
│ Karaus, Evžen,        ┆ Teplo našim domovům             ┆ 145   ┆ 1969 │
│ Paulín, Zdeněk        ┆ 100 zajímavostí z radiotechnik… ┆ 157   ┆ 1969 │
│ Dobrovolný, Bohumil,  ┆ Matematické rekreace            ┆ 131   ┆ 1969 │
│ Kulhánek, Jaroslav,   ┆ Fotografické tabulky            ┆ 216   ┆ 1970 │
│ Chytil, Metoděj       ┆ Zajímavá použití samočinných p… ┆ 131   ┆ 1970 │
│ Nečásek, Sláva        ┆ Výběr zajímavých zapojení       ┆ 256   ┆ 1970 │
│ Krištoufek, Karel,    ┆ Matematické stroje              ┆ 197   ┆ 1970 │
│ Slavíček, Ivan        ┆ 500 tranzistorových obvodů      ┆ 222   ┆ 1970 │
│ Batka, Vilém,         ┆ Elektromagnetismus              ┆ 157   ┆ 1970 │
│ Pavlík, Miloslav,     ┆ Recepty a rady pro dílny        ┆ 189   ┆ 1971 │
│ Opava, Zdeněk,        ┆ Jak sestrojovat spojnicové nom… ┆ 167   ┆ 1972 │
│ Ziegelheim, Otakar,   ┆ Obvody s křemíkovými diodami a… ┆ 174   ┆ 1973 │
│ Krutina, Jaroslav     ┆ Sbírka vzorců z pružnosti a pe… ┆ 234   ┆ 1973 │
│ Dobrovolný, Bohumil,  ┆ Dílenská matematika             ┆ 223   ┆ 1974 │
│ Peřina, František     ┆ Atomy slouží člověku            ┆ 108   ┆ 1976 │
│ Janda, Vladimír,      ┆ Integrovaná elektronika pro ka… ┆ 241   ┆ 1977 │
└───────────────────────┴─────────────────────────────────┴───────┴──────┘

In [101]:
zjisti("Pájení")

Praktické příručky Elektrotechnického Svazu Československého

shape: (10, 6)
┌───────────────────┬───────────────────────────┬───────────────────────────┬──────┬───────┬───────────────────────────┐
│ 100_a             ┆ 245_a                     ┆ 260_b                     ┆ rok  ┆ stran ┆ 490_a                     │
│ ---               ┆ ---                       ┆ ---                       ┆ ---  ┆ ---   ┆ ---                       │
│ str               ┆ str                       ┆ str                       ┆ i64  ┆ i64   ┆ str                       │
╞═══════════════════╪═══════════════════════════╪═══════════════════════════╪══════╪═══════╪═══════════════════════════╡
│ Slánský, Antonín  ┆ Pájení mědí elektrickým   ┆ Elektrotechnický svaz     ┆ 1947 ┆ 78    ┆ Praktické příručky        │
│                   ┆ teplem                    ┆ českoslo…                 ┆      ┆       ┆ Elektrotech…              │
│ Puchnar, Bedřich  ┆ Pájení a svařování, pájky ┆ Min. hutního prům. a      ┆ 1952 ┆ 89    ┆ null                      │
│                   ┆ a sv…                     ┆ rudných d…                ┆      ┆       ┆                           │
│ Němec, Karel      ┆ Pájení                    ┆ SNTL                      ┆ 1963 ┆ 50    ┆ Kurs technických znalostí │
│ Karlík, Pavel     ┆ Pájení ve sdělovací       ┆ SNTL                      ┆ 1967 ┆ 147   ┆ Elektrotechnická minima   │
│                   ┆ elektrotec…               ┆                           ┆      ┆       ┆                           │
│ Karlík, Pavel     ┆ Pájení ve sdělovací       ┆ SNTL                      ┆ 1967 ┆ 147   ┆ Řada elektrotechn. lit    │
│                   ┆ elektrotec…               ┆                           ┆      ┆       ┆                           │
│ Němec, Karel      ┆ Pájení                    ┆ SNTL                      ┆ 1970 ┆ 59    ┆ Kurs technických znalostí │
│ Ruža, Viliam      ┆ Pájení                    ┆ SNTL - Nakladatelství     ┆ 1978 ┆ 395   ┆ Řada strojírenské         │
│                   ┆                           ┆ technick…                 ┆      ┆       ┆ literatury                │
│ Ruža, Viliam      ┆ Pájení                    ┆ SNTL                      ┆ 1988 ┆ 452   ┆ null                      │
│ Ruža, Viliam      ┆ Pájení                    ┆ Alfa                      ┆ 1988 ┆ 452   ┆ null                      │
│ Martínek, Antonín ┆ Pájení v elektronice      ┆ Tesla-Výzkumný ústav pro  ┆ 1990 ┆ 245   ┆ Technické příručky /      │
│                   ┆                           ┆ sdělo…                    ┆      ┆       ┆ Tesla, Vý…                │
└───────────────────┴───────────────────────────┴───────────────────────────┴──────┴───────┴───────────────────────────┘

In [103]:
edice("Kurs technických znalostí")

shape: (73, 4)
┌────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                  ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                    ┆ ---                             ┆ ---   ┆ ---  │
│ str                    ┆ str                             ┆ i64   ┆ i64  │
╞════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Němec, Josef           ┆ Svařování elektrickým obloukem  ┆ 75    ┆ 1960 │
│ Řeháček, Emil          ┆ Malá energetika                 ┆ 71    ┆ 1960 │
│ Dobrovolný, Bohumil,   ┆ Pilování                        ┆ 82    ┆ 1960 │
│ Řeháček, Emil          ┆ Základy elektrotechniky         ┆ 78    ┆ 1960 │
│ Mazurek, Alois,        ┆ Technická fyzika                ┆ 97    ┆ 1960 │
│ Dobrovolný, Bohumil,   ┆ Soustružení kovů                ┆ 82    ┆ 1961 │
│ Mazurek, Alois,        ┆ Technologie přesné optiky       ┆ 76    ┆ 1961 │
│ Němec, Josef           ┆ Svařování elektrickým obloukem  ┆ 84    ┆ 1961 │
│ Němec, Karel           ┆ Montážní práce ve strojírenstv… ┆ 77    ┆ 1961 │
│ Němec, Karel           ┆ Přehled strojních součástí      ┆ 66    ┆ 1961 │
│ Chýle, Vladimír        ┆ Ostření řezných nástrojů        ┆ 82    ┆ 1961 │
│ Šindelář, Václav,      ┆ Automatizace měření             ┆ 79    ┆ 1961 │
│ Outrata, Jiří,         ┆ Práce na revolverovém soustruh… ┆ 101   ┆ 1961 │
│ Schück, Karel          ┆ Mechanizace ručních prací ve s… ┆ 103   ┆ 1961 │
│ Beneš, Jiří,           ┆ Organizace zlepšovatelství      ┆ 79    ┆ 1962 │
│ Beneš, Oldřich         ┆ Seřizování vozidlových motorů   ┆ 86    ┆ 1962 │
│ Pytlíček, Dušan        ┆ Odlévání ocelových ingotů       ┆ 113   ┆ 1962 │
│ Blabolil, František    ┆ Zpracování plastických hmot     ┆ 93    ┆ 1962 │
│ Outrata, Jiří,         ┆ Výroba přesných měřidel         ┆ 82    ┆ 1962 │
│ Outrata, Jiří,         ┆ Základy obrábění kovů           ┆ 54    ┆ 1962 │
│ Píč, Josef,            ┆ Programové řízení obráběcích s… ┆ 65    ┆ 1962 │
│ Dobrovolný, Bohumil,   ┆ Motory a pracovní stroje        ┆ 100   ┆ 1962 │
│ Řeháček, Emil          ┆ Základy elektrotechniky         ┆ 91    ┆ 1962 │
│ Doškář, Josef,         ┆ Základy galvanotechniky         ┆ 68    ┆ 1963 │
│ Řeháček, Emil          ┆ Malá energetika                 ┆ 77    ┆ 1963 │
│ Němec, Karel           ┆ Pájení                          ┆ 50    ┆ 1963 │
│ Mazurek, Alois,        ┆ Technická fyzika                ┆ 109   ┆ 1963 │
│ Outrata, Jiří,         ┆ Práce na vodorovných obrážečká… ┆ 88    ┆ 1963 │
│ Řeháček, Emil          ┆ Obsluha jeřábů                  ┆ 87    ┆ 1963 │
│ Mazurek, Alois,        ┆ Technická fyzika                ┆ 88    ┆ 1963 │
│ Outrata, Jiří,         ┆ Dlouhotočné automaty            ┆ 103   ┆ 1963 │
│ Beutl, Karel           ┆ Přípravky pro obrábění          ┆ 67    ┆ 1963 │
│ Odehnal, Josef         ┆ Hluboké tažení                  ┆ 100   ┆ 1963 │
│ Outrata, Jiří,         ┆ Práce na dlouhotočných automat… ┆ 111   ┆ 1963 │
│ Novák, Vítězslav       ┆ Technické kreslení              ┆ 71    ┆ 1963 │
│ Binko, Jaroslav        ┆ Fyzikální a technické veličiny  ┆ 134   ┆ 1964 │
│ Mrázek, Vilém          ┆ Matematické stroje              ┆ 96    ┆ 1964 │
│ Nováček, Jaroslav      ┆ Potrubářství                    ┆ 79    ┆ 1964 │
│ Němec, Josef           ┆ Svařování elektrickým obloukem  ┆ 87    ┆ 1964 │
│ Hájek, Ludvík          ┆ Leptání                         ┆ 77    ┆ 1964 │
│ Dítě, Karel            ┆ Základní práce s plechy         ┆ 86    ┆ 1964 │
│ Musil, Rudolf          ┆ Střídavý proud                  ┆ 85    ┆ 1964 │
│ Oppl, Zdeněk           ┆ Mechanika                       ┆ 99    ┆ 1964 │
│ Paleček, Jaroslav      ┆ Vzduchotechnická zařízení       ┆ 84    ┆ 1964 │
│ Němec, Karel           ┆ Montážní práce ve strojírenstv… ┆ 92    ┆ 1964 │
│ Kovanda, Jan           ┆ Přístroje pro měření fyzikální… ┆ 108   ┆ 1965 │
│ Blažek, Václav         ┆ Strojní obrábění dřeva          ┆ 76    ┆ 1965 │
│ Mazurek, Alois,        ┆ Přístrojová optika              ┆ 84    ┆ 1965 │
│ Mazurek, Alois,        ┆ Základy technické optiky        ┆ 88    ┆ 1965 │
│ Pokorný, Adolf Gustav, ┆ Technologie práškových kovů     ┆ 87    ┆ 1965 │
│ Oravský, Hieronym,     ┆ Stavební práce klempířské       ┆ 80    ┆ 1965 │
│ Schönbach, Ladislav    ┆ Stavební čalounictví            ┆ 79    ┆ 1965 │
│ Konečný, František,    ┆ Tolerance a lícování            ┆ 103   ┆ 1965 │
│ Dobrovolný, Bohumil,   ┆ Technické kreslení ve strojíre… ┆ 99    ┆ 1965 │
│ Hrbek, Vladimír,       ┆ Transformátory                  ┆ 88    ┆ 1966 │
│ Fetter, František,     ┆ Asynchronní motory              ┆ 79    ┆ 1966 │
│ Pendl, Karel           ┆ Zedník                          ┆ 156   ┆ 1966 │
│ Outrata, Jiří,         ┆ Práce na revolverových automat… ┆ 109   ┆ 1966 │
│ Martínek, Zdeněk,      ┆ Základy hodinářství             ┆ 117   ┆ 1968 │
│ Dítě, Karel            ┆ Základní práce s plechy         ┆ 86    ┆ 1969 │
│ Paleček, Jaroslav      ┆ Vzduchotechnická zařízení       ┆ 84    ┆ 1969 │
│ Blažek, Václav         ┆ Strojní obrábění dřeva          ┆ 75    ┆ 1970 │
│ Hrbek, Antonín,        ┆ Slévárenství                    ┆ 136   ┆ 1970 │
│ Němec, Karel           ┆ Pájení                          ┆ 59    ┆ 1970 │
│ Kříž, Václav           ┆ Svařování plamenem              ┆ 117   ┆ 1970 │
│ Chýle, Vladimír        ┆ Ostření řezných nástrojů a jej… ┆ 159   ┆ 1970 │
│ Blažek, Václav         ┆ Ruční obrábění dřeva            ┆ 74    ┆ 1971 │
│ Oravský, Hieronym,     ┆ Stavební práce klempířské       ┆ 113   ┆ 1971 │
│ Dobrovolný, Bohumil,   ┆ Strojní zámečnictví             ┆ 87    ┆ 1971 │
│ Paleček, Jaroslav      ┆ Vzduchotechnická zařízení       ┆ 84    ┆ 1971 │
│ Dítě, Karel            ┆ Základní práce s plechy         ┆ 86    ┆ 1972 │
│ Lebr, Jindřich         ┆ Vytápění pro 1. a 2. ročník OU… ┆ 112   ┆ 1974 │
│ Tybor, Josef           ┆ Pákové váhy                     ┆ 281   ┆ 1977 │
└────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [105]:
zjisti("Náš les")

None

shape: (8, 6)
┌────────────────────┬─────────────────────┬───────────────────┬──────┬───────┬───────┐
│ 100_a              ┆ 245_a               ┆ 260_b             ┆ rok  ┆ stran ┆ 490_a │
│ ---                ┆ ---                 ┆ ---               ┆ ---  ┆ ---   ┆ ---   │
│ str                ┆ str                 ┆ str               ┆ i64  ┆ i64   ┆ str   │
╞════════════════════╪═════════════════════╪═══════════════════╪══════╪═══════╪═══════╡
│ Odehnal, Ivo,      ┆ Náš les             ┆ Junior            ┆ null ┆ 8     ┆ null  │
│ Šiman, Karel,      ┆ Náš lesnický Slavín ┆ nákladem vlastním ┆ 1943 ┆ 7     ┆ null  │
│ Patočka, Karel,    ┆ Náš les             ┆ Albatros          ┆ 1974 ┆ 357   ┆ Oko   │
│ Patočka, Karel,    ┆ Náš les             ┆ Albatros          ┆ 1989 ┆ 395   ┆ Oko   │
│ Lockerová, Jiřina, ┆ Náš les a louka     ┆ Axióma            ┆ 1997 ┆ 1     ┆ null  │
│ Patočka, Karel,    ┆ Náš les             ┆ Albatros          ┆ 2007 ┆ 1     ┆ Oko   │
│ Kovalčík, Václav   ┆ Náš lesopark        ┆ Nová Forma        ┆ 2010 ┆ 55    ┆ null  │
│ Kovalčík, Václav   ┆ Náš lesopark 2      ┆ Nová Forma        ┆ 2011 ┆ 63    ┆ null  │
└────────────────────┴─────────────────────┴───────────────────┴──────┴───────┴───────┘

In [107]:
edice("Oko")

shape: (146, 4)
┌───────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                         ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                           ┆ ---                             ┆ ---   ┆ ---  │
│ str                           ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Spirhanzl-Duriš, Jaroslav,    ┆ Z ptačí říše                    ┆ 31    ┆ 1961 │
│ Patočka, Karel,               ┆ Kouzla s rostlinami             ┆ 251   ┆ 1961 │
│ Zapletal, Miloš,              ┆ Tisíc malých dobrodružství      ┆ 345   ┆ 1961 │
│ Zapletal, Miloš,              ┆ Tisíc malých dobrodružství      ┆ 284   ┆ 1961 │
│ Bodláková, Jitka,             ┆ Dneska vařím já                 ┆ 243   ┆ 1962 │
│ Elstner, František Alexander, ┆ Dovedu to!                      ┆ 272   ┆ 1962 │
│ Vodinský, Stanislav,          ┆ Ryby našich vod                 ┆ 285   ┆ 1962 │
│ Patočka, Karel,               ┆ Kouzla se zvířaty               ┆ 282   ┆ 1963 │
│ Jist, Adam,                   ┆ Nejen zlatá jablka              ┆ 230   ┆ 1963 │
│ Feuerstein, Karel             ┆ Letadla včera, dnes a zítra     ┆ 230   ┆ 1963 │
│ Mařan, Josef,                 ┆ Naši brouci                     ┆ 405   ┆ 1963 │
│ Zapletal, Miloš,              ┆ Kouzelné brýle                  ┆ 174   ┆ 1963 │
│ Pálka, Ondřej,                ┆ Rozum do kapsy                  ┆ 347   ┆ 1964 │
│ Louda, Jiří,                  ┆ Česká města                     ┆ 369   ┆ 1964 │
│ Vydra, Jindřich,              ┆ Divotvorné krabičky             ┆ 373   ┆ 1964 │
│ Hlavatý, Miloslav             ┆ Svět na kolejích                ┆ 347   ┆ 1964 │
│ Čajda, Ivan,                  ┆ Chemik detektivem               ┆ 281   ┆ 1964 │
│ Spirhanzl-Duriš, Jaroslav,    ┆ Z ptačí říše                    ┆ 242   ┆ 1965 │
│ Öveges, József,               ┆ Fyzikální kratochvíle           ┆ 290   ┆ 1965 │
│ Kotlaba, František,           ┆ Naše houby                      ┆ 306   ┆ 1965 │
│ Elstner, František Alexander, ┆ Dobrodružnou stezkou            ┆ 301   ┆ 1965 │
│ Elstner, František Alexander, ┆ Dobrodružnou stezkou            ┆ 368   ┆ 1965 │
│ Vodinský, Stanislav,          ┆ Ryby našich vod                 ┆ 293   ┆ 1965 │
│ Bodláková, Jitka,             ┆ Dneska vařím já                 ┆ 286   ┆ 1966 │
│ Kouřimský, Jiří,              ┆ Naše nerosty                    ┆ 350   ┆ 1966 │
│ Strouhal, Josef,              ┆ Hádej, hádej, hádači            ┆ 186   ┆ 1966 │
│ Dudek, Oldřich,               ┆ Sport a hry                     ┆ 321   ┆ 1967 │
│ Šmíd, Mirko                   ┆ Lodi včera, dnes a zítra        ┆ 340   ┆ 1968 │
│ Maier-Puschi, Kolma           ┆ Šach mat                        ┆ 218   ┆ 1968 │
│ Mezera, Alois,                ┆ Naše stromy a keře              ┆ 429   ┆ 1969 │
│ Elstner, František Alexander, ┆ Automobily včera, dnes a zítra  ┆ 362   ┆ 1969 │
│ Hanzák, Jan,                  ┆ Naši savci                      ┆ 347   ┆ 1970 │
│ Jirásek, Václav,              ┆ Rostliny známé neznámé          ┆ 308   ┆ 1970 │
│ Klapetek, Josef               ┆ Abrakadabra                     ┆ 264   ┆ 1970 │
│ Kotlaba, František,           ┆ Naše houby                      ┆ 349   ┆ 1972 │
│ Zapletal, Miloš,              ┆ Kouzelné brýle                  ┆ 182   ┆ 1972 │
│ Klement, Miloslav,            ┆ Hudební nástroje                ┆ 172   ┆ 1972 │
│ Mařan, Josef,                 ┆ Naši brouci                     ┆ 398   ┆ 1972 │
│ Vaculín, Ivo,                 ┆ Vyberte si pejska               ┆ 366   ┆ 1972 │
│ Kleczek, Josip,               ┆ Naše souhvězdí                  ┆ 374   ┆ 1973 │
│ Pálka, Ondřej,                ┆ Rozum do kapsy                  ┆ 387   ┆ 1973 │
│ Moucha, Josef,                ┆ Naši denní motýli               ┆ 228   ┆ 1973 │
│ Patočka, Karel,               ┆ Náš les                         ┆ 357   ┆ 1974 │
│ Janáček, Josef,               ┆ České erby                      ┆ 221   ┆ 1974 │
│ Louda, Jiří,                  ┆ Česká města                     ┆ 378   ┆ 1974 │
│ Kyzlink, Jaroslav             ┆ Sestroj si sám                  ┆ 238   ┆ 1974 │
│ Herout, Jaroslav,             ┆ Naše stavební památky           ┆ 508   ┆ 1975 │
│ Moucha, Josef,                ┆ Naši noční motýli               ┆ 369   ┆ 1975 │
│ Letošníková, Ludiše,          ┆ Zbraně, střelci, puškaři        ┆ 332   ┆ 1975 │
│ Toufar, Pavel,                ┆ Cesty ke hvězdám                ┆ 368   ┆ 1976 │
│ Čihař, Jiří,                  ┆ Naše hory                       ┆ 316   ┆ 1976 │
│ Toufar, Pavel,                ┆ Svět dopravních letadel         ┆ 176   ┆ 1976 │
│ Pálka, Ondřej,                ┆ Rozum do kapsy                  ┆ 479   ┆ 1977 │
│ Šubrt, Josef,                 ┆ Vlajky a znaky celého světa     ┆ 183   ┆ 1977 │
│ Kyzlink, Jaroslav             ┆ Sestroj si doma                 ┆ 296   ┆ 1977 │
│ Spirhanzl-Duriš, Jaroslav,    ┆ Z ptačí říše                    ┆ 253   ┆ 1978 │
│ Kleczek, Josip,               ┆ Naše souhvězdí                  ┆ 404   ┆ 1978 │
│ Čihař, Jiří,                  ┆ Naše přehrady                   ┆ 255   ┆ 1978 │
│ Šorel, Václav,                ┆ Letadla československých pilot… ┆ 430   ┆ 1979 │
│ Moucha, Josef,                ┆ Naši denní motýli               ┆ 228   ┆ 1980 │
│ Sklenář, Karel,               ┆ Od pěstního klínu k Přemyslově… ┆ 481   ┆ 1981 │
│ Zahradník, Jiří,              ┆ Náš hmyz                        ┆ 444   ┆ 1981 │
│ Kotlaba, František,           ┆ Naše houby                      ┆ 373   ┆ 1982 │
│ Kouřimský, Jiří,              ┆ Naše nerostné bohatství         ┆ 460   ┆ 1982 │
│ Šolc, Václav,                 ┆ Indiánskou stezkou              ┆ 292   ┆ 1982 │
│ Šorel, Václav,                ┆ Letadla československých pilot… ┆ 246   ┆ 1982 │
│ Čajda, Ivan,                  ┆ Chemik detektivem               ┆ 255   ┆ 1982 │
│ Letošníková, Ludiše,          ┆ Zbraně, šerm a mečíři           ┆ 375   ┆ 1983 │
│ Langer, Jiří,                 ┆ Naše lidové stavby              ┆ 348   ┆ 1983 │
│ Louda, Jiří,                  ┆ Česká města II                  ┆ 380   ┆ 1983 │
│ Losos, Ludvík,                ┆ Dějiny městské dopravy          ┆ 296   ┆ 1983 │
│ Novák, Jan,                   ┆ Naše jedovaté rostliny          ┆ 213   ┆ 1984 │
│ Durdík, Tomáš,                ┆ České hrady                     ┆ 397   ┆ 1984 │
│ Altmann, Antonín,             ┆ Mořská fauna a flóra            ┆ 302   ┆ 1984 │
│ Kleczek, Josip,               ┆ Naše Slunce                     ┆ 299   ┆ 1984 │
│ Jirásek, Václav,              ┆ Rostliny známé neznámé          ┆ 302   ┆ 1985 │
│ Buben, Milan,                 ┆ Heraldika                       ┆ 317   ┆ 1986 │
│ Kleczek, Josip,               ┆ Naše souhvězdí                  ┆ 413   ┆ 1986 │
│ Vaculín, Ivo,                 ┆ Vyberte si pejska               ┆ 396   ┆ 1986 │
│ Koudelková, Jarmila           ┆ Naše dějiny v datech            ┆ 474   ┆ 1987 │
│ Zahradník, Jiří,              ┆ Náš hmyz                        ┆ 445   ┆ 1987 │
│ Spirhanzl-Duriš, Jaroslav,    ┆ Z ptačí říše                    ┆ 310   ┆ 1987 │
│ Seger, Jiří                   ┆ Jak se lidé dorozumívali        ┆ 332   ┆ 1987 │
│ Opravil, Emanuel,             ┆ Jak rostliny cestují            ┆ 324   ┆ 1987 │
│ Hanousek, Ivan,               ┆ Naši slavní sportovci           ┆ 414   ┆ 1987 │
│ Janáček, Josef,               ┆ České erby                      ┆ 367   ┆ 1988 │
│ Koubský, Pavel,               ┆ Planety naší sluneční soustavy  ┆ 363   ┆ 1988 │
│ Patočka, Karel,               ┆ Náš les                         ┆ 395   ┆ 1989 │
│ Škňouřil, Evžen,              ┆ Hlavní města Evropy             ┆ 414   ┆ 1989 │
│ Vodinský, Stanislav,          ┆ Ryby našich vod                 ┆ 377   ┆ 1989 │
│ Letošníková, Ludiše,          ┆ Zbraně, šerm a mečíři           ┆ 375   ┆ 1989 │
│ Koudelková, Jarmila           ┆ Naše dějiny v datech            ┆ 474   ┆ 1989 │
│ Mezera, Alois,                ┆ Naše stromy a keře              ┆ 426   ┆ 1989 │
│ Klégr, Aleš,                  ┆ Světem jazyků                   ┆ 522   ┆ 1989 │
│ Kleczek, Josip,               ┆ Naše souhvězdí                  ┆ 412   ┆ 1994 │
│ Zahradník, Jiří,              ┆ Naši motýli                     ┆ 457   ┆ 1997 │
│ Škňouřil, Evžen,              ┆ Hlavní města Evropy             ┆ 406   ┆ 1998 │
│ Pernes, Jiří,                 ┆ České dějiny v datech           ┆ 278   ┆ 1998 │
│ Flegl, Václav                 ┆ Malý průvodce olympijskými spo… ┆ 369   ┆ 1999 │
│ Kleczek, Josip,               ┆ Naše souhvězdí                  ┆ 412   ┆ 2000 │
│ Kubeš, Vladimír               ┆ Malá tábornická encyklopedie    ┆ 334   ┆ 2000 │
│ Pernes, Jiří,                 ┆ Evropské dějiny v datech        ┆ 343   ┆ 2000 │
│ Kleczek, Josip,               ┆ Energie                         ┆ 317   ┆ 2002 │
│ Pavličová, Šárka,             ┆ Dnes vařím já                   ┆ 302   ┆ 2002 │
│ Škňouřil, Evžen,              ┆ Hlavní města světa              ┆ 651   ┆ 2002 │
│ Kubeš, Vladimír               ┆ Malá tábornická encyklopedie    ┆ 334   ┆ 2003 │
│ Pernes, Jiří,                 ┆ České dějiny v datech           ┆ 290   ┆ 2003 │
│ Škňouřil, Evžen,              ┆ Hlavní města Evropy             ┆ 406   ┆ 2004 │
│ Smrčková, Lea,                ┆ Pes pro mě                      ┆ 530   ┆ 2004 │
│ Kotlaba, František,           ┆ Naše houby                      ┆ 335   ┆ 2004 │
│ Vondrušková, Alena,           ┆ České zvyky a obyčeje           ┆ 370   ┆ 2004 │
│ Havel, Jan                    ┆ Peníze do kapsy                 ┆ 455   ┆ 2004 │
│ Kleczek, Josip,               ┆ Náš vesmír                      ┆ 580   ┆ 2005 │
│ Smrček, Martin,               ┆ Naši ptáci                      ┆ 429   ┆ 2005 │
│ Haškovec, Vít,                ┆ Svět v souvislostech            ┆ 415   ┆ 2005 │
│ Záruba, Bořivoj,              ┆ 777+1 zajímavost z historie Ze… ┆ 369   ┆ 2005 │
│ Martínek, Miloslav,           ┆ Čeští cestovatelé a mořeplavci  ┆ 399   ┆ 2006 │
│ Vondruška, Pavel,             ┆ Kryptologie, šifrování a tajná… ┆ 340   ┆ 2006 │
│ Vondruška, Vlastimil,         ┆ Život ve středověku             ┆ 398   ┆ 2007 │
│ Kubeš, Vladimír               ┆ Knížka poslední záchrany        ┆ 285   ┆ 2007 │
│ Bulisová, Jiřina              ┆ Kapesní svět                    ┆ 262   ┆ 2007 │
│ Buben, Milan,                 ┆ Heraldika                       ┆ 1     ┆ 2007 │
│ Šorel, Václav,                ┆ Letadla československých pilot… ┆ 1     ┆ 2007 │
│ Altmann, Antonín,             ┆ Mořská fauna a flóra            ┆ 1     ┆ 2007 │
│ Patočka, Karel,               ┆ Náš les                         ┆ 1     ┆ 2007 │
│ Kotlaba, František,           ┆ Naše houby                      ┆ 1     ┆ 2007 │
│ Kleczek, Josip,               ┆ Naše souhvězdí                  ┆ 1     ┆ 2007 │
│ Hanzák, Jan,                  ┆ Naši savci                      ┆ 1     ┆ 2008 │
│ Herout, Jaroslav,             ┆ Naše stavební památky           ┆ 1     ┆ 2008 │
│ Letošníková, Ludiše,          ┆ Zbraně, šerm a mečíři           ┆ 1     ┆ 2008 │
│ Pernes, Jiří,                 ┆ České dějiny v datech           ┆ 295   ┆ 2008 │
│ Pavličová, Šárka,             ┆ Dnes vařím já                   ┆ 302   ┆ 2008 │
│ Durdík, Tomáš,                ┆ České hrady                     ┆ 382   ┆ 2008 │
│ Zahradník, Jiří,              ┆ Naši motýli                     ┆ 1     ┆ 2008 │
│ Toufar, Pavel,                ┆ Cesty ke hvězdám                ┆ 1     ┆ 2008 │
│ Zahradník, Jiří,              ┆ Náš hmyz                        ┆ 1     ┆ 2008 │
│ Novák, Jan,                   ┆ Naše jedovaté rostliny          ┆ 1     ┆ 2008 │
│ Vodinský, Stanislav,          ┆ Ryby našich vod                 ┆ 1     ┆ 2008 │
│ Losos, Ludvík,                ┆ Dějiny městské dopravy          ┆ 1     ┆ 2008 │
│ Zahradník, Jiří,              ┆ Naši motýli                     ┆ 457   ┆ 2009 │
│ Kleczek, Josip,               ┆ Náš vesmír                      ┆ 1     ┆ 2009 │
│ Smrček, Martin,               ┆ Exotičtí ptáci a jejich chov    ┆ 414   ┆ 2010 │
│ Vondrušková, Alena,           ┆ Rodinné svátky a oslavy         ┆ 339   ┆ 2010 │
│ Záruba, Bořivoj,              ┆ 777+1 zajímavost z historie Ze… ┆ 1     ┆ 2010 │
│ Kleczek, Josip,               ┆ Energie ve vesmíru a ve službá… ┆ 1     ┆ 2012 │
│ Strouhal, Josef,              ┆ Hádej, hádej, hadači            ┆ 187   ┆ 2019 │
└───────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [109]:
zjisti("Jak s tím pohnu")

Krystal

shape: (1, 6)
┌────────────────────┬─────────────────┬───────┬──────┬───────┬─────────┐
│ 100_a              ┆ 245_a           ┆ 260_b ┆ rok  ┆ stran ┆ 490_a   │
│ ---                ┆ ---             ┆ ---   ┆ ---  ┆ ---   ┆ ---     │
│ str                ┆ str             ┆ str   ┆ i64  ┆ i64   ┆ str     │
╞════════════════════╪═════════════════╪═══════╪══════╪═══════╪═════════╡
│ Houška, Vítězslav, ┆ Jak s tím pohnu ┆ SNDK  ┆ 1965 ┆ 188   ┆ Krystal │
└────────────────────┴─────────────────┴───────┴──────┴───────┴─────────┘

In [111]:
help(edice)

Help on function edice in module __main__:

edice(retezec, nakladatelstvi=None)

In [113]:
edice("Krystal",nakladatelstvi="SNDK")

shape: (10, 5)
┌───────────────────────────────┬───────────────────────┬────────────────┬──────┬───────┐
│ 100_a                         ┆ 245_a                 ┆ 300_a          ┆ rok  ┆ stran │
│ ---                           ┆ ---                   ┆ ---            ┆ ---  ┆ ---   │
│ str                           ┆ str                   ┆ str            ┆ i64  ┆ i64   │
╞═══════════════════════════════╪═══════════════════════╪════════════════╪══════╪═══════╡
│ Adla, Zdeněk,                 ┆ Krásná a slavná       ┆ 257, [7] s. :  ┆ 1961 ┆ 257   │
│ Bojarová, Olga,               ┆ Od hlavy k patě       ┆ 186, [6] s. ;  ┆ 1961 ┆ 186   │
│ Petr, Tomislav,               ┆ Divy oceánů           ┆ 174 s. :       ┆ 1962 ┆ 174   │
│ Koval, Václav,                ┆ Na dně vzdušného moře ┆ 221, [4] s. ;  ┆ 1962 ┆ 221   │
│ Štuka, Ivo,                   ┆ Šest dnů na luně 1    ┆ 200, [3] s. ;  ┆ 1963 ┆ 200   │
│ Houška, Vítězslav,            ┆ Jak s tím pohnu       ┆ 188 s. ;       ┆ 1965 ┆ 188   │
│ Tichý, Jaroslav,              ┆ Letem ČSSR            ┆ 214, [6] s. ;  ┆ 1965 ┆ 214   │
│ Elstner, František Alexander, ┆ Motorové opojení      ┆ 207, [5] s. ;  ┆ 1966 ┆ 207   │
│ Deyl, Václav,                 ┆ Tajemství plamenů     ┆ 185, [7] s. :  ┆ 1967 ┆ 185   │
│ Hons, Josef,                  ┆ A štafeta běží dál    ┆ 214, [34] s. : ┆ 1967 ┆ 214   │
└───────────────────────────────┴───────────────────────┴────────────────┴──────┴───────┘

In [115]:
zjisti("Pět olympijských kruhů")

None

shape: (1, 6)
┌──────────────────┬────────────────────────┬───────┬──────┬───────┬───────┐
│ 100_a            ┆ 245_a                  ┆ 260_b ┆ rok  ┆ stran ┆ 490_a │
│ ---              ┆ ---                    ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str              ┆ str                    ┆ str   ┆ i64  ┆ i64   ┆ str   │
╞══════════════════╪════════════════════════╪═══════╪══════╪═══════╪═══════╡
│ Zapletal, Miloš, ┆ Pět olympijských kruhů ┆ STN   ┆ 1964 ┆ 426   ┆ null  │
└──────────────────┴────────────────────────┴───────┴──────┴───────┴───────┘

In [121]:
df.filter(pl.col("260_b") == "STN").group_by(["100_a","245_a"]).len().sort(by="len",descending=True)

shape: (731, 3)
┌─────────────────────────────────┬─────────────────────────────────┬─────┐
│ 100_a                           ┆ 245_a                           ┆ len │
│ ---                             ┆ ---                             ┆ --- │
│ str                             ┆ str                             ┆ u32 │
╞═════════════════════════════════╪═════════════════════════════════╪═════╡
│ Svoboda, Alois,                 ┆ Prag                            ┆ 4   │
│ Žanda, Václav František         ┆ Karlovy Vary                    ┆ 4   │
│ Hlaváček, Miroslav,             ┆ Turistika                       ┆ 3   │
│ Bartušek, Antonín,              ┆ Buchlov                         ┆ 3   │
│ Pachman, Luděk,                 ┆ Theorie moderního šachu         ┆ 3   │
│ Pithart, František,             ┆ Základy šachu                   ┆ 3   │
│ Mrňák, Václav                   ┆ Kuželky                         ┆ 3   │
│ Sedláčková, Ema,                ┆ Lednice                         ┆ 3   │
│ Vaněk, Jan,                     ┆ Pozemní hokej                   ┆ 2   │
│ Höhm, Jindřich,                 ┆ Tenis                           ┆ 2   │
│ Bašta, Ladislav                 ┆ Zlatá brána                     ┆ 2   │
│ Doležal, Jiří,                  ┆ Hrady a zámky ČSSR              ┆ 2   │
│ Vacková, Jarmila                ┆ Kroměříž                        ┆ 2   │
│ Král, Josef,                    ┆ Průvodce zoologickou zahradou … ┆ 2   │
│ Vinařický, Richard,             ┆ Zásady správné výživy sportovc… ┆ 2   │
│ Kožík, František,               ┆ Synové hor                      ┆ 2   │
│ Man, František,                 ┆ Svazarm - lidová, masová a dob… ┆ 2   │
│ Müller, Emil                    ┆ Kulturistika                    ┆ 2   │
│ Navrátilová, Hana               ┆ Francie                         ┆ 2   │
│ Šulc, Jan,                      ┆ Vodní slalom                    ┆ 2   │
│ Kotov, Aleksandr Aleksandrovič… ┆ Alechinův šachový odkaz         ┆ 2   │
│ Zdeněk, Dalibor,                ┆ Pohybové hry                    ┆ 2   │
│ Děták, Jaroslav,                ┆ Hluboká nad Vltavou a okolí     ┆ 2   │
│ Berdychová, Jana,               ┆ Dětské taneční hry              ┆ 2   │
│ Žižka, Jiří                     ┆ Pořadová cvičení                ┆ 2   │
│ Babica, Josef                   ┆ Za vítězstvím                   ┆ 2   │
│ Dědič, Josef,                   ┆ Krasobruslení pro rozhodčí a t… ┆ 2   │
│ Purkyně, Cyril,                 ┆ Zoo Praha                       ┆ 2   │
│ Duda, Ivo                       ┆ Mladý turista ČSSR              ┆ 2   │
│ Houdek, Igor                    ┆ Zimní nebezpečí v horách        ┆ 2   │
│ Bušek, Bedřich                  ┆ Beskydy a Ostravsko             ┆ 2   │
│ Serbus, Ladislav,               ┆ Přes překážky                   ┆ 2   │
│ Novický, Oldřich,               ┆ Mexiko - země 19. her letní ol… ┆ 2   │
│ Kuchař, Radovan,                ┆ Deset velkých stěn              ┆ 2   │
│ Hilmera, Jiří,                  ┆ Domažlice                       ┆ 2   │
│ Kýhos, Karel                    ┆ Praha                           ┆ 2   │
│ Trefný, Zdeněk,                 ┆ Lehkoatletické bodovací tabulk… ┆ 2   │
│ Wirth, Zdeněk,                  ┆ Ratibořice                      ┆ 2   │
│ Oskolkova, Valentina Andrejevn… ┆ Vzorové treningové hodiny odbí… ┆ 2   │
│ Mojžíšová, Věra                 ┆ Jaro země mé                    ┆ 2   │
│ Smlsal, František               ┆ Mapa a kompas                   ┆ 2   │
│ Čivrný, Čestmír                 ┆ Šerm                            ┆ 2   │
│ Zapletal, Miloš,                ┆ Hry v přírodě                   ┆ 2   │
│ Michalička, Vlastimil,          ┆ Zimní turistika                 ┆ 2   │
│ Hlaváč, Lumír                   ┆ Dolní Posázaví                  ┆ 2   │
│ Brzák, František,               ┆ Stavba kanoí a kajaků           ┆ 2   │
│ Dostál, Emil,                   ┆ Lehká atletika                  ┆ 2   │
│ Kroutil, František,             ┆ Mezinárodní olympijské řády     ┆ 2   │
│ Hanč, Jan,                      ┆ Sprinty                         ┆ 2   │
│ Berdychová, Jana,               ┆ Na sluníčku                     ┆ 2   │
│ Pešková, Lída                   ┆ Zpěv míru                       ┆ 2   │
│ Drobná, Zoroslava,              ┆ Karlův most                     ┆ 2   │
│ Sláma, Zdeněk,                  ┆ Ragby                           ┆ 2   │
│ Kos, Bohumil,                   ┆ Účelová gymnastika sportovce    ┆ 2   │
│ Pešina, Jaroslav,               ┆ Hradní kaple na Švihově         ┆ 2   │
│ Vahala, Miroslav                ┆ Brno                            ┆ 2   │
│ Svoboda, Alois,                 ┆ Prague                          ┆ 2   │
│ Špičková-Matoušková, Marie      ┆ Polka s ošatkami (pro 12-18 cv… ┆ 1   │
│ Adamec, Quido                   ┆ Pravidla ledního hokeje         ┆ 1   │
│ Draxl, Miloslav,                ┆ Letní putování mladých vodáků   ┆ 1   │
│ Wollmann, František             ┆ Na zájezd po Šumavě             ┆ 1   │
│ Vorel, Stanislav,               ┆ Pojeďte s námi na vodu!         ┆ 1   │
│ Lebeda, Adolf Andrej,           ┆ Branný zápas judo               ┆ 1   │
│ Sarkizov-Serazini, Ivan Michaj… ┆ Cesta ke zdraví, síle a dlouhé… ┆ 1   │
│ Holub, Dalibor                  ┆ Chodsko                         ┆ 1   │
│ Belšan, Pavel,                  ┆ Sportovní filmy a filmové smyč… ┆ 1   │
│ Šamánková, Eva,                 ┆ Český Krumlov                   ┆ 1   │
│ Krupička, Jiří                  ┆ Junior                          ┆ 1   │
│ Rybár, Ctibor,                  ┆ Im Rhythmus der Schönheit und … ┆ 1   │
│ Vahala, Miroslav                ┆ Táboření                        ┆ 1   │
│ Čížek, Radoslav,                ┆ Sup                             ┆ 1   │
│ Urban, František                ┆ Dnešní Japonsko                 ┆ 1   │
│ Fassati, Miloslav,              ┆ Chodecký sport                  ┆ 1   │
│ Lomakin, Trofim                 ┆ Cesta vzpěrače                  ┆ 1   │
│ Král, Mojmír                    ┆ Jak si postavíme stanový tábor  ┆ 1   │
│ Čepelák, Vladislav,             ┆ Lyžařské švihy a oblouky        ┆ 1   │
│ Mráz, Jaroslav,                 ┆ Házená mládeže                  ┆ 1   │
│ Bursík, Richard                 ┆ Základy moderního bridge        ┆ 1   │
│ Šterc, Jaroslav,                ┆ Prostná cvičení pro muže ROH    ┆ 1   │
│ Vepřek, Josef,                  ┆ Kutná Hora a okolí              ┆ 1   │
│ Finková, Zdena                  ┆ Lidová hvězdárna v Praze na Pe… ┆ 1   │
│ Kouřimský, Gustav               ┆ Cvičení s praporky pro žactvo … ┆ 1   │
│ Liska, Zdeněk                   ┆ Trio                            ┆ 1   │
│ Velenský, Emil,                 ┆ Košíková                        ┆ 1   │
│ Kratochvíl, Jiří                ┆ Výlety do okolí Prahy           ┆ 1   │
│ Špecinger, Otakar,              ┆ Příbramsko                      ┆ 1   │
│ Faigl, Václav                   ┆ Pravidla šachu a soutěžní řád   ┆ 1   │
│ Motyljanskaja, R. Je.           ┆ Tělesná výchova ženy            ┆ 1   │
│ Glivický, Vladimír,             ┆ Tělesná výchova a výkonnost pr… ┆ 1   │
│ Brdlík, Jan                     ┆ Zdravotní příručka horské služ… ┆ 1   │
│ Hrubý, Jaromír                  ┆ Aurea                           ┆ 1   │
│ Jakovlev, Nikolaj Nikolajevič,  ┆ Co se děje v organismu sportov… ┆ 1   │
│ Appelt, Karel,                  ┆ Akrobatická prostná             ┆ 1   │
│ Vahala, Miroslav                ┆ Turista poznává vlast           ┆ 1   │
│ Czesaný, Karel,                 ┆ Pravidla veslování              ┆ 1   │
│ Chalupa, Jiří                   ┆ Využít zkušeností z 1. celostá… ┆ 1   │
│ Brauchitsch, Manfred von,       ┆ Boj o metry a vteřiny           ┆ 1   │
│ Šafařík, Vladimír,              ┆ Basketbalové prvky (pro 6 cvič… ┆ 1   │
│ Bělonožník, Miloslav,           ┆ Skok na lyžích                  ┆ 1   │
│ Brož, Jaroslav                  ┆ Pionýr                          ┆ 1   │
│ Menclová, Dobroslava,           ┆ Bezděz                          ┆ 1   │
│ Stránský, Antonín,              ┆ Psychologie sportu              ┆ 1   │
│ Fürlová-Votavová, Danica,       ┆ V mírovém soužití k výšinám ve… ┆ 1   │
│ Dvořáková, Vlasta,              ┆ Horšovský Týn                   ┆ 1   │
│ Vorel, Stanislav,               ┆ Vlakový průvodce Praha - Česká… ┆ 1   │
│ Bušek, Bedřich                  ┆ Oderské vrchy                   ┆ 1   │
│ Drážek, Milan                   ┆ Meteor - upoutaný model pro sk… ┆ 1   │
│ Šprynar, Zdeněk,                ┆ Dovršit výstavbu socialistické… ┆ 1   │
│ Hlaváček, Miroslav,             ┆ Jak získat odznak Turista ČSSR  ┆ 1   │
│ Havelka, Otto                   ┆ Liptovské hole                  ┆ 1   │
│ Kassil‘, Lev Abramovič,         ┆ Vládkyně sněžné hory            ┆ 1   │
│ Tichák, Mojmír                  ┆ Zimní horolezecké táboření      ┆ 1   │
│ Děták, Jaroslav,                ┆ Českokrumlovsko                 ┆ 1   │
│ Vedral, Jan                     ┆ Lyžování mládeže                ┆ 1   │
│ Levá, Stáza                     ┆ Cvičení osmice s dvěma obručem… ┆ 1   │
│ Zikmund, Václav                 ┆ Parníkem po Vltavě a Labi       ┆ 1   │
│ Marcoň, Josef                   ┆ Plavání na pionýrských táborec… ┆ 1   │
│ Rudolph, Fritz                  ┆ Himálajští tygři                ┆ 1   │
│ Makovský, Bedřich,              ┆ Propagačně výchovná práce v tě… ┆ 1   │
│ Panoš, Vladimír,                ┆ Javoříčko - Moravské Lidice     ┆ 1   │
│ Líbal, Dobroslav,               ┆ Znojmo                          ┆ 1   │
│ Svoboda, Karel,                 ┆ Buchlovice                      ┆ 1   │
│ Mareš, Jan,                     ┆ Spodní úder                     ┆ 1   │
│ Smetana, František              ┆ Výcvik neplavce s pomůckami     ┆ 1   │
│ Čivrný, Čestmír,                ┆ Pravidla šermu                  ┆ 1   │
│ Šantl, Hynek                    ┆ Pootaví                         ┆ 1   │
│ Cihlář, Jaroslav,               ┆ Po prvé na kole                 ┆ 1   │
│ Pavel, Jakub,                   ┆ Rychnov nad Kněžnou             ┆ 1   │
│ Frýzek, Václav                  ┆ Lední hokej                     ┆ 1   │
│ Oktábec, Josef,                 ┆ II. celostátní spartakiáda ve … ┆ 1   │
│ Vodháněl, Ladislav,             ┆ Český ráj pro horolezce         ┆ 1   │
│ Barcziová, Jarmila              ┆ Cvičíme na pracovišti           ┆ 1   │
│ Brzák, František,               ┆ Kanoistika                      ┆ 1   │
│ Rybár, Ctibor,                  ┆ V ritme krasoty i radosti       ┆ 1   │
│ Petrová, Blažena,               ┆ Hravé míčky                     ┆ 1   │
│ Kunstmüllerová-Hnátková, Květu… ┆ Jak se Zdeněk naučil plavat     ┆ 1   │
│ Patočka, František,             ┆ Máchův kraj                     ┆ 1   │
│ Baitler, Jiří                   ┆ Jiba-25 vodní kluzák s motorem… ┆ 1   │
│ Žák, Jaroslav,                  ┆ Dobrý borec Antonín             ┆ 1   │
│ Antonov-Tonič, Anton,           ┆ Poslední kolo                   ┆ 1   │
│ Penninger, Evžen,               ┆ Prostná cvičení pro muže a žen… ┆ 1   │
│ Jedlička, Miroslav,             ┆ Měření času na lyžařských závo… ┆ 1   │
│ Buquaiová, Manka                ┆ Cvičení s velkým míčem (třídíl… ┆ 1   │
│ Žemla, František,               ┆ Niké pro Anglii                 ┆ 1   │
│ Revenda, Miroslav               ┆ Skok o tyči                     ┆ 1   │
│ Livorová, Helena,               ┆ Pohybem ke kráse                ┆ 1   │
│ Vahala, Miroslav                ┆ Mototuristika v Brněnském kraj… ┆ 1   │
│ Rybár, Ctibor,                  ┆ A story of beauty, joy and ach… ┆ 1   │
│ Šterc, Jaroslav,                ┆ Pokyny k pořádání tělovýchovný… ┆ 1   │
│ Peterka, Václav                 ┆ Vzpírání                        ┆ 1   │
│ Hrbek, Rudolf,                  ┆ Avantgarda                      ┆ 1   │
│ Přikryl, František              ┆ Vodní dílo Orlík                ┆ 1   │
│ Choutková-Cvrková, Božena,      ┆ Lehká atletika pro mládež       ┆ 1   │
│ Továrek, František,             ┆ Pochodem v chod                 ┆ 1   │
│ Vlk, Gustav,                    ┆ Lední hokej v kapse             ┆ 1   │
│ Hainz, Jaroslav,                ┆ Pravidla tanců na ledě a jejic… ┆ 1   │
│ Moťka, Leo                      ┆ Die Tschechoslowakei als Reise… ┆ 1   │
│ Landa, Abram Moisejevič,        ┆ Úrazová zábrana ve sportu       ┆ 1   │
│ Bass, Eduard,                   ┆ Klapzubova jedenáctka           ┆ 1   │
│ Menclová, Dobroslava,           ┆ Karlštejn                       ┆ 1   │
│ Doubek, Eduard,                 ┆ Posázaví                        ┆ 1   │
│ Šnajperk, Rajmund               ┆ Republikou na kole              ┆ 1   │
│ Valeš, Jan                      ┆ Sportovní soutěže 3. celostátn… ┆ 1   │
│ Knap, Karel                     ┆ Od Ženevy k Ženevě a jak dál v… ┆ 1   │
│ Petrová, Blažena,               ┆ Cvičení pro ženy                ┆ 1   │
│ Erhart, Vilém,                  ┆ Krásy jižních Čech - Krumlovsk… ┆ 1   │
│ Wagner, Jaroslav,               ┆ Jičín                           ┆ 1   │
│ Kučeravý, Vasil                 ┆ Na zemi i ve vzduchu vždy přip… ┆ 1   │
│ Maršíček, Josef                 ┆ Motortrip durch die Tschechosl… ┆ 1   │
│ Podzemská, Jiřina,              ┆ Hořovice                        ┆ 1   │
│ Chyský, Jiří,                   ┆ Orlické hory                    ┆ 1   │
│ Šterc, Jaroslav,                ┆ Jak organizovat a řídit základ… ┆ 1   │
│ Hlaváč, Lumír                   ┆ Střední Polabí                  ┆ 1   │
│ Žbírková, Alena,                ┆ Domácí cvičení pro otylé        ┆ 1   │
│ Doubnerová, Jiřina,             ┆ Krajem jihočeských rybníků      ┆ 1   │
│ Tesařík, Jiří                   ┆ Házená                          ┆ 1   │
│ Seidl, Karel,                   ┆ Historická knihovna Teplá - kl… ┆ 1   │
│ Novák, Jindřich,                ┆ Karate                          ┆ 1   │
│ Nejdl, Karel,                   ┆ Lázeňské město Karlovy Vary     ┆ 1   │
│ Fauová, Naďa                    ┆ Turistická tábořiště a ubytovn… ┆ 1   │
│ Norkjä, Tändzin,                ┆ Muž z Everestu                  ┆ 1   │
│ Kukuškin, G. I.                 ┆ Sovětská tělesná kultura - důl… ┆ 1   │
│ Rejhonová, Marie                ┆ Do nových zítřků                ┆ 1   │
│ Chyský, Jiří,                   ┆ Základy turistiky               ┆ 1   │
│ Bělská, Milada                  ┆ Na hory s DPM                   ┆ 1   │
│ Krestovnikov, Aleksej Nikolaje… ┆ Nárys fysiologie tělesných cvi… ┆ 1   │
│ Kramarič, Julius                ┆ Cestujeme do Bulharska          ┆ 1   │
│ Panoš, Vladimír,                ┆ Jeskyně Severomoravského krasu  ┆ 1   │
│ Kocourek, Miloslav              ┆ Katalog filmů tělovýchovy a sp… ┆ 1   │
│ Hlavsa, Václav,                 ┆ Nové Město pražské              ┆ 1   │
│ Oliva, Pavel,                   ┆ Spartakus                       ┆ 1   │
│ Vacula, Jindřich,               ┆ Lehká atletika                  ┆ 1   │
│ Chod, Václav                    ┆ Záchrana tonoucích              ┆ 1   │
│ Holub, Jiří                     ┆ O žlutý trikot                  ┆ 1   │
│ Hlavsa, Václav,                 ┆ Staré Město                     ┆ 1   │
│ Rybár, Ctibor,                  ┆ 18. olympijské hry, Tokio 1964  ┆ 1   │
│ Rozhoň, František               ┆ Pražský kraj                    ┆ 1   │
│ Kříž, Vladimír                  ┆ Stavíme koupaliště na potocích  ┆ 1   │
│ Herych, Přemysl                 ┆ Šerm                            ┆ 1   │
│ Průša, Jan                      ┆ Jak na turistickou propustku d… ┆ 1   │
│ Šedivý, Vladimír,               ┆ Na ledovcích Váchánu            ┆ 1   │
│ Fanagorskaja, T. P.             ┆ Co má sportovec vědět o nervov… ┆ 1   │
│ Votrubec, Ctibor,               ┆ Turistická oblast polských Krk… ┆ 1   │
│ Stárka, Vladimír,               ┆ Český kras a jeskyně na Zlatém… ┆ 1   │
│ Holub, Jiří                     ┆ Zlato z Tokia                   ┆ 1   │
│ Antonov-Tonič, Anton,           ┆ Vysoká hra                      ┆ 1   │
│ Tožička, Jiří,                  ┆ Chlapci a hokej                 ┆ 1   │
│ Hanuš, Josef                    ┆ Krajem Aloise Jiráska a Boženy… ┆ 1   │
│ Filip, Miroslav,                ┆ Turnaj kandidátů mistrovství s… ┆ 1   │
│ Kovanda, Vladimír               ┆ Upravujeme a stavíme sáňkařské… ┆ 1   │
│ Gutwirth, Lev,                  ┆ Turistika, sport a rekreace ve… ┆ 1   │
│ Kubík, Čestmír,                 ┆ Příběhy mužů a hor              ┆ 1   │
│ Pačenovský, Samo,               ┆ Taktika šermu na základě Pavlo… ┆ 1   │
│ Dobrý, Lubomír,                 ┆ Košíková mládeže                ┆ 1   │
│ Vahala, Miroslav                ┆ Moravský Kras, Macocha a okolí  ┆ 1   │
│ Žižka, Jiří                     ┆ Cvičení na bedně                ┆ 1   │
│ Procházka, Vladimír,            ┆ Gama - kabinový model s gumový… ┆ 1   │
│ Hadaš, František,               ┆ Luk a šíp                       ┆ 1   │
│ Hejna, Antonín,                 ┆ Opočno                          ┆ 1   │
│ Höhm, Jindřich,                 ┆ Metodika nácviku útočné hry v … ┆ 1   │
│ Tošnar, Milan,                  ┆ Překážkové běhy                 ┆ 1   │
│ Hrubý, Gustav                   ┆ Bradla                          ┆ 1   │
│ Sýkora, Bohuslav,               ┆ Orientační hry a závody mládež… ┆ 1   │
│ Pacovský, Jaroslav,             ┆ Český ráj                       ┆ 1   │
│ Smítková, Zdenka                ┆ Cvičíme s dětmi                 ┆ 1   │
│ Folprecht, Václav               ┆ Bohemians ČKD Praha             ┆ 1   │
│ Barczi, Oskar,                  ┆ Průpravná cvičení a hry         ┆ 1   │
│ Pešková, Lída                   ┆ Za mír, přátelství a spoluprác… ┆ 1   │
│ Tuma, Antonín                   ┆ Cvičení pro chlapce 6.-8. post… ┆ 1   │
│ Hrubý, Gustav                   ┆ Přemety na bradlech             ┆ 1   │
│ Šimka, Alois,                   ┆ Jihlavské vrchy a Dačicko       ┆ 1   │
│ Makovská, Stanislava            ┆ Prostná cvičení pro ženy TSO S… ┆ 1   │
│ Procházka, Vladimír,            ┆ Ogar - školní kluzák            ┆ 1   │
│ Stibitz, František,             ┆ Jednotné názvosloví sportovníc… ┆ 1   │
│ Zmatlík, Karel,                 ┆ Šachista začátečník             ┆ 1   │
│ Pernica, Milan                  ┆ Odbor turistiky tělovýchovné j… ┆ 1   │
│ Dietlová, Jana                  ┆ Cvičení s obručemi pro žactvo … ┆ 1   │
│ Kostková, Jarmila,              ┆ Má země je kvetoucí louka       ┆ 1   │
│ Hadaš, Zdeněk,                  ┆ Turistikou k činnému stáří      ┆ 1   │
│ Kraus, Ervín                    ┆ Tabulky pro výpočet časů, tres… ┆ 1   │
│ Buddeusová, Nora,               ┆ Tělesná výchova starších žen    ┆ 1   │
│ Kouřimský, Gustav               ┆ Cvičební hodiny všeobecné průp… ┆ 1   │
│ Hudec, Jaroslav                 ┆ Cyklistika                      ┆ 1   │
│ Demeter, Georgij Stepanovič,    ┆ Lenin o tělesné výchově         ┆ 1   │
│ Moravec, Radim                  ┆ Františkovy Lázně a okolí       ┆ 1   │
│ Karlíček, Miroslav,             ┆ Malá Fatra v zimě               ┆ 1   │
│ Wollmann, František             ┆ Autokarem do západočeských láz… ┆ 1   │
│ Heger, Vladimír,                ┆ Mladí hrají košíkovou           ┆ 1   │
│ Hruška, Jaroslav                ┆ Rohování                        ┆ 1   │
│ Fiala, Václav,                  ┆ Poučení z pedagogiky pro cviči… ┆ 1   │
│ …                               ┆ …                               ┆ …   │
│ Chrástek, Josef,                ┆ Základy lékařsko-pedagogického… ┆ 1   │
│ Říha, Jaromír,                  ┆ Rybářský průvodce kraji Praha … ┆ 1   │
│ Plisková, Libuše,               ┆ Mládí a radost                  ┆ 1   │
│ Rozhoň, František               ┆ Liptov a Orava                  ┆ 1   │
│ Vaněk, Lubomír,                 ┆ Kutná Hora                      ┆ 1   │
│ Čížek, Jiří                     ┆ Pootaví                         ┆ 1   │

In [29]:
edice("Řada polytechn. literatury")

shape: (41, 4)
┌──────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                        ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                          ┆ ---                             ┆ ---   ┆ ---  │
│ str                          ┆ str                             ┆ i64   ┆ i64  │
╞══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Boublík, Vlastimil,          ┆ Lití plastických hmot pro mode… ┆ 199   ┆ 1966 │
│ Válek, Jiří                  ┆ Úvod do elektroniky             ┆ 195   ┆ 1966 │
│ Boublík, Vlastimil,          ┆ Lepidla a jejich příprava       ┆ 190   ┆ 1966 │
│ Štěpánský, Václav,           ┆ Nomogramy                       ┆ 186   ┆ 1966 │
│ Procházka, Arnold            ┆ Základy mechaniky vody v praxi  ┆ 125   ┆ 1966 │
│ Fišner, Boleslav,            ┆ Chemie                          ┆ 229   ┆ 1967 │
│ Sedláček, Jiří,              ┆ Nebojte se matematiky           ┆ 135   ┆ 1969 │
│ Jarník, Jiří,                ┆ Jak řešit rovnice a jejich sou… ┆ 243   ┆ 1969 │
│ Beránek, Robert,             ┆ Úprava okolí chaty nebo rodinn… ┆ 133   ┆ 1970 │
│ Košťál, Karel,               ┆ Sbírka fyzikálních vzorců a po… ┆ 407   ┆ 1970 │
│ Kolek, Lubomír               ┆ Přehled vzorců středoškolské m… ┆ 323   ┆ 1970 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 354   ┆ 1971 │
│ Toř, Zdeněk                  ┆ Fyzika v příkladech             ┆ 250   ┆ 1971 │
│ Rejman, Martin,              ┆ Co a jak s polyesterovými skel… ┆ 94    ┆ 1972 │
│ Slánský, Bohuslav,           ┆ Technika v malířské tvorbě      ┆ 186   ┆ 1973 │
│ Štulík, Václav               ┆ Jak fotografovat                ┆ 149   ┆ 1973 │
│ Štěpán, Jan                  ┆ Motorové čluny                  ┆ 275   ┆ 1973 │
│ Tůma, Jan,                   ┆ Nebojte se promítání!           ┆ 211   ┆ 1973 │
│ Šulc, Jan                    ┆ Jednoduchá měření pro amatéry   ┆ 106   ┆ 1973 │
│ Tausk, Petr,                 ┆ Materiály pro černobílou fotog… ┆ 125   ┆ 1973 │
│ Tausk, Petr,                 ┆ Materiály pro černobílou fotog… ┆ 125   ┆ 1973 │
│ Vinter, Jan                  ┆ Práce se dřevem                 ┆ 139   ┆ 1973 │
│ Kusl, František              ┆ Příručka pro domácí dílnu       ┆ 179   ┆ 1973 │
│ Beneš, Jan                   ┆ Stavba garáže                   ┆ 213   ┆ 1974 │
│ Jukl, Alois,                 ┆ Vytápěcí zařízení pro byty a d… ┆ 193   ┆ 1974 │
│ Beránek, Robert,             ┆ Úprava okolí chaty nebo rodinn… ┆ 177   ┆ 1974 │
│ Kusl, František              ┆ Příručka pro domácí dílnu       ┆ 179   ┆ 1974 │
│ Šustr, Karel                 ┆ Elektrické rozvody a zařízení … ┆ 183   ┆ 1974 │
│ Šustr, Karel                 ┆ Elektrické rozvody a zařízení … ┆ 183   ┆ 1975 │
│ Täubl, Karel,                ┆ Zlatnictví                      ┆ 199   ┆ 1975 │
│ Šmok, Ján,                   ┆ Diapozitivy v praxi             ┆ 289   ┆ 1975 │
│ Svoboda, Antonín             ┆ Mikrofilm v praxi               ┆ 340   ┆ 1976 │
│ Täubl, Karel,                ┆ Zlatnictví                      ┆ 199   ┆ 1976 │
│ Slánský, Bohuslav,           ┆ Technika v malířské tvorbě      ┆ 186   ┆ 1976 │
│ Jeřábek, Václav,             ┆ Obnova a údržba malých staveb   ┆ 165   ┆ 1976 │
│ David, Stanislav             ┆ Vlastní výroba bytových doplňk… ┆ 142   ┆ 1976 │
│ Krůta, Václav                ┆ Staviva a výrobky pro svépomoc… ┆ 148   ┆ 1978 │
│ Šrejder, Julij Anatol‘jevič, ┆ Binární relace                  ┆ 320   ┆ 1978 │
│ Tausk, Petr,                 ┆ Materiály pro barevnou fotogra… ┆ 147   ┆ 1979 │
│ Staňková, Jaroslava,         ┆ Tisíciletý vývoj architektury   ┆ 427   ┆ 1979 │
└──────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [30]:
zjisti("Volají neviditelné vlny")

Knížky pro chytré děti

shape: (1, 6)
┌───────────────────┬─────────────────────────┬───────┬──────┬───────┬────────────────────────┐
│ 100_a             ┆ 245_a                   ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                  │
│ ---               ┆ ---                     ┆ ---   ┆ ---  ┆ ---   ┆ ---                    │
│ str               ┆ str                     ┆ str   ┆ i64  ┆ i64   ┆ str                    │
╞═══════════════════╪═════════════════════════╪═══════╪══════╪═══════╪════════════════════════╡
│ Škoda, František, ┆ Volají neviditelné vlny ┆ SNDK  ┆ 1960 ┆ 47    ┆ Knížky pro chytré děti │
└───────────────────┴─────────────────────────┴───────┴──────┴───────┴────────────────────────┘

In [31]:
edice("Knížky pro chytré děti")

shape: (9, 4)
┌────────────────────┬─────────────────────────┬───────┬──────┐
│ 100_a              ┆ 245_a                   ┆ stran ┆ rok  │
│ ---                ┆ ---                     ┆ ---   ┆ ---  │
│ str                ┆ str                     ┆ i64   ┆ i64  │
╞════════════════════╪═════════════════════════╪═══════╪══════╡
│ Čtvrtek, Václav,   ┆ Směr vesmír - start!    ┆ 44    ┆ 1959 │
│ Koval, Václav,     ┆ Svět za sklem           ┆ 47    ┆ 1959 │
│ Růžička, Jiří,     ┆ Nej - nej - nej         ┆ 36    ┆ 1959 │
│ Korejs, Milan,     ┆ Rukulíbám - dobrý den   ┆ 47    ┆ 1959 │
│ Svoboda, Vladimír, ┆ Ať přestane svítit      ┆ 46    ┆ 1960 │
│ Škoda, František,  ┆ Volají neviditelné vlny ┆ 47    ┆ 1960 │
│ Koval, Václav,     ┆ 25 divů v našem domě    ┆ 63    ┆ 1961 │
│ Souček, Ludvík,    ┆ Hrátky kolem křižovatky ┆ 54    ┆ 1962 │
│ Nepil, František,  ┆ Kola, strojky, nápady   ┆ 69    ┆ 1963 │
└────────────────────┴─────────────────────────┴───────┴──────┘

In [32]:
zjisti("Hry s kalkulátory")

Knižnice všeobecného vzdělání mládeže. Maják

shape: (3, 6)
┌──────────────┬───────────────────┬───────┬──────┬───────┬─────────────────────────────────┐
│ 100_a        ┆ 245_a             ┆ 260_b ┆ rok  ┆ stran ┆ 490_a                           │
│ ---          ┆ ---               ┆ ---   ┆ ---  ┆ ---   ┆ ---                             │
│ str          ┆ str               ┆ str   ┆ i64  ┆ i64   ┆ str                             │
╞══════════════╪═══════════════════╪═══════╪══════╪═══════╪═════════════════════════════════╡
│ Mrázek, Jiří ┆ Hry s kalkulátory ┆ SPN   ┆ 1984 ┆ 111   ┆ Knižnice všeobecného vzdělání … │
│ Mrázek, Jiří ┆ Hry s kalkulátory ┆ SPN   ┆ 1986 ┆ 111   ┆ Knižnice všeobecného vzděláván… │
│ Mrázek, Jiří ┆ Hry s kalkulátory ┆ SPN   ┆ 1988 ┆ 111   ┆ Knižnice všeobecného vzdělání … │
└──────────────┴───────────────────┴───────┴──────┴───────┴─────────────────────────────────┘

In [33]:
edice("Knižnice všeobecného vzdělání mládeže")

shape: (33, 4)
┌────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                      ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                        ┆ ---                             ┆ ---   ┆ ---  │
│ str                        ┆ str                             ┆ i64   ┆ i64  │
╞════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Duchoň, František,         ┆ Hydroponie                      ┆ 199   ┆ 1965 │
│ Hejda, Stanislav,          ┆ Správná výživa teoreticky a pr… ┆ 304   ┆ 1968 │
│ Řehák, Bohuslav,           ┆ Vycházky do přírody             ┆ 243   ┆ 1968 │
│ Hejda, Stanislav,          ┆ Správná výživa teoreticky a pr… ┆ 304   ┆ 1969 │
│ Kuba, Adolf,               ┆ Kluci, plný plyn                ┆ 131   ┆ 1969 │
│ Bojev, Sergej Nikolajevič, ┆ Jak savci pečují o svá mláďata  ┆ 61    ┆ 1969 │
│ Šimáček, Radovan,          ┆ Obchodujeme s celým světem      ┆ 264   ┆ 1970 │
│ Augusta, Josef,            ┆ U pravěkých lovců               ┆ 163   ┆ 1971 │
│ Augusta, Josef,            ┆ Z hlubin pravěku                ┆ 141   ┆ 1971 │
│ Augusta, Josef,            ┆ Zavátý život                    ┆ 174   ┆ 1971 │
│ Novoveský, Štefan,         ┆ 777 matematických zábav a her   ┆ 381   ┆ 1971 │
│ Mečíř, Miloslav,           ┆ Péče o malé dítě                ┆ 186   ┆ 1971 │
│ Řehák, Bohuslav,           ┆ Vycházky do přírody             ┆ 243   ┆ 1971 │
│ Augusta, Josef,            ┆ Ztracený svět                   ┆ 170   ┆ 1972 │
│ Dobrowolski, Kazimierz A., ┆ Jak živočichové létají          ┆ 145   ┆ 1972 │
│ Augusta, Josef,            ┆ U pravěkých lovců               ┆ 156   ┆ 1973 │
│ Řehák, Bohuslav,           ┆ Vycházky do přírody             ┆ 243   ┆ 1973 │
│ Chvátal, Václav            ┆ Světová socialistická soustava  ┆ 181   ┆ 1974 │
│ Míka, Alois,               ┆ Stoletý zápas o charakter česk… ┆ 189   ┆ 1974 │
│ Picmaus, Karel,            ┆ Evropská bezpečnost             ┆ 190   ┆ 1974 │
│ Augusta, Josef,            ┆ U pravěkých lovců               ┆ 156   ┆ 1975 │
│ Novoveský, Štefan,         ┆ Zábavná matematika              ┆ 325   ┆ 1975 │
│ Duchoň, František,         ┆ Uživí nás Země?                 ┆ 155   ┆ 1976 │
│ Augusta, Josef,            ┆ Lovci jeskynních medvědů        ┆ 229   ┆ 1976 │
│ Augusta, Josef,            ┆ Zavátý život                    ┆ 176   ┆ 1976 │
│ Houška, Jiří,              ┆ Společnost, stát a jednotlivec  ┆ 195   ┆ 1977 │
│ Grosse, Erich,             ┆ Chemie z vlastních pozorování   ┆ 365   ┆ 1977 │
│ Sedliak, Július            ┆ Polsko v epoše socialismu       ┆ 189   ┆ 1977 │
│ Jelínek, Jaroslav,         ┆ Čtení o českém jazyku           ┆ 301   ┆ 1980 │
│ Jelínek, Jaroslav,         ┆ Čtení o českém jazyku           ┆ 301   ┆ 1982 │
│ Polák, Josef,              ┆ Přehled středoškolské matemati… ┆ 627   ┆ 1983 │
│ Mrázek, Jiří               ┆ Hry s kalkulátory               ┆ 111   ┆ 1984 │
│ Mrázek, Jiří               ┆ Hry s kalkulátory               ┆ 111   ┆ 1988 │
└────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [99]:
df.filter(pl.col("245_a").str.contains("Grand Prix")).select(pl.col(["100_a","245_a","rok"])).sort(by='rok')

shape: (27, 3)
┌─────────────────────┬─────────────────────────────────┬──────┐
│ 100_a               ┆ 245_a                           ┆ rok  │
│ ---                 ┆ ---                             ┆ ---  │
│ str                 ┆ str                             ┆ i64  │
╞═════════════════════╪═════════════════════════════════╪══════╡
│ Frewin, Michael     ┆ Grand Prix                      ┆ 1968 │
│ Kovářík, Miloš,     ┆ Grand Prix je náš život         ┆ 1969 │
│ Čížek, Zdeněk       ┆ Grand Prix Brno                 ┆ 1978 │
│ Nixbauer, Miloš     ┆ Ironcurtain duathlon Grand Pri… ┆ 1995 │
│ Šubertová, Zuzana   ┆ Evropské kolo světového šampio… ┆ 1995 │
│ Adit, Josef         ┆ Grand Prix amerických profesio… ┆ 1997 │
│ Dobbins, Bill,      ┆ Pro Fitness USA Grand Prix      ┆ 1998 │
│ Kroužek, Jiří,      ┆ Grand Prix F 1                  ┆ 1998 │
│ Kroužek, Jiří,      ┆ Grand Prix F1                   ┆ 1999 │
│ Krejčí, A.          ┆ Grand Prix České republiky      ┆ 1999 │
│ Velímský, Dušan,    ┆ Grand Prix České republiky      ┆ 2000 │
│ Wohlmuth, Jiří,     ┆ Grand Prix Československa a Če… ┆ 2000 │
│ Wohlmuth, Jiří,     ┆ Grand Prix Československa a Če… ┆ 2003 │
│ Selucký, David,     ┆ Grand Prix a Formule 1          ┆ 2006 │
│ Wohlmuth, Jiří,     ┆ Grand Prix Československa a Če… ┆ 2007 │
│ Rittstein, Michael, ┆ 2008 FIM Czech republic Speedw… ┆ 2008 │
│ Selucký, David,     ┆ Grand Prix a Formule 1          ┆ 2009 │
│ Makušev, Petr       ┆ FIM Speedway Grand Prix Czech … ┆ 2010 │
│ Polách, Radek,      ┆ Alfred Neubauer - "Muž tisíce … ┆ 2010 │
│ Selucký, David,     ┆ Grand Prix a Formule 1          ┆ 2011 │
│ Houlihan, Brian     ┆ Světová Grand Prix              ┆ 2011 │
│ Houlihan, Brian     ┆ Svetová Grand Prix              ┆ 2011 │
│ Štola, Petr         ┆ Grand Prix 2012                 ┆ 2011 │
│ Štola, Petr         ┆ Grand Prix 2013                 ┆ 2012 │
│ Procházka, Václav   ┆ Speedway Grand Prix Prague      ┆ 2022 │
│ Buxton, Will,       ┆ Grand Prix                      ┆ 2024 │
│ Turco, Michel,      ┆ 1000 Grand Prix                 ┆ 2024 │
└─────────────────────┴─────────────────────────────────┴──────┘

In [34]:
df.filter(pl.col("245_a").str.contains("Pájení"))

shape: (10, 64)
┌──────────┬───────────────────┬───────────────┬───────────┬───┬───────────┬───────────┬───────┬──────┐
│ 100_ind1 ┆ 100_a             ┆ 100_7         ┆ 100_4     ┆ … ┆ 490_x     ┆ 490_3     ┆ stran ┆ rok  │
│ ---      ┆ ---               ┆ ---           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---  │
│ str      ┆ str               ┆ str           ┆ list[str] ┆   ┆ list[str] ┆ list[str] ┆ i64   ┆ i64  │
╞══════════╪═══════════════════╪═══════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════╪══════╡
│ 1        ┆ Ruža, Viliam      ┆ jx20051114023 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 452   ┆ 1988 │
│ 1        ┆ Ruža, Viliam      ┆ jx20051114023 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 452   ┆ 1988 │
│ 1        ┆ Martínek, Antonín ┆ null          ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 245   ┆ 1990 │
│ 1        ┆ Ruža, Viliam      ┆ jx20051114023 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 395   ┆ 1978 │
│ 1        ┆ Puchnar, Bedřich  ┆ jx20050531019 ┆ ["edt"]   ┆ … ┆ null      ┆ null      ┆ 89    ┆ 1952 │
│ 1        ┆ Němec, Karel      ┆ jk01083089    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 59    ┆ 1970 │
│ 1        ┆ Karlík, Pavel     ┆ xx0039036     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 147   ┆ 1967 │
│ 1        ┆ Karlík, Pavel     ┆ xx0039036     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 147   ┆ 1967 │
│ 1        ┆ Němec, Karel      ┆ jk01083089    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 50    ┆ 1963 │
│ 1        ┆ Slánský, Antonín  ┆ null          ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 78    ┆ 1947 │
└──────────┴───────────────────┴───────────────┴───────────┴───┴───────────┴───────────┴───────┴──────┘

In [35]:
zjisti("Současný šperk")

Soudobé české umění

shape: (1, 6)
┌─────────────────┬────────────────┬───────┬──────┬───────┬─────────────────────┐
│ 100_a           ┆ 245_a          ┆ 260_b ┆ rok  ┆ stran ┆ 490_a               │
│ ---             ┆ ---            ┆ ---   ┆ ---  ┆ ---   ┆ ---                 │
│ str             ┆ str            ┆ str   ┆ i64  ┆ i64   ┆ str                 │
╞═════════════════╪════════════════╪═══════╪══════╪═══════╪═════════════════════╡
│ Vokáčová, Věra, ┆ Současný šperk ┆ Odeon ┆ 1979 ┆ 71    ┆ Soudobé české umění │
└─────────────────┴────────────────┴───────┴──────┴───────┴─────────────────────┘

In [36]:
edice("Soudobé české umění")

shape: (33, 4)
┌───────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                         ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                           ┆ ---                             ┆ ---   ┆ ---  │
│ str                           ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Hlaváček, Luboš,              ┆ Současná kresba                 ┆ 71    ┆ 1976 │
│ Vlček, Tomáš,                 ┆ Současný plakát                 ┆ 71    ┆ 1976 │
│ Konečný, Dušan,               ┆ Výstavy současného umění        ┆ 71    ┆ 1977 │
│ Mrázová-Schusterová, Marcela, ┆ Současná krajinomalba           ┆ 71    ┆ 1977 │
│ Hlaváček, Luboš,              ┆ Současná grafika                ┆ 72    ┆ 1977 │
│ Dvorská, Pavla                ┆ Současná monumentální tvorba    ┆ 71    ┆ 1978 │
│ Michl, Jan                    ┆ Realizace a projekty v současn… ┆ 71    ┆ 1978 │
│ Konečný, Dušan,               ┆ Mladí čeští malíři              ┆ 71    ┆ 1978 │
│ Nýdl, Miroslav,               ┆ Současná známková tvorba        ┆ 71    ┆ 1978 │
│ Holub, Karel,                 ┆ Mladí čeští sochaři             ┆ 71    ┆ 1978 │
│ Laudová, Věra,                ┆ Obraz města v současném malířs… ┆ 71    ┆ 1978 │
│ Dvořák, František,            ┆ Současné exlibris               ┆ 71    ┆ 1979 │
│ Adlerová, Alena,              ┆ Současné sklo                   ┆ 71    ┆ 1979 │
│ Fixl, Viktor,                 ┆ Současná hračka                 ┆ 71    ┆ 1979 │
│ Růžička, Milouš,              ┆ Současná keramika               ┆ 71    ┆ 1979 │
│ Vokáčová, Věra,               ┆ Současný šperk                  ┆ 71    ┆ 1979 │
│ Vlček, Tomáš,                 ┆ Současný plakát                 ┆ 71    ┆ 1979 │
│ Růžička, Milouš,              ┆ Sovremennaja keramika           ┆ 71    ┆ 1979 │
│ Stehlíková, Blanka,           ┆ Zeitgenössische Illustration v… ┆ 71    ┆ 1979 │
│ Mráz, Bohumír,                ┆ Současná tapisérie              ┆ 71    ┆ 1980 │
│ Petrová, Sylva,               ┆ Mladá grafika                   ┆ 71    ┆ 1980 │
│ Jeřábek, Richard,             ┆ Plastika lidových tvůrců        ┆ 71    ┆ 1981 │
│ Fabel, Karel,                 ┆ Současná typografie             ┆ 71    ┆ 1981 │
│ Halířová, Marie               ┆ Portrétní tvorba                ┆ 71    ┆ 1981 │
│ Šimoníková, Jaromíra,         ┆ Interiérová tvorba              ┆ 71    ┆ 1982 │
│ Laudová, Věra,                ┆ Zátiší                          ┆ 71    ┆ 1983 │
│ Stehlíková, Blanka,           ┆ Ilustrace                       ┆ 71    ┆ 1984 │
│ Hošková, Simeona,             ┆ Mladá kresba                    ┆ 71    ┆ 1984 │
│ Procházka, Václav,            ┆ Medaile a plaketa               ┆ 71    ┆ 1984 │
│ Lamarová, Milena,             ┆ Průmyslový design               ┆ 71    ┆ 1985 │
│ Štochlová, Helena             ┆ Animovaný film                  ┆ 71    ┆ 1985 │
│ Matyášová, Eva                ┆ Naivní malířství                ┆ 71    ┆ 1986 │
│ Kybalová, Ludmila,            ┆ Oděvní tvorba                   ┆ 71    ┆ 1986 │
└───────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [37]:
zjisti("Můžu ochutnat")

None

shape: (1, 6)
┌──────────────────────────┬────────────────┬───────┬──────┬───────┬───────┐
│ 100_a                    ┆ 245_a          ┆ 260_b ┆ rok  ┆ stran ┆ 490_a │
│ ---                      ┆ ---            ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str                      ┆ str            ┆ str   ┆ i64  ┆ i64   ┆ str   │
╞══════════════════════════╪════════════════╪═══════╪══════╪═══════╪═══════╡
│ Mizielińska, Aleksandra, ┆ Můžu ochutnat? ┆ null  ┆ 2021 ┆ 112   ┆ null  │
└──────────────────────────┴────────────────┴───────┴──────┴───────┴───────┘

In [38]:
zjisti(", která se nesmála")

None

shape: (1, 6)
┌─────────────────┬──────────────────────────┬────────┬──────┬───────┬───────┐
│ 100_a           ┆ 245_a                    ┆ 260_b  ┆ rok  ┆ stran ┆ 490_a │
│ ---             ┆ ---                      ┆ ---    ┆ ---  ┆ ---   ┆ ---   │
│ str             ┆ str                      ┆ str    ┆ i64  ┆ i64   ┆ str   │
╞═════════════════╪══════════════════════════╪════════╪══════╪═══════╪═══════╡
│ Tashlin, Frank, ┆ Vačice, která se nesmála ┆ Baobab ┆ 2013 ┆ 55    ┆ null  │
└─────────────────┴──────────────────────────┴────────┴──────┴───────┴───────┘

In [39]:
zjisti("Nad propastí")

Spisů pro mládež č. 27

shape: (33, 6)
┌──────────────────────────┬───────────────────────┬──────────────────────────┬──────┬───────┬─────────────────────────┐
│ 100_a                    ┆ 245_a                 ┆ 260_b                    ┆ rok  ┆ stran ┆ 490_a                   │
│ ---                      ┆ ---                   ┆ ---                      ┆ ---  ┆ ---   ┆ ---                     │
│ str                      ┆ str                   ┆ str                      ┆ i64  ┆ i64   ┆ str                     │
╞══════════════════════════╪═══════════════════════╪══════════════════════════╪══════╪═══════╪═════════════════════════╡
│ Vlasák, Josef Věnceslav, ┆ Nad propastí          ┆ Nákladem knihkupectví B. ┆ 1882 ┆ 94    ┆ Spisů pro mládež č. 27  │
│                          ┆                       ┆ Stýbl…                   ┆      ┆       ┆                         │
│ Michajlov, A.,           ┆ Nad propastí          ┆ A. Hynek                 ┆ 1883 ┆ 70    ┆ Česká bibliotéka        │
│                          ┆                       ┆                          ┆      ┆       ┆ rodinná                 │
│ Michajlov, A.,           ┆ Nad propastí          ┆ Nákladem Al. Hynka,      ┆ 1884 ┆ 254   ┆ Česká bibliotéka        │
│                          ┆                       ┆ knihkupce                ┆      ┆       ┆ rodinná                 │
│ Michajlov, A.,           ┆ Nad propastí          ┆ Nákladem Al. Hynka,      ┆ 1884 ┆ 238   ┆ Česká bibliotéka        │
│                          ┆                       ┆ knihkupce                ┆      ┆       ┆ rodinná                 │
│ Vrchlický, Jaroslav,     ┆ Nad propastí          ┆ null                     ┆ 1887 ┆ 46    ┆ Dramatická díla         │
│                          ┆                       ┆                          ┆      ┆       ┆ Jaroslava Vrch…         │
│ Zahradník-Brodský,       ┆ Nad propastí          ┆ E. Šolc                  ┆ 1901 ┆ 371   ┆ null                    │
│ Bohumil,                 ┆                       ┆                          ┆      ┆       ┆                         │
│ Skarlandt, Julius,       ┆ Nad propastí          ┆ Edvard Jan Baštýř a      ┆ 1908 ┆ 210   ┆ Romány Praž. Illustr.   │
│                          ┆                       ┆ spol.                    ┆      ┆       ┆ kurýra                  │
│ Kraszewski, Józef        ┆ Nad propastí          ┆ Jos. R. Vilímek          ┆ 1913 ┆ 382   ┆ Vilímkovy illustrované  │
│ Ignacy,                  ┆                       ┆                          ┆      ┆       ┆ romány                  │
│ Vrchlický, Jaroslav,     ┆ Nad propastí          ┆ Nákladem F. Šimáčka      ┆ 1913 ┆ 47    ┆ Dramatická díla         │
│                          ┆                       ┆                          ┆      ┆       ┆ Jaroslava Vrch…         │
│ Zahradník-Brodský,       ┆ Nad propastí          ┆ Alois Wiesner            ┆ 1913 ┆ 291   ┆ Sebr. spisy             │
│ Bohumil,                 ┆                       ┆                          ┆      ┆       ┆                         │
│ Novák, Robert Lev,       ┆ Nad propastí          ┆ nákl.vl.                 ┆ 1916 ┆ 55    ┆ null                    │
│ Novák, Robert Lev,       ┆ Nad propastí          ┆ Přerod                   ┆ 1917 ┆ 59    ┆ Přerod                  │
│ Pasovský, Jaroslav,      ┆ Nad propastí          ┆ B. Kočí                  ┆ 1919 ┆ 16    ┆ Umělecké snahy          │
│ Dědina, František,       ┆ Nad propastí          ┆ null                     ┆ 1919 ┆ 26    ┆ null                    │
│ Hearts, James            ┆ Nad propastí          ┆ Reiter                   ┆ 1920 ┆ 32    ┆ Povídky z biografu      │
│ Dědina, František,       ┆ Nad propastí          ┆ nákl. vl.                ┆ 1920 ┆ 32    ┆ null                    │
│ Dědina, František,       ┆ Nad propastí          ┆ Obch. družstvo čes.      ┆ 1920 ┆ 32    ┆ null                    │
│                          ┆                       ┆ knihk. dis…              ┆      ┆       ┆                         │
│ Zahradník-Brodský,       ┆ Nad propastí          ┆ A. Neubert               ┆ 1922 ┆ 291   ┆ Sebr. spisy             │
│ Bohumil,                 ┆                       ┆                          ┆      ┆       ┆                         │
│ Zahradník-Brodský,       ┆ Nad propastí          ┆ V. Kotrba                ┆ 1922 ┆ 291   ┆ Sebrané spisy           │
│ Bohumil,                 ┆                       ┆                          ┆      ┆       ┆                         │
│ Šupka, František,        ┆ Nad propastí          ┆ Fr. Šupka                ┆ 1925 ┆ 220   ┆ Lidové povídky          │
│ Madeus, Š. A.            ┆ Nad propastí hanby    ┆ Svět                     ┆ 1932 ┆ 243   ┆ Romány Svět             │
│ Malzahn, Erik            ┆ Nad propastí          ┆ Novela, Karel Ninger     ┆ 1932 ┆ 64    ┆ Knihovna moderní ženy   │
│ Vrba, Rudolf,            ┆ Nad propastí          ┆ null                     ┆ 1932 ┆ 116   ┆ null                    │
│ Vrchlický, Jaroslav,     ┆ Nad propastí          ┆ Rodina                   ┆ 1933 ┆ 84    ┆ Vrchlický, Jaroslav:    │
│                          ┆                       ┆                          ┆      ┆       ┆ Dramatick…              │
│ Slavík, Jindřich Maria,  ┆ Nad propastí          ┆ C. Beran                 ┆ 1937 ┆ 30    ┆ null                    │
│ Kurka, Bernard,          ┆ Nad propastí          ┆ null                     ┆ 1942 ┆ 33    ┆ Moderní romány          │
│ Davis, Gill              ┆ Nad propastí          ┆ Návrat                   ┆ 1996 ┆ 40    ┆ Little & big western    │
│ Kellerman, Jonathan,     ┆ Nad propastí          ┆ Domino                   ┆ 2001 ┆ 389   ┆ null                    │
│ Smith, Wilbur A.,        ┆ Nad propastí          ┆ null                     ┆ 2018 ┆ 480   ┆ Klokan                  │
│ Auður Ava Ólafsdóttir,   ┆ Nad propastí byla tma ┆ null                     ┆ 2018 ┆ 209   ┆ null                    │
│ Havranová, Mária         ┆ Nad propastí          ┆ null                     ┆ 2020 ┆ 234   ┆ null                    │
│ Ord, Toby,               ┆ Nad propastí          ┆ null                     ┆ 2022 ┆ 480   ┆ Crossover               │
│ Štefková, Eliška,        ┆ Nad propastí          ┆ null                     ┆ 2024 ┆ 219   ┆ Bookla                  │
└──────────────────────────┴───────────────────────┴──────────────────────────┴──────┴───────┴─────────────────────────┘

In [40]:
edice("Crossover")

shape: (16, 4)
┌─────────────────────┬────────────────────────────────┬───────┬──────┐
│ 100_a               ┆ 245_a                          ┆ stran ┆ rok  │
│ ---                 ┆ ---                            ┆ ---   ┆ ---  │
│ str                 ┆ str                            ┆ i64   ┆ i64  │
╞═════════════════════╪════════════════════════════════╪═══════╪══════╡
│ Klein, Naomi,       ┆ Ne nestačí                     ┆ 294   ┆ 2019 │
│ Luce, Edward,       ┆ Soumrak západního liberalismu  ┆ 191   ┆ 2019 │
│ Keen, Andrew        ┆ Jak opravit budoucnost         ┆ 278   ┆ 2019 │
│ Ross, Alec,         ┆ Obory budoucnosti              ┆ 330   ┆ 2019 │
│ Lee, Kai-fu,        ┆ Supervelmoci umělé inteligence ┆ 291   ┆ 2019 │
│ Lowrey, Annie,      ┆ Dejte lidem peníze             ┆ 251   ┆ 2020 │
│ Scheidel, Walter,   ┆ Velký nivelizátor              ┆ 589   ┆ 2020 │
│ Collier, Paul,      ┆ Budoucnost kapitalismu         ┆ 299   ┆ 2020 │
│ Brown, Archie,      ┆ Mýtus silného vůdce            ┆ 503   ┆ 2021 │
│ MacAskill, William, ┆ Dobré úmysly nestačí           ┆ 262   ┆ 2021 │
│ Bregman, Rutger,    ┆ Lidstvo                        ┆ 425   ┆ 2022 │
│ Ord, Toby,          ┆ Nad propastí                   ┆ 480   ┆ 2022 │
│ Milanović, Branko,  ┆ Nic než kapitalismus           ┆ 309   ┆ 2022 │
│ Zuboff, Shoshana,   ┆ Věk kapitalismu dohledu        ┆ 725   ┆ 2022 │
│ Kolbert, Elizabeth, ┆ Pod bílou oblohou              ┆ 214   ┆ 2023 │
│ Turchin, Peter,     ┆ Poslední dny                   ┆ 299   ┆ 2024 │
└─────────────────────┴────────────────────────────────┴───────┴──────┘

In [41]:
zjisti("Neobyvatelná")

Klimax

shape: (1, 6)
┌──────────────────────┬───────────────────┬───────┬──────┬───────┬────────┐
│ 100_a                ┆ 245_a             ┆ 260_b ┆ rok  ┆ stran ┆ 490_a  │
│ ---                  ┆ ---               ┆ ---   ┆ ---  ┆ ---   ┆ ---    │
│ str                  ┆ str               ┆ str   ┆ i64  ┆ i64   ┆ str    │
╞══════════════════════╪═══════════════════╪═══════╪══════╪═══════╪════════╡
│ Wallace-Wells, David ┆ Neobyvatelná Země ┆ null  ┆ 2020 ┆ 390   ┆ Klimax │
└──────────────────────┴───────────────────┴───────┴──────┴───────┴────────┘

In [42]:
edice("Klimax")

shape: (11, 4)
┌──────────────────────┬───────────────────────┬───────┬──────┐
│ 100_a                ┆ 245_a                 ┆ stran ┆ rok  │
│ ---                  ┆ ---                   ┆ ---   ┆ ---  │
│ str                  ┆ str                   ┆ i64   ┆ i64  │
╞══════════════════════╪═══════════════════════╪═══════╪══════╡
│ Wallace-Wells, David ┆ Neobyvatelná Země     ┆ 390   ┆ 2020 │
│ Rich, Nathaniel,     ┆ Jak ztratit Zemi      ┆ 199   ┆ 2020 │
│ Hanišová, Viktorie,  ┆ Beton a hlína         ┆ 258   ┆ 2021 │
│ Carson, Rachel,      ┆ Tiché jaro            ┆ 374   ┆ 2021 │
│ Marshall, George,    ┆ Ani na to nemyslete   ┆ 348   ┆ 2022 │
│ Lovelock, James,     ┆ Novacén               ┆ 148   ┆ 2022 │
│ Mann, Michael E.,    ┆ Nová klimatická válka ┆ 444   ┆ 2022 │
│ Klein, Naomi,        ┆ Tím se všechno mění   ┆ 702   ┆ 2023 │
│ Abram, David,        ┆ Stávat se zvířetem    ┆ 371   ┆ 2024 │
│ Sanderson, Henry     ┆ Zelená horečka        ┆ 316   ┆ 2024 │
│ Goodell, Jeff,       ┆ Vedro                 ┆ 419   ┆ 2024 │
└──────────────────────┴───────────────────────┴───────┴──────┘

In [43]:
zjisti("Každému chléb")

Dobrý vítr

shape: (1, 6)
┌────────────────────┬─────────────────────────────┬──────────────┬──────┬───────┬────────────┐
│ 100_a              ┆ 245_a                       ┆ 260_b        ┆ rok  ┆ stran ┆ 490_a      │
│ ---                ┆ ---                         ┆ ---          ┆ ---  ┆ ---   ┆ ---        │
│ str                ┆ str                         ┆ str          ┆ i64  ┆ i64   ┆ str        │
╞════════════════════╪═════════════════════════════╪══════════════╪══════╪═══════╪════════════╡
│ Selucký, Radoslav, ┆ Každému chléb, každému růže ┆ Mladá fronta ┆ 1962 ┆ 208   ┆ Dobrý vítr │
└────────────────────┴─────────────────────────────┴──────────────┴──────┴───────┴────────────┘

In [44]:
edice("Dobrý vítr")

shape: (46, 4)
┌───────────────────────────────┬─────────────────────────────────┬───────┬──────┐
│ 100_a                         ┆ 245_a                           ┆ stran ┆ rok  │
│ ---                           ┆ ---                             ┆ ---   ┆ ---  │
│ str                           ┆ str                             ┆ i64   ┆ i64  │
╞═══════════════════════════════╪═════════════════════════════════╪═══════╪══════╡
│ Chrastil, Josef,              ┆ Smím prosit?                    ┆ 126   ┆ 1958 │
│ Chrastil, Josef,              ┆ Smím prosit?                    ┆ 126   ┆ 1958 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 123   ┆ 1958 │
│ Faukner, Rudolf,              ┆ Kdyby přišli Marťané, aneb, Pr… ┆ 120   ┆ 1958 │
│ Dvořák, František             ┆ Zařizujete si byt?              ┆ 83    ┆ 1958 │
│ Kusák, Alexej,                ┆ Knížka o vkusu                  ┆ 167   ┆ 1959 │
│ Boček, Jaroslav,              ┆ Znáte je z plátna               ┆ 183   ┆ 1959 │
│ Klímová-Fügnerová, Miroslava, ┆ Na prahu života                 ┆ 91    ┆ 1959 │
│ Zahradník, Miroslav,          ┆ Chcete se líbit?                ┆ 96    ┆ 1959 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 124   ┆ 1960 │
│ Hoffmann, Hans-Joachim,       ┆ Upřímné slovo                   ┆ 137   ┆ 1960 │
│ Jandera, Alexander,           ┆ Medicína do kapsy               ┆ 120   ┆ 1960 │
│ Dvořák, Vladimír,             ┆ Začínáme od Adama               ┆ 133   ┆ 1960 │
│ Kusák, Alexej,                ┆ Země kolem nás                  ┆ 98    ┆ 1961 │
│ Vávra, Ivan                   ┆ Malá abeceda na témata z mezin… ┆ 141   ┆ 1961 │
│ Urbanec, Jindřich             ┆ Lidé kolem stolu                ┆ 118   ┆ 1961 │
│ Hayn, H. G.                   ┆ Adam, Eva a teologové           ┆ 85    ┆ 1961 │
│ Selucký, Radoslav,            ┆ Každému chléb, každému růže     ┆ 208   ┆ 1962 │
│ Příbramská, Markéta           ┆ Móda od A do Z                  ┆ 131   ┆ 1962 │
│ Pavlík, Jan,                  ┆ Taneční do kapsy                ┆ 180   ┆ 1962 │
│ Barták, Vladimír,             ┆ Čtení před manželstvím          ┆ 186   ┆ 1963 │
│ Štěpnička, Jiří,              ┆ Cvičte s námi každý den         ┆ 117   ┆ 1963 │
│ Hartl, Břetislav,             ┆ Fotografie pro Aristotela       ┆ 279   ┆ 1964 │
│ Pondělíček, Ivo,              ┆ Rozumíte sami sobě?             ┆ 188   ┆ 1964 │
│ Tomášková, Jana,              ┆ Breviář půvabu                  ┆ 155   ┆ 1964 │
│ Stoklasa, Jaroslav,           ┆ Byt či nebyt                    ┆ 237   ┆ 1965 │
│ Břízová, Joza,                ┆ A přidáme něco fantazie         ┆ 169   ┆ 1965 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 146   ┆ 1966 │
│ Sís, Vladimír,                ┆ Počítání nudliček v jarní polé… ┆ 116   ┆ 1966 │
│ Plzák, Miroslav,              ┆ První pomoc při nehodách manže… ┆ 131   ┆ 1967 │
│ Sís, Vladimír,                ┆ Počítání nudliček v jarní polé… ┆ 116   ┆ 1967 │
│ Rakušan, Zdenko               ┆ Byt či nebyt                    ┆ 235   ┆ 1967 │
│ Tomášková, Jana,              ┆ Breviář půvabu                  ┆ 160   ┆ 1968 │
│ Majorová, Milena,             ┆ Člověk mezi lidmi               ┆ 146   ┆ 1969 │
│ Plzák, Miroslav,              ┆ První pomoc při nehodách manže… ┆ 130   ┆ 1969 │
│ Stoklasa, Jaroslav,           ┆ Ideální manžel, aneb, Co má vě… ┆ 274   ┆ 1969 │
│ Kozakiewicz, Mikołaj,         ┆ Důvěrnosti                      ┆ 189   ┆ 1970 │
│ Ravik, Slavomír,              ┆ Svět starožitností              ┆ 221   ┆ 1972 │
│ Nyklová, Milena,              ┆ Sbohem dětství                  ┆ 180   ┆ 1972 │
│ Nyklová, Milena,              ┆ O štěstí trochu jinak           ┆ 187   ┆ 1975 │
│ Matulová, Nina                ┆ Žena v dnešní rodině            ┆ 250   ┆ 1976 │
│ Garczyński, Stefan,           ┆ Soužití snadné a složité        ┆ 207   ┆ 1977 │
│ Staněk, Josef                 ┆ Zn. "Jen upřímně a vážně"       ┆ 217   ┆ 1977 │
│ Ravik, Slavomír,              ┆ Svět starožitností              ┆ 377   ┆ 1977 │
│ Kozakiewicz, Mikołaj,         ┆ Každý volí sebe                 ┆ 344   ┆ 1978 │
│ Pávek, František,             ┆ Manželská čítanka               ┆ 282   ┆ 1979 │
└───────────────────────────────┴─────────────────────────────────┴───────┴──────┘

In [123]:
zjisti("Nápady pro motoristy")

None

shape: (2, 6)
┌────────────────┬──────────────────────┬───────┬──────┬───────┬───────┐
│ 100_a          ┆ 245_a                ┆ 260_b ┆ rok  ┆ stran ┆ 490_a │
│ ---            ┆ ---                  ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str            ┆ str                  ┆ str   ┆ i64  ┆ i64   ┆ str   │
╞════════════════╪══════════════════════╪═══════╪══════╪═══════╪═══════╡
│ Beneš, Oldřich ┆ Nápady pro motoristy ┆ Práce ┆ 1970 ┆ 310   ┆ null  │
│ Beneš, Oldřich ┆ Nápady pro motoristy ┆ Práce ┆ 1971 ┆ 310   ┆ null  │
└────────────────┴──────────────────────┴───────┴──────┴───────┴───────┘