In [1]:
import os
import polars as pl
from src.bez_bordelu import bez_bordelu
from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
pl.Config(tbl_rows=500)

In [5]:
df = pl.read_parquet(
    os.path.join("data","cnb_vyber.parquet")
).with_columns(
    pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran')
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
)

In [11]:
df.filter(pl.col("245_a").str.contains("Odborné kreslení") & pl.col('100_a').str.contains('Cibulk'))

shape: (4, 64)
┌──────────────────┬──────────────────┬───────────┬─────────────┬───┬──────────────────┬────────────────┬───────┬──────┐
│ 008              ┆ 020_a            ┆ 020_c     ┆ 020_q       ┆ … ┆ leader           ┆ 001            ┆ stran ┆ rok  │
│ ---              ┆ ---              ┆ ---       ┆ ---         ┆   ┆ ---              ┆ ---            ┆ ---   ┆ ---  │
│ str              ┆ list[str]        ┆ list[str] ┆ list[str]   ┆   ┆ str              ┆ str            ┆ i64   ┆ i64  │
╞══════════════════╪══════════════════╪═══════════╪═════════════╪═══╪══════════════════╪════════════════╪═══════╪══════╡
│ 970802s1964      ┆ null             ┆ null      ┆ null        ┆ … ┆ nam a22     1    ┆ bk196501079    ┆ 170   ┆ 1964 │
│ xr a          0… ┆                  ┆           ┆             ┆   ┆ 4500             ┆                ┆       ┆      │
│ 960818s1980      ┆ null             ┆ null      ┆ ["(Brož.)"] ┆ … ┆ nam a22     1    ┆ bk198200854    ┆ 195   ┆ 1980 │
│ xr a          0… ┆                  ┆           ┆             ┆   ┆ 4500             ┆                ┆       ┆      │
│ 990202s1998      ┆ ["80-85920-46-8" ┆ null      ┆ ["(brož.)"] ┆ … ┆ nam a22      a   ┆ cpk19990631587 ┆ 155   ┆ 1998 │
│ xr a   d p    0… ┆ ]                ┆           ┆             ┆   ┆ 4500             ┆                ┆       ┆      │
│ 101008s2010      ┆ ["978-80-86817-4 ┆ null      ┆ ["(brož.)"] ┆ … ┆ cam a22      a   ┆ nkc20102154060 ┆ 165   ┆ 2010 │
│ xr a   e p    0… ┆ 1-5"]            ┆           ┆             ┆   ┆ 4500             ┆                ┆       ┆      │
└──────────────────┴──────────────────┴───────────┴─────────────┴───┴──────────────────┴────────────────┴───────┴──────┘

In [13]:
df.explode('964_a').filter(pl.col('964_a').str.contains('Kreslení odborné'))

shape: (45, 64)
┌────────────────┬────────────────┬───────────────┬────────────────┬───┬────────────────┬───────────────┬───────┬──────┐
│ 008            ┆ 020_a          ┆ 020_c         ┆ 020_q          ┆ … ┆ leader         ┆ 001           ┆ stran ┆ rok  │
│ ---            ┆ ---            ┆ ---           ┆ ---            ┆   ┆ ---            ┆ ---           ┆ ---   ┆ ---  │
│ str            ┆ list[str]      ┆ list[str]     ┆ list[str]      ┆   ┆ str            ┆ str           ┆ i64   ┆ i64  │
╞════════════════╪════════════════╪═══════════════╪════════════════╪═══╪════════════════╪═══════════════╪═══════╪══════╡
│ 980821s1950    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk195001894   ┆ 21    ┆ 1950 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980831s1950    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk195002110   ┆ 86    ┆ 1950 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980218s1951    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk195102228   ┆ 85    ┆ 1951 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 981209s1956    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk195601880   ┆ 89    ┆ 1956 │
│ xr     d p     ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980907s1956    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk195700885   ┆ 79    ┆ 1956 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980223s1959    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk195901040   ┆ 81    ┆ 1959 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980911s1959    ┆ null           ┆ null          ┆ ["(Brožováno)" ┆ … ┆ nam a22     1i ┆ bk195906436   ┆ 91    ┆ 1959 │
│ xr a           ┆                ┆               ┆ ]              ┆   ┆ 4500           ┆               ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980807s1960    ┆ null           ┆ ["Kčs 6,70"]  ┆ ["(Brož.) :"]  ┆ … ┆ nam a22     1  ┆ bk196002751   ┆ 105   ┆ 1960 │
│ xr af          ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980219s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196100930   ┆ 57    ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980306s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196101439   ┆ 102   ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980424s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196103127   ┆ 81    ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980504s1960    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196103363   ┆ 31    ┆ 1960 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980504s1960    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196103366   ┆ 12    ┆ 1960 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980716s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196105732   ┆ 87    ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980303s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196200448   ┆ 32    ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980427s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196200994   ┆ 105   ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980616s1962    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196202628   ┆ 96    ┆ 1962 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980718s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196203055   ┆ 91    ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980718s1962    ┆ null           ┆ null          ┆ ["(Váz.)"]     ┆ … ┆ nam a22     1  ┆ bk196203066   ┆ 103   ┆ 1962 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 980722s1961    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196203245   ┆ 7     ┆ 1961 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 971107s1964    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196402413   ┆ 69    ┆ 1964 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 971113s1964    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196402672   ┆ 60    ┆ 1964 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 971103s1964    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196404619   ┆ 57    ┆ 1964 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970802s1964    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196501079   ┆ 170   ┆ 1964 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 971123s1965    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196504777   ┆ 182   ┆ 1965 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970922s1966    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196603175   ┆ 141   ┆ 1966 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970810s1968    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196901416   ┆ 57    ┆ 1968 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 971018s1968    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk196902264   ┆ 28    ┆ 1968 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970403s1972    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk197204160   ┆ 73    ┆ 1972 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970409s1974    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk197403720   ┆ 115   ┆ 1974 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970806s1977    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk197705513   ┆ 73    ┆ 1977 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 970326s1978    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk197902481   ┆ 143   ┆ 1978 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 950908s1980    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk198102518   ┆ 123   ┆ 1980 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 960818s1980    ┆ null           ┆ null          ┆ ["(Brož.)"]    ┆ … ┆ nam a22     1  ┆ bk198200854   ┆ 195   ┆ 1980 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 961126s1981    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22     1  ┆ bk198202715   ┆ 85    ┆ 1981 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ |…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 860311s1986    ┆ null           ┆ ["11,50 Kčs"] ┆ ["(Brož.) :"]  ┆ … ┆ nam a22        ┆ ck8601063     ┆ 200   ┆ 1986 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ u0…            ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 860507s1986    ┆ null           ┆ ["Kčs 13,00"] ┆ ["(Váz.) :"]   ┆ … ┆ nam a22        ┆ ck8601854     ┆ 72    ┆ 1986 │
│ xr af          ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 860620s1986    ┆ null           ┆ ["4 Kčs"]     ┆ ["(Brož.) :"]  ┆ … ┆ nam a22        ┆ ck8603710     ┆ 26    ┆ 1986 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ u0…            ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 890201s1988    ┆ null           ┆ ["13 Kčs"]    ┆ ["(Váz.) :"]   ┆ … ┆ nam a22        ┆ ck8900933     ┆ 68    ┆ 1988 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ u0…            ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 890427s1988    ┆ null           ┆ ["18,50 Kčs"] ┆ ["(Brož.) :"]  ┆ … ┆ nam a22        ┆ ck8903840     ┆ 180   ┆ 1988 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ u0…            ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 890712s1989    ┆ null           ┆ ["11,50 Kčs"] ┆ ["(Brož.) :"]  ┆ … ┆ nam a22        ┆ ck8905634     ┆ 200   ┆ 1989 │
│ xr a           ┆                ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ u0…            ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 910321s1990    ┆ ["80-04-25209- ┆ ["13 Kčs"]    ┆ ["(váz.) :"]   ┆ … ┆ nam a22        ┆ ck9100908     ┆ 68    ┆ 1990 │
│ xr a           ┆ 5"]            ┆               ┆                ┆   ┆ 4500           ┆               ┆       ┆      │
│ u0…            ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 000619s2000    ┆ ["80-85920-62- ┆ null          ┆ ["(brož.)"]    ┆ … ┆ cam a22      a ┆ cpk2000088598 ┆ 259   ┆ 2000 │
│ xr ae  d p     ┆ X"]            ┆               ┆                ┆   ┆ 4500           ┆ 1             ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 040202s2004    ┆ ["80-86706-03- ┆ null          ┆ ["(brož.)"]    ┆ … ┆ cam a22      a ┆ cpk2004131277 ┆ 156   ┆ 2004 │
│ xr a   g p     ┆ 6"]            ┆               ┆                ┆   ┆ 4500           ┆ 0             ┆       ┆      │
│ 0…             ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
│ 100317s1959    ┆ null           ┆ null          ┆ null           ┆ … ┆ nam a22      a ┆ cpk2010209119 ┆ 87    ┆ 1959 │
│ xr             ┆                ┆               ┆                ┆   ┆ 4500           ┆ 9             ┆       ┆      │
│ …              ┆                ┆               ┆                ┆   ┆                ┆               ┆       ┆      │
└────────────────┴────────────────┴───────────────┴────────────────┴───┴────────────────┴───────────────┴───────┴──────┘