In [1]:
import os
import json
import datetime
import warnings
import polars as pl
import pandas as pd
import altair as alt

from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.hezke_jmeno import hezke_jmeno
from src.kristi_promin import kristi_promin
from src.me_to_neurazi import me_to_neurazi

with open(os.path.join('src','kredity.json'), 'r', encoding='utf-8') as kredity:
    kredity = json.loads(kredity.read())
pl.Config(tbl_rows=100)
alt.data_transformers.disable_max_rows()
alt.themes.register('irozhlas', kristi_promin)
alt.themes.enable('irozhlas')
warnings.filterwarnings('ignore')

In [2]:
aut = pl.read_parquet(
    os.path.join("data","aut_vyber.parquet")
).explode(
    "370_c"
).filter(
    pl.col("370_c").str.contains("Česk")
).explode(
    "100_7"
).select(
    ["100_a","100_7","370_c","374_a","375_a","678_a"]
)

In [3]:
cesi = aut.filter(pl.col("370_c").str.contains("Česk")).select(pl.col("100_7").unique()).to_series().to_list()

In [4]:
len(cesi)

267043

In [5]:
aut.sample(10)

shape: (10, 6)
┌──────────────────────┬───────────────┬───────┬──────────────────────────┬───────────┬────────────────────────────────┐
│ 100_a                ┆ 100_7         ┆ 370_c ┆ 374_a                    ┆ 375_a     ┆ 678_a                          │
│ ---                  ┆ ---           ┆ ---   ┆ ---                      ┆ ---       ┆ ---                            │
│ list[str]            ┆ str           ┆ str   ┆ list[str]                ┆ list[str] ┆ list[str]                      │
╞══════════════════════╪═══════════════╪═══════╪══════════════════════════╪═══════════╪════════════════════════════════╡
│ ["Kočí, Tomáš"]      ┆ hka2011660244 ┆ Česko ┆ ["houslisté"]            ┆ ["muž"]   ┆ ["Houslista v dětském          │
│                      ┆               ┆       ┆                          ┆           ┆ pěveckém…                      │
│ ["Bláhová, Helena"]  ┆ jk01012231    ┆ Česko ┆ null                     ┆ null      ┆ ["Autorka německé čítanky."]   │
│ null                 ┆ null          ┆ Česko ┆ null                     ┆ null      ┆ null                           │
│ ["Novák, Radek"]     ┆ pag2010609511 ┆ Česko ┆ null                     ┆ null      ┆ ["Překladatel."]               │
│ ["Velichová, Laďka"] ┆ ola2011650770 ┆ Česko ┆ null                     ┆ null      ┆ ["Autorka románu, pedagožka."] │
│ ["Beranová, Lenka,"] ┆ ola2002152641 ┆ Česko ┆ null                     ┆ null      ┆ ["Narozena 3.10.1955 ve        │
│                      ┆               ┆       ┆                          ┆           ┆ Vysoké…                        │
│ ["Čadková, Marie,"]  ┆ js20080323014 ┆ Česko ┆ null                     ┆ null      ┆ ["Narozena 1956 v Hodoníně.    │
│                      ┆               ┆       ┆                          ┆           ┆ Ph…                            │
│ ["Havel, Vít"]       ┆ xx0276308     ┆ Česko ┆ ["lékaři", "internisté", ┆ ["muž"]   ┆ ["MUDr., pneumolog, ftizeolog  │
│                      ┆               ┆       ┆ "pneu…                   ┆           ┆ …                              │
│ ["Svoboda, Karel,"]  ┆ jk01122034    ┆ Česko ┆ null                     ┆ null      ┆ ["Narozen 8.1.1914 v Brandýse  │
│                      ┆               ┆       ┆                          ┆           ┆ …                              │
│ null                 ┆ null          ┆ Česko ┆ null                     ┆ null      ┆ null                           │
└──────────────────────┴───────────────┴───────┴──────────────────────────┴───────────┴────────────────────────────────┘

In [6]:
len(cesi)

267043

In [7]:
cesi

['skuk0002160',
 'jx20110614027',
 'xx0084196',
 'jk01010710',
 'pna2007389192',
 'mub2017944429',
 'jk01152668',
 'xx0109086',
 'xx0140371',
 'xx0320769',
 'jk01011049',
 'ola200207395',
 'ola20201081078',
 'jx20110906012',
 'pag20241220416',
 'jk01010721',
 'jk01082503',
 'jo2015863683',
 'ola200205423',
 'xx0155122',
 'jo2016926442',
 'ola20211132994',
 'jo2007399880',
 'jx20060403056',
 'xx0033513',
 'osa20181013635',
 'jo2012708849',
 'jk01110882',
 'xx0002139',
 'mzk2007377767',
 'av20191035109',
 'jk01122839',
 'xx0054521',
 'xx0040388',
 'mzk2016931891',
 'xx0207941',
 'xx0075191',
 'mzk2014844167',
 'xx0008246',
 'jo2004232679',
 'jk01140072',
 'mzk2004148302',
 'mzk2005266267',
 'pna2010561744',
 'mzk2010612596',
 'jo2018991573',
 'mzk2014836816',
 'xx0201923',
 'jk01102048',
 'ola2008474690',
 'ola20211133534',
 'xx0267202',
 'kv2015863749',
 'xx0141688',
 'xx0088573',
 'js20090519002',
 'xx0316928',
 'xx0083151',
 'mzk20231183672',
 'jk01020326',
 'xx0209201',
 'jk01150954',
 'jo2012732505',
 'ola20040302003',
 'jx20080226011',
 'jk01032004',
 'pna20231193036',
 'jk01012444',
 'jk01020047',
 'xx0098023',
 'mub2011671361',
 'jx20080310052',
 'xx0303248',
 'xx0226698',
 'xx0033458',
 'jk01030806',
 'xx0072787',
 'ola200201571',
 'mzk2012714314',
 'jx20110831023',
 'ola200202645',
 'ola2002145081',
 'xx0075810',
 'jk01120748',
 'xx0328134',
 'hka0057286',
 'jo20181010380',
 'jx20050727028',
 'xx0102148',
 'jk01040372',
 'xx0309398',
 'jk01033296',
 'jx20071203056',
 'ola20201078354',
 'ola20241223133',
 'xx0007608',
 'jk01031267',
 'xx0061338',
 'jo2013752412',
 'jk01090127',
 'xx0311590',
 'jn20000402235',
 'mzk2015867151',
 'ola2006319206',
 'mzk2012720193',
 'hka2016902564',
 'hka2010611978',
 'vse20221140721',
 'xx0094032',
 'xx0152829',
 'xx0264764',
 'xx0153904',
 'jo2014806753',
 'jn20001005383',
 'ola2007364468',
 'jk01093448',
 'ola200203874',
 'ola2013790747',
 'mzk2010602972',
 'xx0308426',
 'jn20000810314',
 'ola2006345499',
 'jk01032577',
 'jx20070905024',
 'pna2011675988',
 'hka2013774800',
 'ola2002146734',
 'jk01051764',
 'ola200202689',
 'jn20000401748',
 'jk01061710',
 'pna2011666494',
 'xx0153468',
 'xx0031662',
 'jn20000728344',
 'jk01101347',
 'xx0079883',
 'xx0065336',
 'mzk2009544394',
 'xx0091575',
 'pna2016906840',
 'jx20070806008',
 'xx0242788',
 'mzk2014832619',
 'ola20201065019',
 'jk01080495',
 'xx0233838',
 'xx0326872',
 'xx0139746',
 'ola20231179925',
 'jo2012720187',
 'jk01061148',
 'jk01030270',
 'ola20201097353',
 'ola2004235622',
 'jk01030022',
 'jo20221163278',
 'xx0201938',
 'mzk20201077788',
 'jk01073276',
 'mzk2005318198',
 'kpwa2636',
 'jx20080206013',
 'jk01062027',
 'xx0170939',
 'jo2009268168',
 'xx0083412',
 'ola2006329811',
 'jo20191042833',
 'jx20140127001',
 'xx0326660',
 'mub20191050002',
 'jo2002157597',
 'jo2017945300',
 'jk01122303',
 'ola2012722507',
 'jk01102688',
 'pna2005292268',
 'jk01080951',
 'uzp2009465463',
 'xx0139583',
 'ola2002158432',
 'xx0172642',
 'jk01062897',
 'jx20050607034',
 'jk01070620',
 'jn20000710093',
 'mzk2011631251',
 'jn19990209300',
 'mzk2008486373',
 'ola200207937',
 'xx0227311',
 'mzk20231206402',
 'jk01050059',
 'jk01070758',
 'xx0100633',
 'ntk2013780781',
 'jk01131574',
 'xx0066532',
 'uzp2011673619',
 'mzk2018981875',
 'xx0074079',
 'ola2006319195',
 'mzk2002157095',
 'xx0006834',
 'js20121109002',
 'mzk2013792567',
 'uzp20201079309',
 'jn20010420044',
 'jk01080565',
 'xx0277981',
 'nlk20010095012',
 'jk01071224',
 'ola2011630484',
 'xx0167615',
 'jk01042553',
 'jk01130006',
 'jk01131960',
 'mzk2003194590',
 'xx0073567',
 'jx20051121016',
 'xx0084445',
 'xx0133811',
 'xx0236541',
 'jo2016913047',
 'jk01051911',
 'jk01020828',
 'mzk2010610465',
 'jk01030736',
 'jx20060403071',
 'kpwa1322',
 'xx0070690',
 'jo2002103142',
 'mzk2006343149',
 'xx0305046',
 'xx0108069',
 'mzk2002144853',
 'xx0196204',
 'xx0257549',
 'jk01061302',
 'xx0072649',
 'jo2017940893',
 'xx0006171',
 'mzk2005273032',
 'jk01033541',
 'xx0145054',
 'av20221146916',
 'jk01022948',
 'jk01110070',
 'jk01030068',
 'mzk2004243934',
 'mzk2005294698',
 'nlk19990072985',
 'mzk20221167987',
 'jx20071204058',
 'jk01032901',
 'xx0309823',
 'jk01091852',
 'mzk2002160618',
 'jx20071122042',
 'xx0098628',
 'pna20231198286',
 'mub2016934186',
 'xx0009388',
 'jo2004213806',
 'jo2003197109',
 'jx20050513008',
 'jk01111367',
 'jk01152029',
 'jn20000401926',
 'mzk20201078421',
 'mub2014802165',
 'jk01072743',
 'jx20051220022',
 'jx20040729027',
 'xx0306823',
 'xx0073833',
 'mzk20201089529',
 'ola20231175280',
 'jk01131890',
 'mzk20251249743',
 'jk01072255',
 'jo2008479071',
 'ntka174052',
 'xx0130235',
 'jx20080905010',
 'jo19990051635',
 'xx0099208',
 'mzk2008443003',
 'mzk2009496363',
 'xx0018262',
 'xx0128650',
 'jn20000620417',
 'jo2011631583',
 'jx20071203035',
 'jx20071203072',
 'xx0125284',
 'xx0208795',
 'mzk2005295036',
 'jn19990218024',
 'mzk2002145240',
 'pna2006312061',
 'xx0038357',
 'js20090421015',
 'jk01013032',
 'mzk2006322987',
 'xx0168548',
 'jk01073366',
 'xx0312657',
 'xx0030976',
 'xx0092590',
 'jk01152269',
 'jx20100415010',
 'xx0308434',
 'mub20191028927',
 'ola2011620285',
 'xx0313407',
 'jk01122116',
 'mub20231203633',
 'xx0149023',
 'av20201091633',
 'mzk2010614515',
 'jk01092766',
 'jn20000400650',
 'xx0006037',
 'jo20181005885',
 'jk01010657',
 'ola2002153391',
 'jo20010091792',
 'ntka174040',
 'zcu2016909624',
 'jo20010088896',
 'xx0323550',
 'xx0060741',
 'ntka174467',
 'mzk2010585830',
 'kpwa11226',
 'jo2015856070',
 'nlk20000085143',
 'hka2010593536',
 'mzk2004249145',
 'kpwa6109',
 'jk01061743',
 'jk01021680',
 'jn20000402000',
 'kpwa2124',
 'xx0125336',
 'jo20231191311',
 'xx0212000',
 'ola20241214648',
 'jk01010632',
 'av20191019713',
 'jk01130245',
 'xx0282317',
 'xx0104600',
 'xx0192159',
 'xx0227673',
 'xx0243026',
 'xx0134816',
 'xx0303257',
 'pna20241216577',
 'mzk20201079431',
 'pna2009551213',
 'av20231204936',
 'ola200209107',
 'mzk2013749550',
 'jo2003204301',
 'jk01052975',
 'jk01092758',
 'jo2012705401',
 'xx0238704',
 'xx0327813',
 'jx20090814041',
 'jn20000402871',
 'jo20000080553',
 'jx20101206006',
 'xx0104146',
 'jo2016902041',
 'jk01082531',
 'jo2018996991',
 'xx0274679',
 'jk01032279',
 'mzk2005282326',
 'ola2006340370',
 'mzk2012728153',
 'xx0227577',
 'mzk2002145070',
 'jk01151193',
 'xx0031919',
 'xx0041213',
 'jk01141596',
 'xx0033078',
 'jn19981000835',
 'xx0101837',
 'jx20050621044',
 'xx0273121',
 'mzk2004236702',
 'jk01142090',
 'xx0052830',
 'xx0126569',
 'xx0138257',
 'hka2013773224',
 'mzk2003202447',
 'jk01023291',
 'xx0200775',
 'jk01102027',
 'jk01130368',
 'xx0106744',
 'ola20040310006',
 'xx0224585',
 'mzk2005317911',
 'av2017954502',
 'js20060505023',
 'jk01050258',
 'jk01081328',
 'xx0084393',
 'jo2003193376',
 'pna2007389193',
 'js20020527003',
 'pna2014830789',
 'js20120112003',
 'vut2013749053',
 'ola2002111857',
 'mzk2003171437',
 'xx0091957',
 'ola2014832743',
 'mzk2011631272',
 'xx0256456',
 'mzk2008453220',
 'xx0204219',
 'jk01021016',
 'mzk2005300861',
 'jk01110383',
 'xx0313999',
 'jk01052160',
 'hka2015859159',
 'av20241218730',
 'jk01011835',
 'uzp2009504226',
 'xx0024105',
 'ntka172066',
 'xx0316494',
 'pna20221155842',
 'jk01142476',
 'jk01042745',
 'xx0002920',
 'xx0185878',
 'xx0214271',
 'jn19981002460',
 'xx0073470',
 'hka2011662210',
 'xx0180599',
 'xx0275985',
 'osa2013791527',
 'mzk2010581785',
 'nlk20000087468',
 'jk01150843',
 'ola200206707',
 'mzk2013762606',
 'xx0187420',
 'js20050606003',
 'xx0244780',
 'xx0080690',
 'xx0102470',
 'jk01092188',
 'ola20231209609',
 'xx0016732',
 'xx0276308',
 'jx20050621049',
 'jk01060696',
 'xx0115950',
 'xx0243730',
 'jx20050216010',
 'jx20110629002',
 'mzk2017953450',
 'xx0267977',
 'xx0312820',
 'ntka174290',
 'jk01053281',
 'xx0098088',
 'jn20000810067',
 'jn20000703085',
 'jk01090628',
 'jn20001227605',
 'jo2006324953',
 'ntka173306',
 'jn20020716430',
 'pag2008454886',
 'jk01051511',
 'xx0107703',
 'xx0168265',
 'mzk2005279384',
 'xx0268508',
 'jk01052259',
 'xx0304292',
 'xx0274249',
 'xx0278037',
 'jn99240000568',
 'ola20201087648',
 'jk01013215',
 'skuk0001201',
 'jk01150320',
 'jk01111805',
 'mzk2009502207',
 'xx0211570',
 'xx0318557',
 'xx0134912',
 'ola2011653619',
 'xx0006043',
 'ntk20231208427',
 'mzk2005282641',
 'xx0243437',
 'jn20000710251',
 'pna2009482569',
 'xx0132479',
 'pna2016904234',
 'ntka173694',
 'mzk2002156974',
 'hka2013783382',
 'ola2002113809',
 'jk01100164',
 'mzk20231196994',
 'jz8600247',
 'xx0098790',
 'mzk20181019045',
 'stk2008428618',
 'xx0064640',
 'ola2002159625',
 'mzk2009502324',
 'jk01021211',
 'av2016923201',
 'osa2017951071',
 'xx0316275',
 'pna2008424760',
 'jx20090921039',
 'xx0165629',
 'xx0086128',
 'xx0153845',
 'xx0029962',
 'xx0095940',
 'mzk20211126271',
 'xx0094654',
 'mub20241229776',
 'jk01103360',
 'hka2012699617',
 'hka2013756121',
 'xx0192628',
 'mub2011669624',
 'jk01121398',
 'jo2012737396',
 'pag2016903177',
 'ola20201071698',
 'xx0262835',
 'xx0184198',
 'mzk20221164490',
 'xx0303473',
 'ola2014845920',
 'jk01081479',
 'js20080821004',
 'mzk2013796347',
 'jn20000620287',
 'jk01020908',
 'mzk2007424015',
 'jn19981001233',
 'mzk2004246366',
 'mzk20191045649',
 'mzk2011641919',
 'mzk2002163410',
 'xx0206080',
 'mzk2006348633',
 'mzk2011673182',
 'xx0106434',
 'jk01061358',
 'jk01070820',
 'xx0083399',
 'xx0022162',
 'ntk2013762546',
 'jk01031850',
 'jk01131112',
 'uzp2012706284',
 'mzk2013753136',
 'pna2014830426',
 'jo20191040234',
 'kup19960000081936',
 'jo2013781253',
 'jk01023168',
 'ola20201077856',
 'xx0151166',
 'jk01070348',
 'ntka172316',
 'jk01082120',
 'jx20071128081',
 'jk01101067',
 'xx0004205',
 'xx0056989',
 'jx20051111040',
 'mzk2013760754',
 'xx0160473',
 'jk01033041',
 'xx0187316',
 'xx0208231',
 'av20221142992',
 'xx0308261',
 'jk01152517',
 'jk01051371',
 'jk01021560',
 'mzk2007417233',
 'jk01093145',
 'mzk2012725484',
 'jk01041504',
 'mzk2013791555',
 'jo2016920777',
 'kv2012701408',
 'jk01122769',
 'jk01101548',
 'mzk2012685212',
 'jk01031361',
 'mzk2006343269',
 'jx20080519014',
 'ola200201115',
 'mzk2004246456',
 'jx20111004009',
 'jk01132805',
 'js20110830003',
 'xx0134078',
 'jn20000401482',
 'av20191031825',
 'jk01132694',
 'mzk2007430848',
 'xx0237578',
 'js20060526031',
 'mzk2010612833',
 'xx0092556',
 'mzk2012720874',
 'xx0034781',
 'mzk2010508350',
 'jo2017954238',
 'jk01081827',
 'mzk2005269915',
 'jk01130019',
 'uzp2009465495',
 'jx20071212026',
 'jk01150727',
 'xx0145030',
 'xx0307119',
 'jk01152548',
 'mub2014828216',
 'ola2006345322',
 'jk01052613',
 'jk01151077',
 'jk01131448',
 'xx0177829',
 'xx0007901',
 'jk01130829',
 'jx20120713004',
 'ola2015861824',
 'xx0003703',
 'osa2015862469',
 'pna2005281025',
 'jn99240001312',
 'mzk2012715937',
 'mzk2016922543',
 'xx0012271',
 'jk01081066',
 'ola2010578861',
 'jk01090360',
 'mzk2005318090',
 'jk01063472',
 'jk01090593',
 'xx0212184',
 'mzk2002106521',
 'mzk2014824935',
 'jn20010310184',
 'hka2011620893',
 'xx0008886',
 'jk01151660',
 'xx0237887',
 'mzk2004246446',
 'mzk2008430451',
 'mzk2004236837',
 'jn20001227216',
 'mzk2006355829',
 'mzk2015853371',
 'stk2008428823',
 'xx0106964',
 'mzk2002113116',
 'jk01030687',
 'nlk20000087319',
 'xx0229643',
 'jn99240000807',
 'jx20070509016',
 'xx0277576',
 'jx20080404009',
 'jk01011854',
 'xx0146775',
 'jk01121498',
 'jn20010309291',
 'xx0016211',
 'ola2018999025',
 'jx20060324038',
 'xx0199073',
 'jk01072390',
 'jn20000807005',
 'jk01090411',
 'xx0129000',
 'ntk2012717201',
 'mzk2014815429',
 'jk01050900',
 'xx0255168',
 'ola2007364432',
 'uzp2012721278',
 'xx0325133',
 'xx0125782',
 'kv2015879206',
 'ola2015864820',
 'stk2008461327',
 'xx0130576',
 'xx0139175',
 'js20120815002',
 'jk01051706',
 'js20050703045',
 'xx0303003',
 'xx0090982',
 'pag2007414601',
 'jk01010533',
 'xx0229486',
 'xx0105397',
 'xx0062335',
 'mub2011669652',
 'mzk2007424013',
 'pna2014835872',
 'xx0070786',
 'jk01031213',
 'xx0128816',
 'osa2018994193',
 'js20090430004',
 'jn20000710490',
 'ola2017949113',
 'mzk20241228199',
 'mzk2015871158',
 'ola2008434576',
 'jk01130107',
 'ola200203337',
 'jo2016913742',
 'jo20181003766',
 'xx0242479',
 'xx0007741',
 'jk01061362',
 'jx20061212002',
 'jk01083263',
 'mzk2005266515',
 'pna2008482523',
 'mzk2006354272',
 'kpwa5287',
 'mzk2009533580',
 'ola2003206375',
 'jo2012684051',
 'xx0154210',
 'xx0010066',
 'js20090609003',
 'xx0076621',
 'jo2012732447',
 'mzk20231206046',
 'hka2013792291',
 'jx20050722023',
 'hka2010576054',
 'jx20061127014',
 'xx0119837',
 'nlk20000084103',
 'xx0194884',
 'xx0109753',
 'jk01060375',
 'jk01152880',
 'jn20001227122',
 'jk01151306',
 'xx0064474',
 'ola2010548320',
 'xx0206498',
 'jk01032570',
 'xx0096672',
 'jk01121384',
 'xx0172098',
 'xx0242218',
 'jk01041120',
 'mzk2006377729',
 'jk01111887',
 'jo20000082873',
 'jn20000710134',
 'xx0018231',
 'xx0039760',
 'xx0095444',
 'jk01012421',
 'mzk2010583402',
 'xx0107739',
 'jx20110324016',
 'xx0140393',
 'ntk2013773482',
 'pna2018995763',
 'jn20000400863',
 'xx0058333',
 'hka20191026027',
 'jk01032436',
 'js20050926023',
 'mzk2003208500',
 'jn20001103125',
 'xx0316362',
 'jn20000400939',
 'jn19990209746',
 'xx0108148',
 'mzk2006368425',
 'jx20070918040',
 'jo20191053496',
 'uk20201074356',
 'jn19990010050',
 'mzk2009517456',
 'xx0259257',
 'jk01081056',
 'jk01023157',
 'xx0110956',
 'nlk20000089570',
 'jo20000069665',
 'ola2008455931',
 'xx0128515',
 'mzk2012707644',
 'jk01140748',
 'jo2008399898',
 'pna2012691766',
 'xx0283804',
 'js20090313003',
 'xx0054102',
 'ola2002113957',
 'jk01111200',
 'js20070311007',
 'js20100503002',
 'xx0134727',
 'jk01151593',
 'xx0201627',
 'ola2003199594',
 'xx0229787',
 'xx0252192',
 'mzk2005286568',
 'xx0305467',
 'jk01132528',
 'ola200208172',
 'xx0001297',
 'jo2002105212',
 'jx20110714011',
 'xx0001140',
 'jk01120746',
 'pna2007370934',
 'xx0072060',
 'mzk2006320213',
 'xx0275217',
 'jk01022747',
 'jk01041334',
 'ntka172158',
 'ola2004235515',
 'jo2011668471',
 'jo20191028494',
 'jk01041648',
 'ola20201066333',
 'jo2012734079',
 'mzk2014810503',
 'xx0001909',
 'xx0069818',
 'pna2015876459',
 'xx0227390',
 'xx0324056',
 'xx0238149',
 'jz8600236',
 'jx20070509010',
 'xx0225618',
 'xx0271816',
 'ola20221171308',
 'jx20091112019',
 'xx0232410',
 'mzk2013749353',
 'jk01110488',
 'jk01021639',
 'jo2016923403',
 'av20191045563',
 'xx0113929',
 'mzk2007417152',
 'ctu2015858214',
 'jo20000074325',
 'jx20080924034',
 'ola2004231489',
 'xx0018202',
 'xx0174913',
 'xx0322029',
 'xx0322104',
 'mzk2013767105',
 'jk01081037',
 'ntk2012719315',
 'jk01090026',
 'mzk2007377642',
 'xx0086213',
 'xx0323179',
 'jx20080613002',
 'ola20191021300',
 'jk01041093',
 'xx0213742',
 'jk01131752',
 'xx0311609',
 'xx0139993',
 'jk01080839',
 'jk01020241',
 'mzk20181017542',
 'xx0310202',
 'xx0047448',
 'ola2006323431',
 'jk01040159',
 'jk01012629',
 'xx0271514',
 'pna2009525842',
 'mzk2016904011',
 'jk01053030',
 'ntka173274',
 'pna2013773841',
 'xx0271180',
 'ola20241235495',
 'jk01010651',
 'jk01041367',
 'hka2018989981',
 'xx0095268',
 'mzk20181008040',
 'mzk2014805074',
 'xx0277325',
 'kv2010540373',
 'jk01130237',
 'xx0274684',
 'ola2006340312',
 'xx0269144',
 'hka2010554628',
 'mzk2016935453',
 'xx0216585',
 'mub20201066605',
 'ola200203369',
 'xx0178920',
 'jx20041217020',
 'mzk2017973008',
 'mzk2002113132',
 'xx0324382',
 'xx0006937',
 'jk01092602',
 'jo2015894247',
 'xx0050730',
 'jn19990209455',
 'mzk2007423941',
 'mzk2002156828',
 'jx20090206007',
 'ola200203335',
 'ola2002159121',
 'xx0159579',
 'xx0006287',
 'jk01122602',
 'xx0277270',
 'jx20071120050',
 'xx0243373',
 'xx0255436',
 'ola200208733',
 'xx0023913',
 'jk01071459',
 'ola2015862061',
 'jx20070419011',
 'xx0072978',
 'xx0153021',
 'jo2017949723',
 'pna2012677786',
 'xx0117556',
 'xx0007980',
 'mzk2004221700',
 'mzk2012685211',
 'jo2012724440',
 'xx0092898',
 'jx20120104001',
 'jo2017975406',
 'xx0202483',
 'xx0326437',
 'ola20221151398',
 'jk01142263',
 'ola2002142276',
 'jn20031211001',
 'jx20050704012',
 'ola2017970432',
 'hka0075827',
 'ola2003191800',
 'ola200208284',
 'xx0197377',
 'jk01062266',
 'jn20001227230',
 'mzk2011648090',
 'jn20000728169',
 'pna2013761502',
 'xx0155436',
 'jo2016899469',
 'av20231182167',
 'jo2005259942',
 'xx0207028',
 'jk01072622',
 ...]

In [8]:
df = pl.read_parquet(os.path.join("data","cnb_ceska_proza.parquet")).rename({'autorstvo_kod':'100_7'})
df = pl.concat([df, pl.read_parquet(os.path.join("data","cnb_ceska_poezie.parquet"))])
spisovatelstvo = list(set(df.select(pl.col('100_7')).drop_nulls().to_series().to_list()))

In [9]:
len(spisovatelstvo)

18992

In [10]:
df = pl.read_parquet(os.path.join("data/cnb_sloupce","100.parquet"))
df = df.filter(pl.col("100_7").is_in(cesi))
df = df.join(aut, left_on="100_7", right_on="100_7", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","072.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","655.parquet")), left_on="001", right_on="001", how="left")
df.explode("655_a").group_by("655_a").len().top_k(100, by="len")

shape: (100, 2)
┌─────────────────────────────────┬────────┐
│ 655_a                           ┆ len    │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ null                            ┆ 186758 │
│ učebnice vysokých škol          ┆ 42516  │
│ příručky                        ┆ 34773  │
│ studie                          ┆ 21628  │
│ publikace pro děti              ┆ 21145  │
│ monografie                      ┆ 21065  │
│ textbooks (higher)              ┆ 20797  │
│ handbooks and manuals           ┆ 17960  │
│ místní pohlednice               ┆ 17932  │
│ česká poezie                    ┆ 17034  │
│ české romány                    ┆ 16841  │
│ monographs                      ┆ 16677  │
│ children's literature           ┆ 15169  │
│ Czech fiction                   ┆ 12428  │
│ Czech poetry                    ┆ 12073  │
│ populární hudba                 ┆ 9994   │
│ české příběhy                   ┆ 9515   │
│ informační publikace            ┆ 9372   │
│ české povídky                   ┆ 8949   │
│ učebnice středních škol         ┆ 8813   │
│ studies                         ┆ 8690   │
│ fotografické publikace          ┆ 8460   │
│ Czech stories                   ┆ 8243   │
│ přehledy                        ┆ 7873   │
│ populárně-naučné publikace      ┆ 7801   │
│ pohlednice kulturních památek   ┆ 7157   │
│ metodické příručky              ┆ 7153   │
│ kompaktní disky                 ┆ 7067   │
│ photographical works            ┆ 6956   │
│ vokální linky s podloženým tex… ┆ 6893   │
│ kolektivní monografie           ┆ 6832   │
│ učebnice základních škol        ┆ 6830   │
│ collective monographs           ┆ 6756   │
│ obrazové publikace              ┆ 6717   │
│ popular music                   ┆ 6633   │
│ information publications        ┆ 6361   │
│ partitury                       ┆ 6085   │
│ popular works                   ┆ 6068   │
│ pojednání                       ┆ 5940   │
│ biografie                       ┆ 5897   │
│ české prózy                     ┆ 5818   │
│ sborníky                        ┆ 5509   │
│ partitury pro sólový nástroj    ┆ 5467   │
│ CD-ROM                          ┆ 5355   │
│ hlasy                           ┆ 5312   │
│ scores                          ┆ 5200   │
│ pracovní sešity                 ┆ 5133   │
│ pictorial works                 ┆ 4997   │
│ surveys                         ┆ 4858   │
│ scores for solo instrument      ┆ 4840   │
│ písně                           ┆ 4794   │
│ učebnice                        ┆ 4730   │
│ publikace pro mládež            ┆ 4630   │
│ essays                          ┆ 4577   │
│ parts                           ┆ 4554   │
│ autobiografické vzpomínky       ┆ 4548   │
│ kuchařské recepty               ┆ 4539   │
│ methodological manuals          ┆ 4422   │
│ activity books                  ┆ 4375   │
│ průvodce                        ┆ 4199   │
│ nástěnné vícelisté kalendáře    ┆ 4193   │
│ česká dramata                   ┆ 4084   │
│ Czech short stories             ┆ 4065   │
│ katalogy výstav                 ┆ 4060   │
│ Czech prose                     ┆ 3962   │
│ autobiographical reminiscences  ┆ 3845   │
│ učební texty                    ┆ 3706   │
│ brožury                         ┆ 3698   │
│ vocal parts with text           ┆ 3686   │
│ biography                       ┆ 3598   │
│ textbooks (elementary)          ┆ 3517   │
│ jubilejní publikace             ┆ 3454   │
│ aranžmá (hudba)                 ┆ 3328   │
│ úvahy                           ┆ 3324   │
│ české pohádky                   ┆ 3290   │
│ cookbooks                       ┆ 3219   │
│ textbooks (secondary)           ┆ 3098   │
│ praktická cvičení               ┆ 3040   │
│ vzpomínky                       ┆ 2981   │
│ příběhy                         ┆ 2972   │
│ polky                           ┆ 2946   │
│ educational texts               ┆ 2891   │
│ songs                           ┆ 2753   │
│ historické romány               ┆ 2707   │
│ exhibition catalogs             ┆ 2669   │
│ leporela                        ┆ 2631   │
│ stolní kalendáře                ┆ 2612   │
│ rozhovory                       ┆ 2597   │
│ výstavní plakáty                ┆ 2549   │
│ bibliofilie                     ┆ 2516   │
│ valčíky                         ┆ 2502   │
│ textbooks                       ┆ 2500   │
│ literatura faktu                ┆ 2492   │
│ výbory                          ┆ 2490   │
│ teze                            ┆ 2467   │
│ waltzes                         ┆ 2388   │
│ jubilee books                   ┆ 2382   │
│ abstracts                       ┆ 2360   │
│ Textbooks                       ┆ 2351   │
│ guidebooks                      ┆ 2346   │
└─────────────────────────────────┴────────┘

In [11]:
df = df.explode("655_a").explode("072_x")

## 1. verze

In [13]:
poezie = df.filter(
    pl.col('655_a').str.contains('poez|poetr') | pl.col("072_x").str.contains('poez')
).with_columns(
    kategorie = pl.lit('poezie')
)

proza = df.filter(
    pl.col('655_a').str.contains('román|fiction|novel|příbě|povíd|próz') | pl.col('072_x').str.contains('román|fiction|novel|příbě|povíd|próz')
).with_columns(
    kategorie = pl.lit('próza')
)

vzpominky = df.filter(
    pl.col('655_a').str.contains('vzpomínky|autobiographical')
).with_columns(
    kategorie = pl.lit('vzpomínky')
)

In [14]:
do_grafu = pl.concat(
    [poezie, proza, vzpominky]
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).sort(
    by="rok"
).unique(
    subset=['100_a','245_a'],keep='first'
)

In [15]:
vek = pl.read_parquet(os.path.join("data","narozeni-umrti-gender.parquet"))
do_grafu = do_grafu.join(vek, on="100_7", how="left").with_columns((pl.col("rok") - pl.col("narozeni")).alias("vek"))

In [16]:
do_grafu = do_grafu.drop_nulls("narozeni")

In [17]:
do_grafu = do_grafu.filter(pl.col("vek").is_between(15,100))

In [18]:
do_grafu.sort(by="vek").head(n=10)

shape: (10, 44)
┌──────────┬─────────────────────────────┬────────────────┬────────────────┬───┬──────────┬───────┬────────┬─────┐
│ 100_ind1 ┆ 100_a                       ┆ 100_7          ┆ 100_4          ┆ … ┆ narozeni ┆ umrti ┆ gender ┆ vek │
│ ---      ┆ ---                         ┆ ---            ┆ ---            ┆   ┆ ---      ┆ ---   ┆ ---    ┆ --- │
│ str      ┆ str                         ┆ str            ┆ list[str]      ┆   ┆ i64      ┆ i64   ┆ str    ┆ i64 │
╞══════════╪═════════════════════════════╪════════════════╪════════════════╪═══╪══════════╪═══════╪════════╪═════╡
│ 1        ┆ Vokurková, Františka Sylva, ┆ xx0228767      ┆ ["aut"]        ┆ … ┆ 2003     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Paťhová, Magdaléna,         ┆ xx0302475      ┆ ["aut"]        ┆ … ┆ 2008     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Trojovská, Inesa,           ┆ xx0060696      ┆ ["aut"]        ┆ … ┆ 1993     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Grygar, Tomáš,              ┆ ola20221138391 ┆ ["aut"]        ┆ … ┆ 2006     ┆ null  ┆ m      ┆ 15  │
│ 1        ┆ Paťhová, Magdaléna,         ┆ xx0302475      ┆ ["aut"]        ┆ … ┆ 2008     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Paťhová, Magdaléna,         ┆ xx0302475      ┆ ["aut"]        ┆ … ┆ 2008     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Kneřová, Bety,              ┆ mzk2009543980  ┆ ["aut"]        ┆ … ┆ 1994     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Braunová, Vlasta,           ┆ jo2018980786   ┆ ["aut"]        ┆ … ┆ 2002     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Shaft, Terry,               ┆ xx0218245      ┆ ["aut"]        ┆ … ┆ 2002     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Ratolístka, Ludvík,         ┆ jo2003193192   ┆ ["aut", "pbl"] ┆ … ┆ 1886     ┆ 1953  ┆ m      ┆ 15  │
└──────────┴─────────────────────────────┴────────────────┴────────────────┴───┴──────────┴───────┴────────┴─────┘

In [19]:
do_grafu = do_grafu.filter((pl.col("umrti") >= pl.col('rok')) | pl.col("umrti").is_null())

## Mediánový věk

In [21]:
do_grafu.group_by("kategorie").agg(pl.col("vek").median())

shape: (3, 2)
┌───────────┬──────┐
│ kategorie ┆ vek  │
│ ---       ┆ ---  │
│ str       ┆ f64  │
╞═══════════╪══════╡
│ poezie    ┆ 52.0 │
│ próza     ┆ 50.0 │
│ vzpomínky ┆ 67.0 │
└───────────┴──────┘

## Druhý pokus

In [23]:
do_grafu.sample(10)

shape: (10, 44)
┌──────────┬────────────────────┬───────────────┬───────────┬───┬──────────┬───────┬────────┬─────┐
│ 100_ind1 ┆ 100_a              ┆ 100_7         ┆ 100_4     ┆ … ┆ narozeni ┆ umrti ┆ gender ┆ vek │
│ ---      ┆ ---                ┆ ---           ┆ ---       ┆   ┆ ---      ┆ ---   ┆ ---    ┆ --- │
│ str      ┆ str                ┆ str           ┆ list[str] ┆   ┆ i64      ┆ i64   ┆ str    ┆ i64 │
╞══════════╪════════════════════╪═══════════════╪═══════════╪═══╪══════════╪═══════╪════════╪═════╡
│ 1        ┆ Rops, Roman,       ┆ jo2013746618  ┆ ["aut"]   ┆ … ┆ 1985     ┆ null  ┆ m      ┆ 28  │
│ 1        ┆ Tomek, Ferdinand,  ┆ jk01132698    ┆ ["aut"]   ┆ … ┆ 1860     ┆ 1940  ┆ m      ┆ 71  │
│ 1        ┆ Urban, Miloš,      ┆ jn99240001220 ┆ ["aut"]   ┆ … ┆ 1967     ┆ null  ┆ m      ┆ 45  │
│ 1        ┆ Pekárková, Iva,    ┆ jn19990218083 ┆ ["aut"]   ┆ … ┆ 1963     ┆ null  ┆ f      ┆ 51  │
│ 1        ┆ Hrzánová, Barbora, ┆ jn20000710054 ┆ ["aut"]   ┆ … ┆ 1964     ┆ null  ┆ f      ┆ 54  │
│ 1        ┆ Lehkoživ, Radek,   ┆ mzk2006317955 ┆ ["aut"]   ┆ … ┆ 1975     ┆ null  ┆ m      ┆ 43  │
│ 1        ┆ Vladár, Marek,     ┆ mzk2006322946 ┆ ["aut"]   ┆ … ┆ 1969     ┆ null  ┆ m      ┆ 35  │
│ 1        ┆ Březina, Otokar,   ┆ jk01020045    ┆ ["aut"]   ┆ … ┆ 1868     ┆ 1929  ┆ m      ┆ 32  │
│ 1        ┆ Hraše, Jan Karel,  ┆ jk01042673    ┆ ["aut"]   ┆ … ┆ 1840     ┆ 1907  ┆ m      ┆ 45  │
│ 1        ┆ Antošová, Svatava, ┆ jn19990201008 ┆ ["aut"]   ┆ … ┆ 1957     ┆ null  ┆ f      ┆ 55  │
└──────────┴────────────────────┴───────────────┴───────────┴───┴──────────┴───────┴────────┴─────┘

In [24]:
do_grafu_drive = do_grafu.filter(pl.col("rok").is_between(1800,1938)).with_columns(obdobi = pl.lit('1800-1938'))
print(len(do_grafu_drive))
do_grafu_ted = do_grafu.filter(pl.col("rok").is_between(2000,2020)).with_columns(obdobi = pl.lit('2000-2020'))
print(len(do_grafu_ted))

8223
27669

In [25]:
do_grafu_basnici = pl.concat([do_grafu_drive.filter(pl.col("kategorie") == "poezie"), do_grafu_ted.filter(pl.col("kategorie") == "poezie")]).group_by(["obdobi","vek"]).len()
do_grafu_basnici

shape: (152, 3)
┌───────────┬─────┬─────┐
│ obdobi    ┆ vek ┆ len │
│ ---       ┆ --- ┆ --- │
│ str       ┆ i64 ┆ u32 │
╞═══════════╪═════╪═════╡
│ 2000-2020 ┆ 29  ┆ 90  │
│ 2000-2020 ┆ 20  ┆ 21  │
│ 1800-1938 ┆ 76  ┆ 7   │
│ 1800-1938 ┆ 63  ┆ 32  │
│ 2000-2020 ┆ 41  ┆ 97  │
│ 2000-2020 ┆ 94  ┆ 9   │
│ 2000-2020 ┆ 44  ┆ 84  │
│ 1800-1938 ┆ 59  ┆ 22  │
│ 2000-2020 ┆ 26  ┆ 71  │
│ 1800-1938 ┆ 52  ┆ 29  │
│ 1800-1938 ┆ 53  ┆ 41  │
│ 2000-2020 ┆ 68  ┆ 147 │
│ 1800-1938 ┆ 35  ┆ 66  │
│ 1800-1938 ┆ 41  ┆ 51  │
│ 2000-2020 ┆ 80  ┆ 120 │
│ 1800-1938 ┆ 43  ┆ 42  │
│ 2000-2020 ┆ 61  ┆ 135 │
│ 2000-2020 ┆ 46  ┆ 107 │
│ 2000-2020 ┆ 39  ┆ 94  │
│ 1800-1938 ┆ 20  ┆ 37  │
│ 2000-2020 ┆ 50  ┆ 156 │
│ 2000-2020 ┆ 87  ┆ 58  │
│ 2000-2020 ┆ 99  ┆ 3   │
│ 1800-1938 ┆ 57  ┆ 25  │
│ 1800-1938 ┆ 71  ┆ 15  │
│ 2000-2020 ┆ 66  ┆ 138 │
│ 2000-2020 ┆ 51  ┆ 114 │
│ 2000-2020 ┆ 35  ┆ 85  │
│ 1800-1938 ┆ 78  ┆ 7   │
│ 1800-1938 ┆ 47  ┆ 48  │
│ 1800-1938 ┆ 85  ┆ 3   │
│ 1800-1938 ┆ 58  ┆ 19  │
│ 1800-1938 ┆ 79  ┆ 6   │
│ 2000-2020 ┆ 23  ┆ 40  │
│ 1800-1938 ┆ 32  ┆ 64  │
│ 1800-1938 ┆ 69  ┆ 12  │
│ 2000-2020 ┆ 22  ┆ 48  │
│ 1800-1938 ┆ 44  ┆ 52  │
│ 1800-1938 ┆ 73  ┆ 8   │
│ 1800-1938 ┆ 55  ┆ 21  │
│ 2000-2020 ┆ 84  ┆ 56  │
│ 1800-1938 ┆ 27  ┆ 75  │
│ 1800-1938 ┆ 40  ┆ 49  │
│ 2000-2020 ┆ 78  ┆ 102 │
│ 2000-2020 ┆ 34  ┆ 104 │
│ 1800-1938 ┆ 67  ┆ 14  │
│ 2000-2020 ┆ 98  ┆ 4   │
│ 2000-2020 ┆ 16  ┆ 4   │
│ 1800-1938 ┆ 24  ┆ 64  │
│ 1800-1938 ┆ 46  ┆ 53  │
│ …         ┆ …   ┆ …   │
│ 2000-2020 ┆ 77  ┆ 116 │
│ 1800-1938 ┆ 61  ┆ 20  │
│ 1800-1938 ┆ 60  ┆ 27  │
│ 1800-1938 ┆ 21  ┆ 51  │
│ 2000-2020 ┆ 19  ┆ 23  │
│ 1800-1938 ┆ 68  ┆ 17  │
│ 1800-1938 ┆ 54  ┆ 35  │
│ 2000-2020 ┆ 54  ┆ 121 │
│ 2000-2020 ┆ 65  ┆ 158 │
│ 1800-1938 ┆ 83  ┆ 1   │
│ 1800-1938 ┆ 36  ┆ 75  │
│ 2000-2020 ┆ 55  ┆ 127 │
│ 1800-1938 ┆ 34  ┆ 77  │
│ 1800-1938 ┆ 28  ┆ 95  │
│ 2000-2020 ┆ 95  ┆ 3   │
│ 2000-2020 ┆ 83  ┆ 70  │
│ 2000-2020 ┆ 67  ┆ 174 │
│ 2000-2020 ┆ 28  ┆ 84  │
│ 2000-2020 ┆ 81  ┆ 78  │
│ 1800-1938 ┆ 80  ┆ 4   │
│ 1800-1938 ┆ 48  ┆ 39  │
│ 1800-1938 ┆ 22  ┆ 66  │
│ 1800-1938 ┆ 64  ┆ 29  │
│ 2000-2020 ┆ 75  ┆ 109 │
│ 2000-2020 ┆ 58  ┆ 126 │
│ 2000-2020 ┆ 18  ┆ 13  │
│ 2000-2020 ┆ 32  ┆ 87  │
│ 1800-1938 ┆ 77  ┆ 4   │
│ 2000-2020 ┆ 79  ┆ 75  │
│ 1800-1938 ┆ 39  ┆ 61  │
│ 2000-2020 ┆ 48  ┆ 95  │
│ 1800-1938 ┆ 70  ┆ 19  │
│ 2000-2020 ┆ 52  ┆ 117 │
│ 1800-1938 ┆ 45  ┆ 45  │
│ 2000-2020 ┆ 24  ┆ 56  │
│ 1800-1938 ┆ 56  ┆ 20  │
│ 2000-2020 ┆ 91  ┆ 22  │
│ 1800-1938 ┆ 51  ┆ 48  │
│ 2000-2020 ┆ 60  ┆ 191 │
│ 2000-2020 ┆ 92  ┆ 14  │
│ 2000-2020 ┆ 88  ┆ 29  │
│ 2000-2020 ┆ 30  ┆ 95  │
│ 2000-2020 ┆ 56  ┆ 150 │
│ 1800-1938 ┆ 37  ┆ 57  │
│ 2000-2020 ┆ 17  ┆ 8   │
│ 2000-2020 ┆ 47  ┆ 91  │
│ 2000-2020 ┆ 93  ┆ 5   │
│ 1800-1938 ┆ 74  ┆ 10  │
│ 1800-1938 ┆ 19  ┆ 20  │
│ 1800-1938 ┆ 75  ┆ 6   │
└───────────┴─────┴─────┘

In [26]:
tvar1 = alt.Chart(do_grafu_basnici.to_pandas(), width=300, height=100).mark_line(interpolate="monotone").encode(
    alt.X('vek:Q').axis(domain=False, tickSize=0, title=None),
    alt.Y('len:Q').stack('zero').axis(None),
    alt.Color('obdobi:N', sort=['2000-2020','1800-1838'], scale=alt.Scale(range=['#D6534B', '#DB842F']), legend=alt.Legend(title=None, orient="top")),
    alt.StrokeDash('obdobi:N', sort=['2000-2020','1800-1838'], legend=None)
)

tvar1

alt.Chart(...)

In [27]:
do_grafu_prozaici = pl.concat([do_grafu_drive.filter(pl.col("kategorie") == "próza"), do_grafu_ted.filter(pl.col("kategorie") == "próza")]).group_by(["obdobi","vek"]).len()

In [28]:
tvar2 = alt.Chart(do_grafu_prozaici.to_pandas(), width=300, height=100, title="…beletrii…").mark_line(interpolate="monotone").encode(
    alt.X('vek:Q').axis(domain=False, tickSize=0, title=None),
    alt.Y('len:Q').stack('zero').axis(None),
    alt.Color('obdobi:N', sort=['2000-2020','1800-1838'], scale=alt.Scale(range=['#D6534B', '#DB842F']), legend=None),
    alt.StrokeDash('obdobi:N', sort=['2000-2020','1800-1838'], legend=None)
)

tvar2

alt.Chart(...)

In [29]:
do_grafu_vzpominky = pl.concat([do_grafu_drive.filter(pl.col("kategorie") == "vzpomínky"), do_grafu_ted.filter(pl.col("kategorie") == "vzpomínky")]).group_by(["obdobi","vek"]).len()

In [30]:
do_grafu_vzpominky

shape: (142, 3)
┌───────────┬─────┬─────┐
│ obdobi    ┆ vek ┆ len │
│ ---       ┆ --- ┆ --- │
│ str       ┆ i64 ┆ u32 │
╞═══════════╪═════╪═════╡
│ 1800-1938 ┆ 57  ┆ 3   │
│ 1800-1938 ┆ 68  ┆ 5   │
│ 2000-2020 ┆ 36  ┆ 21  │
│ 2000-2020 ┆ 22  ┆ 8   │
│ 1800-1938 ┆ 81  ┆ 1   │
│ 2000-2020 ┆ 96  ┆ 6   │
│ 1800-1938 ┆ 27  ┆ 1   │
│ 2000-2020 ┆ 94  ┆ 14  │
│ 2000-2020 ┆ 45  ┆ 32  │
│ 2000-2020 ┆ 83  ┆ 48  │
│ 2000-2020 ┆ 26  ┆ 14  │
│ 2000-2020 ┆ 64  ┆ 53  │
│ 2000-2020 ┆ 86  ┆ 53  │
│ 2000-2020 ┆ 34  ┆ 24  │
│ 1800-1938 ┆ 25  ┆ 1   │
│ 2000-2020 ┆ 90  ┆ 37  │
│ 2000-2020 ┆ 89  ┆ 24  │
│ 2000-2020 ┆ 25  ┆ 6   │
│ 2000-2020 ┆ 35  ┆ 26  │
│ 1800-1938 ┆ 53  ┆ 8   │
│ 1800-1938 ┆ 45  ┆ 3   │
│ 2000-2020 ┆ 23  ┆ 3   │
│ 1800-1938 ┆ 85  ┆ 1   │
│ 1800-1938 ┆ 75  ┆ 3   │
│ 2000-2020 ┆ 54  ┆ 33  │
│ 1800-1938 ┆ 31  ┆ 1   │
│ 2000-2020 ┆ 92  ┆ 25  │
│ 2000-2020 ┆ 27  ┆ 5   │
│ 2000-2020 ┆ 62  ┆ 47  │
│ 1800-1938 ┆ 63  ┆ 3   │
│ 1800-1938 ┆ 29  ┆ 2   │
│ 2000-2020 ┆ 30  ┆ 9   │
│ 2000-2020 ┆ 60  ┆ 48  │
│ 1800-1938 ┆ 70  ┆ 5   │
│ 2000-2020 ┆ 24  ┆ 1   │
│ 2000-2020 ┆ 81  ┆ 68  │
│ 2000-2020 ┆ 51  ┆ 30  │
│ 1800-1938 ┆ 46  ┆ 7   │
│ 2000-2020 ┆ 57  ┆ 44  │
│ 2000-2020 ┆ 61  ┆ 50  │
│ 2000-2020 ┆ 41  ┆ 31  │
│ 2000-2020 ┆ 93  ┆ 13  │
│ 1800-1938 ┆ 65  ┆ 2   │
│ 1800-1938 ┆ 32  ┆ 1   │
│ 1800-1938 ┆ 37  ┆ 5   │
│ 1800-1938 ┆ 76  ┆ 3   │
│ 2000-2020 ┆ 47  ┆ 30  │
│ 1800-1938 ┆ 86  ┆ 1   │
│ 1800-1938 ┆ 52  ┆ 7   │
│ 1800-1938 ┆ 34  ┆ 6   │
│ …         ┆ …   ┆ …   │
│ 2000-2020 ┆ 56  ┆ 32  │
│ 1800-1938 ┆ 26  ┆ 3   │
│ 1800-1938 ┆ 61  ┆ 5   │
│ 1800-1938 ┆ 49  ┆ 3   │
│ 2000-2020 ┆ 46  ┆ 25  │
│ 1800-1938 ┆ 56  ┆ 6   │
│ 1800-1938 ┆ 67  ┆ 4   │
│ 2000-2020 ┆ 99  ┆ 2   │
│ 1800-1938 ┆ 59  ┆ 2   │
│ 2000-2020 ┆ 50  ┆ 44  │
│ 2000-2020 ┆ 78  ┆ 76  │
│ 2000-2020 ┆ 70  ┆ 80  │
│ 2000-2020 ┆ 71  ┆ 51  │
│ 1800-1938 ┆ 42  ┆ 2   │
│ 2000-2020 ┆ 95  ┆ 14  │
│ 1800-1938 ┆ 18  ┆ 1   │
│ 2000-2020 ┆ 85  ┆ 56  │
│ 1800-1938 ┆ 39  ┆ 8   │
│ 2000-2020 ┆ 59  ┆ 48  │
│ 2000-2020 ┆ 69  ┆ 47  │
│ 1800-1938 ┆ 69  ┆ 4   │
│ 2000-2020 ┆ 21  ┆ 1   │
│ 2000-2020 ┆ 77  ┆ 69  │
│ 1800-1938 ┆ 30  ┆ 1   │
│ 2000-2020 ┆ 76  ┆ 67  │
│ 2000-2020 ┆ 38  ┆ 28  │
│ 2000-2020 ┆ 44  ┆ 32  │
│ 1800-1938 ┆ 43  ┆ 7   │
│ 1800-1938 ┆ 33  ┆ 1   │
│ 1800-1938 ┆ 40  ┆ 4   │
│ 1800-1938 ┆ 66  ┆ 3   │
│ 2000-2020 ┆ 88  ┆ 41  │
│ 2000-2020 ┆ 66  ┆ 48  │
│ 2000-2020 ┆ 91  ┆ 21  │
│ 1800-1938 ┆ 55  ┆ 8   │
│ 1800-1938 ┆ 78  ┆ 1   │
│ 1800-1938 ┆ 50  ┆ 10  │
│ 1800-1938 ┆ 58  ┆ 3   │
│ 2000-2020 ┆ 48  ┆ 20  │
│ 1800-1938 ┆ 47  ┆ 5   │
│ 2000-2020 ┆ 28  ┆ 12  │
│ 1800-1938 ┆ 89  ┆ 1   │
│ 1800-1938 ┆ 72  ┆ 5   │
│ 2000-2020 ┆ 17  ┆ 1   │
│ 1800-1938 ┆ 51  ┆ 2   │
│ 2000-2020 ┆ 67  ┆ 62  │
│ 2000-2020 ┆ 98  ┆ 5   │
│ 2000-2020 ┆ 37  ┆ 24  │
│ 1800-1938 ┆ 82  ┆ 2   │
│ 1800-1938 ┆ 62  ┆ 7   │
└───────────┴─────┴─────┘

In [31]:
tvar3 = alt.Chart(do_grafu_vzpominky.to_pandas(), width=300, height=100, title="…a vzpomínky").mark_line(interpolate="monotone").encode(
    alt.X('vek:Q').axis(domain=False, tickSize=0, title=None),
    alt.Y('len:Q').stack('zero').axis(None),
    alt.Color('obdobi:N', sort=['2000-2020','1800-1838'], scale=alt.Scale(range=['#D6534B', '#DB842F']), legend=None),
    alt.StrokeDash('obdobi:N', sort=['2000-2020','1800-1838'], legend=None)
)

tvar3

alt.Chart(...)

In [32]:
alt.vconcat(tvar1, tvar2, tvar3, title=alt.Title("V jakém věku lidé vydávají básně…")).resolve_scale(x='shared').configure_view(stroke='transparent')

alt.VConcatChart(...)

## Finální verze

In [34]:
kolik = len(do_grafu.select(pl.col("100_7").unique()))
kolik

15820

In [35]:
do_grafu.select(pl.col("rok").median())

shape: (1, 1)
┌────────┐
│ rok    │
│ ---    │
│ f64    │
╞════════╡
│ 2008.0 │
└────────┘

In [75]:
veky_autorstva = alt.Chart(do_grafu.with_columns(pl.col("kategorie").replace(
    {'próza':'…prózu','poezie':'…poezii','vzpomínky':'…vzpomínky'}
)).group_by(["vek","kategorie"]).len().to_pandas(),
         title=alt.Title(
             'V jakém věku čeští autoři a autorky publikují…',
             subtitle=
             ["Osamělé vrcholky odpovídají kulatým narozeninám.",
              "(Převažují publikace z posledních dvou dekád. Grafy mají odlišná měřítka.)"]
         )).mark_bar(width=1).encode(
    alt.X(
        "vek:Q", 
        scale=alt.Scale(domainMax=90, domainMin=20), 
        title=None, 
        axis=alt.Axis(tickCount=4)),
    alt.Y(
        "len:Q", 
        title=None, 
        scale=alt.Scale(domainMin=1), 
        axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6', orient='right', format='~s', labelExpr='datum.label + " knih"')),
    alt.Color('kategorie:N', scale=alt.Scale(range=['#E09DA3','#70871E','#DB842F',]), title=None, legend=None),
    alt.Column('kategorie:N', spacing=8, title=None, sort=['…prózu','…poezii','…vzpomínky'],
           header=alt.Header(labelAngle=0, labelAlign='left', labelAnchor='start', labelFontWeight=500, labelFont='Asap', labelOrient="top"))
).properties(
    width=kredity['sirka'] / 3.8, 
    height=kredity['vyska_nizkych'], 
    autosize={'type': 'fit', 'contains': 'padding'}
).configure_view(stroke='transparent').configure_axis(grid=False, domain=False).resolve_axis(x="independent").resolve_scale(y="independent")

veky_autorstva

alt.Chart(...)

In [77]:
me_to_neurazi(veky_autorstva, soubor="02_tvar_kariery", kredity=kredity['default'])

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_tvar_kariery.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_tvar_kariery.svg" width="100%" alt="Graf s titulkem „V jakém věku čeští autoři a autorky publikují…“. Další texty by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

In [79]:
do_grafu.filter(pl.col("vek") <= 65).group_by("kategorie").agg(pl.col("vek").median())

shape: (3, 2)
┌───────────┬──────┐
│ kategorie ┆ vek  │
│ ---       ┆ ---  │
│ str       ┆ f64  │
╞═══════════╪══════╡
│ próza     ┆ 46.0 │
│ vzpomínky ┆ 51.0 │
│ poezie    ┆ 44.0 │
└───────────┴──────┘

In [85]:
do_grafu.filter(pl.col("vek").is_between(20,45)).group_by("kategorie").agg(pl.col("vek").median())

shape: (3, 2)
┌───────────┬──────┐
│ kategorie ┆ vek  │
│ ---       ┆ ---  │
│ str       ┆ f64  │
╞═══════════╪══════╡
│ próza     ┆ 37.0 │
│ poezie    ┆ 34.0 │
│ vzpomínky ┆ 37.0 │
└───────────┴──────┘