In [1]:
import os
import json
import datetime
import warnings
import polars as pl
import pandas as pd
import altair as alt

from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.hezke_jmeno import hezke_jmeno
from src.kristi_promin import kristi_promin
from src.me_to_neurazi import me_to_neurazi

with open(os.path.join('src','kredity.json'), 'r', encoding='utf-8') as kredity:
    kredity = json.loads(kredity.read())
pl.Config(tbl_rows=100)
alt.data_transformers.disable_max_rows()
alt.themes.register('irozhlas', kristi_promin)
alt.themes.enable('irozhlas')
warnings.filterwarnings('ignore')

In [2]:
aut = pl.read_parquet(
    os.path.join("data","aut_vyber.parquet")
).explode(
    "370_c"
).filter(
    pl.col("370_c").str.contains("Česk")
).explode(
    "100_7"
).select(
    ["100_a","100_7","370_c","374_a","375_a","678_a"]
)

In [3]:
cesi = aut.filter(pl.col("370_c").str.contains("Česk")).select(pl.col("100_7").unique()).to_series().to_list()

In [4]:
len(cesi)

267043

In [5]:
aut.sample(10)

shape: (10, 6)
┌────────────────────────┬───────────────┬───────┬──────────────────────┬───────────┬──────────────────────────────────┐
│ 100_a                  ┆ 100_7         ┆ 370_c ┆ 374_a                ┆ 375_a     ┆ 678_a                            │
│ ---                    ┆ ---           ┆ ---   ┆ ---                  ┆ ---       ┆ ---                              │
│ list[str]              ┆ str           ┆ str   ┆ list[str]            ┆ list[str] ┆ list[str]                        │
╞════════════════════════╪═══════════════╪═══════╪══════════════════════╪═══════════╪══════════════════════════════════╡
│ ["Adámková, Petra,"]   ┆ ola2013797998 ┆ Česko ┆ null                 ┆ null      ┆ ["Mgr., spoluautorka vysokoško…  │
│ ["Hrbek, Jiří,"]       ┆ jn20000401070 ┆ Česko ┆ null                 ┆ null      ┆ ["Narozen 18.2.1932 v Praze. P…  │
│ null                   ┆ null          ┆ Česko ┆ null                 ┆ null      ┆ null                             │
│ ["Němec, Jan,"]        ┆ mzk2006337016 ┆ Česko ┆ null                 ┆ null      ┆ ["Narozen 1980. Zemědělský ing…  │
│ ["Šemberová, Martina"] ┆ xx0216632     ┆ Česko ┆ ["zdravotní sestry"] ┆ ["žena"]  ┆ ["Zdravotní sestra (Dermatoven…  │
│ ["Hofmann, Lukáš,"]    ┆ xx0273123     ┆ Česko ┆ ["umělci", "kurátoři ┆ ["muž"]   ┆ ["Narozen 22. 2. 1993 v Praze.…  │
│                        ┆               ┆       ┆ výstav", …           ┆           ┆                                  │
│ ["Kříž, Radek"]        ┆ av20221143624 ┆ Česko ┆ ["herci", "televizní ┆ ["muž"]   ┆ ["Herec, scénárista, rozhlasov…  │
│                        ┆               ┆       ┆ scenárist…           ┆           ┆                                  │
│ null                   ┆ null          ┆ Česko ┆ null                 ┆ null      ┆ null                             │
│ null                   ┆ null          ┆ Česko ┆ null                 ┆ null      ┆ null                             │
│ null                   ┆ null          ┆ Česko ┆ null                 ┆ null      ┆ ["Původně luteránský kostel by…  │
└────────────────────────┴───────────────┴───────┴──────────────────────┴───────────┴──────────────────────────────────┘

In [6]:
len(cesi)

267043

In [7]:
cesi

['xx0095633',
 'ola2008434503',
 'xx0009186',
 'xx0173961',
 'jk01060274',
 'pna20211100385',
 'xx0270281',
 'jk01061577',
 'jo20221154827',
 'ola2012693799',
 'ola20211108943',
 'jk01092177',
 'jn20000710524',
 'xx0208844',
 'jk01060145',
 'mzk2003183075',
 'jx20050216008',
 'xx0268729',
 'xx0184884',
 'xx0231936',
 'jo2018978303',
 'xx0260598',
 'mzk2008448525',
 'mzk2011642485',
 'jo20000080259',
 'jk01082894',
 'xx0077224',
 'ola2012687482',
 'jk01081507',
 'jx20090908062',
 'xx0120511',
 'xx0121860',
 'xx0179866',
 'mzk2009521724',
 'jo2016936200',
 'ola2004254075',
 'xx0090738',
 'jx20121219011',
 'mzk2013770440',
 'mzk2005289924',
 'jk01150478',
 'xx0149522',
 'xx0193372',
 'jo20191041085',
 'av20191019769',
 'xx0241319',
 'xx0207848',
 'ntka172199',
 'mzk20201078482',
 'xx0327466',
 'mzk2013784480',
 'jn20020726048',
 'xx0087783',
 'xx0037794',
 'jk01010112',
 'mzk2011655659',
 'mzk2005266270',
 'jk01090072',
 'jk01130430',
 'xx0083154',
 'xx0258799',
 'mzk2007411064',
 'jn20000620407',
 'jn20010309019',
 'jk01042650',
 'mub2010600061',
 'mub20191054817',
 'pna2012678504',
 'xx0089518',
 'jk01111601',
 'jk01140507',
 'ntka173914',
 'ola2008455796',
 'hka2010587811',
 'xx0201854',
 'jk01110395',
 'jk01062066',
 'xx0076065',
 'xx0328669',
 'jn20000403034',
 'xx0270245',
 'jz8000552',
 'mzk2005309092',
 'ntk2011667138',
 'mzk2013768634',
 'xx0105569',
 'jo2010591555',
 'osa20181002659',
 'ola2004212133',
 'jk01012867',
 'js20101123002',
 'jo2006333781',
 'xx0306237',
 'mzk2008448777',
 'xx0216038',
 'kup19950000070970',
 'mzk2004234111',
 'av20241214901',
 'nlk20010095606',
 'jk01052156',
 'xx0104313',
 'xx0141865',
 'xx0314791',
 'jk01142419',
 'mzk2009544426',
 'ola2002150639',
 'mzk2004228234',
 'xx0079327',
 'jo20201083015',
 'xx0087110',
 'jk01121783',
 'mub2012687918',
 'mzk2009521576',
 'ola2002159517',
 'jk01022383',
 'xx0064510',
 'xx0036870',
 'jk01011134',
 'jo2012722293',
 'xx0011161',
 'hka20231201470',
 'jx20050726057',
 'xx0059139',
 'js20020122030',
 'jk01081035',
 'xx0107184',
 'jx20100621014',
 'mzk2011635459',
 'xx0248805',
 'xx0318495',
 'hka2011641559',
 'xx0270224',
 'jk01092258',
 'osa20211123607',
 'xx0065941',
 'jk01022615',
 'jx20090917007',
 'ola2009548127',
 'xx0087797',
 'xx0119418',
 'xx0243685',
 'jk01050393',
 'jk01120662',
 'xx0233490',
 'jcu2012689634',
 'ola2002157879',
 'jn99240000909',
 'jk01031758',
 'pna2006327174',
 'xx0070522',
 'mub2011637592',
 'jn20011121011',
 'jo2012687543',
 'mzk2008469233',
 'jk01070530',
 'mub2010584888',
 'osd2015888994',
 'xx0001303',
 'jk01070558',
 'xx0139237',
 'js20011127001',
 'ola2012720693',
 'xx0097188',
 'mzk2009491882',
 'mzk2004248713',
 'nlk20020112535',
 'xx0001097',
 'stk2008461719',
 'xx0022520',
 'xx0148108',
 'mzk2014814013',
 'xx0323802',
 'nlk20010099494',
 'js20040322001',
 'jk01131362',
 'ola2006345489',
 'ctu20231178614',
 'xx0043368',
 'jk01141267',
 'mzk2013789197',
 'kpwa11240',
 'jk01010535',
 'mzk2006337340',
 'mzk2014830817',
 'xx0048386',
 'mzk2010572708',
 'js20050418009',
 'jk01070713',
 'jk01011066',
 'xx0078921',
 'jo2010589194',
 'mzk2013776287',
 'xx0211243',
 'xx0241525',
 'jx20071114039',
 'ola2002159167',
 'jk01033374',
 'jx20041207018',
 'jx20081111008',
 'xx0110760',
 'xx0306243',
 'ola2014838173',
 'jo2009521381',
 'jk01020486',
 'xx0114096',
 'jx20051019025',
 'xx0268654',
 'js20100802004',
 'xx0062744',
 'skuk0005761',
 'xx0028906',
 'jo2002140351',
 'xx0247500',
 'xx0243554',
 'jk01043325',
 'xx0312760',
 'xx0116283',
 'xx0042527',
 'jk01151257',
 'jx20080717040',
 'xx0093276',
 'ola20221141727',
 'xx0315184',
 'xx0005842',
 'kpwa10804',
 'jn20000620039',
 'xx0174645',
 'mzk2016923212',
 'mzk2003213882',
 'jk01063528',
 'xx0234764',
 'xx0128712',
 'ola200200590',
 'ctu2012682945',
 'xx0231708',
 'stk2008461209',
 'ola2007364709',
 'xx0271199',
 'jk01091745',
 'xx0035314',
 'ola2014846588',
 'jx20120229005',
 'xx0328108',
 'xx0103882',
 'xx0128048',
 'jx20090417021',
 'av2014851214',
 'xx0237664',
 'xx0243478',
 'mzk2014815727',
 'xx0106448',
 'jo2016924411',
 'jk01090603',
 'jk01011352',
 'jcu2011631305',
 'xx0145755',
 'xx0044990',
 'av20221151358',
 'xx0199605',
 'xx0094832',
 'mzk2002156781',
 'jk01121930',
 'xx0167937',
 'kpwa2280',
 'jk01071498',
 'jn20000728082',
 'mzk2007411234',
 'jx20080513039',
 'xx0128416',
 'xx0110896',
 'jo2002100956',
 'mub2010580192',
 'jk01072462',
 'mzk2007424202',
 'kpwa1767',
 'jz6702197',
 'xx0276486',
 'xx0192230',
 'xx0034437',
 'xx0087806',
 'mzk2011638697',
 'jx20060223034',
 'jo20010084593',
 'xx0074214',
 'mzk2008459101',
 'jx20120224021',
 'jk01011162',
 'jk01110890',
 'xx0063390',
 'ola2012693930',
 'kpwa2353',
 'jo2012735778',
 'jk01021187',
 'jn20010309006',
 'mzk2009539375',
 'jo2012678362',
 'xx0194200',
 'jk01070491',
 'jk01131384',
 'ola200202349',
 'mzk2017941063',
 'jk01051389',
 'xx0219273',
 'jk01020658',
 'jn99240001306',
 'mzk2011670208',
 'nlk20010092725',
 'xx0320530',
 'jx20081128011',
 'ola2007364184',
 'jo20010091866',
 'jn20000402331',
 'jx20050113007',
 'mzk2014834527',
 'mzk2005304450',
 'mzk2008443068',
 'jk01151803',
 'kpwa4247',
 'xx0118043',
 'mzk2013769693',
 'xx0281224',
 'xx0281613',
 'xx0175820',
 'kpwa3832',
 'jo2010573527',
 'mzk2006337207',
 'xx0276161',
 'xx0101741',
 'ola2006345451',
 'jk01101891',
 'ntk2011666566',
 'pna2009525929',
 'xx0097631',
 'mzk2013789203',
 'uzp2015867174',
 'xx0068585',
 'xx0227745',
 'mzk2015864742',
 'xx0203431',
 'mzk2003175489',
 'kv2014837516',
 'jx20070418003',
 'jk01052716',
 'jk01130662',
 'xx0025184',
 'xx0101603',
 'jo2012688281',
 'mzk20181008952',
 'js20030106012',
 'ola20241231797',
 'xx0249301',
 'xx0275733',
 'xx0233877',
 'jk01010337',
 'jx20090220017',
 'xx0014704',
 'xx0022847',
 'jn19990209251',
 'jo2003204236',
 'nlk20030127571',
 'mzk2010594557',
 'xx0110371',
 'ctu20231200023',
 'ntka173652',
 'jn19981000032',
 'mzk2007377355',
 'mzk2007386101',
 'jn20031223010',
 'ola2013779445',
 'mzk2013753906',
 'jo2014848319',
 'xx0246714',
 'mzk2007430822',
 'jn20000402989',
 'xx0029142',
 'hka2010582474',
 'jx20100824004',
 'jk01020366',
 'ola2012722046',
 'xx0052980',
 'jk01110888',
 'mzk2006337128',
 'jo2007416283',
 'xx0076862',
 'xx0234101',
 'jo2010555005',
 'jk01041922',
 'jo20181000033',
 'xx0228308',
 'jk01063222',
 'ntka173003',
 'ola2009522960',
 'xx0204108',
 'jk01073014',
 'ola2002150723',
 'ntka173305',
 'jk01070064',
 'jz8001394',
 'mzk2011649355',
 'xx0273268',
 'jn20010309194',
 'xx0224257',
 'js20081127008',
 'jx20050613026',
 'hka2010577117',
 'xx0305423',
 'mzk2002149491',
 'jk01053082',
 'xx0191397',
 'stk2008461701',
 'jo2012714516',
 'jo2008446764',
 'xx0067809',
 'mzk2007401030',
 'mzk2008469125',
 'xx0230080',
 'jo2013762422',
 'jx20080822008',
 'skuk0001135',
 'jo2013761453',
 'jk01080991',
 'xx0006763',
 'jk01031822',
 'jx20121010003',
 'jk01050373',
 'xx0266950',
 'js20040107008',
 'pna2013791853',
 'ola2006329967',
 'jx20080407017',
 'jx20110504005',
 'jk01073313',
 'jo20191060382',
 'jo2007416035',
 'ola2003206339',
 'xx0173382',
 'jk01063032',
 'pna2006337830',
 'mzk2009533949',
 'xx0019064',
 'jo20221171824',
 'jk01132278',
 'uk20241215067',
 'mzk20221141615',
 'xx0051620',
 'hka2016922233',
 'jo2014830048',
 'mzk2015863878',
 'jo20000082473',
 'ola20211133251',
 'mzk2004250863',
 'mzk2011627545',
 'xx0003359',
 'jk01122867',
 'xx0016720',
 'xx0144462',
 'pna2013745624',
 'xx0171293',
 'xx0263148',
 'uzp2006333631',
 'jk01043029',
 'xx0061344',
 'xx0077555',
 'mzk2011660633',
 'xx0134920',
 'xx0096085',
 'jk01082505',
 'js20030929016',
 'jo2016910586',
 'xx0088979',
 'pna2011654857',
 'xx0156585',
 'mzk20181014015',
 'mzk2015868563',
 'xx0071171',
 'xx0048424',
 'jx20090619004',
 'xx0092045',
 'xx0004766',
 'jn20000402797',
 'mub20191035355',
 'xx0125105',
 'jk01100701',
 'jk01021450',
 'jk01050642',
 'jx20111213038',
 'xx0123817',
 'jx20041103016',
 'jo2010571469',
 'xx0175438',
 'ntk20191039245',
 'mzk2016897343',
 'ola2018982856',
 'xx0147118',
 'xx0182500',
 'ntk2016917983',
 'jn20000401850',
 'jk01152380',
 'mzk20211129760',
 'xx0140183',
 'mzk2010571020',
 'jk01030547',
 'xx0107658',
 'mzk2016920690',
 'ola20221160884',
 'mzk2013794225',
 'jo2015856109',
 'xx0146412',
 'xx0324717',
 'jk01062602',
 'jo2014849265',
 'jk01091098',
 'jx20050104027',
 'jx20090707001',
 'xx0007262',
 'pna2008424994',
 'xx0105015',
 'xx0017197',
 'pag2010568617',
 'jk01080834',
 'jo2006362201',
 'mzk2008473124',
 'xx0169184',
 'xx0106240',
 'jk01020835',
 'kpwa3601',
 'jx20070123007',
 'xx0110212',
 'jo2009409347',
 'pna20231207740',
 'jk01150110',
 'jo2002105437',
 'jn20000620418',
 'ola2008455744',
 'xx0048255',
 'js20060217019',
 'xx0112676',
 'av2018976176',
 'jk01111890',
 'mzk2009521546',
 'mzk2012716590',
 'jn20040226011',
 'mzk2005286819',
 'mzk2004258446',
 'jk01072108',
 'jo2016933515',
 'mzk2005271836',
 'jo20201085263',
 'mzk20201091948',
 'jk01022204',
 'jn19990209012',
 'jo20000080288',
 'ola2003193819',
 'stk2007393636',
 'xx0067792',
 'mzk2002156925',
 'jk01030550',
 'pna2009495547',
 'ola20211122418',
 'mzk2009539754',
 'xx0302403',
 'jo2008480426',
 'xx0273733',
 'ola200207062',
 'jo2012713957',
 'mzk2007390583',
 'kup19990000095873',
 'xx0108095',
 'mzk2015887569',
 'xx0208967',
 'xx0125268',
 'xx0238049',
 'pna2015865049',
 'xx0266793',
 'jn20001227374',
 'xx0106447',
 'jk01121871',
 'xx0194882',
 'mub20231183888',
 'xx0068640',
 'xx0190149',
 'mzk2009521564',
 'xx0129852',
 'xx0008828',
 'xx0096557',
 'xx0150665',
 'xx0269408',
 'xx0108773',
 'jk01010858',
 'mzk2006322988',
 'jn20031222008',
 'xx0005359',
 'jn20000710043',
 'xx0054402',
 'xx0132567',
 'pna2012678519',
 'xx0214936',
 'xx0095939',
 'jk01041543',
 'jk01050232',
 'xx0022996',
 'xx0324713',
 'xx0184890',
 'jk01020687',
 'mzk2005300517',
 'xx0083843',
 'xx0064124',
 'xx0006620',
 'xx0161970',
 'xx0211240',
 'ola2009522966',
 'jn19990210835',
 'jx20111123009',
 'ola20211134702',
 'xx0208486',
 'jk01040217',
 'jn19981000712',
 'jn20001103592',
 'osa20201064976',
 'ola20211102302',
 'jn20001005528',
 'ola200209290',
 'mzk2010609330',
 'mzk2002113425',
 'xx0300518',
 'jo2005321085',
 'ola2014815266',
 'mzk2011657398',
 'mzk2015870028',
 'jo20201088382',
 'xx0270605',
 'ola2009507987',
 'mzk2003165644',
 'mzk2004221752',
 'pna2015854838',
 'jo2006321117',
 'jk01110764',
 'xx0018338',
 'mzk2005282678',
 'ola2007364716',
 'ola20221143185',
 'xx0211642',
 'xx0121547',
 'pna2006327190',
 'jo2014848778',
 'xx0090981',
 'mzk2003213251',
 'jo2006324892',
 'xx0235739',
 'xx0238978',
 'xx0276606',
 'jk01030076',
 'mzk2013767925',
 'xx0021826',
 'js20070406009',
 'xx0057028',
 'jx20031130004',
 'xx0243373',
 'ola2003201056',
 'xx0239091',
 'xx0301920',
 'ola2008404528',
 'xx0026171',
 'jo2014816092',
 'xx0209229',
 'ola2018981975',
 'jk01100347',
 'xx0030288',
 'ola2015862645',
 'kpwa4046',
 'jo2015856028',
 'xx0114359',
 'ola2003206218',
 'mzk2004261039',
 'mzk2013769853',
 'mzk2010581528',
 'xx0204191',
 'jo2017940686',
 'jx20040924008',
 'xx0248765',
 'jn20000402931',
 'mzk2011655268',
 'ola2002113372',
 'xx0140005',
 'jk01072839',
 'jk01121390',
 'xx0037125',
 'xx0006440',
 'xx0171648',
 'mzk2003202467',
 'xx0221098',
 'mzk2011668629',
 'hka20241232714',
 'jo2002105297',
 'xx0241590',
 'jx20050505025',
 'jo2013741403',
 'jn19990209494',
 'jo2014802974',
 'mzk2016903251',
 'xx0061792',
 'jx20080926018',
 'jk01021029',
 'ola2014808712',
 'jx20041110032',
 'xx0071614',
 'xx0268667',
 'xx0271685',
 'xx0318175',
 'zcu2016909612',
 'xx0231446',
 'ola2010586997',
 'pna2015896289',
 'jk01130333',
 'xx0277049',
 'mzk20231197354',
 'xx0066343',
 'xx0081255',
 'jx20080730022',
 'mzk2004229545',
 'mub20201063695',
 'xx0082531',
 'xx0267913',
 'jk01140367',
 'ola200207261',
 'jo20221143861',
 'xx0143520',
 'ntk2017954019',
 'xx0121863',
 'xx0169529',
 'osa2016931734',
 'jo20191020037',
 'pag2008454916',
 'xx0019248',
 'jn99240000008',
 'ola200209251',
 'skuk0000685',
 'mzk2014841101',
 'xx0243725',
 'ola20211107874',
 'xx0019995',
 'jx20090227027',
 'ola2010583214',
 'jz8600043',
 'jk01040316',
 'ola2007364559',
 'jx20071205041',
 'jcu20241223894',
 'xx0007159',
 'jn20000401935',
 'xx0228040',
 'jn20001005128',
 'jo2015858269',
 'xx0324726',
 'xx0213776',
 'jk01151267',
 'jo2009507492',
 'pna2014830783',
 'jk01041839',
 'mzk2007417191',
 'xx0191535',
 'xx0283074',
 'xx0001607',
 'ola2004235554',
 'xx0113962',
 'xx0136604',
 'xx0164829',
 'mzk2015865504',
 'mzk2008486735',
 'mzk20181013793',
 'xx0041027',
 'xx0108277',
 'mzk20251251632',
 'jk01072090',
 'jn99240001033',
 'jk01111277',
 'mzk2007386161',
 'xx0119376',
 'hka2016936888',
 'jk01031776',
 'jx20080528034',
 'jo2006333916',
 'jo20000073736',
 'mzk2006348666',
 'jn20000728231',
 'jk01021100',
 'jk01012877',
 'mub2011648977',
 'xx0276381',
 'jk01061748',
 'mzk2008458993',
 'mzk2014813636',
 'mzk2004246532',
 'jk01010433',
 'xx0098127',
 'xx0116727',
 'pna2006334372',
 'xx0225620',
 'ola20181010377',
 'hka20241242184',
 'xx0043651',
 'mzk2010612577',
 'xx0113120',
 'xx0135154',
 'jx20090417018',
 'xx0230618',
 'xx0235437',
 'jx20101018019',
 'jk01100287',
 'mzk2009496131',
 'ola2003204973',
 'jk01062438',
 'jx20080930052',
 'xx0094063',
 'jo20251248421',
 'mzk2014821791',
 'av20191047327',
 'xx0254906',
 'pna2009505142',
 'xx0012905',
 'xx0039690',
 'xx0273866',
 'xx0301366',
 'mub2010573195',
 'ntk2015855575',
 'jx20091002011',
 'ctu20241215426',
 'jk01121433',
 'xx0004871',
 'jx20080512019',
 'mub2011659494',
 'jk01022063',
 'xx0033851',
 'ntka172841',
 'jo20201091131',
 'jx20090723028',
 'jk01120774',
 'ola200208951',
 'ola20201072755',
 'hka20241242312',
 'jx20060207009',
 'ola2008434619',
 'jk01050487',
 'nlk20000089618',
 'jo20231187666',
 'ola20191053778',
 'jk01052416',
 'xx0188161',
 'xx0314270',
 'xx0106850',
 'jo2004249949',
 'jk01152413',
 'jn20000401949',
 'mzk2017974284',
 'pna2012703356',
 'xx0272714',
 'ola200205837',
 'mzk2009529535',
 'pag2018999149',
 'xx0124454',
 'jcu2010574588',
 'xx0262200',
 'xx0275845',
 'jo2009546529',
 'xx0107168',
 'xx0127524',
 'xx0011208',
 'kpwa5464',
 'xx0109951',
 'xx0277748',
 'xx0282757',
 'jn19981001297',
 'jx20050414031',
 'mzk20251252668',
 'mzk20191053179',
 'xx0181699',
 'xx0232314',
 'jk01012097',
 'jn20001103572',
 'czu2010571618',
 'xx0169676',
 'jx20040109004',
 'mzk2010598841',
 'xx0132776',
 'mzk2015857974',
 'ola2002101055',
 'hka20221155011',
 'mzk20241230616',
 'mzk2005273004',
 'xx0104166',
 'jk01041360',
 'xx0073323',
 'mzk2013796629',
 'xx0199344',
 'jk01122551',
 'xx0269348',
 'mzk2009502301',
 'mzk2016902499',
 'jn20000402497',
 'jx20090709005',
 'jk01033484',
 'ntka172817',
 'jk01012348',
 'mzk2002143996',
 'xx0194100',
 'xx0277942',
 'pna2005292226',
 'ola2012696165',
 'xx0283844',
 'jk01101528',
 'xx0303812',
 'xx0154017',
 'ntk2013790321',
 'xx0209425',
 'pna20191026104',
 'jn20000402219',
 'xx0039208',
 'xx0185820',
 'js20040530001',
 'jk01071057',
 'av20181016163',
 'pna2016937031',
 'jo2013778746',
 'jx20081107006',
 'mzk2010607479',
 'jo20231186359',
 'xx0056785',
 'jk01090572',
 'jk01022042',
 'pna20221151579',
 'mzk2006322946',
 'xx0129555',
 'xx0134446',
 'jn20000401734',
 'xx0025194',
 'jo20010090066',
 'jo2002106684',
 'av20211121487',
 'xx0003672',
 'jk01121275',
 'jk01101932',
 'jk01102868',
 'jx20050621056',
 'xx0081831',
 'xx0128621',
 'xx0240872',
 'js20090708007',
 'xx0129498',
 'xx0283812',
 'xx0272944',
 'hka2015873900',
 'xx0121144',
 'hka2011634372',
 'ola364016',
 'xx0321035',
 'pna20241218604',
 'jx20041220028',
 'js20081120001',
 'hka2009498630',
 'hka20191023684',
 'xx0063600',
 'jk01061976',
 'mzk2014831373',
 'mub20231173753',
 'jk01052652',
 'jk01033255',
 'xx0011876',
 'xx0021270',
 'ola2006345448',
 'jk01082605',
 'mzk2007424067',
 'jk01092275',
 'jk01151581',
 'mzk2008448686',
 'mzk2011666328',
 'mzk2015885968',
 'jo2016920777',
 'pna20191036972',
 'mzk2009502192',
 'xx0316616',
 'jn19981000360',
 'ola20221158303',
 'jo2006321210',
 'xx0217263',
 'jk01070807',
 'xx0122003',
 'jn19990209480',
 'kpwa6347',
 'jk01140631',
 'xx0159382',
 'av20191044449',
 'osa2011663513',
 'jk01111531',
 'xx0001339',
 'jk01091439',
 'xx0096355',
 'mzk2010576785',
 'mzk20191040453',
 'pna2009495546',
 'ola20201075582',
 ...]

In [8]:
df = pl.read_parquet(os.path.join("data","cnb_ceska_proza.parquet")).rename({'autorstvo_kod':'100_7'})
df = pl.concat([df, pl.read_parquet(os.path.join("data","cnb_ceska_poezie.parquet"))])
spisovatelstvo = list(set(df.select(pl.col('100_7')).drop_nulls().to_series().to_list()))

In [9]:
len(spisovatelstvo)

18992

In [10]:
df = pl.read_parquet(os.path.join("data/cnb_sloupce","100.parquet"))
df = df.filter(pl.col("100_7").is_in(cesi))
df = df.join(aut, left_on="100_7", right_on="100_7", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","072.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","655.parquet")), left_on="001", right_on="001", how="left")
df.explode("655_a").group_by("655_a").len().top_k(100, by="len")

shape: (100, 2)
┌─────────────────────────────────┬────────┐
│ 655_a                           ┆ len    │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ null                            ┆ 186758 │
│ učebnice vysokých škol          ┆ 42516  │
│ příručky                        ┆ 34773  │
│ studie                          ┆ 21628  │
│ publikace pro děti              ┆ 21145  │
│ monografie                      ┆ 21065  │
│ textbooks (higher)              ┆ 20797  │
│ handbooks and manuals           ┆ 17960  │
│ místní pohlednice               ┆ 17932  │
│ česká poezie                    ┆ 17034  │
│ české romány                    ┆ 16841  │
│ monographs                      ┆ 16677  │
│ children's literature           ┆ 15169  │
│ Czech fiction                   ┆ 12428  │
│ Czech poetry                    ┆ 12073  │
│ populární hudba                 ┆ 9994   │
│ české příběhy                   ┆ 9515   │
│ informační publikace            ┆ 9372   │
│ české povídky                   ┆ 8949   │
│ učebnice středních škol         ┆ 8813   │
│ studies                         ┆ 8690   │
│ fotografické publikace          ┆ 8460   │
│ Czech stories                   ┆ 8243   │
│ přehledy                        ┆ 7873   │
│ populárně-naučné publikace      ┆ 7801   │
│ pohlednice kulturních památek   ┆ 7157   │
│ metodické příručky              ┆ 7153   │
│ kompaktní disky                 ┆ 7067   │
│ photographical works            ┆ 6956   │
│ vokální linky s podloženým tex… ┆ 6893   │
│ kolektivní monografie           ┆ 6832   │
│ učebnice základních škol        ┆ 6830   │
│ collective monographs           ┆ 6756   │
│ obrazové publikace              ┆ 6717   │
│ popular music                   ┆ 6633   │
│ information publications        ┆ 6361   │
│ partitury                       ┆ 6085   │
│ popular works                   ┆ 6068   │
│ pojednání                       ┆ 5940   │
│ biografie                       ┆ 5897   │
│ české prózy                     ┆ 5818   │
│ sborníky                        ┆ 5509   │
│ partitury pro sólový nástroj    ┆ 5467   │
│ CD-ROM                          ┆ 5355   │
│ hlasy                           ┆ 5312   │
│ scores                          ┆ 5200   │
│ pracovní sešity                 ┆ 5133   │
│ pictorial works                 ┆ 4997   │
│ surveys                         ┆ 4858   │
│ scores for solo instrument      ┆ 4840   │
│ písně                           ┆ 4794   │
│ učebnice                        ┆ 4730   │
│ publikace pro mládež            ┆ 4630   │
│ essays                          ┆ 4577   │
│ parts                           ┆ 4554   │
│ autobiografické vzpomínky       ┆ 4548   │
│ kuchařské recepty               ┆ 4539   │
│ methodological manuals          ┆ 4422   │
│ activity books                  ┆ 4375   │
│ průvodce                        ┆ 4199   │
│ nástěnné vícelisté kalendáře    ┆ 4193   │
│ česká dramata                   ┆ 4084   │
│ Czech short stories             ┆ 4065   │
│ katalogy výstav                 ┆ 4060   │
│ Czech prose                     ┆ 3962   │
│ autobiographical reminiscences  ┆ 3845   │
│ učební texty                    ┆ 3706   │
│ brožury                         ┆ 3698   │
│ vocal parts with text           ┆ 3686   │
│ biography                       ┆ 3598   │
│ textbooks (elementary)          ┆ 3517   │
│ jubilejní publikace             ┆ 3454   │
│ aranžmá (hudba)                 ┆ 3328   │
│ úvahy                           ┆ 3324   │
│ české pohádky                   ┆ 3290   │
│ cookbooks                       ┆ 3219   │
│ textbooks (secondary)           ┆ 3098   │
│ praktická cvičení               ┆ 3040   │
│ vzpomínky                       ┆ 2981   │
│ příběhy                         ┆ 2972   │
│ polky                           ┆ 2946   │
│ educational texts               ┆ 2891   │
│ songs                           ┆ 2753   │
│ historické romány               ┆ 2707   │
│ exhibition catalogs             ┆ 2669   │
│ leporela                        ┆ 2631   │
│ stolní kalendáře                ┆ 2612   │
│ rozhovory                       ┆ 2597   │
│ výstavní plakáty                ┆ 2549   │
│ bibliofilie                     ┆ 2516   │
│ valčíky                         ┆ 2502   │
│ textbooks                       ┆ 2500   │
│ literatura faktu                ┆ 2492   │
│ výbory                          ┆ 2490   │
│ teze                            ┆ 2467   │
│ waltzes                         ┆ 2388   │
│ jubilee books                   ┆ 2382   │
│ abstracts                       ┆ 2360   │
│ Textbooks                       ┆ 2351   │
│ guidebooks                      ┆ 2346   │
└─────────────────────────────────┴────────┘

In [11]:
df = df.explode("655_a").explode("072_x")

## 1. verze

In [13]:
poezie = df.filter(
    pl.col('655_a').str.contains('poez|poetr') | pl.col("072_x").str.contains('poez')
).with_columns(
    kategorie = pl.lit('poezie')
)

proza = df.filter(
    pl.col('655_a').str.contains('román|fiction|novel|příbě|povíd|próz') | pl.col('072_x').str.contains('román|fiction|novel|příbě|povíd|próz')
).with_columns(
    kategorie = pl.lit('próza')
)

vzpominky = df.filter(
    pl.col('655_a').str.contains('vzpomínky|autobiographical')
).with_columns(
    kategorie = pl.lit('vzpomínky')
)

In [14]:
do_grafu = pl.concat(
    [poezie, proza, vzpominky]
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).sort(
    by="rok"
).unique(
    subset=['100_a','245_a'],keep='first'
)

In [15]:
vek = pl.read_parquet(os.path.join("data","narozeni-umrti-gender.parquet"))
do_grafu = do_grafu.join(vek, on="100_7", how="left").with_columns((pl.col("rok") - pl.col("narozeni")).alias("vek"))

In [16]:
do_grafu = do_grafu.drop_nulls("narozeni")

In [17]:
do_grafu = do_grafu.filter(pl.col("vek").is_between(15,100))

In [18]:
do_grafu.sort(by="vek").head(n=10)

shape: (10, 44)
┌──────────┬─────────────────────────────┬───────────────┬───────────┬───┬──────────┬───────┬────────┬─────┐
│ 100_ind1 ┆ 100_a                       ┆ 100_7         ┆ 100_4     ┆ … ┆ narozeni ┆ umrti ┆ gender ┆ vek │
│ ---      ┆ ---                         ┆ ---           ┆ ---       ┆   ┆ ---      ┆ ---   ┆ ---    ┆ --- │
│ str      ┆ str                         ┆ str           ┆ list[str] ┆   ┆ i64      ┆ i64   ┆ str    ┆ i64 │
╞══════════╪═════════════════════════════╪═══════════════╪═══════════╪═══╪══════════╪═══════╪════════╪═════╡
│ 1        ┆ Fidlerová, Lucie,           ┆ mzk2014819685 ┆ ["aut"]   ┆ … ┆ 1999     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Paťhová, Magdaléna,         ┆ xx0302475     ┆ ["aut"]   ┆ … ┆ 2008     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Černá, Barbora,             ┆ jn20010310308 ┆ ["aut"]   ┆ … ┆ 1986     ┆ null  ┆ null   ┆ 15  │
│ 1        ┆ Paťhová, Magdaléna,         ┆ xx0302475     ┆ ["aut"]   ┆ … ┆ 2008     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Braunová, Vlasta,           ┆ jo2018980786  ┆ ["aut"]   ┆ … ┆ 2002     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Kneřová, Bety,              ┆ mzk2009543980 ┆ ["aut"]   ┆ … ┆ 1994     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Jeklová, Veronika,          ┆ xx0148777     ┆ ["aut"]   ┆ … ┆ 1995     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Vokurková, Františka Sylva, ┆ xx0228767     ┆ ["aut"]   ┆ … ┆ 2003     ┆ null  ┆ f      ┆ 15  │
│ 1        ┆ Tobiáš, Petr,               ┆ mzk2009491824 ┆ ["aut"]   ┆ … ┆ 1993     ┆ null  ┆ m      ┆ 15  │
│ 1        ┆ Shaft, Terry,               ┆ xx0218245     ┆ ["aut"]   ┆ … ┆ 2002     ┆ null  ┆ f      ┆ 15  │
└──────────┴─────────────────────────────┴───────────────┴───────────┴───┴──────────┴───────┴────────┴─────┘

In [19]:
do_grafu = do_grafu.filter((pl.col("umrti") >= pl.col('rok')) | pl.col("umrti").is_null())

## Mediánový věk

In [21]:
do_grafu.group_by("kategorie").agg(pl.col("vek").median())

shape: (3, 2)
┌───────────┬──────┐
│ kategorie ┆ vek  │
│ ---       ┆ ---  │
│ str       ┆ f64  │
╞═══════════╪══════╡
│ vzpomínky ┆ 67.0 │
│ próza     ┆ 50.0 │
│ poezie    ┆ 52.0 │
└───────────┴──────┘

## Druhý pokus

In [23]:
do_grafu.sample(10)

shape: (10, 44)
┌──────────┬─────────────────────┬───────────────┬───────────┬───┬──────────┬───────┬────────┬─────┐
│ 100_ind1 ┆ 100_a               ┆ 100_7         ┆ 100_4     ┆ … ┆ narozeni ┆ umrti ┆ gender ┆ vek │
│ ---      ┆ ---                 ┆ ---           ┆ ---       ┆   ┆ ---      ┆ ---   ┆ ---    ┆ --- │
│ str      ┆ str                 ┆ str           ┆ list[str] ┆   ┆ i64      ┆ i64   ┆ str    ┆ i64 │
╞══════════╪═════════════════════╪═══════════════╪═══════════╪═══╪══════════╪═══════╪════════╪═════╡
│ 1        ┆ Vidura, Bohumír,    ┆ jx20100209041 ┆ ["aut"]   ┆ … ┆ 1939     ┆ null  ┆ m      ┆ 83  │
│ 1        ┆ Černík, Michal,     ┆ jk01021422    ┆ ["aut"]   ┆ … ┆ 1943     ┆ null  ┆ m      ┆ 65  │
│ 1        ┆ Otopalová, Jitka,   ┆ pna2010616260 ┆ ["aut"]   ┆ … ┆ 1964     ┆ null  ┆ f      ┆ 47  │
│ 1        ┆ Blažek, Pavel,      ┆ mzk2009534993 ┆ ["aut"]   ┆ … ┆ 1944     ┆ null  ┆ m      ┆ 65  │
│ 1        ┆ Mišíková, Eva,      ┆ jn99240001006 ┆ ["aut"]   ┆ … ┆ 1961     ┆ null  ┆ f      ┆ 51  │
│ 1        ┆ Höppner, Ondřej,    ┆ xx0062058     ┆ ["aut"]   ┆ … ┆ 1965     ┆ 2021  ┆ m      ┆ 53  │
│ 1        ┆ Bešťáková, Eva,     ┆ jk01011935    ┆ ["aut"]   ┆ … ┆ 1932     ┆ 2021  ┆ f      ┆ 68  │
│ 1        ┆ Krňanský, Jaroslav, ┆ jo20201079149 ┆ ["aut"]   ┆ … ┆ 1951     ┆ null  ┆ m      ┆ 52  │
│ 1        ┆ Jirotka, Antonín,   ┆ jx20040623006 ┆ ["aut"]   ┆ … ┆ 1946     ┆ null  ┆ m      ┆ 68  │
│ 1        ┆ Kapoun, Oldřich     ┆ xx0001113     ┆ ["aut"]   ┆ … ┆ 1955     ┆ null  ┆ m      ┆ 61  │
└──────────┴─────────────────────┴───────────────┴───────────┴───┴──────────┴───────┴────────┴─────┘

In [24]:
do_grafu_drive = do_grafu.filter(pl.col("rok").is_between(1800,1938)).with_columns(obdobi = pl.lit('1800-1938'))
print(len(do_grafu_drive))
do_grafu_ted = do_grafu.filter(pl.col("rok").is_between(2000,2020)).with_columns(obdobi = pl.lit('2000-2020'))
print(len(do_grafu_ted))

8223
27669

In [25]:
do_grafu_basnici = pl.concat([do_grafu_drive.filter(pl.col("kategorie") == "poezie"), do_grafu_ted.filter(pl.col("kategorie") == "poezie")]).group_by(["obdobi","vek"]).len()
do_grafu_basnici

shape: (152, 3)
┌───────────┬─────┬─────┐
│ obdobi    ┆ vek ┆ len │
│ ---       ┆ --- ┆ --- │
│ str       ┆ i64 ┆ u32 │
╞═══════════╪═════╪═════╡
│ 2000-2020 ┆ 19  ┆ 23  │
│ 1800-1938 ┆ 35  ┆ 66  │
│ 1800-1938 ┆ 25  ┆ 83  │
│ 2000-2020 ┆ 26  ┆ 71  │
│ 2000-2020 ┆ 35  ┆ 85  │
│ 2000-2020 ┆ 40  ┆ 116 │
│ 2000-2020 ┆ 53  ┆ 150 │
│ 2000-2020 ┆ 88  ┆ 29  │
│ 2000-2020 ┆ 54  ┆ 121 │
│ 1800-1938 ┆ 15  ┆ 2   │
│ 2000-2020 ┆ 73  ┆ 116 │
│ 1800-1938 ┆ 48  ┆ 39  │
│ 1800-1938 ┆ 78  ┆ 7   │
│ 1800-1938 ┆ 37  ┆ 57  │
│ 1800-1938 ┆ 62  ┆ 15  │
│ 1800-1938 ┆ 72  ┆ 4   │
│ 1800-1938 ┆ 68  ┆ 17  │
│ 1800-1938 ┆ 71  ┆ 15  │
│ 2000-2020 ┆ 71  ┆ 121 │
│ 2000-2020 ┆ 86  ┆ 45  │
│ 1800-1938 ┆ 77  ┆ 4   │
│ 1800-1938 ┆ 23  ┆ 66  │
│ 2000-2020 ┆ 93  ┆ 5   │
│ 2000-2020 ┆ 85  ┆ 65  │
│ 2000-2020 ┆ 16  ┆ 4   │
│ 2000-2020 ┆ 58  ┆ 126 │
│ 1800-1938 ┆ 24  ┆ 64  │
│ 1800-1938 ┆ 29  ┆ 90  │
│ 2000-2020 ┆ 39  ┆ 94  │
│ 2000-2020 ┆ 97  ┆ 5   │
│ 2000-2020 ┆ 75  ┆ 109 │
│ 2000-2020 ┆ 41  ┆ 97  │
│ 2000-2020 ┆ 50  ┆ 156 │
│ 2000-2020 ┆ 61  ┆ 135 │
│ 1800-1938 ┆ 55  ┆ 21  │
│ 2000-2020 ┆ 46  ┆ 107 │
│ 1800-1938 ┆ 75  ┆ 6   │
│ 2000-2020 ┆ 45  ┆ 99  │
│ 1800-1938 ┆ 85  ┆ 3   │
│ 2000-2020 ┆ 89  ┆ 21  │
│ 2000-2020 ┆ 62  ┆ 161 │
│ 2000-2020 ┆ 80  ┆ 120 │
│ 2000-2020 ┆ 36  ┆ 102 │
│ 2000-2020 ┆ 49  ┆ 98  │
│ 1800-1938 ┆ 81  ┆ 4   │
│ 1800-1938 ┆ 38  ┆ 63  │
│ 1800-1938 ┆ 42  ┆ 65  │
│ 1800-1938 ┆ 28  ┆ 95  │
│ 2000-2020 ┆ 79  ┆ 75  │
│ 1800-1938 ┆ 67  ┆ 14  │
│ …         ┆ …   ┆ …   │
│ 1800-1938 ┆ 50  ┆ 43  │
│ 1800-1938 ┆ 33  ┆ 74  │
│ 2000-2020 ┆ 43  ┆ 108 │
│ 2000-2020 ┆ 25  ┆ 67  │
│ 2000-2020 ┆ 21  ┆ 38  │
│ 2000-2020 ┆ 74  ┆ 97  │
│ 2000-2020 ┆ 69  ┆ 135 │
│ 2000-2020 ┆ 27  ┆ 75  │
│ 1800-1938 ┆ 40  ┆ 49  │
│ 2000-2020 ┆ 42  ┆ 104 │
│ 2000-2020 ┆ 87  ┆ 58  │
│ 1800-1938 ┆ 19  ┆ 20  │
│ 2000-2020 ┆ 67  ┆ 174 │
│ 1800-1938 ┆ 61  ┆ 20  │
│ 1800-1938 ┆ 83  ┆ 1   │
│ 2000-2020 ┆ 30  ┆ 95  │
│ 1800-1938 ┆ 60  ┆ 27  │
│ 2000-2020 ┆ 23  ┆ 40  │
│ 2000-2020 ┆ 66  ┆ 138 │
│ 1800-1938 ┆ 63  ┆ 32  │
│ 1800-1938 ┆ 36  ┆ 75  │
│ 1800-1938 ┆ 32  ┆ 64  │
│ 2000-2020 ┆ 72  ┆ 115 │
│ 2000-2020 ┆ 91  ┆ 22  │
│ 2000-2020 ┆ 31  ┆ 104 │
│ 2000-2020 ┆ 95  ┆ 3   │
│ 2000-2020 ┆ 33  ┆ 94  │
│ 1800-1938 ┆ 69  ┆ 12  │
│ 2000-2020 ┆ 34  ┆ 104 │
│ 1800-1938 ┆ 47  ┆ 48  │
│ 2000-2020 ┆ 68  ┆ 147 │
│ 1800-1938 ┆ 53  ┆ 41  │
│ 2000-2020 ┆ 51  ┆ 114 │
│ 2000-2020 ┆ 24  ┆ 56  │
│ 2000-2020 ┆ 37  ┆ 94  │
│ 1800-1938 ┆ 20  ┆ 37  │
│ 2000-2020 ┆ 70  ┆ 180 │
│ 2000-2020 ┆ 84  ┆ 56  │
│ 1800-1938 ┆ 27  ┆ 75  │
│ 1800-1938 ┆ 80  ┆ 4   │
│ 1800-1938 ┆ 43  ┆ 42  │
│ 2000-2020 ┆ 47  ┆ 91  │
│ 1800-1938 ┆ 39  ┆ 61  │
│ 2000-2020 ┆ 20  ┆ 21  │
│ 1800-1938 ┆ 21  ┆ 51  │
│ 2000-2020 ┆ 29  ┆ 90  │
│ 2000-2020 ┆ 32  ┆ 87  │
│ 1800-1938 ┆ 57  ┆ 25  │
│ 2000-2020 ┆ 99  ┆ 3   │
│ 2000-2020 ┆ 59  ┆ 140 │
└───────────┴─────┴─────┘

In [26]:
tvar1 = alt.Chart(do_grafu_basnici.to_pandas(), width=300, height=100).mark_line(interpolate="monotone").encode(
    alt.X('vek:Q').axis(domain=False, tickSize=0, title=None),
    alt.Y('len:Q').stack('zero').axis(None),
    alt.Color('obdobi:N', sort=['2000-2020','1800-1838'], scale=alt.Scale(range=['#D6534B', '#DB842F']), legend=alt.Legend(title=None, orient="top")),
    alt.StrokeDash('obdobi:N', sort=['2000-2020','1800-1838'], legend=None)
)

tvar1

alt.Chart(...)

In [27]:
do_grafu_prozaici = pl.concat([do_grafu_drive.filter(pl.col("kategorie") == "próza"), do_grafu_ted.filter(pl.col("kategorie") == "próza")]).group_by(["obdobi","vek"]).len()

In [28]:
tvar2 = alt.Chart(do_grafu_prozaici.to_pandas(), width=300, height=100, title="…beletrii…").mark_line(interpolate="monotone").encode(
    alt.X('vek:Q').axis(domain=False, tickSize=0, title=None),
    alt.Y('len:Q').stack('zero').axis(None),
    alt.Color('obdobi:N', sort=['2000-2020','1800-1838'], scale=alt.Scale(range=['#D6534B', '#DB842F']), legend=None),
    alt.StrokeDash('obdobi:N', sort=['2000-2020','1800-1838'], legend=None)
)

tvar2

alt.Chart(...)

In [29]:
do_grafu_vzpominky = pl.concat([do_grafu_drive.filter(pl.col("kategorie") == "vzpomínky"), do_grafu_ted.filter(pl.col("kategorie") == "vzpomínky")]).group_by(["obdobi","vek"]).len()

In [30]:
do_grafu_vzpominky

shape: (142, 3)
┌───────────┬─────┬─────┐
│ obdobi    ┆ vek ┆ len │
│ ---       ┆ --- ┆ --- │
│ str       ┆ i64 ┆ u32 │
╞═══════════╪═════╪═════╡
│ 1800-1938 ┆ 82  ┆ 2   │
│ 2000-2020 ┆ 87  ┆ 43  │
│ 1800-1938 ┆ 69  ┆ 4   │
│ 1800-1938 ┆ 40  ┆ 4   │
│ 1800-1938 ┆ 26  ┆ 3   │
│ 2000-2020 ┆ 80  ┆ 111 │
│ 2000-2020 ┆ 59  ┆ 48  │
│ 2000-2020 ┆ 61  ┆ 50  │
│ 2000-2020 ┆ 81  ┆ 68  │
│ 1800-1938 ┆ 81  ┆ 1   │
│ 2000-2020 ┆ 56  ┆ 32  │
│ 2000-2020 ┆ 28  ┆ 12  │
│ 2000-2020 ┆ 48  ┆ 20  │
│ 1800-1938 ┆ 36  ┆ 4   │
│ 1800-1938 ┆ 45  ┆ 3   │
│ 2000-2020 ┆ 47  ┆ 30  │
│ 2000-2020 ┆ 73  ┆ 68  │
│ 2000-2020 ┆ 82  ┆ 58  │
│ 1800-1938 ┆ 67  ┆ 4   │
│ 1800-1938 ┆ 61  ┆ 5   │
│ 1800-1938 ┆ 57  ┆ 3   │
│ 1800-1938 ┆ 80  ┆ 3   │
│ 2000-2020 ┆ 42  ┆ 21  │
│ 2000-2020 ┆ 93  ┆ 13  │
│ 2000-2020 ┆ 53  ┆ 27  │
│ 2000-2020 ┆ 78  ┆ 76  │
│ 2000-2020 ┆ 71  ┆ 51  │
│ 2000-2020 ┆ 84  ┆ 49  │
│ 2000-2020 ┆ 55  ┆ 46  │
│ 2000-2020 ┆ 58  ┆ 32  │
│ 1800-1938 ┆ 60  ┆ 11  │
│ 2000-2020 ┆ 41  ┆ 31  │
│ 2000-2020 ┆ 65  ┆ 60  │
│ 1800-1938 ┆ 49  ┆ 3   │
│ 2000-2020 ┆ 94  ┆ 14  │
│ 2000-2020 ┆ 86  ┆ 53  │
│ 1800-1938 ┆ 27  ┆ 1   │
│ 2000-2020 ┆ 66  ┆ 48  │
│ 1800-1938 ┆ 48  ┆ 6   │
│ 2000-2020 ┆ 24  ┆ 1   │
│ 2000-2020 ┆ 74  ┆ 64  │
│ 1800-1938 ┆ 56  ┆ 6   │
│ 2000-2020 ┆ 17  ┆ 1   │
│ 2000-2020 ┆ 62  ┆ 47  │
│ 2000-2020 ┆ 69  ┆ 47  │
│ 1800-1938 ┆ 78  ┆ 1   │
│ 2000-2020 ┆ 44  ┆ 32  │
│ 2000-2020 ┆ 38  ┆ 28  │
│ 1800-1938 ┆ 33  ┆ 1   │
│ 2000-2020 ┆ 85  ┆ 56  │
│ …         ┆ …   ┆ …   │
│ 2000-2020 ┆ 63  ┆ 50  │
│ 1800-1938 ┆ 55  ┆ 8   │
│ 2000-2020 ┆ 75  ┆ 80  │
│ 2000-2020 ┆ 35  ┆ 26  │
│ 1800-1938 ┆ 85  ┆ 1   │
│ 2000-2020 ┆ 20  ┆ 5   │
│ 1800-1938 ┆ 31  ┆ 1   │
│ 1800-1938 ┆ 35  ┆ 7   │
│ 1800-1938 ┆ 73  ┆ 1   │
│ 1800-1938 ┆ 63  ┆ 3   │
│ 2000-2020 ┆ 39  ┆ 22  │
│ 2000-2020 ┆ 68  ┆ 53  │
│ 2000-2020 ┆ 76  ┆ 67  │
│ 1800-1938 ┆ 18  ┆ 1   │
│ 1800-1938 ┆ 52  ┆ 7   │
│ 2000-2020 ┆ 34  ┆ 24  │
│ 1800-1938 ┆ 54  ┆ 2   │
│ 1800-1938 ┆ 37  ┆ 5   │
│ 2000-2020 ┆ 49  ┆ 29  │
│ 2000-2020 ┆ 97  ┆ 5   │
│ 2000-2020 ┆ 57  ┆ 44  │
│ 2000-2020 ┆ 50  ┆ 44  │
│ 1800-1938 ┆ 86  ┆ 1   │
│ 1800-1938 ┆ 64  ┆ 4   │
│ 2000-2020 ┆ 92  ┆ 25  │
│ 1800-1938 ┆ 65  ┆ 2   │
│ 1800-1938 ┆ 44  ┆ 5   │
│ 1800-1938 ┆ 83  ┆ 1   │
│ 1800-1938 ┆ 66  ┆ 3   │
│ 1800-1938 ┆ 71  ┆ 3   │
│ 2000-2020 ┆ 54  ┆ 33  │
│ 1800-1938 ┆ 42  ┆ 2   │
│ 2000-2020 ┆ 36  ┆ 21  │
│ 2000-2020 ┆ 95  ┆ 14  │
│ 1800-1938 ┆ 72  ┆ 5   │
│ 2000-2020 ┆ 51  ┆ 30  │
│ 2000-2020 ┆ 52  ┆ 37  │
│ 2000-2020 ┆ 91  ┆ 21  │
│ 1800-1938 ┆ 70  ┆ 5   │
│ 1800-1938 ┆ 30  ┆ 1   │
│ 2000-2020 ┆ 72  ┆ 81  │
│ 1800-1938 ┆ 34  ┆ 6   │
│ 1800-1938 ┆ 62  ┆ 7   │
│ 2000-2020 ┆ 89  ┆ 24  │
│ 2000-2020 ┆ 31  ┆ 7   │
│ 1800-1938 ┆ 75  ┆ 3   │
│ 2000-2020 ┆ 25  ┆ 6   │
│ 1800-1938 ┆ 41  ┆ 5   │
│ 1800-1938 ┆ 47  ┆ 5   │
│ 2000-2020 ┆ 98  ┆ 5   │
└───────────┴─────┴─────┘

In [31]:
tvar3 = alt.Chart(do_grafu_vzpominky.to_pandas(), width=300, height=100, title="…a vzpomínky").mark_line(interpolate="monotone").encode(
    alt.X('vek:Q').axis(domain=False, tickSize=0, title=None),
    alt.Y('len:Q').stack('zero').axis(None),
    alt.Color('obdobi:N', sort=['2000-2020','1800-1838'], scale=alt.Scale(range=['#D6534B', '#DB842F']), legend=None),
    alt.StrokeDash('obdobi:N', sort=['2000-2020','1800-1838'], legend=None)
)

tvar3

alt.Chart(...)

In [32]:
alt.vconcat(tvar1, tvar2, tvar3, title=alt.Title("V jakém věku lidé vydávají básně…")).resolve_scale(x='shared').configure_view(stroke='transparent')

alt.VConcatChart(...)

## Finální verze

In [34]:
kolik = len(do_grafu.select(pl.col("100_7").unique()))
kolik

15820

In [35]:
do_grafu.select(pl.col("rok").median())

shape: (1, 1)
┌────────┐
│ rok    │
│ ---    │
│ f64    │
╞════════╡
│ 2008.0 │
└────────┘

In [71]:
veky_autorstva = alt.Chart(do_grafu.with_columns(pl.col("kategorie").replace(
    {'próza':'…prózu','poezie':'…poezii','vzpomínky':'…vzpomínky'}
)).group_by(["vek","kategorie"]).len().to_pandas(),
         title=alt.Title(
             'V jakém věku čeští autoři a autorky publikují…',
             subtitle=
             ["Osamělé vrcholky odpovídají kulatým narozeninám.",
              "(Převažují publikace z posledních dvou dekád. Grafy mají odlišná měřítka.)"]
         )).mark_bar(width=1).encode(
    alt.X("vek:Q", scale=alt.Scale(domainMax=90, domainMin=20), title=None, axis=alt.Axis(tickCount=4)),
    alt.Y("len:Q", title=None, scale=alt.Scale(domainMin=1), axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6', orient='right', format='~s')),
    alt.Color('kategorie:N', scale=alt.Scale(range=['#E09DA3','#70871E','#DB842F',]), title=None, legend=None),
    alt.Column('kategorie:N', spacing=8, title=None, sort=['…prózu','…poezii','…vzpomínky'],
           header=alt.Header(labelAngle=0, labelAlign='left', labelAnchor='start', labelFontWeight=500, labelFont='Asap', labelOrient="top"))
).properties(
    width=kredity['sirka'] / 3.8, 
    height=kredity['vyska_nizkych'], 
    autosize={'type': 'fit', 'contains': 'padding'}
).configure_view(stroke='transparent').configure_axis(grid=False, domain=False).resolve_axis(x="independent").resolve_scale(y="independent")

veky_autorstva

alt.Chart(...)

In [73]:
me_to_neurazi(veky_autorstva, soubor="02_tvar_kariery", kredity=kredity['default'])

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_tvar_kariery.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_tvar_kariery.svg" width="100%" alt="Graf s titulkem „V jakém věku čeští autoři a autorky publikují…“. Další texty by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>