In [1]:
import os
import datetime
import warnings
import polars as pl
import pandas as pd
import altair as alt

from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.hezke_jmeno import hezke_jmeno
from src.kristi_promin import kristi_promin
from src.zjisti_vazbu import zjisti_vazbu
from src.me_to_neurazi import me_to_neurazi

pl.Config(tbl_rows=100)
alt.data_transformers.disable_max_rows()
alt.themes.register('irozhlas', kristi_promin)
alt.themes.enable('irozhlas')
warnings.filterwarnings('ignore')

In [2]:
df = pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet"))
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","100.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left")
df = df.to_pandas()
df = df[df["leader"].str[6].isin(["a", "t"])]
df = df[~df["leader"].str[7].isin(["b", "i", "s", " "])]
df = df[(df["008"].str[15:17] == "xr") & (df["008"].str[35:38] == "cze")]
df = pl.from_pandas(df)
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","020.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","022.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","300.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","655.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","700.parquet")), left_on="001", right_on="001", how="left")
df = df.explode("022_a").filter(pl.col("022_a").is_null())
df = df.with_columns(pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok'))
df = df.with_columns(pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran'))
df = df.with_columns(pl.col('245_a').map_elements(bez_bordelu, return_dtype=str))
df = df.explode("020_q").with_columns(pl.col("020_q").map_elements(zjisti_vazbu, return_dtype=str).alias('vazba'))
df = df.explode('245_p').with_columns(pl.col('245_p').map_elements(bez_bordelu, return_dtype=str))
print(len(df))
df = df.filter(~pl.col('rok').is_null()).sort(by='rok')
df = df.filter((~pl.col("245_h").str.contains("grafika")) | pl.col("245_h").is_null())
print(len(df))

1001279
991612

In [3]:
df = df.filter(pl.col("rok") >= 1800)

In [4]:
df.group_by(["100_a","100_7"]).len().sort(by="len",descending=True).head(n=100)

shape: (100, 3)
┌─────────────────────────────────┬───────────────┬────────┐
│ 100_a                           ┆ 100_7         ┆ len    │
│ ---                             ┆ ---           ┆ ---    │
│ str                             ┆ str           ┆ u32    │
╞═════════════════════════════════╪═══════════════╪════════╡
│ null                            ┆ null          ┆ 202742 │
│ Unger, Gert F.,                 ┆ jn20001103529 ┆ 1682   │
│ Vandenberg, Patricia,           ┆ jn20000810141 ┆ 1185   │
│ Němcová, Božena,                ┆ jk01083016    ┆ 1126   │
│ Jirásek, Alois,                 ┆ jk01051816    ┆ 1112   │
│ Čapek, Karel,                   ┆ jk01021023    ┆ 874    │
│ Shakespeare, William,           ┆ jn19981002129 ┆ 822    │
│ Verne, Jules,                   ┆ jn19990008769 ┆ 793    │
│ Dark, Jason,                    ┆ jn20000810032 ┆ 725    │
│ Vedral, Jiří,                   ┆ mzk2003169026 ┆ 713    │
│ Javořická, Vlasta,              ┆ jk01051344    ┆ 685    │
│ Neruda, Jan,                    ┆ jk01083209    ┆ 666    │
│ Courths-Mahler, Hedwig,         ┆ jn19990001513 ┆ 652    │
│ May, Karl,                      ┆ jn19990005499 ┆ 573    │
│ Kirby, John                     ┆ jx20040611003 ┆ 563    │
│ Erben, Karel Jaromír,           ┆ jk01030532    ┆ 543    │
│ Vrchlický, Jaroslav,            ┆ jk01151037    ┆ 533    │
│ Masaryk, Tomáš Garrigue,        ┆ jk01080472    ┆ 499    │
│ Dumas, Alexandre,               ┆ jn19990001907 ┆ 432    │
│ Rais, Karel Václav,             ┆ jk01101955    ┆ 407    │
│ Tyl, Josef Kajetán,             ┆ jk01140553    ┆ 405    │
│ Tolstoj, Lev Nikolajevič,       ┆ jn19981002230 ┆ 398    │
│ Komenský, Jan Amos,             ┆ jk01061444    ┆ 391    │
│ Čech, Svatopluk,                ┆ jk01021137    ┆ 388    │
│ Štohl, Pavel,                   ┆ xx0024514     ┆ 380    │
│ Lada, Josef,                    ┆ jk01071364    ┆ 377    │
│ Mácha, Karel Hynek,             ┆ jk01072915    ┆ 377    │
│ Clifton, Léon                   ┆ xx0111518     ┆ 353    │
│ Zeyer, Julius,                  ┆ jk01152552    ┆ 352    │
│ Nedbalová, Marie                ┆ jo2014816080  ┆ 345    │
│ Pittnerová, Vlasta,             ┆ jk01093291    ┆ 342    │
│ Seifert, Jaroslav,              ┆ jk01110657    ┆ 340    │
│ Lenin, Vladimir Il‘jič,         ┆ jn19981001737 ┆ 340    │
│ Strong, Pitt,                   ┆ jo2005267810  ┆ 324    │
│ Světlá, Karolina,               ┆ jk01121895    ┆ 323    │
│ Batěk, Alexandr,                ┆ jk01011106    ┆ 323    │
│ Novotný, Miloš                  ┆ mzk2013757672 ┆ 320    │
│ Birkner-Mahler, Frieda,         ┆ jn20000600873 ┆ 319    │
│ Scott, William,                 ┆ ola2003188680 ┆ 318    │
│ Žáček, Jiří,                    ┆ jk01152946    ┆ 317    │
│ Šváb-Malostranský, Josef,       ┆ jk01131780    ┆ 315    │
│ Hrubín, František,              ┆ jk01042920    ┆ 313    │
│ Baar, Jindřich Šimon,           ┆ jk01010468    ┆ 311    │
│ Grey, Zane,                     ┆ jn19990002874 ┆ 306    │
│ Christie, Agatha,               ┆ jn19981000482 ┆ 298    │
│ Havlíček Borovský, Karel,       ┆ jk01040361    ┆ 298    │
│ Foglar, Jaroslav,               ┆ jk01031485    ┆ 289    │
│ Machar, Josef Svatopluk,        ┆ jk01072996    ┆ 288    │
│ Miler, Zdeněk,                  ┆ jk01081695    ┆ 286    │
│ Pospíšilová, Zuzana,            ┆ mzk2006331486 ┆ 284    │
│ Hálek, Vítězslav,               ┆ jk01033219    ┆ 282    │
│ Beneš Třebízský, Václav,        ┆ jk01011653    ┆ 282    │
│ Brezina, Thomas,                ┆ jn20001227589 ┆ 280    │
│ Nezval, Vítězslav,              ┆ jk01090162    ┆ 279    │
│ Dostojevskij, Fedor Michajlovi… ┆ jn19990210182 ┆ 278    │
│ David, Petr,                    ┆ xx0006786     ┆ 277    │
│ Steiner, Rudolf,                ┆ jn19990009728 ┆ 277    │
│ Brahová, Marie                  ┆ jn20010310261 ┆ 273    │
│ Wallace, Edgar,                 ┆ jn19990008883 ┆ 272    │
│ Vrba, Jan,                      ┆ jk01150966    ┆ 271    │
│ Šulc, Petr,                     ┆ jn20011018797 ┆ 270    │
│ Bezruč, Petr,                   ┆ jk01011993    ┆ 270    │
│ Cílek, Roman,                   ┆ jk01020709    ┆ 268    │
│ London, Jack,                   ┆ jn19990005166 ┆ 268    │
│ Gardner, Erle Stanley,          ┆ jn19981001320 ┆ 265    │
│ Březinová, Ivona,               ┆ jn19990218010 ┆ 264    │
│ Rowling, J. K.,                 ┆ jo20000071115 ┆ 263    │
│ Doležalová, Alena Bára          ┆ hka2010562386 ┆ 261    │
│ Herrmann, Ignát,                ┆ jk01040882    ┆ 261    │
│ Hašek, Jaroslav,                ┆ jk01040097    ┆ 260    │
│ Nejedlý, Zdeněk,                ┆ jk01082971    ┆ 259    │
│ Štiková, Věra                   ┆ mzk2009512876 ┆ 256    │
│ Majerová, Marie,                ┆ jk01073121    ┆ 253    │
│ Petiška, Eduard,                ┆ jk01092720    ┆ 252    │
│ Dobrovolný, Bohumil,            ┆ jk01022456    ┆ 251    │
│ King, Stephen,                  ┆ jn19990004346 ┆ 251    │
│ Steel, Danielle,                ┆ jn20000605140 ┆ 249    │
│ Balzac, Honoré de,              ┆ jn19990000418 ┆ 248    │
│ Šplíchal, Antonín,              ┆ ola2003162788 ┆ 245    │
│ Klostermann, Karel,             ┆ jk01060677    ┆ 244    │
│ Pratchett, Terry,               ┆ jo20000080627 ┆ 243    │
│ Gor‘kij, Maksim,                ┆ jn19990002786 ┆ 242    │
│ Klínský, Petr                   ┆ jn20001227476 ┆ 241    │
│ Svoboda, F. X.,                 ┆ jk01121960    ┆ 240    │
│ Vondruška, Vlastimil,           ┆ xx0004129     ┆ 235    │
│ Bauer, Jan,                     ┆ jk01011157    ┆ 233    │
│ Čtvrtek, Václav,                ┆ jk01021929    ┆ 232    │
│ Maruna, Jan,                    ┆ mzk2004236668 ┆ 230    │
│ Čechov, Anton Pavlovič,         ┆ jn19990210160 ┆ 225    │
│ Šťastný, Alfons Bohumil,        ┆ jk01131099    ┆ 225    │
│ Štíplová, Ljuba,                ┆ jk01131441    ┆ 224    │
│ McBain, Ed,                     ┆ jn19981001834 ┆ 224    │
│ Zahradník-Brodský, Bohumil,     ┆ jk01151969    ┆ 223    │
│ Hrabal, Bohumil,                ┆ jk01042564    ┆ 222    │
│ Sedláček, Václav,               ┆ jk01110523    ┆ 222    │
│ Etzold, Hans-Rüdiger,           ┆ xx0020263     ┆ 219    │
│ Říha, Bohumil,                  ┆ jk01110164    ┆ 217    │
│ Deml, Jakub,                    ┆ jk01022199    ┆ 217    │
│ Poláček, Karel,                 ┆ jk01100136    ┆ 215    │
│ Mark, William,                  ┆ jo20241218643 ┆ 214    │
└─────────────────────────────────┴───────────────┴────────┘

In [5]:
nechcemejetam = [
    "jn19990008769",
    "jx20060515016",
    "jn19981002230",
    "jn19981001737",
    "jn19990210182",
    "jn19990001842",
    "jn19990002786",
    "jn19990004346",
    "jn20020721077",
    "jn19990210513",
    "jn19990005488",
    "jo20000080627",
    "jn19990000171",
    "jn20001005715",
    "jn19981002409",
    "jn20000810141",
    "jn19981002129",
    "jn20001103529",
    "jn20000810032",
    "jn19990001513",
    "jx20040611003",
    "jn19990005499",
    "jn19981002230",
    "jn19990001907",
    "jo2005267810",
    "jo20241218643"
]

In [6]:
df = df.filter(~pl.col("100_7").is_in(nechcemejetam))

In [7]:
df.group_by("rok").len().sort(by="rok")

shape: (226, 2)
┌──────┬───────┐
│ rok  ┆ len   │
│ ---  ┆ ---   │
│ i64  ┆ u32   │
╞══════╪═══════╡
│ 1800 ┆ 1     │
│ 1801 ┆ 10    │
│ 1802 ┆ 10    │
│ 1803 ┆ 14    │
│ 1804 ┆ 15    │
│ 1805 ┆ 16    │
│ 1806 ┆ 9     │
│ 1807 ┆ 16    │
│ 1808 ┆ 16    │
│ 1809 ┆ 14    │
│ 1810 ┆ 15    │
│ 1811 ┆ 10    │
│ 1812 ┆ 20    │
│ 1813 ┆ 14    │
│ 1814 ┆ 19    │
│ 1815 ┆ 20    │
│ 1816 ┆ 21    │
│ 1817 ┆ 21    │
│ 1818 ┆ 35    │
│ 1819 ┆ 38    │
│ 1820 ┆ 40    │
│ 1821 ┆ 49    │
│ 1822 ┆ 40    │
│ 1823 ┆ 42    │
│ 1824 ┆ 45    │
│ 1825 ┆ 50    │
│ 1826 ┆ 33    │
│ 1827 ┆ 45    │
│ 1828 ┆ 42    │
│ 1829 ┆ 32    │
│ 1830 ┆ 48    │
│ 1831 ┆ 47    │
│ 1832 ┆ 34    │
│ 1833 ┆ 33    │
│ 1834 ┆ 32    │
│ 1835 ┆ 45    │
│ 1836 ┆ 45    │
│ 1837 ┆ 37    │
│ 1838 ┆ 37    │
│ 1839 ┆ 38    │
│ 1840 ┆ 68    │
│ 1841 ┆ 49    │
│ 1842 ┆ 63    │
│ 1843 ┆ 75    │
│ 1844 ┆ 98    │
│ 1845 ┆ 76    │
│ 1846 ┆ 82    │
│ 1847 ┆ 90    │
│ 1848 ┆ 99    │
│ 1849 ┆ 104   │
│ …    ┆ …     │
│ 1976 ┆ 3795  │
│ 1977 ┆ 3783  │
│ 1978 ┆ 3770  │
│ 1979 ┆ 4010  │
│ 1980 ┆ 4118  │
│ 1981 ┆ 3913  │
│ 1982 ┆ 4014  │
│ 1983 ┆ 3985  │
│ 1984 ┆ 4158  │
│ 1985 ┆ 3994  │
│ 1986 ┆ 4209  │
│ 1987 ┆ 4267  │
│ 1988 ┆ 4349  │
│ 1989 ┆ 4690  │
│ 1990 ┆ 5215  │
│ 1991 ┆ 5821  │
│ 1992 ┆ 6441  │
│ 1993 ┆ 7277  │
│ 1994 ┆ 7642  │
│ 1995 ┆ 8577  │
│ 1996 ┆ 9625  │
│ 1997 ┆ 10220 │
│ 1998 ┆ 10555 │
│ 1999 ┆ 10836 │
│ 2000 ┆ 11939 │
│ 2001 ┆ 11733 │
│ 2002 ┆ 12151 │
│ 2003 ┆ 12578 │
│ 2004 ┆ 13100 │
│ 2005 ┆ 13708 │
│ 2006 ┆ 14439 │
│ 2007 ┆ 14846 │
│ 2008 ┆ 15559 │
│ 2009 ┆ 14674 │
│ 2010 ┆ 15122 │
│ 2011 ┆ 14886 │
│ 2012 ┆ 14889 │
│ 2013 ┆ 14808 │
│ 2014 ┆ 15089 │
│ 2015 ┆ 15489 │
│ 2016 ┆ 14653 │
│ 2017 ┆ 14434 │
│ 2018 ┆ 14548 │
│ 2019 ┆ 14153 │
│ 2020 ┆ 12872 │
│ 2021 ┆ 13166 │
│ 2022 ┆ 13551 │
│ 2023 ┆ 12045 │
│ 2024 ┆ 10424 │
│ 2025 ┆ 440   │
└──────┴───────┘

In [8]:
df.group_by("100_a").len().sort(by="len",descending=True).head(100)

shape: (100, 2)
┌─────────────────────────────┬──────┐
│ 100_a                       ┆ len  │
│ ---                         ┆ ---  │
│ str                         ┆ u32  │
╞═════════════════════════════╪══════╡
│ Němcová, Božena,            ┆ 1126 │
│ Jirásek, Alois,             ┆ 1112 │
│ Čapek, Karel,               ┆ 880  │
│ Vedral, Jiří,               ┆ 714  │
│ Javořická, Vlasta,          ┆ 685  │
│ Neruda, Jan,                ┆ 666  │
│ Erben, Karel Jaromír,       ┆ 543  │
│ Vrchlický, Jaroslav,        ┆ 533  │
│ Masaryk, Tomáš Garrigue,    ┆ 499  │
│ Rais, Karel Václav,         ┆ 407  │
│ Tyl, Josef Kajetán,         ┆ 405  │
│ Čech, Svatopluk,            ┆ 396  │
│ Komenský, Jan Amos,         ┆ 391  │
│ Štohl, Pavel,               ┆ 380  │
│ Lada, Josef,                ┆ 378  │
│ Mácha, Karel Hynek,         ┆ 377  │
│ Clifton, Léon               ┆ 353  │
│ Zeyer, Julius,              ┆ 352  │
│ Nedbalová, Marie            ┆ 345  │
│ Pittnerová, Vlasta,         ┆ 342  │
│ Seifert, Jaroslav,          ┆ 340  │
│ Světlá, Karolina,           ┆ 323  │
│ Batěk, Alexandr,            ┆ 323  │
│ Novotný, Miloš              ┆ 320  │
│ Birkner-Mahler, Frieda,     ┆ 319  │
│ Scott, William,             ┆ 318  │
│ Žáček, Jiří,                ┆ 317  │
│ Šváb-Malostranský, Josef,   ┆ 315  │
│ Hrubín, František,          ┆ 313  │
│ Baar, Jindřich Šimon,       ┆ 311  │
│ Grey, Zane,                 ┆ 306  │
│ Havlíček Borovský, Karel,   ┆ 298  │
│ Christie, Agatha,           ┆ 298  │
│ Hálek, Vítězslav,           ┆ 293  │
│ David, Petr,                ┆ 292  │
│ Foglar, Jaroslav,           ┆ 289  │
│ Machar, Josef Svatopluk,    ┆ 288  │
│ Vrba, Jan,                  ┆ 287  │
│ Miler, Zdeněk,              ┆ 286  │
│ Pospíšilová, Zuzana,        ┆ 284  │
│ Beneš Třebízský, Václav,    ┆ 282  │
│ Šulc, Petr,                 ┆ 280  │
│ Brezina, Thomas,            ┆ 280  │
│ Nezval, Vítězslav,          ┆ 279  │
│ Steiner, Rudolf,            ┆ 277  │
│ Brahová, Marie              ┆ 273  │
│ Wallace, Edgar,             ┆ 272  │
│ Bezruč, Petr,               ┆ 270  │
│ Cílek, Roman,               ┆ 268  │
│ London, Jack,               ┆ 268  │
│ Gardner, Erle Stanley,      ┆ 265  │
│ Březinová, Ivona,           ┆ 264  │
│ Rowling, J. K.,             ┆ 263  │
│ Doležalová, Alena Bára      ┆ 261  │
│ Herrmann, Ignát,            ┆ 261  │
│ Hašek, Jaroslav,            ┆ 260  │
│ Nejedlý, Zdeněk,            ┆ 259  │
│ Štiková, Věra               ┆ 256  │
│ Petiška, Eduard,            ┆ 254  │
│ Majerová, Marie,            ┆ 253  │
│ Dobrovolný, Bohumil,        ┆ 251  │
│ Steel, Danielle,            ┆ 249  │
│ Balzac, Honoré de,          ┆ 248  │
│ Šplíchal, Antonín,          ┆ 245  │
│ Klostermann, Karel,         ┆ 244  │
│ Bauer, Jan,                 ┆ 242  │
│ Klínský, Petr               ┆ 241  │
│ Svoboda, F. X.,             ┆ 240  │
│ Vondruška, Vlastimil,       ┆ 235  │
│ Čtvrtek, Václav,            ┆ 232  │
│ Maruna, Jan,                ┆ 230  │
│ Čechov, Anton Pavlovič,     ┆ 225  │
│ Šťastný, Alfons Bohumil,    ┆ 225  │
│ Štíplová, Ljuba,            ┆ 224  │
│ McBain, Ed,                 ┆ 224  │
│ Sedláček, Václav,           ┆ 223  │
│ Zahradník-Brodský, Bohumil, ┆ 223  │
│ Hrabal, Bohumil,            ┆ 222  │
│ Etzold, Hans-Rüdiger,       ┆ 219  │
│ Říha, Bohumil,              ┆ 217  │
│ Deml, Jakub,                ┆ 217  │
│ Poláček, Karel,             ┆ 216  │
│ Kříženecký, Jaroslav,       ┆ 216  │
│ Čapek, Josef,               ┆ 216  │
│ Balák, Karel,               ┆ 215  │
│ Bass, Eduard,               ┆ 213  │
│ Zola, Émile,                ┆ 212  │
│ Kožík, František,           ┆ 210  │
│ Durych, Jaroslav,           ┆ 206  │
│ Sekora, Ondřej,             ┆ 206  │
│ Schelle, Karel,             ┆ 205  │
│ Vančura, Vladislav,         ┆ 204  │
│ Rolland, Romain,            ┆ 202  │
│ Suchý, Jiří,                ┆ 202  │
│ Caha, Arnošt,               ┆ 201  │
│ Čečetka, František Josef,   ┆ 201  │
│ Vymazal, František,         ┆ 200  │
│ Švandrlík, Miloslav,        ┆ 199  │
│ Sienkiewicz, Henryk,        ┆ 197  │
│ Neumann, Stanislav Kostka,  ┆ 196  │
└─────────────────────────────┴──────┘

In [9]:
df.filter(pl.col("100_a") == "Mark, William,")

shape: (0, 73)
┌────────┬─────┬──────────┬───────┬───┬───────────┬─────┬───────┬───────┐
│ leader ┆ 001 ┆ 100_ind1 ┆ 100_a ┆ … ┆ 700_g     ┆ rok ┆ stran ┆ vazba │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆   ┆ ---       ┆ --- ┆ ---   ┆ ---   │
│ str    ┆ str ┆ str      ┆ str   ┆   ┆ list[str] ┆ i64 ┆ i64   ┆ str   │
╞════════╪═════╪══════════╪═══════╪═══╪═══════════╪═════╪═══════╪═══════╡
└────────┴─────┴──────────┴───────┴───┴───────────┴─────┴───────┴───────┘

In [10]:
len(df)

728131

In [11]:
df = df.explode("100_4").filter(pl.col("100_4") == "aut")

In [12]:
len(df)

691262

In [13]:
df = df.unique(subset=["100_a","245_a"])

In [14]:
len(df)

485690

In [15]:
len(list(set(df.select(pl.col("100_7")).to_series().to_list())))

147909

In [16]:
df = df.with_columns(pl.col("100_a").map_elements(hezke_jmeno).alias("jméno"))

In [17]:
df.group_by("jméno").len().sort(by="len",descending=True).head(11)

shape: (11, 2)
┌─────────────────────────┬─────┐
│ jméno                   ┆ len │
│ ---                     ┆ --- │
│ str                     ┆ u32 │
╞═════════════════════════╪═════╡
│ Jiří Vedral             ┆ 656 │
│ Božena Němcová          ┆ 274 │
│ Alexandr Batěk          ┆ 261 │
│ Josef Šváb-Malostranský ┆ 260 │
│ Jan Amos Komenský       ┆ 258 │
│ Zuzana Pospíšilová      ┆ 249 │
│ Jan Neruda              ┆ 236 │
│ Jaroslav Vrchlický      ┆ 233 │
│ Tomáš Garrigue Masaryk  ┆ 209 │
│ Alfons Bohumil Šťastný  ┆ 205 │
│ Roman Cílek             ┆ 201 │
└─────────────────────────┴─────┘

In [18]:
hvezdy = df.group_by("100_7").len().sort(by="len",descending=True).head(10).select(pl.col("100_7")).to_series().to_list()
hvezdy

['mzk2003169026',
 'jk01083016',
 'jk01011106',
 'jk01131780',
 'jk01061444',
 'mzk2006331486',
 'jk01083209',
 'jk01151037',
 'jk01080472',
 'jk01131099']

In [19]:
import datetime

In [20]:
aut = pl.read_parquet(os.path.join("data","aut_vyber.parquet"))

In [21]:
mrtvi = aut.explode("100_7").filter(pl.col("100_7").is_in(hvezdy)).explode("046_g").with_columns(pl.col("046_g").map_elements(lambda x: int(x)).alias("umrti")).select(pl.col(["100_7","umrti"])).filter(pl.col('umrti').is_between(1800,2025)).with_columns(pl.col("umrti").map_elements(lambda x: datetime.date(year=int(x), month=1, day=1), return_dtype=pl.Date).cast(pl.Datetime))

In [22]:
do_grafu = df.filter(
    pl.col("100_7").is_in(hvezdy)
).with_columns(
    pl.col("rok").map_elements(lambda x: datetime.date(year=int(x), month=1, day=1), return_dtype=pl.Date).cast(pl.Datetime)
).join(
    df.group_by('100_7').len(), on='100_7', how='left'
).filter(
    pl.col("len") > 10
).with_columns(
    pl.col("len").map_elements(lambda x: str(x) + "×")
).join(
    mrtvi, how='left', on='100_7'
).with_columns(
    pl.concat_str([pl.col('len'), pl.col('jméno')], separator=' ').alias('jméno')
)

In [23]:
do_grafu

shape: (2_840, 76)
┌────────────────┬────────────────┬──────────┬────────────────┬───┬───────────┬────────────────┬──────┬────────────────┐
│ leader         ┆ 001            ┆ 100_ind1 ┆ 100_a          ┆ … ┆ vazba     ┆ jméno          ┆ len  ┆ umrti          │
│ ---            ┆ ---            ┆ ---      ┆ ---            ┆   ┆ ---       ┆ ---            ┆ ---  ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str            ┆   ┆ str       ┆ str            ┆ str  ┆ datetime[μs]   │
╞════════════════╪════════════════╪══════════╪════════════════╪═══╪═══════════╪════════════════╪══════╪════════════════╡
│ nam a22      a ┆ nkc20081808526 ┆ 1        ┆ Komenský, Jan  ┆ … ┆ brožovaná ┆ 258× Jan Amos  ┆ 258× ┆ null           │
│ 4500           ┆                ┆          ┆ Amos,          ┆   ┆           ┆ Komenský       ┆      ┆                │
│ nam a22     1  ┆ bknhak09095    ┆ 1        ┆ Němcová,       ┆ … ┆ null      ┆ 274× Božena    ┆ 274× ┆ 1862-01-01     │
│ 4500           ┆                ┆          ┆ Božena,        ┆   ┆           ┆ Němcová        ┆      ┆ 00:00:00       │
│ nam a22      a ┆ cpk20031191582 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos190249457   ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20091997238 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos190102095   ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆                ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20132502012 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ nkc20051636331 ┆ 1        ┆ Vrchlický,     ┆ … ┆ pevná     ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ bknmik04815    ┆ 1        ┆ Komenský, Jan  ┆ … ┆ null      ┆ 258× Jan Amos  ┆ 258× ┆ null           │
│ 4500           ┆                ┆          ┆ Amos,          ┆   ┆           ┆ Komenský       ┆      ┆                │
│ cam a22      a ┆ nkc20132480742 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos190249511   ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20142636473 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ bk194001771    ┆ 1        ┆ Komenský, Jan  ┆ … ┆ null      ┆ 258× Jan Amos  ┆ 258× ┆ null           │
│ 4500           ┆                ┆          ┆ Amos,          ┆   ┆           ┆ Komenský       ┆      ┆                │
│ nam a22      i ┆ cpk19990291179 ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ brožovaná ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22     1a ┆ bknvsv11748    ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22     1a ┆ nos190228447   ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ brožovaná ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22      i ┆ nos190254748   ┆ 1        ┆ Vrchlický,     ┆ … ┆ brožovaná ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22      a ┆ nkc20081822132 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ nkc20102106303 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ cpk20021094816 ┆ 1        ┆ Vrchlický,     ┆ … ┆ pevná     ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ nos190254852   ┆ 1        ┆ Vrchlický,     ┆ … ┆ pevná     ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ cam a22      i ┆ nkc20132501997 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ cam a22      a ┆ nkc20122394120 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos190228417   ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ null      ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22      a ┆ nkc20112189341 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ cpk20021190246 ┆ 1        ┆ Vrchlický,     ┆ … ┆ pevná     ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ nos190101940   ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆                ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ bk194804888    ┆ 1        ┆ Němcová,       ┆ … ┆ null      ┆ 274× Božena    ┆ 274× ┆ 1862-01-01     │
│ 4500           ┆                ┆          ┆ Božena,        ┆   ┆           ┆ Němcová        ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20122414905 ┆ 1        ┆ Němcová,       ┆ … ┆ pevná     ┆ 274× Božena    ┆ 274× ┆ 1862-01-01     │
│ 4500           ┆                ┆          ┆ Božena,        ┆   ┆           ┆ Němcová        ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ nos190132033   ┆ 1        ┆ Němcová,       ┆ … ┆ null      ┆ 274× Božena    ┆ 274× ┆ 1862-01-01     │
│ 4500           ┆                ┆          ┆ Božena,        ┆   ┆           ┆ Němcová        ┆      ┆ 00:00:00       │
│ nam a22      a ┆ nos190249387   ┆ 1        ┆ Šváb-Malostran ┆ … ┆ brožovaná ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22      i ┆ bknjaj18836    ┆ 1        ┆ Vrchlický,     ┆ … ┆ pevná     ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22      a ┆ cpk19970187285 ┆ 1        ┆ Němcová,       ┆ … ┆ pevná     ┆ 274× Božena    ┆ 274× ┆ 1862-01-01     │
│ 4500           ┆                ┆          ┆ Božena,        ┆   ┆           ┆ Němcová        ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ bk192605508    ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ nos190249420   ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20112189346 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ cam a22      a ┆ nkc20122430321 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos19011968a   ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆                ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ bknzdr18468    ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ null      ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22      a ┆ cpk20031282351 ┆ 1        ┆ Vrchlický,     ┆ … ┆ brožovaná ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ nos190228496   ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ brožovaná ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22      a ┆ cpk20031191579 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos190102011   ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆                ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ nam a22        ┆ np9432587      ┆ 1        ┆ Šťastný,       ┆ … ┆ brožovaná ┆ 205× Alfons    ┆ 205× ┆ 1922-01-01     │
│ 4500           ┆                ┆          ┆ Alfons         ┆   ┆           ┆ Bohumil        ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆ Bohumil,       ┆   ┆           ┆ Šťastný        ┆      ┆                │
│ nam a22     1  ┆ nos190136098   ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22      i ┆ nkc20162800534 ┆ 1        ┆ Pospíšilová,   ┆ … ┆ pevná     ┆ 249× Zuzana    ┆ 249× ┆ null           │
│ 4500           ┆                ┆          ┆ Zuzana,        ┆   ┆           ┆ Pospíšilová    ┆      ┆                │
│ nam a22      i ┆ nkc20223444662 ┆ 1        ┆ Komenský, Jan  ┆ … ┆ brožovaná ┆ 258× Jan Amos  ┆ 258× ┆ null           │
│ 4500           ┆                ┆          ┆ Amos,          ┆   ┆           ┆ Komenský       ┆      ┆                │
│ nam a22     1  ┆ nos19012206400 ┆ 1        ┆ Komenský, Jan  ┆ … ┆ null      ┆ 258× Jan Amos  ┆ 258× ┆ null           │
│ 4500           ┆ 1              ┆          ┆ Amos,          ┆   ┆           ┆ Komenský       ┆      ┆                │
│ nam a22     1  ┆ bk193000158    ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆                ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ cam a22      i ┆ nkc20142636446 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ …              ┆ …              ┆ …        ┆ …              ┆ … ┆ …         ┆ …              ┆ …    ┆ …              │
│ nam a22     1a ┆ bknvsv11690    ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ bk196202411    ┆ 1        ┆ Vrchlický,     ┆ … ┆ null      ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ nam a22      a ┆ nkc20102106314 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ nkc20132469161 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ nos190102031   ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆                ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20142636482 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22     1  ┆ bk193502413    ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ null      ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22     1  ┆ nos190249390   ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22      a ┆ nkc20122410253 ┆ 1        ┆ Pospíšilová,   ┆ … ┆ pevná     ┆ 249× Zuzana    ┆ 249× ┆ null           │
│ 4500           ┆                ┆          ┆ Zuzana,        ┆   ┆           ┆ Pospíšilová    ┆      ┆                │
│ nam a22     1  ┆ nos19010207600 ┆ 1        ┆ Batěk,         ┆ … ┆ null      ┆ 261× Alexandr  ┆ 261× ┆ 1944-01-01     │
│ 4500           ┆ 1              ┆          ┆ Alexandr,      ┆   ┆           ┆ Batěk          ┆      ┆ 00:00:00       │
│ nam a22      i ┆ nkc20162776200 ┆ 1        ┆ Pospíšilová,   ┆ … ┆ pevná     ┆ 249× Zuzana    ┆ 249× ┆ null           │
│ 4500           ┆                ┆          ┆ Zuzana,        ┆   ┆           ┆ Pospíšilová    ┆      ┆                │
│ nam a22      a ┆ cpk20011027680 ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ brožovaná ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22      a ┆ cpk20041489118 ┆ 1        ┆ Vrchlický,     ┆ … ┆ brožovaná ┆ 233× Jaroslav  ┆ 233× ┆ 1912-01-01     │
│ 4500           ┆                ┆          ┆ Jaroslav,      ┆   ┆           ┆ Vrchlický      ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20142611711 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ cam a22      a ┆ nkc20142611725 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ nkc20081816340 ┆ 1        ┆ Pospíšilová,   ┆ … ┆ pevná     ┆ 249× Zuzana    ┆ 249× ┆ null           │
│ 4500           ┆                ┆          ┆ Zuzana,        ┆   ┆           ┆ Pospíšilová    ┆      ┆                │
│ nam a22     1  ┆ bk197603175    ┆ 1        ┆ Neruda, Jan,   ┆ … ┆ null      ┆ 236× Jan       ┆ 236× ┆ 1891-01-01     │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Neruda         ┆      ┆ 00:00:00       │
│ cam a22      a ┆ nkc20142611824 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      i ┆ nkc20172953694 ┆ 1        ┆ Komenský, Jan  ┆ … ┆ null      ┆ 258× Jan Amos  ┆ 258× ┆ null           │
│ 4500           ┆                ┆          ┆ Amos,          ┆   ┆           ┆ Komenský       ┆      ┆                │
│ nam a22     1  ┆ bk193004927    ┆ 1        ┆ Šváb-Malostran ┆ … ┆ null      ┆ 260× Josef Švá ┆ 260× ┆ 1932-01-01     │
│ 4500           ┆                ┆          ┆ ský, Josef,    ┆   ┆           ┆ b-Malostranský ┆      ┆ 00:00:00       │
│ nam a22     1  ┆ bk192601538    ┆ 1        ┆ Masaryk, Tomáš ┆ … ┆ null      ┆ 209× Tomáš     ┆ 209× ┆ 1937-01-01     │
│ 4500           ┆                ┆          ┆ Garrigue,      ┆   ┆           ┆ Garrigue       ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆                ┆   ┆           ┆ Masaryk        ┆      ┆                │
│ nam a22      i ┆ nkc20162794776 ┆ 1        ┆ Pospíšilová,   ┆ … ┆ pevná     ┆ 249× Zuzana    ┆ 249× ┆ null           │
│ 4500           ┆                ┆          ┆ Zuzana,        ┆   ┆           ┆ Pospíšilová    ┆      ┆                │
│ nam a22      a ┆ cpk20031295960 ┆ 1        ┆ Šťastný,       ┆ … ┆ brožovaná ┆ 205× Alfons    ┆ 205× ┆ 1922-01-01     │
│ 4500           ┆                ┆          ┆ Alfons         ┆   ┆           ┆ Bohumil        ┆      ┆ 00:00:00       │
│                ┆                ┆          ┆ Bohumil,       ┆   ┆           ┆ Šťastný        ┆      ┆                │
│ nam a22      a ┆ nkc20112176255 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ brožovaná ┆ 655× Jiří      ┆ 655× ┆ null           │
│ 4500           ┆                ┆          ┆                ┆   ┆           ┆ Vedral         ┆      ┆                │
│ nam a22      a ┆ nkc20081807971 ┆ 1        ┆ Vedral, Jiří,  ┆ … ┆ null      ┆ 655× Jiří      ┆ 655× ┆ null           │

In [24]:
hvezdy_poradi = do_grafu.group_by('jméno').len().sort(by="len",descending=True).to_series().to_list()
hvezdy_poradi

['655× Jiří Vedral',
 '274× Božena Němcová',
 '261× Alexandr Batěk',
 '260× Josef Šváb-Malostranský',
 '258× Jan Amos Komenský',
 '249× Zuzana Pospíšilová',
 '236× Jan Neruda',
 '233× Jaroslav Vrchlický',
 '209× Tomáš Garrigue Masaryk',
 '205× Alfons Bohumil Šťastný']

In [25]:
y_encoding = {
        'field': 'jméno',
        'type': 'nominal',
        'title': None,
        'sort': hvezdy
    }

In [26]:
len(do_grafu)

2840

In [27]:
do_grafu.filter(pl.col("jméno") == "Božena Němcová").group_by("245_a").len()

shape: (0, 2)
┌───────┬─────┐
│ 245_a ┆ len │
│ ---   ┆ --- │
│ str   ┆ u32 │
╞═══════╪═════╡
└───────┴─────┘

In [28]:
import json
from src.me_to_neurazi import me_to_neurazi
with open(os.path.join('src','kredity.json'), 'r', encoding='utf-8') as kredity:
    kredity = json.loads(kredity.read())

In [29]:
base = alt.Chart(do_grafu.to_pandas(), 
                     title=alt.Title(f"{len(hvezdy)} nejvydávanějších autorů a autorek (bez reprintů)",
                                     subtitle=["Co tečka, to kniha. Černá čárka označuje rok úmrtí."]))

kulicky = base.mark_circle(size=6, opacity=1).encode( 
            x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6', tickCount=5)), 
            y=alt.Y("jméno:N", sort=hvezdy, title=None, axis=alt.Axis(orient='left', domainOpacity=0, tickColor='white', labelExpr='split(datum.label, "× ")[1]')), 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[3, 15])), 
            color=alt.Color('jméno:N', scale=alt.Scale(range=['#E09DA3']), 
                            sort=hvezdy_poradi).legend(None)) \
        .transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

kdy_umreli = base.mark_tick(
    color='#292829',  # optional: you can specify color
    thickness=1.5,
    height=9
).encode(
    x=alt.X('umrti:T', title=None),
    y=alt.Y("jméno:N", sort=hvezdy_poradi, title=None, axis=alt.Axis(orient='left', tickColor='white', labels=False)))

pocty = base.mark_circle(size=0).encode(x=alt.X('rok:T', title=None), 
    y=alt.Y('jméno:N', title=None, sort=hvezdy_poradi, axis=alt.Axis(orient="right", tickColor='white', labelExpr='split(datum.label, " ")[0]')))

zebricek = alt.layer(kulicky, pocty, kdy_umreli).properties(
    width=kredity['sirka'] * 1.2,
    autosize={'type': 'fit', 'contains': 'padding'}
).configure_view(stroke='transparent')

zebricek

alt.LayerChart(...)

In [30]:
me_to_neurazi(zebricek, kredity=kredity['default'], soubor="02_nejvydavanejsi_autorstvo")

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_nejvydavanejsi_autorstvo.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_nejvydavanejsi_autorstvo.svg" width="100%" alt="Omlouváme se, ale alternativní text se nepodařilo vygenerovat. Texty v grafu by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

In [31]:
df.filter(pl.col("100_a") == "Pospíšilová, Zuzana,").group_by('rok').len().sort(by='rok')

shape: (21, 2)
┌──────┬─────┐
│ rok  ┆ len │
│ ---  ┆ --- │
│ i64  ┆ u32 │
╞══════╪═════╡
│ 2005 ┆ 2   │
│ 2006 ┆ 7   │
│ 2007 ┆ 7   │
│ 2008 ┆ 12  │
│ 2009 ┆ 12  │
│ 2010 ┆ 19  │
│ 2011 ┆ 20  │
│ 2012 ┆ 24  │
│ 2013 ┆ 11  │
│ 2014 ┆ 22  │
│ 2015 ┆ 12  │
│ 2016 ┆ 12  │
│ 2017 ┆ 17  │
│ 2018 ┆ 16  │
│ 2019 ┆ 10  │
│ 2020 ┆ 16  │
│ 2021 ┆ 5   │
│ 2022 ┆ 9   │
│ 2023 ┆ 6   │
│ 2024 ┆ 9   │
│ 2025 ┆ 1   │
└──────┴─────┘

In [32]:
df.filter(pl.col("100_a") == "Pospíšilová, Zuzana,").group_by('rok').len().sort(by='rok').filter(pl.col("rok").is_between(2019,2024)).select(pl.col("len")).median()

shape: (1, 1)
┌─────┐
│ len │
│ --- │
│ f64 │
╞═════╡
│ 9.0 │
└─────┘

In [33]:
(308-253)/9

6.111111111111111

In [34]:
df.filter(pl.col("100_a") == "Pospíšilová, Zuzana,").select(pl.col(['245_a','rok']))

shape: (249, 2)
┌─────────────────────────────────┬──────┐
│ 245_a                           ┆ rok  │
│ ---                             ┆ ---  │
│ str                             ┆ i64  │
╞═════════════════════════════════╪══════╡
│ Pohádkové uspávanky             ┆ 2016 │
│ Ve škole                        ┆ 2007 │
│ Lesní pohádky                   ┆ 2014 │
│ Fánkova další dobrodružství     ┆ 2011 │
│ Hravá autoškola                 ┆ 2012 │
│ Školnice Valerie v podezření    ┆ 2017 │
│ O kachničce od rybníčka         ┆ 2010 │
│ Barevný svět                    ┆ 2014 │
│ Co už víme o zvířátkách         ┆ 2008 │
│ Včelka Adélka se učí protiklad… ┆ 2012 │
│ Nejkrásnější dárek              ┆ 2009 │
│ Hádankový zvěřinec              ┆ 2022 │
│ Kouzelná třída v zoo            ┆ 2019 │
│ Zlobivé pohádky                 ┆ 2014 │
│ Hádanky a úkoly pro sportovce … ┆ 2018 │
│ Baobaba a jiné příběhy          ┆ 2015 │
│ Prvňáci mají rádi legraci       ┆ 2024 │
│ První kouzlení                  ┆ 2011 │
│ O autech povídání a veselé mal… ┆ 2009 │
│ O zvířátkách povídání a veselé… ┆ 2009 │
│ Kouzelná třída mezi strašidly   ┆ 2023 │
│ Předškolák                      ┆ 2012 │
│ Sportovní pohádky               ┆ 2015 │
│ Hravá škola vaření              ┆ 2014 │
│ O kocourkovi ze dvorku          ┆ 2020 │
│ Bez práce nejsou koláče         ┆ 2014 │
│ Prázdninové pohádky             ┆ 2016 │
│ Výlet do Pekla                  ┆ 2012 │
│ Vánoční pohádky                 ┆ 2012 │
│ Už to fičí!                     ┆ 2010 │
│ Kouzelná hostina                ┆ 2011 │
│ Nezbedný mýval                  ┆ 2021 │
│ Poznáváme písmenka              ┆ 2008 │
│ Prázdniny s kouzelnou aktovkou  ┆ 2021 │
│ Anežka a kouzelná baletní suký… ┆ 2020 │
│ Veršovaný anglicko-český slovn… ┆ 2009 │
│ Krkouni, aneb, Dobrodružství n… ┆ 2010 │
│ Školní štěně                    ┆ 2020 │
│ Co to jede?                     ┆ 2014 │
│ Školní strašidlo                ┆ 2009 │
│ Hravá škola počítání            ┆ 2012 │
│ Národní pohádky                 ┆ 2017 │
│ Na statku                       ┆ 2006 │
│ Pojďte si hrát se zvířátky      ┆ 2010 │
│ O mravenečkovi z lesa           ┆ 2010 │
│ Popletená abeceda               ┆ 2007 │
│ Konec zlobení                   ┆ 2019 │
│ Štěňátko                        ┆ 2010 │
│ Starostlivá veverka             ┆ 2020 │
│ Myslí ptáci na legraci?         ┆ 2014 │
│ …                               ┆ …    │
│ Hravá škola hádání              ┆ 2014 │
│ Veselý den                      ┆ 2011 │
│ Kdo tu troubí, houká, vrčí?     ┆ 2010 │
│ Hádám, hádáš, hádáme            ┆ 2007 │
│ O ovečce z louky                ┆ 2018 │
│ Záhada školní půdy              ┆ 2015 │
│ Kouzelná třída v knihovně       ┆ 2024 │
│ Hádanky pro školáky             ┆ 2017 │
│ Kryštof a Očoun                 ┆ 2013 │
│ Do lavic!                       ┆ 2015 │
│ Kočičí pohádky                  ┆ 2018 │
│ Logohrátky                      ┆ 2018 │
│ Říkám, říkáš říkadla            ┆ 2013 │
│ Neposedné hříbátko              ┆ 2011 │
│ Obrázkové rébusy                ┆ 2012 │
│ Vyber si hru podle jména        ┆ 2008 │
│ O pejskovi ze zahrádky          ┆ 2009 │
│ Kreslíme krok za krokem         ┆ 2008 │
│ Už vím, co udělám, když--       ┆ 2008 │
│ Pojďte si hrát na lékaře        ┆ 2012 │
│ České pohádky                   ┆ 2018 │
│ Hravá škola: hříčky se slovíčk… ┆ 2014 │
│ Mlsné telátko                   ┆ 2011 │
│ Včelka Adélka se učí tvary      ┆ 2012 │
│ O šnečkovi ze zahrádky          ┆ 2018 │
│ Pohádky z parkoviště            ┆ 2013 │
│ Včelka Adélka se učí barvy      ┆ 2012 │
│ Pohádky do hajan                ┆ 2014 │
│ Školnice Valerie odhalena       ┆ 2017 │
│ Zvířátka v ZOO                  ┆ 2006 │
│ Hravá škola cvičení             ┆ 2014 │
│ V knížce vám teď ukážu, co vše… ┆ 2008 │
│ Pohádky                         ┆ 2017 │
│ Fánkova dobrodružství           ┆ 2011 │
│ Vyděšený kalous                 ┆ 2022 │
│ Máš nadání na hádání            ┆ 2011 │
│ Kdo straší školní strašidlo?    ┆ 2016 │
│ Zvířátka v lese                 ┆ 2024 │
│ Školnice Valerie se ujímá vede… ┆ 2018 │
│ Záchranářské pohádky            ┆ 2016 │
│ Kam to patří?                   ┆ 2008 │
│ Kouzelná třída o Velikonocích   ┆ 2022 │
│ Už to zvládnu!                  ┆ 2012 │
│ Prázdniny v talíři              ┆ 2016 │
│ Domeček pro šneka Palmáce       ┆ 2008 │
│ Případ: detektivové a zloději … ┆ 2016 │
│ Jak se stal kozel zahradníkem   ┆ 2011 │
│ Rozvoj dětské řeči              ┆ 2023 │
│ Naše veselá rodina              ┆ 2014 │
│ Rybářské pohádky                ┆ 2019 │
└─────────────────────────────────┴──────┘

In [35]:
vedral = df.filter(pl.col("100_a") == "Vedral, Jiří,").select(pl.col("245_a")).to_series().to_list()
vedral

['Anglicko-český slovník - projektování, organizace a ekonomika',
 'Biologie pro překladatele 2. - němčina',
 'Slovensko-český slovník jmen ptáků',
 'Čínsko-český slovník jmen rostlin',
 'Bosensko-český slovník veřejných zakázek CPV',
 'Chemie pro překladatele 2.',
 'Seversko-český přírodovědný slovník',
 'Česko-italský slovník jmen ptáků',
 'Anglicko-český slovník - ministři a ústavní činitelé',
 'Nizozemsko-český slovník veřejných zakázek CPV',
 'Maltsko-český slovník veřejných zakázek CPV',
 'Lotyšsko-český celní sazebník',
 'Anglicko-český polygrafický slovník',
 'Chorvatsko-český slovník PRODCOM',
 'Norsko-český slovník zaměstnanosti ISCO 08',
 'Česko-německý slovník kamenoprůmyslu',
 'Španělsko-český slovník ekonomických činností (NACE)',
 'Lotyšsko-český slovník ekonomických činností (NACE)',
 'Japonsko-český zemědělský slovník',
 'Dánsko-český biologický slovník',
 'Makedonsko-český celní sazebník',
 'Německo-český slovník PRODCOM na CD',
 'Slovensko-český slovník zaměstnání ISCO 08 KZAM',
 'Švédsko-český biologický slovník',
 'Čínsko-český zemědělský slovník',
 'Německo-český slovník kamenoprůmyslu',
 'Německo-český mlékárenský slovník',
 'Anglicko-český slovník slang roku 1942',
 'Španělsko-český biologický slovník',
 'Anglicko-český slovníček chlazení',
 'Portugalsko-český slovník ekonomických činností (NACE)',
 'Anglicko-český slovník jmen brouků',
 'Latinsko-český slovník názvů zvířat na CD',
 'Chemie pro překladatele - italština',
 'Španělsko-český slovník chirurgických výkonů',
 'Norsko-český slovník veřejných zakázek CPV',
 'Portugalsko-český zemědělský slovník na CD',
 'Turecko-český zemědělský slovník',
 'Anglicko-český slovníček reprografický',
 'Polsko-český zeměpisný slovník',
 'Švédsko-český slovník ICF',
 'Anglicko-český slovník sexu',
 'Anglicko-český slovníček nemoci sic prstů skotu',
 'Anglicko-český slovník - chov skotu',
 'Anglicko-český optický slovník',
 'Srbsko-český slovník ekonomických činností (NACE)',
 'Italsko-český slovník chirurgických výkonů',
 'Korejsko-český slovník jmen ptáků',
 'Slovensko-český slovník PRODCOM',
 'Česko-čínský slovník jmen rostlin',
 'Bosensko-český slovník ICF',
 'Latinsko-český slovník škůdců',
 'Litevsko-český slovník ekonomických činností (NACE)',
 'Anglicko-český slovník jmen ptáků',
 'Česko-norský slovník jmen ptáků',
 'Anglicko-český slovník rybářský',
 'Korejsko-český kosmetický slovník na CD',
 'Polsko-český slovník veřejných zakázek CPV',
 'Slovinsko-český slovník ekonomických činností (NACE)',
 'Rusko-český slovník ICF 10',
 'Anglicko-český slovník jmen obojživelníků',
 'Řecko-český katalog odpadů',
 'Chemie III.',
 'Norsko-český slovník ICF (Internasjonal klassifikasjon av funksjon, funksjonshemming og helse)',
 'Makedonsko-český slovník zaměstnání ISCO 08',
 'Francouzsko-český slovník subjaderné fyziky',
 'Gruzínsko-český slovník vnější příčiny nemocnosti a úmrtnosti',
 'Německo-český fytopatologický slovníček',
 'Italsko-český biologický slovník',
 'Německo-český církevní slovník',
 'Arabsko-český slovník vnější příčiny nemocnosti a úmrtnosti',
 'Česko-německý slovník jmen dvouděložných',
 'Česko-anglický pivovarský slovník',
 'Česko-nizozemský slovník jmen ptáků',
 'Maďarsko-český zemědělský slovník',
 'Portugalsko-český slovník třídění odpadů',
 'Japonsko-český lékařský slovník ICD 10',
 'Vietnamsko-český celní sazebník',
 'Česko-japonský slovník jmen hub',
 'Slovensko-český celní sazebník',
 'Německo-český přírodovědný slovník na CD',
 'Estonsko-český slovník ICF 10',
 'Anglicko-český pivovarský slovník',
 'Česko-německý slovník jmen motýlů',
 'Anglicko-český strojírenský slovník',
 'Anglicko-český zemědělský slovník',
 'Česko-portugalský slovník jmen ptáků',
 'Arménsko-český slovník lékařský slovník ICD 10',
 'Česko-maďarský slovník jmen ptáků',
 'Japonsko-český biologický slovník',
 'Česko-anglický slovník jmen nižších rostlin',
 'Norsko-český katalog odpadů',
 'Česko-japonský slovník jmen ptáků',
 'Anglicko-český obalový slovník',
 'Maďarsko-český slovník PRODCOM',
 'Nizozemsko-český slovník jmen ptáků',
 'Portugalsko-český slovník klasifikace zaměstnání',
 'Polsko-český slovník ICF',
 'Anglicko-český slovník měření, regulace a automatizace',
 'Slovník latinských panovníků',
 'Thajsko-český zemědělský slovník',
 'Norsko-český biologický slovník',
 'Finsko-český slovník třídění odpadů',
 'Maltsko-český celní sazebník',
 'Dánsko-český slovník třídění odpadu',
 'Německo-český slovník zemědělský',
 'Rusko-český přírodovědný slovník',
 'Rumunsko-český slovník PRODCOM na CD',
 'Japonsko-český zemědělský slovník na CD',
 'Čínsko-český celní sazebník na CD',
 'Anglicko-český slovník rakovina-ICD 3 (International Classification of Diseases for Oncology)',
 'Redoxní rovnice',
 'Bulharsko-český slovník chráněných zvířat a rostlin',
 'Portugalsko-český slovník jmen ptáků',
 'Anglicko-český slovník jmen hmyzu (kromě brouků a motýlů)',
 'Latinsko-český slovník jmen stromů a keřů',
 'Nizozemsko-český katalog odpadů',
 'Maďarsko-český slovník veřejných zakázek CPV',
 'Anglicko-český slovník jmen pavouků',
 'Italsko-český ekologický slovník',
 'Anglicko-český slovník jmen motýlů',
 'Gruzínsko-český lékařský slovník MKN10',
 'Česko-německý slovník drcení',
 'Italsko-český slovník PRODCOM',
 'Česko-čínský slovník jmen živočichů',
 'Anglicko-český lesnický slovník',
 'Slovensko-český slovník ekonomických činností NACE',
 'Japonsko-český slovník zaměstnanosti ISCO 08',
 'Česko-německý slovník jmen savců',
 'Chemie V.',
 'Bulharsko-český slovník třídění odpadů',
 'Anglicko-český slovník automatizace na CD',
 'Německo-český biologický taxonomický slovník',
 'Chemie pro překladatele - španělština',
 'Turecko-český slovník ICF',
 'Anglicko-český stavební slovník',
 'Francouzsko-český slovník PRODCOM',
 'Německo-český slovník veterinární',
 'Kosovsko-albánsko-český katalog odpadů',
 'Anglicko-český slovník školských zkratek',
 'Dánský celní sazebník',
 'Anglicko-český slovník taxonomický',
 'Latinsko-český slovník nádorů',
 'Anglicko-český slovník NACE1.1',
 'Finsko-český biologický slovník na CD',
 'Bulharsko-český katalog odpadů',
 'Česko-čínský slovník jmen ptáků',
 'Skotsko-český slovník jmen rostlin',
 'Anglicko-český slovník NHS OPCS',
 'Rumunsko-český slovník nádorů',
 'Řecko-český slovník PRODCOM',
 'Anglicko-český slovníček zpracování půdy',
 'Česko-finský biologický slovník',
 'Španělsko-český zemědělský slovník na CD',
 'Francouzsko-český katalog odpadů',
 'Francouzsko-český slovník - zaměstnanost ISCO 08',
 'Laosko-český zemědělský slovník',
 'Švédsko-český slovník veřejných zakázek (CPV)',
 'Německý celní sazebník',
 'Italsko-český zemědělský slovník na CD',
 'Tegulsko-český [i.e. Telugsko-český] zemědělský slovník na CD',
 'Francouzsko-český mlékařský slovník',
 'Česko-jugoslávský biologický slovník',
 'Anglicko-český slovník jmen obojživelníků (žáby, mloci, červoři)',
 'Německo-český slovník polygrafický',
 'Česko-slovenský slovník jmen zvířat, rostlin, hub a lišejníků',
 'Rumunsko-český slovník ICF',
 'Bosensko-český slovník PRODCOM',
 'Česko-polský slovník jmen ptáků',
 'Anglicko-český slovník zpracování informací',
 'Italsko-český katalog odpadů',
 'Německo-český slovník pivovarský',
 'Polsko-český chemický slovník',
 'Norsko-český slovník třídění odpadů',
 'Zajímavosti v názvosloví zvířat, rostlin a hub',
 'Německo-český slovník jmen ptáků',
 'Anglicko-český slovník - rostlinná výroba',
 'Polsko-český slovník jmen ptáků',
 'Arabsko-český lékařský slovník na CD',
 'Polsko-český slovník PRODCOM na CD',
 'Česko-estonský slovník jmen ptáků',
 'Norsko-český slovník jmen ptáků',
 'Biologie pro překladatele',
 'Rumunsko-český lékařský slovník',
 'Anglicko-český slovník úpravnický',
 'Španělsko-český slovník jmen mořských živočichů',
 'Italsko-český všeobecný slovník na CD',
 'Maďarsko-český slovník jmen ptáků',
 'Anglicko-český slovník - chov prasat',
 'Portugalsko-český slovník nádorů',
 'Německo-český zdravotnický slovník na CD',
 'Makedonsko-český lékařský slovník',
 'Italsko-český slovník třídění odpadů',
 'Dánsko-český slovník jmen zvířat a rostlin na CD',
 'Francouzsko-český gastronomický slovník',
 'Anglicko-český slovník - lékařské přístroje',
 'Anglický celní sazebník',
 'Chemie pro překladatele - jazyky bývalé Jugoslávie',
 'Německo-český slovník ekologický',
 'Česko-portugalský biologický slovník na CD',
 'Španělsko-český slovník PRODCOM',
 'Černohorsko-český slovník PRODCOM',
 'Čínsko-český zemědělský slovník na CD',
 'Anglicko-český biologický slovník',
 'Italsko-český celní sazebník',
 'Francouzsko-český slovník masného průmyslu',
 'Česko-anglický slovník chov prasat',
 'Francouzsko-český chemický slovník na CD',
 'Španělsko-český celní sazebník',
 'Dánsko-český lékařský slovník',
 'Anglicko-český slovník - chov drůbeže',
 'Česko-anglický slovník chov skotu',
 'Česko-holandský biologický slovník',
 'Čínsko-český biologický slovník',
 'Anglicko-český slovník umění',
 'Anglicko-český slovníček sklářský',
 'Rusko-český slovník zaměstnání ISCO 08',
 'Anglicko-český matematický slovník',
 'Německo-český slovník - barvy, laky, koroze',
 'Francouzsko-český slovník ICF 10',
 'Chemie I.',
 'Ázerbajdžánsko-český slovník CPA (Məhsul Növləri Təsnifat)',
 'Anglicko-český slovník jmen jehličnanů',
 'Finsko-český slovník ICF',
 'Anglicko-český slovník stavební mechaniky',
 'Ukrajinsko-český slovník zaměstnání ISCO 08',
 'Finsko-český slovník PRODCOM',
 'Holandsko-český biologický slovník',
 'Italsko-český slovník biologie',
 'Španělsko-český přírodovědný slovník',
 'Česko-anglický slovník titulů a hodností',
 'Italsko-český slovník veřejných zakázek (CPV)',
 'Anglicko-český čerpadlový slovník',
 'Polsko-český zemědělský slovník',
 'Italsko-český slovník ekonomických činností (NACE)',
 'Německo-český slovník jmen bezobratlých',
 'Česko-anglický slovník slangu roku 1942',
 'Anglicko-český slovník jmen dravců a sov',
 'Česko-anglický slovník biotechnologie',
 'Anglicko-český slovník jmen kaktusů',
 'Německo-český slovník zemědělských pojmů',
 'Španělsko-český slovník třídění odpadů',
 'Anglicko-český slovník - bezpečnost práce',
 'Nizozemsko-český slovník zaměstnání ISCO 08',
 'Česko-anglický slovník veterinární',
 'Anglicko-český slovník jmen lichokopytníků a sudokopytníků',
 'Turecko-český slovník zaměstnání ISCO08 Uluslararası Standart Meslek Sınıflaması',
 'Thajsko-český slovník International Standard Classification of Occupations (ISCO)',
 'Anglicko-český slovník jmen jednoděložných',
 'Řecko-český slovník CPA',
 'Dánsko-český slovník veřejných zakázek CPV',
 'Česko-thajský slovník jmen rostlin a živočichů',
 'Turecko-český slovník veřejných zakázek CPV',
 'Bulharsko-český lékárnický slovník',
 'Anglicko-český slovník vojenský',
 'Japonsko-český celní sazebník',
 'Nizozemsko-český zdravotnický slovník na CD',
 'Arabsko-český celní sazebník na CD',
 'Bulharsko-český slovník PRODCOM',
 'Čínsko-český slovník surovin tradiční čínské medicíny',
 'Turecko-český slovník ekonomických činností (NACE)',
 'Anglicko-český hudební slovník',
 'Finsko-český slovník ekonomických činností (NACE)',
 'Anglicko-český slovník automatizace',
 'Italsko-český zdravotnický slovník na CD',
 'Anglicko-český slovník jmen orchidejí',
 'Slovinsko-český slovník lékařských zákroků na CD',
 'Anglicko-český slovník strukturálních fondů',
 'Česko-anglický slovník jmen měkkýšů',
 'Česko-anglický hovorový slovník na CD',
 'Anglicko-český slovníček manipulace s materiálem',
 'Bulharsko-český slovník ekonomických činností (NACE)',
 'Francouzsko-český biologický slovník',
 'Norsko-český slovník ekonomických činností (NACE)',
 'Arabsko-český zemědělský slovník na CD',
 'Ukrajinsko-český slovník ekonomických činností (NACE)',
 'Anglicko-český slovník ICF 10 (International Classification of Functioning, Disability and Health)',
 'Anglicko-český slovník drcení',
 'Česko-anglický filmový a televizní slovník',
 'Rusko-český slovník CPA',
 'Vietnamsko-český slovník jmen rostlin a zvířat',
 'Lotyšsko-český slovník veřejných zakázek CPV',
 'Švédsko-český slovník jmen ptáků',
 'Rumunsko-český slovník veřejných zakázek CPV',
 'Gruzínsko-český slovník zaměstnání ISCO 08',
 'Rusko-český lékařský slovník na CD',
 'Německo-český slovník ICF 10',
 'Bosensko-český katalog odpadů',
 'Jugoslávsko-český biologický slovník',
 'Česko-norský biologický slovník',
 'Česko-německý slovník jmen hub',
 'Anglicko-český motoristický slovník roku 1947',
 'Vietnamsko-český lékařský slovník',
 'Černohorsko-český celní sazebník',
 'Bulharsko-český slovník zaměstnání ISCO 08',
 'Slovinsko-český lékařský slovník',
 'Francouzsko-český slovník veřejných zakázek CPV',
 'Seznam překladových dvojjazyčných slovníků s češtinou do roku 2011',
 'Rusko-český lékařský slovník',
 'Anglicko-český fonetický slovník',
 'Anglicko-český slovník jmen plazů',
 'Anglicko-český slovník lyžování',
 'Bulharsko-český lékařský slovník',
 'Finsko-český slovník jmen zvířat a rostlin na CD',
 'Slovinsko-český slovník lékařských zákroků ACHI',
 'Lotyšsko-český lékařský slovník',
 'Thajsko-český lékařský slovník',
 'Čínsko-český slovník jmen ptáků',
 'Česko-estonský biologický slovník',
 'Německo-český slovníček chlazení',
 'Albánsko-český lékařský slovník ICD 10',
 'Maďarsko-český slovník zaměstnání FEOR08',
 'Česko-německý slovník jmen rostlin na CD',
 'Rusko-český celní sazebník na CD',
 'Švédsko-český slovník ekonomických činností (NACE)',
 'Řecký celní sazebník',
 'Česko-thajský lékařský slovník',
 'Dánsko-český slovník ekonomických činností (NACE)',
 'Čínsko-český lékařský slovník',
 'Litevsko-český slovník veřejných zakázek CPV',
 'Anglicko-český stomatologický slovník',
 'Česko-japonský slovník jmen zvířat',
 'Česko-anglický logistický slovník',
 'Litevsko-český celní sazebník',
 'Kazašsko-český slovník NACE',
 'Německo-český slovník nádorů',
 'Španělsko-český slovník nádorů',
 'Česko-anglický slovník stavební',
 'Maltsko-český katalog odpadů',
 'Německo-český počítačový slovník',
 'Německo-český přírodovědný slovník',
 'Portugalsko-český zemědělský slovník',
 'Francousko-český slovník třídění odpadů',
 'Korejsko-český zemědělský slovník',
 'Bosensko-česká klasifikace zaměstnání (standardna klasifikacija zanimanja) ISCO 88',
 'Řecko-český slovník třídění odpadů',
 'Polsko-český katalog odpadů',
 'Anglicko-český logistický slovník',
 'Slovinsko-český slovník veřejných zakázek CPV',
 'Česko-německý slovník jmen jednoděložných',
 'Rumunský celní sazebník',
 'Nizozemsko-český celní sazebník',
 'Rusko-český slovník jmen ptáků',
 'Přírodovědný slovník italsko-český',
 'Lotyšsko-český slovník povolání ISCO 08',
 'Anglicko-český slovník počítačový',
 'Česko-anglický slovník jmen plazů',
 'Arménsko-český slovník (NACE)',
 'Německo-český myslivecký slovník',
 'Anglicko-český slovník PRODCOM na CD',
 'Anglicko-český slovníček mechanizace zemědělství',
 'Polsko-český biologický slovník na CD',
 'Maďarsko-český slovník ICF 10',
 'Slovinsko-český katalog odpadů',
 'Česko-anglický slovník BOZP',
 'Čínsko-český slovník jmen živočichů',
 'Italsko-český slovních i.e. slovník chlazení a ohřevu',
 'Česko-francouzský přírodovědný slovník na CD',
 'Německo-český slovník zaměstnání ISCO 08',
 'Česko-anglický slovník pekařský',
 'Slovinsko-český slovník nádorů',
 'Nizozemsko-český slovník PRODCOM',
 'Slovensko-český zemědělský slovník',
 'Estonsko-český slovník PRODCOM na CD',
 'Německo-český slovník jmen savců',
 'Česko-anglický slovník jmen hub',
 'Anglicko-český slovník třídění odpadů',
 'Makedonsko-český katalog odpadů',
 'Anglicko-český slovník alkohol a drogy',
 'Německo-český slovník chirurgických výkonů',
 'Rusko-český zemědělský slovník',
 'Arménsko-český slovník vnější příčiny nemocnosti a úmrtnosti',
 'Finsko-český slovník jmen ptáků',
 'Litevsko-český slovník PRODCOM',
 'Portugalsko-český lékařský slovník na CD',
 'Anglicko-český slovník - organizační a výpočetní technika',
 'Maďarsko-český celní sazebník',
 'Anglicko-český kosmetický slovník na CD',
 'Finsko-český slovník zaměstnání ISCO 08',
 'Francouzsko-český slovník nádorů',
 'Slovinsko-český slovník ICD 10',
 'Česko-korejský slovník jmen rostlin',
 'Medicína pro překladatele',
 'Maďarsko-český slovník ekonomických činností (NACE)',
 'Německo-český slovník třídění odpadů',
 'Estonsko-český slovník ekonomických činností (NACE)',
 'Německo-český zeměpisný slovník na CD',
 'Litevsko-český slovník třídění odpadů',
 'Slovinsko-český slovník zaměstnání ISCO 08',
 'Anglicko-český slovník jmen savců',
 'Španělsko-český slovník ICF 10',
 'Anglicko-český slovník zaměstnanost ISCO 08',
 'Česko-ruský slovník jmen ptáků',
 'Maďarsko-český katalog odpadů',
 'Francouzsko-český slovník ekonomických činností (NACE)',
 'Anglicko-český slovník jmen hlodavců',
 'Anglicko-český slovník - naftové motory',
 'Turecko-český celní sazebník na CD',
 'Anglicko-český teplárenský slovník',
 'Finsko-český slovník - lékařský slovník',
 'Anglicko-český slovník jaderné techniky a technologie',
 'Lotyšsko-český klasifikace slovník CPA',
 'Maďarsko-český slovník nádorů',
 'Chemie VI.',
 'Španělsko-český přírodovědný slovník na CD',
 'Česko-anglický slovník jmen savců',
 'Arabsko-český slovník jmen mořských tvorů',
 'Německo-český slovník - lékařské přístroje',
 'Maltsko-český slovník třídění odpadů',
 'Anglicko-český technický slovník na CD',
 'Turecko-český slovník nádorů',
 'Francouzsko-český slovník - jména hub',
 'Korejsko-český celní sazebník na CD',
 'Portugalsko-český slovník PRODCOM',
 'Polsko-český slovník třídění odpadů',
 'Anglicko-český slovník titulů a hodností',
 'Anglicko-český slovník terminologie ISAP',
 'Anglicko-český požární slovník',
 'Německo-český slovník jmen rostlin na CD',
 'Rumunsko-český slovník zaměstnání ISCO 08',
 'Slovinsko-český celní sazebník',
 'Španělsko-český slovník zaměstnání ISCO 08',
 'Německo-český slovník - rostlinná výroba',
 'Estonsko-český slovník třídění odpadů',
 'Anglicko-český mlékařský slovník',
 'Latinsko-český lékařský slovník na CD',
 'Zeměpis pro překladatele',
 'Ukrajinsko-český lékařský slovník',
 'Japonsko-český slovník jmen ptáků',
 'Anglicko-český slovník veterinární',
 'Farsí-český zemědělský slovník na CD',
 'Dánsko-český katalog odpadů',
 'Česko-finský biologický slovník na CD',
 'Litevsko-český katalog odpadů',
 'Turecko-český slovník klasifikace produkce CPA 2008',
 'Anglicko-český slovník jmen papoušků',
 'Anglicko-český psychiatrický slovník',
 'Italsko-český zemědělský slovník',
 'Ázerbajdžánsko-český lékařský slovník',
 'Anglicko-český slovník jmen bobulovitého ovoce',
 'Anglicko-český slovník jmen plazů (želvy, hadi, ještěři, krokodýli, haterie)',
 'Estonský celní sazebník',
 'Portugalsko-český slovník ICF',
 'Maltsko-český slovník ekonomických činností (NACE)',
 'Hindsko-český zemědělský slovník na CD',
 'Anglicko-český slovník z oboru masného průmyslu',
 'Přírodovědný slovník jazyků bývalé Jugoslávie',
 'Španělsko-český slovník jmen ptáků',
 'Česko-anglický slovník jmen jednoděložných',
 'Japonsko-český slovník jmen rostlin',
 'Anglicko-český hovorový slovník na CD',
 'Španělsko-český slovník vnější příčiny nemocnosti a úmrtnosti',
 'Anglicko-český slovník jmen hub',
 'Norsko-český lékařský slovník',
 'Anglicko-český gumárenský slovník',
 'Francouzsko-český slovník mořských živočichů FAO',
 'Portugalsko-český slovník - brazilská avifauna',
 'Španělsko-český zemědělský slovník',
 'Srbsko-český slovník klasifikace CPA',
 'Turecko-český katalog odpadů',
 'Česko-anglický rybářský slovník',
 'Anglicko-český slovník teologický',
 'Německo-český slovník subjaderná fyzika',
 'Česko-anglický slovník - rostlinná výroba',
 'Islandsko-český slovník vnější příčiny nemocnosti a úmrtnosti',
 'Německo-český katalog odpadů',
 'Slovensko-český katalog odpadů',
 'Islandsko-český lékařský slovník',
 'Anglicko-český slovník sexu na CD',
 'Anglicko-český slovník jmen paryb',
 'Německo-český rybářský slovník',
 'Česko-finský slovník jmen ptáků',
 'Anglicko-český divadelní slovník',
 'Latinsko-český teologický slovník',
 'Rusko-český přírodovědný slovník bez latiny',

In [36]:
[x for x in vedral if "chemie" in x.lower()]

['Chemie pro překladatele 2.',
 'Chemie pro překladatele - italština',
 'Chemie III.',
 'Chemie V.',
 'Chemie pro překladatele - španělština',
 'Chemie pro překladatele - jazyky bývalé Jugoslávie',
 'Chemie I.',
 'Chemie VI.',
 'Chemie II.',
 'Chemie IV.',
 'Chemie pro překladatele']

In [37]:
[x for x in vedral if "sex" in x.lower()]

['Anglicko-český slovník sexu', 'Anglicko-český slovník sexu na CD']

In [38]:
with open(os.path.join("data_raw","vedral.json"), "w+", encoding="utf-8") as v:
    v.write(json.dumps(vedral))