In [1]:
import os
import json
import datetime
import warnings
import polars as pl
import pandas as pd
import altair as alt

from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.hezke_jmeno import hezke_jmeno
from src.kristi_promin import kristi_promin
from src.me_to_neurazi import me_to_neurazi
from src.alt_friendly import alt_friendly

with open(os.path.join('src','kredity.json'), 'r', encoding='utf-8') as kredity:
    kredity = json.loads(kredity.read())
pl.Config(tbl_rows=100)
alt.data_transformers.disable_max_rows()
alt.themes.register('irozhlas', kristi_promin)
alt.themes.enable('irozhlas')
warnings.filterwarnings('ignore')

In [2]:
df = pl.read_parquet(os.path.join("data/cnb_sloupce","100.parquet"))
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left")
df = df.to_pandas()
df = df[df["leader"].str[6].isin(["a", "t"])]
df = df[~df["leader"].str[7].isin(["b", "i", "s", " "])]
df = df[(df["008"].str[15:17] == "xr") & (df["008"].str[35:38] == "cze")]
df = pl.from_pandas(df)
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","022.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","300.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","655.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","700.parquet")), left_on="001", right_on="001", how="left")
df = df.explode("022_a").filter(pl.col("022_a").is_null())
df = df.with_columns(pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok'))
df = df.with_columns(pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran'))
df = df.with_columns(pl.col('245_a').map_elements(bez_bordelu, return_dtype=str))
df = df.explode('245_p').with_columns(pl.col('245_p').map_elements(bez_bordelu, return_dtype=str))
print(len(df))

716789

In [3]:
aut = pl.read_parquet(os.path.join("data","aut_vyber.parquet"))

In [4]:
df = df.filter(pl.col("rok") >= 1800)

In [5]:
print(len(df))

710142

In [6]:
df = df.filter((~pl.col("245_h").str.contains("grafika")) | pl.col("245_h").is_null()).unique(subset=["008","100_a","245_a","245_p"], keep="first")

In [7]:
print(len(df))

705921

In [8]:
nechcemejetam = [
    "jn20001103401",
    "xx0008006",
    "jn19990008769",
    "jx20060515016",
    "jn19981002230",
    "jn19981001737",
    "jn19990210182",
    "jn19990001842",
    "jn19990002786",
    "jn19990004346",
    "jn20020721077",
    "jn19990210513",
    "jn19990005488",
    "jo20000080627",
    "jn19990000171",
    "jn20001005715",
    "jn19981002409",
    "jn20000810141",
    "jn19981002129",
    "jn20001103529",
    "jn20000810032",
    "jn19990001513",
    "jx20040611003",
    "jn19990005499",
    "jn19981002230",
    "jn19990001907",
    "jo2005267810",
    "jo20241218643",
    "jn20000602144",
    "jn19990005454",
    "jn19981228078",
    "xx0010566",
    "jn20010310318",
    "xx0203193",
    "jn20001227589",
    "jo2003204270",
    "xx0082647",
    "jn19990001239"
]

# df = df.filter(~pl.col("100_7").is_in(nechcemejetam))

In [9]:
df.sample(10)

shape: (10, 68)
┌──────────┬────────────────────────┬────────────────┬───────────┬───┬───────────┬───────────┬──────┬───────┐
│ 100_ind1 ┆ 100_a                  ┆ 100_7          ┆ 100_4     ┆ … ┆ 700_9     ┆ 700_g     ┆ rok  ┆ stran │
│ ---      ┆ ---                    ┆ ---            ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---   │
│ str      ┆ str                    ┆ str            ┆ list[str] ┆   ┆ list[str] ┆ list[str] ┆ i64  ┆ i64   │
╞══════════╪════════════════════════╪════════════════╪═══════════╪═══╪═══════════╪═══════════╪══════╪═══════╡
│ 1        ┆ O'Neill, Poppy         ┆ mzk20211121725 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 139   │
│ 1        ┆ Miller, Jan,           ┆ jk01081712     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1926 ┆ 195   │
│ 1        ┆ Navrátilová, Jana      ┆ jn20001103670  ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 288   │
│ 1        ┆ Wessel, Kathrin,       ┆ xx0306459      ┆ ["ill"]   ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 16    │
│ 1        ┆ Pierazzi Mitri, Monica ┆ ola2012729333  ┆ ["ill"]   ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 36    │
│ 1        ┆ Česal, Aleš,           ┆ jn20001031037  ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 2020 ┆ 284   │
│ 1        ┆ Kácl, Karel,           ┆ jk01052359     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1937 ┆ 16    │
│ 1        ┆ Dvořáček, František,   ┆ jk01030026     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1922 ┆ 96    │
│ 1        ┆ Strohal, Jakub,        ┆ jk01121485     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1861 ┆ 90    │
│ 1        ┆ Kafka, Jiří,           ┆ jk01052508     ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1946 ┆ 117   │
└──────────┴────────────────────────┴────────────────┴───────────┴───┴───────────┴───────────┴──────┴───────┘

In [10]:
df = df.drop_nulls(subset=["700_a","700_4","700_7"]).explode(["700_a","700_4","700_7"])

In [11]:
df.select(pl.col(["700_a","700_4","700_7",'245_a'])).sample(10)

shape: (10, 4)
┌─────────────────────┬───────┬────────────────┬─────────────────────────────────┐
│ 700_a               ┆ 700_4 ┆ 700_7          ┆ 245_a                           │
│ ---                 ┆ ---   ┆ ---            ┆ ---                             │
│ str                 ┆ str   ┆ str            ┆ str                             │
╞═════════════════════╪═══════╪════════════════╪═════════════════════════════════╡
│ Jerie, Alexander,   ┆ trl   ┆ ola2003209130  ┆ Pirueta                         │
│ Němcová, Edda       ┆ trl   ┆ mzk2005266569  ┆ Královský rubín                 │
│ Vyhnálek, Oldřich   ┆ trl   ┆ null           ┆ Tekuté slunce                   │
│ Havlíček, Miloslav, ┆ bjd   ┆ jo2003204261   ┆ Khanův hněv                     │
│ Marlier, Marcel,    ┆ ill   ┆ jn20000810202  ┆ Martinka se učí kreslit         │
│ Škodný, David,      ┆ ill   ┆ ola20221152275 ┆ Příběhy ze Šumavy v komiksech   │
│ Steinerová, Irena,  ┆ trl   ┆ jn20010309566  ┆ Na útěku                        │
│ Dvořák, Libor,      ┆ trl   ┆ jk01030170     ┆ Vojna a mír                     │
│ Ševicová, Martina   ┆ trl   ┆ null           ┆ Vláčky                          │
│ Hronová, Karla      ┆ aut   ┆ ola2003193823  ┆ Česko-arabský slovník ke studi… │
└─────────────────────┴───────┴────────────────┴─────────────────────────────────┘

## Autorské spolupráce

In [13]:
from itertools import combinations

In [14]:
def find_collaborations(df):
    # Filter for authors only
    authors = df.filter(pl.col('700_4') == 'aut')
    
    # Group by book title to get authors per book
    books_authors = authors.group_by('245_a').agg(pl.col('700_a').alias('authors'))
    
    # Generate author pairs and count collaborations
    collaborations = []
    for book in books_authors.iter_rows():
        if len(book[1]) > 1:  # Only consider books with multiple authors
            for pair in combinations(sorted(book[1]), 2):
                collaborations.append(pair)
    
    # Convert to dataframe and count frequencies
    collab_df = pl.DataFrame({
        'author1': [p[0] for p in collaborations],
        'author2': [p[1] for p in collaborations]
    })
    
    if len(collab_df) == 0:
        return pl.DataFrame({'author1': [], 'author2': [], 'collaboration_count': []})
    
    return (collab_df.group_by(['author1', 'author2'])
            .count()
            .sort('count', descending=True)
            .rename({'count': 'collaboration_count'}))

In [15]:
find_collaborations(df).filter(pl.col("author1") != pl.col("author2"))

shape: (222_858, 3)
┌────────────────────────┬────────────────────────────┬─────────────────────┐
│ author1                ┆ author2                    ┆ collaboration_count │
│ ---                    ┆ ---                        ┆ ---                 │
│ str                    ┆ str                        ┆ u32                 │
╞════════════════════════╪════════════════════════════╪═════════════════════╡
│ Novotný, Miloš         ┆ Novák, František           ┆ 1165                │
│ Král, Lukáš            ┆ Valenta, Tomáš             ┆ 1156                │
│ Krupka, Peter,         ┆ Nechvátalová, Jana,        ┆ 1089                │
│ Malý, Martin           ┆ Münch, Otto                ┆ 897                 │
│ Münch, Otto            ┆ Čechová, Jarmila           ┆ 826                 │
│ Frydryšková, Yvetta    ┆ Münch, Otto                ┆ 820                 │
│ Krupka, Peter,         ┆ Staudková, Hana            ┆ 792                 │
│ Nechvátalová, Jana,    ┆ Staudková, Hana            ┆ 792                 │
│ Medek, Jaroslav,       ┆ Petrůj, Svatopluk,         ┆ 761                 │
│ Frydryšková, Yvetta    ┆ Čechová, Jarmila           ┆ 730                 │
│ Hrdinová, Jarmila      ┆ Novák, František           ┆ 636                 │
│ Nechvátalová, Jana,    ┆ Tůmová, Věra               ┆ 594                 │
│ Krupka, Peter,         ┆ Tůmová, Věra               ┆ 594                 │
│ Kulík, Oldřich         ┆ Tláskal, Jaromír,          ┆ 583                 │
│ Nechvátalová, Jana,    ┆ Pišl, Milan,               ┆ 495                 │
│ Krupka, Peter,         ┆ Pišl, Milan,               ┆ 495                 │
│ Čupera, Jiří,          ┆ Ždánský, Bronislav         ┆ 468                 │
│ Nechvátalová, Jana,    ┆ Rektorys, Karel,           ┆ 462                 │
│ Krupka, Peter,         ┆ Rektorys, Karel,           ┆ 462                 │
│ Staudková, Hana        ┆ Tůmová, Věra               ┆ 438                 │
│ Jirák, Antonín,        ┆ Reitler, Antonín,          ┆ 390                 │
│ Lokay, Bohumil         ┆ Štolba, František          ┆ 387                 │
│ Pišl, Milan,           ┆ Staudková, Hana            ┆ 360                 │
│ Rektorys, Karel,       ┆ Staudková, Hana            ┆ 336                 │
│ Kubát, Jindřich        ┆ Ždánský, Bronislav         ┆ 315                 │
│ Hájek, Bohumil,        ┆ Otčenášek, Ladislav        ┆ 289                 │
│ Styblík, Vlastimil,    ┆ Šafránek, František        ┆ 272                 │
│ Doležalová, Alena Bára ┆ Novák, František           ┆ 270                 │
│ Pišl, Milan,           ┆ Tůmová, Věra               ┆ 270                 │
│ Krsička, Rudolf        ┆ Ondráček, Josef            ┆ 256                 │
│ Chromá, Danuše         ┆ Münch, Otto                ┆ 255                 │
│ Rektorys, Karel,       ┆ Tůmová, Věra               ┆ 252                 │
│ Tožička, Bohumil,      ┆ Žofková, Lidmila,          ┆ 248                 │
│ Barborová, Lenka       ┆ Münch, Otto                ┆ 245                 │
│ Nechvátalová, Jana,    ┆ Černá, Milada              ┆ 231                 │
│ Krupka, Peter,         ┆ Vřešťál, Evžen             ┆ 231                 │
│ Nechvátalová, Jana,    ┆ Vřešťál, Evžen             ┆ 231                 │
│ Krupka, Peter,         ┆ Černá, Milada              ┆ 231                 │
│ Hechtová, Marie,       ┆ Košťálová, Marie           ┆ 224                 │
│ Jelínková, Anna        ┆ Košťálová, Marie           ┆ 224                 │
│ Hrdinová, Jarmila      ┆ Novotný, Miloš             ┆ 220                 │
│ Nykl, Jaroslav,        ┆ Rottová, Milada,           ┆ 216                 │
│ Chalupa, Petr,         ┆ Hübelová, Dana,            ┆ 212                 │
│ Červený, František,    ┆ Řehořovský, Václav Karel,  ┆ 211                 │
│ Pišl, Milan,           ┆ Rektorys, Karel,           ┆ 211                 │
│ Hampl, Rudolf,         ┆ Úlehla, Josef,             ┆ 210                 │
│ Košťálová, Marie       ┆ Wildová, Růžena            ┆ 208                 │
│ Frolíková, Zora,       ┆ Košťálová, Marie           ┆ 208                 │
│ Košťálová, Marie       ┆ Malíková, Marie            ┆ 208                 │
│ Hofman, Antonín,       ┆ Košťálová, Marie           ┆ 208                 │
│ …                      ┆ …                          ┆ …                   │
│ Konopčíková, Petra     ┆ Ptáčková, Andrea           ┆ 1                   │
│ Tumajer, František     ┆ Vraštilová, Olga,          ┆ 1                   │
│ Gaisler, Jiří,         ┆ Truhlář, Jiří              ┆ 1                   │
│ Pánek, Jaroslav,       ┆ Čornej, Petr,              ┆ 1                   │
│ Brzobohatá, Kristýna,  ┆ Štaffa, Olga,              ┆ 1                   │
│ Kaván, Petr            ┆ Wagner, Jaroslav           ┆ 1                   │
│ Krejčík, Tomáš,        ┆ Lipovski, Radek,           ┆ 1                   │
│ Jančurová, Laurencia   ┆ Lyjak, Grzegorz            ┆ 1                   │
│ Benda, Karel,          ┆ Kubinyi, Jozef,            ┆ 1                   │
│ Skorunková, Radka,     ┆ Vondroušová, Jindra,       ┆ 1                   │
│ Hrdlička, Stanislav    ┆ Šťastný, Stanislav         ┆ 1                   │
│ Malý, Karel,           ┆ Zimola, David,             ┆ 1                   │
│ Eichlerová, Kateřina   ┆ Vencálek, František        ┆ 1                   │
│ Futter, Rudolf         ┆ Moraes, Cícero,            ┆ 1                   │
│ Lamačková, Zuzana      ┆ Lanžhotská, Klára          ┆ 1                   │
│ Douda, Ondřej          ┆ Kumar, Jiban               ┆ 1                   │
│ Valach, Milan,         ┆ Vilímek, Petr,             ┆ 1                   │
│ Burgr, Rudolf          ┆ Samek, Bohumil,            ┆ 1                   │
│ Fiala, Josef,          ┆ Kaluža, Jindřich,          ┆ 1                   │
│ Doležal, Stanislav,    ┆ Karpe, Robert              ┆ 1                   │
│ Gabriel, František,    ┆ Stránská-Vařeková, Zuzana, ┆ 1                   │
│ Karlík, Josef,         ┆ Kostelka, Lubomír,         ┆ 1                   │
│ Neradová, Bohuslava    ┆ Strnadová, Jana            ┆ 1                   │
│ Chládková, Jana        ┆ Pucharová, Věra            ┆ 1                   │
│ Moderc, Vilma          ┆ Čižmár, Ján,               ┆ 1                   │
│ Haeney, Mansel         ┆ Snowden, Neil              ┆ 1                   │
│ Procházka, Bohumír,    ┆ Sivová, Taťana,            ┆ 1                   │
│ Palouš, Martin,        ┆ Wagnerová, Eliška,         ┆ 1                   │
│ Hochmanová, Michaela   ┆ Ptáčková, Blanka,          ┆ 1                   │
│ Smrčka, Luboš          ┆ Strnad, Zdeněk,            ┆ 1                   │
│ Horká, Daniela         ┆ Leška, Rudolf,             ┆ 1                   │
│ Hrnčíř, Svatopluk,     ┆ Macourek, Miloš,           ┆ 1                   │
│ Roubalová, Anna,       ┆ Soukupová, Veronika        ┆ 1                   │
│ Forejt, Jindřich,      ┆ Petráček, Ota              ┆ 1                   │
│ Stejskal, David,       ┆ Stránská-Vařeková, Zuzana, ┆ 1                   │
│ Johanis, Milan         ┆ Svobodová, Eva             ┆ 1                   │
│ Slivková, Helena       ┆ Slámová, Hana              ┆ 1                   │
│ Kelbl, Jiří,           ┆ Mráz, Patrik,              ┆ 1                   │
│ Brabec, František,     ┆ Lohr, Sylvie               ┆ 1                   │
│ Kessler, Vojtěch,      ┆ Loch, Thorsten,            ┆ 1                   │
│ Juřena, Jan            ┆ Kudláček, Jan              ┆ 1                   │
│ Humlová, Danka         ┆ Martinkovič, Lukáš         ┆ 1                   │
│ Podstatová, Renata     ┆ Řehořová, Jarmila,         ┆ 1                   │
│ Chybík, Josef,         ┆ Matoušek, Jan,             ┆ 1                   │
│ Christodoulou, Iva     ┆ Heidieker, Claudia         ┆ 1                   │
│ Matušková, Marie,      ┆ Slezák, Roman              ┆ 1                   │
│ Tichá, Alena,          ┆ Říhánek, Zdeněk            ┆ 1                   │
│ Hubeňáková, Zuzana,    ┆ Klabouchová, Petra,        ┆ 1                   │
│ Bosničová, Nina        ┆ Břenková, Jana             ┆ 1                   │
│ Bartoš, Jan,           ┆ Vejpustková, Monika,       ┆ 1                   │
└────────────────────────┴────────────────────────────┴─────────────────────┘

In [16]:
df_autorske = df.filter(pl.col('700_4') == 'aut')

In [17]:
def hezkejmeno(sto):
    if not sto[-1].isalnum():
        sto = sto[:-1]
    if "," in sto:
        sto = sto.split(",")
        sto = sto[1].strip() + " " + sto[0].strip()
    return sto

In [18]:
df_autorske = df_autorske.with_columns(pl.col("100_a").map_elements(hezkejmeno).alias("jmeno1")).with_columns(pl.col("700_a").map_elements(hezkejmeno).alias("jmeno2"))

In [19]:
df_autorske

shape: (164_619, 70)
┌──────────┬───────────────────┬──────────────────┬───────────┬───┬──────┬───────┬──────────────────┬──────────────────┐
│ 100_ind1 ┆ 100_a             ┆ 100_7            ┆ 100_4     ┆ … ┆ rok  ┆ stran ┆ jmeno1           ┆ jmeno2           │
│ ---      ┆ ---               ┆ ---              ┆ ---       ┆   ┆ ---  ┆ ---   ┆ ---              ┆ ---              │
│ str      ┆ str               ┆ str              ┆ list[str] ┆   ┆ i64  ┆ i64   ┆ str              ┆ str              │
╞══════════╪═══════════════════╪══════════════════╪═══════════╪═══╪══════╪═══════╪══════════════════╪══════════════════╡
│ 1        ┆ Nesvadba, Antonín ┆ jk01083229       ┆ ["aut"]   ┆ … ┆ 1985 ┆ 115   ┆ Antonín Nesvadba ┆ Pavel Schránil   │
│ 1        ┆ Jentschura,       ┆ mzk2009517324    ┆ ["aut"]   ┆ … ┆ 2009 ┆ 238   ┆ Peter Jentschura ┆ Josef Lohkämper  │
│          ┆ Peter,            ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Abrahámová,       ┆ jn20001103578    ┆ ["aut"]   ┆ … ┆ 2000 ┆ 20    ┆ Jitka Abrahámová ┆ Ludmila          │
│          ┆ Jitka,            ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Boublíková       │
│ 1        ┆ Abrahámová,       ┆ jn20001103578    ┆ ["aut"]   ┆ … ┆ 2000 ┆ 20    ┆ Jitka Abrahámová ┆ Drahomíra        │
│          ┆ Jitka,            ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Kordíková        │
│ 0        ┆ Peyo,             ┆ xx0007049        ┆ ["ill"]   ┆ … ┆ 2003 ┆ 44    ┆ Peyo             ┆ Philippe         │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Delzenne         │
│ 0        ┆ Peyo,             ┆ xx0007049        ┆ ["ill"]   ┆ … ┆ 2003 ┆ 44    ┆ Peyo             ┆ Thierry          │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Culliford        │
│ 1        ┆ Hradečná, Marie,  ┆ jk01042624       ┆ ["aut"]   ┆ … ┆ 1996 ┆ 41    ┆ Marie Hradečná   ┆ Jiřina Novotná   │
│ 1        ┆ Hradečná, Marie,  ┆ jk01042624       ┆ ["aut"]   ┆ … ┆ 1996 ┆ 41    ┆ Marie Hradečná   ┆ Helena Hejlová   │
│ 1        ┆ Frolík, Ladislav  ┆ null             ┆ ["aut"]   ┆ … ┆ 1982 ┆ 190   ┆ Ladislav Frolík  ┆ Vlastislav       │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Hnízdo           │
│ 1        ┆ Frolík, Ladislav  ┆ null             ┆ ["aut"]   ┆ … ┆ 1982 ┆ 190   ┆ Ladislav Frolík  ┆ Milan Kymlička   │
│ 1        ┆ Hájovský, Ludvík, ┆ jk01033137       ┆ ["aut"]   ┆ … ┆ 1957 ┆ 487   ┆ Ludvík Hájovský  ┆ Bohumil          │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Kaňkovský        │
│ 1        ┆ Penhaker, Marek,  ┆ mzk2004246505    ┆ ["aut"]   ┆ … ┆ 2014 ┆ 327   ┆ Marek Penhaker   ┆ Jan Kubíček      │
│ 1        ┆ Kubásek, Václav,  ┆ jk01070259       ┆ ["aut"]   ┆ … ┆ 1946 ┆ 221   ┆ Václav Kubásek   ┆ Josef Mach       │
│ 1        ┆ Parker, Julia,    ┆ jx20031205007    ┆ ["aut"]   ┆ … ┆ 2001 ┆ 61    ┆ Julia Parker     ┆ Derek Parker     │
│ 1        ┆ Hasel, Kurt,      ┆ skuk0000545      ┆ ["aut"]   ┆ … ┆ 1994 ┆ 96    ┆ Kurt Hasel       ┆ Pavel Mareš      │
│ 1        ┆ Matoušek, Josef,  ┆ jk01080796       ┆ ["aut"]   ┆ … ┆ 1946 ┆ 79    ┆ Josef Matoušek   ┆ Zářecký          │
│ 1        ┆ Matoušek, Josef,  ┆ jk01080796       ┆ ["aut"]   ┆ … ┆ 1946 ┆ 79    ┆ Josef Matoušek   ┆ Jan Petrásek     │
│ 1        ┆ Gabriel,          ┆ jx20040615015    ┆ ["aut"]   ┆ … ┆ 1977 ┆ 290   ┆ Stanislav        ┆ Václav Skokan    │
│          ┆ Stanislav         ┆                  ┆           ┆   ┆      ┆       ┆ Gabriel          ┆                  │
│ 1        ┆ Gabriel,          ┆ jx20040615015    ┆ ["aut"]   ┆ … ┆ 1977 ┆ 290   ┆ Stanislav        ┆ Lidmila          │
│          ┆ Stanislav         ┆                  ┆           ┆   ┆      ┆       ┆ Gabriel          ┆ Gabrielová       │
│ 1        ┆ Hrubeš, Josef,    ┆ jn20000401086    ┆ ["aut"]   ┆ … ┆ 2005 ┆ 95    ┆ Josef Hrubeš     ┆ Eva Hrubešová    │
│ 1        ┆ Řešátko, Miloš,   ┆ jk01110088       ┆ ["trl"]   ┆ … ┆ 1978 ┆ 305   ┆ Miloš Řešátko    ┆ Jaroslav Vachek  │
│ 1        ┆ Řešátko, Miloš,   ┆ jk01110088       ┆ ["trl"]   ┆ … ┆ 1978 ┆ 305   ┆ Miloš Řešátko    ┆ Josef Fuka       │
│ 1        ┆ Dítě, Petr,       ┆ jn20000400604    ┆ ["aut"]   ┆ … ┆ 1992 ┆ 121   ┆ Petr Dítě        ┆ Ivo Dvořák       │
│ 1        ┆ Dítě, Petr,       ┆ jn20000400604    ┆ ["aut"]   ┆ … ┆ 1992 ┆ 121   ┆ Petr Dítě        ┆ Bořivoj Semrád   │
│ 1        ┆ Dítě, Petr,       ┆ jn20000400604    ┆ ["aut"]   ┆ … ┆ 1992 ┆ 121   ┆ Petr Dítě        ┆ Jiří Vorlíček    │
│ 1        ┆ Hausvater, Ervín  ┆ mzk2003171561    ┆ ["aut"]   ┆ … ┆ 2014 ┆ 15    ┆ Ervín Hausvater  ┆ Petr Doležal     │
│ 1        ┆ Hausvater, Ervín  ┆ mzk2003171561    ┆ ["aut"]   ┆ … ┆ 2014 ┆ 15    ┆ Ervín Hausvater  ┆ Petra Baštová    │
│ 1        ┆ Holý, Ivan        ┆ kpwa5529         ┆ ["aut"]   ┆ … ┆ 1992 ┆ 25    ┆ Ivan Holý        ┆ Jiří Rychtera    │
│ 1        ┆ Morávek,          ┆ jz8600663        ┆ ["aut"]   ┆ … ┆ 1969 ┆ 69    ┆ Jaroslav Morávek ┆ Milan Vlach      │
│          ┆ Jaroslav,         ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Kozlovská, Hana   ┆ xx0017066        ┆ ["aut"]   ┆ … ┆ 1998 ┆ 2     ┆ Hana Kozlovská   ┆ Bohuslava        │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Bohanesová       │
│ 1        ┆ Procházková,      ┆ mzk2011654425    ┆ ["aut"]   ┆ … ┆ 1974 ┆ 76    ┆ Eliška           ┆ Dana Běhůnková   │
│          ┆ Eliška            ┆                  ┆           ┆   ┆      ┆       ┆ Procházková      ┆                  │
│ 1        ┆ Šubrt, Bořivoj,   ┆ jn19990209898    ┆ ["aut"]   ┆ … ┆ 2017 ┆ 423   ┆ Bořivoj Šubrt    ┆ Milan Tuček      │
│ 1        ┆ Kos, Jiří         ┆ jx20041115024    ┆ ["aut"]   ┆ … ┆ 1970 ┆ 68    ┆ Jiří Kos         ┆ Miloš Šereda     │
│ 1        ┆ Placková, Renata  ┆ jo2017947954     ┆ ["aut"]   ┆ … ┆ 2015 ┆ 15    ┆ Renata Placková  ┆ Ivo Kropáček     │
│ 1        ┆ Kutáč, Petr       ┆ xx0004820        ┆ ["aut"]   ┆ … ┆ 2001 ┆ 122   ┆ Petr Kutáč       ┆ Taťána           │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Navrátíková      │
│ 1        ┆ Růžička, Karel,   ┆ jn20031230027    ┆ ["aut"]   ┆ … ┆ 2001 ┆ 191   ┆ Karel Růžička    ┆ Pavel Novák      │
│ 1        ┆ Kolářová, Jitka,  ┆ mzk2007424035    ┆ ["aut"]   ┆ … ┆ 2012 ┆ 54    ┆ Jitka Kolářová   ┆ Josef Velíšek    │
│ 1        ┆ Vacková, Monika,  ┆ xx0129881        ┆ ["aut"]   ┆ … ┆ 2014 ┆ 231   ┆ Monika Vacková   ┆ Jiří Vacek       │
│ 1        ┆ Tuček, Karel,     ┆ jk01140322       ┆ ["aut"]   ┆ … ┆ 1954 ┆ 79    ┆ Karel Tuček      ┆ Jiří Neustupný   │
│ 1        ┆ Cassel, Paul      ┆ xx0004663        ┆ ["aut"]   ┆ … ┆ 2003 ┆ 607   ┆ Paul Cassel      ┆ Jon Price        │
│ 1        ┆ Cassel, Paul      ┆ xx0004663        ┆ ["aut"]   ┆ … ┆ 2003 ┆ 607   ┆ Paul Cassel      ┆ Craig Eddy       │
│ 1        ┆ Beneš, Václav,    ┆ jk01011638       ┆ ["aut"]   ┆ … ┆ 1909 ┆ 36    ┆ Václav Beneš     ┆ Karel Bláha      │
│ 1        ┆ Hawking, Stephen, ┆ xx0046498        ┆ ["aut"]   ┆ … ┆ 2002 ┆ 23    ┆ Stephen Hawking  ┆ Roger Penrose    │
│ 1        ┆ Kolářský, Rudolf, ┆ ola2003162691    ┆ ["aut"]   ┆ … ┆ 1998 ┆ 173   ┆ Rudolf Kolářský  ┆ Oleg Suša        │
│ 1        ┆ Ireinová,         ┆ mzk2012735726    ┆ ["aut"]   ┆ … ┆ 2022 ┆ 103   ┆ Martina Ireinová ┆ Vít Voženílek    │
│          ┆ Martina,          ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Ireinová,         ┆ mzk2012735726    ┆ ["aut"]   ┆ … ┆ 2022 ┆ 103   ┆ Martina Ireinová ┆ Jakub Koníček    │
│          ┆ Martina,          ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Ireinová,         ┆ mzk2012735726    ┆ ["aut"]   ┆ … ┆ 2022 ┆ 103   ┆ Martina Ireinová ┆ Filip Kubeček    │
│          ┆ Martina,          ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Ireinová,         ┆ mzk2012735726    ┆ ["aut"]   ┆ … ┆ 2022 ┆ 103   ┆ Martina Ireinová ┆ Šimon Tesař      │
│          ┆ Martina,          ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Ireinová,         ┆ mzk2012735726    ┆ ["aut"]   ┆ … ┆ 2022 ┆ 103   ┆ Martina Ireinová ┆ Petra Přadková   │
│          ┆ Martina,          ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Ireinová,         ┆ mzk2012735726    ┆ ["aut"]   ┆ … ┆ 2022 ┆ 103   ┆ Martina Ireinová ┆ Alena Vondráková │
│          ┆ Martina,          ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ …        ┆ …                 ┆ …                ┆ …         ┆ … ┆ …    ┆ …     ┆ …                ┆ …                │
│ 1        ┆ Mastný, Václav    ┆ mzk2006323056    ┆ ["aut"]   ┆ … ┆ 2018 ┆ 167   ┆ Václav Mastný    ┆ Jiří Víšek       │
│ 1        ┆ Martoňák, Štefan  ┆ null             ┆ ["aut"]   ┆ … ┆ 1990 ┆ 216   ┆ Štefan Martoňák  ┆ Bernard Šeffer   │
│ 1        ┆ Martoňák, Štefan  ┆ null             ┆ ["aut"]   ┆ … ┆ 1990 ┆ 216   ┆ Štefan Martoňák  ┆ Mária Grečná     │
│ 1        ┆ Fiala, Petr,      ┆ jn19981001090    ┆ ["aut"]   ┆ … ┆ 2018 ┆ 990   ┆ Petr Fiala       ┆ Ondřej Krutílek  │
│ 1        ┆ Fiala, Petr,      ┆ jn19981001090    ┆ ["aut"]   ┆ … ┆ 2018 ┆ 990   ┆ Petr Fiala       ┆ Markéta Pitrová  │
│ 1        ┆ Chytil, Josef,    ┆ kup1994000001559 ┆ ["aut"]   ┆ … ┆ 1988 ┆ 110   ┆ Josef Chytil     ┆ Jaromír Kolařík  │
│          ┆                   ┆ 9                ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Chytil, Josef,    ┆ kup1994000001559 ┆ ["aut"]   ┆ … ┆ 1988 ┆ 110   ┆ Josef Chytil     ┆ Stanislav Vašků  │
│          ┆                   ┆ 9                ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Komárek, Jaroslav ┆ null             ┆ ["aut"]   ┆ … ┆ 1966 ┆ 181   ┆ Jaroslav Komárek ┆ Miroslav Šrámek  │
│ 1        ┆ Komárek, Jaroslav ┆ null             ┆ ["aut"]   ┆ … ┆ 1966 ┆ 181   ┆ Jaroslav Komárek ┆ Jaroslav Mrázek  │
│ 1        ┆ Kocík, Jiří       ┆ jk01060964       ┆ ["aut"]   ┆ … ┆ 1978 ┆ 253   ┆ Jiří Kocík       ┆ Ivan Fanderlík   │
│ 1        ┆ Kocík, Jiří       ┆ jk01060964       ┆ ["aut"]   ┆ … ┆ 1978 ┆ 253   ┆ Jiří Kocík       ┆ Jiří Nebřenský   │
│ 1        ┆ Doležal,          ┆ jk01022636       ┆ ["aut"]   ┆ … ┆ 1966 ┆ 96    ┆ Miloslav Doležal ┆ Karel Malý       │
│          ┆ Miloslav,         ┆                  ┆           ┆   ┆      ┆       ┆                  ┆                  │
│ 1        ┆ Burger, Adolf,    ┆ xx0036325        ┆ ["aut"]   ┆ … ┆ 1945 ┆ 83    ┆ Adolf Burger     ┆ Oskar Krejčí     │
│ 1        ┆ Burger, Adolf,    ┆ xx0036325        ┆ ["aut"]   ┆ … ┆ 1945 ┆ 83    ┆ Adolf Burger     ┆ Sylva Krejčí     │
│ 1        ┆ Vejvodová, Hana,  ┆ jn20001005591    ┆ ["aut"]   ┆ … ┆ 2006 ┆ 77    ┆ Hana Vejvodová   ┆ Jan Kopřiva      │
│ 1        ┆ Heeb, Christian,  ┆ jn20000602852    ┆ ["pht"]   ┆ … ┆ 2002 ┆ 71    ┆ Christian Heeb   ┆ Werner W. Wille  │
│ 1        ┆ Chytil, Karel,    ┆ jk01050485       ┆ ["aut"]   ┆ … ┆ 1931 ┆ 88    ┆ Karel Chytil     ┆ Antonín Friedl   │
│ 1        ┆ Šmíd, Leopold     ┆ xx0161971        ┆ ["aut"]   ┆ … ┆ 1940 ┆ 191   ┆ Leopold Šmíd     ┆ František        │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Podzimek         │
│ 1        ┆ Chovan, Jakub,    ┆ mzk20191020214   ┆ ["aut"]   ┆ … ┆ 2023 ┆ 118   ┆ Jakub Chovan     ┆ Radek Štěrba     │
│ 1        ┆ Lang, Štěpán      ┆ ola2012702043    ┆ ["aut"]   ┆ … ┆ 2015 ┆ 21    ┆ Štěpán Lang      ┆ Radovan Kopp     │
│ 1        ┆ Lang, Štěpán      ┆ ola2012702043    ┆ ["aut"]   ┆ … ┆ 2015 ┆ 21    ┆ Štěpán Lang      ┆ Jan Mareš        │
│ 1        ┆ Gerber, Magda,    ┆ hka2011622341    ┆ ["aut"]   ┆ … ┆ 2011 ┆ 223   ┆ Magda Gerber     ┆ Allison Johnson  │
│ 1        ┆ Moucha, Václav,   ┆ jk01082196       ┆ ["aut"]   ┆ … ┆ 2015 ┆ 959   ┆ Václav Moucha    ┆ Bořivoj          │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Nechvátal        │
│ 1        ┆ Moucha, Václav,   ┆ jk01082196       ┆ ["aut"]   ┆ … ┆ 2015 ┆ 959   ┆ Václav Moucha    ┆ Ladislav         │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Varadzin         │
│ 1        ┆ Ježková, Dagmar,  ┆ jo20000075751    ┆ ["ill"]   ┆ … ┆ 2002 ┆ 14    ┆ Dagmar Ježková   ┆ Marie Tetourová  │
│ 1        ┆ Rokyta, Hugo,     ┆ jk01102631       ┆ ["aut"]   ┆ … ┆ 1978 ┆ 38    ┆ Hugo Rokyta      ┆ Jiří Záloha      │
│ 1        ┆ Hájek, Viktor,    ┆ jk01033087       ┆ ["aut"]   ┆ … ┆ 1954 ┆ 30    ┆ Viktor Hájek     ┆ František Kovář  │
│ 1        ┆ Hájek, Viktor,    ┆ jk01033087       ┆ ["aut"]   ┆ … ┆ 1954 ┆ 30    ┆ Viktor Hájek     ┆ Amedeo Molnár    │
│ 1        ┆ Curtis, Brent     ┆ mzk2005312823    ┆ ["aut"]   ┆ … ┆ 2005 ┆ 170   ┆ Brent Curtis     ┆ John Eldredge    │
│ 0        ┆ Bstan-'dzin-rgya- ┆ jn19981000345    ┆ ["aut"]   ┆ … ┆ 2009 ┆ 189   ┆ Bstan-'dzin-rgya ┆ Laurens van den  │
│          ┆ mtsho,            ┆                  ┆           ┆   ┆      ┆       ┆ -mtsho           ┆ Muyzenberg       │
│ 1        ┆ Lowe, C. R.       ┆ mub2017937663    ┆ ["aut"]   ┆ … ┆ 1979 ┆ 300   ┆ C. R Lowe        ┆ P. D. G Dean     │
│ 1        ┆ Berry-Dee,        ┆ xx0027433        ┆ ["aut"]   ┆ … ┆ 2007 ┆ 232   ┆ Christopher      ┆ Steven Morris    │
│          ┆ Christopher       ┆                  ┆           ┆   ┆      ┆       ┆ Berry-Dee        ┆                  │
│ 1        ┆ Valová, Ljuba     ┆ null             ┆ ["aut"]   ┆ … ┆ 1982 ┆ 78    ┆ Ljuba Valová     ┆ Věra Hosnedlová  │
│ 1        ┆ Valová, Ljuba     ┆ null             ┆ ["aut"]   ┆ … ┆ 1982 ┆ 78    ┆ Ljuba Valová     ┆ Lea Přerostová   │
│ 1        ┆ Wünsch, Zdeněk,   ┆ jk01151816       ┆ ["aut"]   ┆ … ┆ 1977 ┆ 492   ┆ Zdeněk Wünsch    ┆ Ctibor Dostál    │
│ 1        ┆ Wünsch, Zdeněk,   ┆ jk01151816       ┆ ["aut"]   ┆ … ┆ 1977 ┆ 492   ┆ Zdeněk Wünsch    ┆ Arnošt Veselý    │
│ 1        ┆ Benešová, Hana,   ┆ pna2012702164    ┆ ["aut"]   ┆ … ┆ 2020 ┆ 40    ┆ Hana Benešová    ┆ Marie Formáčková │
│ 1        ┆ Benešová, Hana,   ┆ pna2012702164    ┆ ["aut"]   ┆ … ┆ 2020 ┆ 40    ┆ Hana Benešová    ┆ Lenka Fukalová   │
│ 1        ┆ Benešová, Hana,   ┆ pna2012702164    ┆ ["aut"]   ┆ … ┆ 2020 ┆ 40    ┆ Hana Benešová    ┆ Žofie Kanyzová   │
│ 1        ┆ Benešová, Hana,   ┆ pna2012702164    ┆ ["aut"]   ┆ … ┆ 2020 ┆ 40    ┆ Hana Benešová    ┆ Pavel Příhoda    │
│ 1        ┆ Benešová, Hana,   ┆ pna2012702164    ┆ ["aut"]   ┆ … ┆ 2020 ┆ 40    ┆ Hana Benešová    ┆ Václav Šmíd      │
│ 1        ┆ Benešová, Hana,   ┆ pna2012702164    ┆ ["aut"]   ┆ … ┆ 2020 ┆ 40    ┆ Hana Benešová    ┆ Jan Vondrák      │
│ 1        ┆ Hallinan, P. K.,  ┆ xx0190912        ┆ ["aut"]   ┆ … ┆ 2014 ┆ 24    ┆ P. K. Hallinan   ┆ Michal Černík    │
│ 1        ┆ Zelazny, Roger,   ┆ jn20010309700    ┆ ["aut"]   ┆ … ┆ 2006 ┆ 302   ┆ Roger Zelazny    ┆ Fred Saberhagen  │
│ 1        ┆ Havelková, Marie, ┆ jk01040293       ┆ ["aut"]   ┆ … ┆ 2009 ┆ 102   ┆ Marie Havelková  ┆ Jitka Slaná      │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Reissmannová     │
│ 1        ┆ Scortia, Thomas   ┆ jn20000604813    ┆ ["aut"]   ┆ … ┆ 1988 ┆ 473   ┆ Thomas N.        ┆ Frank M.         │
│          ┆ N.,               ┆                  ┆           ┆   ┆      ┆       ┆ Scortia          ┆ Robinson         │
│ 1        ┆ Bublová, Marie,   ┆ jk01020102       ┆ ["aut"]   ┆ … ┆ 1987 ┆ 250   ┆ Marie Bublová    ┆ Michail Georgiev │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Videnov          │
│ 1        ┆ Hůlka, Jaroslav,  ┆ jo20010083024    ┆ ["aut"]   ┆ … ┆ 1925 ┆ 61    ┆ Jaroslav Hůlka   ┆ Antonín Matěj    │
│          ┆                   ┆                  ┆           ┆   ┆      ┆       ┆                  ┆ Píša             │
│ 1        ┆ Novák, Jaroslav   ┆ jx20040611009    ┆ ["aut"]   ┆ … ┆ 1994 ┆ 47    ┆ Jaroslav Novák   ┆ Alice Picková    │
│ 1        ┆ Novák, Jaroslav   ┆ jx20040611009    ┆ ["aut"]   ┆ … ┆ 1994 ┆ 47    ┆ Jaroslav Novák   ┆ Zdeněk Sokol     │
└──────────┴───────────────────┴──────────────────┴───────────┴───┴──────┴───────┴──────────────────┴──────────────────┘

In [20]:
def kombajmen(jmeno1, jmeno2, radit=True, spojeni = "a"):
    try:
        jmena = [jmeno1.split(" ")[-1], jmeno2.split(" ")[-1]]
        if radit == True:
            jmena.sort()
        return f" {spojeni} ".join(jmena)
    except Exception as e:
        print(e)
        return None

In [21]:
df_autorske = df_autorske.with_columns(pl.struct('jmeno1','jmeno2').map_elements(lambda x: kombajmen(x['jmeno1'], x['jmeno2'])).alias("dvojice"))

In [22]:
df_autorske.group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (105_346, 2)
┌────────────────────────────┬───────┐
│ dvojice                    ┆ 245_a │
│ ---                        ┆ ---   │
│ str                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ David a Soukup             ┆ 126   │
│ Nedbalová a Nedbalová      ┆ 90    │
│ Engels a Marx              ┆ 60    │
│ Benešová a Kanyzová        ┆ 52    │
│ Benešová a Fukalová        ┆ 52    │
│ Benešová a Formáčková      ┆ 52    │
│ Benešová a Šmíd            ┆ 52    │
│ Benešová a Příhoda         ┆ 52    │
│ Benešová a Vondrák         ┆ 52    │
│ Mihulová a Svoboda         ┆ 43    │
│ Brožová a Vostrá           ┆ 38    │
│ Nedbalcová a Zouharová     ┆ 36    │
│ Smíšek a Smíšková          ┆ 36    │
│ Polášek a Polášková        ┆ 35    │
│ Voskovec a Werich          ┆ 35    │
│ Jirotka a Vaněk            ┆ 34    │
│ Grimm a Grimm              ┆ 33    │
│ Kučera a Stach             ┆ 33    │
│ Child a Preston            ┆ 32    │
│ David a Dobrovolná         ┆ 31    │
│ Chmelař a Šimon            ┆ 29    │
│ Goscinny a Morris          ┆ 29    │
│ Klečka a Kunz              ┆ 28    │
│ Kubálek a Kubálková        ┆ 28    │
│ Kozák a Roček              ┆ 27    │
│ Hošková a Paprčka          ┆ 26    │
│ Jirotka a Turková          ┆ 26    │
│ Lenin a Marx               ┆ 26    │
│ Bartoňová a Vítková        ┆ 25    │
│ Augusta a Honzák           ┆ 25    │
│ Pešatová a Švingalová      ┆ 25    │
│ Novák a Taterová           ┆ 25    │
│ Beran a Cílek              ┆ 25    │
│ Rusňáková a Sedláček       ┆ 25    │
│ Pecinovský a Pecinovský    ┆ 24    │
│ Bruthans a Kondrová        ┆ 24    │
│ Bruthans a Bůzek           ┆ 24    │
│ Erben a Němcová            ┆ 23    │
│ Jucovičová a Žáčková       ┆ 23    │
│ Bruthans a Kadlecová       ┆ 23    │
│ Strugackij a Strugackij    ┆ 23    │
│ Novák a Špička             ┆ 22    │
│ Beran a Jirotka            ┆ 22    │
│ Mikulenková a Molnár       ┆ 22    │
│ Čadilová a Žampachová      ┆ 21    │
│ Bratršovská a Hrdlička     ┆ 21    │
│ Novák a Nováková           ┆ 21    │
│ Matiašková a Nedbalcová    ┆ 21    │
│ Müller a Müllerová         ┆ 21    │
│ Bruthans a Kůrková         ┆ 21    │
│ …                          ┆ …     │
│ Navrátilová a Svoboda      ┆ 1     │
│ Ježek a Němec              ┆ 1     │
│ Graeber a Sedláček         ┆ 1     │
│ Jelínek a Šotola           ┆ 1     │
│ Knížák a Samec             ┆ 1     │
│ Cséfalvay a Košťálová      ┆ 1     │
│ Zahradníková a Zmožek      ┆ 1     │
│ Kostnerová a Mohn          ┆ 1     │
│ Baier a Bartošová          ┆ 1     │
│ Bellová a Gruberová        ┆ 1     │
│ Lenfeld a Wenke            ┆ 1     │
│ Stibor a Vrbenská          ┆ 1     │
│ Horovitz a Sebba           ┆ 1     │
│ Bárta a Ewais              ┆ 1     │
│ Hochman a Maxa             ┆ 1     │
│ Chládek a Klečka           ┆ 1     │
│ Adamec a Jančarová         ┆ 1     │
│ Opplová a Vlčková          ┆ 1     │
│ Sukač a Vlčková-Mejvaldová ┆ 1     │
│ Koblasa a Krejčí           ┆ 1     │
│ Bhatta a Szuczich          ┆ 1     │
│ Kopecký a Kubelka          ┆ 1     │
│ Bedford a Eberle           ┆ 1     │
│ Bičáková a Jurajda         ┆ 1     │
│ Dibuszová a Muroňová       ┆ 1     │
│ Brichtová a Jandová        ┆ 1     │
│ Burešová a Ungerman        ┆ 1     │
│ Hudec a Létal              ┆ 1     │
│ Bielik a Holeček           ┆ 1     │
│ Fišerová a Sokolová        ┆ 1     │
│ Kleibl a Koubek            ┆ 1     │
│ Bláhová a Juránek          ┆ 1     │
│ Čechová a Štícha           ┆ 1     │
│ Berka a Lánská             ┆ 1     │
│ Hanauer a Stirton          ┆ 1     │
│ Chodcová a Marková         ┆ 1     │
│ Keřkovský a Červený        ┆ 1     │
│ Vylíčilová a Światkowská   ┆ 1     │
│ Fürst a Meissner           ┆ 1     │
│ Bidmead a Sleazegrinder    ┆ 1     │
│ Dohnalová a Průša          ┆ 1     │
│ Cavelius a Wuillemet       ┆ 1     │
│ Koplík a Šrámek            ┆ 1     │
│ Bahník a Janský            ┆ 1     │
│ Addair a Zelinková         ┆ 1     │
│ Kovanič a Mučka            ┆ 1     │
│ Vymětal a Šilhánek         ┆ 1     │
│ Machek a Raclavská         ┆ 1     │
│ Bílek a Kolorenčová        ┆ 1     │
│ Bastl a Fidler             ┆ 1     │
└────────────────────────────┴───────┘

In [23]:
df_autorske.group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (111_462, 4)
┌────────────────────────────────┬───────────────┬──────────────────────────────┬───────┐
│ 100_a                          ┆ 100_7         ┆ 700_a                        ┆ 245_a │
│ ---                            ┆ ---           ┆ ---                          ┆ ---   │
│ str                            ┆ str           ┆ str                          ┆ u32   │
╞════════════════════════════════╪═══════════════╪══════════════════════════════╪═══════╡
│ David, Petr,                   ┆ xx0006786     ┆ Soukup, Vladimír,            ┆ 126   │
│ Nedbalová, Marie               ┆ jo2014816080  ┆ Nedbalová, Josefína          ┆ 87    │
│ Marx, Karl,                    ┆ jn19990005454 ┆ Engels, Friedrich,           ┆ 59    │
│ Benešová, Hana,                ┆ pna2012702164 ┆ Fukalová, Lenka              ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164 ┆ Formáčková, Marie,           ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164 ┆ Šmíd, Václav,                ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164 ┆ Kanyzová, Žofie,             ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164 ┆ Vondrák, Jan,                ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164 ┆ Příhoda, Pavel,              ┆ 52    │
│ Mihulová, Marie,               ┆ jn20001227798 ┆ Svoboda, Milan               ┆ 43    │
│ Vostrá, Markéta                ┆ js20050801018 ┆ Brožová, Marie,              ┆ 38    │
│ Smíšek, Richard,               ┆ xx0038627     ┆ Smíšková, Kateřina,          ┆ 36    │
│ Smíšek, Richard,               ┆ xx0038627     ┆ Smíšková, Zuzana             ┆ 36    │
│ Nedbalcová, Kateřina           ┆ mzk2015871497 ┆ Zouharová, Monika            ┆ 33    │
│ Voskovec, Jiří,                ┆ jk01150746    ┆ Werich, Jan,                 ┆ 32    │
│ Preston, Douglas J.,           ┆ jn20000810185 ┆ Child, Lincoln,              ┆ 32    │
│ Grimm, Jacob Ludwig Karl,      ┆ jn19981228078 ┆ Grimm, Wilhelm Karl,         ┆ 32    │
│ David, Petr,                   ┆ xx0006786     ┆ Dobrovolná, Věra,            ┆ 30    │
│ Morris,                        ┆ xx0038205     ┆ Goscinny, René,              ┆ 29    │
│ Jirotka, Antonín,              ┆ jx20040623006 ┆ Vaněk, Jan J.,               ┆ 29    │
│ Klečka, Antonín,               ┆ jk01060331    ┆ Kunz, Emil,                  ┆ 28    │
│ Chmelař, František,            ┆ jk01050240    ┆ Šimon, Jaroslav,             ┆ 27    │
│ Paprčka, Milan,                ┆ osa2014838884 ┆ Hošková, Martina,            ┆ 26    │
│ Marx, Karl,                    ┆ jn19990005454 ┆ Lenin, Vladimir Il‘jič,      ┆ 26    │
│ Stach, Jan,                    ┆ jn20010309343 ┆ Kučera, Miroslav,            ┆ 26    │
│ Kozák, Jan,                    ┆ jk01062553    ┆ Roček, Jan,                  ┆ 26    │
│ Bartoňová, Miroslava,          ┆ mzk2004148531 ┆ Vítková, Marie,              ┆ 25    │
│ Bruthans, Jiří                 ┆ jx20090211004 ┆ Kondrová, Lucie,             ┆ 24    │
│ Augusta, Pavel,                ┆ jk01010424    ┆ Honzák, František,           ┆ 24    │
│ Polášková, Jiřina,             ┆ jn20000402028 ┆ Polášek, Jaromír,            ┆ 24    │
│ Bruthans, Jiří                 ┆ jx20090211004 ┆ Bůzek, František             ┆ 24    │
│ Kubálek, Tomáš,                ┆ jo2002103223  ┆ Kubálková, Markéta,          ┆ 23    │
│ Strugackij, Arkadij Natanovič, ┆ jn19990210589 ┆ Strugackij, Boris Natanovič, ┆ 23    │
│ Taterová, Milada               ┆ jk01132074    ┆ Novák, Jiří,                 ┆ 23    │
│ Jirotka, Antonín,              ┆ jx20040623006 ┆ Turková, Zoja,               ┆ 22    │
│ Bruthans, Jiří                 ┆ jx20090211004 ┆ Kadlecová, Renáta            ┆ 22    │
│ Bruthans, Jiří                 ┆ jx20090211004 ┆ Kůrková, Iva,                ┆ 21    │
│ Nedbalcová, Kateřina           ┆ mzk2015871497 ┆ Matiašková, Katarína         ┆ 21    │
│ Patterson, James,              ┆ jo20000076489 ┆ Paetro, Maxine,              ┆ 21    │
│ Erben, Bohdan,                 ┆ jk01030523    ┆ Vilikovský, Václav,          ┆ 20    │
│ Lebeda, Tomáš,                 ┆ xx0009219     ┆ Lysek, Jakub,                ┆ 20    │
│ Bratršovská, Zdena,            ┆ jk01013004    ┆ Hrdlička, František,         ┆ 20    │
│ Miler, Zdeněk,                 ┆ jk01081695    ┆ Doskočilová, Hana,           ┆ 20    │
│ Beran, Ladislav,               ┆ jn20010310148 ┆ Cílek, Roman,                ┆ 20    │
│ Bruthans, Jiří                 ┆ jx20090211004 ┆ Skácelová, Zuzana            ┆ 19    │
│ Lebeda, Tomáš,                 ┆ xx0009219     ┆ Marek, Daniel,               ┆ 19    │
│ Bruthans, Jiří                 ┆ jx20090211004 ┆ Mlčoch, Bedřich,             ┆ 19    │
│ Lebeda, Tomáš,                 ┆ xx0009219     ┆ Zatloukal, Tomáš,            ┆ 19    │
│ Vysušil, Jiří,                 ┆ jk01151269    ┆ Macík, Karel,                ┆ 19    │
│ Lebeda, Tomáš,                 ┆ xx0009219     ┆ Zymová, Kateřina             ┆ 19    │
│ …                              ┆ …             ┆ …                            ┆ …     │
│ Čížek, Pavel,                  ┆ jk01021881    ┆ Koníček, Zdeněk,             ┆ 1     │
│ Vinciková, Hana,               ┆ jx20090128009 ┆ Nedbal, Václav               ┆ 1     │
│ Dostálová, Lucie,              ┆ osa2017940325 ┆ Havlíčková, Michaela         ┆ 1     │
│ Lukášek, Josef,                ┆ jn20010309368 ┆ Kučera, Zdeněk,              ┆ 1     │
│ Vlček, Jiří,                   ┆ jn20000402561 ┆ Skřivánek, Jaroslav          ┆ 1     │
│ Uchalová, Eva,                 ┆ xx0025365     ┆ Wittlich, Filip,             ┆ 1     │
│ Šťastná, Jana                  ┆ null          ┆ Šťastný, Miroslav            ┆ 1     │
│ Vít, Karel                     ┆ jk01142475    ┆ Kárníková, Jitka             ┆ 1     │
│ Kareš, Jiří,                   ┆ jx20051207024 ┆ Brabcová, Iva                ┆ 1     │
│ Ferencová, Yvona,              ┆ mzk2006324339 ┆ Wörgötter, Zora,             ┆ 1     │
│ Bossaert, Benjamin,            ┆ pna2017969251 ┆ Hejdušková, Barbora          ┆ 1     │
│ Kaštovský, Jan,                ┆ jx20101026010 ┆ Škaloud, Pavel,              ┆ 1     │
│ Novotný, Karel                 ┆ jk01090731    ┆ Adler, Pavel                 ┆ 1     │
│ Kusý, Miloš,                   ┆ xx0020287     ┆ Němečková, Eva               ┆ 1     │
│ Smetáčková, Irena,             ┆ ola2006329785 ┆ Hradecká, Lucie              ┆ 1     │
│ Zahradník, Petr,               ┆ mzk2005299257 ┆ Háva, Jiří,                  ┆ 1     │
│ Chia, Mantak,                  ┆ jn19990003836 ┆ Li, Juan,                    ┆ 1     │
│ Souček, Martin                 ┆ xx0139275     ┆ Masopust, Jan                ┆ 1     │
│ Galla, Karel,                  ┆ jz8600210     ┆ Doležal, Jaroslav,           ┆ 1     │
│ Hruboš, Jan,                   ┆ mzk2005312836 ┆ Pindur, David,               ┆ 1     │
│ Kaderka, Tomáš,                ┆ jo20181014501 ┆ Hřib, Honza,                 ┆ 1     │
│ Šnapka, Petr,                  ┆ jn20000402860 ┆ Dvořáček, Jaroslav,          ┆ 1     │
│ Fic, Dorota                    ┆ mzk2006331490 ┆ Benešová, Alena              ┆ 1     │
│ Willinger, Josef,              ┆ jx20041220026 ┆ Willinger, Hans              ┆ 1     │
│ Benda, Antonín                 ┆ jk01011518    ┆ Schwarz, Zdeněk,             ┆ 1     │
│ Poláková, Jarmila              ┆ null          ┆ Zvoníčková, Helena           ┆ 1     │
│ Janíček, František,            ┆ jk01050943    ┆ Žďánský, Josef               ┆ 1     │
│ Rukovanský, Imrich,            ┆ jk01103045    ┆ Sklenář, Pavel               ┆ 1     │
│ Jan, Libor,                    ┆ jn20000401178 ┆ Samek, Bohumil,              ┆ 1     │
│ Evarts, Hal G.                 ┆ xx0037317     ┆ Heřman, Zdeněk,              ┆ 1     │
│ Kuncipál, Josef                ┆ jk01070882    ┆ Pytlík, František            ┆ 1     │
│ Vlček, Miroslav,               ┆ mzk2004261271 ┆ Kunca, Tomáš,                ┆ 1     │
│ Staněk, Josef                  ┆ jx20040624028 ┆ Drbal, Karel,                ┆ 1     │
│ Boháček, Jiří,                 ┆ mzk2004250840 ┆ Chrobák, Luděk,              ┆ 1     │
│ Pluhařová, Ilona,              ┆ mzk2007400965 ┆ Velešovský, Pavel,           ┆ 1     │
│ Bulliet, Richard W.,           ┆ xx0218876     ┆ Johnson, Lyman L.,           ┆ 1     │
│ Klemš, Marek,                  ┆ mzk2007411211 ┆ Fišerová, Helena             ┆ 1     │
│ Kalendovský, Jan,              ┆ jk01052640    ┆ Strnad, Julius,              ┆ 1     │
│ Jursík, Miroslav,              ┆ xx0029341     ┆ Šuk, Jaroslav                ┆ 1     │
│ Šuvarská, Eva,                 ┆ mzk2012709467 ┆ Juklová, Petra               ┆ 1     │
│ Novák, Jiří,                   ┆ ola2004235393 ┆ Mauer, Oldřich,              ┆ 1     │
│ Štěrba, J. H.                  ┆ null          ┆ Beneš Buchlovan, Bedřich,    ┆ 1     │
│ Kukaň, Vlastimil,              ┆ ntka173132    ┆ Drahorád, Michal,            ┆ 1     │
│ Fišer, Marcel,                 ┆ jn20010601396 ┆ Voda, David,                 ┆ 1     │
│ Janík, Josef,                  ┆ jk01050956    ┆ Jungmann, Josef,             ┆ 1     │
│ Beneš, Bohuslav,               ┆ js20030728001 ┆ Hrníčko, Václav,             ┆ 1     │
│ Kabíček, Pavel                 ┆ xx0078387     ┆ Csémy, Ladislav,             ┆ 1     │
│ Perušičová, Jindra,            ┆ jn19990216137 ┆ Mohr, Pavel,                 ┆ 1     │
│ Srp, Karel,                    ┆ jn20001103780 ┆ Brabcová, Jana A.,           ┆ 1     │
│ Markes, Petr,                  ┆ jk01080251    ┆ Pazourek, Václav,            ┆ 1     │
└────────────────────────────────┴───────────────┴──────────────────────────────┴───────┘

In [24]:
df.filter(pl.col("700_a") == "Soukup, Vladimír,").filter(pl.col("100_a") == "David, Petr,")

shape: (197, 68)
┌──────────┬──────────────┬───────────┬───────────────────────┬───┬───────────┬───────────┬──────┬───────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7     ┆ 100_4                 ┆ … ┆ 700_9     ┆ 700_g     ┆ rok  ┆ stran │
│ ---      ┆ ---          ┆ ---       ┆ ---                   ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---   │
│ str      ┆ str          ┆ str       ┆ list[str]             ┆   ┆ list[str] ┆ list[str] ┆ i64  ┆ i64   │
╞══════════╪══════════════╪═══════════╪═══════════════════════╪═══╪═══════════╪═══════════╪══════╪═══════╡
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 182   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 191   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 4     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 368   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 152   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 363   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2018 ┆ 552   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 129   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"]        ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 208   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 247   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 190   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 215   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2024 ┆ 263   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 56    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 224   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 223   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 111   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 392   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 210   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1994 ┆ 132   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 239   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 210   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 1     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 127   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"]        ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 247   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 175   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 138   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 168   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 159   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 384   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 288   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 113   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 199   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 1     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 318   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 117   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 191   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 335   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 167   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 392   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 167   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 133   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 318   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 264   │
│ …        ┆ …            ┆ …         ┆ …                     ┆ … ┆ …         ┆ …         ┆ …    ┆ …     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 157   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 143   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2013 ┆ 400   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 46    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 147   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2024 ┆ 231   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 122   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 384   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 1     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 176   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"]        ┆ … ┆ null      ┆ null      ┆ 2020 ┆ 424   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 208   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 150   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 764   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 367   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 161   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 336   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 101   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 190   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 316   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 119   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 376   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 131   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 142   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 432   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 190   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 254   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 170   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1996 ┆ 160   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 151   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 328   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 184   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2011 ┆ 416   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 143   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 95    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 159   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2011 ┆ 380   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 416   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 437   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pbl", "pht"] ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 230   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 143   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 119   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 79    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]               ┆ … ┆ null      ┆ null      ┆ 2024 ┆ 365   │
└──────────┴──────────────┴───────────┴───────────────────────┴───┴───────────┴───────────┴──────┴───────┘

## Ilustrátorstvo

In [26]:
df_ill = df.filter(pl.col('700_4') == 'ill')

In [27]:
df_ill = df_ill.with_columns(pl.col("100_a").map_elements(hezkejmeno).alias("jmeno1")).with_columns(pl.col("700_a").map_elements(hezkejmeno).alias("jmeno2"))

In [28]:
df_ill = df_ill.with_columns(pl.struct('jmeno1','jmeno2').map_elements(lambda x: kombajmen(x['jmeno1'], x['jmeno2'], radit=False, spojeni="&")).alias("dvojice"))

In [29]:
df_ill.filter(~pl.col("100_7").is_in(nechcemejetam)).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (32_296, 2)
┌─────────────────────────────┬───────┐
│ dvojice                     ┆ 245_a │
│ ---                         ┆ ---   │
│ str                         ┆ u32   │
╞═════════════════════════════╪═══════╡
│ Štíplová & Němeček          ┆ 108   │
│ Nedbalová & Popprová        ┆ 87    │
│ Nedbalová & Poppr           ┆ 68    │
│ Bass & Kratochvíl           ┆ 67    │
│ Švandrlík & Winter-Neprakta ┆ 64    │
│ Čapek & Čapek               ┆ 33    │
│ Pospíšilová & Trsťan        ┆ 31    │
│ Hašek & Lada                ┆ 30    │
│ Rosecká & Růžička           ┆ 28    │
│ Škodová & Kubašta           ┆ 25    │
│ Pospíšilová & Vopičková     ┆ 25    │
│ Čtvrtek & Pilař             ┆ 24    │
│ Foglar & Čermák             ┆ 24    │
│ Tetourová & Plicková        ┆ 23    │
│ Piroddi & Baruzzi           ┆ 23    │
│ Macourek & Born             ┆ 22    │
│ Drijverová & Otčenášek      ┆ 21    │
│ Válková & Kopl              ┆ 21    │
│ Bednářová & Šmarda          ┆ 21    │
│ Žáček & Born                ┆ 21    │
│ Šavlíková & Roverová        ┆ 20    │
│ Steklač & Born              ┆ 19    │
│ Grey & Hora                 ┆ 19    │
│ Kratochvíl & Vydrová        ┆ 19    │
│ Walliams & Ross             ┆ 19    │
│ Stará & Starý               ┆ 19    │
│ Pospíšilová & Vydrová       ┆ 19    │
│ Webb & Williams             ┆ 19    │
│ Felix & Hísek               ┆ 18    │
│ Hrušková & Turek            ┆ 18    │
│ Hrubín & Trnka              ┆ 18    │
│ Potužníková & Jenčíková     ┆ 18    │
│ Wenig & Wenig               ┆ 18    │
│ Dahl & Blake                ┆ 18    │
│ Brandt & Lefin              ┆ 17    │
│ Pospíšilová & Sušina        ┆ 17    │
│ Štíplová & Vančurová        ┆ 17    │
│ Voleská & Scheiner          ┆ 17    │
│ Lebeda & Študlarová         ┆ 17    │
│ Schovancová & Schovanec     ┆ 17    │
│ Brand & Wowk                ┆ 17    │
│ Smolíková & Smolík          ┆ 16    │
│ Osborne & Knipping          ┆ 16    │
│ Rožnovská & Vydrová         ┆ 16    │
│ Simon & Ross                ┆ 16    │
│ Běhounek & Junek            ┆ 16    │
│ Johns & Barč                ┆ 16    │
│ Ciprová & Němcová           ┆ 16    │
│ Beigel & Goff               ┆ 16    │
│ Grey & Ulč                  ┆ 15    │
│ …                           ┆ …     │
│ Chaykin & Brereton          ┆ 1     │
│ Lawrence & Axmann           ┆ 1     │
│ Jahoda & Adámek             ┆ 1     │
│ Bernardinová & Houra        ┆ 1     │
│ Dostál & Hanvald            ┆ 1     │
│ Hainer & Štorkán            ┆ 1     │
│ Moralesová & Bagdasarov     ┆ 1     │
│ Bezděčka & Kremláček        ┆ 1     │
│ Hines & Hruška              ┆ 1     │
│ Janíčková & Pospíšil        ┆ 1     │
│ Mácha & Tesař               ┆ 1     │
│ Rayle & Vysekal             ┆ 1     │
│ Redl & Fišerová             ┆ 1     │
│ Vyskočil & Podhajský        ┆ 1     │
│ Janyš & Raftl               ┆ 1     │
│ Kutálková & Kutálek         ┆ 1     │
│ Moore & Wears               ┆ 1     │
│ Erben & Jelínek             ┆ 1     │
│ Balejová & Korčáková        ┆ 1     │
│ Dejmek & Černý              ┆ 1     │
│ Cendrars & Skálová          ┆ 1     │
│ Hulpach & Toman             ┆ 1     │
│ Chainani & RaidesArt        ┆ 1     │
│ Dahlke & Tust               ┆ 1     │
│ Chamblain & Neyret          ┆ 1     │
│ Linc & Svoboda              ┆ 1     │
│ Jugla & Mercier             ┆ 1     │
│ Václavík & Křeček           ┆ 1     │
│ Šmejkal & Vlach             ┆ 1     │
│ Opluštil & Študentová       ┆ 1     │
│ Schwarz & Vlachová          ┆ 1     │
│ Pernická & Autratová        ┆ 1     │
│ Gillen & Yu                 ┆ 1     │
│ Kosina & Sehnalová          ┆ 1     │
│ Bizien & Graffet            ┆ 1     │
│ Brězan & Halámková          ┆ 1     │
│ Formáčková & Černý          ┆ 1     │
│ Lipanský & Konůpek          ┆ 1     │
│ Lukeš & Box                 ┆ 1     │
│ Zvelebilová & Hovorková     ┆ 1     │
│ Wiącek & Wierzchowska       ┆ 1     │
│ Dufresne & Majzner          ┆ 1     │
│ Saimura & Takahashi         ┆ 1     │
│ Adámek & Hájek              ┆ 1     │
│ Hawking & Miller            ┆ 1     │
│ David & Lark                ┆ 1     │
│ Zeuch & Reimann             ┆ 1     │
│ Michałowska & Vimr          ┆ 1     │
│ Burdová & Laštuvková        ┆ 1     │
│ Lebeda & Vašák              ┆ 1     │
└─────────────────────────────┴───────┘

In [30]:
koliktohobylo = df_ill.unique(subset=['100_7','245_a']).filter(~pl.col("100_7").is_in(nechcemejetam)).filter(pl.col("stran") > 30).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

In [31]:
dvojice_aut_ill = df_ill.unique(subset=['100_7','245_a']).filter(~pl.col("100_7").is_in(nechcemejetam)).filter(pl.col("stran") > 30).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True).head(5).select(pl.col("dvojice")).to_series().to_list()
dvojice_aut_ill

['Štíplová & Němeček',
 'Švandrlík & Winter-Neprakta',
 'Pospíšilová & Trsťan',
 'Hašek & Lada',
 'Rosecká & Růžička']

In [32]:
df_ill.filter(~pl.col("100_7").is_in(nechcemejetam)).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (32_296, 2)
┌─────────────────────────────┬───────┐
│ dvojice                     ┆ 245_a │
│ ---                         ┆ ---   │
│ str                         ┆ u32   │
╞═════════════════════════════╪═══════╡
│ Štíplová & Němeček          ┆ 108   │
│ Nedbalová & Popprová        ┆ 87    │
│ Nedbalová & Poppr           ┆ 68    │
│ Bass & Kratochvíl           ┆ 67    │
│ Švandrlík & Winter-Neprakta ┆ 64    │
│ Čapek & Čapek               ┆ 33    │
│ Pospíšilová & Trsťan        ┆ 31    │
│ Hašek & Lada                ┆ 30    │
│ Rosecká & Růžička           ┆ 28    │
│ Pospíšilová & Vopičková     ┆ 25    │
│ Škodová & Kubašta           ┆ 25    │
│ Foglar & Čermák             ┆ 24    │
│ Čtvrtek & Pilař             ┆ 24    │
│ Piroddi & Baruzzi           ┆ 23    │
│ Tetourová & Plicková        ┆ 23    │
│ Macourek & Born             ┆ 22    │
│ Drijverová & Otčenášek      ┆ 21    │
│ Válková & Kopl              ┆ 21    │
│ Žáček & Born                ┆ 21    │
│ Bednářová & Šmarda          ┆ 21    │
│ Šavlíková & Roverová        ┆ 20    │
│ Pospíšilová & Vydrová       ┆ 19    │
│ Steklač & Born              ┆ 19    │
│ Walliams & Ross             ┆ 19    │
│ Grey & Hora                 ┆ 19    │
│ Stará & Starý               ┆ 19    │
│ Kratochvíl & Vydrová        ┆ 19    │
│ Webb & Williams             ┆ 19    │
│ Hrušková & Turek            ┆ 18    │
│ Wenig & Wenig               ┆ 18    │
│ Felix & Hísek               ┆ 18    │
│ Hrubín & Trnka              ┆ 18    │
│ Potužníková & Jenčíková     ┆ 18    │
│ Dahl & Blake                ┆ 18    │
│ Pospíšilová & Sušina        ┆ 17    │
│ Voleská & Scheiner          ┆ 17    │
│ Brandt & Lefin              ┆ 17    │
│ Štíplová & Vančurová        ┆ 17    │
│ Brand & Wowk                ┆ 17    │
│ Lebeda & Študlarová         ┆ 17    │
│ Schovancová & Schovanec     ┆ 17    │
│ Osborne & Knipping          ┆ 16    │
│ Rožnovská & Vydrová         ┆ 16    │
│ Beigel & Goff               ┆ 16    │
│ Ciprová & Němcová           ┆ 16    │
│ Johns & Barč                ┆ 16    │
│ Simon & Ross                ┆ 16    │
│ Smolíková & Smolík          ┆ 16    │
│ Běhounek & Junek            ┆ 16    │
│ Eislerová & Šplíchal        ┆ 15    │
│ …                           ┆ …     │
│ Koudelka & Slaba            ┆ 1     │
│ Johns & Albert              ┆ 1     │
│ Hradilová & Němec           ┆ 1     │
│ Rensmann & Penava           ┆ 1     │
│ Turnbull & Noon             ┆ 1     │
│ Košutková & Vlková          ┆ 1     │
│ Banderas & Ranucci          ┆ 1     │
│ Lacey & Antonini            ┆ 1     │
│ David & Matta               ┆ 1     │
│ Čech & Tichá                ┆ 1     │
│ Kovář & Papeš               ┆ 1     │
│ Mašková & Patřičný          ┆ 1     │
│ Ostrovskij & Pachomov       ┆ 1     │
│ Šmejkal & Šechtl            ┆ 1     │
│ Neville & Born              ┆ 1     │
│ Hořejší & Průchová          ┆ 1     │
│ Müller & Pravdová           ┆ 1     │
│ Nevyhoštěná & Václavíková   ┆ 1     │
│ Kašpar & Hořánek            ┆ 1     │
│ Černá & Klimeš              ┆ 1     │
│ Vysocký & Brdlík            ┆ 1     │
│ Procházka & Blažejová       ┆ 1     │
│ Dawkins & Lenzová           ┆ 1     │
│ Hewat & Kim                 ┆ 1     │
│ Sloan & George              ┆ 1     │
│ Součková & Lhoták           ┆ 1     │
│ Richter & Vojtek            ┆ 1     │
│ Rush & Palmer               ┆ 1     │
│ Marshall & Thorpeová        ┆ 1     │
│ Müller & Bohnstedt          ┆ 1     │
│ Neff & Lada                 ┆ 1     │
│ Zakopal & Winter-Neprakta   ┆ 1     │
│ Bílý & Mocek                ┆ 1     │
│ Troiano & Massari           ┆ 1     │
│ Ibbotson & Kyšková          ┆ 1     │
│ Stoker & Humphries          ┆ 1     │
│ Black & Cai                 ┆ 1     │
│ Hulpach & Kolíbal           ┆ 1     │
│ Russell & Scott             ┆ 1     │
│ Vincourová & Nováková       ┆ 1     │
│ Rožnovská & Starý           ┆ 1     │
│ Hruška & Novák              ┆ 1     │
│ Šmíd & Lescoat              ┆ 1     │
│ Sedláček & Brunner          ┆ 1     │
│ Sel'vinskij & Svoboda       ┆ 1     │
│ Simonson & Mhan             ┆ 1     │
│ Brumovská & Joudová         ┆ 1     │
│ Stocks & Jones              ┆ 1     │
│ Hanozet & Mabire            ┆ 1     │
│ Schejbalová & Šnajderová    ┆ 1     │
└─────────────────────────────┴───────┘

In [33]:
import datetime

In [34]:
df_ill.filter(pl.col("dvojice") == "Pospíšilová & Trsťan")

shape: (37, 71)
┌──────────┬──────────────┬───────────────┬───────────┬───┬───────┬─────────────┬─────────────────┬───────────────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7         ┆ 100_4     ┆ … ┆ stran ┆ jmeno1      ┆ jmeno2          ┆ dvojice       │
│ ---      ┆ ---          ┆ ---           ┆ ---       ┆   ┆ ---   ┆ ---         ┆ ---             ┆ ---           │
│ str      ┆ str          ┆ str           ┆ list[str] ┆   ┆ i64   ┆ str         ┆ str             ┆ str           │
╞══════════╪══════════════╪═══════════════╪═══════════╪═══╪═══════╪═════════════╪═════════════════╪═══════════════╡
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 104   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 112   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 152   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 166   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 64    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 1     ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 88    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 58    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 116   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 78    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 70    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 62    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 131   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 119   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
└──────────┴──────────────┴───────────────┴───────────┴───┴───────┴─────────────┴─────────────────┴───────────────┘

In [35]:
do_grafu = df_ill.filter(
    pl.col("dvojice").is_in(dvojice_aut_ill)
).unique(
    subset=['245_a']
).join(
    koliktohobylo, how="left", on="dvojice"
).with_columns(
    pl.col("245_a_right").map_elements(lambda x: str(x) + "×")
).with_columns(
    pl.concat_str([pl.col('245_a_right'), pl.col('dvojice')], separator=' ').alias('dvojice')
)

In [36]:
dvojice_sort = do_grafu.group_by("dvojice").len().sort(by="len",descending=True).select(pl.col("dvojice")).to_series().to_list()
dvojice_sort

['105× Štíplová & Němeček',
 '62× Švandrlík & Winter-Neprakta',
 '30× Pospíšilová & Trsťan',
 '29× Hašek & Lada',
 '27× Rosecká & Růžička']

In [37]:
df_ill.filter(pl.col("dvojice") == "Štíplová & Němeček")

shape: (114, 71)
┌──────────┬───────────┬────────────┬───────────┬───┬───────┬────────────────┬────────────────────┬────────────────────┐
│ 100_ind1 ┆ 100_a     ┆ 100_7      ┆ 100_4     ┆ … ┆ stran ┆ jmeno1         ┆ jmeno2             ┆ dvojice            │
│ ---      ┆ ---       ┆ ---        ┆ ---       ┆   ┆ ---   ┆ ---            ┆ ---                ┆ ---                │
│ str      ┆ str       ┆ str        ┆ list[str] ┆   ┆ i64   ┆ str            ┆ str                ┆ str                │
╞══════════╪═══════════╪════════════╪═══════════╪═══╪═══════╪════════════════╪════════════════════╪════════════════════╡
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 90    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 192   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 64    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 174   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 35    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 162   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 163   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 64    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 79    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 11    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 47    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 143   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 48    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 50    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 143   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 178   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ …        ┆ …         ┆ …          ┆ …         ┆ … ┆ …     ┆ …              ┆ …                  ┆ …                  │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 143   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 96    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 163   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 160   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 11    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 66    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │

In [38]:
df_ill.filter(pl.col("dvojice") == "Pospíšilová & Trsťan")

shape: (37, 71)
┌──────────┬──────────────┬───────────────┬───────────┬───┬───────┬─────────────┬─────────────────┬───────────────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7         ┆ 100_4     ┆ … ┆ stran ┆ jmeno1      ┆ jmeno2          ┆ dvojice       │
│ ---      ┆ ---          ┆ ---           ┆ ---       ┆   ┆ ---   ┆ ---         ┆ ---             ┆ ---           │
│ str      ┆ str          ┆ str           ┆ list[str] ┆   ┆ i64   ┆ str         ┆ str             ┆ str           │
╞══════════╪══════════════╪═══════════════╪═══════════╪═══╪═══════╪═════════════╪═════════════════╪═══════════════╡
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 104   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 112   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 152   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 166   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 64    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 1     ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 88    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 58    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 116   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 78    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 70    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 62    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 131   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 119   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
└──────────┴──────────────┴───────────────┴───────────┴───┴───────┴─────────────┴─────────────────┴───────────────┘

In [39]:
dvojice_sort

['105× Štíplová & Němeček',
 '62× Švandrlík & Winter-Neprakta',
 '30× Pospíšilová & Trsťan',
 '29× Hašek & Lada',
 '27× Rosecká & Růžička']

In [140]:
base_ill = alt.Chart(
    alt_friendly(do_grafu), 
    title=alt.TitleParams(f"{len(dvojice_aut_ill)} nejčastějších dvojic autor/ka-ilustrátor/ka (bez reprintů)")).mark_circle(size=7, filled=True) 

tecky_ill = base_ill.encode(
            x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6')), 
            y=alt.Y("dvojice:N", sort=dvojice_sort, title=None, axis=alt.Axis(orient='left', domainOpacity=0, tickColor='white', labelExpr='split(datum.label, "× ")[1]')), 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[3, 15])), 
            color=alt.Color('dvojice:N', scale=alt.Scale(range=['#E09DA3']), 
                            sort=dvojice_sort).legend(None)) \
        .transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

pocty_ill = base_ill.mark_text().encode(x=alt.X('rok:T', title=None), 
    y=alt.Y('dvojice:N', title=None, sort=dvojice_sort, axis=alt.Axis(orient="right", tickColor='white', labelExpr='split(datum.label, " ")[0]')))

zebricek_ill = alt.layer(tecky_ill, pocty_ill).configure_view(stroke='transparent').properties(
    width=kredity['sirka'] * 1.12, 
    autosize={'type': 'fit', 'contains': 'padding'}
)

zebricek_ill

alt.LayerChart(...)

In [41]:
do_grafu.filter(pl.col('100_a').str.contains('Hašek')).select(pl.col("245_a")).to_series().to_list()

['Dva tucty povídek',
 'Ze staré droguerie',
 'Všivá historie a jiné humoresky',
 'Veselé povídky',
 'Povídky',
 'Když kvetou třešně a jiné humoresky',
 'Procházka přes hranice',
 'Malá zoologická zahrada',
 'Za války i za sovětů v Rusku',
 'Turista Aratáš a jiné humoresky',
 'Pod věchýtkem humoru',
 'Oslí historie, aneb, Vojenské články do čítanek',
 'Má drahá přítelkyně Julča',
 'Reelní podnik',
 'Potměšilé historie',
 'Humoresky',
 'Smějeme se s Jaroslavem Haškem',
 'Nešťastný policejní ředitel',
 'Dobrý voják Švejk před válkou a jiné podivné historky',
 'Když bolševici zrušili Vánoce',
 'Osudy dobrého vojáka Švejka',
 'Švejk před světovou válkou, Velitelem města Bugulmy a další příběhy',
 'Zpověď starého mládence',
 'Hašek v kostce',
 'Aféra s křečkem a jiné povídky',
 'Postrach domu',
 'Dekameron humoru a satiry',
 'Průvodčí cizinců a jiné satiry z cest i z domova',
 'Osudy dobrého vojáka Švejka za světové války',
 'Útrapy vychovatele']

In [142]:
me_to_neurazi(zebricek_ill, soubor="02_psali_ilustrovali", kredity=kredity['default'])

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_psali_ilustrovali.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_psali_ilustrovali.svg" width="100%" alt="Omlouváme se, ale alternativní text se nepodařilo vygenerovat. Texty v grafu by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

In [43]:
df_ill.group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (34_493, 4)
┌─────────────────────────────────┬───────────────┬─────────────────────────────────┬───────┐
│ 100_a                           ┆ 100_7         ┆ 700_a                           ┆ 245_a │
│ ---                             ┆ ---           ┆ ---                             ┆ ---   │
│ str                             ┆ str           ┆ str                             ┆ u32   │
╞═════════════════════════════════╪═══════════════╪═════════════════════════════════╪═══════╡
│ Štíplová, Ljuba,                ┆ jk01131441    ┆ Němeček, Jaroslav,              ┆ 108   │
│ Nedbalová, Marie                ┆ jo2014816080  ┆ Popprová, Andrea                ┆ 87    │
│ Nedbalová, Marie                ┆ jo2014816080  ┆ Poppr, Roman                    ┆ 68    │
│ Bass, Eduard,                   ┆ jk01011066    ┆ Kratochvíl, Zdeněk,             ┆ 67    │
│ Švandrlík, Miloslav,            ┆ jk01131832    ┆ Winter-Neprakta, Jiří,          ┆ 64    │
│ Wilson, Jacqueline,             ┆ jn20010310318 ┆ Sharratt, Nick,                 ┆ 52    │
│ Delahaye, Gilbert,              ┆ xx0203193     ┆ Marlier, Marcel,                ┆ 51    │
│ Verne, Jules,                   ┆ jn19990008769 ┆ Benett, Léon,                   ┆ 50    │
│ Brezina, Thomas,                ┆ jn20001227589 ┆ Fearn, Naomi,                   ┆ 43    │
│ Verne, Jules,                   ┆ jn19990008769 ┆ Roux, George,                   ┆ 42    │
│ Goscinny, René,                 ┆ jn20000602144 ┆ Uderzo, Albert,                 ┆ 42    │
│ Deary, Terry,                   ┆ jn20001103401 ┆ Brown, Martin,                  ┆ 36    │
│ Čapek, Karel,                   ┆ jk01021023    ┆ Čapek, Josef,                   ┆ 33    │
│ Arnold, Nick,                   ┆ xx0008006     ┆ De Saulles, Tony                ┆ 33    │
│ Pospíšilová, Zuzana,            ┆ mzk2006331486 ┆ Trsťan, Drahomír,               ┆ 31    │
│ Meadows, Daisy                  ┆ xx0082647     ┆ Ripper, Georgie,                ┆ 29    │
│ Hašek, Jaroslav,                ┆ jk01040097    ┆ Lada, Josef,                    ┆ 29    │
│ Rosecká, Zdena                  ┆ jx20031130107 ┆ Růžička, Jiří                   ┆ 28    │
│ Pospíšilová, Zuzana,            ┆ mzk2006331486 ┆ Vopičková, Vladimíra            ┆ 25    │
│ Škodová, Helena,                ┆ jx20040618039 ┆ Kubašta, Vojtěch,               ┆ 25    │
│ Čtvrtek, Václav,                ┆ jk01021929    ┆ Pilař, Radek,                   ┆ 24    │
│ Awdry, W.,                      ┆ xx0010566     ┆ Davies, Robin,                  ┆ 24    │
│ Awdry, W.,                      ┆ xx0010566     ┆ Smith, Jerry                    ┆ 23    │
│ Piroddi, Chiara,                ┆ osa2017965599 ┆ Baruzzi, Agnese,                ┆ 23    │
│ Burroughs, Edgar Rice,          ┆ jn19990001239 ┆ Pešek, Richard,                 ┆ 23    │
│ Tetourová, Marie,               ┆ jn20001005512 ┆ Plicková, Edita,                ┆ 23    │
│ Macourek, Miloš,                ┆ jk01072813    ┆ Born, Adolf,                    ┆ 22    │
│ Foglar, Jaroslav,               ┆ jk01031485    ┆ Čermák, Marko,                  ┆ 22    │
│ May, Karl,                      ┆ jn19990005499 ┆ Krum, Gustav,                   ┆ 21    │
│ Válková, Veronika,              ┆ jo2005274171  ┆ Kopl, Petr,                     ┆ 21    │
│ Žáček, Jiří,                    ┆ jk01152946    ┆ Born, Adolf,                    ┆ 21    │
│ Bednářová, Jiřina,              ┆ mzk2004248919 ┆ Šmarda, Richard,                ┆ 21    │
│ Drijverová, Martina,            ┆ jk01023067    ┆ Otčenášek, Vojtěch,             ┆ 21    │
│ Šavlíková, Lucie,               ┆ jn19981002458 ┆ Roverová, Eva                   ┆ 20    │
│ Pospíšilová, Zuzana,            ┆ mzk2006331486 ┆ Vydrová, Markéta,               ┆ 19    │
│ Walliams, David,                ┆ xx0158956     ┆ Ross, Tony,                     ┆ 19    │
│ Steklač, Vojtěch,               ┆ jk01121138    ┆ Born, Adolf,                    ┆ 19    │
│ May, Karl,                      ┆ jn19990005499 ┆ Ulrich, Josef,                  ┆ 19    │
│ Kratochvíl, Miloš,              ┆ jk01062996    ┆ Vydrová, Markéta,               ┆ 19    │
│ Webb, Holly                     ┆ ola2010577122 ┆ Williams, Sophy                 ┆ 19    │
│ Grey, Zane,                     ┆ jn19990002874 ┆ Hora, Jan,                      ┆ 19    │
│ Stará, Ester,                   ┆ mzk2004261153 ┆ Starý, Milan,                   ┆ 19    │
│ Hrubín, František,              ┆ jk01042920    ┆ Trnka, Jiří,                    ┆ 18    │
│ May, Karl,                      ┆ jn19990005499 ┆ Burian, Zdeněk,                 ┆ 18    │
│ Felix, Jiří,                    ┆ jk01030870    ┆ Hísek, Květoslav,               ┆ 18    │
│ Brezina, Thomas,                ┆ jn20001227589 ┆ Gotzen-Beek, Betina,            ┆ 18    │
│ May, Karl,                      ┆ jn19990005499 ┆ Černý, Věnceslav,               ┆ 18    │
│ Potužníková, Ema                ┆ xx0244812     ┆ Jenčíková, Lucie                ┆ 18    │
│ Hrušková, Marie,                ┆ jn20000401097 ┆ Turek, Jaroslav,                ┆ 18    │
│ Dahl, Roald,                    ┆ jn19990001595 ┆ Blake, Quentin,                 ┆ 18    │
│ …                               ┆ …             ┆ …                               ┆ …     │
│ Kelly, Joe,                     ┆ mzk2015869233 ┆ Morales, Mark                   ┆ 1     │
│ Burget, Eduard,                 ┆ js20011212182 ┆ Bubeníček, Ota,                 ┆ 1     │
│ Kostelecký, Oldřich S.,         ┆ jk01061980    ┆ Kočí, Josef,                    ┆ 1     │
│ Nováková, Milena,               ┆ jk01090591    ┆ Bouda, Cyril,                   ┆ 1     │
│ Frusová, Anna,                  ┆ jk01032045    ┆ Černý, Věnceslav,               ┆ 1     │
│ Křivský, Petr,                  ┆ jk01070124    ┆ Novák, Vladimír,                ┆ 1     │
│ Holejšovská-Genčiová, Miroslav… ┆ jk01032402    ┆ Wagnerová, Denisa,              ┆ 1     │
│ Bezděková, Zdeňka,              ┆ jk01011964    ┆ Ban-Jiránková, Viktoria,        ┆ 1     │
│ Klíma, Miroslav,                ┆ jn99240000464 ┆ Holasová, Aneta Františka,      ┆ 1     │
│ Kendragon, Apollo Raroia        ┆ null          ┆ Otto 66                         ┆ 1     │
│ Hozák, Jan,                     ┆ jn20000401052 ┆ Anlauf, Lubomír,                ┆ 1     │
│ Eastman, Kevin B.,              ┆ xx0062876     ┆ Laird, Peter A.,                ┆ 1     │
│ Tichý, Jiří                     ┆ jk01132425    ┆ Pospíšil, Přemysl,              ┆ 1     │
│ Pěta, Jan,                      ┆ js20050515019 ┆ Šindler, Jiří,                  ┆ 1     │
│ Souter, Gerry,                  ┆ jx20100524036 ┆ Kahlo, Frida,                   ┆ 1     │
│ Kohoutová, Marcela,             ┆ mzk2011667350 ┆ Benetka, Karel,                 ┆ 1     │
│ Mácha, Karel Hynek,             ┆ jk01072915    ┆ Křišťa, Miloslav                ┆ 1     │
│ Hrdličková, Věna,               ┆ jk01042762    ┆ Krejčová, Zdeňka,               ┆ 1     │
│ Slimani, Leïla,                 ┆ pna2017950857 ┆ Oubrerie, Clément,              ┆ 1     │
│ Hroníková, Linda,               ┆ jx20070809014 ┆ Tláskalová, Jitka,              ┆ 1     │
│ Mignola, Mike,                  ┆ mzk2003198870 ┆ Owens, Andy                     ┆ 1     │
│ Lomax, Dean R.                  ┆ xx0273440     ┆ Ugolotti, Sara,                 ┆ 1     │
│ Šachnazarov, Karen,             ┆ js20050808004 ┆ Duchoň, Josef,                  ┆ 1     │
│ Sucharda, Jan Robert,           ┆ jk01121699    ┆ Fuchs, Otakar,                  ┆ 1     │
│ Schmidtová, Eva,                ┆ jk01111011    ┆ Žertová, Anna,                  ┆ 1     │
│ Cikánová, Karla,                ┆ xx0010795     ┆ Skalník, Michal                 ┆ 1     │
│ Hedbávný, Miroslav              ┆ mzk2005313097 ┆ Dvořák, Josef                   ┆ 1     │
│ Mignola, Mike,                  ┆ mzk2003198870 ┆ Chen, Jo,                       ┆ 1     │
│ Brikcius, Eugen,                ┆ jn19990218008 ┆ Slavík, Otakar,                 ┆ 1     │
│ Markup, Antonín                 ┆ jk01080270    ┆ Lhota, Josef,                   ┆ 1     │
│ Kulda, Beneš Metod,             ┆ jk01070781    ┆ Kremláček, Josef,               ┆ 1     │
│ Nový, Ivan,                     ┆ jk01090803    ┆ Beneš, Karel,                   ┆ 1     │
│ Marbehant, Cécile               ┆ jo2012707257  ┆ Mortiaux, Anne-Catherine        ┆ 1     │
│ Isakovskij, Michail Vasil‘jevi… ┆ ola2003172227 ┆ Karásek, Arnošt,                ┆ 1     │
│ Berková, Hana                   ┆ xx0132665     ┆ Umlášek, Josef,                 ┆ 1     │
│ Dobeš, Pavel,                   ┆ jn19981000685 ┆ Neuwirt, Jiří,                  ┆ 1     │
│ Hadrava, Bohumil                ┆ null          ┆ Ceplecha, Bohumil,              ┆ 1     │
│ Vondruška, Vlastimil,           ┆ xx0004129     ┆ Líška, Jan                      ┆ 1     │
│ Šuchmanová, Magdalena           ┆ null          ┆ Filcík, Gabriel,                ┆ 1     │
│ Plívová-Šimková, Věra,          ┆ jk01093489    ┆ Plívová-Pospíšilová, Břetislav… ┆ 1     │
│ Frank, Astrid,                  ┆ xx0061775     ┆ Havlíček, Miloslav,             ┆ 1     │
│ Hrubín, František,              ┆ jk01042920    ┆ Pileček, Jindřich,              ┆ 1     │
│ Grabowski, Sławomir,            ┆ xx0004237     ┆ Szal, Marek                     ┆ 1     │
│ Machota, Jiří                   ┆ null          ┆ Jasanský, Pavel,                ┆ 1     │
│ Náhlovský, Josef Alois,         ┆ pna2006322484 ┆ Mareš, Štěpán,                  ┆ 1     │
│ Braumová, Zdeňka,               ┆ xx0036406     ┆ Koubská, Patricie,              ┆ 1     │
│ Aaron, Jason,                   ┆ xx0189091     ┆ Pichelli, Sara,                 ┆ 1     │
│ Mžyková, Marie,                 ┆ xx0001361     ┆ Hynais, Vojtěch,                ┆ 1     │
│ Blížkovský, Bohumír,            ┆ jk01012376    ┆ Hainall, Václav                 ┆ 1     │
│ Štarha, Ivan,                   ┆ jk01131086    ┆ Hortvík, Václav,                ┆ 1     │
└─────────────────────────────────┴───────────────┴─────────────────────────────────┴───────┘

In [44]:
ctyrlistek_leader = " <leader>     cam a22      a 4500"
ctyrlistek_leader = ctyrlistek_leader.split(">")[1]
print(ctyrlistek_leader[6])
print(ctyrlistek_leader[7])

a
m

In [45]:
df.filter(pl.col('700_4') == 'ill').filter(~pl.col("100_7").is_in(nechcemejetam)).group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True).rename({'100_a':'autor/ka','700_a':'ilustrátor/ka','245_a':'společných knih'}).drop("100_7")

shape: (32_606, 3)
┌─────────────────────────────────┬─────────────────────────────┬─────────────────┐
│ autor/ka                        ┆ ilustrátor/ka               ┆ společných knih │
│ ---                             ┆ ---                         ┆ ---             │
│ str                             ┆ str                         ┆ u32             │
╞═════════════════════════════════╪═════════════════════════════╪═════════════════╡
│ Štíplová, Ljuba,                ┆ Němeček, Jaroslav,          ┆ 108             │
│ Nedbalová, Marie                ┆ Popprová, Andrea            ┆ 87              │
│ Nedbalová, Marie                ┆ Poppr, Roman                ┆ 68              │
│ Bass, Eduard,                   ┆ Kratochvíl, Zdeněk,         ┆ 67              │
│ Švandrlík, Miloslav,            ┆ Winter-Neprakta, Jiří,      ┆ 64              │
│ Čapek, Karel,                   ┆ Čapek, Josef,               ┆ 33              │
│ Pospíšilová, Zuzana,            ┆ Trsťan, Drahomír,           ┆ 31              │
│ Hašek, Jaroslav,                ┆ Lada, Josef,                ┆ 29              │
│ Rosecká, Zdena                  ┆ Růžička, Jiří               ┆ 28              │
│ Pospíšilová, Zuzana,            ┆ Vopičková, Vladimíra        ┆ 25              │
│ Škodová, Helena,                ┆ Kubašta, Vojtěch,           ┆ 25              │
│ Čtvrtek, Václav,                ┆ Pilař, Radek,               ┆ 24              │
│ Tetourová, Marie,               ┆ Plicková, Edita,            ┆ 23              │
│ Piroddi, Chiara,                ┆ Baruzzi, Agnese,            ┆ 23              │
│ Foglar, Jaroslav,               ┆ Čermák, Marko,              ┆ 22              │
│ Macourek, Miloš,                ┆ Born, Adolf,                ┆ 22              │
│ Válková, Veronika,              ┆ Kopl, Petr,                 ┆ 21              │
│ Drijverová, Martina,            ┆ Otčenášek, Vojtěch,         ┆ 21              │
│ Žáček, Jiří,                    ┆ Born, Adolf,                ┆ 21              │
│ Bednářová, Jiřina,              ┆ Šmarda, Richard,            ┆ 21              │
│ Šavlíková, Lucie,               ┆ Roverová, Eva               ┆ 20              │
│ Webb, Holly                     ┆ Williams, Sophy             ┆ 19              │
│ Kratochvíl, Miloš,              ┆ Vydrová, Markéta,           ┆ 19              │
│ Grey, Zane,                     ┆ Hora, Jan,                  ┆ 19              │
│ Stará, Ester,                   ┆ Starý, Milan,               ┆ 19              │
│ Walliams, David,                ┆ Ross, Tony,                 ┆ 19              │
│ Steklač, Vojtěch,               ┆ Born, Adolf,                ┆ 19              │
│ Pospíšilová, Zuzana,            ┆ Vydrová, Markéta,           ┆ 19              │
│ Hrubín, František,              ┆ Trnka, Jiří,                ┆ 18              │
│ Potužníková, Ema                ┆ Jenčíková, Lucie            ┆ 18              │
│ Dahl, Roald,                    ┆ Blake, Quentin,             ┆ 18              │
│ Hrušková, Marie,                ┆ Turek, Jaroslav,            ┆ 18              │
│ Felix, Jiří,                    ┆ Hísek, Květoslav,           ┆ 18              │
│ Brandt, Susanne,                ┆ Lefin, Petra,               ┆ 17              │
│ Lebeda, Jan,                    ┆ Študlarová, Zdeňka,         ┆ 17              │
│ Voleská, Marta,                 ┆ Scheiner, Artuš,            ┆ 17              │
│ Schovancová, Běla,              ┆ Schovanec, Ladislav,        ┆ 17              │
│ Štíplová, Ljuba,                ┆ Janoušková Vančurová, Alena ┆ 17              │
│ Brand, Max,                     ┆ Wowk, Jiří,                 ┆ 17              │
│ Pospíšilová, Zuzana,            ┆ Sušina, Michal              ┆ 17              │
│ Osborne, Mary Pope,             ┆ Knipping, Jutta,            ┆ 16              │
│ Ciprová, Oldřiška,              ┆ Němcová, Lenka,             ┆ 16              │
│ Smolíková, Klára,               ┆ Smolík, Jan,                ┆ 16              │
│ Simon, Francesca,               ┆ Ross, Tony,                 ┆ 16              │
│ Johns, William Earl,            ┆ Barč, Petr,                 ┆ 16              │
│ Beigel, Christine,              ┆ Le Goff, Hervé,             ┆ 16              │
│ Běhounek, František,            ┆ Junek, Václav,              ┆ 16              │
│ Rožnovská, Lenka,               ┆ Vydrová, Markéta,           ┆ 16              │
│ Eislerová, Jana,                ┆ Šplíchal, Antonín,          ┆ 15              │
│ Friedrich, Joachim,             ┆ Páv, Libor,                 ┆ 14              │
│ …                               ┆ …                           ┆ …               │
│ Rybák, Josef,                   ┆ Troup, Miloslav,            ┆ 1               │
│ O'Hara, Natalia                 ┆ O'Hara, Lauren              ┆ 1               │
│ Potter, Ellen,                  ┆ Reynolds, Peter,            ┆ 1               │
│ Skolek, Richard,                ┆ Janík, Štěpán               ┆ 1               │
│ Šircová, Milena,                ┆ Slábová, Martina,           ┆ 1               │
│ Uhde, Milan,                    ┆ Pospíšil, Rostislav,        ┆ 1               │
│ Toušová, Pavla                  ┆ Šerá, Eva                   ┆ 1               │
│ Rusnáková, Olga,                ┆ Chládková, Dagmar,          ┆ 1               │
│ Mináč, Vladimír,                ┆ Klimo, Alojz,               ┆ 1               │
│ Kohoutová, Kamila,              ┆ Myokard                     ┆ 1               │
│ Bystrá-Radvanová, Michaela,     ┆ Braná, Jana,                ┆ 1               │
│ Vyšín, Jan,                     ┆ Mikulčák, Jiří,             ┆ 1               │
│ Silvestri, Marc,                ┆ Smith, Matthew Dow,         ┆ 1               │
│ Juliš, Emil,                    ┆ Kopecký, Bohdan,            ┆ 1               │
│ Přádná, Petra                   ┆ Smetana, Zdeněk,            ┆ 1               │
│ Hulpach, Vladimír,              ┆ Kolíbal, Stanislav,         ┆ 1               │
│ Novák, Emil,                    ┆ Shéla, Lubomír              ┆ 1               │
│ Sláma, Jan,                     ┆ Rittstein, Michael,         ┆ 1               │
│ Cook, James,                    ┆ Majzner, Zdeněk,            ┆ 1               │
│ Nevečeřal, Aleš,                ┆ Dajč, Jaroslav,             ┆ 1               │
│ Štěrbová, Ludmila,              ┆ Špačková, Jitka             ┆ 1               │
│ Mühlsteinová, Berta,            ┆ Šimůnek, Karel,             ┆ 1               │
│ Rowling, J. K.,                 ┆ Pinfold, Levi               ┆ 1               │
│ Smoljak, Ladislav,              ┆ Otáhalová, Pavla            ┆ 1               │
│ Čermáková, Josefa               ┆ Polakovič, Dušan,           ┆ 1               │
│ Kafková, Blanka,                ┆ Mánes, Josef,               ┆ 1               │
│ Kostrhun, Petr,                 ┆ Latzmann, Marek,            ┆ 1               │
│ Gaiman, Neil,                   ┆ Johnson, Paul,              ┆ 1               │
│ Plívová, Hana                   ┆ To.Hlava                    ┆ 1               │
│ Russell, P. Craig,              ┆ Kantůrek, Jan,              ┆ 1               │
│ Conner, Amanda,                 ┆ Peters, Brandt              ┆ 1               │
│ Scott, Cavan,                   ┆ Charretier, Elsa,           ┆ 1               │
│ Kučera, Jan Pavel,              ┆ Born, Adolf,                ┆ 1               │
│ Frank, Astrid,                  ┆ Havlíček, Miloslav,         ┆ 1               │
│ Vaněk, František Bernard,       ┆ Thein, Antonín,             ┆ 1               │
│ Kocová, Tereza                  ┆ Buchalová, Bára,            ┆ 1               │
│ Kašpar, Jan,                    ┆ Holý, Stanislav,            ┆ 1               │
│ Letz, Štefan,                   ┆ Rocman, Vladimír,           ┆ 1               │
│ Ezop,                           ┆ Mézl, Zdeněk,               ┆ 1               │
│ Gaudore, Pavel,                 ┆ Žilák, Pavel,               ┆ 1               │
│ Holková, Marie,                 ┆ Hrabal, Arnošt,             ┆ 1               │
│ Matoušek, Oldřich,              ┆ Velková, Irena,             ┆ 1               │
│ Davies, Stephen,                ┆ Evans, Victoria             ┆ 1               │
│ Palacký, František,             ┆ Svolinský, Karel,           ┆ 1               │
│ Procházka, Jiří,                ┆ Havlíček, Miloslav,         ┆ 1               │
│ Flaška z Pardubic a Rychmburku… ┆ Strnadel, Antonín,          ┆ 1               │
│ Bílek, Otakar                   ┆ Humpál, Zdeněk              ┆ 1               │
│ Slušný, Jaromír,                ┆ Poharyskyi, Daniel          ┆ 1               │
│ Adamec, Vladimír                ┆ Pospíšil, Přemysl,          ┆ 1               │
│ Andreadis, Ivan,                ┆ Mašek, Otakar               ┆ 1               │
└─────────────────────────────────┴─────────────────────────────┴─────────────────┘

In [46]:
df.filter(pl.col('700_4') == 'trl').group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (66_400, 4)
┌─────────────────────────────────┬────────────────┬───────────────────────────┬───────┐
│ 100_a                           ┆ 100_7          ┆ 700_a                     ┆ 245_a │
│ ---                             ┆ ---            ┆ ---                       ┆ ---   │
│ str                             ┆ str            ┆ str                       ┆ u32   │
╞═════════════════════════════════╪════════════════╪═══════════════════════════╪═══════╡
│ Unger, Gert F.,                 ┆ jn20001103529  ┆ Butala, Tomáš,            ┆ 311   │
│ Kirby, John                     ┆ jx20040611003  ┆ Pavka, Marek,             ┆ 182   │
│ Courths-Mahler, Hedwig,         ┆ jn19990001513  ┆ Schönová, Zuzana          ┆ 120   │
│ Scott, William,                 ┆ ola2003188680  ┆ Butala, Tomáš,            ┆ 101   │
│ Birkner-Mahler, Frieda,         ┆ jn20000600873  ┆ Lacinová, Libuše,         ┆ 80    │
│ Unger, Gert F.,                 ┆ jn20001103529  ┆ Schönová, Zuzana          ┆ 80    │
│ Unger, Gert F.,                 ┆ jn20001103529  ┆ Sedláčková, Libuše        ┆ 77    │
│ Pratchett, Terry,               ┆ jo20000080627  ┆ Kantůrek, Jan,            ┆ 57    │
│ Brezina, Thomas,                ┆ jn20001227589  ┆ Steidlová, Dagmar,        ┆ 55    │
│ Courths-Mahler, Hedwig,         ┆ jn19990001513  ┆ Lacinová, Libuše,         ┆ 54    │
│ Lane, Lex                       ┆ ola2007364818  ┆ Pavka, Marek,             ┆ 53    │
│ Dark, Jason,                    ┆ jn20000810032  ┆ Sychra, Pavel             ┆ 50    │
│ Nieritz, Gustav,                ┆ jo20000080760  ┆ Tomsa, František Bohumil, ┆ 49    │
│ Dark, Jason,                    ┆ jn20000810032  ┆ Küchler, Marek            ┆ 48    │
│ Unger, Gert F.,                 ┆ jn20001103529  ┆ Sychra, Pavel             ┆ 48    │
│ Hayes, Rex,                     ┆ jn20020717154  ┆ Pavka, Marek,             ┆ 47    │
│ Shakespeare, William,           ┆ jn19981002129  ┆ Sládek, Josef Václav,     ┆ 46    │
│ Etzold, Hans-Rüdiger,           ┆ xx0020263      ┆ Hlásek, Pavel             ┆ 45    │
│ Steiner, Rudolf,                ┆ jn19990009728  ┆ Hradil, Radomil,          ┆ 45    │
│ Francis, Dick,                  ┆ jn19990002376  ┆ Moserová, Jaroslava,      ┆ 43    │
│ Wallace, Edgar,                 ┆ jn19990008883  ┆ Heller, František         ┆ 43    │
│ Shakespeare, William,           ┆ jn19981002129  ┆ Hilský, Martin,           ┆ 42    │
│ Mark, William,                  ┆ jo20241218643  ┆ Kuťák, Jaroslav,          ┆ 42    │
│ Davis, Jim,                     ┆ jn20010601536  ┆ Škába, Filip,             ┆ 42    │
│ Velden, Irene von               ┆ jx20031204026  ┆ Chromiaková, Eva          ┆ 40    │
│ May, Karl,                      ┆ jn19990005499  ┆ Šunda, Vladimír           ┆ 39    │
│ Verne, Jules,                   ┆ jn19990008769  ┆ Unzeitig, Vítězslav,      ┆ 38    │
│ Wilson, Jacqueline,             ┆ jn20010310318  ┆ Feltová, Daniela,         ┆ 38    │
│ Unger, Gert F.,                 ┆ jn20001103529  ┆ Veselý, Milan             ┆ 38    │
│ Dark, Jason,                    ┆ jn20000810032  ┆ Brzobohatý, Rostislav     ┆ 35    │
│ Patterson, James,               ┆ jo20000076489  ┆ Duha, Ondřej              ┆ 35    │
│ Wild, Dunja                     ┆ ola20040510003 ┆ Smolaková, Helena         ┆ 35    │
│ Cartland, Barbara,              ┆ jn19990001350  ┆ Volná, Kristina,          ┆ 34    │
│ Andrée, Michaela                ┆ ola2003188685  ┆ Smolaková, Helena         ┆ 34    │
│ Platón,                         ┆ jn19981001996  ┆ Novotný, František,       ┆ 33    │
│ McBain, Ed,                     ┆ jn19981001834  ┆ Maxová, Alena,            ┆ 33    │
│ King, Stephen,                  ┆ jn19990004346  ┆ Bartošková, Linda,        ┆ 32    │
│ Ošó,                            ┆ jn19981001926  ┆ Žlábková, Jana,           ┆ 32    │
│ Everett, Jack,                  ┆ jn20020717155  ┆ Pavka, Marek,             ┆ 31    │
│ Deaver, Jeffery,                ┆ jn20001103550  ┆ Kobělka, Jiří,            ┆ 31    │
│ Murphy, Bill,                   ┆ mzk2008443048  ┆ Pavka, Marek,             ┆ 31    │
│ Vandenberg, Patricia,           ┆ jn20000810141  ┆ Všetulová, Marisa         ┆ 31    │
│ Billet, Marion,                 ┆ xx0206378      ┆ Kocmanová, Ivana,         ┆ 28    │
│ Choux, Nathalie,                ┆ xx0200182      ┆ Vyskočil, Josef           ┆ 27    │
│ Dán, Dominik,                   ┆ xx0085412      ┆ Hanzlík, Jan              ┆ 27    │
│ Doyle, Arthur Conan,            ┆ jn19990001842  ┆ Pachmayer, Josef,         ┆ 27    │
│ Hergé,                          ┆ xx0019604      ┆ Vinšová, Kateřina,        ┆ 26    │
│ Stephan, Sabine                 ┆ jn20010309603  ┆ Smolaková, Helena         ┆ 26    │
│ Vandenberg, Patricia,           ┆ jn20000810141  ┆ Podolská, Zora            ┆ 25    │
│ Shakespeare, William,           ┆ jn19981002129  ┆ Saudek, Erik Adolf,       ┆ 24    │
│ …                               ┆ …              ┆ …                         ┆ …     │
│ Schwarz, Marianne               ┆ jn20000810056  ┆ Všetulová, Marisa         ┆ 1     │
│ Euripidés,                      ┆ jn19981001000  ┆ Topol, Josef,             ┆ 1     │
│ Albert, Melissa                 ┆ xx0228747      ┆ Řeřichová, Alžběta        ┆ 1     │
│ Cox, Richard                    ┆ null           ┆ Švejda, Michal            ┆ 1     │
│ Molière,                        ┆ jn19981001860  ┆ Bernášek, Antonín,        ┆ 1     │
│ Moseley, Lonnie E.              ┆ null           ┆ Lahoda, Vladimír          ┆ 1     │
│ Futscher, Christian,            ┆ jo2008464869   ┆ Buddeus, Ondřej,          ┆ 1     │
│ Hart, Maarten 't,               ┆ xx0000467      ┆ Vítek, Lukáš,             ┆ 1     │
│ Ricœur, Paul,                   ┆ jn20000701502  ┆ Poučová, Marcela          ┆ 1     │
│ Doležal, Jakub,                 ┆ xx0125890      ┆ Day, Barbara,             ┆ 1     │
│ Whitlock, Brand,                ┆ jn20010316239  ┆ Lázňovský, Bohuslav,      ┆ 1     │
│ Misesti, Paola,                 ┆ jo20211125575  ┆ Osoba, Petr               ┆ 1     │
│ Oftring, Bärbel,                ┆ ola2010605436  ┆ Blättler, Linda,          ┆ 1     │
│ Rothberg, Gerta                 ┆ jx20041020018  ┆ Pavlíček, Ant. R.         ┆ 1     │
│ Kepka, Tomáš                    ┆ xx0109708      ┆ Zuntová, Sylvie           ┆ 1     │
│ Afanas‘jev, Aleksandr Nikolaje… ┆ jo20010084752  ┆ Kurzová, Eva              ┆ 1     │
│ Wilson, Deirdre,                ┆ jo2013767337   ┆ Vichnarová, Ingrid        ┆ 1     │
│ Elman, Michelle,                ┆ xx0239294      ┆ Hesounová, Vlasta,        ┆ 1     │
│ Zell, Friedrich,                ┆ jo2002109915   ┆ P.                        ┆ 1     │
│ Posse-Brázdová, Amelie,         ┆ jn19981002028  ┆ Kufnerová, Zlata,         ┆ 1     │
│ Nosilov, Konstantin Dmitrijevi… ┆ xx0187373      ┆ Wagner, Jan,              ┆ 1     │
│ Thompson, Don                   ┆ jx20100317010  ┆ Neradová, Martina,        ┆ 1     │
│ Cho, Charlotte                  ┆ xx0239621      ┆ Štorkánová, Anna,         ┆ 1     │
│ Puleo, Joe                      ┆ mub2011632983  ┆ Stackeová, Daniela,       ┆ 1     │
│ Greene, Graham,                 ┆ jn19990002859  ┆ Kyncl, Karel,             ┆ 1     │
│ Moore, Dan                      ┆ ola20191019598 ┆ Kopička, Karel,           ┆ 1     │
│ Eco, Umberto,                   ┆ jn19990001971  ┆ Štichauer, Pavel,         ┆ 1     │
│ Culler, Jonathan D.,            ┆ jo2003163248   ┆ Bareš, Jiří,              ┆ 1     │
│ Winkler, Philipp,               ┆ osa2016931879  ┆ Hanišová, Viktorie,       ┆ 1     │
│ Kesey, Ken,                     ┆ jo20010087027  ┆ Hanuš, Jiří,              ┆ 1     │
│ Pourtalès, Guy de,              ┆ ola2004216987  ┆ Marek, Oldřich,           ┆ 1     │
│ Saburov, Aleksandr Nikolajevič… ┆ xx0063711      ┆ Michna, Vladimír,         ┆ 1     │
│ Gray, John,                     ┆ skuk0002744    ┆ Micka, Daniel,            ┆ 1     │
│ Jensen, Johannes Vilhelm,       ┆ xx0004106      ┆ Hackenschmied, Hanuš,     ┆ 1     │
│ Clancy, Tim                     ┆ xx0280953      ┆ Beneš, Radomír            ┆ 1     │
│ Karasch, Peter,                 ┆ pna20201068929 ┆ Moudrý, Lubomír,          ┆ 1     │
│ Dufek, Pavel,                   ┆ mzk2006323061  ┆ Langer, Theresa           ┆ 1     │
│ Fuchs, Vivian,                  ┆ xx0012346      ┆ Bernau, Gustav,           ┆ 1     │
│ Simon, Erik,                    ┆ jn19990007974  ┆ Železná, Jitka,           ┆ 1     │
│ Kehl, Medard,                   ┆ jn19990004241  ┆ Kolmačka, Pavel,          ┆ 1     │
│ Groot, Anne de                  ┆ jx20040130001  ┆ Černá, Ivana              ┆ 1     │
│ Yegar, Moshe                    ┆ null           ┆ Sláma, Petr,              ┆ 1     │
│ Lingas-Łoniewska, Agnieszka,    ┆ xx0261973      ┆ Novák, Jan                ┆ 1     │
│ Harrar, Sarí                    ┆ jx20090630007  ┆ Kušiak, Ivan              ┆ 1     │
│ Mansell, Joanna                 ┆ xx0074836      ┆ Láblerová, Ivana          ┆ 1     │
│ Scheurmann, Ines,               ┆ jn20000604880  ┆ Sochorová, Bronislava     ┆ 1     │
│ Winckler, Britta                ┆ xx0084566      ┆ Doubravová, Jarmila       ┆ 1     │
│ Espriu, Salvador,               ┆ ola2002161284  ┆ Schejbal, Jan,            ┆ 1     │
│ Doherty, Bridget                ┆ nlk20050170682 ┆ Šišáková, Jitka,          ┆ 1     │
│ Wax, Ruby,                      ┆ osa2016933402  ┆ Sumcov, Petr,             ┆ 1     │
└─────────────────────────────────┴────────────────┴───────────────────────────┴───────┘

In [47]:
df.filter(pl.col('700_4') == 'ill').group_by('700_a').agg(pl.col("100_a").n_unique()).sort(by="100_a",descending=True)

shape: (13_657, 2)
┌─────────────────────────────────┬───────┐
│ 700_a                           ┆ 100_a │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Born, Adolf,                    ┆ 149   │
│ Bouda, Cyril,                   ┆ 114   │
│ Burian, Zdeněk,                 ┆ 112   │
│ Krejčová, Zdeňka,               ┆ 98    │
│ Svolinský, Karel,               ┆ 93    │
│ Zmatlíková, Helena,             ┆ 80    │
│ Aleš, Mikoláš,                  ┆ 80    │
│ Petráček, Jiří,                 ┆ 78    │
│ Jiránek, Vladimír,              ┆ 75    │
│ Slíva, Jiří,                    ┆ 73    │
│ Šplíchal, Antonín,              ┆ 73    │
│ Černý, Věnceslav,               ┆ 69    │
│ Čuma, Aleš,                     ┆ 67    │
│ Thuma, Karel Ladislav,          ┆ 67    │
│ Plicková, Edita,                ┆ 67    │
│ Winter-Neprakta, Jiří,          ┆ 65    │
│ Teissig, Karel,                 ┆ 65    │
│ Procházka, Otakar               ┆ 65    │
│ Lada, Josef,                    ┆ 61    │
│ Lhoták, Kamil,                  ┆ 61    │
│ Komárek, Vladimír,              ┆ 61    │
│ Janeček, Ota,                   ┆ 60    │
│ Urban, Petr,                    ┆ 60    │
│ Martenek, Miloslav,             ┆ 58    │
│ Černý, Jan,                     ┆ 55    │
│ Fixl, Jiří,                     ┆ 55    │
│ Kabát, Václav,                  ┆ 55    │
│ Tesař, Vladimír,                ┆ 53    │
│ Netopil, Zdeněk,                ┆ 53    │
│ Velčovský, Josef,               ┆ 53    │
│ Čutta, Václav,                  ┆ 52    │
│ Jakešová, Miroslava,            ┆ 52    │
│ Škoda, František,               ┆ 51    │
│ Duda, Stanislav,                ┆ 50    │
│ Trnka, Jiří,                    ┆ 49    │
│ Renčín, Vladimír,               ┆ 49    │
│ Čechová, Olga,                  ┆ 48    │
│ Kalousek, Jiří,                 ┆ 48    │
│ Váša, Miroslav,                 ┆ 46    │
│ Konůpek, Jan,                   ┆ 45    │
│ Scheiner, Artuš,                ┆ 45    │
│ Nesvadba, Miloš,                ┆ 44    │
│ Zpěvák, Karel                   ┆ 44    │
│ Kovařík, Jindřich,              ┆ 44    │
│ Barták, Miroslav,               ┆ 44    │
│ Jágr, Miloslav,                 ┆ 43    │
│ Anlauf, Lubomír,                ┆ 42    │
│ Drobný, Libor,                  ┆ 42    │
│ Franta, Karel,                  ┆ 42    │
│ Študlarová, Zdeňka,             ┆ 41    │
│ …                               ┆ …     │
│ Sulkiewicz, Miroslav            ┆ 1     │
│ Downton, David,                 ┆ 1     │
│ Černý, Bohuslav                 ┆ 1     │
│ Polák, Miroslav,                ┆ 1     │
│ Davies, Kate,                   ┆ 1     │
│ Fei, Shen                       ┆ 1     │
│ Moumene, Sofian,                ┆ 1     │
│ Hauptigová, Nikola              ┆ 1     │
│ Juryšek, Jaroslav               ┆ 1     │
│ Hues, Nat                       ┆ 1     │
│ Kopp, Antonín,                  ┆ 1     │
│ Škardová Kubásková, Naděžda,    ┆ 1     │
│ Cooke, Grace                    ┆ 1     │
│ Stone, Petula                   ┆ 1     │
│ Łobuś, Artur                    ┆ 1     │
│ Quesnay de Beaurepaire, Alfred… ┆ 1     │
│ Rohanová, Renáta                ┆ 1     │
│ Rerekìna, Natalìja              ┆ 1     │
│ Adamcová, Erika Ena             ┆ 1     │
│ Špaček, Jaroslav,               ┆ 1     │
│ Hořavová, Karolina,             ┆ 1     │
│ Hajdamaka, Jevhenìja,           ┆ 1     │
│ Truksa, Miroslav,               ┆ 1     │
│ Kaname, Ryu                     ┆ 1     │
│ Maresca, Luca                   ┆ 1     │
│ Austin, Terry,                  ┆ 1     │
│ Gribouille, Mary,               ┆ 1     │
│ Vlček, Václav,                  ┆ 1     │
│ Wilhelm, Hans,                  ┆ 1     │
│ Sandberg, Lasse,                ┆ 1     │
│ Kotasová, Věra,                 ┆ 1     │
│ Stier, Irmtrud                  ┆ 1     │
│ Cone, Sno                       ┆ 1     │
│ Small, Steve                    ┆ 1     │
│ Šáteková, Ivana,                ┆ 1     │
│ Šebesta, Pavel                  ┆ 1     │
│ Chebret, Sébastien,             ┆ 1     │
│ Blažejová, Hana,                ┆ 1     │
│ Šrámková, Andrea,               ┆ 1     │
│ Dvořáková, Šárka                ┆ 1     │
│ Cain, Martyn                    ┆ 1     │
│ Pino, Chaco                     ┆ 1     │
│ Kolčáková, Běla,                ┆ 1     │
│ Winiecki, Marian                ┆ 1     │
│ Mayerhofer, Theodor,            ┆ 1     │
│ Kirkham, Tyler,                 ┆ 1     │
│ MacNaughton, Wendy,             ┆ 1     │
│ Tošovský, Josef                 ┆ 1     │
│ Offermann, Andrea,              ┆ 1     │
│ Votruba, Jaroslav,              ┆ 1     │
└─────────────────────────────────┴───────┘

In [48]:
nejaktivnejsi_ilustratori = df.filter(pl.col("stran") > 30).filter(pl.col('700_4') == 'ill').group_by('700_7').agg(pl.struct(["100_a","245_a"]).n_unique()).sort(by="100_a",descending=True).head(11).select(pl.col("700_7")).to_series().to_list()
nejaktivnejsi_ilustratori = [x for x in nejaktivnejsi_ilustratori if x != None]
nejaktivnejsi_ilustratori

['jk01012660',
 'jk01020396',
 'jk01083186',
 'jk01083128',
 'jk01012795',
 'jk01063265',
 'jk01152754',
 'jk01021645',
 'jk01132366',
 'ola2003162788']

In [49]:
def hezkejmeno(sto):
    if not sto[-1].isalnum():
        sto = sto[:-1]
    if "," in sto:
        sto = sto.split(",")
        sto = sto[1].strip() + " " + sto[0].strip()
    return sto

In [50]:
do_grafu2 = df.filter(pl.col('700_7').is_in(nejaktivnejsi_ilustratori)).with_columns(pl.col('700_a').map_elements(hezkejmeno)).with_columns(pl.col("rok").map_elements(lambda x: datetime.date(year=int(x), month=1, day=1), return_dtype=pl.Date).cast(pl.Datetime))
nejaktivnejsi_ilustratori2 = do_grafu2.group_by('700_a').agg(pl.struct(["100_a","245_a"]).n_unique()).sort(by="100_a",descending=True).head(10).select(pl.col("700_a")).to_series().to_list()
mrtvi_ilustratori = aut.explode("100_7").filter(pl.col('100_7').is_in(nejaktivnejsi_ilustratori)).explode("046_g").with_columns(pl.col("046_g").map_elements(lambda x: int(x)).alias("umrti")).select(pl.col(["100_7","umrti"])).filter(pl.col('umrti').is_between(1800,2025)).with_columns(pl.col("umrti").map_elements(lambda x: datetime.date(year=int(x), month=1, day=1), return_dtype=pl.Date).cast(pl.Datetime))
do_grafu2 = do_grafu2.join(mrtvi_ilustratori, how='left', left_on='700_7', right_on='100_7').join(
    do_grafu2.group_by('700_7').len(), on='700_7', how='left'
).with_columns(
    pl.col("len").map_elements(lambda x: str(x) + "×")
).with_columns(
    pl.concat_str([pl.col('len'), pl.col('700_a')], separator=' ').alias('700_a')
)
nejaktivnejsi_ilustratori2 = do_grafu2.group_by('700_a').len().sort(by='len',descending=True).select(pl.col('700_a')).to_series().to_list()

In [51]:
mrtvi_ilustratori

shape: (7, 2)
┌────────────┬─────────────────────┐
│ 100_7      ┆ umrti               │
│ ---        ┆ ---                 │
│ str        ┆ datetime[μs]        │
╞════════════╪═════════════════════╡
│ jk01012660 ┆ 2016-01-01 00:00:00 │
│ jk01012795 ┆ 1984-01-01 00:00:00 │
│ jk01020396 ┆ 1981-01-01 00:00:00 │
│ jk01021645 ┆ 1936-01-01 00:00:00 │
│ jk01132366 ┆ 1917-01-01 00:00:00 │
│ jk01083186 ┆ 2011-01-01 00:00:00 │
│ jk01152754 ┆ 2005-01-01 00:00:00 │
└────────────┴─────────────────────┘

In [52]:
nejaktivnejsi_ilustratori2

['457× Zdeněk Burian',
 '451× Helena Zmatlíková',
 '445× Adolf Born',
 '254× Antonín Šplíchal',
 '252× Cyril Bouda',
 '233× Jiří Winter-Neprakta',
 '204× Věnceslav Černý',
 '198× Zdeňka Krejčová',
 '197× Jaroslav Němeček',
 '169× Karel Ladislav Thuma']

In [53]:
do_grafu2.sample(5)

shape: (5, 70)
┌──────────┬──────────────────────┬───────────────┬───────────┬───┬──────────────┬───────┬──────────────────────┬──────┐
│ 100_ind1 ┆ 100_a                ┆ 100_7         ┆ 100_4     ┆ … ┆ rok          ┆ stran ┆ umrti                ┆ len  │
│ ---      ┆ ---                  ┆ ---           ┆ ---       ┆   ┆ ---          ┆ ---   ┆ ---                  ┆ ---  │
│ str      ┆ str                  ┆ str           ┆ list[str] ┆   ┆ datetime[μs] ┆ i64   ┆ datetime[μs]         ┆ str  │
╞══════════╪══════════════════════╪═══════════════╪═══════════╪═══╪══════════════╪═══════╪══════════════════════╪══════╡
│ 1        ┆ Brukner, Josef,      ┆ jk01013304    ┆ ["aut"]   ┆ … ┆ 1997-01-01   ┆ 224   ┆ null                 ┆ 198× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Doucha, František,   ┆ jk01022897    ┆ ["aut"]   ┆ … ┆ 1885-01-01   ┆ 46    ┆ 1917-01-01 00:00:00  ┆ 169× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Seidel, Ina,         ┆ xx0022624     ┆ ["aut"]   ┆ … ┆ 1941-01-01   ┆ 423   ┆ 1984-01-01 00:00:00  ┆ 252× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Rodari, Gianni,      ┆ jn19990007094 ┆ ["aut"]   ┆ … ┆ 2016-01-01   ┆ 125   ┆ 2016-01-01 00:00:00  ┆ 445× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Johns, William Earl, ┆ jn19990004054 ┆ ["aut"]   ┆ … ┆ 1939-01-01   ┆ 212   ┆ 1981-01-01 00:00:00  ┆ 457× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
└──────────┴──────────────────────┴───────────────┴───────────┴───┴──────────────┴───────┴──────────────────────┴──────┘

In [54]:
nejaktivnejsi_ilustratori2

['457× Zdeněk Burian',
 '451× Helena Zmatlíková',
 '445× Adolf Born',
 '254× Antonín Šplíchal',
 '252× Cyril Bouda',
 '233× Jiří Winter-Neprakta',
 '204× Věnceslav Černý',
 '198× Zdeňka Krejčová',
 '197× Jaroslav Němeček',
 '169× Karel Ladislav Thuma']

In [55]:
do_grafu2.sample(3)

shape: (3, 70)
┌──────────┬────────────────┬────────────┬───────────┬───┬───────────────────────┬───────┬──────────────────────┬──────┐
│ 100_ind1 ┆ 100_a          ┆ 100_7      ┆ 100_4     ┆ … ┆ rok                   ┆ stran ┆ umrti                ┆ len  │
│ ---      ┆ ---            ┆ ---        ┆ ---       ┆   ┆ ---                   ┆ ---   ┆ ---                  ┆ ---  │
│ str      ┆ str            ┆ str        ┆ list[str] ┆   ┆ datetime[μs]          ┆ i64   ┆ datetime[μs]         ┆ str  │
╞══════════╪════════════════╪════════════╪═══════════╪═══╪═══════════════════════╪═══════╪══════════════════════╪══════╡
│ 1        ┆ Uzel, Radim,   ┆ jk01140932 ┆ ["aut"]   ┆ … ┆ 2014-01-01 00:00:00   ┆ 206   ┆ 2011-01-01 00:00:00  ┆ 233× │
│ 1        ┆ Baar, Jindřich ┆ jk01010468 ┆ ["aut"]   ┆ … ┆ 1975-01-01 00:00:00   ┆ 437   ┆ 1984-01-01 00:00:00  ┆ 252× │
│          ┆ Šimon,         ┆            ┆           ┆   ┆                       ┆       ┆                      ┆      │
│ 1        ┆ Horníček,      ┆ jk01042235 ┆ ["aut"]   ┆ … ┆ 1984-01-01 00:00:00   ┆ 170   ┆ 2016-01-01 00:00:00  ┆ 445× │
│          ┆ Miroslav,      ┆            ┆           ┆   ┆                       ┆       ┆                      ┆      │
└──────────┴────────────────┴────────────┴───────────┴───┴───────────────────────┴───────┴──────────────────────┴──────┘

In [56]:
base = alt.Chart(
    do_grafu2.filter(pl.col('700_a').is_in(nejaktivnejsi_ilustratori2)).to_pandas(), title=alt.TitleParams(
        f"{len(nejaktivnejsi_ilustratori2)} nejvydávanějších ilustrátorů a ilustrátorek (bez reprintů)",
    subtitle="Co tečka, to kniha. Černá čárka označuje rok úmrtí."))

kulicky = base.mark_circle(size=7, filled=True).encode(
            x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6')), 
            y=alt.Y("700_a:N", sort=nejaktivnejsi_ilustratori2, title=None, axis=alt.Axis(orient='left', domainOpacity=0, tickColor='white', labelExpr='split(datum.label, "× ")[1]' )), #, 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[3, 15])), 
            color=alt.Color('700_a:N', scale=alt.Scale(range=['#E09DA3']), 
                            sort=nejaktivnejsi_ilustratori2).legend(None)) \
        .transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

kdy_umreli = base.mark_tick(
    color='#292829',  # optional: you can specify color
    thickness=1.5,
    height=9
).encode(
    x=alt.X('umrti:T', title=None),
    y=alt.Y("700_a:N", sort=nejaktivnejsi_ilustratori2, title=None, axis=alt.Axis(orient='left', tickColor='white', labels=False)))

pocty = base.mark_text().encode(x=alt.X('rok:T', title=None), 
    y=alt.Y('700_a:N', title=None, sort=nejaktivnejsi_ilustratori2, axis=alt.Axis(orient="right", tickColor='white', labelExpr='split(datum.label, " ")[0]'))) #

zebricek2 = alt.layer(kulicky, kdy_umreli, pocty).configure_view(stroke='transparent').properties(
    width=kredity['sirka'] * 1.12,
    autosize={'type': 'fit', 'contains': 'padding'}
).resolve_scale(color='independent',x="shared")

zebricek2

alt.LayerChart(...)

In [57]:
me_to_neurazi(zebricek2, kredity=kredity['default'], soubor='02_ilustratorstvo')

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_ilustratorstvo.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_ilustratorstvo.svg" width="100%" alt="Omlouváme se, ale alternativní text se nepodařilo vygenerovat. Texty v grafu by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

In [58]:
df.filter(pl.col('700_a') == 'Born, Adolf,')

shape: (445, 68)
┌──────────┬───────────────────────────┬───────────────────┬────────────────┬───┬───────────┬───────────┬──────┬───────┐
│ 100_ind1 ┆ 100_a                     ┆ 100_7             ┆ 100_4          ┆ … ┆ 700_9     ┆ 700_g     ┆ rok  ┆ stran │
│ ---      ┆ ---                       ┆ ---               ┆ ---            ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---   │
│ str      ┆ str                       ┆ str               ┆ list[str]      ┆   ┆ list[str] ┆ list[str] ┆ i64  ┆ i64   │
╞══════════╪═══════════════════════════╪═══════════════════╪════════════════╪═══╪═══════════╪═══════════╪══════╪═══════╡
│ 1        ┆ Pecháček, Ladislav,       ┆ jk01092311        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 133   │
│ 1        ┆ Branald, Adolf,           ┆ jk01012955        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 319   │
│ 1        ┆ Drijverová, Martina,      ┆ jk01023067        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1988 ┆ 59    │
│ 1        ┆ Hercíková, Iva,           ┆ jk01040797        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 141   │
│ 1        ┆ Drijverová, Martina,      ┆ jk01023067        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 62    │
│ 1        ┆ Sýkora, Pavel,            ┆ xx0008401         ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 141   │
│ 1        ┆ Nepil, František,         ┆ jk01083177        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 93    │
│ 1        ┆ Drijverová, Martina,      ┆ jk01023067        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 62    │
│ 1        ┆ Pavel, Ota,               ┆ jk01092027        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1979 ┆ 98    │
│ 1        ┆ Frýbová, Zdena,           ┆ jk01032058        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 237   │
│ 1        ┆ Karfíková, Věra,          ┆ jk01053026        ┆ ["com"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 180   │
│ 1        ┆ Franková, Hermína,        ┆ jk01031754        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1979 ┆ 147   │
│ 1        ┆ Krejčí, Stanislav         ┆ jk01063233        ┆ ["com", "trl"] ┆ … ┆ null      ┆ null      ┆ 1978 ┆ 94    │
│ 1        ┆ Rudolf, Stanislav,        ┆ jk01103025        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1973 ┆ 132   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2020 ┆ 108   │
│ 1        ┆ Brdečka, Jiří,            ┆ jk01013050        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1956 ┆ 195   │
│ 1        ┆ Hercíková, Iva,           ┆ jk01040797        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1981 ┆ 383   │
│ 1        ┆ Neville, Emily,           ┆ xx0051718         ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1973 ┆ 130   │
│ 1        ┆ Dickens, Charles,         ┆ jn19990001747     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 158   │
│ 1        ┆ Říha, Bohumil,            ┆ jk01110164        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 56    │
│ 1        ┆ Neruda, Jan,              ┆ jk01083209        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 12    │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1989 ┆ 63    │
│ 1        ┆ Shakespeare, William,     ┆ jn19981002129     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1966 ┆ 168   │
│ 1        ┆ Le Fay, Monika,           ┆ jn20010601270     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2011 ┆ 8     │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1989 ┆ 139   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 124   │
│ 1        ┆ Haňavec, Ladislav         ┆ jx20080526015     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1961 ┆ 114   │
│ 1        ┆ Hašek, Jaroslav,          ┆ jk01040097        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1973 ┆ 155   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 110   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2013 ┆ 239   │
│ 1        ┆ Twain, Mark,              ┆ jn19981002263     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 169   │
│ 1        ┆ Stehlíková, Blanka,       ┆ jk01121022        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1988 ┆ 134   │
│ 1        ┆ Rolleczek, Natalia,       ┆ kup20020000083748 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1977 ┆ 106   │
│ 1        ┆ Steklač, Vojtěch,         ┆ jk01121138        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 266   │
│ 1        ┆ Gordon, Richard,          ┆ jn20000602113     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2011 ┆ 245   │
│ 1        ┆ Erben, Karel Jaromír,     ┆ jk01030532        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1989 ┆ 243   │
│ 1        ┆ Gregor, Achille,          ┆ jk01032611        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1988 ┆ 381   │
│ 1        ┆ McCullers, Carson,        ┆ jn20000603964     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1965 ┆ 249   │
│ 1        ┆ Neff, Vladimír,           ┆ jk01082908        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1984 ┆ 348   │
│ 1        ┆ Havlíček Borovský, Karel, ┆ jk01040361        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 36    │
│ 1        ┆ Steklač, Vojtěch,         ┆ jk01121138        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 225   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 151   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 255   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 92    │
│ 1        ┆ Twain, Mark,              ┆ jn19981002263     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 56    │
│ 1        ┆ Twain, Mark,              ┆ jn19981002263     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 56    │
│ 1        ┆ Horelová, Eliška,         ┆ jk01042181        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1985 ┆ 287   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 157   │
│ 1        ┆ Sýkora, Pavel,            ┆ xx0008401         ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 223   │
│ 1        ┆ Klaus, Václav,            ┆ jn19990218045     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1996 ┆ 390   │
│ …        ┆ …                         ┆ …                 ┆ …              ┆ … ┆ …         ┆ …         ┆ …    ┆ …     │
│ 1        ┆ Steklač, Vojtěch,         ┆ jk01121138        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 197   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 148   │
│ 1        ┆ Pavel, Ota,               ┆ jk01092027        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1989 ┆ 269   │
│ 1        ┆ Slabý, Zdeněk Karel,      ┆ jk01111713        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1972 ┆ 30    │
│ 1        ┆ Hrnčíř, Svatopluk,        ┆ jk01042788        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 54    │
│ 1        ┆ Marshall, Alan,           ┆ jn20000603908     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1972 ┆ 253   │
│ 1        ┆ Říha, Bohumil,            ┆ jk01110164        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 171   │
│ 1        ┆ Dumas, Alexandre,         ┆ jn19990001907     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 624   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2018 ┆ 12    │
│ 1        ┆ Vodičková, Jarmila        ┆ null              ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 28    │
│ 1        ┆ Svěrák, Zdeněk,           ┆ jk01121890        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 45    │
│ 1        ┆ Lindgren, Astrid,         ┆ jn19990005095     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 270   │
│ 1        ┆ Poberová, Slávka,         ┆ jk01100162        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1996 ┆ 67    │
│ 1        ┆ Brecht, Bertolt,          ┆ jn19990001059     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1965 ┆ 105   │
│ 1        ┆ Hurník, Ilja,             ┆ jn19990209280     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 52    │
│ 1        ┆ Doyle, Arthur Conan,      ┆ jn19990001842     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 253   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 117   │
│ 1        ┆ Hercíková, Iva,           ┆ jk01040797        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 101   │
│ 1        ┆ Kravetz, Nathan           ┆ xx0178055         ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1983 ┆ 60    │
│ 1        ┆ Fialová, Juliana Anna,    ┆ jk01031044        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1984 ┆ 284   │
│ 1        ┆ Frýbová, Zdena,           ┆ jk01032058        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 237   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2011 ┆ 303   │
│ 1        ┆ Skála, Miroslav,          ┆ jk01111431        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1986 ┆ 190   │
│ 1        ┆ Kraus, Ivan,              ┆ jn19981001677     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 395   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 124   │
│ 1        ┆ Šotola, Jiří,             ┆ jk01130767        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1984 ┆ 326   │
│ 1        ┆ Bendl Stránický, Václav   ┆ jk01011548        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1985 ┆ 29    │
│          ┆ Čeněk,                    ┆                   ┆                ┆   ┆           ┆           ┆      ┆       │
│ 1        ┆ Steklač, Vojtěch,         ┆ jk01121138        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1989 ┆ 379   │
│ 1        ┆ Branald, Adolf,           ┆ jk01012955        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1990 ┆ 302   │
│ 1        ┆ Saltykov-Ščedrin, Michail ┆ jn19990210552     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1976 ┆ 254   │
│          ┆ Jevg…                     ┆                   ┆                ┆   ┆           ┆           ┆      ┆       │
│ 1        ┆ Lindgren, Astrid,         ┆ jn19990005095     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 270   │
│ 1        ┆ Barnes, Pauline           ┆ null              ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1994 ┆ 24    │
│ 1        ┆ Frýbová, Zdena,           ┆ jk01032058        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 195   │
│ 0        ┆ Klaret,                   ┆ jk01060290        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1991 ┆ 106   │
│ 1        ┆ La Fontaine, Jean de,     ┆ jn19990004795     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 588   │
│ 1        ┆ Pitlík, Josef             ┆ jk01093252        ┆ ["com"]        ┆ … ┆ null      ┆ null      ┆ 1974 ┆ 93    │
│ 1        ┆ Havlíková, Helena         ┆ jo2003197041      ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 56    │
│ 1        ┆ Lindgren, Astrid,         ┆ jn19990005095     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 263   │
│ 1        ┆ Steklač, Vojtěch,         ┆ jk01121138        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 214   │
│ 1        ┆ Svěrák, Zdeněk,           ┆ jk01121890        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 45    │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1990 ┆ 88    │
│ 1        ┆ Lindgren, Astrid,         ┆ jn19990005095     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 270   │
│ 1        ┆ Steklač, Vojtěch,         ┆ jk01121138        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1985 ┆ 304   │
│ 1        ┆ Žáček, Jiří,              ┆ jk01152946        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 117   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 157   │
│ 1        ┆ Holcová, Milena,          ┆ jn99240000298     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 179   │
│ 1        ┆ Macourek, Miloš,          ┆ jk01072813        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 157   │
│ 1        ┆ Saltykov-Ščedrin, Michail ┆ jn19990210552     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1974 ┆ 334   │
│          ┆ Jevg…                     ┆                   ┆                ┆   ┆           ┆           ┆      ┆       │
│ 1        ┆ Šmíd, Zdeněk,             ┆ jn19990209873     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 181   │
│ 1        ┆ Holoubek, Jaroslav,       ┆ jk01041772        ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1990 ┆ 122   │
└──────────┴───────────────────────────┴───────────────────┴────────────────┴───┴───────────┴───────────┴──────┴───────┘

In [59]:
df.filter(pl.col('700_4') == 'ill').group_by('700_a').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (13_657, 2)
┌──────────────────────────┬───────┐
│ 700_a                    ┆ 245_a │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ Born, Adolf,             ┆ 281   │
│ Burian, Zdeněk,          ┆ 230   │
│ Němeček, Jaroslav,       ┆ 179   │
│ Bouda, Cyril,            ┆ 166   │
│ Zmatlíková, Helena,      ┆ 164   │
│ Winter-Neprakta, Jiří,   ┆ 160   │
│ Krejčová, Zdeňka,        ┆ 159   │
│ Šplíchal, Antonín,       ┆ 143   │
│ Thuma, Karel Ladislav,   ┆ 134   │
│ Černý, Věnceslav,        ┆ 133   │
│ Vydrová, Markéta,        ┆ 128   │
│ Plicková, Edita,         ┆ 124   │
│ Svolinský, Karel,        ┆ 123   │
│ Študlarová, Zdeňka,      ┆ 122   │
│ Lada, Josef,             ┆ 122   │
│ Aleš, Mikoláš,           ┆ 119   │
│ Petráček, Jiří,          ┆ 108   │
│ Popprová, Andrea         ┆ 103   │
│ Lhoták, Kamil,           ┆ 99    │
│ Scheiner, Artuš,         ┆ 97    │
│ Slíva, Jiří,             ┆ 93    │
│ Jiránek, Vladimír,       ┆ 88    │
│ Trnka, Jiří,             ┆ 87    │
│ Janeček, Ota,            ┆ 85    │
│ Čuma, Aleš,              ┆ 85    │
│ Hegerová, Vendula,       ┆ 84    │
│ Jakešová, Miroslava,     ┆ 84    │
│ Wowk, Jiří,              ┆ 80    │
│ Schulz, Alena,           ┆ 80    │
│ Tesař, Vladimír,         ┆ 79    │
│ Martenek, Miloslav,      ┆ 78    │
│ Velčovský, Josef,        ┆ 78    │
│ Fixl, Jiří,              ┆ 78    │
│ Čutta, Václav,           ┆ 76    │
│ Procházka, Otakar        ┆ 76    │
│ Kubašta, Vojtěch,        ┆ 75    │
│ Teissig, Karel,          ┆ 75    │
│ Škoda, František,        ┆ 74    │
│ Kratochvíl, Zdeněk,      ┆ 74    │
│ Komárek, Vladimír,       ┆ 73    │
│ Hora, Jan,               ┆ 70    │
│ Kabát, Václav,           ┆ 70    │
│ Poppr, Roman             ┆ 68    │
│ Renčín, Vladimír,        ┆ 68    │
│ Čapek, Josef,            ┆ 68    │
│ Netopil, Zdeněk,         ┆ 66    │
│ Franta, Karel,           ┆ 66    │
│ Urban, Petr,             ┆ 66    │
│ Konůpek, Jan,            ┆ 65    │
│ Kalousek, Jiří,          ┆ 65    │
│ …                        ┆ …     │
│ Chew, Camille            ┆ 1     │
│ Krausová, Edita,         ┆ 1     │
│ Eliáš, Jaroslav          ┆ 1     │
│ Frait, Jiří,             ┆ 1     │
│ Škaroupka, Vladimír,     ┆ 1     │
│ Barrow, Alex             ┆ 1     │
│ Murata, Yusuke,          ┆ 1     │
│ Sacré, Florent,          ┆ 1     │
│ Callixte                 ┆ 1     │
│ Zemanovič, Karol         ┆ 1     │
│ Šalamounová, Eva         ┆ 1     │
│ Čajka, Jirka             ┆ 1     │
│ Štojdl, Michael,         ┆ 1     │
│ Vyskočil, Miloš          ┆ 1     │
│ Pešlová, Lucie           ┆ 1     │
│ Raad, Madeleine van der, ┆ 1     │
│ Kratochvílová, Marie,    ┆ 1     │
│ Pavel, Pavel,            ┆ 1     │
│ Vystrčil, Otakar,        ┆ 1     │
│ Ford, Wayne              ┆ 1     │
│ Gosling, Livi            ┆ 1     │
│ Naldi, Martina           ┆ 1     │
│ Heinzová, Věra           ┆ 1     │
│ Titěra, Dalibor,         ┆ 1     │
│ Bego, Benson Avea,       ┆ 1     │
│ Cejtlina, N.             ┆ 1     │
│ Fila, Roman              ┆ 1     │
│ Girouard, Patrick,       ┆ 1     │
│ Runk, Ferdinand,         ┆ 1     │
│ Cupples, Pat             ┆ 1     │
│ Bažantová, Nina          ┆ 1     │
│ Skrepl, Vladimír,        ┆ 1     │
│ Grecová, Krista          ┆ 1     │
│ Sinding, Otto,           ┆ 1     │
│ Lyddon, Emma             ┆ 1     │
│ Táborský, František,     ┆ 1     │
│ Mayer, Peretz Béda,      ┆ 1     │
│ Weiselová, Jitka         ┆ 1     │
│ Kříhová, Kateřina        ┆ 1     │
│ Alran, Pierre            ┆ 1     │
│ Person, Sebastian        ┆ 1     │
│ Tichá, Lucie,            ┆ 1     │
│ Billerová, Taťána        ┆ 1     │
│ Hanuš, Dorian,           ┆ 1     │
│ Ziebiker, Eduard         ┆ 1     │
│ Jansen, Maan,            ┆ 1     │
│ Weidner, Zdeněk,         ┆ 1     │
│ Rébera, László           ┆ 1     │
│ Koplová, Marie,          ┆ 1     │
│ Bielecki, Jiří,          ┆ 1     │
└──────────────────────────┴───────┘

In [60]:
df_preklady = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","041.parquet")), left_on="001", right_on="001", how="left")

In [61]:
df_preklady.filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (18_202, 2)
┌─────────────────────────────────┬───────┐
│ 700_a                           ┆ 245_a │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Butala, Tomáš,                  ┆ 502   │
│ Pavka, Marek,                   ┆ 429   │
│ Vyskočil, Josef                 ┆ 344   │
│ Sladká, Stanislava              ┆ 246   │
│ Schönová, Zuzana                ┆ 234   │
│ Volhejnová, Veronika,           ┆ 230   │
│ Podaný, Richard,                ┆ 224   │
│ Kuťák, Jaroslav,                ┆ 214   │
│ Chromiaková, Eva                ┆ 196   │
│ Pacnerová, Jana,                ┆ 195   │
│ Štorkánová, Anna,               ┆ 179   │
│ Klůfová, Petra,                 ┆ 164   │
│ Jašová, Jana,                   ┆ 163   │
│ Dušek, Zdík,                    ┆ 155   │
│ Kadlecová, Eva,                 ┆ 148   │
│ Řežábek, Rudolf,                ┆ 140   │
│ Pokorný, Martin,                ┆ 140   │
│ Lacinová, Libuše,               ┆ 140   │
│ Dvořáková, Dagmar               ┆ 134   │
│ Kantůrek, Jan,                  ┆ 130   │
│ Smolaková, Helena               ┆ 127   │
│ Kozák, Jan,                     ┆ 126   │
│ Sychra, Pavel                   ┆ 122   │
│ Führmann Vízdalová, Ivana,      ┆ 119   │
│ Jovanovičová, Hana,             ┆ 118   │
│ Stach, Jiří,                    ┆ 117   │
│ Kufnerová, Zlata,               ┆ 117   │
│ Stachová, Helena,               ┆ 117   │
│ Škultéty, Michaela,             ┆ 112   │
│ Žáček, Milan,                   ┆ 111   │
│ Niklíčková, Alexandra,          ┆ 109   │
│ Somogyi, Viola,                 ┆ 107   │
│ Vlčková, Jana,                  ┆ 107   │
│ Weinfurter, Karel,              ┆ 106   │
│ Diestlerová, Petra,             ┆ 104   │
│ Krejčí, Hana                    ┆ 102   │
│ Heller, František               ┆ 102   │
│ Nuhlíčková, Ivana,              ┆ 102   │
│ Vinšová, Kateřina,              ┆ 102   │
│ Hradil, Radomil,                ┆ 99    │
│ Brožová, Eva                    ┆ 98    │
│ Faltejsková, Lenka,             ┆ 98    │
│ Schuster, R. K.                 ┆ 95    │
│ Morávková, Alena,               ┆ 93    │
│ Žák, Jiří,                      ┆ 92    │
│ Rada, Jan                       ┆ 92    │
│ Chodilová, Dana,                ┆ 92    │
│ Novotná, Jana,                  ┆ 92    │
│ Zábrana, Jan,                   ┆ 91    │
│ Křivánková, Anna,               ┆ 89    │
│ …                               ┆ …     │
│ Spoustová, Eva,                 ┆ 1     │
│ Císařová-Kolářová, Anna,        ┆ 1     │
│ Peisertová, Jana                ┆ 1     │
│ Forejt, Matěj,                  ┆ 1     │
│ Mauermann, Zdeněk,              ┆ 1     │
│ Stibor, Jan                     ┆ 1     │
│ Volf, Štěpán,                   ┆ 1     │
│ Chumová, Eva                    ┆ 1     │
│ Voců, Anna                      ┆ 1     │
│ Hajný, Petr                     ┆ 1     │
│ Bočánková, Milena,              ┆ 1     │
│ Ocisková, Marie                 ┆ 1     │
│ Nigrin, Jaromír,                ┆ 1     │
│ Kylarová, Dagmar                ┆ 1     │
│ Krouská Kanayama, Misako,       ┆ 1     │
│ Halášková, Lucie                ┆ 1     │
│ Krejčí, Jaromír,                ┆ 1     │
│ Beran, Vilém                    ┆ 1     │
│ Engel, Přemysl                  ┆ 1     │
│ Podlipský, Josef,               ┆ 1     │
│ Valenta, Petr                   ┆ 1     │
│ Bukáčková, Kateřina Beáta,      ┆ 1     │
│ Hajdovský, Vladimír             ┆ 1     │
│ Vodehnal, Jan,                  ┆ 1     │
│ Kurková, Monika                 ┆ 1     │
│ Kouble, Josef,                  ┆ 1     │
│ Zeman, Karel                    ┆ 1     │
│ Burian, Jiří,                   ┆ 1     │
│ Tesařová, Helena                ┆ 1     │
│ Helebrant, Martin,              ┆ 1     │
│ Valoch, Karel,                  ┆ 1     │
│ Mrázová, Milada                 ┆ 1     │
│ Shöenfelt, Phil,                ┆ 1     │
│ Jaurisová, Blanka               ┆ 1     │
│ Makovský, Josef                 ┆ 1     │
│ Kotačková, Šárka                ┆ 1     │
│ Audyová, Soňa                   ┆ 1     │
│ Fafejtová, Klára,               ┆ 1     │
│ Havlů, Tatjana                  ┆ 1     │
│ Růžička, Otto                   ┆ 1     │
│ Špičková, Martina               ┆ 1     │
│ Rektorisová, Klementina,        ┆ 1     │
│ Holub, Tomáš                    ┆ 1     │
│ Zimová, Jitka                   ┆ 1     │
│ Kunešová, Hana                  ┆ 1     │
│ Andrýsková, Iva                 ┆ 1     │
│ Fischer, Ondřej,                ┆ 1     │
│ Vasil‘jev, Nikolaj Vladimirovi… ┆ 1     │
│ Turek, Rudolf                   ┆ 1     │
│ Berka, Vít                      ┆ 1     │
└─────────────────────────────────┴───────┘

In [62]:
df_preklady.filter(pl.col('700_a') == "Butala, Tomáš,").group_by("100_a").len()

shape: (33, 2)
┌────────────────────────────┬─────┐
│ 100_a                      ┆ len │
│ ---                        ┆ --- │
│ str                        ┆ u32 │
╞════════════════════════════╪═════╡
│ Taylor, Kathryn            ┆ 3   │
│ Aurel, Catherine,          ┆ 1   │
│ Goga-Klinkenberg, Susanne, ┆ 4   │
│ Unger, Gert F.,            ┆ 391 │
│ Roberts, Dan,              ┆ 1   │
│ Ryan, William              ┆ 4   │
│ Murphy, Bill,              ┆ 10  │
│ Denver, Jeff,              ┆ 1   │
│ Schröder, Rainer M.,       ┆ 1   │
│ Gringel, Dana,             ┆ 1   │
│ Warner, Hal,               ┆ 1   │
│ Silva, Tony,               ┆ 1   │
│ Fargo, Bill                ┆ 4   │
│ Bellmar, Elena,            ┆ 2   │
│ Hayes, Rex,                ┆ 13  │
│ Morton, Jack               ┆ 7   │
│ Vermalle, Caroline,        ┆ 1   │
│ Robertson, Frank C.        ┆ 2   │
│ Glaser, Frank              ┆ 9   │
│ Engel, Cornelia            ┆ 1   │
│ Sinclair, Luke             ┆ 8   │
│ Czernin, Monika,           ┆ 1   │
│ Kutscher, Volker,          ┆ 10  │
│ Morgan, Matt               ┆ 4   │
│ Callahan, Frank            ┆ 2   │
│ Arnaldur Indriðason,       ┆ 5   │
│ Shannon, Mark              ┆ 1   │
│ Schiewe, Ulf,              ┆ 1   │
│ Lane, Lex                  ┆ 4   │
│ Sharon, H. S.              ┆ 3   │
│ Mortimer, Glenn            ┆ 4   │
│ Benson, Robert             ┆ 2   │
│ Scott, William,            ┆ 141 │
└────────────────────────────┴─────┘

In [63]:
df_preklady.filter(pl.col('700_a') == "Butala, Tomáš,").group_by("041_h").len()

shape: (5, 2)
┌───────────┬─────┐
│ 041_h     ┆ len │
│ ---       ┆ --- │
│ list[str] ┆ u32 │
╞═══════════╪═════╡
│ ["ice"]   ┆ 5   │
│ ["fre"]   ┆ 1   │
│ null      ┆ 2   │
│ ["ger"]   ┆ 633 │
│ ["eng"]   ┆ 3   │
└───────────┴─────┘

In [64]:
df_preklady.filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (18_202, 2)
┌─────────────────────────────────┬───────┐
│ 700_a                           ┆ 245_a │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Butala, Tomáš,                  ┆ 502   │
│ Pavka, Marek,                   ┆ 429   │
│ Vyskočil, Josef                 ┆ 344   │
│ Sladká, Stanislava              ┆ 246   │
│ Schönová, Zuzana                ┆ 234   │
│ Volhejnová, Veronika,           ┆ 230   │
│ Podaný, Richard,                ┆ 224   │
│ Kuťák, Jaroslav,                ┆ 214   │
│ Chromiaková, Eva                ┆ 196   │
│ Pacnerová, Jana,                ┆ 195   │
│ Štorkánová, Anna,               ┆ 179   │
│ Klůfová, Petra,                 ┆ 164   │
│ Jašová, Jana,                   ┆ 163   │
│ Dušek, Zdík,                    ┆ 155   │
│ Kadlecová, Eva,                 ┆ 148   │
│ Řežábek, Rudolf,                ┆ 140   │
│ Pokorný, Martin,                ┆ 140   │
│ Lacinová, Libuše,               ┆ 140   │
│ Dvořáková, Dagmar               ┆ 134   │
│ Kantůrek, Jan,                  ┆ 130   │
│ Smolaková, Helena               ┆ 127   │
│ Kozák, Jan,                     ┆ 126   │
│ Sychra, Pavel                   ┆ 122   │
│ Führmann Vízdalová, Ivana,      ┆ 119   │
│ Jovanovičová, Hana,             ┆ 118   │
│ Stach, Jiří,                    ┆ 117   │
│ Kufnerová, Zlata,               ┆ 117   │
│ Stachová, Helena,               ┆ 117   │
│ Škultéty, Michaela,             ┆ 112   │
│ Žáček, Milan,                   ┆ 111   │
│ Niklíčková, Alexandra,          ┆ 109   │
│ Vlčková, Jana,                  ┆ 107   │
│ Somogyi, Viola,                 ┆ 107   │
│ Weinfurter, Karel,              ┆ 106   │
│ Diestlerová, Petra,             ┆ 104   │
│ Vinšová, Kateřina,              ┆ 102   │
│ Heller, František               ┆ 102   │
│ Krejčí, Hana                    ┆ 102   │
│ Nuhlíčková, Ivana,              ┆ 102   │
│ Hradil, Radomil,                ┆ 99    │
│ Faltejsková, Lenka,             ┆ 98    │
│ Brožová, Eva                    ┆ 98    │
│ Schuster, R. K.                 ┆ 95    │
│ Morávková, Alena,               ┆ 93    │
│ Rada, Jan                       ┆ 92    │
│ Žák, Jiří,                      ┆ 92    │
│ Chodilová, Dana,                ┆ 92    │
│ Novotná, Jana,                  ┆ 92    │
│ Zábrana, Jan,                   ┆ 91    │
│ Křivánková, Anna,               ┆ 89    │
│ …                               ┆ …     │
│ Janeček, Pavel                  ┆ 1     │
│ Žovnìrovič, Anastasìja Vasylìv… ┆ 1     │
│ Pazderka, Petr                  ┆ 1     │
│ Kúchová, Eva                    ┆ 1     │
│ Tauc, Anna                      ┆ 1     │
│ Galeta, Jan,                    ┆ 1     │
│ Štěrba, Oldřich,                ┆ 1     │
│ Adalbert, Alois,                ┆ 1     │
│ Salař, Josef                    ┆ 1     │
│ Král, Alois                     ┆ 1     │
│ Schwarzová, Jiřina              ┆ 1     │
│ Hrabětová, Kateřina             ┆ 1     │
│ Hroch, Miroslav,                ┆ 1     │
│ Pacholík, Radoslav,             ┆ 1     │
│ Inževatkin, Michal              ┆ 1     │
│ Macková, Milena                 ┆ 1     │
│ Dvořák, Dalimil,                ┆ 1     │
│ Seidlová, Jarmila               ┆ 1     │
│ Hrašková, Zuzana                ┆ 1     │
│ Petr z Vlkova                   ┆ 1     │
│ Hanák, Svetozár                 ┆ 1     │
│ Ducháček, Milan,                ┆ 1     │
│ Vrba, Martin                    ┆ 1     │
│ Rozov, Michaela,                ┆ 1     │
│ Vavrušková, Marie               ┆ 1     │
│ Falvey, Christian               ┆ 1     │
│ Dokládal, Petr,                 ┆ 1     │
│ Melen, Dušan                    ┆ 1     │
│ Ruml, Vladimír,                 ┆ 1     │
│ Vavrušková, Gabriela            ┆ 1     │
│ Hniličková, Jana B.             ┆ 1     │
│ Voborník, Jan,                  ┆ 1     │
│ Sobotková, Marie,               ┆ 1     │
│ Susová, Zdena                   ┆ 1     │
│ Havlová, Veronika               ┆ 1     │
│ Panuška, František,             ┆ 1     │
│ Rešetka, Dušan                  ┆ 1     │
│ Nová, Olga                      ┆ 1     │
│ Lencová, Bohumila,              ┆ 1     │
│ Pasz, David                     ┆ 1     │
│ Soumar, Libor,                  ┆ 1     │
│ Holubcová, B.                   ┆ 1     │
│ Žůrek, Jiří,                    ┆ 1     │
│ Nečas, Tomáš                    ┆ 1     │
│ Štěpánek, Petr,                 ┆ 1     │
│ Hánová, Kamila                  ┆ 1     │
│ Ziech, Petra                    ┆ 1     │
│ Matička, Vladimír               ┆ 1     │
│ Macák, Marek                    ┆ 1     │
│ Dostrašilová, Marta             ┆ 1     │
└─────────────────────────────────┴───────┘

In [65]:
df_preklady.filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("stran").sum()).sort(by="stran",descending=True)

shape: (18_202, 2)
┌─────────────────────────────────┬────────┐
│ 700_a                           ┆ stran  │
│ ---                             ┆ ---    │
│ str                             ┆ i64    │
╞═════════════════════════════════╪════════╡
│ Volhejnová, Veronika,           ┆ 104086 │
│ Pacnerová, Jana,                ┆ 90284  │
│ Kantůrek, Jan,                  ┆ 80551  │
│ Podaný, Richard,                ┆ 76323  │
│ Dušek, Zdík,                    ┆ 68870  │
│ Jašová, Jana,                   ┆ 66951  │
│ Klůfová, Petra,                 ┆ 66769  │
│ Chodilová, Dana,                ┆ 56060  │
│ Medek, Pavel,                   ┆ 54195  │
│ Bartošková, Linda,              ┆ 53632  │
│ Řežábek, Rudolf,                ┆ 51852  │
│ Kobělka, Jiří,                  ┆ 50248  │
│ Pokorný, Martin,                ┆ 49472  │
│ Butala, Tomáš,                  ┆ 48256  │
│ Hron, Zdeněk,                   ┆ 45346  │
│ Zaorálek, Jaroslav,             ┆ 44751  │
│ Kotrle, Petr,                   ┆ 44222  │
│ Führmann Vízdalová, Ivana,      ┆ 43707  │
│ Krejčová, Dana                  ┆ 43672  │
│ Kozák, Jan,                     ┆ 43670  │
│ Faltejsková, Lenka,             ┆ 42989  │
│ Kadlecová, Eva,                 ┆ 42772  │
│ Trávníček, Luboš,               ┆ 42489  │
│ Kondrysová, Eva,                ┆ 41792  │
│ Ľalíková, Zuzana,               ┆ 41569  │
│ Žáček, Milan,                   ┆ 41130  │
│ Krištůfková, Kateřina,          ┆ 40202  │
│ Medek, Vladimír,                ┆ 39526  │
│ Jindrová, Alena,                ┆ 37979  │
│ Míček, Dalibor,                 ┆ 37961  │
│ Křivánková, Anna,               ┆ 37329  │
│ Trávníčková, Libuše,            ┆ 37257  │
│ Zábrana, Jan,                   ┆ 36956  │
│ Vlčková, Jana,                  ┆ 36700  │
│ Brožová, Eva                    ┆ 36699  │
│ Heller, František               ┆ 35764  │
│ Houbová, Věra,                  ┆ 35662  │
│ Moserová, Jaroslava,            ┆ 35535  │
│ Žák, Jiří,                      ┆ 35332  │
│ Weinfurter, Karel,              ┆ 34763  │
│ Stárková, Jiřina                ┆ 34565  │
│ Wolfová, Zora,                  ┆ 34555  │
│ Bičíková, Romana,               ┆ 34245  │
│ Křístková, Eva                  ┆ 34049  │
│ Nuhlíčková, Ivana,              ┆ 33785  │
│ Tilsch, Emanuel,                ┆ 33415  │
│ Marková, Michala,               ┆ 33354  │
│ Niklíčková, Alexandra,          ┆ 33232  │
│ Jindra, Miroslav,               ┆ 32742  │
│ Dvořák, Libor,                  ┆ 32490  │
│ …                               ┆ …      │
│ Novotná, Eliška                 ┆ 1      │
│ Ponešová, Anita,                ┆ 1      │
│ Vavruška, Jindřich              ┆ 1      │
│ Kaszonyi, Pavol                 ┆ 1      │
│ Žovnìrovič, Anastasìja Vasylìv… ┆ 1      │
│ Lukaštíková, Julie,             ┆ 1      │
│ Fošum, Lukáš Jan,               ┆ 1      │
│ Horníková, Pavlína              ┆ 1      │
│ Maruščak, Marija Tarasivna      ┆ 1      │
│ Phamová, Hau,                   ┆ 1      │
│ Čadková, Daniela,               ┆ 1      │
│ Jiřičková, Marie,               ┆ 1      │
│ Kim, Mina                       ┆ 1      │
│ Trnka, Jakub                    ┆ 1      │
│ Marx, Jakub                     ┆ 1      │
│ Rudčenková, Kateřina,           ┆ 1      │
│ Burjak, Marta Igorìvna          ┆ 1      │
│ Austová, Veronika               ┆ 1      │
│ Zoban, Petr,                    ┆ 1      │
│ Geislerová, Gabriela            ┆ 1      │
│ Tenaud, Guillaume,              ┆ 1      │
│ Jelínek, Konstantin,            ┆ 1      │
│ Ivancìv, Galyna Volodymyrìvna   ┆ 1      │
│ Mostova, Julìja Mykolajivna     ┆ 1      │
│ Božek, Tomáš                    ┆ 1      │
│ Maršálek, Zdenko,               ┆ 1      │
│ Pelc, Vojtěch                   ┆ 1      │
│ Berlad, Iryna Dmytrivna         ┆ 1      │
│ Tauchmanová, Věra,              ┆ 1      │
│ Škňouřil, Evžen,                ┆ 1      │
│ Žůrek, Jiří,                    ┆ 1      │
│ Horáček, Pavel,                 ┆ 1      │
│ Rohoža, Anna Vìktorìvna         ┆ 1      │
│ Hofman, Petr,                   ┆ 1      │
│ Matička, Vladimír               ┆ 1      │
│ Kadlecová, Ester,               ┆ 1      │
│ Kohnerová, Lucie                ┆ 1      │
│ Paraiová, Pavlína               ┆ 1      │
│ Metličková, Kristýna            ┆ 1      │
│ Petrunìna, Julìja Andrìjivna    ┆ 1      │
│ Irena                           ┆ 1      │
│ Savčyn, Marìja-Mar'jana Volody… ┆ 1      │
│ Ochmanová, Taťána               ┆ 1      │
│ Majer, Petr,                    ┆ 1      │
│ Čech, Radek,                    ┆ 1      │
│ Desenská Ciglerová, Jana        ┆ 1      │
│ Malicki, Jarosław               ┆ 1      │
│ Velká, Tereza                   ┆ 1      │
│ Prentis, Thomas                 ┆ 1      │
│ Maxová, Pavla                   ┆ 1      │
└─────────────────────────────────┴────────┘

In [66]:
df_preklady.filter(pl.col('700_a') == "Volhejnová, Veronika,").group_by("100_a").len().sort(by="len",descending=True)

shape: (106, 2)
┌────────────────────────┬─────┐
│ 100_a                  ┆ len │
│ ---                    ┆ --- │
│ str                    ┆ u32 │
╞════════════════════════╪═════╡
│ Kinney, Jeff,          ┆ 52  │
│ Christie, Agatha,      ┆ 29  │
│ Herbert, Frank,        ┆ 24  │
│ Lewis, C. S.           ┆ 21  │
│ Walliams, David,       ┆ 21  │
│ Green, John,           ┆ 17  │
│ Colfer, Chris,         ┆ 16  │
│ Le Carré, John,        ┆ 8   │
│ Morse, Brian,          ┆ 7   │
│ Grisham, John,         ┆ 6   │
│ Hannah, Sophie,        ┆ 6   │
│ Cunningham, Michael,   ┆ 5   │
│ Atkinson, Kate,        ┆ 5   │
│ Eason, Cassandra,      ┆ 5   │
│ Russell, Rachel Renée  ┆ 4   │
│ Andrews, William W.    ┆ 4   │
│ Peters, Helen          ┆ 4   │
│ Piers, Helen           ┆ 4   │
│ Daldry, Jeremy,        ┆ 4   │
│ Clarke, Arthur C.      ┆ 4   │
│ Barnes, Jennifer Lynn, ┆ 3   │
│ Novik, Naomi,          ┆ 3   │
│ Allison, Jennifer,     ┆ 3   │
│ Herbert, Brian,        ┆ 3   │
│ Asimov, Isaac,         ┆ 3   │
│ Smith, James,          ┆ 3   │
│ Brown, Sandra,         ┆ 3   │
│ Anderson, Poul,        ┆ 3   │
│ Lamb, Kathryn,         ┆ 3   │
│ Crichton, Michael,     ┆ 3   │
│ Colfer, Eoin,          ┆ 3   │
│ King, Andrew           ┆ 2   │
│ Crouch, Blake,         ┆ 2   │
│ Smale, Holly,          ┆ 2   │
│ Chee, Traci            ┆ 2   │
│ McKinlay, Deborah      ┆ 2   │
│ Kalfař, Jaroslav,      ┆ 2   │
│ Kaplický, Jan,         ┆ 2   │
│ Mercree, Amy Leigh,    ┆ 2   │
│ Levin, Ira,            ┆ 2   │
│ Johansen, Erika        ┆ 2   │
│ Twain, Mark,           ┆ 2   │
│ Rich, Roberta,         ┆ 2   │
│ Thomson, Jamie,        ┆ 2   │
│ Adeyemi, Tomi,         ┆ 2   │
│ George, Elizabeth,     ┆ 2   │
│ Cornell, Paul,         ┆ 1   │
│ Piedilato, Janet       ┆ 1   │
│ Larwood, Kieran        ┆ 1   │
│ Brooks, Kevin,         ┆ 1   │
│ …                      ┆ …   │
│ Koontz, Dean R.        ┆ 1   │
│ Laurie, Meshel,        ┆ 1   │
│ Josephs, Ray           ┆ 1   │
│ Setterfield, Diane,    ┆ 1   │
│ Graham, Caroline,      ┆ 1   │
│ Pessl, Marisha,        ┆ 1   │
│ La Fontaine, Jean de,  ┆ 1   │
│ Hubbard, L. Ron        ┆ 1   │
│ Neubauer, Bonnie       ┆ 1   │
│ Extence, Gavin,        ┆ 1   │
│ Cooper, Rose           ┆ 1   │
│ Anderson, Kevin J.,    ┆ 1   │
│ Hedsel, Mark,          ┆ 1   │
│ Walls, Jeannette,      ┆ 1   │
│ Selden, George,        ┆ 1   │
│ Peterson, Jordan B.,   ┆ 1   │
│ Abrams, Stacey,        ┆ 1   │
│ Lee, Suh Yoon          ┆ 1   │
│ Kuttner, Henry,        ┆ 1   │
│ Winterson, Jeanette,   ┆ 1   │
│ Durrant, Sabine        ┆ 1   │
│ Bryant, Dani           ┆ 1   │
│ Kissick, Lucy          ┆ 1   │
│ Arnold, Stephanie      ┆ 1   │
│ Donoghue, Emma,        ┆ 1   │
│ Flinn, Alex,           ┆ 1   │
│ Mendell, Adrienne      ┆ 1   │
│ Cornelius, Geoffrey    ┆ 1   │
│ Quirk, Lawrence J.,    ┆ 1   │
│ Poe, Edgar Allan,      ┆ 1   │
│ Pollard, Michael,      ┆ 1   │
│ Oula, Valerie          ┆ 1   │
│ Kvítek, Martin,        ┆ 1   │
│ Fuller, Claire,        ┆ 1   │
│ Levithan, David,       ┆ 1   │
│ Matheson, Richard,     ┆ 1   │
│ Nelson, Jandy,         ┆ 1   │
│ Garber, Joseph R.,     ┆ 1   │
│ Hearne, Kevin,         ┆ 1   │
│ Reed, Henry,           ┆ 1   │
│ McIntyre, Anne,        ┆ 1   │
│ Shaheen, Michael A.    ┆ 1   │
│ Zhang, Amy,            ┆ 1   │
│ Jerome, Jerome K.      ┆ 1   │
│ Hornak, Francesca      ┆ 1   │
│ Delany, Samuel R.,     ┆ 1   │
│ Kowitt, Holly          ┆ 1   │
│ Forleo, Marie          ┆ 1   │
│ Moore, Alan,           ┆ 1   │
│ Marshall, David        ┆ 1   │
└────────────────────────┴─────┘

In [67]:
df_preklady.explode("041_h").filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("041_h").n_unique()).sort(by="041_h",descending=True)

shape: (18_202, 2)
┌────────────────────────────────┬───────┐
│ 700_a                          ┆ 041_h │
│ ---                            ┆ ---   │
│ str                            ┆ u32   │
╞════════════════════════════════╪═══════╡
│ Babler, Otto František,        ┆ 19    │
│ Vetti, O. S.,                  ┆ 16    │
│ Hiršal, Josef,                 ┆ 16    │
│ Vrchlický, Jaroslav,           ┆ 12    │
│ Bednář, Kamil,                 ┆ 12    │
│ Žáček, Jiří,                   ┆ 11    │
│ Sýs, Karel,                    ┆ 11    │
│ Vladislav, Jan,                ┆ 11    │
│ Fischer, Otokar,               ┆ 11    │
│ Žilina, Miloslav,              ┆ 11    │
│ Kosterka, Hugo,                ┆ 11    │
│ Hrubín, František,             ┆ 10    │
│ Eisner, Pavel,                 ┆ 10    │
│ Karpatský, Dušan,              ┆ 9     │
│ Stankovský, Josef Jiří,        ┆ 9     │
│ Štroblová, Jana,               ┆ 9     │
│ Borecký, Jaromír,              ┆ 9     │
│ Hackenschmied, Hanuš,          ┆ 9     │
│ Vrátný, Karel,                 ┆ 8     │
│ Zbavitel, Dušan,               ┆ 8     │
│ Vacek, Jindřich,               ┆ 8     │
│ Mertlík, Rudolf,               ┆ 8     │
│ Čvančara, Karel,               ┆ 8     │
│ Pešková, Eliška,               ┆ 8     │
│ Kubišta, Luděk,                ┆ 8     │
│ Somogyi, Viola,                ┆ 8     │
│ Vyskočil, Josef                ┆ 8     │
│ Vrbová, Hana,                  ┆ 8     │
│ Kundera, Ludvík,               ┆ 8     │
│ Šádek, František,              ┆ 8     │
│ Mathesius, Bohumil,            ┆ 8     │
│ Novotný, Václav Juda,          ┆ 8     │
│ Pelán, Jiří,                   ┆ 8     │
│ Weinfurter, Karel,             ┆ 8     │
│ Sládek, Josef Václav,          ┆ 8     │
│ Závada, Vilém,                 ┆ 8     │
│ Pokorný, Jaroslav,             ┆ 8     │
│ Renč, Václav,                  ┆ 8     │
│ Krausová-Lesná, Milada,        ┆ 7     │
│ Frýbort, Zdeněk,               ┆ 7     │
│ Mattuš, Jan,                   ┆ 7     │
│ Koláček, Josef,                ┆ 7     │
│ Koněrza, Josef,                ┆ 7     │
│ Kühnl, Jan Baptist,            ┆ 7     │
│ Hrůša, Josef,                  ┆ 7     │
│ Tůma, Petr                     ┆ 7     │
│ Kunstovný, Otakar,             ┆ 7     │
│ Nowak, Antonín,                ┆ 7     │
│ Peisertová, Alena              ┆ 7     │
│ Škultéty, Michaela,            ┆ 7     │
│ …                              ┆ …     │
│ Kalinová, Milada,              ┆ 1     │
│ Smejtek, Pavel                 ┆ 1     │
│ Loukotka, František,           ┆ 1     │
│ Vágenknechtová Edrová, Pavlína ┆ 1     │
│ Hromková, Blanka               ┆ 1     │
│ Stingl, Josef,                 ┆ 1     │
│ Vyplel, Jaroslav,              ┆ 1     │
│ Fafejta, Martin,               ┆ 1     │
│ Vondroušková, Ljubov',         ┆ 1     │
│ Šustková, Pavla                ┆ 1     │
│ Kubů, František,               ┆ 1     │
│ Flídr, Jáchym                  ┆ 1     │
│ Anděrová, Romana,              ┆ 1     │
│ Bairovová, Gabriela            ┆ 1     │
│ Zemanová, Jana,                ┆ 1     │
│ Beránek, David                 ┆ 1     │
│ Novosad, Zdeněk                ┆ 1     │
│ Šabacká, Agnes                 ┆ 1     │
│ Tinková, Daniela,              ┆ 1     │
│ Suchardová, Věra               ┆ 1     │
│ Polák, Anton,                  ┆ 1     │
│ Zbořilová, Anna                ┆ 1     │
│ Sokolov, Vlad.                 ┆ 1     │
│ Seige, Viktor                  ┆ 1     │
│ Podlešáková, Štěpánka          ┆ 1     │
│ Jíchová, Eva                   ┆ 1     │
│ Nejedlý, Josef K.,             ┆ 1     │
│ Urban, Miloš,                  ┆ 1     │
│ Rybová, Lucie                  ┆ 1     │
│ Jelenová, Jarmila,             ┆ 1     │
│ Vengřenovský, Alex             ┆ 1     │
│ Eliášová, Kristýna             ┆ 1     │
│ Houdková, Jana                 ┆ 1     │
│ Silva-Taroucová, Gisela,       ┆ 1     │
│ R. K.                          ┆ 1     │
│ Čaněk, David                   ┆ 1     │
│ Baušteinová, Kateřina          ┆ 1     │
│ Drda, Vratislav Antonij        ┆ 1     │
│ Reinerová, Hana,               ┆ 1     │
│ Švejkovská, Tereza             ┆ 1     │
│ Šmerdová, Dagmar,              ┆ 1     │
│ Dušková, Elena,                ┆ 1     │
│ Dietiová, Karin                ┆ 1     │
│ Bambas, Gustav,                ┆ 1     │
│ Lakomý, Antonín,               ┆ 1     │
│ Jeřábek, Rudolf                ┆ 1     │
│ Dibble, Suzanne                ┆ 1     │
│ Sůvová, Zlatuše                ┆ 1     │
│ Mathé, Lukáš,                  ┆ 1     │
│ Škandera, R.                   ┆ 1     │
└────────────────────────────────┴───────┘

In [68]:
df_preklady.filter(pl.col('700_a') == "Babler, Otto František,").group_by('041_h').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (20, 2)
┌─────────────────────────┬───────┐
│ 041_h                   ┆ 245_a │
│ ---                     ┆ ---   │
│ list[str]               ┆ u32   │
╞═════════════════════════╪═══════╡
│ ["eng"]                 ┆ 10    │
│ ["ger"]                 ┆ 9     │
│ ["fre"]                 ┆ 8     │
│ ["scr"]                 ┆ 5     │
│ null                    ┆ 5     │
│ ["hrv"]                 ┆ 3     │
│ ["ita"]                 ┆ 3     │
│ ["bul"]                 ┆ 2     │
│ ["lat"]                 ┆ 2     │
│ ["und"]                 ┆ 2     │
│ ["rus"]                 ┆ 2     │
│ ["srp"]                 ┆ 2     │
│ ["pol"]                 ┆ 1     │
│ ["slv"]                 ┆ 1     │
│ ["dut"]                 ┆ 1     │
│ ["fre", "eng"]          ┆ 1     │
│ ["hrv", "slv", … "mac"] ┆ 1     │
│ ["cze"]                 ┆ 1     │
│ ["fro"]                 ┆ 1     │
│ ["lit"]                 ┆ 1     │
└─────────────────────────┴───────┘

In [69]:
df_preklady.filter(pl.col('700_a') == "Hiršal, Josef,").group_by('041_h').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (20, 2)
┌────────────────┬───────┐
│ 041_h          ┆ 245_a │
│ ---            ┆ ---   │
│ list[str]      ┆ u32   │
╞════════════════╪═══════╡
│ ["ger"]        ┆ 32    │
│ null           ┆ 12    │
│ ["por"]        ┆ 4     │
│ ["spa"]        ┆ 3     │
│ ["mul"]        ┆ 2     │
│ ["scr"]        ┆ 2     │
│ ["rum"]        ┆ 2     │
│ ["swe"]        ┆ 2     │
│ ["fre"]        ┆ 2     │
│ ["nor"]        ┆ 1     │
│ ["eng"]        ┆ 1     │
│ ["rus"]        ┆ 1     │
│ ["hun"]        ┆ 1     │
│ ["por", "fre"] ┆ 1     │
│ ["scc"]        ┆ 1     │
│ ["per"]        ┆ 1     │
│ ["por", "eng"] ┆ 1     │
│ ["hrv"]        ┆ 1     │
│ ["pal"]        ┆ 1     │
│ ["chi"]        ┆ 1     │
└────────────────┴───────┘