In [1]:
import os
import json
import datetime
import warnings
import polars as pl
import pandas as pd
import altair as alt

from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.hezke_jmeno import hezke_jmeno
from src.kristi_promin import kristi_promin
from src.me_to_neurazi import me_to_neurazi
from src.alt_friendly import alt_friendly

with open(os.path.join('src','kredity.json'), 'r', encoding='utf-8') as kredity:
    kredity = json.loads(kredity.read())
pl.Config(tbl_rows=100)
alt.data_transformers.disable_max_rows()
alt.themes.register('irozhlas', kristi_promin)
alt.themes.enable('irozhlas')
warnings.filterwarnings('ignore')

In [2]:
df = pl.read_parquet(os.path.join("data/cnb_sloupce","100.parquet"))
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left")
df = df.to_pandas()
df = df[df["leader"].str[6].isin(["a", "t"])]
df = df[~df["leader"].str[7].isin(["b", "i", "s", " "])]
df = df[(df["008"].str[15:17] == "xr") & (df["008"].str[35:38] == "cze")]
df = pl.from_pandas(df)
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","022.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","300.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","655.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","700.parquet")), left_on="001", right_on="001", how="left")
df = df.explode("022_a").filter(pl.col("022_a").is_null())
df = df.with_columns(pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok'))
df = df.with_columns(pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran'))
df = df.with_columns(pl.col('245_a').map_elements(bez_bordelu, return_dtype=str))
df = df.explode('245_p').with_columns(pl.col('245_p').map_elements(bez_bordelu, return_dtype=str))
print(len(df))

716789

In [3]:
aut = pl.read_parquet(os.path.join("data","aut_vyber.parquet"))

In [4]:
df = df.filter(pl.col("rok") >= 1800)

In [5]:
print(len(df))

710142

In [6]:
df = df.filter((~pl.col("245_h").str.contains("grafika")) | pl.col("245_h").is_null()).unique(subset=["008","100_a","245_a","245_p"], keep="first")

In [7]:
print(len(df))

705921

In [8]:
nechcemejetam = [
    "jn20001103401",
    "xx0008006",
    "jn19990008769",
    "jx20060515016",
    "jn19981002230",
    "jn19981001737",
    "jn19990210182",
    "jn19990001842",
    "jn19990002786",
    "jn19990004346",
    "jn20020721077",
    "jn19990210513",
    "jn19990005488",
    "jo20000080627",
    "jn19990000171",
    "jn20001005715",
    "jn19981002409",
    "jn20000810141",
    "jn19981002129",
    "jn20001103529",
    "jn20000810032",
    "jn19990001513",
    "jx20040611003",
    "jn19990005499",
    "jn19981002230",
    "jn19990001907",
    "jo2005267810",
    "jo20241218643",
    "jn20000602144",
    "jn19990005454",
    "jn19981228078",
    "xx0010566",
    "jn20010310318",
    "xx0203193",
    "jn20001227589",
    "jo2003204270",
    "xx0082647",
    "jn19990001239"
]

# df = df.filter(~pl.col("100_7").is_in(nechcemejetam))

In [9]:
df.sample(10)

shape: (10, 68)
┌──────────┬────────────────────┬───────────────┬───────────┬───┬───────────┬───────────┬──────┬───────┐
│ 100_ind1 ┆ 100_a              ┆ 100_7         ┆ 100_4     ┆ … ┆ 700_9     ┆ 700_g     ┆ rok  ┆ stran │
│ ---      ┆ ---                ┆ ---           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---   │
│ str      ┆ str                ┆ str           ┆ list[str] ┆   ┆ list[str] ┆ list[str] ┆ i64  ┆ i64   │
╞══════════╪════════════════════╪═══════════════╪═══════════╪═══╪═══════════╪═══════════╪══════╪═══════╡
│ 1        ┆ Luu, Uyen          ┆ mzk2014837473 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 143   │
│ 1        ┆ Dyk, Viktor,       ┆ jk01030247    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1959 ┆ 125   │
│ 1        ┆ Pilzer, Paul Zane, ┆ kv2013746292  ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 271   │
│ 1        ┆ Jepson, Tim        ┆ mzk2005300744 ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 96    │
│ 1        ┆ Šubrt, Filip,      ┆ jk01131614    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1890 ┆ 117   │
│ 1        ┆ Kantor, Milan,     ┆ jk01052876    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 109   │
│ 1        ┆ Štěpaníková, Anna, ┆ jk01131327    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1973 ┆ 41    │
│ 1        ┆ Bolzano, Bernard,  ┆ jk01012602    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1981 ┆ 438   │
│ 1        ┆ Liška, Václav,     ┆ ntka173243    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 301   │
│ 1        ┆ Povejšil, Jaromír, ┆ jk01100850    ┆ ["aut"]   ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 313   │
└──────────┴────────────────────┴───────────────┴───────────┴───┴───────────┴───────────┴──────┴───────┘

In [10]:
df = df.drop_nulls(subset=["700_a","700_4","700_7"]).explode(["700_a","700_4","700_7"])

In [11]:
df.select(pl.col(["700_a","700_4","700_7",'245_a'])).sample(10)

shape: (10, 4)
┌──────────────────────┬───────┬────────────────┬─────────────────────────────────┐
│ 700_a                ┆ 700_4 ┆ 700_7          ┆ 245_a                           │
│ ---                  ┆ ---   ┆ ---            ┆ ---                             │
│ str                  ┆ str   ┆ str            ┆ str                             │
╞══════════════════════╪═══════╪════════════════╪═════════════════════════════════╡
│ Lahoda, Zdeněk,      ┆ trl   ┆ jk01071384     ┆ Vlčí kůže                       │
│ Ross, Tony,          ┆ ill   ┆ xx0001347      ┆ Darebák David a tělo            │
│ Znamenaný, Petr,     ┆ pht   ┆ xx0124011      ┆ Plzeň                           │
│ Cesnak, Jozef,       ┆ ill   ┆ jx20040112005  ┆ Dějepis pro 6. ročník základní… │
│ Zazula, Roman        ┆ aut   ┆ jn20001227545  ┆ Záchranářské techniky a postup… │
│ Šumberová, Olga,     ┆ trl   ┆ jx20040116013  ┆ Známá tvář                      │
│ Klůfová, Petra,      ┆ trl   ┆ jo2008416199   ┆ Nebe mé lásky                   │
│ Hauner, Miroslav,    ┆ aut   ┆ jz8000333      ┆ Svařování v otázkách a odpověd… │
│ McRae, Carla         ┆ ill   ┆ hka20211107341 ┆ Mazej ven!                      │
│ Müllerová, Jaroslava ┆ aut   ┆ jx20050701056  ┆ Dějepis pro 2. stupeň základní… │
└──────────────────────┴───────┴────────────────┴─────────────────────────────────┘

## Autorské spolupráce

In [13]:
from itertools import combinations

In [14]:
def find_collaborations(df):
    # Filter for authors only
    authors = df.filter(pl.col('700_4') == 'aut')
    
    # Group by book title to get authors per book
    books_authors = authors.group_by('245_a').agg(pl.col('700_a').alias('authors'))
    
    # Generate author pairs and count collaborations
    collaborations = []
    for book in books_authors.iter_rows():
        if len(book[1]) > 1:  # Only consider books with multiple authors
            for pair in combinations(sorted(book[1]), 2):
                collaborations.append(pair)
    
    # Convert to dataframe and count frequencies
    collab_df = pl.DataFrame({
        'author1': [p[0] for p in collaborations],
        'author2': [p[1] for p in collaborations]
    })
    
    if len(collab_df) == 0:
        return pl.DataFrame({'author1': [], 'author2': [], 'collaboration_count': []})
    
    return (collab_df.group_by(['author1', 'author2'])
            .count()
            .sort('count', descending=True)
            .rename({'count': 'collaboration_count'}))

In [15]:
find_collaborations(df).filter(pl.col("author1") != pl.col("author2"))

shape: (222_858, 3)
┌────────────────────────┬───────────────────────────┬─────────────────────┐
│ author1                ┆ author2                   ┆ collaboration_count │
│ ---                    ┆ ---                       ┆ ---                 │
│ str                    ┆ str                       ┆ u32                 │
╞════════════════════════╪═══════════════════════════╪═════════════════════╡
│ Novotný, Miloš         ┆ Novák, František          ┆ 1165                │
│ Král, Lukáš            ┆ Valenta, Tomáš            ┆ 1156                │
│ Krupka, Peter,         ┆ Nechvátalová, Jana,       ┆ 1089                │
│ Malý, Martin           ┆ Münch, Otto               ┆ 897                 │
│ Münch, Otto            ┆ Čechová, Jarmila          ┆ 826                 │
│ Frydryšková, Yvetta    ┆ Münch, Otto               ┆ 820                 │
│ Krupka, Peter,         ┆ Staudková, Hana           ┆ 792                 │
│ Nechvátalová, Jana,    ┆ Staudková, Hana           ┆ 792                 │
│ Medek, Jaroslav,       ┆ Petrůj, Svatopluk,        ┆ 761                 │
│ Frydryšková, Yvetta    ┆ Čechová, Jarmila          ┆ 730                 │
│ Hrdinová, Jarmila      ┆ Novák, František          ┆ 636                 │
│ Nechvátalová, Jana,    ┆ Tůmová, Věra              ┆ 594                 │
│ Krupka, Peter,         ┆ Tůmová, Věra              ┆ 594                 │
│ Kulík, Oldřich         ┆ Tláskal, Jaromír,         ┆ 583                 │
│ Nechvátalová, Jana,    ┆ Pišl, Milan,              ┆ 495                 │
│ Krupka, Peter,         ┆ Pišl, Milan,              ┆ 495                 │
│ Čupera, Jiří,          ┆ Ždánský, Bronislav        ┆ 468                 │
│ Nechvátalová, Jana,    ┆ Rektorys, Karel,          ┆ 462                 │
│ Krupka, Peter,         ┆ Rektorys, Karel,          ┆ 462                 │
│ Staudková, Hana        ┆ Tůmová, Věra              ┆ 438                 │
│ Jirák, Antonín,        ┆ Reitler, Antonín,         ┆ 390                 │
│ Lokay, Bohumil         ┆ Štolba, František         ┆ 387                 │
│ Pišl, Milan,           ┆ Staudková, Hana           ┆ 360                 │
│ Rektorys, Karel,       ┆ Staudková, Hana           ┆ 336                 │
│ Kubát, Jindřich        ┆ Ždánský, Bronislav        ┆ 315                 │
│ Hájek, Bohumil,        ┆ Otčenášek, Ladislav       ┆ 289                 │
│ Styblík, Vlastimil,    ┆ Šafránek, František       ┆ 272                 │
│ Doležalová, Alena Bára ┆ Novák, František          ┆ 270                 │
│ Pišl, Milan,           ┆ Tůmová, Věra              ┆ 270                 │
│ Krsička, Rudolf        ┆ Ondráček, Josef           ┆ 256                 │
│ Chromá, Danuše         ┆ Münch, Otto               ┆ 255                 │
│ Rektorys, Karel,       ┆ Tůmová, Věra              ┆ 252                 │
│ Tožička, Bohumil,      ┆ Žofková, Lidmila,         ┆ 248                 │
│ Barborová, Lenka       ┆ Münch, Otto               ┆ 245                 │
│ Krupka, Peter,         ┆ Vřešťál, Evžen            ┆ 231                 │
│ Nechvátalová, Jana,    ┆ Černá, Milada             ┆ 231                 │
│ Nechvátalová, Jana,    ┆ Vřešťál, Evžen            ┆ 231                 │
│ Krupka, Peter,         ┆ Černá, Milada             ┆ 231                 │
│ Jelínková, Anna        ┆ Košťálová, Marie          ┆ 224                 │
│ Hechtová, Marie,       ┆ Košťálová, Marie          ┆ 224                 │
│ Hrdinová, Jarmila      ┆ Novotný, Miloš            ┆ 220                 │
│ Nykl, Jaroslav,        ┆ Rottová, Milada,          ┆ 216                 │
│ Chalupa, Petr,         ┆ Hübelová, Dana,           ┆ 212                 │
│ Pišl, Milan,           ┆ Rektorys, Karel,          ┆ 211                 │
│ Červený, František,    ┆ Řehořovský, Václav Karel, ┆ 211                 │
│ Hampl, Rudolf,         ┆ Úlehla, Josef,            ┆ 210                 │
│ Frolíková, Zora,       ┆ Košťálová, Marie          ┆ 208                 │
│ Hofman, Antonín,       ┆ Košťálová, Marie          ┆ 208                 │
│ Košťálová, Marie       ┆ Malíková, Marie           ┆ 208                 │
│ Košťálová, Marie       ┆ Wildová, Růžena           ┆ 208                 │
│ …                      ┆ …                         ┆ …                   │
│ Kröhn, Bohumil,        ┆ Rys, Jan                  ┆ 1                   │
│ Vlnas, Radek           ┆ Vokoun, Martin            ┆ 1                   │
│ Martínek, Jiří,        ┆ Nekvasil, Jiří,           ┆ 1                   │
│ Skálová, Eva           ┆ Sýkora, Pavel,            ┆ 1                   │
│ Horalíková, Marie,     ┆ Šubrt, Bořivoj,           ┆ 1                   │
│ Havel, Radovan,        ┆ Tamchyna, Miroslav        ┆ 1                   │
│ Binková, Adriena       ┆ Hruška, Josef,            ┆ 1                   │
│ Knapíková, Jaromíra,   ┆ Pokludová, Andrea,        ┆ 1                   │
│ Axman, Emil,           ┆ Hoffmeister, Karel,       ┆ 1                   │
│ Halászová, Věra,       ┆ Přadka, Milan,            ┆ 1                   │
│ Bártík, Pavel          ┆ Martanová, Veronika,      ┆ 1                   │
│ Gutzer, Martin         ┆ Ondráček, Čestmír         ┆ 1                   │
│ Kroupová, Alena,       ┆ Šulc, Petr,               ┆ 1                   │
│ Franke, Helena         ┆ Kubíčková, Anna           ┆ 1                   │
│ Jukl, Alois,           ┆ Trnka, Jiří,              ┆ 1                   │
│ Mach, Jiří,            ┆ Odehnal, Milan,           ┆ 1                   │
│ Tejrovský, Vít,        ┆ Vondrák, Jan,             ┆ 1                   │
│ Graubner, Jan,         ┆ Hudec, Petr,              ┆ 1                   │
│ Beran, Milan           ┆ Vaněk, Jan J.,            ┆ 1                   │
│ Palán, Aleš,           ┆ Pithart, Petr,            ┆ 1                   │
│ Blažek, Vladimír,      ┆ Malý, Karel,              ┆ 1                   │
│ Vybíral, Zdeněk,       ┆ Čornej, Petr,             ┆ 1                   │
│ Pešťák, Michael        ┆ Plavec, Michal,           ┆ 1                   │
│ Erban Kočergina, Julie ┆ Vargová, Lenka,           ┆ 1                   │
│ Brant, Jiří            ┆ Vojteková, Lenka          ┆ 1                   │
│ Kubecová, Markéta      ┆ Peterková, Dana           ┆ 1                   │
│ Bumbálek, Jaroslav,    ┆ Vlach, Petr               ┆ 1                   │
│ Hlobil, Ivo,           ┆ Lahoda, Vojtěch,          ┆ 1                   │
│ Ditrych, Daniel        ┆ Prouza, Martin,           ┆ 1                   │
│ Betáková, Lucie,       ┆ Petr, Jan,                ┆ 1                   │
│ Křížová, Lenka,        ┆ Prostředník, Jan,         ┆ 1                   │
│ Benson, Sara           ┆ Ver Berkmoes, Ryan        ┆ 1                   │
│ Kavka, Aleš            ┆ Kysílko, Martin           ┆ 1                   │
│ Vaňatová, Lada         ┆ Vlček, Václav             ┆ 1                   │
│ Martinec, Petr,        ┆ Ryšánek, Petr             ┆ 1                   │
│ Young, Grant M.        ┆ Zoubková, Jana            ┆ 1                   │
│ Zemčík, Tomáš,         ┆ Čapková, Magdalena,       ┆ 1                   │
│ Dragoun, Zdeněk,       ┆ Lukas, Jiří,              ┆ 1                   │
│ Horáčková, Ladislava,  ┆ Kyselý, René,             ┆ 1                   │
│ Bouška, Kamil,         ┆ Puršl, Ladislav,          ┆ 1                   │
│ Košina, Miroslav       ┆ Nedoma, Woodrow           ┆ 1                   │
│ Košťan, Pavol          ┆ Šuleř, Oldřich,           ┆ 1                   │
│ Boková, Liv,           ┆ Neuman, Saša,             ┆ 1                   │
│ Dvořáková, Naděžda     ┆ Macháčková, Jitka         ┆ 1                   │
│ Osička, Jaroslav       ┆ Svoboda, Josef,           ┆ 1                   │
│ Stejskal, Pavel,       ┆ Stolz, Ivo,               ┆ 1                   │
│ Arppe, Laura           ┆ Velemínský, Petr,         ┆ 1                   │
│ Hrazdira, Luboš,       ┆ Veselý, Tomáš             ┆ 1                   │
│ Běhounková, Blanka     ┆ Škoda, Filip,             ┆ 1                   │
│ Hanáková, Jitka,       ┆ Junek, Marek,             ┆ 1                   │
└────────────────────────┴───────────────────────────┴─────────────────────┘

In [16]:
df_autorske = df.filter(pl.col('700_4') == 'aut')

In [17]:
def hezkejmeno(sto):
    if not sto[-1].isalnum():
        sto = sto[:-1]
    if "," in sto:
        sto = sto.split(",")
        sto = sto[1].strip() + " " + sto[0].strip()
    return sto

In [18]:
df_autorske = df_autorske.with_columns(pl.col("100_a").map_elements(hezkejmeno).alias("jmeno1")).with_columns(pl.col("700_a").map_elements(hezkejmeno).alias("jmeno2"))

In [19]:
df_autorske

shape: (164_619, 70)
┌──────────┬──────────────────┬────────────────┬────────────────┬───┬──────┬───────┬─────────────────┬─────────────────┐
│ 100_ind1 ┆ 100_a            ┆ 100_7          ┆ 100_4          ┆ … ┆ rok  ┆ stran ┆ jmeno1          ┆ jmeno2          │
│ ---      ┆ ---              ┆ ---            ┆ ---            ┆   ┆ ---  ┆ ---   ┆ ---             ┆ ---             │
│ str      ┆ str              ┆ str            ┆ list[str]      ┆   ┆ i64  ┆ i64   ┆ str             ┆ str             │
╞══════════╪══════════════════╪════════════════╪════════════════╪═══╪══════╪═══════╪═════════════════╪═════════════════╡
│ 1        ┆ Kopietz, Gerit,  ┆ jn20001103811  ┆ ["aut"]        ┆ … ┆ 2002 ┆ 120   ┆ Gerit Kopietz   ┆ Jörg Sommer     │
│ 1        ┆ Lach, Vladimír,  ┆ jk01071391     ┆ ["aut"]        ┆ … ┆ 1991 ┆ 178   ┆ Vladimír Lach   ┆ Marcela Daňková │
│ 1        ┆ Fischerová-Kvěch ┆ jk01031311     ┆ ["ill"]        ┆ … ┆ 2018 ┆ 50    ┆ Marie Fischerov ┆ Radek Malý      │
│          ┆ ová, Marie,      ┆                ┆                ┆   ┆      ┆       ┆ á-Kvěchová      ┆                 │
│ 1        ┆ Hrůza, Jiří,     ┆ jk01043070     ┆ ["aut"]        ┆ … ┆ 1995 ┆ 186   ┆ Jiří Hrůza      ┆ Josef Zajíc     │
│ 1        ┆ Sysel, Miroslav  ┆ xx0013565      ┆ ["aut"]        ┆ … ┆ 1951 ┆ 154   ┆ Miroslav Sysel  ┆ Antonín Jiráček │
│ 1        ┆ Žáková, Eliška   ┆ jo2015896152   ┆ ["aut"]        ┆ … ┆ 2020 ┆ 17    ┆ Eliška Žáková   ┆ Zuzana Krupová  │
│ 1        ┆ Žáková, Eliška   ┆ jo2015896152   ┆ ["aut"]        ┆ … ┆ 2020 ┆ 17    ┆ Eliška Žáková   ┆ Emil Krupa      │
│ 1        ┆ Walters, David,  ┆ xx0174429      ┆ ["aut"]        ┆ … ┆ 1999 ┆ 39    ┆ David Walters   ┆ John Wesley     │
│ 1        ┆ Pauková, Marie,  ┆ jk01091956     ┆ ["aut"]        ┆ … ┆ 1976 ┆ 163   ┆ Marie Pauková   ┆ Ladislav        │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Otčenášek       │
│ 1        ┆ Pauková, Marie,  ┆ jk01091956     ┆ ["aut"]        ┆ … ┆ 1976 ┆ 163   ┆ Marie Pauková   ┆ Bohumil Hájek   │
│ 1        ┆ Kos, Jan,        ┆ ola2016930333  ┆ ["aut"]        ┆ … ┆ 2022 ┆ 320   ┆ Jan Kos         ┆ Jan Dvořák      │
│ 1        ┆ Běhounek,        ┆ jk01011367     ┆ ["aut"]        ┆ … ┆ 1931 ┆ 113   ┆ František       ┆ Jaroslav        │
│          ┆ František,       ┆                ┆                ┆   ┆      ┆       ┆ Běhounek        ┆ Heyrovský       │
│ 1        ┆ Hume, Rob        ┆ mzk2004234210  ┆ ["aut"]        ┆ … ┆ 2023 ┆ 640   ┆ Rob Hume        ┆ Rob Still       │
│ 1        ┆ Hume, Rob        ┆ mzk2004234210  ┆ ["aut"]        ┆ … ┆ 2023 ┆ 640   ┆ Rob Hume        ┆ Andy Swash      │
│ 1        ┆ Hume, Rob        ┆ mzk2004234210  ┆ ["aut"]        ┆ … ┆ 2023 ┆ 640   ┆ Rob Hume        ┆ Hugh Harrop     │
│ 1        ┆ Nováčková,       ┆ jx20120224021  ┆ ["aut"]        ┆ … ┆ 2016 ┆ 100   ┆ Helena          ┆ Radka Piknerová │
│          ┆ Helena           ┆                ┆                ┆   ┆      ┆       ┆ Nováčková       ┆                 │
│ 1        ┆ Nováčková,       ┆ jx20120224021  ┆ ["aut"]        ┆ … ┆ 2016 ┆ 100   ┆ Helena          ┆ Barbora         │
│          ┆ Helena           ┆                ┆                ┆   ┆      ┆       ┆ Nováčková       ┆ Škaloudová      │
│ 1        ┆ Nováčková,       ┆ jx20120224021  ┆ ["aut"]        ┆ … ┆ 2016 ┆ 100   ┆ Helena          ┆ Zdenka          │
│          ┆ Helena           ┆                ┆                ┆   ┆      ┆       ┆ Nováčková       ┆ Štefanidesová   │
│ 1        ┆ Šoltés, Josef    ┆ jk01130737     ┆ ["aut"]        ┆ … ┆ 1946 ┆ 23    ┆ Josef Šoltés    ┆ František       │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Janouch         │
│ 1        ┆ Šoltés, Josef    ┆ jk01130737     ┆ ["aut"]        ┆ … ┆ 1946 ┆ 23    ┆ Josef Šoltés    ┆ Jan Vallas      │
│ 1        ┆ Kotková,         ┆ xx0057903      ┆ ["aut", "ill"] ┆ … ┆ 2012 ┆ 53    ┆ Markéta Kotková ┆ Kateřina        │
│          ┆ Markéta,         ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Kotková         │
│ 1        ┆ Pavlůsek, Alois  ┆ xx0027446      ┆ ["aut"]        ┆ … ┆ 2009 ┆ 140   ┆ Alois Pavlůsek  ┆ Ondřej Pavlůsek │
│ 1        ┆ Stránský, Jiří   ┆ jx20040813018  ┆ ["aut"]        ┆ … ┆ 2010 ┆ 135   ┆ Jiří Stránský   ┆ Kamil Ondroušek │
│ 1        ┆ Kuchař, Jan,     ┆ jk01070723     ┆ ["aut"]        ┆ … ┆ 1945 ┆ 126   ┆ Jan Kuchař      ┆ František       │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Svoboda         │
│ 1        ┆ Ulrych, Petr,    ┆ jn19981002274  ┆ ["aut"]        ┆ … ┆ 1975 ┆ 97    ┆ Petr Ulrych     ┆ Bohumil Nekolný │
│ 1        ┆ Chotěbor, Petr,  ┆ jn19990216035  ┆ ["aut", "ill"] ┆ … ┆ 1994 ┆ 183   ┆ Petr Chotěbor   ┆ František       │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Kadlec          │
│ 1        ┆ Marx, Karl,      ┆ jn19990005454  ┆ ["aut"]        ┆ … ┆ 1945 ┆ 31    ┆ Karl Marx       ┆ Friedrich       │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Engels          │
│ 1        ┆ Dvořák, Otomar,  ┆ jn20010523024  ┆ ["aut"]        ┆ … ┆ 2020 ┆ 232   ┆ Otomar Dvořák   ┆ Josef Pepson    │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Snětivý         │
│ 1        ┆ Martinásková,    ┆ null           ┆ ["aut"]        ┆ … ┆ 1998 ┆ 160   ┆ Marie           ┆ Ladislav        │
│          ┆ Marie            ┆                ┆                ┆   ┆      ┆       ┆ Martinásková    ┆ Šmejkal         │
│ 1        ┆ Hanzlová, Hana,  ┆ ntka172493     ┆ ["aut"]        ┆ … ┆ 2018 ┆ 270   ┆ Hana Hanzlová   ┆ Jiří Šmejkal    │
│ 1        ┆ Kraus, Radek     ┆ xx0190670      ┆ ["aut"]        ┆ … ┆ 2000 ┆ 192   ┆ Radek Kraus     ┆ Martin Brejla   │
│ 1        ┆ Kršňáková,       ┆ ola2013786912  ┆ ["aut"]        ┆ … ┆ 2006 ┆ 137   ┆ Martina         ┆ Jakub John      │
│          ┆ Martina          ┆                ┆                ┆   ┆      ┆       ┆ Kršňáková       ┆                 │
│ 1        ┆ Kršňáková,       ┆ ola2013786912  ┆ ["aut"]        ┆ … ┆ 2006 ┆ 137   ┆ Martina         ┆ Dalimil Vítek   │
│          ┆ Martina          ┆                ┆                ┆   ┆      ┆       ┆ Kršňáková       ┆                 │
│ 1        ┆ Kudláčková, Hana ┆ jo2017946500   ┆ ["aut"]        ┆ … ┆ 2016 ┆ 11    ┆ Hana Kudláčková ┆ Kateřina        │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Horáčková       │
│ 1        ┆ Kudláčková, Hana ┆ jo2017946500   ┆ ["aut"]        ┆ … ┆ 2016 ┆ 11    ┆ Hana Kudláčková ┆ Zora Smržová    │
│ 1        ┆ Kudláčková, Hana ┆ jo2017946500   ┆ ["aut"]        ┆ … ┆ 2016 ┆ 11    ┆ Hana Kudláčková ┆ Eliška          │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Hrabálková      │
│ 1        ┆ Kudláčková, Hana ┆ jo2017946500   ┆ ["aut"]        ┆ … ┆ 2016 ┆ 11    ┆ Hana Kudláčková ┆ Alena           │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Bartošková      │
│ 1        ┆ Kudláčková, Hana ┆ jo2017946500   ┆ ["aut"]        ┆ … ┆ 2016 ┆ 11    ┆ Hana Kudláčková ┆ Martin Faldyna  │
│ 1        ┆ Chromečková,     ┆ ola20201067519 ┆ ["aut"]        ┆ … ┆ 2019 ┆ 185   ┆ Monika          ┆ Václav          │
│          ┆ Monika           ┆                ┆                ┆   ┆      ┆       ┆ Chromečková     ┆ Michalička      │
│ 1        ┆ Smrček, Martin,  ┆ jn20001227587  ┆ ["aut"]        ┆ … ┆ 2004 ┆ 180   ┆ Martin Smrček   ┆ Lea Smrčková    │
│ 1        ┆ Bek, Jindřich,   ┆ jk01011407     ┆ ["aut"]        ┆ … ┆ 1973 ┆ 217   ┆ Jindřich Bek    ┆ Alexandr        │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Chmelík         │
│ 1        ┆ Pešek, Ladislav, ┆ jk01092649     ┆ ["aut"]        ┆ … ┆ 1997 ┆ 442   ┆ Ladislav Pešek  ┆ Zdeněk Hedvábný │
│ 1        ┆ Nagy, Jozef,     ┆ jk01082642     ┆ ["aut"]        ┆ … ┆ 1997 ┆ 247   ┆ Jozef Nagy      ┆ Jiří Taufer     │
│ 1        ┆ Drastík,         ┆ jk01022997     ┆ ["aut"]        ┆ … ┆ 1979 ┆ 293   ┆ František       ┆ Václav Vávra    │
│          ┆ František,       ┆                ┆                ┆   ┆      ┆       ┆ Drastík         ┆                 │
│ 1        ┆ Drastík,         ┆ jk01022997     ┆ ["aut"]        ┆ … ┆ 1979 ┆ 293   ┆ František       ┆ Jaroslav Křivý  │
│          ┆ František,       ┆                ┆                ┆   ┆      ┆       ┆ Drastík         ┆                 │
│ 1        ┆ Votoček, Emil,   ┆ jk01150807     ┆ ["aut"]        ┆ … ┆ 1911 ┆ 5     ┆ Emil Votoček    ┆ Cyril Krauz     │
│ 1        ┆ Šmejkal, Václav, ┆ jn20001227177  ┆ ["aut"]        ┆ … ┆ 2021 ┆ 514   ┆ Václav Šmejkal  ┆ Barbara Dufková │
│ 1        ┆ Vondráček,       ┆ mzk2013800101  ┆ ["aut"]        ┆ … ┆ 2013 ┆ 125   ┆ Ondřej          ┆ Marek Havrda    │
│          ┆ Ondřej,          ┆                ┆                ┆   ┆      ┆       ┆ Vondráček       ┆                 │
│ 1        ┆ Novotný, Ivan    ┆ null           ┆ ["aut"]        ┆ … ┆ 1995 ┆ 32    ┆ Ivan Novotný    ┆ Jiří Fidler     │
│ 1        ┆ Novotný, Ivan    ┆ null           ┆ ["aut"]        ┆ … ┆ 1995 ┆ 32    ┆ Ivan Novotný    ┆ Jaroslav Roušar │
│ …        ┆ …                ┆ …              ┆ …              ┆ … ┆ …    ┆ …     ┆ …               ┆ …               │
│ 1        ┆ Drahný, Miloš,   ┆ jk01022954     ┆ ["aut"]        ┆ … ┆ 1964 ┆ 68    ┆ Miloš Drahný    ┆ Ladislav Bohal  │
│ 1        ┆ Prorok,          ┆ mzk2003184706  ┆ ["aut"]        ┆ … ┆ 2011 ┆ 156   ┆ Vladimír Prorok ┆ Aleš Lisa       │
│          ┆ Vladimír,        ┆                ┆                ┆   ┆      ┆       ┆                 ┆                 │
│ 1        ┆ Soušková, Milena ┆ pna2005274578  ┆ ["aut"]        ┆ … ┆ 2001 ┆ 214   ┆ Milena Soušková ┆ Michal Spirit   │
│ 1        ┆ Verheiden, Mark, ┆ xx0096689      ┆ ["aut"]        ┆ … ┆ 2009 ┆ 6     ┆ Mark Verheiden  ┆ John Arcudi     │
│ 1        ┆ Verheiden, Mark, ┆ xx0096689      ┆ ["aut"]        ┆ … ┆ 2009 ┆ 6     ┆ Mark Verheiden  ┆ Ian Edginton    │
│ 1        ┆ Verheiden, Mark, ┆ xx0096689      ┆ ["aut"]        ┆ … ┆ 2009 ┆ 6     ┆ Mark Verheiden  ┆ Chet Williamson │
│ 1        ┆ Verheiden, Mark, ┆ xx0096689      ┆ ["aut"]        ┆ … ┆ 2009 ┆ 6     ┆ Mark Verheiden  ┆ Mark Schultz    │
│ 1        ┆ Edgar, Silène,   ┆ xx0205879      ┆ ["aut"]        ┆ … ┆ 2017 ┆ 204   ┆ Silène Edgar    ┆ Paul Beorn      │
│ 1        ┆ Veselka,         ┆ jx20050520018  ┆ ["aut"]        ┆ … ┆ 1950 ┆ 87    ┆ Jaroslav        ┆ Karel Ouředník  │
│          ┆ Jaroslav         ┆                ┆                ┆   ┆      ┆       ┆ Veselka         ┆                 │
│ 1        ┆ Málek, Zdeněk,   ┆ mzk2008479771  ┆ ["aut"]        ┆ … ┆ 2008 ┆ 122   ┆ Zdeněk Málek    ┆ Zdeněk Čujan    │
│ 1        ┆ Janků, Martin,   ┆ mzk2003181709  ┆ ["aut"]        ┆ … ┆ 2010 ┆ 234   ┆ Martin Janků    ┆ Linda Janků     │
│ 1        ┆ Vyčichlová,      ┆ mzk2008434001  ┆ ["aut"]        ┆ … ┆ 2015 ┆ 93    ┆ Vlasta          ┆ Vendula         │
│          ┆ Vlasta,          ┆                ┆                ┆   ┆      ┆       ┆ Vyčichlová      ┆ Šnokhousová     │
│ 1        ┆ Vyčichlová,      ┆ mzk2008434001  ┆ ["aut"]        ┆ … ┆ 2015 ┆ 93    ┆ Vlasta          ┆ František Rozum │
│          ┆ Vlasta,          ┆                ┆                ┆   ┆      ┆       ┆ Vyčichlová      ┆                 │
│ 1        ┆ Vyčichlová,      ┆ mzk2008434001  ┆ ["aut"]        ┆ … ┆ 2015 ┆ 93    ┆ Vlasta          ┆ David Valouch   │
│          ┆ Vlasta,          ┆                ┆                ┆   ┆      ┆       ┆ Vyčichlová      ┆                 │
│ 1        ┆ Vyčichlová,      ┆ mzk2008434001  ┆ ["aut"]        ┆ … ┆ 2015 ┆ 93    ┆ Vlasta          ┆ Ludmila         │
│          ┆ Vlasta,          ┆                ┆                ┆   ┆      ┆       ┆ Vyčichlová      ┆ Součková        │
│ 1        ┆ Kopp, Jan,       ┆ jo20010086952  ┆ ["aut"]        ┆ … ┆ 1997 ┆ 78    ┆ Jan Kopp        ┆ Marie Novotná   │
│ 1        ┆ Spitzer          ┆ jo2012739127   ┆ ["aut"]        ┆ … ┆ 2014 ┆ 75    ┆ Ivana Spitzer   ┆ Bohdana Orlová  │
│          ┆ Ostřanská,       ┆                ┆                ┆   ┆      ┆       ┆ Ostřanská       ┆                 │
│          ┆ Ivana,           ┆                ┆                ┆   ┆      ┆       ┆                 ┆                 │
│ 1        ┆ Spitzer          ┆ jo2012739127   ┆ ["aut"]        ┆ … ┆ 2014 ┆ 75    ┆ Ivana Spitzer   ┆ Rudolf Gerát    │
│          ┆ Ostřanská,       ┆                ┆                ┆   ┆      ┆       ┆ Ostřanská       ┆                 │
│          ┆ Ivana,           ┆                ┆                ┆   ┆      ┆       ┆                 ┆                 │
│ 1        ┆ Janák, Jan,      ┆ jk01050753     ┆ ["aut"]        ┆ … ┆ 1989 ┆ 519   ┆ Jan Janák       ┆ Zdeňka          │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Hledíková       │
│ 1        ┆ Kuna, Martin,    ┆ mzk2004239326  ┆ ["aut"]        ┆ … ┆ 2005 ┆ 593   ┆ Martin Kuna     ┆ Naďa Profantová │
│ 1        ┆ Kuna, Martin,    ┆ mzk2004239326  ┆ ["aut"]        ┆ … ┆ 2005 ┆ 593   ┆ Martin Kuna     ┆ Miloslav        │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Bartuška        │
│ 1        ┆ Lutovský,        ┆ jo2002100447   ┆ ["aut"]        ┆ … ┆ 1995 ┆ 89    ┆ Michal Lutovský ┆ Naďa Profantová │
│          ┆ Michal,          ┆                ┆                ┆   ┆      ┆       ┆                 ┆                 │
│ 1        ┆ Herčík, Karel,   ┆ jn20001005045  ┆ ["aut"]        ┆ … ┆ 2007 ┆ 174   ┆ Karel Herčík    ┆ Jiří Dufek      │
│ 1        ┆ Herčík, Karel,   ┆ jn20001005045  ┆ ["aut"]        ┆ … ┆ 2007 ┆ 174   ┆ Karel Herčík    ┆ Pavel Filip     │
│ 1        ┆ Borská, Zdeňka   ┆ xx0086240      ┆ ["aut"]        ┆ … ┆ 1996 ┆ 786   ┆ Zdeňka Borská   ┆ Zbyněk Gross    │
│ 1        ┆ Michel, George   ┆ xx0012043      ┆ ["aut"]        ┆ … ┆ 1999 ┆ 478   ┆ George F.       ┆ Celia L. Moore  │
│          ┆ F.,              ┆                ┆                ┆   ┆      ┆       ┆ Michel          ┆                 │
│ 1        ┆ Münich, Daniel,  ┆ mzk2003185111  ┆ ["aut"]        ┆ … ┆ 2015 ┆ 28    ┆ Daniel Münich   ┆ Štěpán Jurajda  │
│ 1        ┆ Cartland,        ┆ jn19990001350  ┆ ["aut"]        ┆ … ┆ 1993 ┆ 187   ┆ Barbara         ┆ Olga Šumberová  │
│          ┆ Barbara,         ┆                ┆                ┆   ┆      ┆       ┆ Cartland        ┆                 │
│ 1        ┆ Rozenský,        ┆ mzk2002144893  ┆ ["aut"]        ┆ … ┆ 1981 ┆ 296   ┆ Zdeněk Rozenský ┆ Jiří Brabec     │
│          ┆ Zdeněk,          ┆                ┆                ┆   ┆      ┆       ┆                 ┆                 │
│ 1        ┆ Rozenský,        ┆ mzk2002144893  ┆ ["aut"]        ┆ … ┆ 1981 ┆ 296   ┆ Zdeněk Rozenský ┆ František       │
│          ┆ Zdeněk,          ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Martan          │
│ 1        ┆ Bejčková, Marie  ┆ xx0153425      ┆ ["aut"]        ┆ … ┆ 1941 ┆ 72    ┆ Marie Bejčková  ┆ Milada Zlochová │
│ 1        ┆ Šlajer, Josef,   ┆ jk01130425     ┆ ["edt"]        ┆ … ┆ 1959 ┆ 38    ┆ Josef Šlajer    ┆ Božena Němcová  │
│ 1        ┆ Šlajer, Josef,   ┆ jk01130425     ┆ ["edt"]        ┆ … ┆ 1959 ┆ 38    ┆ Josef Šlajer    ┆ Karel Jaromír   │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Erben           │
│ 1        ┆ Šlajer, Josef,   ┆ jk01130425     ┆ ["edt"]        ┆ … ┆ 1959 ┆ 38    ┆ Josef Šlajer    ┆ František       │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Bartoš          │
│ 1        ┆ Doleček, Josef   ┆ jk01022564     ┆ ["aut"]        ┆ … ┆ 1988 ┆ 179   ┆ Josef Doleček   ┆ Zdeněk Holoubek │
│ 1        ┆ Konečný, Michal, ┆ mzk2004246393  ┆ ["aut"]        ┆ … ┆ 2021 ┆ 287   ┆ Michal Konečný  ┆ Ivo Cerman      │
│ 1        ┆ Brčák, Antonín   ┆ jk01013044     ┆ ["aut"]        ┆ … ┆ 1972 ┆ 254   ┆ Antonín Brčák   ┆ Josef Rollo     │
│ 1        ┆ Sitenský,        ┆ jk01111376     ┆ ["aut", "pht"] ┆ … ┆ 1994 ┆ 229   ┆ Ladislav        ┆ Zdeněk Kukal    │
│          ┆ Ladislav,        ┆                ┆                ┆   ┆      ┆       ┆ Sitenský        ┆                 │
│ 1        ┆ Hušek, Roman,    ┆ jk01043337     ┆ ["aut"]        ┆ … ┆ 1977 ┆ 136   ┆ Roman Hušek     ┆ Josef Lauber    │
│ 1        ┆ Pavlásek,        ┆ jx20050718044  ┆ ["aut"]        ┆ … ┆ 2008 ┆ 215   ┆ Vlastimil       ┆ Hana Kunešová   │
│          ┆ Vlastimil        ┆                ┆                ┆   ┆      ┆       ┆ Pavlásek        ┆                 │
│ 1        ┆ Pavlásek,        ┆ jx20050718044  ┆ ["aut"]        ┆ … ┆ 2008 ┆ 215   ┆ Vlastimil       ┆ Pavlína         │
│          ┆ Vlastimil        ┆                ┆                ┆   ┆      ┆       ┆ Pavlásek        ┆ Hejduková       │
│ 1        ┆ Cottini, Lucio,  ┆ xx0215649      ┆ ["aut"]        ┆ … ┆ 2017 ┆ 3     ┆ Lucio Cottini   ┆ Giacomo Vivanti │
│ 1        ┆ Cottini, Lucio,  ┆ xx0215649      ┆ ["aut"]        ┆ … ┆ 2017 ┆ 3     ┆ Lucio Cottini   ┆ Benedetta Bonci │
│ 1        ┆ Cottini, Lucio,  ┆ xx0215649      ┆ ["aut"]        ┆ … ┆ 2017 ┆ 3     ┆ Lucio Cottini   ┆ Rita Centra     │
│ 1        ┆ Krásnohorská,    ┆ jk01062911     ┆ ["aut"]        ┆ … ┆ 1940 ┆ 170   ┆ Eliška          ┆ Anežka Čermákov │
│          ┆ Eliška,          ┆                ┆                ┆   ┆      ┆       ┆ Krásnohorská    ┆ á-Sluková       │
│ 1        ┆ Pacnerová, Jana, ┆ jn20000810168  ┆ ["aut"]        ┆ … ┆ 2021 ┆ 78    ┆ Jana Pacnerová  ┆ Ivana           │
│          ┆                  ┆                ┆                ┆   ┆      ┆       ┆                 ┆ Scheinostová    │
│ 1        ┆ Cetl, Jiří,      ┆ jk01020629     ┆ ["aut"]        ┆ … ┆ 1985 ┆ 634   ┆ Jiří Cetl       ┆ Petr Horák      │
│ 1        ┆ Cetl, Jiří,      ┆ jk01020629     ┆ ["aut"]        ┆ … ┆ 1985 ┆ 634   ┆ Jiří Cetl       ┆ Radislav Hošek  │
│ 1        ┆ Cetl, Jiří,      ┆ jk01020629     ┆ ["aut"]        ┆ … ┆ 1985 ┆ 634   ┆ Jiří Cetl       ┆ Jaroslav Kudrna │
│ 1        ┆ Olej, Vladimír,  ┆ mzk2005269726  ┆ ["aut"]        ┆ … ┆ 2010 ┆ 98    ┆ Vladimír Olej   ┆ Petr Hájek      │
└──────────┴──────────────────┴────────────────┴────────────────┴───┴──────┴───────┴─────────────────┴─────────────────┘

In [20]:
def kombajmen(jmeno1, jmeno2, radit=True, spojeni = "a"):
    try:
        jmena = [jmeno1.split(" ")[-1], jmeno2.split(" ")[-1]]
        if radit == True:
            jmena.sort()
        return f" {spojeni} ".join(jmena)
    except Exception as e:
        print(e)
        return None

In [21]:
df_autorske = df_autorske.with_columns(pl.struct('jmeno1','jmeno2').map_elements(lambda x: kombajmen(x['jmeno1'], x['jmeno2'])).alias("dvojice"))

In [22]:
df_autorske.group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (105_346, 2)
┌─────────────────────────┬───────┐
│ dvojice                 ┆ 245_a │
│ ---                     ┆ ---   │
│ str                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ David a Soukup          ┆ 126   │
│ Nedbalová a Nedbalová   ┆ 90    │
│ Engels a Marx           ┆ 60    │
│ Benešová a Kanyzová     ┆ 52    │
│ Benešová a Fukalová     ┆ 52    │
│ Benešová a Příhoda      ┆ 52    │
│ Benešová a Šmíd         ┆ 52    │
│ Benešová a Vondrák      ┆ 52    │
│ Benešová a Formáčková   ┆ 52    │
│ Mihulová a Svoboda      ┆ 43    │
│ Brožová a Vostrá        ┆ 38    │
│ Smíšek a Smíšková       ┆ 36    │
│ Nedbalcová a Zouharová  ┆ 36    │
│ Voskovec a Werich       ┆ 35    │
│ Polášek a Polášková     ┆ 35    │
│ Jirotka a Vaněk         ┆ 34    │
│ Kučera a Stach          ┆ 33    │
│ Grimm a Grimm           ┆ 33    │
│ Child a Preston         ┆ 32    │
│ David a Dobrovolná      ┆ 31    │
│ Chmelař a Šimon         ┆ 29    │
│ Goscinny a Morris       ┆ 29    │
│ Klečka a Kunz           ┆ 28    │
│ Kubálek a Kubálková     ┆ 28    │
│ Kozák a Roček           ┆ 27    │
│ Hošková a Paprčka       ┆ 26    │
│ Lenin a Marx            ┆ 26    │
│ Jirotka a Turková       ┆ 26    │
│ Rusňáková a Sedláček    ┆ 25    │
│ Beran a Cílek           ┆ 25    │
│ Augusta a Honzák        ┆ 25    │
│ Novák a Taterová        ┆ 25    │
│ Pešatová a Švingalová   ┆ 25    │
│ Bartoňová a Vítková     ┆ 25    │
│ Bruthans a Kondrová     ┆ 24    │
│ Bruthans a Bůzek        ┆ 24    │
│ Pecinovský a Pecinovský ┆ 24    │
│ Bruthans a Kadlecová    ┆ 23    │
│ Erben a Němcová         ┆ 23    │
│ Jucovičová a Žáčková    ┆ 23    │
│ Strugackij a Strugackij ┆ 23    │
│ Beran a Jirotka         ┆ 22    │
│ Mikulenková a Molnár    ┆ 22    │
│ Novák a Špička          ┆ 22    │
│ Erben a Vilikovský      ┆ 21    │
│ Müller a Müllerová      ┆ 21    │
│ Čadilová a Žampachová   ┆ 21    │
│ Novák a Nováková        ┆ 21    │
│ Bratršovská a Hrdlička  ┆ 21    │
│ Matiašková a Nedbalcová ┆ 21    │
│ …                       ┆ …     │
│ Durdil a Nymburský      ┆ 1     │
│ Kadleček a Polanský     ┆ 1     │
│ Hospodka a Pleninger    ┆ 1     │
│ Grygar a Kalašová       ┆ 1     │
│ Komárek a Pfeffer       ┆ 1     │
│ Chaloupecký a Vaněk     ┆ 1     │
│ Felisatti a Pittorru    ┆ 1     │
│ Fischer a Mikeštíková   ┆ 1     │
│ Crosbie a Gool          ┆ 1     │
│ Gorbačev a Jurgens      ┆ 1     │
│ Horák a Rybínová        ┆ 1     │
│ Achtenová a Klír        ┆ 1     │
│ Prokeš a Skřivan        ┆ 1     │
│ Filipová a Kukutschová  ┆ 1     │
│ Jann a Steiner          ┆ 1     │
│ Bartková a Sikorová     ┆ 1     │
│ Michal a Vebersík       ┆ 1     │
│ Klásek a Lážnovský      ┆ 1     │
│ Borůvková a Wimmerová   ┆ 1     │
│ Saint-Germain a Thys    ┆ 1     │
│ Zpěvák a Štětina        ┆ 1     │
│ Lánská a Vaněk          ┆ 1     │
│ Rusová a Šiková         ┆ 1     │
│ Hyland a Wilson         ┆ 1     │
│ Drastík a Švejda        ┆ 1     │
│ Dobrovolný a Drastík    ┆ 1     │
│ Skřivánek a Vopálka     ┆ 1     │
│ Bártlová a Jenšík       ┆ 1     │
│ George a Tollefsen      ┆ 1     │
│ Hladíková a Novák       ┆ 1     │
│ Smetáček a Švarcová     ┆ 1     │
│ Milota a Stará          ┆ 1     │
│ Kupka a Rychlíková      ┆ 1     │
│ Fragner a Skarnitzl     ┆ 1     │
│ Dvořáková a Polášek     ┆ 1     │
│ Barcuch a Šerka         ┆ 1     │
│ Sellner a Štorch        ┆ 1     │
│ Nemčok a Rybář          ┆ 1     │
│ Beneš a Ducháček        ┆ 1     │
│ Mach a Vlk              ┆ 1     │
│ Nedorost a Větrovec     ┆ 1     │
│ Jůn a Woitschová        ┆ 1     │
│ Janíčková a Zmeškalová  ┆ 1     │
│ Danihelková a Malý      ┆ 1     │
│ Maixner a Mojžíšek      ┆ 1     │
│ Hašek a Trávníček       ┆ 1     │
│ Hošek a Wahl            ┆ 1     │
│ Lipták a Přendík        ┆ 1     │
│ Sechterová a Tillmann   ┆ 1     │
│ Borovanský a Čeladník   ┆ 1     │
└─────────────────────────┴───────┘

In [23]:
df_autorske.group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (111_462, 4)
┌────────────────────────────────┬────────────────┬──────────────────────────────┬───────┐
│ 100_a                          ┆ 100_7          ┆ 700_a                        ┆ 245_a │
│ ---                            ┆ ---            ┆ ---                          ┆ ---   │
│ str                            ┆ str            ┆ str                          ┆ u32   │
╞════════════════════════════════╪════════════════╪══════════════════════════════╪═══════╡
│ David, Petr,                   ┆ xx0006786      ┆ Soukup, Vladimír,            ┆ 126   │
│ Nedbalová, Marie               ┆ jo2014816080   ┆ Nedbalová, Josefína          ┆ 87    │
│ Marx, Karl,                    ┆ jn19990005454  ┆ Engels, Friedrich,           ┆ 59    │
│ Benešová, Hana,                ┆ pna2012702164  ┆ Formáčková, Marie,           ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164  ┆ Fukalová, Lenka              ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164  ┆ Vondrák, Jan,                ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164  ┆ Šmíd, Václav,                ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164  ┆ Kanyzová, Žofie,             ┆ 52    │
│ Benešová, Hana,                ┆ pna2012702164  ┆ Příhoda, Pavel,              ┆ 52    │
│ Mihulová, Marie,               ┆ jn20001227798  ┆ Svoboda, Milan               ┆ 43    │
│ Vostrá, Markéta                ┆ js20050801018  ┆ Brožová, Marie,              ┆ 38    │
│ Smíšek, Richard,               ┆ xx0038627      ┆ Smíšková, Zuzana             ┆ 36    │
│ Smíšek, Richard,               ┆ xx0038627      ┆ Smíšková, Kateřina,          ┆ 36    │
│ Nedbalcová, Kateřina           ┆ mzk2015871497  ┆ Zouharová, Monika            ┆ 33    │
│ Voskovec, Jiří,                ┆ jk01150746     ┆ Werich, Jan,                 ┆ 32    │
│ Preston, Douglas J.,           ┆ jn20000810185  ┆ Child, Lincoln,              ┆ 32    │
│ Grimm, Jacob Ludwig Karl,      ┆ jn19981228078  ┆ Grimm, Wilhelm Karl,         ┆ 32    │
│ David, Petr,                   ┆ xx0006786      ┆ Dobrovolná, Věra,            ┆ 30    │
│ Morris,                        ┆ xx0038205      ┆ Goscinny, René,              ┆ 29    │
│ Jirotka, Antonín,              ┆ jx20040623006  ┆ Vaněk, Jan J.,               ┆ 29    │
│ Klečka, Antonín,               ┆ jk01060331     ┆ Kunz, Emil,                  ┆ 28    │
│ Chmelař, František,            ┆ jk01050240     ┆ Šimon, Jaroslav,             ┆ 27    │
│ Kozák, Jan,                    ┆ jk01062553     ┆ Roček, Jan,                  ┆ 26    │
│ Paprčka, Milan,                ┆ osa2014838884  ┆ Hošková, Martina,            ┆ 26    │
│ Marx, Karl,                    ┆ jn19990005454  ┆ Lenin, Vladimir Il‘jič,      ┆ 26    │
│ Stach, Jan,                    ┆ jn20010309343  ┆ Kučera, Miroslav,            ┆ 26    │
│ Bartoňová, Miroslava,          ┆ mzk2004148531  ┆ Vítková, Marie,              ┆ 25    │
│ Bruthans, Jiří                 ┆ jx20090211004  ┆ Kondrová, Lucie,             ┆ 24    │
│ Augusta, Pavel,                ┆ jk01010424     ┆ Honzák, František,           ┆ 24    │
│ Polášková, Jiřina,             ┆ jn20000402028  ┆ Polášek, Jaromír,            ┆ 24    │
│ Bruthans, Jiří                 ┆ jx20090211004  ┆ Bůzek, František             ┆ 24    │
│ Taterová, Milada               ┆ jk01132074     ┆ Novák, Jiří,                 ┆ 23    │
│ Kubálek, Tomáš,                ┆ jo2002103223   ┆ Kubálková, Markéta,          ┆ 23    │
│ Strugackij, Arkadij Natanovič, ┆ jn19990210589  ┆ Strugackij, Boris Natanovič, ┆ 23    │
│ Jirotka, Antonín,              ┆ jx20040623006  ┆ Turková, Zoja,               ┆ 22    │
│ Bruthans, Jiří                 ┆ jx20090211004  ┆ Kadlecová, Renáta            ┆ 22    │
│ Bruthans, Jiří                 ┆ jx20090211004  ┆ Kůrková, Iva,                ┆ 21    │
│ Nedbalcová, Kateřina           ┆ mzk2015871497  ┆ Matiašková, Katarína         ┆ 21    │
│ Patterson, James,              ┆ jo20000076489  ┆ Paetro, Maxine,              ┆ 21    │
│ Beran, Ladislav,               ┆ jn20010310148  ┆ Cílek, Roman,                ┆ 20    │
│ Erben, Bohdan,                 ┆ jk01030523     ┆ Vilikovský, Václav,          ┆ 20    │
│ Lebeda, Tomáš,                 ┆ xx0009219      ┆ Lysek, Jakub,                ┆ 20    │
│ Miler, Zdeněk,                 ┆ jk01081695     ┆ Doskočilová, Hana,           ┆ 20    │
│ Bratršovská, Zdena,            ┆ jk01013004     ┆ Hrdlička, František,         ┆ 20    │
│ Lebeda, Tomáš,                 ┆ xx0009219      ┆ Zymová, Kateřina             ┆ 19    │
│ Lebeda, Tomáš,                 ┆ xx0009219      ┆ Zatloukal, Tomáš,            ┆ 19    │
│ Bruthans, Jiří                 ┆ jx20090211004  ┆ Mlčoch, Bedřich,             ┆ 19    │
│ Bruthans, Jiří                 ┆ jx20090211004  ┆ Skácelová, Zuzana            ┆ 19    │
│ Lebeda, Tomáš,                 ┆ xx0009219      ┆ Marek, Daniel,               ┆ 19    │
│ Vysušil, Jiří,                 ┆ jk01151269     ┆ Macík, Karel,                ┆ 19    │
│ …                              ┆ …              ┆ …                            ┆ …     │
│ Le Duc, Michel                 ┆ xx0024434      ┆ Tordjman, Nathalie,          ┆ 1     │
│ Šutara, Josef,                 ┆ mzk2009512966  ┆ Janda, Václav,               ┆ 1     │
│ Lepš, Jan,                     ┆ xx0031785      ┆ Šmilauer, Petr,              ┆ 1     │
│ Čermák, Ladislav,              ┆ jn19981002578  ┆ Horák, Aleš,                 ┆ 1     │
│ Žaloudek, Věroslav             ┆ jk01153017     ┆ Pokorný, Jiří                ┆ 1     │
│ Kulhánek, Karel,               ┆ jk01070797     ┆ Mašínová, Božena,            ┆ 1     │
│ Pilař, Antonín,                ┆ jk01093048     ┆ Pechoč, Vladimír,            ┆ 1     │
│ Borseková, Kamila,             ┆ xx0231282      ┆ Kotlánová, Eva               ┆ 1     │
│ Róna, Jaroslav,                ┆ jn19990009972  ┆ Rónová, Lucie,               ┆ 1     │
│ Klíma, Milan,                  ┆ jk01060533     ┆ Kubišta, Karel               ┆ 1     │
│ Mazura, Vítězslav              ┆ jx20100803006  ┆ Latner, Jaromír              ┆ 1     │
│ Slováček, Ladislav,            ┆ mzk2007408363  ┆ Jebavý, Ladislav,            ┆ 1     │
│ Bušta, Jaroslav,               ┆ ola2016898870  ┆ Buštová, Adéla               ┆ 1     │
│ Domanický, Petr,               ┆ jo2002102404   ┆ Bechný, Daniel,              ┆ 1     │
│ Žlábek, Vladimír,              ┆ xx0097941      ┆ Červený, Daniel,             ┆ 1     │
│ Čížek, Lukáš,                  ┆ xx0036611      ┆ Čamlík, G.,                  ┆ 1     │
│ Kliment, Pavel                 ┆ jo2002105459   ┆ Petřková, Anna,              ┆ 1     │
│ Andrejsek, Jan                 ┆ null           ┆ Zemánková, Veronika          ┆ 1     │
│ Haas, Štěpán,                  ┆ jk01032887     ┆ Čácha, Josef                 ┆ 1     │
│ Hedges, Alan                   ┆ xx0272651      ┆ Zuranová, Ivana,             ┆ 1     │
│ Montès, Christian              ┆ xx0274577      ┆ Nédélec, Pascale,            ┆ 1     │
│ Jirásková, Lucie               ┆ ntk2017962281  ┆ Macháček, Štěpán,            ┆ 1     │
│ Barton, Geoff                  ┆ jo20201085498  ┆ Ravendale, Ian               ┆ 1     │
│ Pohl, Tomáš,                   ┆ jn19990218085  ┆ Balabán, Petr                ┆ 1     │
│ Lochmannová, Alena,            ┆ kv2016899013   ┆ Šafr, Miroslav,              ┆ 1     │
│ Chovancová, Karolína           ┆ null           ┆ Zadinová, Andrea             ┆ 1     │
│ Kaplová, Františka             ┆ xx0003421      ┆ Turek, Josef,                ┆ 1     │
│ Macháček, Jaroslav             ┆ vse2006316034  ┆ Prokop, Viktor               ┆ 1     │
│ Vaisová, Petra                 ┆ null           ┆ Dolejší, Pavel,              ┆ 1     │
│ Mička, Antonín,                ┆ mzk2002143914  ┆ Škopík, Michal,              ┆ 1     │
│ Sobotková, Veronika,           ┆ mzk2005274817  ┆ Blatný, Marek,               ┆ 1     │
│ Štický, Jiří                   ┆ mzk2016904660  ┆ Váchal, Adam                 ┆ 1     │
│ Kopřiva, Miloš,                ┆ mzk2003202336  ┆ Achten, Henri,               ┆ 1     │
│ Hes, Aleš                      ┆ ola2003206341  ┆ Hrubá, Daniela               ┆ 1     │
│ Arlt, Josef,                   ┆ jo20000079968  ┆ Rublíková, Eva,              ┆ 1     │
│ Pešek, Tomáš                   ┆ ola20191044077 ┆ Novosádová, Monika,          ┆ 1     │
│ Travers, Susan,                ┆ xx0277076      ┆ Holden, Wendy,               ┆ 1     │
│ Mitchell, Eva                  ┆ pna2010563961  ┆ Klímová Chaloupková, Jana,   ┆ 1     │
│ Dovicová, Andrea               ┆ mzk20211102162 ┆ Trávníček, Dušan,            ┆ 1     │
│ Vostrý, Luboš                  ┆ jo2013739901   ┆ Vostrá Vydrová, Hana         ┆ 1     │
│ Skoumal, Aloys,                ┆ jk01111589     ┆ Čep, Jan,                    ┆ 1     │
│ Matějka, Zdeněk,               ┆ jo2015868973   ┆ Čechová, Miluše              ┆ 1     │
│ Bachelard, Gaston,             ┆ ola2002150766  ┆ Richard, Jean-Pierre,        ┆ 1     │
│ Ilík, František,               ┆ mzk2009529083  ┆ Doleželová, Dagmar           ┆ 1     │
│ Volavka, Vojtěch,              ┆ jk01150452     ┆ Volavková-Skořepová, Zdenka, ┆ 1     │
│ Mach, Jiří,                    ┆ jn20010310202  ┆ Hlaváček, Zdeněk             ┆ 1     │
│ Bezunk, Jaroslav               ┆ null           ┆ Habětínek, František         ┆ 1     │
│ Petráň, Josef,                 ┆ jk01092786     ┆ Fuchs, Vilém,                ┆ 1     │
│ Mašek, Petr,                   ┆ jn20000620219  ┆ Antonín, Luboš,              ┆ 1     │
│ Sitenský, Ladislav,            ┆ jk01111376     ┆ Helmich, Karel,              ┆ 1     │
└────────────────────────────────┴────────────────┴──────────────────────────────┴───────┘

In [24]:
df.filter(pl.col("700_a") == "Soukup, Vladimír,").filter(pl.col("100_a") == "David, Petr,")

shape: (197, 68)
┌──────────┬──────────────┬───────────┬────────────────┬───┬───────────┬───────────┬──────┬───────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7     ┆ 100_4          ┆ … ┆ 700_9     ┆ 700_g     ┆ rok  ┆ stran │
│ ---      ┆ ---          ┆ ---       ┆ ---            ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---   │
│ str      ┆ str          ┆ str       ┆ list[str]      ┆   ┆ list[str] ┆ list[str] ┆ i64  ┆ i64   │
╞══════════╪══════════════╪═══════════╪════════════════╪═══╪═══════════╪═══════════╪══════╪═══════╡
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 208   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 191   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 764   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 127   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 143   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 141   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 191   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 405   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 210   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 376   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 184   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 176   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 399   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 392   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 224   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"] ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 168   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 143   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 119   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 175   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 175   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 208   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 147   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 223   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2024 ┆ 263   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 155   │
│ 1        ┆ David, Petr, ┆ xx0006785 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 246   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 344   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 336   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 144   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 191   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 384   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 131   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 199   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 239   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 129   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1994 ┆ 63    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 122   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 318   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2011 ┆ 416   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1996 ┆ 160   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 142   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 138   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"] ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 247   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 119   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 232   │
│ …        ┆ …            ┆ …         ┆ …              ┆ … ┆ …         ┆ …         ┆ …    ┆ …     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"] ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 384   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 264   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 116   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 189   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 215   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 138   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 182   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 157   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 101   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2024 ┆ 365   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2010 ┆ 199   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 170   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 1     │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"] ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 432   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 157   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 168   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 126   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2018 ┆ 552   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 148   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 132   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 150   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 149   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2021 ┆ 231   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 239   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 175   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 150   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 168   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 138   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 247   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 128   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 224   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 328   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 232   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 207   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2013 ┆ 216   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 191   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 95    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 223   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 151   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 135   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 219   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 316   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut", "pht"] ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 472   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 125   │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 87    │
│ 1        ┆ David, Petr, ┆ xx0006786 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 99    │
└──────────┴──────────────┴───────────┴────────────────┴───┴───────────┴───────────┴──────┴───────┘

## Ilustrátorstvo

In [26]:
df_ill = df.filter(pl.col('700_4') == 'ill')

In [27]:
df_ill = df_ill.with_columns(pl.col("100_a").map_elements(hezkejmeno).alias("jmeno1")).with_columns(pl.col("700_a").map_elements(hezkejmeno).alias("jmeno2"))

In [28]:
df_ill = df_ill.with_columns(pl.struct('jmeno1','jmeno2').map_elements(lambda x: kombajmen(x['jmeno1'], x['jmeno2'], radit=False, spojeni="&")).alias("dvojice"))

In [29]:
df_ill.filter(~pl.col("100_7").is_in(nechcemejetam)).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (32_296, 2)
┌─────────────────────────────┬───────┐
│ dvojice                     ┆ 245_a │
│ ---                         ┆ ---   │
│ str                         ┆ u32   │
╞═════════════════════════════╪═══════╡
│ Štíplová & Němeček          ┆ 108   │
│ Nedbalová & Popprová        ┆ 87    │
│ Nedbalová & Poppr           ┆ 68    │
│ Bass & Kratochvíl           ┆ 67    │
│ Švandrlík & Winter-Neprakta ┆ 64    │
│ Čapek & Čapek               ┆ 33    │
│ Pospíšilová & Trsťan        ┆ 31    │
│ Hašek & Lada                ┆ 30    │
│ Rosecká & Růžička           ┆ 28    │
│ Pospíšilová & Vopičková     ┆ 25    │
│ Škodová & Kubašta           ┆ 25    │
│ Foglar & Čermák             ┆ 24    │
│ Čtvrtek & Pilař             ┆ 24    │
│ Tetourová & Plicková        ┆ 23    │
│ Piroddi & Baruzzi           ┆ 23    │
│ Macourek & Born             ┆ 22    │
│ Bednářová & Šmarda          ┆ 21    │
│ Žáček & Born                ┆ 21    │
│ Válková & Kopl              ┆ 21    │
│ Drijverová & Otčenášek      ┆ 21    │
│ Šavlíková & Roverová        ┆ 20    │
│ Steklač & Born              ┆ 19    │
│ Webb & Williams             ┆ 19    │
│ Stará & Starý               ┆ 19    │
│ Kratochvíl & Vydrová        ┆ 19    │
│ Grey & Hora                 ┆ 19    │
│ Walliams & Ross             ┆ 19    │
│ Pospíšilová & Vydrová       ┆ 19    │
│ Potužníková & Jenčíková     ┆ 18    │
│ Felix & Hísek               ┆ 18    │
│ Wenig & Wenig               ┆ 18    │
│ Hrušková & Turek            ┆ 18    │
│ Hrubín & Trnka              ┆ 18    │
│ Dahl & Blake                ┆ 18    │
│ Lebeda & Študlarová         ┆ 17    │
│ Brand & Wowk                ┆ 17    │
│ Schovancová & Schovanec     ┆ 17    │
│ Štíplová & Vančurová        ┆ 17    │
│ Pospíšilová & Sušina        ┆ 17    │
│ Voleská & Scheiner          ┆ 17    │
│ Brandt & Lefin              ┆ 17    │
│ Osborne & Knipping          ┆ 16    │
│ Smolíková & Smolík          ┆ 16    │
│ Ciprová & Němcová           ┆ 16    │
│ Rožnovská & Vydrová         ┆ 16    │
│ Beigel & Goff               ┆ 16    │
│ Běhounek & Junek            ┆ 16    │
│ Simon & Ross                ┆ 16    │
│ Johns & Barč                ┆ 16    │
│ Eislerová & Šplíchal        ┆ 15    │
│ …                           ┆ …     │
│ Mikoláš & Palata            ┆ 1     │
│ Jelagin & Römer             ┆ 1     │
│ Kleibl & Hégr               ┆ 1     │
│ Háková & Fixl               ┆ 1     │
│ Pêgo & Carvalho             ┆ 1     │
│ Havránek & Pešl             ┆ 1     │
│ Mikolášková & Plicková      ┆ 1     │
│ Horst & Mareš               ┆ 1     │
│ Thorvall & Wagnerová        ┆ 1     │
│ Reed & Kincaid              ┆ 1     │
│ Vamba & Štáfl               ┆ 1     │
│ Nováková & Sobek            ┆ 1     │
│ Janáček & Louda             ┆ 1     │
│ Soukup & Franta             ┆ 1     │
│ Rinecker & Činčerová        ┆ 1     │
│ Cupalová & Šradějová        ┆ 1     │
│ Andrejs & Čermák            ┆ 1     │
│ Pastor & Valečka            ┆ 1     │
│ Metzen & Sevilla            ┆ 1     │
│ Fiala & Štěpán              ┆ 1     │
│ >>Žerotína & Kubíček        ┆ 1     │
│ Jodorowsky & Jérémy         ┆ 1     │
│ Dvořák & Špála              ┆ 1     │
│ Orzeszkowa & Andriolli      ┆ 1     │
│ Blažek & Borisova           ┆ 1     │
│ Matějka & Vildt             ┆ 1     │
│ Zahradníček & Boštík        ┆ 1     │
│ Malý & Zmatlíková           ┆ 1     │
│ Pecháček & Bárta            ┆ 1     │
│ Hrnčíř & Lhota              ┆ 1     │
│ Borovský & Korbelová        ┆ 1     │
│ Matina & Vodrážka           ┆ 1     │
│ Frič & Zemina               ┆ 1     │
│ Meyrink & Sivko             ┆ 1     │
│ Šimon & Chlupáček           ┆ 1     │
│ Wiącek & Kwapińska          ┆ 1     │
│ Conner & Lee                ┆ 1     │
│ Faulkner & Bolognese        ┆ 1     │
│ Rajský & Suková             ┆ 1     │
│ Suková & Mašek              ┆ 1     │
│ Keler & Guibert             ┆ 1     │
│ Aleksejev & Zelinka         ┆ 1     │
│ Ewing & Simmonds            ┆ 1     │
│ Nohejl & Rokytová           ┆ 1     │
│ Malinda & Fialová           ┆ 1     │
│ Halačka & Ščotka            ┆ 1     │
│ Iverson & Manco             ┆ 1     │
│ Kořán & Habr                ┆ 1     │
│ Klimek & Vranovský          ┆ 1     │
│ Brikcius & Střížek          ┆ 1     │
└─────────────────────────────┴───────┘

In [30]:
koliktohobylo = df_ill.unique(subset=['100_7','245_a']).filter(~pl.col("100_7").is_in(nechcemejetam)).filter(pl.col("stran") > 30).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

In [31]:
dvojice_aut_ill = df_ill.unique(subset=['100_7','245_a']).filter(~pl.col("100_7").is_in(nechcemejetam)).filter(pl.col("stran") > 30).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True).head(5).select(pl.col("dvojice")).to_series().to_list()
dvojice_aut_ill

['Štíplová & Němeček',
 'Švandrlík & Winter-Neprakta',
 'Pospíšilová & Trsťan',
 'Hašek & Lada',
 'Rosecká & Růžička']

In [32]:
df_ill.filter(~pl.col("100_7").is_in(nechcemejetam)).group_by(['dvojice']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (32_296, 2)
┌─────────────────────────────┬───────┐
│ dvojice                     ┆ 245_a │
│ ---                         ┆ ---   │
│ str                         ┆ u32   │
╞═════════════════════════════╪═══════╡
│ Štíplová & Němeček          ┆ 108   │
│ Nedbalová & Popprová        ┆ 87    │
│ Nedbalová & Poppr           ┆ 68    │
│ Bass & Kratochvíl           ┆ 67    │
│ Švandrlík & Winter-Neprakta ┆ 64    │
│ Čapek & Čapek               ┆ 33    │
│ Pospíšilová & Trsťan        ┆ 31    │
│ Hašek & Lada                ┆ 30    │
│ Rosecká & Růžička           ┆ 28    │
│ Škodová & Kubašta           ┆ 25    │
│ Pospíšilová & Vopičková     ┆ 25    │
│ Čtvrtek & Pilař             ┆ 24    │
│ Foglar & Čermák             ┆ 24    │
│ Piroddi & Baruzzi           ┆ 23    │
│ Tetourová & Plicková        ┆ 23    │
│ Macourek & Born             ┆ 22    │
│ Žáček & Born                ┆ 21    │
│ Drijverová & Otčenášek      ┆ 21    │
│ Bednářová & Šmarda          ┆ 21    │
│ Válková & Kopl              ┆ 21    │
│ Šavlíková & Roverová        ┆ 20    │
│ Stará & Starý               ┆ 19    │
│ Steklač & Born              ┆ 19    │
│ Pospíšilová & Vydrová       ┆ 19    │
│ Walliams & Ross             ┆ 19    │
│ Grey & Hora                 ┆ 19    │
│ Webb & Williams             ┆ 19    │
│ Kratochvíl & Vydrová        ┆ 19    │
│ Hrubín & Trnka              ┆ 18    │
│ Felix & Hísek               ┆ 18    │
│ Hrušková & Turek            ┆ 18    │
│ Wenig & Wenig               ┆ 18    │
│ Potužníková & Jenčíková     ┆ 18    │
│ Dahl & Blake                ┆ 18    │
│ Brand & Wowk                ┆ 17    │
│ Pospíšilová & Sušina        ┆ 17    │
│ Štíplová & Vančurová        ┆ 17    │
│ Schovancová & Schovanec     ┆ 17    │
│ Voleská & Scheiner          ┆ 17    │
│ Brandt & Lefin              ┆ 17    │
│ Lebeda & Študlarová         ┆ 17    │
│ Ciprová & Němcová           ┆ 16    │
│ Běhounek & Junek            ┆ 16    │
│ Smolíková & Smolík          ┆ 16    │
│ Simon & Ross                ┆ 16    │
│ Rožnovská & Vydrová         ┆ 16    │
│ Osborne & Knipping          ┆ 16    │
│ Johns & Barč                ┆ 16    │
│ Beigel & Goff               ┆ 16    │
│ Grey & Ulč                  ┆ 15    │
│ …                           ┆ …     │
│ Horák & Šalda               ┆ 1     │
│ Kibblesmith & Bazaldua      ┆ 1     │
│ Říha & Jüngling             ┆ 1     │
│ Skořepa & Dvořáková         ┆ 1     │
│ Valéry & Konůpek            ┆ 1     │
│ Neubauer & Christoph        ┆ 1     │
│ Rossberg & Kurze            ┆ 1     │
│ Šmidrkal & Skluzáčková      ┆ 1     │
│ Wolker & Hruška             ┆ 1     │
│ Kostrhun & Netopil          ┆ 1     │
│ Milbourne & MacKinnon       ┆ 1     │
│ Czos & Kostrina             ┆ 1     │
│ Šafářová & Davidová         ┆ 1     │
│ Hołuj & Vaca                ┆ 1     │
│ Pospíšil & Blažek           ┆ 1     │
│ Roth & Grossmann            ┆ 1     │
│ Seifert & Born              ┆ 1     │
│ Hübner & Šajnerová          ┆ 1     │
│ Růt & Steiner-Prag          ┆ 1     │
│ Kilianová & Zeman           ┆ 1     │
│ Starý & Maixner             ┆ 1     │
│ Graham & Crisp              ┆ 1     │
│ Solet & Teissig             ┆ 1     │
│ Jaki & Hataya               ┆ 1     │
│ Komínek & Bavor             ┆ 1     │
│ Dickens & Furniss           ┆ 1     │
│ Rowling & Goes              ┆ 1     │
│ Březinová & Morkes          ┆ 1     │
│ Gerstäcker & Čutta          ┆ 1     │
│ Kott & Krejčová             ┆ 1     │
│ Mrštík & Klusáček           ┆ 1     │
│ Skalka & Tripes             ┆ 1     │
│ Vargová & Válka             ┆ 1     │
│ Hrnčíř & Štěrba             ┆ 1     │
│ Kravetz & Born              ┆ 1     │
│ Tomeček & Kobzáň            ┆ 1     │
│ Landers & Hamplová          ┆ 1     │
│ Algarra & Mazali            ┆ 1     │
│ Nedo & Karel                ┆ 1     │
│ Aigner & Pták               ┆ 1     │
│ Bitzanová & Šindler         ┆ 1     │
│ Jachnin & Trnka             ┆ 1     │
│ Syrovátka & Urban           ┆ 1     │
│ Jenčíková-Váňová & Krejčová ┆ 1     │
│ Jakoubková & Kostková       ┆ 1     │
│ Pulec & Měšťánek            ┆ 1     │
│ Hercíková & Fremund         ┆ 1     │
│ Doležalová & Šmídová        ┆ 1     │
│ Horák & Bím                 ┆ 1     │
│ Snyder & Clarke             ┆ 1     │
└─────────────────────────────┴───────┘

In [33]:
import datetime

In [34]:
df_ill.filter(pl.col("dvojice") == "Pospíšilová & Trsťan")

shape: (37, 71)
┌──────────┬──────────────┬───────────────┬───────────┬───┬───────┬─────────────┬─────────────────┬───────────────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7         ┆ 100_4     ┆ … ┆ stran ┆ jmeno1      ┆ jmeno2          ┆ dvojice       │
│ ---      ┆ ---          ┆ ---           ┆ ---       ┆   ┆ ---   ┆ ---         ┆ ---             ┆ ---           │
│ str      ┆ str          ┆ str           ┆ list[str] ┆   ┆ i64   ┆ str         ┆ str             ┆ str           │
╞══════════╪══════════════╪═══════════════╪═══════════╪═══╪═══════╪═════════════╪═════════════════╪═══════════════╡
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 58    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 88    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 131   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 166   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 78    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 112   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 104   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 116   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 152   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 70    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 1     ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 64    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 62    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 119   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
└──────────┴──────────────┴───────────────┴───────────┴───┴───────┴─────────────┴─────────────────┴───────────────┘

In [35]:
do_grafu = df_ill.filter(
    pl.col("dvojice").is_in(dvojice_aut_ill)
).unique(
    subset=['245_a']
).join(
    koliktohobylo, how="left", on="dvojice"
).with_columns(
    pl.col("245_a_right").map_elements(lambda x: str(x) + "×")
).with_columns(
    pl.concat_str([pl.col('245_a_right'), pl.col('dvojice')], separator=' ').alias('dvojice')
)

In [36]:
dvojice_sort = do_grafu.group_by("dvojice").len().sort(by="len",descending=True).select(pl.col("dvojice")).to_series().to_list()
dvojice_sort

['106× Štíplová & Němeček',
 '62× Švandrlík & Winter-Neprakta',
 '30× Pospíšilová & Trsťan',
 '28× Hašek & Lada',
 '27× Rosecká & Růžička']

In [142]:
df_ill.filter(pl.col("dvojice") == "Štíplová & Němeček")

shape: (114, 71)
┌──────────┬───────────┬────────────┬───────────┬───┬───────┬────────────────┬────────────────────┬────────────────────┐
│ 100_ind1 ┆ 100_a     ┆ 100_7      ┆ 100_4     ┆ … ┆ stran ┆ jmeno1         ┆ jmeno2             ┆ dvojice            │
│ ---      ┆ ---       ┆ ---        ┆ ---       ┆   ┆ ---   ┆ ---            ┆ ---                ┆ ---                │
│ str      ┆ str       ┆ str        ┆ list[str] ┆   ┆ i64   ┆ str            ┆ str                ┆ str                │
╞══════════╪═══════════╪════════════╪═══════════╪═══╪═══════╪════════════════╪════════════════════╪════════════════════╡
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 90    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 64    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 143   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 192   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 35    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 47    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 160   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 66    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 162   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 178   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ …        ┆ …         ┆ …          ┆ …         ┆ … ┆ …     ┆ …              ┆ …                  ┆ …                  │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 79    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 11    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 174   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 162   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 143   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 163   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 96    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 143   ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │
│          ┆ Ljuba,    ┆            ┆           ┆   ┆       ┆                ┆                    ┆                    │
│ 1        ┆ Štíplová, ┆ jk01131441 ┆ ["aut"]   ┆ … ┆ 34    ┆ Ljuba Štíplová ┆ Jaroslav Němeček   ┆ Štíplová & Němeček │

In [37]:
df_ill.filter(pl.col("dvojice") == "Pospíšilová & Trsťan")

shape: (37, 71)
┌──────────┬──────────────┬───────────────┬───────────┬───┬───────┬─────────────┬─────────────────┬───────────────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7         ┆ 100_4     ┆ … ┆ stran ┆ jmeno1      ┆ jmeno2          ┆ dvojice       │
│ ---      ┆ ---          ┆ ---           ┆ ---       ┆   ┆ ---   ┆ ---         ┆ ---             ┆ ---           │
│ str      ┆ str          ┆ str           ┆ list[str] ┆   ┆ i64   ┆ str         ┆ str             ┆ str           │
╞══════════╪══════════════╪═══════════════╪═══════════╪═══╪═══════╪═════════════╪═════════════════╪═══════════════╡
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 58    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 88    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 87    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 131   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 166   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 78    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 112   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 80    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 104   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 116   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 152   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 70    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 1     ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 72    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 64    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 71    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 62    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 118   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 119   ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
│ 1        ┆ Pospíšilová, ┆ mzk2006331486 ┆ ["aut"]   ┆ … ┆ 79    ┆ Zuzana      ┆ Drahomír Trsťan ┆ Pospíšilová & │
│          ┆ Zuzana,      ┆               ┆           ┆   ┆       ┆ Pospíšilová ┆                 ┆ Trsťan        │
└──────────┴──────────────┴───────────────┴───────────┴───┴───────┴─────────────┴─────────────────┴───────────────┘

In [38]:
dvojice_sort

['106× Štíplová & Němeček',
 '62× Švandrlík & Winter-Neprakta',
 '30× Pospíšilová & Trsťan',
 '28× Hašek & Lada',
 '27× Rosecká & Růžička']

In [159]:
base_ill = alt.Chart(
    alt_friendly(do_grafu), 
    title=alt.TitleParams(f"{len(dvojice_aut_ill)} nejčastějších dvojic autor/ka-ilustrátor/ka (bez reprintů)")).mark_circle(size=7, filled=True) 

tecky_ill = base_ill.encode(
            x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6')), 
            y=alt.Y("dvojice:N", sort=dvojice_sort, title=None, axis=alt.Axis(orient='left', domainOpacity=0, tickColor='white', labelExpr='split(datum.label, "× ")[1]')), 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[3, 15])), 
            color=alt.Color('dvojice:N', scale=alt.Scale(range=['#E09DA3']), 
                            sort=dvojice_sort).legend(None)) \
        .transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

pocty_ill = base_ill.mark_text().encode(x=alt.X('rok:T', title=None), 
    y=alt.Y('dvojice:N', title=None, sort=dvojice_sort, axis=alt.Axis(orient="right", tickColor='white', labelExpr='split(datum.label, " ")[0]')))

zebricek_ill = alt.layer(tecky_ill, pocty_ill).configure_view(stroke='transparent').properties(
    width=kredity['sirka'] * 1.25, 
    autosize={'type': 'fit', 'contains': 'padding'}
)

zebricek_ill

alt.LayerChart(...)

In [40]:
do_grafu.filter(pl.col('100_a').str.contains('Hašek')).select(pl.col("245_a")).to_series().to_list()

['Veselé povídky',
 'Aféra s křečkem a jiné povídky',
 'Hašek v kostce',
 'Zpověď starého mládence',
 'Oslí historie, aneb, Vojenské články do čítanek',
 'Postrach domu',
 'Humoresky',
 'Osudy dobrého vojáka Švejka za světové války',
 'Dekameron humoru a satiry',
 'Povídky',
 'Potměšilé historie',
 'Osudy dobrého vojáka Švejka',
 'Má drahá přítelkyně Julča',
 'Nešťastný policejní ředitel',
 'Všivá historie a jiné humoresky',
 'Dva tucty povídek',
 'Když kvetou třešně a jiné humoresky',
 'Průvodčí cizinců a jiné satiry z cest i z domova',
 'Malá zoologická zahrada',
 'Švejk před světovou válkou, Velitelem města Bugulmy a další příběhy',
 'Za války i za sovětů v Rusku',
 'Smějeme se s Jaroslavem Haškem',
 'Procházka přes hranice',
 'Ze staré droguerie',
 'Turista Aratáš a jiné humoresky',
 'Když bolševici zrušili Vánoce',
 'Pod věchýtkem humoru',
 'Útrapy vychovatele',
 'Dobrý voják Švejk před válkou a jiné podivné historky',
 'Reelní podnik']

In [161]:
me_to_neurazi(zebricek_ill, soubor="02_psali_ilustrovali", kredity=kredity['default'])

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_psali_ilustrovali.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_psali_ilustrovali.svg" width="100%" alt="Omlouváme se, ale alternativní text se nepodařilo vygenerovat. Texty v grafu by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

In [42]:
df_ill.group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (34_493, 4)
┌──────────────────────────────┬────────────────┬─────────────────────────────┬───────┐
│ 100_a                        ┆ 100_7          ┆ 700_a                       ┆ 245_a │
│ ---                          ┆ ---            ┆ ---                         ┆ ---   │
│ str                          ┆ str            ┆ str                         ┆ u32   │
╞══════════════════════════════╪════════════════╪═════════════════════════════╪═══════╡
│ Štíplová, Ljuba,             ┆ jk01131441     ┆ Němeček, Jaroslav,          ┆ 108   │
│ Nedbalová, Marie             ┆ jo2014816080   ┆ Popprová, Andrea            ┆ 87    │
│ Nedbalová, Marie             ┆ jo2014816080   ┆ Poppr, Roman                ┆ 68    │
│ Bass, Eduard,                ┆ jk01011066     ┆ Kratochvíl, Zdeněk,         ┆ 67    │
│ Švandrlík, Miloslav,         ┆ jk01131832     ┆ Winter-Neprakta, Jiří,      ┆ 64    │
│ Wilson, Jacqueline,          ┆ jn20010310318  ┆ Sharratt, Nick,             ┆ 52    │
│ Delahaye, Gilbert,           ┆ xx0203193      ┆ Marlier, Marcel,            ┆ 51    │
│ Verne, Jules,                ┆ jn19990008769  ┆ Benett, Léon,               ┆ 50    │
│ Brezina, Thomas,             ┆ jn20001227589  ┆ Fearn, Naomi,               ┆ 43    │
│ Goscinny, René,              ┆ jn20000602144  ┆ Uderzo, Albert,             ┆ 42    │
│ Verne, Jules,                ┆ jn19990008769  ┆ Roux, George,               ┆ 42    │
│ Deary, Terry,                ┆ jn20001103401  ┆ Brown, Martin,              ┆ 36    │
│ Arnold, Nick,                ┆ xx0008006      ┆ De Saulles, Tony            ┆ 33    │
│ Čapek, Karel,                ┆ jk01021023     ┆ Čapek, Josef,               ┆ 33    │
│ Pospíšilová, Zuzana,         ┆ mzk2006331486  ┆ Trsťan, Drahomír,           ┆ 31    │
│ Meadows, Daisy               ┆ xx0082647      ┆ Ripper, Georgie,            ┆ 29    │
│ Hašek, Jaroslav,             ┆ jk01040097     ┆ Lada, Josef,                ┆ 29    │
│ Rosecká, Zdena               ┆ jx20031130107  ┆ Růžička, Jiří               ┆ 28    │
│ Pospíšilová, Zuzana,         ┆ mzk2006331486  ┆ Vopičková, Vladimíra        ┆ 25    │
│ Škodová, Helena,             ┆ jx20040618039  ┆ Kubašta, Vojtěch,           ┆ 25    │
│ Awdry, W.,                   ┆ xx0010566      ┆ Davies, Robin,              ┆ 24    │
│ Čtvrtek, Václav,             ┆ jk01021929     ┆ Pilař, Radek,               ┆ 24    │
│ Piroddi, Chiara,             ┆ osa2017965599  ┆ Baruzzi, Agnese,            ┆ 23    │
│ Burroughs, Edgar Rice,       ┆ jn19990001239  ┆ Pešek, Richard,             ┆ 23    │
│ Tetourová, Marie,            ┆ jn20001005512  ┆ Plicková, Edita,            ┆ 23    │
│ Awdry, W.,                   ┆ xx0010566      ┆ Smith, Jerry                ┆ 23    │
│ Foglar, Jaroslav,            ┆ jk01031485     ┆ Čermák, Marko,              ┆ 22    │
│ Macourek, Miloš,             ┆ jk01072813     ┆ Born, Adolf,                ┆ 22    │
│ May, Karl,                   ┆ jn19990005499  ┆ Krum, Gustav,               ┆ 21    │
│ Drijverová, Martina,         ┆ jk01023067     ┆ Otčenášek, Vojtěch,         ┆ 21    │
│ Bednářová, Jiřina,           ┆ mzk2004248919  ┆ Šmarda, Richard,            ┆ 21    │
│ Válková, Veronika,           ┆ jo2005274171   ┆ Kopl, Petr,                 ┆ 21    │
│ Žáček, Jiří,                 ┆ jk01152946     ┆ Born, Adolf,                ┆ 21    │
│ Šavlíková, Lucie,            ┆ jn19981002458  ┆ Roverová, Eva               ┆ 20    │
│ Steklač, Vojtěch,            ┆ jk01121138     ┆ Born, Adolf,                ┆ 19    │
│ Walliams, David,             ┆ xx0158956      ┆ Ross, Tony,                 ┆ 19    │
│ Kratochvíl, Miloš,           ┆ jk01062996     ┆ Vydrová, Markéta,           ┆ 19    │
│ May, Karl,                   ┆ jn19990005499  ┆ Ulrich, Josef,              ┆ 19    │
│ Webb, Holly                  ┆ ola2010577122  ┆ Williams, Sophy             ┆ 19    │
│ Pospíšilová, Zuzana,         ┆ mzk2006331486  ┆ Vydrová, Markéta,           ┆ 19    │
│ Stará, Ester,                ┆ mzk2004261153  ┆ Starý, Milan,               ┆ 19    │
│ Grey, Zane,                  ┆ jn19990002874  ┆ Hora, Jan,                  ┆ 19    │
│ Potužníková, Ema             ┆ xx0244812      ┆ Jenčíková, Lucie            ┆ 18    │
│ Hrušková, Marie,             ┆ jn20000401097  ┆ Turek, Jaroslav,            ┆ 18    │
│ Dahl, Roald,                 ┆ jn19990001595  ┆ Blake, Quentin,             ┆ 18    │
│ May, Karl,                   ┆ jn19990005499  ┆ Černý, Věnceslav,           ┆ 18    │
│ May, Karl,                   ┆ jn19990005499  ┆ Burian, Zdeněk,             ┆ 18    │
│ Felix, Jiří,                 ┆ jk01030870     ┆ Hísek, Květoslav,           ┆ 18    │
│ Hrubín, František,           ┆ jk01042920     ┆ Trnka, Jiří,                ┆ 18    │
│ Brezina, Thomas,             ┆ jn20001227589  ┆ Gotzen-Beek, Betina,        ┆ 18    │
│ …                            ┆ …              ┆ …                           ┆ …     │
│ Matějka, Jaroslav,           ┆ jk01080656     ┆ Kovářík, Vladimír,          ┆ 1     │
│ Erben, Karel Jaromír,        ┆ jk01030532     ┆ Prousek, Jan,               ┆ 1     │
│ Bílek, Jiří,                 ┆ xx0001277      ┆ Dudková, Světla             ┆ 1     │
│ Červenka, Jaromír,           ┆ xx0010656      ┆ Meisnerová Gruntová, Šárka  ┆ 1     │
│ Tollu, Cindy                 ┆ ola20211117854 ┆ Grard, Emmanuel,            ┆ 1     │
│ Březinová, Ivona,            ┆ jn19990218010  ┆ Šedivá, Eva,                ┆ 1     │
│ Pak, Viktor,                 ┆ xx0321654      ┆ Račanská, Markéta,          ┆ 1     │
│ Hale, Edward Everest         ┆ null           ┆ Kalina, Karel,              ┆ 1     │
│ Šulová, Anežka,              ┆ jk01131698     ┆ Mikulka, Alois,             ┆ 1     │
│ Šindelář, Vladimír,          ┆ jn20011018818  ┆ Slouková, Kristýna,         ┆ 1     │
│ Lilia, Hermor,               ┆ jo2015883238   ┆ Šerých, Jaroslav,           ┆ 1     │
│ Hlaváček, Libor,             ┆ mzk2005279545  ┆ Vlach, Dalibor,             ┆ 1     │
│ Narciso, Massimiliano,       ┆ ola2009531504  ┆ Ferrari, Marieke,           ┆ 1     │
│ Hlaváček, Emil,              ┆ xx0178190      ┆ Hlaváček, Martin            ┆ 1     │
│ Kopic, Bořivoj,              ┆ jk01061721     ┆ Šindler, Jiří,              ┆ 1     │
│ Řehák, Stanislav,            ┆ jk01110032     ┆ Schulz, Gustav Jaroslav,    ┆ 1     │
│ Černošová, Eva,              ┆ mzk2006348944  ┆ Hrabinec, Jiří,             ┆ 1     │
│ Dorance, Sylvia              ┆ xx0084835      ┆ Beaumont, Annie             ┆ 1     │
│ Baicker, Karen               ┆ mzk2009502351  ┆ Goodell, Jon                ┆ 1     │
│ Kraft, Robert,               ┆ jn20010310250  ┆ Pospíchal, Josef,           ┆ 1     │
│ Vosátka, Josef,              ┆ mzk2009521530  ┆ Míča, Miroslav              ┆ 1     │
│ Davis, Jon,                  ┆ mzk2007377610  ┆ Hencl, Milan,               ┆ 1     │
│ Przeczek, Wilhelm,           ┆ jn19990006732  ┆ Kresowaty, Zbigniew         ┆ 1     │
│ Spurný, Jan,                 ┆ jz8600965      ┆ Kybal, Antonín,             ┆ 1     │
│ Makásek Hiawatha, Ivan,      ┆ mzk2003175452  ┆ Hora, Jan,                  ┆ 1     │
│ Beljajev, Vladimir Pavlovič, ┆ jx20040617002  ┆ Burant, František,          ┆ 1     │
│ Grubešlieva, Marija,         ┆ jn20000602645  ┆ Malát, Radim,               ┆ 1     │
│ Kirschnerová, Denisa,        ┆ jn20000620160  ┆ Grus, Jiří,                 ┆ 1     │
│ Valoch, Karel,               ┆ jk01141319     ┆ Najmrová, Libuše            ┆ 1     │
│ Říčan, Pavel,                ┆ jk01110151     ┆ Hrubý, Jan,                 ┆ 1     │
│ Studnička, František         ┆ jk01121580     ┆ Fiala, Václav               ┆ 1     │
│ Miler, Karel,                ┆ jn20000401793  ┆ Komárek, Vladimír,          ┆ 1     │
│ Ježková, Alena,              ┆ xx0002238      ┆ Nikkarin,                   ┆ 1     │
│ Bochořák, Klement,           ┆ jk01012559     ┆ Vořechová-Vejvodová, Marie, ┆ 1     │
│ Corazza, Verena,             ┆ xx0094854      ┆ Schwarzer, Eitel            ┆ 1     │
│ Tordjman, Nathalie,          ┆ mzk2004233176  ┆ Simler, Isabelle            ┆ 1     │
│ Průchová, Adéla,             ┆ jk01101433     ┆ Zpěvák, Jaromír,            ┆ 1     │
│ Gál, Václav                  ┆ mzk2008479721  ┆ Renčín, Vladimír,           ┆ 1     │
│ Konečná, Kateřina,           ┆ mzk2006322913  ┆ Marčák, Michal,             ┆ 1     │
│ Fischerová, Viola,           ┆ jk01031308     ┆ Šlapetová, Barbora,         ┆ 1     │
│ Peroutková, Ivana,           ┆ jn20000401963  ┆ Klementová, Zuzana,         ┆ 1     │
│ Šikula, Jaromír,             ┆ jk01122897     ┆ Štolfa, Vojtěch,            ┆ 1     │
│ Hawksley, Julie              ┆ mzk2009529116  ┆ Petty, Colin                ┆ 1     │
│ Janíková, Jana,              ┆ mzk2002157045  ┆ Chytková, Eliška,           ┆ 1     │
│ Dale, Elizabeth,             ┆ xx0166780      ┆ Scott, Kimberley            ┆ 1     │
│ Werich, Jan,                 ┆ jk01151601     ┆ Suchý, Jiří,                ┆ 1     │
│ Vámos, Miklós,               ┆ xx0068518      ┆ Borůvka, Vladimír           ┆ 1     │
│ Humphries, Sam,              ┆ xx0243080      ┆ Garbowska, Agnes            ┆ 1     │
│ Slavíčková, Jitka            ┆ ola2015855627  ┆ Kochová, Aneta              ┆ 1     │
│ Váňa, Jaroslav,              ┆ mzk2004258403  ┆ Procházka, Otakar           ┆ 1     │
└──────────────────────────────┴────────────────┴─────────────────────────────┴───────┘

In [43]:
ctyrlistek_leader = " <leader>     cam a22      a 4500"
ctyrlistek_leader = ctyrlistek_leader.split(">")[1]
print(ctyrlistek_leader[6])
print(ctyrlistek_leader[7])

a
m

In [44]:
df.filter(pl.col('700_4') == 'ill').filter(~pl.col("100_7").is_in(nechcemejetam)).group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True).rename({'100_a':'autor/ka','700_a':'ilustrátor/ka','245_a':'společných knih'}).drop("100_7")

shape: (32_606, 3)
┌───────────────────────────────┬─────────────────────────────┬─────────────────┐
│ autor/ka                      ┆ ilustrátor/ka               ┆ společných knih │
│ ---                           ┆ ---                         ┆ ---             │
│ str                           ┆ str                         ┆ u32             │
╞═══════════════════════════════╪═════════════════════════════╪═════════════════╡
│ Štíplová, Ljuba,              ┆ Němeček, Jaroslav,          ┆ 108             │
│ Nedbalová, Marie              ┆ Popprová, Andrea            ┆ 87              │
│ Nedbalová, Marie              ┆ Poppr, Roman                ┆ 68              │
│ Bass, Eduard,                 ┆ Kratochvíl, Zdeněk,         ┆ 67              │
│ Švandrlík, Miloslav,          ┆ Winter-Neprakta, Jiří,      ┆ 64              │
│ Čapek, Karel,                 ┆ Čapek, Josef,               ┆ 33              │
│ Pospíšilová, Zuzana,          ┆ Trsťan, Drahomír,           ┆ 31              │
│ Hašek, Jaroslav,              ┆ Lada, Josef,                ┆ 29              │
│ Rosecká, Zdena                ┆ Růžička, Jiří               ┆ 28              │
│ Pospíšilová, Zuzana,          ┆ Vopičková, Vladimíra        ┆ 25              │
│ Škodová, Helena,              ┆ Kubašta, Vojtěch,           ┆ 25              │
│ Čtvrtek, Václav,              ┆ Pilař, Radek,               ┆ 24              │
│ Piroddi, Chiara,              ┆ Baruzzi, Agnese,            ┆ 23              │
│ Tetourová, Marie,             ┆ Plicková, Edita,            ┆ 23              │
│ Foglar, Jaroslav,             ┆ Čermák, Marko,              ┆ 22              │
│ Macourek, Miloš,              ┆ Born, Adolf,                ┆ 22              │
│ Drijverová, Martina,          ┆ Otčenášek, Vojtěch,         ┆ 21              │
│ Válková, Veronika,            ┆ Kopl, Petr,                 ┆ 21              │
│ Žáček, Jiří,                  ┆ Born, Adolf,                ┆ 21              │
│ Bednářová, Jiřina,            ┆ Šmarda, Richard,            ┆ 21              │
│ Šavlíková, Lucie,             ┆ Roverová, Eva               ┆ 20              │
│ Stará, Ester,                 ┆ Starý, Milan,               ┆ 19              │
│ Walliams, David,              ┆ Ross, Tony,                 ┆ 19              │
│ Grey, Zane,                   ┆ Hora, Jan,                  ┆ 19              │
│ Steklač, Vojtěch,             ┆ Born, Adolf,                ┆ 19              │
│ Webb, Holly                   ┆ Williams, Sophy             ┆ 19              │
│ Pospíšilová, Zuzana,          ┆ Vydrová, Markéta,           ┆ 19              │
│ Kratochvíl, Miloš,            ┆ Vydrová, Markéta,           ┆ 19              │
│ Hrubín, František,            ┆ Trnka, Jiří,                ┆ 18              │
│ Felix, Jiří,                  ┆ Hísek, Květoslav,           ┆ 18              │
│ Hrušková, Marie,              ┆ Turek, Jaroslav,            ┆ 18              │
│ Dahl, Roald,                  ┆ Blake, Quentin,             ┆ 18              │
│ Potužníková, Ema              ┆ Jenčíková, Lucie            ┆ 18              │
│ Brand, Max,                   ┆ Wowk, Jiří,                 ┆ 17              │
│ Brandt, Susanne,              ┆ Lefin, Petra,               ┆ 17              │
│ Schovancová, Běla,            ┆ Schovanec, Ladislav,        ┆ 17              │
│ Pospíšilová, Zuzana,          ┆ Sušina, Michal              ┆ 17              │
│ Štíplová, Ljuba,              ┆ Janoušková Vančurová, Alena ┆ 17              │
│ Voleská, Marta,               ┆ Scheiner, Artuš,            ┆ 17              │
│ Lebeda, Jan,                  ┆ Študlarová, Zdeňka,         ┆ 17              │
│ Běhounek, František,          ┆ Junek, Václav,              ┆ 16              │
│ Johns, William Earl,          ┆ Barč, Petr,                 ┆ 16              │
│ Simon, Francesca,             ┆ Ross, Tony,                 ┆ 16              │
│ Ciprová, Oldřiška,            ┆ Němcová, Lenka,             ┆ 16              │
│ Smolíková, Klára,             ┆ Smolík, Jan,                ┆ 16              │
│ Beigel, Christine,            ┆ Le Goff, Hervé,             ┆ 16              │
│ Rožnovská, Lenka,             ┆ Vydrová, Markéta,           ┆ 16              │
│ Osborne, Mary Pope,           ┆ Knipping, Jutta,            ┆ 16              │
│ Eislerová, Jana,              ┆ Šplíchal, Antonín,          ┆ 15              │
│ Friedrich, Joachim,           ┆ Páv, Libor,                 ┆ 14              │
│ …                             ┆ …                           ┆ …               │
│ Svobodová, Martina,           ┆ Sojková, Irena,             ┆ 1               │
│ Kelly, Milena,                ┆ Pekárek, Jaroslav           ┆ 1               │
│ Nejedlý, Zdeněk,              ┆ Sůra, Jaroslav,             ┆ 1               │
│ Čtvrtek, Václav,              ┆ Foll, Dobroslav,            ┆ 1               │
│ Hewat, Katie                  ┆ Massari, Alida,             ┆ 1               │
│ Kohoutek, Jiří,               ┆ Pavlů, Miroslav J. V.,      ┆ 1               │
│ Kraus, Vilém,                 ┆ Balog, František            ┆ 1               │
│ Luxová, Blanka,               ┆ Stopka, Adéla,              ┆ 1               │
│ Baxter, Nicola                ┆ Manson, Beverlie            ┆ 1               │
│ Mrázková, Eva                 ┆ Drobný, Libor,              ┆ 1               │
│ Mráz, Karel,                  ┆ Kilán, Otakar               ┆ 1               │
│ Preußler, Otfried,            ┆ Hansen, Christiane,         ┆ 1               │
│ Schubert, Fredy,              ┆ Ryvola, Miki,               ┆ 1               │
│ Williams, Rob                 ┆ Williams, Scott,            ┆ 1               │
│ Mráz, Bohumír,                ┆ Medek, Mikuláš,             ┆ 1               │
│ Hrubý, Vladimír,              ┆ Machata, Libor,             ┆ 1               │
│ Hiršal, Josef,                ┆ Lužná, Jana                 ┆ 1               │
│ Faltus, Jiří,                 ┆ Korbelářová, Andréa,        ┆ 1               │
│ Lugovik, Marijka              ┆ Us, Sofia                   ┆ 1               │
│ Stýblová, Valja,              ┆ Ronovský, František,        ┆ 1               │
│ Kubátová, Marie,              ┆ Renčín, Vladimír,           ┆ 1               │
│ Hons, Josef,                  ┆ Rocman, Vladimír,           ┆ 1               │
│ Morrisroe, Rachel             ┆ Lenton, Steven,             ┆ 1               │
│ Kalaš, Petr,                  ┆ Petrášová, Jitka,           ┆ 1               │
│ Bianki, Vitalij Valentinovič, ┆ Lesková, Vilma,             ┆ 1               │
│ Willingham, Bill,             ┆ Hamilton, Craig,            ┆ 1               │
│ Husák, Pavel                  ┆ Štolfa, Miroslav,           ┆ 1               │
│ Goethe, Johann Wolfgang von,  ┆ Dillinger, Petr,            ┆ 1               │
│ Novotná, Jarmila              ┆ Rampl, Karel,               ┆ 1               │
│ Smotlacha, Miroslav,          ┆ Novák, Josef,               ┆ 1               │
│ Eastman, Kevin B.,            ┆ Gallant, S. L.              ┆ 1               │
│ Bílý, Svatopluk,              ┆ Brantlová, Simona           ┆ 1               │
│ Plowman, Graham               ┆ Dewhurst, Matthew           ┆ 1               │
│ Gazda, Jaroslav,              ┆ Střihavková, Hana,          ┆ 1               │
│ Čajaková, Kornélia            ┆ Hložník, Ferdinand,         ┆ 1               │
│ Lindell, Unni,                ┆ Skavlan, Fredrik,           ┆ 1               │
│ Rix, Megan,                   ┆ Budgen, Tim,                ┆ 1               │
│ Gruber, David,                ┆ Kliský, Roman,              ┆ 1               │
│ Nettel, Guadalupe,            ┆ Hřivnáč, Tomáš,             ┆ 1               │
│ Křelina, František,           ┆ Chvojková, Helena,          ┆ 1               │
│ Salaquardová, Jiřina,         ┆ Ždímal, Dušan,              ┆ 1               │
│ Radović, Dušan,               ┆ Pilař, Radek,               ┆ 1               │
│ Jakeš, Antonín,               ┆ Winter-Neprakta, Jiří,      ┆ 1               │
│ Schneidermann, Brigitte       ┆ Jankovics, György           ┆ 1               │
│ Bertolazzi, Alberto           ┆ Sacco, Mauro                ┆ 1               │
│ Děták, Jaroslav,              ┆ Škopek, Jiří,               ┆ 1               │
│ Vilímek, Josef Richard,       ┆ Olíva, Viktor,              ┆ 1               │
│ Augusta, Oldřich,             ┆ Mytysková, Anna,            ┆ 1               │
│ Kasanda, Karel,               ┆ Kursell, Otto von,          ┆ 1               │
│ Dvořák, Josef                 ┆ Dostál, Jaroslav,           ┆ 1               │
└───────────────────────────────┴─────────────────────────────┴─────────────────┘

In [45]:
df.filter(pl.col('700_4') == 'trl').group_by(['100_a','100_7','700_a']).agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (66_400, 4)
┌────────────────────────────────┬───────────────────┬───────────────────────────────┬───────┐
│ 100_a                          ┆ 100_7             ┆ 700_a                         ┆ 245_a │
│ ---                            ┆ ---               ┆ ---                           ┆ ---   │
│ str                            ┆ str               ┆ str                           ┆ u32   │
╞════════════════════════════════╪═══════════════════╪═══════════════════════════════╪═══════╡
│ Unger, Gert F.,                ┆ jn20001103529     ┆ Butala, Tomáš,                ┆ 311   │
│ Kirby, John                    ┆ jx20040611003     ┆ Pavka, Marek,                 ┆ 182   │
│ Courths-Mahler, Hedwig,        ┆ jn19990001513     ┆ Schönová, Zuzana              ┆ 120   │
│ Scott, William,                ┆ ola2003188680     ┆ Butala, Tomáš,                ┆ 101   │
│ Birkner-Mahler, Frieda,        ┆ jn20000600873     ┆ Lacinová, Libuše,             ┆ 80    │
│ Unger, Gert F.,                ┆ jn20001103529     ┆ Schönová, Zuzana              ┆ 80    │
│ Unger, Gert F.,                ┆ jn20001103529     ┆ Sedláčková, Libuše            ┆ 77    │
│ Pratchett, Terry,              ┆ jo20000080627     ┆ Kantůrek, Jan,                ┆ 57    │
│ Brezina, Thomas,               ┆ jn20001227589     ┆ Steidlová, Dagmar,            ┆ 55    │
│ Courths-Mahler, Hedwig,        ┆ jn19990001513     ┆ Lacinová, Libuše,             ┆ 54    │
│ Lane, Lex                      ┆ ola2007364818     ┆ Pavka, Marek,                 ┆ 53    │
│ Dark, Jason,                   ┆ jn20000810032     ┆ Sychra, Pavel                 ┆ 50    │
│ Nieritz, Gustav,               ┆ jo20000080760     ┆ Tomsa, František Bohumil,     ┆ 49    │
│ Unger, Gert F.,                ┆ jn20001103529     ┆ Sychra, Pavel                 ┆ 48    │
│ Dark, Jason,                   ┆ jn20000810032     ┆ Küchler, Marek                ┆ 48    │
│ Hayes, Rex,                    ┆ jn20020717154     ┆ Pavka, Marek,                 ┆ 47    │
│ Shakespeare, William,          ┆ jn19981002129     ┆ Sládek, Josef Václav,         ┆ 46    │
│ Etzold, Hans-Rüdiger,          ┆ xx0020263         ┆ Hlásek, Pavel                 ┆ 45    │
│ Steiner, Rudolf,               ┆ jn19990009728     ┆ Hradil, Radomil,              ┆ 45    │
│ Wallace, Edgar,                ┆ jn19990008883     ┆ Heller, František             ┆ 43    │
│ Francis, Dick,                 ┆ jn19990002376     ┆ Moserová, Jaroslava,          ┆ 43    │
│ Mark, William,                 ┆ jo20241218643     ┆ Kuťák, Jaroslav,              ┆ 42    │
│ Shakespeare, William,          ┆ jn19981002129     ┆ Hilský, Martin,               ┆ 42    │
│ Davis, Jim,                    ┆ jn20010601536     ┆ Škába, Filip,                 ┆ 42    │
│ Velden, Irene von              ┆ jx20031204026     ┆ Chromiaková, Eva              ┆ 40    │
│ May, Karl,                     ┆ jn19990005499     ┆ Šunda, Vladimír               ┆ 39    │
│ Wilson, Jacqueline,            ┆ jn20010310318     ┆ Feltová, Daniela,             ┆ 38    │
│ Unger, Gert F.,                ┆ jn20001103529     ┆ Veselý, Milan                 ┆ 38    │
│ Verne, Jules,                  ┆ jn19990008769     ┆ Unzeitig, Vítězslav,          ┆ 38    │
│ Dark, Jason,                   ┆ jn20000810032     ┆ Brzobohatý, Rostislav         ┆ 35    │
│ Patterson, James,              ┆ jo20000076489     ┆ Duha, Ondřej                  ┆ 35    │
│ Wild, Dunja                    ┆ ola20040510003    ┆ Smolaková, Helena             ┆ 35    │
│ Cartland, Barbara,             ┆ jn19990001350     ┆ Volná, Kristina,              ┆ 34    │
│ Andrée, Michaela               ┆ ola2003188685     ┆ Smolaková, Helena             ┆ 34    │
│ Platón,                        ┆ jn19981001996     ┆ Novotný, František,           ┆ 33    │
│ McBain, Ed,                    ┆ jn19981001834     ┆ Maxová, Alena,                ┆ 33    │
│ Ošó,                           ┆ jn19981001926     ┆ Žlábková, Jana,               ┆ 32    │
│ King, Stephen,                 ┆ jn19990004346     ┆ Bartošková, Linda,            ┆ 32    │
│ Deaver, Jeffery,               ┆ jn20001103550     ┆ Kobělka, Jiří,                ┆ 31    │
│ Murphy, Bill,                  ┆ mzk2008443048     ┆ Pavka, Marek,                 ┆ 31    │
│ Vandenberg, Patricia,          ┆ jn20000810141     ┆ Všetulová, Marisa             ┆ 31    │
│ Everett, Jack,                 ┆ jn20020717155     ┆ Pavka, Marek,                 ┆ 31    │
│ Billet, Marion,                ┆ xx0206378         ┆ Kocmanová, Ivana,             ┆ 28    │
│ Dán, Dominik,                  ┆ xx0085412         ┆ Hanzlík, Jan                  ┆ 27    │
│ Doyle, Arthur Conan,           ┆ jn19990001842     ┆ Pachmayer, Josef,             ┆ 27    │
│ Choux, Nathalie,               ┆ xx0200182         ┆ Vyskočil, Josef               ┆ 27    │
│ Stephan, Sabine                ┆ jn20010309603     ┆ Smolaková, Helena             ┆ 26    │
│ Hergé,                         ┆ xx0019604         ┆ Vinšová, Kateřina,            ┆ 26    │
│ Vandenberg, Patricia,          ┆ jn20000810141     ┆ Podolská, Zora                ┆ 25    │
│ Shakespeare, William,          ┆ jn19981002129     ┆ Saudek, Erik Adolf,           ┆ 24    │
│ …                              ┆ …                 ┆ …                             ┆ …     │
│ Frankl, Viktor Emil,           ┆ jn19990009561     ┆ Balcar, Karel,                ┆ 1     │
│ Klymenko, Oleksandr Ìvanovyč,  ┆ mzk2018979853     ┆ Dědinová, Nikola              ┆ 1     │
│ Kašafutdinov, Il‘ja,           ┆ kup19970000047006 ┆ Chrobák, Kamil,               ┆ 1     │
│ Wild, Dunja                    ┆ ola20040510003    ┆ Chromiaková, Eva              ┆ 1     │
│ Kesselring, Albert,            ┆ jn20000700883     ┆ Čadský, Vladimír              ┆ 1     │
│ Wilson, Neil,                  ┆ mzk2005289996     ┆ Cachová, Eva                  ┆ 1     │
│ De Quincey, Thomas,            ┆ jn20010316118     ┆ Procházka, Arnošt,            ┆ 1     │
│ Bonsels, Waldemar,             ┆ jn20030916001     ┆ Jirda, Miloslav,              ┆ 1     │
│ Polaschewski, Edwin            ┆ null              ┆ Hoffmann, Václav,             ┆ 1     │
│ Bergeret, Gaston,              ┆ hka20191051143    ┆ Beneš Šumavský, Václav,       ┆ 1     │
│ Hopping, Lorraine Jean,        ┆ osa20181005914    ┆ Pešková, Lenka                ┆ 1     │
│ Plomin, Robert,                ┆ hka20191042676    ┆ Drlík, Filip,                 ┆ 1     │
│ Myszogląd, Marcin              ┆ null              ┆ Kuchejda, Tadeusz             ┆ 1     │
│ Katz, Robert,                  ┆ jx20070711012     ┆ Miller, Robert,               ┆ 1     │
│ Schroeder, Karl                ┆ null              ┆ Rektorys, Artuš,              ┆ 1     │
│ Hoffmeier, Mark                ┆ mzk2016900568     ┆ Belejová, Katarína            ┆ 1     │
│ Xiao, San,                     ┆ xx0102103         ┆ Šťovíčková, Dana,             ┆ 1     │
│ Ponomarev, Boris Nikolajevič,  ┆ jx20040217016     ┆ Filip, Eudoros Myrtilos       ┆ 1     │
│ Parnov, Jeremej Iudovič,       ┆ jn20000604355     ┆ Andrle, Pavel,                ┆ 1     │
│ Bower, Sarah,                  ┆ xx0150257         ┆ Křístková, Eva                ┆ 1     │
│ Gordejev, Vsevolod Borisovič   ┆ jx20080930043     ┆ Horská, Hana                  ┆ 1     │
│ Oyono, Ferdinand,              ┆ ola2003169735     ┆ Kajdoš, Václav,               ┆ 1     │
│ Bevan, Mike                    ┆ ola20241247324    ┆ Machalová, Hana               ┆ 1     │
│ Mallowan, Agatha Christie,     ┆ jo20221171216     ┆ Lžička, Milan,                ┆ 1     │
│ La Hire, Jean de,              ┆ jn20031212003     ┆ Dubský, Ota,                  ┆ 1     │
│ Lamb, Stacey                   ┆ mzk20231185970    ┆ Vyskočil, Josef               ┆ 1     │
│ Novikov, Igor' Dmitrijevič,    ┆ xx0051663         ┆ Langer, Jiří,                 ┆ 1     │
│ Hyde, Aaron                    ┆ ola20231200680    ┆ Pavlová, Zuzana,              ┆ 1     │
│ Mann, Don,                     ┆ ola2015874847     ┆ Kubík, Zdeněk,                ┆ 1     │
│ Asanov, Nikolaj Aleksandrovič, ┆ jx20041103002     ┆ Neumann, Bohumil,             ┆ 1     │
│ Nix, Garth,                    ┆ xx0002179         ┆ Hejnová, Kateřina,            ┆ 1     │
│ Stangneth, Bettina,            ┆ zmp2013748098     ┆ Houda, Přemysl,               ┆ 1     │
│ Oseid, Kelsey                  ┆ xx0233728         ┆ Schlöglová, Eva               ┆ 1     │
│ Stone, Jean                    ┆ xx0036224         ┆ Černá, Hana,                  ┆ 1     │
│ Frank, Marisa                  ┆ jn20010309554     ┆ Savická, Stanislava           ┆ 1     │
│ Lorenz, Peter                  ┆ null              ┆ Hendrych, Antonín             ┆ 1     │
│ Thoreau, Sophie                ┆ xx0243216         ┆ Škopová, Barbara              ┆ 1     │
│ Slavíček, Jiří Vincenc,        ┆ jn19990209767     ┆ Koldus Frantová, Tereza,      ┆ 1     │
│ Blum, Howard                   ┆ null              ┆ Hošťálek, Stanislav           ┆ 1     │
│ Faber, Polly                   ┆ xx0223109         ┆ Nejedlá, Kateřina             ┆ 1     │
│ Elliott, Robin                 ┆ null              ┆ Zpěváčková, Jana              ┆ 1     │
│ Scott, Jennifer L.             ┆ xx0184560         ┆ Šavlíková, Lucie,             ┆ 1     │
│ Cain, Henri,                   ┆ kup20030000013154 ┆ Wenig, Adolf,                 ┆ 1     │
│ Tjutjunnyk, Hryhir             ┆ null              ┆ Bitzanová, Jaroslava          ┆ 1     │
│ Kern, Hans                     ┆ jn20001005047     ┆ Valášková, Magdalena,         ┆ 1     │
│ Nejedlíková, Pavlína           ┆ ola20201088814    ┆ Sverdan, Oksana               ┆ 1     │
│ McIntosh, Margo                ┆ jx20041029021     ┆ Benešovská-Horská, Anna Maria ┆ 1     │
│ Larsen, Reinhard,              ┆ mzk2004261046     ┆ Seidlová, Dagmar              ┆ 1     │
│ Lenormand, Frédéric,           ┆ mzk2006343198     ┆ Misařová, Vlasta,             ┆ 1     │
│ Bride, Nadja                   ┆ null              ┆ Štorkánová, Anna,             ┆ 1     │
└────────────────────────────────┴───────────────────┴───────────────────────────────┴───────┘

In [46]:
df.filter(pl.col('700_4') == 'ill').group_by('700_a').agg(pl.col("100_a").n_unique()).sort(by="100_a",descending=True)

shape: (13_657, 2)
┌─────────────────────────────────┬───────┐
│ 700_a                           ┆ 100_a │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Born, Adolf,                    ┆ 149   │
│ Bouda, Cyril,                   ┆ 114   │
│ Burian, Zdeněk,                 ┆ 112   │
│ Krejčová, Zdeňka,               ┆ 98    │
│ Svolinský, Karel,               ┆ 93    │
│ Aleš, Mikoláš,                  ┆ 80    │
│ Zmatlíková, Helena,             ┆ 80    │
│ Petráček, Jiří,                 ┆ 78    │
│ Jiránek, Vladimír,              ┆ 75    │
│ Slíva, Jiří,                    ┆ 73    │
│ Šplíchal, Antonín,              ┆ 73    │
│ Černý, Věnceslav,               ┆ 69    │
│ Plicková, Edita,                ┆ 67    │
│ Čuma, Aleš,                     ┆ 67    │
│ Thuma, Karel Ladislav,          ┆ 67    │
│ Procházka, Otakar               ┆ 65    │
│ Winter-Neprakta, Jiří,          ┆ 65    │
│ Teissig, Karel,                 ┆ 65    │
│ Komárek, Vladimír,              ┆ 61    │
│ Lhoták, Kamil,                  ┆ 61    │
│ Lada, Josef,                    ┆ 61    │
│ Janeček, Ota,                   ┆ 60    │
│ Urban, Petr,                    ┆ 60    │
│ Martenek, Miloslav,             ┆ 58    │
│ Kabát, Václav,                  ┆ 55    │
│ Černý, Jan,                     ┆ 55    │
│ Fixl, Jiří,                     ┆ 55    │
│ Tesař, Vladimír,                ┆ 53    │
│ Velčovský, Josef,               ┆ 53    │
│ Netopil, Zdeněk,                ┆ 53    │
│ Čutta, Václav,                  ┆ 52    │
│ Jakešová, Miroslava,            ┆ 52    │
│ Škoda, František,               ┆ 51    │
│ Duda, Stanislav,                ┆ 50    │
│ Trnka, Jiří,                    ┆ 49    │
│ Renčín, Vladimír,               ┆ 49    │
│ Čechová, Olga,                  ┆ 48    │
│ Kalousek, Jiří,                 ┆ 48    │
│ Váša, Miroslav,                 ┆ 46    │
│ Scheiner, Artuš,                ┆ 45    │
│ Konůpek, Jan,                   ┆ 45    │
│ Barták, Miroslav,               ┆ 44    │
│ Zpěvák, Karel                   ┆ 44    │
│ Nesvadba, Miloš,                ┆ 44    │
│ Kovařík, Jindřich,              ┆ 44    │
│ Jágr, Miloslav,                 ┆ 43    │
│ Anlauf, Lubomír,                ┆ 42    │
│ Franta, Karel,                  ┆ 42    │
│ Drobný, Libor,                  ┆ 42    │
│ Študlarová, Zdeňka,             ┆ 41    │
│ …                               ┆ …     │
│ Zykmundová, Alena               ┆ 1     │
│ Brückin, Nastassia              ┆ 1     │
│ Korthues, Barbara,              ┆ 1     │
│ Guillerat, Nicolas              ┆ 1     │
│ Gergeľová, Viera,               ┆ 1     │
│ Colón, Ernie,                   ┆ 1     │
│ Takeda, Wako,                   ┆ 1     │
│ Love, Mike                      ┆ 1     │
│ Dodds, Siobhan                  ┆ 1     │
│ Makovský, Zdeněk,               ┆ 1     │
│ Seo, Eunyoung                   ┆ 1     │
│ Titz, Petr,                     ┆ 1     │
│ Grafnetter, Antonín             ┆ 1     │
│ Winiecki, Marian                ┆ 1     │
│ Bořek, Josef                    ┆ 1     │
│ Štorm, Jiří                     ┆ 1     │
│ Tirso,                          ┆ 1     │
│ Waszek, Stanisław               ┆ 1     │
│ Rocher, Mathieu,                ┆ 1     │
│ Barlow, Lisa                    ┆ 1     │
│ Mais, Alan                      ┆ 1     │
│ Špic, Štefan,                   ┆ 1     │
│ Pijáček, František              ┆ 1     │
│ Tessier, Frédéric,              ┆ 1     │
│ Schubert, Otto,                 ┆ 1     │
│ Stránský, Jiří,                 ┆ 1     │
│ Vráblík, Jiří                   ┆ 1     │
│ Torseter, Øyvind,               ┆ 1     │
│ Guijarro, María Reyes           ┆ 1     │
│ Coufal, Ondřej,                 ┆ 1     │
│ Smrčková, Alena,                ┆ 1     │
│ Sembdner, František,            ┆ 1     │
│ Ashton-Jewell, Pythia           ┆ 1     │
│ Coleman, Stephanie Fizer        ┆ 1     │
│ Basařová, Tereza                ┆ 1     │
│ Marsden, Ian D.,                ┆ 1     │
│ Skružný, Zdeněk,                ┆ 1     │
│ Evans, Frances                  ┆ 1     │
│ Šabata, Karel                   ┆ 1     │
│ Vorlíčková, Irena               ┆ 1     │
│ Černý, Stanislav,               ┆ 1     │
│ Mörtl, Renate                   ┆ 1     │
│ Hvízdal, Josef,                 ┆ 1     │
│ Aguirre, Claudia                ┆ 1     │
│ Cingroš, Marian                 ┆ 1     │
│ García Hermosilla, Marta Anäis… ┆ 1     │
│ Černý, Bohuslav                 ┆ 1     │
│ Nevěčná, Alena,                 ┆ 1     │
│ Leialoha, Steve,                ┆ 1     │
│ Huard, Ch.                      ┆ 1     │
└─────────────────────────────────┴───────┘

In [47]:
nejaktivnejsi_ilustratori = df.filter(pl.col("stran") > 30).filter(pl.col('700_4') == 'ill').group_by('700_7').agg(pl.struct(["100_a","245_a"]).n_unique()).sort(by="100_a",descending=True).head(11).select(pl.col("700_7")).to_series().to_list()
nejaktivnejsi_ilustratori = [x for x in nejaktivnejsi_ilustratori if x != None]
nejaktivnejsi_ilustratori

['jk01012660',
 'jk01020396',
 'jk01083186',
 'jk01083128',
 'jk01012795',
 'jk01063265',
 'jk01152754',
 'jk01021645',
 'jk01132366',
 'ola2003162788']

In [48]:
def hezkejmeno(sto):
    if not sto[-1].isalnum():
        sto = sto[:-1]
    if "," in sto:
        sto = sto.split(",")
        sto = sto[1].strip() + " " + sto[0].strip()
    return sto

In [49]:
do_grafu2 = df.filter(pl.col('700_7').is_in(nejaktivnejsi_ilustratori)).with_columns(pl.col('700_a').map_elements(hezkejmeno)).with_columns(pl.col("rok").map_elements(lambda x: datetime.date(year=int(x), month=1, day=1), return_dtype=pl.Date).cast(pl.Datetime))
nejaktivnejsi_ilustratori2 = do_grafu2.group_by('700_a').agg(pl.struct(["100_a","245_a"]).n_unique()).sort(by="100_a",descending=True).head(10).select(pl.col("700_a")).to_series().to_list()
mrtvi_ilustratori = aut.explode("100_7").filter(pl.col('100_7').is_in(nejaktivnejsi_ilustratori)).explode("046_g").with_columns(pl.col("046_g").map_elements(lambda x: int(x)).alias("umrti")).select(pl.col(["100_7","umrti"])).filter(pl.col('umrti').is_between(1800,2025)).with_columns(pl.col("umrti").map_elements(lambda x: datetime.date(year=int(x), month=1, day=1), return_dtype=pl.Date).cast(pl.Datetime))
do_grafu2 = do_grafu2.join(mrtvi_ilustratori, how='left', left_on='700_7', right_on='100_7').join(
    do_grafu2.group_by('700_7').len(), on='700_7', how='left'
).with_columns(
    pl.col("len").map_elements(lambda x: str(x) + "×")
).with_columns(
    pl.concat_str([pl.col('len'), pl.col('700_a')], separator=' ').alias('700_a')
)
nejaktivnejsi_ilustratori2 = do_grafu2.group_by('700_a').len().sort(by='len',descending=True).select(pl.col('700_a')).to_series().to_list()

In [50]:
mrtvi_ilustratori

shape: (7, 2)
┌────────────┬─────────────────────┐
│ 100_7      ┆ umrti               │
│ ---        ┆ ---                 │
│ str        ┆ datetime[μs]        │
╞════════════╪═════════════════════╡
│ jk01012660 ┆ 2016-01-01 00:00:00 │
│ jk01012795 ┆ 1984-01-01 00:00:00 │
│ jk01020396 ┆ 1981-01-01 00:00:00 │
│ jk01021645 ┆ 1936-01-01 00:00:00 │
│ jk01132366 ┆ 1917-01-01 00:00:00 │
│ jk01083186 ┆ 2011-01-01 00:00:00 │
│ jk01152754 ┆ 2005-01-01 00:00:00 │
└────────────┴─────────────────────┘

In [51]:
nejaktivnejsi_ilustratori2

['457× Zdeněk Burian',
 '451× Helena Zmatlíková',
 '445× Adolf Born',
 '254× Antonín Šplíchal',
 '252× Cyril Bouda',
 '233× Jiří Winter-Neprakta',
 '204× Věnceslav Černý',
 '198× Zdeňka Krejčová',
 '197× Jaroslav Němeček',
 '169× Karel Ladislav Thuma']

In [52]:
do_grafu2.sample(5)

shape: (5, 70)
┌──────────┬──────────────────────┬───────────────┬───────────┬───┬──────────────┬───────┬──────────────────────┬──────┐
│ 100_ind1 ┆ 100_a                ┆ 100_7         ┆ 100_4     ┆ … ┆ rok          ┆ stran ┆ umrti                ┆ len  │
│ ---      ┆ ---                  ┆ ---           ┆ ---       ┆   ┆ ---          ┆ ---   ┆ ---                  ┆ ---  │
│ str      ┆ str                  ┆ str           ┆ list[str] ┆   ┆ datetime[μs] ┆ i64   ┆ datetime[μs]         ┆ str  │
╞══════════╪══════════════════════╪═══════════════╪═══════════╪═══╪══════════════╪═══════╪══════════════════════╪══════╡
│ 1        ┆ Grey, Zane,          ┆ jn19990002874 ┆ ["aut"]   ┆ … ┆ 1936-01-01   ┆ 218   ┆ 1981-01-01 00:00:00  ┆ 457× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Kocourek, Vítězslav, ┆ jk01060985    ┆ ["aut"]   ┆ … ┆ 2014-01-01   ┆ 193   ┆ 2005-01-01 00:00:00  ┆ 451× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Swift, Jonathan,     ┆ jn20000605232 ┆ ["aut"]   ┆ … ┆ 1990-01-01   ┆ 336   ┆ 1984-01-01 00:00:00  ┆ 252× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Čečetka, František   ┆ jk01021086    ┆ ["aut"]   ┆ … ┆ 2015-01-01   ┆ 386   ┆ 1936-01-01 00:00:00  ┆ 204× │
│          ┆ Josef,               ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
│ 1        ┆ Švandrlík, Miloslav, ┆ jk01131832    ┆ ["aut"]   ┆ … ┆ 2008-01-01   ┆ 271   ┆ 2011-01-01 00:00:00  ┆ 233× │
│          ┆                      ┆               ┆           ┆   ┆ 00:00:00     ┆       ┆                      ┆      │
└──────────┴──────────────────────┴───────────────┴───────────┴───┴──────────────┴───────┴──────────────────────┴──────┘

In [53]:
nejaktivnejsi_ilustratori2

['457× Zdeněk Burian',
 '451× Helena Zmatlíková',
 '445× Adolf Born',
 '254× Antonín Šplíchal',
 '252× Cyril Bouda',
 '233× Jiří Winter-Neprakta',
 '204× Věnceslav Černý',
 '198× Zdeňka Krejčová',
 '197× Jaroslav Němeček',
 '169× Karel Ladislav Thuma']

In [54]:
do_grafu2.sample(3)

shape: (3, 70)
┌──────────┬──────────────────┬────────────────┬───────────┬───┬──────────────┬───────┬─────────────────────┬──────┐
│ 100_ind1 ┆ 100_a            ┆ 100_7          ┆ 100_4     ┆ … ┆ rok          ┆ stran ┆ umrti               ┆ len  │
│ ---      ┆ ---              ┆ ---            ┆ ---       ┆   ┆ ---          ┆ ---   ┆ ---                 ┆ ---  │
│ str      ┆ str              ┆ str            ┆ list[str] ┆   ┆ datetime[μs] ┆ i64   ┆ datetime[μs]        ┆ str  │
╞══════════╪══════════════════╪════════════════╪═══════════╪═══╪══════════════╪═══════╪═════════════════════╪══════╡
│ 1        ┆ Trobl, Jaroslav  ┆ jk01140172     ┆ ["oth"]   ┆ … ┆ 1975-01-01   ┆ 92    ┆ 2016-01-01 00:00:00 ┆ 445× │
│          ┆                  ┆                ┆           ┆   ┆ 00:00:00     ┆       ┆                     ┆      │
│ 1        ┆ Jelínek, Jan,    ┆ jo200120086905 ┆ ["aut"]   ┆ … ┆ 1984-01-01   ┆ 56    ┆ 1981-01-01 00:00:00 ┆ 457× │
│          ┆                  ┆                ┆           ┆   ┆ 00:00:00     ┆       ┆                     ┆      │
│ 1        ┆ Štíplová, Ljuba, ┆ jk01131441     ┆ ["aut"]   ┆ … ┆ 2016-01-01   ┆ 64    ┆ null                ┆ 197× │
│          ┆                  ┆                ┆           ┆   ┆ 00:00:00     ┆       ┆                     ┆      │
└──────────┴──────────────────┴────────────────┴───────────┴───┴──────────────┴───────┴─────────────────────┴──────┘

In [163]:
base = alt.Chart(
    do_grafu2.filter(pl.col('700_a').is_in(nejaktivnejsi_ilustratori2)).to_pandas(), title=alt.TitleParams(
        f"{len(nejaktivnejsi_ilustratori2)} nejvydávanějších ilustrátorů a ilustrátorek (bez reprintů)",
    subtitle="Co tečka, to kniha. Černá čárka označuje rok úmrtí."))

kulicky = base.mark_circle(size=7, filled=True).encode(
            x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#DCDDD6')), 
            y=alt.Y("700_a:N", sort=nejaktivnejsi_ilustratori2, title=None, axis=alt.Axis(orient='left', domainOpacity=0, tickColor='white', labelExpr='split(datum.label, "× ")[1]' )), #, 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[3, 15])), 
            color=alt.Color('700_a:N', scale=alt.Scale(range=['#E09DA3']), 
                            sort=nejaktivnejsi_ilustratori2).legend(None)) \
        .transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

kdy_umreli = base.mark_tick(
    color='#292829',  # optional: you can specify color
    thickness=1.5,
    height=9
).encode(
    x=alt.X('umrti:T', title=None),
    y=alt.Y("700_a:N", sort=nejaktivnejsi_ilustratori2, title=None, axis=alt.Axis(orient='left', tickColor='white', labels=False)))

pocty = base.mark_text().encode(x=alt.X('rok:T', title=None), 
    y=alt.Y('700_a:N', title=None, sort=nejaktivnejsi_ilustratori2, axis=alt.Axis(orient="right", tickColor='white', labelExpr='split(datum.label, " ")[0]'))) #

zebricek2 = alt.layer(kulicky, kdy_umreli, pocty).configure_view(stroke='transparent').properties(
    width=kredity['sirka'] * 1.24,
    autosize={'type': 'fit', 'contains': 'padding'}
).resolve_scale(color='independent',x="shared")

zebricek2

alt.LayerChart(...)

In [165]:
me_to_neurazi(zebricek2, kredity=kredity['default'], soubor='02_ilustratorstvo')

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/02_ilustratorstvo.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/02_ilustratorstvo.svg" width="100%" alt="Omlouváme se, ale alternativní text se nepodařilo vygenerovat. Texty v grafu by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

In [57]:
df.filter(pl.col('700_a') == 'Born, Adolf,')

shape: (445, 68)
┌──────────┬────────────────────────────┬───────────────┬────────────────┬───┬───────────┬───────────┬──────┬───────┐
│ 100_ind1 ┆ 100_a                      ┆ 100_7         ┆ 100_4          ┆ … ┆ 700_9     ┆ 700_g     ┆ rok  ┆ stran │
│ ---      ┆ ---                        ┆ ---           ┆ ---            ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---   │
│ str      ┆ str                        ┆ str           ┆ list[str]      ┆   ┆ list[str] ┆ list[str] ┆ i64  ┆ i64   │
╞══════════╪════════════════════════════╪═══════════════╪════════════════╪═══╪═══════════╪═══════════╪══════╪═══════╡
│ 1        ┆ Steklač, Vojtěch,          ┆ jk01121138    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 2     │
│ 1        ┆ Drijverová, Martina,       ┆ jk01023067    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 69    │
│ 1        ┆ Shakespeare, William,      ┆ jn19981002129 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1993 ┆ 104   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 108   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1990 ┆ 88    │
│ 1        ┆ Hromádka, Jan              ┆ null          ┆ ["com"]        ┆ … ┆ null      ┆ null      ┆ 1974 ┆ 94    │
│ 1        ┆ Steklač, Vojtěch,          ┆ jk01121138    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1983 ┆ 33    │
│ 1        ┆ Horníček, Miroslav,        ┆ jk01042235    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1979 ┆ 249   │
│ 1        ┆ Novotná, Olga              ┆ jk01090625    ┆ ["com"]        ┆ … ┆ null      ┆ null      ┆ 1974 ┆ 92    │
│ 1        ┆ Shakespeare, William,      ┆ jn19981002129 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1966 ┆ 168   │
│ 1        ┆ Čapek, Karel,              ┆ jk01021023    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1975 ┆ 92    │
│ 1        ┆ Cervantes Saavedra, Miguel ┆ jn19990001383 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1981 ┆ 109   │
│          ┆ de,                        ┆               ┆                ┆   ┆           ┆           ┆      ┆       │
│ 1        ┆ Defoe, Daniel,             ┆ jn19990001679 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1986 ┆ 518   │
│ 1        ┆ Poe, Edgar Allan,          ┆ jn19990006608 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 199   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 157   │
│ 1        ┆ Páral, Vladimír,           ┆ jk01091743    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1978 ┆ 186   │
│ 1        ┆ Durrell, Gerald Malcolm,   ┆ jn19981000804 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1983 ┆ 157   │
│ 1        ┆ Hartog, Jan de,            ┆ jn20000602818 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1983 ┆ 216   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1991 ┆ 144   │
│ 1        ┆ Rudolf, Stanislav,         ┆ jk01103025    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1988 ┆ 132   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 91    │
│ 1        ┆ Kučera, Jan Pavel,         ┆ jn99240000579 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 68    │
│ 1        ┆ Steklač, Vojtěch,          ┆ jk01121138    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2009 ┆ 261   │
│ 1        ┆ Dickens, Charles,          ┆ jn19990001747 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 158   │
│ 1        ┆ Šmíd, Zdeněk,              ┆ jn19990209873 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 142   │
│ 1        ┆ Neff, Vladimír,            ┆ jk01082908    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1984 ┆ 288   │
│ 1        ┆ Durrell, Gerald Malcolm,   ┆ jn19981000804 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2013 ┆ 195   │
│ 1        ┆ Steklač, Vojtěch,          ┆ jk01121138    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2005 ┆ 197   │
│ 1        ┆ Hauff, Wilhelm,            ┆ jn19990003237 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1963 ┆ 255   │
│ 1        ┆ Hrnčíř, Svatopluk,         ┆ jk01042788    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 119   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2017 ┆ 47    │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 188   │
│ 1        ┆ Pavel, Ota,                ┆ jk01092027    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1979 ┆ 98    │
│ 1        ┆ Peisertová, Alena          ┆ jn20001005453 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 26    │
│ 1        ┆ Frýbová, Zdena,            ┆ jk01032058    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 246   │
│ 1        ┆ Drijverová, Martina,       ┆ jk01023067    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2019 ┆ 69    │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 147   │
│ 0        ┆ Jef a Besi                 ┆ jo2004244448  ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 38    │
│ 1        ┆ Hercíková, Iva,            ┆ jk01040797    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1980 ┆ 392   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 31    │
│ 1        ┆ Havlíček Borovský, Karel,  ┆ jk01040361    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2006 ┆ 36    │
│ 1        ┆ Dumas, Alexandre,          ┆ jn19990001907 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 3     │
│ 1        ┆ France, Anatole,           ┆ jn19981001227 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1978 ┆ 283   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 110   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1991 ┆ 87    │
│ 1        ┆ Říha, Bohumil,             ┆ jk01110164    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1982 ┆ 264   │
│ 1        ┆ Klaus, Václav,             ┆ jn19990218045 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1996 ┆ 390   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1982 ┆ 232   │
│ 1        ┆ Slabý, Zdeněk Karel,       ┆ jk01111713    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 103   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2002 ┆ 92    │
│ …        ┆ …                          ┆ …             ┆ …              ┆ … ┆ …         ┆ …         ┆ …    ┆ …     │
│ 1        ┆ Seifert, Jaroslav,         ┆ jk01110657    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 21    │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2023 ┆ 119   │
│ 1        ┆ Nepil, František,          ┆ jk01083177    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2004 ┆ 93    │
│ 1        ┆ Holcová, Milena,           ┆ jn99240000298 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 179   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2013 ┆ 65    │
│ 1        ┆ Gordon, Richard,           ┆ jn20000602113 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 275   │
│ 1        ┆ Taylor, David,             ┆ xx0028832     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 247   │
│ 1        ┆ Šrut, Pavel,               ┆ jk01131041    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 45    │
│ 1        ┆ Gregor, Achille,           ┆ jk01032611    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 215   │
│ 1        ┆ Gregor, Achille,           ┆ jk01032611    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1988 ┆ 381   │
│ 1        ┆ Sýkora, Pavel,             ┆ xx0008401     ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 223   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 63    │
│ 1        ┆ Berger, Thomas,            ┆ jn20010310095 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1995 ┆ 444   │
│ 1        ┆ Šulc, Ľudovít              ┆ xx0157097     ┆ ["com"]        ┆ … ┆ null      ┆ null      ┆ 1976 ┆ 94    │
│ 1        ┆ Doyle, Arthur Conan,       ┆ jn19990001842 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 253   │
│ 1        ┆ Janoušek, Miroslav,        ┆ jk01051075    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1978 ┆ 263   │
│ 1        ┆ Doyle, Arthur Conan,       ┆ jn19990001842 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 151   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2024 ┆ 223   │
│ 1        ┆ Nepil, František,          ┆ jk01083177    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2014 ┆ 92    │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 94    │
│ 1        ┆ Steklač, Vojtěch,          ┆ jk01121138    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2013 ┆ 409   │
│ 1        ┆ Šmíd, Zdeněk,              ┆ jn19990209873 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 151   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 106   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1998 ┆ 124   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 148   │
│ 1        ┆ Říha, Bohumil,             ┆ jk01110164    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 60    │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 94    │
│ 1        ┆ Branald, Adolf,            ┆ jk01012955    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1992 ┆ 319   │
│ 1        ┆ Steklač, Vojtěch,          ┆ jk01121138    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 332   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1985 ┆ 168   │
│ 1        ┆ Svěrák, Zdeněk,            ┆ jk01121890    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2012 ┆ 45    │
│ 1        ┆ Gregor, Achille,           ┆ jk01032611    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1991 ┆ 381   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1989 ┆ 139   │
│ 1        ┆ Macourek, Miloš,           ┆ jk01072813    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2000 ┆ 72    │
│ 1        ┆ Rudolf, Stanislav,         ┆ jk01103025    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1977 ┆ 222   │
│ 1        ┆ Říha, Bohumil,             ┆ jk01110164    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2015 ┆ 171   │
│ 1        ┆ Slabý, Zdeněk Karel,       ┆ jk01111713    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1972 ┆ 30    │
│ 1        ┆ Holoubek, Jaroslav,        ┆ jk01041772    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1990 ┆ 122   │
│ 1        ┆ Wodehouse, P. G.           ┆ jn19990009232 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2008 ┆ 215   │
│ 1        ┆ Vitula, Jiří,              ┆ jk01142558    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1983 ┆ 40    │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut", "com"] ┆ … ┆ null      ┆ null      ┆ 2016 ┆ 303   │
│ 1        ┆ Holcová, Milena,           ┆ jn99240000298 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2001 ┆ 195   │
│ 1        ┆ Lindgren, Astrid,          ┆ jn19990005095 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1999 ┆ 263   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1987 ┆ 152   │
│ 1        ┆ Dumas, Alexandre,          ┆ jn19990001907 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2003 ┆ 624   │
│ 1        ┆ Svěrák, Zdeněk,            ┆ jk01121890    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2022 ┆ 45    │
│ 1        ┆ Holcová, Milena,           ┆ jn99240000298 ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1997 ┆ 195   │
│ 1        ┆ Žáček, Jiří,               ┆ jk01152946    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2018 ┆ 12    │
│ 1        ┆ Drijverová, Martina,       ┆ jk01023067    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 1988 ┆ 59    │
│ 1        ┆ Frýbová, Zdena,            ┆ jk01032058    ┆ ["aut"]        ┆ … ┆ null      ┆ null      ┆ 2007 ┆ 237   │
└──────────┴────────────────────────────┴───────────────┴────────────────┴───┴───────────┴───────────┴──────┴───────┘

In [58]:
df.filter(pl.col('700_4') == 'ill').group_by('700_a').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (13_657, 2)
┌───────────────────────────┬───────┐
│ 700_a                     ┆ 245_a │
│ ---                       ┆ ---   │
│ str                       ┆ u32   │
╞═══════════════════════════╪═══════╡
│ Born, Adolf,              ┆ 281   │
│ Burian, Zdeněk,           ┆ 230   │
│ Němeček, Jaroslav,        ┆ 179   │
│ Bouda, Cyril,             ┆ 166   │
│ Zmatlíková, Helena,       ┆ 164   │
│ Winter-Neprakta, Jiří,    ┆ 160   │
│ Krejčová, Zdeňka,         ┆ 159   │
│ Šplíchal, Antonín,        ┆ 143   │
│ Thuma, Karel Ladislav,    ┆ 134   │
│ Černý, Věnceslav,         ┆ 133   │
│ Vydrová, Markéta,         ┆ 128   │
│ Plicková, Edita,          ┆ 124   │
│ Svolinský, Karel,         ┆ 123   │
│ Študlarová, Zdeňka,       ┆ 122   │
│ Lada, Josef,              ┆ 122   │
│ Aleš, Mikoláš,            ┆ 119   │
│ Petráček, Jiří,           ┆ 108   │
│ Popprová, Andrea          ┆ 103   │
│ Lhoták, Kamil,            ┆ 99    │
│ Scheiner, Artuš,          ┆ 97    │
│ Slíva, Jiří,              ┆ 93    │
│ Jiránek, Vladimír,        ┆ 88    │
│ Trnka, Jiří,              ┆ 87    │
│ Čuma, Aleš,               ┆ 85    │
│ Janeček, Ota,             ┆ 85    │
│ Hegerová, Vendula,        ┆ 84    │
│ Jakešová, Miroslava,      ┆ 84    │
│ Schulz, Alena,            ┆ 80    │
│ Wowk, Jiří,               ┆ 80    │
│ Tesař, Vladimír,          ┆ 79    │
│ Martenek, Miloslav,       ┆ 78    │
│ Fixl, Jiří,               ┆ 78    │
│ Velčovský, Josef,         ┆ 78    │
│ Čutta, Václav,            ┆ 76    │
│ Procházka, Otakar         ┆ 76    │
│ Kubašta, Vojtěch,         ┆ 75    │
│ Teissig, Karel,           ┆ 75    │
│ Kratochvíl, Zdeněk,       ┆ 74    │
│ Škoda, František,         ┆ 74    │
│ Komárek, Vladimír,        ┆ 73    │
│ Kabát, Václav,            ┆ 70    │
│ Hora, Jan,                ┆ 70    │
│ Poppr, Roman              ┆ 68    │
│ Čapek, Josef,             ┆ 68    │
│ Renčín, Vladimír,         ┆ 68    │
│ Franta, Karel,            ┆ 66    │
│ Netopil, Zdeněk,          ┆ 66    │
│ Urban, Petr,              ┆ 66    │
│ Konůpek, Jan,             ┆ 65    │
│ Kalousek, Jiří,           ┆ 65    │
│ …                         ┆ …     │
│ Leigh, Tom                ┆ 1     │
│ Šindler, Jiří             ┆ 1     │
│ Kmošek, Jiří,             ┆ 1     │
│ Štěpán, František,        ┆ 1     │
│ O'Brien, John,            ┆ 1     │
│ Mahdalová, Hana           ┆ 1     │
│ Höhmová, Zdena,           ┆ 1     │
│ Laburdová, Jaroslava,     ┆ 1     │
│ Forshaw, Louise           ┆ 1     │
│ Filip, Jiří               ┆ 1     │
│ Channell, Jim             ┆ 1     │
│ Libánská, Vlasta,         ┆ 1     │
│ Uesugi, Hikaru            ┆ 1     │
│ Strouhal, Hubert          ┆ 1     │
│ Dillon, Diane,            ┆ 1     │
│ Budík, Tomáš              ┆ 1     │
│ Johnsson, Karl,           ┆ 1     │
│ Janke, Vinzenz,           ┆ 1     │
│ Hilmerová, Olga           ┆ 1     │
│ Malátek, Jaroslav,        ┆ 1     │
│ Doubek, Michael,          ┆ 1     │
│ Sedlák, Josef,            ┆ 1     │
│ Pavlenko, Alexander,      ┆ 1     │
│ Luis Tichá Tužka          ┆ 1     │
│ Čapková, Eva,             ┆ 1     │
│ Krebsová-Sajdlová, Marie, ┆ 1     │
│ Šlégr, Oldřich            ┆ 1     │
│ Veris, Jaroslav,          ┆ 1     │
│ Obrovský, Jakub,          ┆ 1     │
│ Pond, Sandra              ┆ 1     │
│ Liwska, Renata            ┆ 1     │
│ Schubert, Otto,           ┆ 1     │
│ Rybová, Jaroslava,        ┆ 1     │
│ Vránová, Ludmila          ┆ 1     │
│ Gugliotti, Chris,         ┆ 1     │
│ Tišnovský, Jan            ┆ 1     │
│ Bourhis, Hervé,           ┆ 1     │
│ Dekan, Roman,             ┆ 1     │
│ Maršíková, Jana           ┆ 1     │
│ Yoon, David               ┆ 1     │
│ Veleva, Veronika,         ┆ 1     │
│ Sędziwy, Anna             ┆ 1     │
│ Krátká, Lenka             ┆ 1     │
│ Kameda, Bōsai,            ┆ 1     │
│ Tirsch, Ignác,            ┆ 1     │
│ Bartoš, Stanislav         ┆ 1     │
│ Cundrla, František        ┆ 1     │
│ Uhlířová, Marcela         ┆ 1     │
│ Hánlová, Yvetta,          ┆ 1     │
│ Hrbáčová, Anna            ┆ 1     │
└───────────────────────────┴───────┘

In [59]:
df_preklady = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","041.parquet")), left_on="001", right_on="001", how="left")

In [60]:
df_preklady.filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (18_202, 2)
┌────────────────────────────┬───────┐
│ 700_a                      ┆ 245_a │
│ ---                        ┆ ---   │
│ str                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ Butala, Tomáš,             ┆ 502   │
│ Pavka, Marek,              ┆ 429   │
│ Vyskočil, Josef            ┆ 344   │
│ Sladká, Stanislava         ┆ 246   │
│ Schönová, Zuzana           ┆ 234   │
│ Volhejnová, Veronika,      ┆ 230   │
│ Podaný, Richard,           ┆ 224   │
│ Kuťák, Jaroslav,           ┆ 214   │
│ Chromiaková, Eva           ┆ 196   │
│ Pacnerová, Jana,           ┆ 195   │
│ Štorkánová, Anna,          ┆ 179   │
│ Klůfová, Petra,            ┆ 164   │
│ Jašová, Jana,              ┆ 163   │
│ Dušek, Zdík,               ┆ 155   │
│ Kadlecová, Eva,            ┆ 148   │
│ Lacinová, Libuše,          ┆ 140   │
│ Řežábek, Rudolf,           ┆ 140   │
│ Pokorný, Martin,           ┆ 140   │
│ Dvořáková, Dagmar          ┆ 134   │
│ Kantůrek, Jan,             ┆ 130   │
│ Smolaková, Helena          ┆ 127   │
│ Kozák, Jan,                ┆ 126   │
│ Sychra, Pavel              ┆ 122   │
│ Führmann Vízdalová, Ivana, ┆ 119   │
│ Jovanovičová, Hana,        ┆ 118   │
│ Stachová, Helena,          ┆ 117   │
│ Stach, Jiří,               ┆ 117   │
│ Kufnerová, Zlata,          ┆ 117   │
│ Škultéty, Michaela,        ┆ 112   │
│ Žáček, Milan,              ┆ 111   │
│ Niklíčková, Alexandra,     ┆ 109   │
│ Vlčková, Jana,             ┆ 107   │
│ Somogyi, Viola,            ┆ 107   │
│ Weinfurter, Karel,         ┆ 106   │
│ Diestlerová, Petra,        ┆ 104   │
│ Nuhlíčková, Ivana,         ┆ 102   │
│ Heller, František          ┆ 102   │
│ Vinšová, Kateřina,         ┆ 102   │
│ Krejčí, Hana               ┆ 102   │
│ Hradil, Radomil,           ┆ 99    │
│ Brožová, Eva               ┆ 98    │
│ Faltejsková, Lenka,        ┆ 98    │
│ Schuster, R. K.            ┆ 95    │
│ Morávková, Alena,          ┆ 93    │
│ Novotná, Jana,             ┆ 92    │
│ Rada, Jan                  ┆ 92    │
│ Žák, Jiří,                 ┆ 92    │
│ Chodilová, Dana,           ┆ 92    │
│ Zábrana, Jan,              ┆ 91    │
│ Křivánková, Anna,          ┆ 89    │
│ …                          ┆ …     │
│ Víchová, Lenka,            ┆ 1     │
│ Bartoš, Pavel              ┆ 1     │
│ Tepper, Tomáš,             ┆ 1     │
│ Fiala, Jaroslav,           ┆ 1     │
│ Waloschek, Michael,        ┆ 1     │
│ Bajer, Petr                ┆ 1     │
│ Štefec, Rudolf             ┆ 1     │
│ Čermáková, Olga            ┆ 1     │
│ Mikyska, Martin            ┆ 1     │
│ Silná, Brigita             ┆ 1     │
│ Jandová, Lenka             ┆ 1     │
│ Herbrychová, Helena        ┆ 1     │
│ Randé, Karel,              ┆ 1     │
│ Havlíček, Petr             ┆ 1     │
│ Lichtenecker, K. E.        ┆ 1     │
│ Klauda, Petr               ┆ 1     │
│ Váňa, Alois                ┆ 1     │
│ Mensch, Joshua,            ┆ 1     │
│ Křížová, Kateřina,         ┆ 1     │
│ Bartošová, Heda            ┆ 1     │
│ Galuščáková, Klára         ┆ 1     │
│ Draxl, Václav,             ┆ 1     │
│ Rážová, Jana               ┆ 1     │
│ Mullin, Glenn H.,          ┆ 1     │
│ Svadbová, Blanka           ┆ 1     │
│ Rymeš, Patrik              ┆ 1     │
│ Nosek, Jiří,               ┆ 1     │
│ Hrbková, Ruth              ┆ 1     │
│ Bussinow, Petr             ┆ 1     │
│ Nevol, J.                  ┆ 1     │
│ Schwarzová, Jiřina         ┆ 1     │
│ Soukupová, Lenka           ┆ 1     │
│ Janovský, Emil,            ┆ 1     │
│ Jelínek, Martin,           ┆ 1     │
│ Johnová, Božena,           ┆ 1     │
│ Buchal, Petr               ┆ 1     │
│ Velechovská, Michaela,     ┆ 1     │
│ Vodžáková, Judita,         ┆ 1     │
│ Rubeš, Vladimír            ┆ 1     │
│ Mertl, Karel               ┆ 1     │
│ Vlasáková, Blanka          ┆ 1     │
│ Ter-Manuelianc, Antonín    ┆ 1     │
│ Vavroušek, Petr,           ┆ 1     │
│ Kovanský, Valentin         ┆ 1     │
│ Hampl, Mojmír,             ┆ 1     │
│ Trávníčková, Eliana,       ┆ 1     │
│ Vlček, Igor                ┆ 1     │
│ Boček, Pavel,              ┆ 1     │
│ Daniel, Jan                ┆ 1     │
│ Petrak, Nikica,            ┆ 1     │
└────────────────────────────┴───────┘

In [61]:
df_preklady.filter(pl.col('700_a') == "Butala, Tomáš,").group_by("100_a").len()

shape: (33, 2)
┌────────────────────────────┬─────┐
│ 100_a                      ┆ len │
│ ---                        ┆ --- │
│ str                        ┆ u32 │
╞════════════════════════════╪═════╡
│ Glaser, Frank              ┆ 9   │
│ Roberts, Dan,              ┆ 1   │
│ Silva, Tony,               ┆ 1   │
│ Robertson, Frank C.        ┆ 2   │
│ Aurel, Catherine,          ┆ 1   │
│ Unger, Gert F.,            ┆ 391 │
│ Morgan, Matt               ┆ 4   │
│ Hayes, Rex,                ┆ 13  │
│ Arnaldur Indriðason,       ┆ 5   │
│ Scott, William,            ┆ 141 │
│ Goga-Klinkenberg, Susanne, ┆ 4   │
│ Callahan, Frank            ┆ 2   │
│ Ryan, William              ┆ 4   │
│ Warner, Hal,               ┆ 1   │
│ Morton, Jack               ┆ 7   │
│ Schröder, Rainer M.,       ┆ 1   │
│ Mortimer, Glenn            ┆ 4   │
│ Taylor, Kathryn            ┆ 3   │
│ Shannon, Mark              ┆ 1   │
│ Czernin, Monika,           ┆ 1   │
│ Lane, Lex                  ┆ 4   │
│ Schiewe, Ulf,              ┆ 1   │
│ Gringel, Dana,             ┆ 1   │
│ Vermalle, Caroline,        ┆ 1   │
│ Denver, Jeff,              ┆ 1   │
│ Fargo, Bill                ┆ 4   │
│ Sharon, H. S.              ┆ 3   │
│ Bellmar, Elena,            ┆ 2   │
│ Sinclair, Luke             ┆ 8   │
│ Benson, Robert             ┆ 2   │
│ Murphy, Bill,              ┆ 10  │
│ Kutscher, Volker,          ┆ 10  │
│ Engel, Cornelia            ┆ 1   │
└────────────────────────────┴─────┘

In [62]:
df_preklady.filter(pl.col('700_a') == "Butala, Tomáš,").group_by("041_h").len()

shape: (5, 2)
┌───────────┬─────┐
│ 041_h     ┆ len │
│ ---       ┆ --- │
│ list[str] ┆ u32 │
╞═══════════╪═════╡
│ ["fre"]   ┆ 1   │
│ ["ice"]   ┆ 5   │
│ ["ger"]   ┆ 633 │
│ null      ┆ 2   │
│ ["eng"]   ┆ 3   │
└───────────┴─────┘

In [63]:
df_preklady.filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (18_202, 2)
┌─────────────────────────────────┬───────┐
│ 700_a                           ┆ 245_a │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Butala, Tomáš,                  ┆ 502   │
│ Pavka, Marek,                   ┆ 429   │
│ Vyskočil, Josef                 ┆ 344   │
│ Sladká, Stanislava              ┆ 246   │
│ Schönová, Zuzana                ┆ 234   │
│ Volhejnová, Veronika,           ┆ 230   │
│ Podaný, Richard,                ┆ 224   │
│ Kuťák, Jaroslav,                ┆ 214   │
│ Chromiaková, Eva                ┆ 196   │
│ Pacnerová, Jana,                ┆ 195   │
│ Štorkánová, Anna,               ┆ 179   │
│ Klůfová, Petra,                 ┆ 164   │
│ Jašová, Jana,                   ┆ 163   │
│ Dušek, Zdík,                    ┆ 155   │
│ Kadlecová, Eva,                 ┆ 148   │
│ Pokorný, Martin,                ┆ 140   │
│ Řežábek, Rudolf,                ┆ 140   │
│ Lacinová, Libuše,               ┆ 140   │
│ Dvořáková, Dagmar               ┆ 134   │
│ Kantůrek, Jan,                  ┆ 130   │
│ Smolaková, Helena               ┆ 127   │
│ Kozák, Jan,                     ┆ 126   │
│ Sychra, Pavel                   ┆ 122   │
│ Führmann Vízdalová, Ivana,      ┆ 119   │
│ Jovanovičová, Hana,             ┆ 118   │
│ Kufnerová, Zlata,               ┆ 117   │
│ Stachová, Helena,               ┆ 117   │
│ Stach, Jiří,                    ┆ 117   │
│ Škultéty, Michaela,             ┆ 112   │
│ Žáček, Milan,                   ┆ 111   │
│ Niklíčková, Alexandra,          ┆ 109   │
│ Somogyi, Viola,                 ┆ 107   │
│ Vlčková, Jana,                  ┆ 107   │
│ Weinfurter, Karel,              ┆ 106   │
│ Diestlerová, Petra,             ┆ 104   │
│ Vinšová, Kateřina,              ┆ 102   │
│ Nuhlíčková, Ivana,              ┆ 102   │
│ Heller, František               ┆ 102   │
│ Krejčí, Hana                    ┆ 102   │
│ Hradil, Radomil,                ┆ 99    │
│ Brožová, Eva                    ┆ 98    │
│ Faltejsková, Lenka,             ┆ 98    │
│ Schuster, R. K.                 ┆ 95    │
│ Morávková, Alena,               ┆ 93    │
│ Novotná, Jana,                  ┆ 92    │
│ Rada, Jan                       ┆ 92    │
│ Chodilová, Dana,                ┆ 92    │
│ Žák, Jiří,                      ┆ 92    │
│ Zábrana, Jan,                   ┆ 91    │
│ Křivánková, Anna,               ┆ 89    │
│ …                               ┆ …     │
│ Vavroušek, Petr,                ┆ 1     │
│ Grofová, Kateřina               ┆ 1     │
│ Srdínko, Otakar,                ┆ 1     │
│ Havránek, Tomáš,                ┆ 1     │
│ Bureš, Zdeněk,                  ┆ 1     │
│ Pačes, Václav,                  ┆ 1     │
│ Vitmanová, Martina              ┆ 1     │
│ Nehodová, Alena                 ┆ 1     │
│ Adámková, Věra                  ┆ 1     │
│ Grzeszek, Joanna                ┆ 1     │
│ Koblihová, Helena               ┆ 1     │
│ Humpal-Zemanová, Josefa,        ┆ 1     │
│ Mrázek, Jan                     ┆ 1     │
│ Bohatá, Daniela                 ┆ 1     │
│ Křesťanová, Pavla               ┆ 1     │
│ Ivancìv, Galyna Volodymyrìvna   ┆ 1     │
│ Sobotka, Ondřej                 ┆ 1     │
│ Budzová, Zuzana                 ┆ 1     │
│ Křehla, Ladislav,               ┆ 1     │
│ Hrabová, Libuše,                ┆ 1     │
│ Viceník, Pavel                  ┆ 1     │
│ Bělovský, Vítězslav,            ┆ 1     │
│ Svobodová, Jana                 ┆ 1     │
│ Pokorná, Alena,                 ┆ 1     │
│ Silva-Taroucová, Gisela,        ┆ 1     │
│ Ševčíková, Mirka,               ┆ 1     │
│ Profousová, Eva,                ┆ 1     │
│ Derev'janko, Vìra Igorìvna      ┆ 1     │
│ Bratršovská, Zdena,             ┆ 1     │
│ Szwarcbach, Bruno               ┆ 1     │
│ Lejsal, Tomáš                   ┆ 1     │
│ Kovář, Jiří                     ┆ 1     │
│ Kučerovská, Taťána,             ┆ 1     │
│ Hořký, Vladimír                 ┆ 1     │
│ Kaplánková, Barbora,1994-ola20… ┆ 1     │
│ Růžička, Lukáš,                 ┆ 1     │
│ Javůrková, Helena               ┆ 1     │
│ Somrová, Radmila                ┆ 1     │
│ Ficková, Renáta,                ┆ 1     │
│ Rotrekl, Teodor,                ┆ 1     │
│ Král, Petr                      ┆ 1     │
│ Plechanov, Anatolij             ┆ 1     │
│ Čapek, Jan Ladislav,            ┆ 1     │
│ Dobeš, Karel,                   ┆ 1     │
│ Poláková, Jenny,                ┆ 1     │
│ Bähr, Erich                     ┆ 1     │
│ Spurná, Michaela                ┆ 1     │
│ Kokyová, Iveta,                 ┆ 1     │
│ Kadlečková, Kateřina,           ┆ 1     │
│ Kohoutová, Alena                ┆ 1     │
└─────────────────────────────────┴───────┘

In [64]:
df_preklady.filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("stran").sum()).sort(by="stran",descending=True)

shape: (18_202, 2)
┌─────────────────────────────────┬────────┐
│ 700_a                           ┆ stran  │
│ ---                             ┆ ---    │
│ str                             ┆ i64    │
╞═════════════════════════════════╪════════╡
│ Volhejnová, Veronika,           ┆ 104086 │
│ Pacnerová, Jana,                ┆ 90284  │
│ Kantůrek, Jan,                  ┆ 80551  │
│ Podaný, Richard,                ┆ 76323  │
│ Dušek, Zdík,                    ┆ 68870  │
│ Jašová, Jana,                   ┆ 66951  │
│ Klůfová, Petra,                 ┆ 66769  │
│ Chodilová, Dana,                ┆ 56060  │
│ Medek, Pavel,                   ┆ 54195  │
│ Bartošková, Linda,              ┆ 53632  │
│ Řežábek, Rudolf,                ┆ 51852  │
│ Kobělka, Jiří,                  ┆ 50248  │
│ Pokorný, Martin,                ┆ 49472  │
│ Butala, Tomáš,                  ┆ 48256  │
│ Hron, Zdeněk,                   ┆ 45346  │
│ Zaorálek, Jaroslav,             ┆ 44751  │
│ Kotrle, Petr,                   ┆ 44222  │
│ Führmann Vízdalová, Ivana,      ┆ 43707  │
│ Krejčová, Dana                  ┆ 43672  │
│ Kozák, Jan,                     ┆ 43670  │
│ Faltejsková, Lenka,             ┆ 42989  │
│ Kadlecová, Eva,                 ┆ 42772  │
│ Trávníček, Luboš,               ┆ 42489  │
│ Kondrysová, Eva,                ┆ 41792  │
│ Ľalíková, Zuzana,               ┆ 41569  │
│ Žáček, Milan,                   ┆ 41130  │
│ Krištůfková, Kateřina,          ┆ 40202  │
│ Medek, Vladimír,                ┆ 39526  │
│ Jindrová, Alena,                ┆ 37979  │
│ Míček, Dalibor,                 ┆ 37961  │
│ Křivánková, Anna,               ┆ 37329  │
│ Trávníčková, Libuše,            ┆ 37257  │
│ Zábrana, Jan,                   ┆ 36956  │
│ Vlčková, Jana,                  ┆ 36700  │
│ Brožová, Eva                    ┆ 36699  │
│ Heller, František               ┆ 35764  │
│ Houbová, Věra,                  ┆ 35662  │
│ Moserová, Jaroslava,            ┆ 35535  │
│ Žák, Jiří,                      ┆ 35332  │
│ Weinfurter, Karel,              ┆ 34763  │
│ Stárková, Jiřina                ┆ 34565  │
│ Wolfová, Zora,                  ┆ 34555  │
│ Bičíková, Romana,               ┆ 34245  │
│ Křístková, Eva                  ┆ 34049  │
│ Nuhlíčková, Ivana,              ┆ 33785  │
│ Tilsch, Emanuel,                ┆ 33415  │
│ Marková, Michala,               ┆ 33354  │
│ Niklíčková, Alexandra,          ┆ 33232  │
│ Jindra, Miroslav,               ┆ 32742  │
│ Dvořák, Libor,                  ┆ 32490  │
│ …                               ┆ …      │
│ Pokorná, Alexandra              ┆ 1      │
│ Müller, Dušan                   ┆ 1      │
│ Irena                           ┆ 1      │
│ Petrunìna, Julìja Andrìjivna    ┆ 1      │
│ Fošum, Lukáš Jan,               ┆ 1      │
│ Geislerová, Gabriela            ┆ 1      │
│ Zavoral, Method Jan,            ┆ 1      │
│ Žůrek, Jiří,                    ┆ 1      │
│ Bubíková, Ráchel                ┆ 1      │
│ Kaszonyi, Pavol                 ┆ 1      │
│ Vavruška, Jindřich              ┆ 1      │
│ Matička, Vladimír               ┆ 1      │
│ Tenaud, Guillaume,              ┆ 1      │
│ Malicki, Jarosław               ┆ 1      │
│ Čadková, Daniela,               ┆ 1      │
│ Jiřičková, Marie,               ┆ 1      │
│ Metličková, Kristýna            ┆ 1      │
│ Rohoža, Anna Vìktorìvna         ┆ 1      │
│ Kubát, Miroslav,                ┆ 1      │
│ Zoban, Petr,                    ┆ 1      │
│ Kohnerová, Lucie                ┆ 1      │
│ Lukaštíková, Julie,             ┆ 1      │
│ Kim, Mina                       ┆ 1      │
│ Savčyn, Marìja-Mar'jana Volody… ┆ 1      │
│ Majer, Petr,                    ┆ 1      │
│ Uhlířová, Lucie                 ┆ 1      │
│ Prentis, Thomas                 ┆ 1      │
│ Horáček, Pavel,                 ┆ 1      │
│ Novotná, Eliška                 ┆ 1      │
│ Marx, Jakub                     ┆ 1      │
│ Vaněčková, Vladislava,          ┆ 1      │
│ Trnka, Jakub                    ┆ 1      │
│ Dudzik, Pavel                   ┆ 1      │
│ Maršálek, Zdenko,               ┆ 1      │
│ Podavka, Ondřej,                ┆ 1      │
│ Paraiová, Pavlína               ┆ 1      │
│ Phamová, Hau,                   ┆ 1      │
│ Velká, Tereza                   ┆ 1      │
│ Ochmanová, Taťána               ┆ 1      │
│ Austová, Veronika               ┆ 1      │
│ Nguy, Giang Linh                ┆ 1      │
│ Hofman, Petr,                   ┆ 1      │
│ Pol'ko, Ol'ga Volodymyrìvna     ┆ 1      │
│ Jezdinský, Jakub                ┆ 1      │
│ Dyčková, Alžběta,               ┆ 1      │
│ Hurt, Lukáš                     ┆ 1      │
│ Horníková, Pavlína              ┆ 1      │
│ Božek, Tomáš                    ┆ 1      │
│ Mostova, Julìja Mykolajivna     ┆ 1      │
│ Forejt, Matěj,                  ┆ 1      │
└─────────────────────────────────┴────────┘

In [65]:
df_preklady.filter(pl.col('700_a') == "Volhejnová, Veronika,").group_by("100_a").len().sort(by="len",descending=True)

shape: (106, 2)
┌────────────────────────┬─────┐
│ 100_a                  ┆ len │
│ ---                    ┆ --- │
│ str                    ┆ u32 │
╞════════════════════════╪═════╡
│ Kinney, Jeff,          ┆ 52  │
│ Christie, Agatha,      ┆ 29  │
│ Herbert, Frank,        ┆ 24  │
│ Walliams, David,       ┆ 21  │
│ Lewis, C. S.           ┆ 21  │
│ Green, John,           ┆ 17  │
│ Colfer, Chris,         ┆ 16  │
│ Le Carré, John,        ┆ 8   │
│ Morse, Brian,          ┆ 7   │
│ Grisham, John,         ┆ 6   │
│ Hannah, Sophie,        ┆ 6   │
│ Eason, Cassandra,      ┆ 5   │
│ Atkinson, Kate,        ┆ 5   │
│ Cunningham, Michael,   ┆ 5   │
│ Clarke, Arthur C.      ┆ 4   │
│ Peters, Helen          ┆ 4   │
│ Andrews, William W.    ┆ 4   │
│ Russell, Rachel Renée  ┆ 4   │
│ Daldry, Jeremy,        ┆ 4   │
│ Piers, Helen           ┆ 4   │
│ Herbert, Brian,        ┆ 3   │
│ Brown, Sandra,         ┆ 3   │
│ Crichton, Michael,     ┆ 3   │
│ Anderson, Poul,        ┆ 3   │
│ Novik, Naomi,          ┆ 3   │
│ Colfer, Eoin,          ┆ 3   │
│ Barnes, Jennifer Lynn, ┆ 3   │
│ Allison, Jennifer,     ┆ 3   │
│ Lamb, Kathryn,         ┆ 3   │
│ Asimov, Isaac,         ┆ 3   │
│ Smith, James,          ┆ 3   │
│ Mercree, Amy Leigh,    ┆ 2   │
│ Smale, Holly,          ┆ 2   │
│ Adeyemi, Tomi,         ┆ 2   │
│ McKinlay, Deborah      ┆ 2   │
│ Crouch, Blake,         ┆ 2   │
│ Thomson, Jamie,        ┆ 2   │
│ Rich, Roberta,         ┆ 2   │
│ Kalfař, Jaroslav,      ┆ 2   │
│ Johansen, Erika        ┆ 2   │
│ Levin, Ira,            ┆ 2   │
│ Chee, Traci            ┆ 2   │
│ Kaplický, Jan,         ┆ 2   │
│ Twain, Mark,           ┆ 2   │
│ George, Elizabeth,     ┆ 2   │
│ King, Andrew           ┆ 2   │
│ Kowitt, Holly          ┆ 1   │
│ Pessl, Marisha,        ┆ 1   │
│ Bryant, Dani           ┆ 1   │
│ Flinn, Alex,           ┆ 1   │
│ …                      ┆ …   │
│ Graham, Caroline,      ┆ 1   │
│ Garber, Joseph R.,     ┆ 1   │
│ Scott, Joanna,         ┆ 1   │
│ Laurie, Meshel,        ┆ 1   │
│ Quirk, Lawrence J.,    ┆ 1   │
│ Levithan, David,       ┆ 1   │
│ Fuller, Claire,        ┆ 1   │
│ Rennison, Louise,      ┆ 1   │
│ Kostova, Elizabeth,    ┆ 1   │
│ Hedsel, Mark,          ┆ 1   │
│ Winterson, Jeanette,   ┆ 1   │
│ Extence, Gavin,        ┆ 1   │
│ Neubauer, Bonnie       ┆ 1   │
│ Abrams, Stacey,        ┆ 1   │
│ Kissick, Lucy          ┆ 1   │
│ Kuttner, Henry,        ┆ 1   │
│ Brooks, Kevin,         ┆ 1   │
│ Setterfield, Diane,    ┆ 1   │
│ Ross, JoAnn            ┆ 1   │
│ Poe, Edgar Allan,      ┆ 1   │
│ Silverberg, Robert,    ┆ 1   │
│ Durrant, Sabine        ┆ 1   │
│ Cooper, Rose           ┆ 1   │
│ Lee, Suh Yoon          ┆ 1   │
│ Oula, Valerie          ┆ 1   │
│ Hubbard, L. Ron        ┆ 1   │
│ Arnold, Stephanie      ┆ 1   │
│ Cornell, Paul,         ┆ 1   │
│ Shaheen, Michael A.    ┆ 1   │
│ Kvítek, Martin,        ┆ 1   │
│ Zhang, Amy,            ┆ 1   │
│ Peterson, Jordan B.,   ┆ 1   │
│ Pollard, Michael,      ┆ 1   │
│ Michaels, Stase        ┆ 1   │
│ Mendell, Adrienne      ┆ 1   │
│ McIntyre, Anne,        ┆ 1   │
│ La Fontaine, Jean de,  ┆ 1   │
│ Nelson, Jandy,         ┆ 1   │
│ Donoghue, Emma,        ┆ 1   │
│ Jerome, Jerome K.      ┆ 1   │
│ Walls, Jeannette,      ┆ 1   │
│ Josephs, Ray           ┆ 1   │
│ Hornak, Francesca      ┆ 1   │
│ Delany, Samuel R.,     ┆ 1   │
│ Anderson, Kevin J.,    ┆ 1   │
│ Marshall, David        ┆ 1   │
│ Forleo, Marie          ┆ 1   │
│ Matheson, Richard,     ┆ 1   │
│ Piedilato, Janet       ┆ 1   │
│ Hearne, Kevin,         ┆ 1   │
└────────────────────────┴─────┘

In [66]:
df_preklady.explode("041_h").filter(pl.col('700_4') == 'trl').group_by('700_a').agg(pl.col("041_h").n_unique()).sort(by="041_h",descending=True)

shape: (18_202, 2)
┌───────────────────────────────┬───────┐
│ 700_a                         ┆ 041_h │
│ ---                           ┆ ---   │
│ str                           ┆ u32   │
╞═══════════════════════════════╪═══════╡
│ Babler, Otto František,       ┆ 19    │
│ Vetti, O. S.,                 ┆ 16    │
│ Hiršal, Josef,                ┆ 16    │
│ Bednář, Kamil,                ┆ 12    │
│ Vrchlický, Jaroslav,          ┆ 12    │
│ Fischer, Otokar,              ┆ 11    │
│ Vladislav, Jan,               ┆ 11    │
│ Sýs, Karel,                   ┆ 11    │
│ Žáček, Jiří,                  ┆ 11    │
│ Kosterka, Hugo,               ┆ 11    │
│ Žilina, Miloslav,             ┆ 11    │
│ Eisner, Pavel,                ┆ 10    │
│ Hrubín, František,            ┆ 10    │
│ Štroblová, Jana,              ┆ 9     │
│ Stankovský, Josef Jiří,       ┆ 9     │
│ Borecký, Jaromír,             ┆ 9     │
│ Hackenschmied, Hanuš,         ┆ 9     │
│ Karpatský, Dušan,             ┆ 9     │
│ Vyskočil, Josef               ┆ 8     │
│ Novotný, Václav Juda,         ┆ 8     │
│ Čvančara, Karel,              ┆ 8     │
│ Závada, Vilém,                ┆ 8     │
│ Zbavitel, Dušan,              ┆ 8     │
│ Vrátný, Karel,                ┆ 8     │
│ Weinfurter, Karel,            ┆ 8     │
│ Pešková, Eliška,              ┆ 8     │
│ Somogyi, Viola,               ┆ 8     │
│ Kubišta, Luděk,               ┆ 8     │
│ Renč, Václav,                 ┆ 8     │
│ Vacek, Jindřich,              ┆ 8     │
│ Sládek, Josef Václav,         ┆ 8     │
│ Pelán, Jiří,                  ┆ 8     │
│ Kundera, Ludvík,              ┆ 8     │
│ Pokorný, Jaroslav,            ┆ 8     │
│ Mertlík, Rudolf,              ┆ 8     │
│ Vrbová, Hana,                 ┆ 8     │
│ Šádek, František,             ┆ 8     │
│ Mathesius, Bohumil,           ┆ 8     │
│ Benešová, Naďa,               ┆ 7     │
│ Škultéty, Michaela,           ┆ 7     │
│ Mattuš, Jan,                  ┆ 7     │
│ Tůma, Petr                    ┆ 7     │
│ Koněrza, Josef,               ┆ 7     │
│ Stříž, Antonín Ludvík,        ┆ 7     │
│ Kühnl, Jan Baptist,           ┆ 7     │
│ Nowak, Antonín,               ┆ 7     │
│ Neumannová, Nina,             ┆ 7     │
│ Hrůša, Josef,                 ┆ 7     │
│ Mařík, Kamil,                 ┆ 7     │
│ Konůpek, Jiří,                ┆ 7     │
│ …                             ┆ …     │
│ Kociánová, Věra,              ┆ 1     │
│ Beneš, Viktor                 ┆ 1     │
│ Mach, Alexander,              ┆ 1     │
│ Pascual Suris, Mariana        ┆ 1     │
│ Spáčal, Lev                   ┆ 1     │
│ Livchotark, P. F.             ┆ 1     │
│ Šárecká-Radoňová, Maryša,     ┆ 1     │
│ Kamarýt, Jan,                 ┆ 1     │
│ Pražáková, Zdenka             ┆ 1     │
│ Steidlová, Dagmar,            ┆ 1     │
│ Škarková Drejslová, Kristýna, ┆ 1     │
│ Říha, Václav,                 ┆ 1     │
│ Parzan                        ┆ 1     │
│ Kašík, Milan                  ┆ 1     │
│ Vyskočilová, Eva,             ┆ 1     │
│ Umlauf, Michal                ┆ 1     │
│ Hučínová, Lucie               ┆ 1     │
│ Štouračová, Alena             ┆ 1     │
│ Sklenář, Karel,               ┆ 1     │
│ Pekař, Ladislav,              ┆ 1     │
│ Čapla, Nikola                 ┆ 1     │
│ Šimek, Josef Bohuslav,        ┆ 1     │
│ Tichá, Věra                   ┆ 1     │
│ Horák, Milan,                 ┆ 1     │
│ Zachar,                       ┆ 1     │
│ Esson, Mike,                  ┆ 1     │
│ Fischer, Lukáš                ┆ 1     │
│ Gottfriedová, Eliška          ┆ 1     │
│ Novosad, Lukáš,               ┆ 1     │
│ Bregha, František             ┆ 1     │
│ Hrušková, Karin,              ┆ 1     │
│ Staša, Michal                 ┆ 1     │
│ Kettner, Pavel                ┆ 1     │
│ Stehno, Bedřich,              ┆ 1     │
│ Povondrová, Eva               ┆ 1     │
│ Soukupová, Martina            ┆ 1     │
│ Häuslerová, E.                ┆ 1     │
│ Jáka, Jaroslav                ┆ 1     │
│ Janáková, Marie               ┆ 1     │
│ Jandík, Milan                 ┆ 1     │
│ Straková, Michaela            ┆ 1     │
│ Mašek, Gustav                 ┆ 1     │
│ Kalvodová, Dana,              ┆ 1     │
│ Thöndlová, Gabriela           ┆ 1     │
│ Heine, Ant.                   ┆ 1     │
│ Staňková, Ela                 ┆ 1     │
│ Pokorný, Jiří                 ┆ 1     │
│ Hybler, Martin,               ┆ 1     │
│ Vaněk, Miloš,                 ┆ 1     │
│ Berka, Ladislav Emil,         ┆ 1     │
└───────────────────────────────┴───────┘

In [67]:
df_preklady.filter(pl.col('700_a') == "Babler, Otto František,").group_by('041_h').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (20, 2)
┌─────────────────────────┬───────┐
│ 041_h                   ┆ 245_a │
│ ---                     ┆ ---   │
│ list[str]               ┆ u32   │
╞═════════════════════════╪═══════╡
│ ["eng"]                 ┆ 10    │
│ ["ger"]                 ┆ 9     │
│ ["fre"]                 ┆ 8     │
│ ["scr"]                 ┆ 5     │
│ null                    ┆ 5     │
│ ["hrv"]                 ┆ 3     │
│ ["ita"]                 ┆ 3     │
│ ["srp"]                 ┆ 2     │
│ ["bul"]                 ┆ 2     │
│ ["rus"]                 ┆ 2     │
│ ["und"]                 ┆ 2     │
│ ["lat"]                 ┆ 2     │
│ ["fre", "eng"]          ┆ 1     │
│ ["dut"]                 ┆ 1     │
│ ["hrv", "slv", … "mac"] ┆ 1     │
│ ["fro"]                 ┆ 1     │
│ ["pol"]                 ┆ 1     │
│ ["lit"]                 ┆ 1     │
│ ["slv"]                 ┆ 1     │
│ ["cze"]                 ┆ 1     │
└─────────────────────────┴───────┘

In [68]:
df_preklady.filter(pl.col('700_a') == "Hiršal, Josef,").group_by('041_h').agg(pl.col("245_a").n_unique()).sort(by="245_a",descending=True)

shape: (20, 2)
┌────────────────┬───────┐
│ 041_h          ┆ 245_a │
│ ---            ┆ ---   │
│ list[str]      ┆ u32   │
╞════════════════╪═══════╡
│ ["ger"]        ┆ 32    │
│ null           ┆ 12    │
│ ["por"]        ┆ 4     │
│ ["spa"]        ┆ 3     │
│ ["fre"]        ┆ 2     │
│ ["mul"]        ┆ 2     │
│ ["swe"]        ┆ 2     │
│ ["scr"]        ┆ 2     │
│ ["rum"]        ┆ 2     │
│ ["chi"]        ┆ 1     │
│ ["nor"]        ┆ 1     │
│ ["pal"]        ┆ 1     │
│ ["per"]        ┆ 1     │
│ ["por", "fre"] ┆ 1     │
│ ["rus"]        ┆ 1     │
│ ["scc"]        ┆ 1     │
│ ["eng"]        ┆ 1     │
│ ["hrv"]        ┆ 1     │
│ ["hun"]        ┆ 1     │
│ ["por", "eng"] ┆ 1     │
└────────────────┴───────┘